INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('13107495', NULL, 'Terminal Sageori', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.44357, 126.70022, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal sageori terminal sageori south korea kr terminal sageori,teomineolsageoli,터미널사거리',
    NOW(), NOW(), '13178243', NULL, 'Incheon-gwangyeoksi Sports Center', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.45289, 126.75059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheon-gwangyeoksi sports center incheon-gwangyeoksi sports center south korea kr incheon-gwangyeoksi sports center,incheongwang-yeogsiseupocheusenteo,인천광역시스포츠센터',
    NOW(), NOW(), '13190597', NULL, 'Incheonmichuhol-gu Sports Center', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.4626, 126.65055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheonmichuhol-gu sports center incheonmichuhol-gu sports center south korea kr incheonmichuhol-gu sports center,incheonmichuholguseupocheusenteo,인천미추홀구스포츠센터',
    NOW(), NOW(), '13196998', NULL, 'Jonghap Terminal Ipgusageori', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.43891, 126.69961, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'jonghap terminal ipgusageori jonghap terminal ipgusageori south korea kr jonghap terminal ipgusageori,jonghabteomineol-ibgusageoli,종합터미널입구사거리',
    NOW(), NOW(), '13197014', NULL, 'Incheonjonghap Bus Terminal', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.44171, 126.70156, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'incheonjonghap bus terminal incheonjonghap bus terminal south korea kr incheonjonghap bus terminal,incheonjonghabbeoseuteomineol,인천종합버스터미널',
    NOW(), NOW(), '13198940', NULL, 'HILLSTATE Harbor House Stay', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.46374, 126.63209, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hillstate harbor house stay hillstate harbor house stay south korea kr hillstate harbor house stay,hilseuteiteuhabeohauseuseutei,힐스테이트하버하우스스테이',
    NOW(), NOW(), '13223049', NULL, 'Songdo THE SHARP Harbor View Sipsam Danji Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39829, 126.64632, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo the sharp harbor view sipsam danji apartment songdo the sharp harbor view sipsam danji apartment south korea kr songdo the sharp harbor view 13 danji apartment,songdo the sharp harbor view sipsam danji apartment,songdodeosyabhabeobyu13danjiapateu,songdodeosyabhabeobyusibsamdanjiapateu,송도더샵하버뷰13단지아파트,송도더샵하버뷰십삼단지아파트',
    NOW(), NOW(), '13223059', NULL, 'Songdo Xi Harbor View Il Danji Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39642, 126.64152, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo xi harbor view il danji apartment songdo xi harbor view il danji apartment south korea kr songdo xi harbor view 1 danji apartment,songdo xi harbor view il danji apartment,songdojaihabeobyu1danjiapateu,songdojaihabeobyuildanjiapateu,송도자이하버뷰1단지아파트,송도자이하버뷰일단지아파트',
    NOW(), NOW(), '13223095', NULL, 'Songdo Xi Harbor View I Danji Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39531, 126.64299, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo xi harbor view i danji apartment songdo xi harbor view i danji apartment south korea kr songdo xi harbor view 2 danji apartment,songdo xi harbor view i danji apartment,songdojaihabeobyu2danjiapateu,songdojaihabeobyuidanjiapateu,송도자이하버뷰2단지아파트,송도자이하버뷰이단지아파트',
    NOW(), NOW(), '13223098', NULL, 'Songdo PRUGIO Harbor View Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39752, 126.63974, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo prugio harbor view apartment songdo prugio harbor view apartment south korea kr songdo prugio harbor view apartment,songdopuleujiohabeobyuapateu,송도푸르지오하버뷰아파트',
    NOW(), NOW(), '13223102', NULL, 'Songdo THE SHARP Harbor View Sibo Danji Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39787, 126.64324, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo the sharp harbor view sibo danji apartment songdo the sharp harbor view sibo danji apartment south korea kr songdo the sharp harbor view 15 danji apartment,songdo the sharp harbor view sibo danji apartment,songdodeosyabhabeobyu15danjiapateu,songdodeosyabhabeobyusib-odanjiapateu,송도더샵하버뷰15단지아파트,송도더샵하버뷰십오단지아파트',
    NOW(), NOW(), '13223128', NULL, 'Songdo THE SHARP Harbor View Sipsa Danji Apartment', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.39653, 126.64507, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'songdo the sharp harbor view sipsa danji apartment songdo the sharp harbor view sipsa danji apartment south korea kr songdo the sharp harbor view 14 danji apartment,songdo the sharp harbor view sipsa danji apartment,songdodeosyabhabeobyu14danjiapateu,songdodeosyabhabeobyusibsadanjiapateu,송도더샵하버뷰14단지아파트,송도더샵하버뷰십사단지아파트',
    NOW(), NOW(), '13234723', NULL, 'Incheonhang Cruise Terminal', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.42519, 126.59171, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'incheonhang cruise terminal incheonhang cruise terminal south korea kr incheonhang cruise terminal,incheonhangkeulujeuteomineol,인천항크루즈터미널',
    NOW(), NOW(), '13234729', NULL, 'Incheonhang Gukjeyeogaek Terminal', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.42395, 126.60552, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'incheonhang gukjeyeogaek terminal incheonhang gukjeyeogaek terminal south korea kr incheonhang gukjeyeogaek terminal,incheonhang-gugjeyeogaegteomineol,인천항국제여객터미널',
    NOW(), NOW(), '13234749', NULL, 'THE SHARP Songdo Marina Bay', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.41198, 126.61144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the sharp songdo marina bay the sharp songdo marina bay south korea kr the sharp songdo marina bay,deosyabsongdomalinabei,더샵송도마리나베이',
    NOW(), NOW(), '13240373', NULL, 'Songdo LNG Jonghap Sports Town Je Sa Jigu Yagujang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.3522, 126.58455, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'songdo lng jonghap sports town je sa jigu yagujang songdo lng jonghap sports town je sa jigu yagujang south korea kr songdo lng jonghap sports town je 4 jigu yagujang,songdo lng jonghap sports town je sa jigu yagujang,songdo-el-enjijonghabseupocheutaunjesajiguyagujang,songdolngjonghabseupocheutaunje4jiguyagujang,송도lng종합스포츠타운제4지구야구장,송도엘엔지종합스포츠타운제사지구야구장',
    NOW(), NOW(), '13240434', NULL, 'Songdo LNG Jonghap Sports Town', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.35278, 126.61622, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'songdo lng jonghap sports town songdo lng jonghap sports town south korea kr songdo lng jonghap sports town,songdo-el-enjijonghabseupocheutaun,songdolngjonghabseupocheutaun,송도lng종합스포츠타운,송도엘엔지종합스포츠타운',
    NOW(), NOW(), '13240445', NULL, 'Incheon Sinhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.34414, 126.63173, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheon sinhang incheon sinhang south korea kr incheon sinhang,incheonsinhang,인천신항',
    NOW(), NOW(), '13240449', NULL, 'Incheon Hwan-gyeonggongdan Songdo Sports Center', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.35116, 126.61843, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheon hwan-gyeonggongdan songdo sports center incheon hwan-gyeonggongdan songdo sports center south korea kr incheon hwan-gyeonggongdan songdo sports center,incheonhwangyeong-gongdansongdoseupocheusenteo,인천환경공단송도스포츠센터',
    NOW(), NOW(), '13512609', NULL, 'Ulsan Port', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.31894, 129.22264, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ulsan port ulsan port south korea kr',
    NOW(), NOW(), '1222385', NULL, 'Pelabuhan Bass', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.31667, 99.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan bass pelabuhan bass malaysia my bass harbour,pelabohan bass,pelabuhan bass',
    NOW(), NOW(), '1732687', NULL, 'Batu Pahat', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.8548, 102.9325, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'batu pahat batu pahat malaysia my bp,bandar penggaram,batu pahat',
    NOW(), NOW(), '1732696', NULL, 'Ayer Hitam', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.915, 103.1808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ayer hitam ayer hitam malaysia my air hitam,ayer hitam,bandar seramik',
    NOW(), NOW(), '1732716', NULL, 'Bandar Permas', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.3355, 103.4575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar permas bandar permas malaysia my bandar permas',
    NOW(), NOW(), '1732738', NULL, 'Kota Tinggi', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.7381, 103.8999, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'kota tinggi kota tinggi malaysia my bandar kota tinggi,kota tinggi,kota tuiggi',
    NOW(), NOW(), '1732863', NULL, 'Bandar Sungai Mati', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.1467, 102.5655, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar sungai mati bandar sungai mati malaysia my bandar sungai mati,death river,sungai mati',
    NOW(), NOW(), '1732869', NULL, 'Muar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.0442, 102.5689, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'muar muar malaysia my bandar maharani,muar,muar town,ma po,муар,麻坡',
    NOW(), NOW(), '1732905', NULL, 'Klang', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    3.03667, 101.44333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'klang klang malaysia my kelang,klang,klangas,klanq,port kelang,ba sheng,ba sheng shi,kalanga,keullang,killan,klagh,klaj,klam,klang,klang syty,kuran,qlng,келанг,кланг,קלנג,كلاج,كلاغ,کلانگ,کلانگ سیتی,कलंग,ক্লাং,கிள்ளான்,クラン,巴生,巴生市,클랑',
    NOW(), NOW(), '1733321', NULL, 'Pelabuhan Labuan', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.27226, 115.24152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan labuan pelabuhan labuan malaysia my pelabuhan labuan,victoria harbour',
    NOW(), NOW(), '1733362', NULL, 'Telukan Kimanis', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.621, 115.7349, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan kimanis telukan kimanis malaysia my kimanis bay,teluk kimanis,telukan kimanis',
    NOW(), NOW(), '1733615', NULL, 'Telukan Lahad Datu', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.76761, 118.64151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan lahad datu telukan lahad datu malaysia my darvel bay,teluk darvel,teluk lahad datu,telukan lahad datu',
    NOW(), NOW(), '1733655', NULL, 'Telukan Tambak', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.9304, 118.5653, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan tambak telukan tambak malaysia my kennedy bay,teluk kennedy,telukan tambak',
    NOW(), NOW(), '1734025', NULL, 'Telukan Utara', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.7948, 117.995, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan utara telukan utara malaysia my north bay,teluk utara,telukan utara',
    NOW(), NOW(), '1734027', NULL, 'Telukan Dalam', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.7628, 117.9314, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan dalam telukan dalam malaysia my inner bay,teluk dalam,telukan dalam',
    NOW(), NOW(), '1734029', NULL, 'Telukan Sekong', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.7048, 117.9613, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'telukan sekong telukan sekong malaysia my sekong bay,teluk sekong,telukan sekong',
    NOW(), NOW(), '1734051', NULL, 'Pelabuhan Sandakan', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.81645, 118.12384, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan sandakan pelabuhan sandakan malaysia my pelabuhan sandakan,sandakan harbour',
    NOW(), NOW(), '1734114', NULL, 'Bandar Nabawan', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.0393, 116.4274, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bandar nabawan bandar nabawan malaysia my bandar nabawan,nabawan,nebawan',
    NOW(), NOW(), '1734219', NULL, 'Pelabuhan Cowie', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.3243, 117.6821, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan cowie pelabuhan cowie malaysia my cowie bay,cowie harbour,pelabuhan cowie',
    NOW(), NOW(), '1734406', NULL, 'Bandar Baharu', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.23007, 100.6068, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar baharu bandar baharu malaysia my bandar baharu,bandar bahru,daerah bandar baharu',
    NOW(), NOW(), '1734407', NULL, 'Bandar Baharu', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.13428, 100.49549, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bandar baharu bandar baharu malaysia my bandar baharu,bandar bahru,bandar bharu',
    NOW(), NOW(), '1734503', NULL, 'Kuching International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.4847, 110.34693, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'kuching international airport kuching international airport malaysia my aeroporto internazionale di kuching,aeroportul international kuching,aeroportul internațional kuching,aeropuerto internacional de kuching,bandar udara internasional kuching,flughafen kuching,kch,kia,kuching international airport,kuching uluslararasi havalimani,kuching uluslararası havalimanı,kuchingin kansainvaelinen lentoasema,kuchingin kansainvälinen lentoasema,lapangan terbang antarabangsa kuching,mezhdunarodnyj aehroport kuching,mezinarodni letiste kuching,mezinárodní letiště kuching,port lotniczy kuching,san bay quoc te kuching,sân bay quốc tế kuching,wbgg,aeroport international de kuching,aéroport international de kuching,frwdgah byn‌almlly kwchyng,gu jin guo ji ji chang,kuccin pannattu vanurti nilaiyam,kuchin guo ji kong gang,kuching gugjegonghang,tha xakasyan nanachati ku ching,международный аэропорт кучинг,фурудгоҳи бин‌алмилалӣ кучинг,فرودگاه بین‌المللی کوچینگ,கூச்சிங் பன்னாட்டு வானூர்தி நிலையம்,ท่าอากาศยานนานาชาติกูชิง,クチン国際空港,古晉國際機場,古晋国际机场,쿠칭 국제공항',
    NOW(), NOW(), '1734586', NULL, 'Taiping', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.85, 100.73333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'taiping taiping malaysia my bandar taiping,tpg,taipeng,taiping,taipingo,tajpin,tai ping,taipin,taiping,taippin,тайпин,தைப்பிங்,タイピン,太平,타이핑',
    NOW(), NOW(), '1734588', NULL, 'Kampung Sepetang', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.83333, 100.63333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung sepetang kampung sepetang malaysia my kampung sepetang,port weld,port wend,sapetang',
    NOW(), NOW(), '1734676', NULL, 'Kampung Belukar Bukit', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.8952, 102.9978, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung belukar bukit kampung belukar bukit malaysia my kampung belukar bukit',
    NOW(), NOW(), '1734705', NULL, 'Kuala Terengganu', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.3302, 103.1408, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'kuala terengganu kuala terengganu malaysia my bandar kuala terengganu,kuala terenganu,kuala terengganu,kuala trengganu,kuala-trenganu,kuala-trengganu,kvala terenganu,tgg,trengganu,tringano,tringganu,gua la deng jia lou,kaw la trang kanu,kuallateuleng-ganu,kuaratorenganu,kwala trnghanw,kwala tyrnganw,куала теренгану,куала теренггану,куала-тренгану,куала-тренггану,كوالا ترنغانو,کوالا تیرنگانو,กัวลาตรังกานู,クアラトレンガヌ,瓜拉登嘉楼,쿠알라트렝가누',
    NOW(), NOW(), '1734759', NULL, 'Malacca', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.196, 102.2405, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'malacca malacca malaysia my bandaraya melaka,mkz,malaca,malacca,malacca town,malaka,malakka,melaka,ma liu jia,marakka,малакка,マラッカ,马六甲',
    NOW(), NOW(), '1734769', NULL, 'Pelabuhan Klang', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.99959, 101.39287, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'pelabuhan klang pelabuhan klang malaysia my pelabohan klang,pelabuhan kelang,pelabuhan kelang selatan,pelabuhan klang,port kalang,port kelang,port klang,port sweetenham,port swettenham',
    NOW(), NOW(), '1734777', NULL, 'Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.86367, 101.45803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar malaysia my',
    NOW(), NOW(), '1734815', NULL, 'Port Dickson', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.52462, 101.79651, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port dickson port dickson malaysia my arang arang anchorage,arang-arang,port dickson',
    NOW(), NOW(), '1734816', NULL, 'Daerah Port Dickson', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.5, 101.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'daerah port dickson daerah port dickson malaysia my coast,daerah port dickson',
    NOW(), NOW();