INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('6702516', NULL, 'Bandar Lampahan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.74, 96.7777, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar lampahan bandar lampahan indonesia id bandar lampahan',
    NOW(), NOW(), '6702517', NULL, 'Bandarseilan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.5874, 96.9225, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarseilan bandarseilan indonesia id bandarseilan',
    NOW(), NOW(), '6702549', NULL, 'Blok Delapan Puluh', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.7471, 96.7818, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blok delapan puluh blok delapan puluh indonesia id bandarlampahan,blok 80,blok delapan puluh',
    NOW(), NOW(), '6703034', NULL, 'Bandar Tinggi', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.7242, 98.2473, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar tinggi bandar tinggi indonesia id bandar tinggi',
    NOW(), NOW(), '6703103', NULL, 'Bandartengah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.6162, 98.1283, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandartengah bandartengah indonesia id bandartengah',
    NOW(), NOW(), '6703136', NULL, 'Bandarmeriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5409, 98.1472, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarmeriah bandarmeriah indonesia id bandarmeriah',
    NOW(), NOW(), '6703137', NULL, 'Bandarmeriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5394, 98.154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarmeriah bandarmeriah indonesia id bandarmeriah',
    NOW(), NOW(), '6703139', NULL, 'Bandar Pulung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5349, 98.1708, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar pulung bandar pulung indonesia id bandar pulung',
    NOW(), NOW(), '6703167', NULL, 'Bandar Bunga', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5054, 98.21, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bunga bandar bunga indonesia id bandar bunga',
    NOW(), NOW(), '6703556', NULL, 'Bandar Minggu', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.0459, 99.7419, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar minggu bandar minggu indonesia id bandar minggu',
    NOW(), NOW(), '6703776', NULL, 'Bandardua', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.2546, 97.1733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandardua bandardua indonesia id bandardua',
    NOW(), NOW(), '6703792', NULL, 'Kapalabandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.2954, 97.153, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kapalabandar kapalabandar indonesia id kapalabandar',
    NOW(), NOW(), '6704369', NULL, 'Dolok Palaliman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.5043, 98.9772, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dolok palaliman dolok palaliman indonesia id dolok palaliman',
    NOW(), NOW(), '6706105', NULL, 'Bandar Meriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.08294, 98.40744, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar meriah bandar meriah indonesia id bandar meriah',
    NOW(), NOW(), '6706610', NULL, 'Bandarsenembah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.6016, 98.468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarsenembah bandarsenembah indonesia id bandarsenembah,bandarsinombah',
    NOW(), NOW(), '6706654', NULL, 'Bandarsakti', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5771, 98.3508, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarsakti bandarsakti indonesia id bandarsakti',
    NOW(), NOW(), '6706688', NULL, 'Bandar Muda', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5429, 98.2576, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar muda bandar muda indonesia id bandar muda',
    NOW(), NOW(), '6706727', NULL, 'Bandar Meriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5173, 98.4674, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar meriah bandar meriah indonesia id bandar meriah',
    NOW(), NOW(), '6706802', NULL, 'Bandarbingai', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5649, 98.4473, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarbingai bandarbingai indonesia id bandarbingai',
    NOW(), NOW(), '6706917', NULL, 'Pulau Kalimantung Na Godang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.5751, 98.5262, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pulau kalimantung na godang pulau kalimantung na godang indonesia id pulau kalimantang,pulau kalimantung na godang,pulau kalmantungnagodang',
    NOW(), NOW(), '6706926', NULL, 'Pulau Kalimantung Na Menek', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.5617, 98.5761, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pulau kalimantung na menek pulau kalimantung na menek indonesia id pulau kalimantung na menek',
    NOW(), NOW(), '6707218', NULL, 'Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.9599, 99.0253, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar indonesia id bandar',
    NOW(), NOW(), '6707370', NULL, 'Bandar Dolok', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.8252, 99.0321, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar dolok bandar dolok indonesia id bandar dolok',
    NOW(), NOW(), '6707648', NULL, 'Ujung Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.9124, 99.236, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ujung bandar ujung bandar indonesia id ujung bandar',
    NOW(), NOW(), '6707680', NULL, 'Aek Liman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.7992, 99.2254, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aek liman aek liman indonesia id aek liman',
    NOW(), NOW(), '6708631', NULL, 'Krueng Aliman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    5.0999, 96.0151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'krueng aliman krueng aliman indonesia id krueng aliman',
    NOW(), NOW(), '6710259', NULL, 'Burni Bandara', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.39404, 97.68459, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'burni bandara burni bandara indonesia id burni bandara,gunung bandara',
    NOW(), NOW(), '6710486', NULL, 'Bandar Meriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.432, 98.4925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar meriah bandar meriah indonesia id bandar meriah',
    NOW(), NOW(), '6710490', NULL, 'Bandar Kuala', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.4318, 98.4632, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar kuala bandar kuala indonesia id bandar kuala',
    NOW(), NOW(), '6710552', NULL, 'Bandar Kuala', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.3894, 98.2882, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar kuala bandar kuala indonesia id bandar kuala',
    NOW(), NOW(), '6710565', NULL, 'Ujung Bandak', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.382, 98.3259, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ujung bandak ujung bandak indonesia id ujung bandak,ujungbandar',
    NOW(), NOW(), '6710578', NULL, 'Bandar Meriah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.3679, 98.48, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar meriah bandar meriah indonesia id bandar meriah',
    NOW(), NOW(), '6711578', NULL, 'Suak Lukahe', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.9863, 96.669, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'suak lukahe suak lukahe indonesia id suak lukahe',
    NOW(), NOW(), '6711777', NULL, 'Bandarchalifah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.8078, 97.8422, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarchalifah bandarchalifah indonesia id bandarchalifah',
    NOW(), NOW(), '6711802', NULL, 'Byah Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.9421, 97.7674, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'byah bandar byah bandar indonesia id byah bandar',
    NOW(), NOW(), '6712480', NULL, 'Bandarlampahan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.7557, 96.7716, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarlampahan bandarlampahan indonesia id bandarlampahan',
    NOW(), NOW(), '6712826', NULL, 'Bandar Baru', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.4137, 98.174, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar baru bandar baru indonesia id bandar baru',
    NOW(), NOW(), '6712829', NULL, 'Bandarkhalipat', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.4154, 98.1634, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarkhalipat bandarkhalipat indonesia id bandarkhalipat',
    NOW(), NOW(), '6712957', NULL, 'Bandar Mahligai', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.2749, 98.0295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar mahligai bandar mahligai indonesia id bandar mahligai,bandarmeligai',
    NOW(), NOW(), '6713219', NULL, 'Limang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.1217, 98.2378, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limang limang indonesia id limang',
    NOW(), NOW(), '6713656', NULL, 'Bandarbaru', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.5741, 96.9583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarbaru bandarbaru indonesia id bandarbaru',
    NOW(), NOW(), '6714070', NULL, 'Belukar Blang Kulem', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.7751, 97.1502, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belukar blang kulem belukar blang kulem indonesia id belukar blang kulem',
    NOW(), NOW(), '6714707', NULL, 'Bandar Baru', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.9719, 97.6089, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar baru bandar baru indonesia id bandar baru',
    NOW(), NOW(), '6715068', NULL, 'Krueng Seulukat', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.8923, 97.5784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'krueng seulukat krueng seulukat indonesia id krueng seulukat',
    NOW(), NOW(), '6715182', NULL, 'Bangunbandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.2721, 99.0447, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bangunbandar bangunbandar indonesia id bangunbandar',
    NOW(), NOW(), '6715188', NULL, 'Bandarpadang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.3369, 99.1062, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarpadang bandarpadang indonesia id bandarpadang',
    NOW(), NOW(), '6715189', NULL, 'Bandarlawan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.3434, 99.1372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarlawan bandarlawan indonesia id bandarlawan',
    NOW(), NOW(), '6715193', NULL, 'Bandar Dalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.3749, 99.24, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar dalam bandar dalam indonesia id bandar dalam',
    NOW(), NOW(), '6715248', NULL, 'Bandarbaru', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.4061, 98.2197, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarbaru bandarbaru indonesia id bandarbaru',
    NOW(), NOW(), '6715254', NULL, 'Gunung Sibandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.344, 98.1935, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gunung sibandar gunung sibandar indonesia id gunung sibandar',
    NOW(), NOW();