INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12487249', NULL, 'Desa Bandar Agung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.23167, 104.35806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar agung desa bandar agung indonesia id desa bandar agung',
    NOW(), NOW(), '12487266', NULL, 'Kecamatan Bandar Negeri Suoh', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.17167, 104.26583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kecamatan bandar negeri suoh kecamatan bandar negeri suoh indonesia id kecamatan bandar negeri suoh',
    NOW(), NOW(), '12487371', NULL, 'Desa Bandar Aji Jaya', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.23417, 105.56306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar aji jaya desa bandar aji jaya indonesia id desa bandar aji jaya',
    NOW(), NOW(), '12487387', NULL, 'Desa Gedung Bandar Rahayu', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.37056, 105.65417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa gedung bandar rahayu desa gedung bandar rahayu indonesia id desa gedung bandar rahayu',
    NOW(), NOW(), '12487391', NULL, 'Desa Gedung Bandar Rejo', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.40722, 105.64306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa gedung bandar rejo desa gedung bandar rejo indonesia id desa gedung bandar rejo',
    NOW(), NOW(), '12487561', NULL, 'Desa Bandar Kejadian', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.49278, 104.55389, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar kejadian desa bandar kejadian indonesia id desa bandar kejadian',
    NOW(), NOW(), '12487785', NULL, 'Desa Bandar Sukabumi', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.4425, 104.495, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar sukabumi desa bandar sukabumi indonesia id desa bandar sukabumi',
    NOW(), NOW(), '12487833', NULL, 'Kecamatan Bandar Negeri Semuong', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.42139, 104.47083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kecamatan bandar negeri semuong kecamatan bandar negeri semuong indonesia id kecamatan bandar negeri semuong',
    NOW(), NOW(), '12487860', NULL, 'Desa Bandar Negeri', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.405, 105.81222, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar negeri desa bandar negeri indonesia id desa bandar negeri',
    NOW(), NOW(), '12488026', NULL, 'Desa Bandar Agung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.29833, 105.67833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar agung desa bandar agung indonesia id desa bandar agung',
    NOW(), NOW(), '12488102', NULL, 'Kecamatan Bandar Sribhawono', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.27556, 105.68444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kecamatan bandar sribhawono kecamatan bandar sribhawono indonesia id kecamatan bandar sribhawono',
    NOW(), NOW(), '12488172', NULL, 'Desa Bandar Agung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.87528, 104.46083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar agung desa bandar agung indonesia id desa bandar agung',
    NOW(), NOW(), '12488230', NULL, 'Desa Bandar Dalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.58028, 104.62806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar dalam desa bandar dalam indonesia id desa bandar dalam',
    NOW(), NOW(), '12488245', NULL, 'Desa Bandar Kasih', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.56972, 104.66611, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar kasih desa bandar kasih indonesia id desa bandar kasih',
    NOW(), NOW(), '12488254', NULL, 'Desa Bandar Sari', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.41472, 104.36333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar sari desa bandar sari indonesia id desa bandar sari',
    NOW(), NOW(), '12488771', NULL, 'Desa Sidang Bandar Anom', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.18, 105.6675, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa sidang bandar anom desa sidang bandar anom indonesia id desa sidang bandar anom',
    NOW(), NOW(), '12488847', NULL, 'Desa Bandar Dewa', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.47472, 105.09778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar dewa desa bandar dewa indonesia id desa bandar dewa',
    NOW(), NOW(), '12488978', NULL, 'Desa Bandar Pugung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.97722, 103.75944, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar pugung desa bandar pugung indonesia id desa bandar pugung',
    NOW(), NOW(), '12489009', NULL, 'Desa Bandar Dalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.12361, 103.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar dalam desa bandar dalam indonesia id desa bandar dalam',
    NOW(), NOW(), '12489050', NULL, 'Desa Bandar Jaya', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.48611, 104.23028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar jaya desa bandar jaya indonesia id desa bandar jaya',
    NOW(), NOW(), '12489056', NULL, 'Desa Bandar Dalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.70611, 104.46306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa bandar dalam desa bandar dalam indonesia id desa bandar dalam',
    NOW(), NOW(), '12490837', NULL, 'Kelurahan Telukair', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.99583, 103.44083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kelurahan telukair kelurahan telukair indonesia id kelurahan telukair',
    NOW(), NOW(), '12490901', NULL, 'Kelurahan Bandarsyah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.93083, 108.34778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kelurahan bandarsyah kelurahan bandarsyah indonesia id kelurahan bandarsyah',
    NOW(), NOW(), '12511243', NULL, 'Pelabuhan Sausapor', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -0.50846, 132.08283, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan sausapor pelabuhan sausapor indonesia id',
    NOW(), NOW(), '12624997', NULL, 'Weda Bay Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.46918, 127.95354, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'weda bay airport weda bay airport indonesia id waeh,wdb',
    NOW(), NOW(), '12648516', NULL, 'Dhoho International Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.76194, 111.95127, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'dhoho international airport dhoho international airport indonesia id dhx,ward',
    NOW(), NOW(), '12719967', NULL, 'Arung Palakka Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.46021, 120.30683, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arung palakka airport arung palakka airport indonesia id apd,wawn',
    NOW(), NOW(), '12750419', NULL, 'Budiarto Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.28915, 106.56988, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'budiarto airport budiarto airport indonesia id rto,wirr',
    NOW(), NOW(), '12750420', NULL, 'Singkawang Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.79176, 108.96143, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'singkawang airport singkawang airport indonesia id skj,wiod',
    NOW(), NOW(), '12808738', NULL, 'ONE 15 Marina Nirup Island', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.12753, 103.82866, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'one 15 marina nirup island one 15 marina nirup island indonesia id one°15 marina nirup island',
    NOW(), NOW(), '12808988', NULL, 'Bolaang Mongondow Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.88858, 124.03306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bolaang mongondow airport bolaang mongondow airport indonesia id lkm,wami',
    NOW(), NOW(), '12908911', NULL, 'Enggano Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.30765, 102.19008, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'enggano airport enggano airport indonesia id eng,wige',
    NOW(), NOW(), '12908915', NULL, 'General Besar Abdul Haris Nasution Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.9498, 99.5326, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'general besar abdul haris nasution airport general besar abdul haris nasution airport indonesia id jhn',
    NOW(), NOW(), '13060358', NULL, 'Maratua Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.19724, 118.59752, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maratua airport maratua airport indonesia id rtu,waqc',
    NOW(), NOW(), '13118080', NULL, 'Miangas Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    5.56317, 126.58154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miangas airport miangas airport indonesia id iax',
    NOW(), NOW(), '13192036', NULL, 'Kuala Kurun Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.12577, 113.87508, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kuala kurun airport kuala kurun airport indonesia id gxm,waga',
    NOW(), NOW(), '13192264', NULL, 'Keluang Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.62353, 103.955, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'keluang airport keluang airport indonesia id klq,wipv',
    NOW(), NOW(), '13192653', NULL, 'Karel Sadsuitubun Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.75829, 132.75797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karel sadsuitubun airport karel sadsuitubun airport indonesia id luv,wapf',
    NOW(), NOW(), '13236407', NULL, 'Terminal Ciamis', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.33248, 108.35738, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal ciamis terminal ciamis indonesia id ciamis bus terminal,term. ciamis,terminal bus ciamis,terminal ciamis',
    NOW(), NOW(), '13405970', NULL, 'Panua Pohuwato Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.46536, 121.81744, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'panua pohuwato airport panua pohuwato airport indonesia id pwx,wafz',
    NOW(), NOW(), '13410559', NULL, 'Bandardalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.74457, 104.4442, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandardalam bandardalam indonesia id bandardalam',
    NOW(), NOW(), '13411601', NULL, 'Desa Kalimanggis', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.36917, 108.30722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa kalimanggis desa kalimanggis indonesia id desa kalimanggis',
    NOW(), NOW(), '1847949', NULL, 'Naha Air Base', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    26.19796, 127.6457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'naha air base naha air base japan jp aha,naha air base,naha air force base,naha kuko,naha kūkō,oroku airport,oroku hikojo,oroku hikōjō',
    NOW(), NOW(), '1848041', NULL, 'Yura Kō', 'Yura Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.28333, 134.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yura kō yura ko japan jp yura ko,yura kō,yura-ko,yura-kō,you liang gang,由良港',
    NOW(), NOW(), '1848042', NULL, 'Yura-kō', 'Yura-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.9576, 135.10252, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yura-kō yura-ko japan jp yura no uchi,yura-ko,yura-kō,yurano-uchi',
    NOW(), NOW(), '1848053', NULL, 'Yunotsu Kō', 'Yunotsu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.0979, 132.33574, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yunotsu kō yunotsu ko japan jp yunotsu ko,yunotsu kō,yunotsu-ko,yunotsu-kō,yunotu ko,wen quan jin gang,温泉津港',
    NOW(), NOW(), '1848092', NULL, 'Yuki-kō', 'Yuki-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.76655, 134.59195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yuki-kō yuki-ko japan jp yuki ko,yuki kō,yuki-ko,yuki-kō,you qi gang,由岐港',
    NOW(), NOW(), '1848152', NULL, 'Yoshiura-kō', 'Yoshiura-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.25, 132.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yoshiura-kō yoshiura-ko japan jp yoshi-ura,yoshiura-ko,yoshiura-kō,yoshiura-wan,yosiura wan',
    NOW(), NOW(), '1848250', NULL, 'Yonōzu-urashiro Kō', 'Yonozu-urashiro Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.9, 132, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yonōzu-urashiro kō yonozu-urashiro ko japan jp yonozu-ko,yonozu-urashiro ko,yonōzu-kō,yonōzu-urashiro kō,mi shui jin pu dai gang,米水津浦代港',
    NOW(), NOW(), '1848279', NULL, 'Yonabaru-kō', 'Yonabaru-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    26.20396, 127.7706, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yonabaru-kō yonabaru-ko japan jp',
    NOW(), NOW();