INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8298754', NULL, 'Yangzhou Taizhou Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.5631, 119.719, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yangzhou taizhou airport yangzhou taizhou airport china cn yty,yangzhou taizhou airport,zsya,yang zhou tai zhou ji chang,扬州泰州机场',
    NOW(), NOW(), '8298775', NULL, 'Penglai Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    37.8089, 120.813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'penglai airport penglai airport china cn pnj',
    NOW(), NOW(), '8298784', NULL, 'Yongzhou Lingling Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    26.34658, 111.61028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yongzhou lingling airport yongzhou lingling airport china cn llf,yongzhou lingling airport,zglg,yong zhou ling ling ji chang,永州零陵机场',
    NOW(), NOW(), '8298788', NULL, 'Huizhou Pingtan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.04972, 114.59873, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'huizhou pingtan airport huizhou pingtan airport china cn huz,huizhou pingtan airport,huizhou pingtan jichang,huìzhōu píngtán jīchǎng,zghz,hui zhou ping tan ji chang,惠州平潭机场',
    NOW(), NOW(), '8298799', NULL, 'Tonghua Sanyuanpu Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    42.25476, 125.70587, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tonghua sanyuanpu airport tonghua sanyuanpu airport china cn aeroportul tonghua sanyuanpu,ljukheh tunkhua,san bay tam nguyen pho thong hoa,sân bay tam nguyên phổ thông hóa,tnh,tonghua sanyuanpu airport,zytn,aeroport de tonghua sanyuanpu,aeroporto di tonghua sanyuanpu,aéroport de tonghua sanyuanpu,mtar twnghhwa,tong hua san yuan pu ji chang,люхэ тунхуа,фурудгоҳи тунгҳуо син‌юонпу,فرودگاه تونگهوا سن‌یوانپو,مطار تونغهوا,通化三源浦机场,通化三源浦機場',
    NOW(), NOW(), '8299063', NULL, 'Foshan Shadi Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.08321, 113.06923, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'foshan shadi airport foshan shadi airport china cn aeroportul foshan shadi,fuo,foshan shadi airport,foshan shadi jichang,fóshān shādī jīchǎng,port lotniczy foshan,san bay sa gje phat son,sân bay sa đê phật sơn,zgfs,aeroport de foshan shadi,aeroporto di foshan shadi,aéroport de foshan shadi,fo shan sha di kong gang,frwdgah fwshan shady,fu shan sha di ji chang,mtar fwshan shady,posan sadi gonghang,фурудгоҳи фушон шодӣ,فرودگاه فوشان شادی,مطار فوشان شادي,仏山沙堤空港,佛山沙堤机场,佛山沙堤機場,포산 사디 공항',
    NOW(), NOW(), '8299103', NULL, 'Xi''an Xiguan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    34.37497, 109.12239, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'xi''an xiguan airport xi''an xiguan airport china cn sia,zlsn,xi an xi guan ji chang,西安西关机场',
    NOW(), NOW(), '8307188', NULL, 'Gangmen Gang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    18.34275, 109.12627, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gangmen gang gangmen gang china cn gangmen gang,gang men gang,港门港',
    NOW(), NOW(), '8359269', NULL, 'Dongzao Gang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.11065, 121.48009, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dongzao gang dongzao gang china cn dongzao gang,dong zao gang,东灶港',
    NOW(), NOW(), '8359424', NULL, 'Jiaogang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.09588, 120.48525, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jiaogang jiaogang china cn jiaogang,jiao gang,焦港',
    NOW(), NOW(), '8359719', NULL, 'Miaoyu Gang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.03232, 120.25128, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miaoyu gang miaoyu gang china cn miaoyu gang,miao yu gang,庙宇港',
    NOW(), NOW(), '8359854', NULL, 'Denggan Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.01552, 120.3675, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'denggan gangkou denggan gangkou china cn denggan gangkou,deng gan gang kou,灯杆港口',
    NOW(), NOW(), '8359857', NULL, 'Liuzhu Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.00935, 120.35965, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'liuzhu gangkou liuzhu gangkou china cn liuzhu gangkou,liu zhu gang kou,六助港口',
    NOW(), NOW(), '8359889', NULL, 'Wangqiao Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.00211, 120.34592, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wangqiao gangkou wangqiao gangkou china cn wangqiao gangkou,wang qiao gang kou,旺桥港口',
    NOW(), NOW(), '8360428', NULL, 'Ganjin Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.00121, 120.39983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ganjin gangkou ganjin gangkou china cn ganjin gangkou,gan jin gang kou,干斤港口',
    NOW(), NOW(), '8360472', NULL, 'Taizi Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.01203, 120.51204, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taizi gangkou taizi gangkou china cn taizi gangkou,tai zi gang kou,太字港口',
    NOW(), NOW(), '8360507', NULL, 'Duanshan Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.00716, 120.52696, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'duanshan gangkou duanshan gangkou china cn duanshan gangkou,duan shan gang kou,段山港口',
    NOW(), NOW(), '8360532', NULL, 'Yongji Gangkou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.0761, 120.48587, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yongji gangkou yongji gangkou china cn yongji gangkou,yong ji gang kou,永济港口',
    NOW(), NOW(), '8391812', NULL, 'Wanzhou Wuqiao Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.80179, 108.4327, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wanzhou wuqiao airport wanzhou wuqiao airport china cn wxn,wanxian airport,wanzhou wuqiao airport,wanzhou wuqiao jichang,wànzhōu wǔqiáo jīchǎng,zuwx,wan zhou wu qiao ji chang,万州五桥机场',
    NOW(), NOW(), '8394375', NULL, 'Nansha Ferry Port', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.7729, 113.60717, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nansha ferry port nansha ferry port china cn nsz,nansha ferry port',
    NOW(), NOW(), '8394377', NULL, 'Shenzhen Fuyong Ferry Terminal', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.60545, 113.80943, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shenzhen fuyong ferry terminal shenzhen fuyong ferry terminal china cn fyg,shenzhen fuyong ferry terminal',
    NOW(), NOW(), '8394378', NULL, 'Humen Ferry Terminal', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.81552, 113.66359, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'humen ferry terminal humen ferry terminal china cn humen ferry terminal,zti',
    NOW(), NOW(), '8410844', NULL, 'Dao Cheng Yading Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    29.31613, 100.04828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dao cheng yading airport dao cheng yading airport china cn aeroport de dao cheng yading,aeropuerto de dao cheng yading,aéroport de dao cheng yading,dcy,dao cheng yading airport,flughafen dao cheng yading,yading airport,zudc,dao cheng ya ding ji chang,dao cheng ya ding kong gang,稲城亜丁空港,稻城亞丁機場',
    NOW(), NOW(), '8411018', NULL, 'Jiaxing Nanhu Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.70598, 120.68069, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jiaxing nanhu airport jiaxing nanhu airport china cn jnh,jiaxing south airport',
    NOW(), NOW(), '8426217', NULL, 'Bijie Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    27.30036, 105.30159, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bijie airport bijie airport china cn aeroporto de bijie-feixiong,aeroportul bijie feixiong,bfj,bijie airport,bijie feixiong airport,maes awyr bijie feixiong,zubj,aeroport de bijie feixiong,aéroport de bijie feixiong,bi jie fei xiong ji chang,bi jie fei xiong kong gang,frwdgah byjy,mtar byjy fyshwngh,фурудгоҳи биҷи,فرودگاه بیجی,مطار بيجي فيشونغ,毕节飞雄机场,畢節飛雄機場,畢節飛雄空港',
    NOW(), NOW(), '8428016', NULL, 'Shuangdao Gang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    37.4473, 121.96566, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shuangdao gang shuangdao gang china cn shuangdao gang,western inlet,shuang dao gang,双岛港',
    NOW(), NOW(), '8429963', NULL, 'Youkuribuliman', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    39.18081, 76.67495, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'youkuribuliman youkuribuliman china cn youkuribuliman,you ku ri bu li man,尤库日布力曼',
    NOW(), NOW(), '8435706', NULL, 'Yichun Mingyueshan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    27.80347, 114.3082, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yichun mingyueshan airport yichun mingyueshan airport china cn yic,yichun mingyueshan airport,yichun mingyueshan jichang,yíchūn míngyuèshān jīchǎng,zsyc,yi chun ming yue shan ji chang,宜春明月山机场',
    NOW(), NOW(), '8435732', NULL, 'Foshan Ferry Port', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.04612, 113.11556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'foshan ferry port foshan ferry port china cn foshan ferry port,zcp',
    NOW(), NOW(), '8435860', NULL, 'Jiuzhou Ferry Port', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.24128, 113.58228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jiuzhou ferry port jiuzhou ferry port china cn jiuzhou ferry port,zui,jiu zhou gang,九洲港',
    NOW(), NOW(), '8436332', NULL, 'Sanya Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    18.28633, 109.46125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sanya airport sanya airport china cn syx,sanya airport',
    NOW(), NOW(), '8470856', NULL, 'Alukangbu', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    41.08247, 110.88369, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alukangbu alukangbu china cn alukangbu,a lu kang bo,阿路康卜',
    NOW(), NOW(), '8504981', NULL, 'Dajiayi Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.71763, 103.82475, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dajiayi airport dajiayi airport china cn wenshan air base',
    NOW(), NOW(), '8505071', NULL, 'Xuzhou Guanyin Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    34.05757, 117.55483, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'xuzhou guanyin airport xuzhou guanyin airport china cn xuz,xuzhou daguozhang air base,xuzhou guanyin airport,xuzhou guanyin jichang,xúzhōu guānyīn jīchǎng,zsxz,xu zhou guan yin ji chang,徐州觀音機場,徐州观音机场',
    NOW(), NOW(), '8521364', NULL, 'Gannan Xiahe Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    34.8107, 102.64492, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gannan xiahe airport gannan xiahe airport china cn gxh,gannan xiahe airport,zlxh',
    NOW(), NOW(), '8521371', NULL, 'Kaili Huangping Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    26.9741, 107.98046, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kaili huangping airport kaili huangping airport china cn aeroportul kaili huangping,kjh,kaili huangping airport,kaili huangping jichang,kǎilǐ huángpíng jīchǎng,zukj,aeroport de kaili huangping,aéroport de kaili huangping,kai li huang ping ji chang,kai li huang ping kong gang,mtar ghayly hwanghbyngh,фурудгоҳи коили ҳуонг‌пенг,فرودگاه کایلی هوانگ‌پینگ,مطار غايلي هوانغبينغ,凯里黄平机场,凱里黃平機場,凱里黄平空港',
    NOW(), NOW(), '8521741', NULL, 'Hongyuan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    32.52684, 102.35464, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hongyuan airport hongyuan airport china cn ahj,hongyuan airport,hongyuan jichang,hóngyuán jīchǎng,zuhy,frwdgah hngywan,hong yuan ji chang,mtar hwnghywan,فرودگاه هنگیوان,مطار هونغيوان,红原机场',
    NOW(), NOW(), '8531990', NULL, 'Yongxing Island Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    16.83216, 112.34355, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yongxing island airport yongxing island airport china cn aeroportul yongxing island,bandar udara pulau yongxing,lapangan terbang woody island,san bay gao vinh hung,sân bay đảo vĩnh hưng,woody island airport,yongxing island airport,zjyx,aeroport de yongxing,aeroporto di yongxing,aéroport de yongxing,mtar jzyrt ywnghshyngh,yong xing dao ji chang,yong xing dao kong gang,éng-heng-tó ki-tiûⁿ,مطار جزيرة يونغشينغ,永兴岛机场,永興島機場,永興島空港',
    NOW(), NOW(), '8531999', NULL, 'Xinjin Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.42037, 103.84642, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'xinjin airport xinjin airport china cn aeroportul xinjin,hsinching airfield,xinjin airport,zuxj,xin jin ji chang,фурудгоҳи син‌ҷийн,فرودگاه سین‌جین,新津机场,新津機場',
    NOW(), NOW(), '8533073', NULL, 'Shantou Waisha Air Base', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.42742, 116.76244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shantou waisha air base shantou waisha air base china cn swa,shantou waisha air base,shantou waisha airport,shantou waisha jichang,shàntóu wàishā jīchǎng,zgow,shan tou wai sha ji chang,汕头外砂机场',
    NOW(), NOW(), '8533171', NULL, 'Tangshan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    39.6552, 118.13144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tangshan airport tangshan airport china cn tvs,tangshan airport,zbts',
    NOW(), NOW(), '8555855', NULL, 'Taiping Island Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    10.37788, 114.36633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taiping island airport taiping island airport china cn aeroportul taiping island,rcsp,san bay gao thai binh,sân bay đảo thái bình,taiping island airport,frwdgah aytw aba aylnd,tai ping dao ji chang,tai ping dao kong gang,фурудгоҳи оиту обо оилнд,فرودگاه ایتو ابا آیلند,太平岛机场,太平島機場,太平島空港',
    NOW(), NOW(), '8556003', NULL, 'Fuyuan Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    48.19447, 134.35799, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fuyuan airport fuyuan airport china cn aehroport fujuan'',aeroport de fuyuan,aéroport de fuyuan,fyj,fuyuan airport,fuyuan jichang,fǔyuǎn jīchǎng,zyfy,fu yuan ji chang,аэропорт фуюань,抚远机场,撫遠機場',
    NOW(), NOW(), '8581628', NULL, 'Delingha Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    37.12501, 97.26849, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delingha airport delingha airport china cn aeroportul delingha,delingha airport,delingha jichang,délìnghā jīchǎng,hxd,port lotniczy delingha,zldl,aeroport de delingha,aéroport de delingha,de ling ha ji chang,frwdgah dlyngha,mtar dylynghha,фурудгоҳи длингҳо,فرودگاه دلینگها,مطار ديلينغها,德令哈机场,德令哈機場',
    NOW(), NOW(), '8581630', NULL, 'Hefei Xinqiao International Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.99082, 116.96908, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'hefei xinqiao international airport hefei xinqiao international airport china cn hfe,hefei xinqiao guoji jichang,hefei xinqiao international airport,héféi xīnqiáo guójì jīchǎng,zsof,he fei xin qiao guo ji ji chang,合肥新桥国际机场',
    NOW(), NOW(), '8593872', NULL, 'Lüliang Airport', 'Lueliang Airport',
    NULL, 'CN', 'China', NULL, NULL,
    37.68324, 111.1428, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lüliang airport lueliang airport china cn aeroportul lueliang,aeroportul lüliang,llv,lueliang airport,luliang jichang,lüliang airport,lǚliáng jīchǎng,san bay lu luong,sân bay lữ lương,zbll,aeroport de lueliang,aéroport de lüliang,frwdgah lwlyang,lu liang da wu ji chang,lu liang ji chang,mtar lwlyangh daw,فرودگاه لولیانگ,مطار لوليانغ داو,吕梁机场,呂梁大武機場,呂梁機場',
    NOW(), NOW(), '8594743', NULL, 'Shennongjia Hongping Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.63365, 110.33792, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shennongjia hongping airport shennongjia hongping airport china cn hpg,shennongjia hongping airport,shennongjia jichang,shénnóngjià jīchǎng,zhsn,shen nong jia ji chang,神农架机场,神農架機場',
    NOW(), NOW(), '8617183', NULL, 'Alxa Left Banner Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    38.82286, 105.62616, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alxa left banner airport alxa left banner airport china cn axf,alxa left banner airport,zbal',
    NOW(), NOW(), '8617186', NULL, 'Taolai Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    42.01488, 101.00195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taolai airport taolai airport china cn ejn,taolai airport,zben',
    NOW(), NOW(), '8617226', NULL, 'Alxa Right Banner Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    39.22213, 101.54942, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alxa right banner airport alxa right banner airport china cn alxa right banner airport,rht',
    NOW(), NOW();