INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12909298', NULL, 'Yamada Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.46424, 141.95791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yamada fishing port yamada fishing port japan jp',
    NOW(), NOW(), '12909299', NULL, 'Orikasa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.45214, 141.96364, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'orikasa fishing port orikasa fishing port japan jp',
    NOW(), NOW(), '12909300', NULL, 'Funakoshi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.42072, 141.98227, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'funakoshi fishing port funakoshi fishing port japan jp',
    NOW(), NOW(), '12909301', NULL, 'Oura FIshing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.44847, 142.00238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oura fishing port oura fishing port japan jp',
    NOW(), NOW(), '12909302', NULL, 'Koyadori Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.42588, 142.01342, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koyadori fishing port koyadori fishing port japan jp',
    NOW(), NOW(), '12909304', NULL, 'Yamanouichi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.42631, 141.97426, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yamanouichi fishing port yamanouichi fishing port japan jp',
    NOW(), NOW(), '12909305', NULL, 'Kirikiri Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.37253, 141.95002, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kirikiri fishing port kirikiri fishing port japan jp',
    NOW(), NOW(), '12909306', NULL, 'Otsuchi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.35249, 141.91798, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'otsuchi fishing port otsuchi fishing port japan jp',
    NOW(), NOW(), '12909313', NULL, 'Murohama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.34402, 141.91022, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'murohama fishing port murohama fishing port japan jp',
    NOW(), NOW(), '12909314', NULL, 'Katagichi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.34073, 141.90494, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katagichi fishing port katagichi fishing port japan jp',
    NOW(), NOW(), '12909315', NULL, 'Nehama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.32719, 141.9051, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nehama fishing port nehama fishing port japan jp',
    NOW(), NOW(), '12909317', NULL, 'Hakozaki Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.32644, 141.91515, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hakozaki fishing port hakozaki fishing port japan jp',
    NOW(), NOW(), '12909318', NULL, 'Unozumai Shirahama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.32978, 141.94343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'unozumai shirahama fishing port unozumai shirahama fishing port japan jp',
    NOW(), NOW(), '12909319', NULL, 'Kariyado Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.31498, 141.94632, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kariyado fishing port kariyado fishing port japan jp',
    NOW(), NOW(), '12909320', NULL, 'Kuwanohama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.30795, 141.90667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kuwanohama fishing port kuwanohama fishing port japan jp',
    NOW(), NOW(), '12909321', NULL, 'Ryoishi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.30601, 141.89203, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ryoishi fishing port ryoishi fishing port japan jp',
    NOW(), NOW(), '12909322', NULL, 'Kamaishi Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.26701, 141.89479, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kamaishi port kamaishi port japan jp',
    NOW(), NOW(), '12909324', NULL, 'Heita Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.24753, 141.89048, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'heita port heita port japan jp',
    NOW(), NOW(), '12909325', NULL, 'Ozaki Shirahama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.23908, 141.92194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ozaki shirahama fishing port ozaki shirahama fishing port japan jp',
    NOW(), NOW(), '12909326', NULL, 'Sasu Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.22137, 141.92568, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sasu fishing port sasu fishing port japan jp',
    NOW(), NOW(), '12909327', NULL, 'Toni Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.20803, 141.89141, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'toni fishing port toni fishing port japan jp',
    NOW(), NOW(), '12909328', NULL, 'Kojirahama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.20597, 141.86952, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kojirahama fishing port kojirahama fishing port japan jp',
    NOW(), NOW(), '12909329', NULL, 'Katagishi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.20079, 141.86866, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katagishi fishing port katagishi fishing port japan jp',
    NOW(), NOW(), '12909330', NULL, 'Arakawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.19178, 141.87029, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arakawa fishing port arakawa fishing port japan jp',
    NOW(), NOW(), '12909331', NULL, 'Oishi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.18223, 141.89345, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oishi fishing port oishi fishing port japan jp',
    NOW(), NOW(), '12909332', NULL, 'Senzai Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.16248, 141.89627, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senzai fishing port senzai fishing port japan jp',
    NOW(), NOW(), '12909333', NULL, 'Konpaku Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.15515, 141.86103, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'konpaku fishing port konpaku fishing port japan jp',
    NOW(), NOW(), '12909334', NULL, 'Okita Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.15464, 141.84636, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okita fishing port okita fishing port japan jp',
    NOW(), NOW(), '12909335', NULL, 'Yoshihama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.14488, 141.83992, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yoshihama fishing port yoshihama fishing port japan jp',
    NOW(), NOW(), '12909336', NULL, 'Masudate Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.13607, 141.85337, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'masudate fishing port masudate fishing port japan jp',
    NOW(), NOW(), '12909337', NULL, 'Kokabe Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.11609, 141.88767, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kokabe fishing port kokabe fishing port japan jp',
    NOW(), NOW(), '12909338', NULL, 'Sakihama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.10207, 141.86024, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakihama fishing port sakihama fishing port japan jp',
    NOW(), NOW(), '12909339', NULL, 'Rikuchu-Sakihama Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.10303, 141.85904, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rikuchu-sakihama port rikuchu-sakihama port japan jp',
    NOW(), NOW(), '12909340', NULL, 'Namiita Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.10824, 141.8292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'namiita fishing port namiita fishing port japan jp',
    NOW(), NOW(), '12909341', NULL, 'Okirai Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.11361, 141.81953, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okirai fishing port okirai fishing port japan jp',
    NOW(), NOW(), '12909342', NULL, 'Tomari Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.10855, 141.81136, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tomari fishing port tomari fishing port japan jp',
    NOW(), NOW(), '12909343', NULL, 'Onizawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.08845, 141.81137, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onizawa fishing port onizawa fishing port japan jp',
    NOW(), NOW(), '12909344', NULL, 'Koishihama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.07759, 141.82228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koishihama fishing port koishihama fishing port japan jp',
    NOW(), NOW(), '12909345', NULL, 'Sunagohama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.07504, 141.83923, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sunagohama fishing port sunagohama fishing port japan jp',
    NOW(), NOW(), '12909346', NULL, 'Nonomae-Shirahama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.05546, 141.81553, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nonomae-shirahama fishing port nonomae-shirahama fishing port japan jp',
    NOW(), NOW(), '12909347', NULL, 'Nonomae Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.05183, 141.81763, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nonomae fishing port nonomae fishing port japan jp',
    NOW(), NOW(), '12909349', NULL, 'Tahama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.03959, 141.79759, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tahama fishing port tahama fishing port japan jp',
    NOW(), NOW(), '12909350', NULL, 'Ishihama-Ryori Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.04063, 141.794, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ishihama-ryori fishing port ishihama-ryori fishing port japan jp',
    NOW(), NOW(), '12909351', NULL, 'Ryori Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.04291, 141.79616, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ryori fishing port ryori fishing port japan jp',
    NOW(), NOW(), '12909352', NULL, 'Koji-Tanojiri Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.02894, 141.78347, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koji-tanojiri fishing port koji-tanojiri fishing port japan jp',
    NOW(), NOW(), '12909353', NULL, 'Koji Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.03099, 141.77485, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koji fishing port koji fishing port japan jp',
    NOW(), NOW(), '12909354', NULL, 'Attari Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.03426, 141.76902, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'attari fishing port attari fishing port japan jp',
    NOW(), NOW(), '12909355', NULL, 'Waikou Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.01949, 141.76019, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'waikou fishing port waikou fishing port japan jp',
    NOW(), NOW(), '12909356', NULL, 'Nagasaki Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.01979, 141.75275, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagasaki fishing port nagasaki fishing port japan jp',
    NOW(), NOW(), '12909357', NULL, 'Takonoura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    39.03189, 141.7369, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takonoura fishing port takonoura fishing port japan jp',
    NOW(), NOW();