INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12863003', NULL, 'Ōsato Kō', 'Osato Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.83713, 129.95784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōsato kō osato ko japan jp osato ko,da li gang,oosatokou,ōsato kō,おおさとこう,オオサトコウ,大里港',
    NOW(), NOW(), '12863004', NULL, 'Nagashima Kō', 'Nagashima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.16932, 130.10791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagashima kō nagashima ko japan jp kohama ko,kohama kō,nagashima ko,nagashima kō,kohamakou,nagashimakou,xiao bang gang,zhang dao gang,こはまこう,ながしまこう,コハマコウ,ナガシマコウ,小浜港,長島港',
    NOW(), NOW(), '12863005', NULL, 'Nakanoshima Kō', 'Nakanoshima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    29.83957, 129.84866, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nakanoshima kō nakanoshima ko japan jp nakanoshima ko,nakanoshima kō,nakanoshimakou,zhong zhi dao gang,なかのしまこう,ナカノシマコウ,中之島港',
    NOW(), NOW(), '12863006', NULL, 'Nagashima Kō', 'Nagashima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.20408, 130.15306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagashima kō nagashima ko japan jp nagashima ko,nagashima kō,urasoko ko,urasoko kō,nagashimakou,pu di gang,urasokokou,zhang dao gang,うらそここう,ながしまこう,ウラソココウ,ナガシマコウ,浦底港,長島港',
    NOW(), NOW(), '12863007', NULL, 'Nagashima Kō', 'Nagashima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.25529, 130.18561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagashima kō nagashima ko japan jp nagashima ko,nagashima kō,shoura ko,shoura kō,nagashimakou,shourakou,zhang dao gang,zhu pu gang,しょうらこう,ながしまこう,ショウラコウ,ナガシマコウ,諸浦港,長島港',
    NOW(), NOW(), '12863008', NULL, 'Iwayadomari Kō', 'Iwayadomari Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.48416, 130.16826, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iwayadomari kō iwayadomari ko japan jp iwayadomari ko,iwayadomari kō,iwayadomarikou,yan wu po gang,いわやどまりこう,イワやドマリコウ,岩屋泊港',
    NOW(), NOW(), '12863009', NULL, 'Kurio Kō', 'Kurio Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.26534, 130.41916, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kurio kō kurio ko japan jp kurio ko,kurio kō,kuriokou,li sheng gang,くりおこう,クリオコウ,栗生港',
    NOW(), NOW(), '12863010', NULL, 'Anbō Kō', 'Anbo Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.31581, 130.66037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anbō kō anbo ko japan jp anbo ko,anbō kō,an fang gang,anboukou,あんぼうこう,アンボウコウ,安房港',
    NOW(), NOW(), '12863011', NULL, 'Yuwan Kō', 'Yuwan Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.27803, 129.2921, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yuwan kō yuwan ko japan jp yuwan ko,yuwan kō,tang wan gang,yuwankou,ゆわんこう,ユワンコウ,湯湾港',
    NOW(), NOW(), '12863012', NULL, 'Futagawa Kō', 'Futagawa Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.5863, 130.78698, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'futagawa kō futagawa ko japan jp futagawa ko,futagawa kō,er chuan gang,futagawakou,ふたがわこう,フタガワコウ,二川港',
    NOW(), NOW(), '12863013', NULL, 'Higashinohama Kō', 'Higashinohama Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    29.68887, 129.54034, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'higashinohama kō higashinohama ko japan jp higashinohama ko,higashinohama kō,dong zhi bang gang,higashinohamakou,ひがしのはまこう,ヒガシノハマコウ,東之浜港',
    NOW(), NOW(), '12863014', NULL, 'Koniya Gyokō', 'Koniya Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.14263, 129.31065, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koniya gyokō koniya gyoko japan jp koniya gyoko,koniya gyokō,gu ren wu yu gang,koniyagyokou,こにやぎょこう,コニヤギョコウ,古仁屋漁港',
    NOW(), NOW(), '12863015', NULL, 'Imuta Gyokō', 'Imuta Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.77481, 129.80221, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'imuta gyokō imuta gyoko japan jp imuta gyoko,imuta gyokō,imutagyokou,lin mou tian yu gang,いむたぎょこう,イムタギョコウ,藺牟田漁港',
    NOW(), NOW(), '12863016', NULL, 'Kiire Kō', 'Kiire Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.37783, 130.55072, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kiire kō kiire ko japan jp kiire ko,kiire kō,kiirekou,xi ru gang,きいれこう,キイレコウ,喜入港',
    NOW(), NOW(), '12863017', NULL, 'Izashiki Gyokō', 'Izashiki Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.09649, 130.69083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'izashiki gyokō izashiki gyoko japan jp izashiki gyoko,izashiki gyokō,izashikigyokou,yi zuo fu yu gang,いざしきぎょこう,イザシキギョコウ,伊座敷漁港',
    NOW(), NOW(), '12863018', NULL, 'Kakeroma Kō', 'Kakeroma Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.1067, 129.24589, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kakeroma kō kakeroma ko japan jp ikomo ko,ikomo kō,kakeroma ko,kakeroma kō,ikomokou,jia ji lu ma gang,kakeromakou,yi zi mao gang,いこもこう,かけろまこう,イコモコウ,カケロマコウ,伊子茂港,加計呂麻港',
    NOW(), NOW(), '12863019', NULL, 'Onoaida Kō', 'Onoaida Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.23218, 130.55259, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onoaida kō onoaida ko japan jp onoaida ko,onoaida kō,onoaidakou,wei zhi jian gang,おのあいだこう,オノアイダコウ,尾之間港',
    NOW(), NOW(), '12863020', NULL, 'Akune Gyokō', 'Akune Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.01863, 130.18829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'akune gyokō akune gyoko japan jp akune gyoko,akune gyokō,a jiu gen yu gang,akunegyokou,あくねぎょこう,アクネギョコウ,阿久根漁港',
    NOW(), NOW(), '12863021', NULL, 'Tarumizu Kō', 'Tarumizu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.49636, 130.69428, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tarumizu kō tarumizu ko japan jp tarumizu ko,tarumizu kō,chui shui gang,tarumizukou,たるみずこう,タルミズコウ,垂水港',
    NOW(), NOW(), '12863022', NULL, 'Motoura Kō', 'Motoura Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    29.61047, 129.69598, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'motoura kō motoura ko japan jp motoura ko,motoura kō,motourakou,yuan pu gang,もとうらこう,モトウラコウ,元浦港',
    NOW(), NOW(), '12863023', NULL, 'Kikaijima Kō', 'Kikaijima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.27561, 129.9491, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kikaijima kō kikaijima ko japan jp kamikatetsu ko,kamikatetsu kō,kikaijima ko,kikaijima kō,kamikatetsukou,kikaijimakou,shang jia zhi gang,xi jie dao gang,かみかてつこう,きかいじまこう,カミカテツコウ,キカイジマコウ,上嘉鉄港,喜界島港',
    NOW(), NOW(), '12863024', NULL, 'Kamiyaku-nagata Kō', 'Kamiyaku-nagata Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.39716, 130.41757, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kamiyaku-nagata kō kamiyaku-nagata ko japan jp kamiyaku-nagata ko,kamiyaku-nagata kō,kamiyakunagatakou,shang wu jiu yong tian gang,かみやくながたこう,カミヤクナガタコウ,上屋久永田港',
    NOW(), NOW(), '12863025', NULL, 'Sumiyoshi Kō', 'Sumiyoshi Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    27.3603, 128.5247, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sumiyoshi kō sumiyoshi ko japan jp sumiyoshi ko,sumiyoshi kō,sumiyoshikou,zhu ji gang,すみよしこう,スミヨシコウ,住吉港',
    NOW(), NOW(), '12863026', NULL, 'Sōmachi Gyokō', 'Somachi Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.33268, 130.00578, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sōmachi gyokō somachi gyoko japan jp somachi gyoko,sōmachi gyokō,soumachigyokou,zao ding yu gang,そうまちぎょこう,ソウマチギョコウ,早町漁港',
    NOW(), NOW(), '12863027', NULL, 'Nagashima Kō', 'Nagashima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.13315, 130.17258, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagashima kō nagashima ko japan jp kasedoo ko,kasedoō kō,nagashima ko,nagashima kō,jia shi tang gang,kasedoukou,nagashimakou,zhang dao gang,かせどうこう,ながしまこう,カセドウコウ,ナガシマコウ,加世堂港,長島港',
    NOW(), NOW(), '12863028', NULL, 'Kawashiri Gyokō', 'Kawashiri Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.17742, 130.55484, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kawashiri gyokō kawashiri gyoko japan jp kawashiri gyoko,kawashiri gyokō,chuan kao yu gang,kawashirigyokou,かわしりぎょこう,カワシリギョコウ,川尻漁港',
    NOW(), NOW(), '12863029', NULL, 'Chinase Kō', 'Chinase Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.3839, 129.44562, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chinase kō chinase ko japan jp chinase ko,chinase kō,chinasekou,zhi ming lai gang,ちなせこう,チナセコウ,知名瀬港',
    NOW(), NOW(), '12863030', NULL, 'Ōkuma Gyokō', 'Okuma Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.40231, 129.51551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōkuma gyokō okuma gyoko japan jp okuma gyoko,da xiong yu gang,ookumagyokou,ōkuma gyokō,おおくまぎょこう,オオクマギョコウ,大熊漁港',
    NOW(), NOW(), '12863031', NULL, 'Kakeroma Kō', 'Kakeroma Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.16644, 129.21229, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kakeroma kō kakeroma ko japan jp kakeroma ko,kakeroma kō,setake ko,setake kō,jia ji lu ma gang,kakeromakou,lai wu gang,setakekou,かけろまこう,せたけこう,カケロマコウ,セタケコウ,加計呂麻港,瀬武港',
    NOW(), NOW(), '12863032', NULL, 'Kudadon Kō', 'Kudadon Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.22479, 129.19423, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kudadon kō kudadon ko japan jp kudadon ko,kudadon kō,guan dun gang,kudadonkou,くだどんこう,クダドンコウ,管鈍港',
    NOW(), NOW(), '12863033', NULL, 'Inobe Kō', 'Inobe Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    27.41681, 128.64089, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inobe kō inobe ko japan jp inobe ko,inobe kō,inobekou,yi yan gang,いのべこう,イノベコウ,伊延港',
    NOW(), NOW(), '12863034', NULL, 'Kikaijima Kō', 'Kikaijima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.28372, 129.93436, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kikaijima kō kikaijima ko japan jp kikaijima ko,kikaijima kō,tekuzuku ko,tekuzuku kō,kikaijimakou,shou jiu jin jiu gang,tekudzukukou,xi jie dao gang,きかいじまこう,てくづくこう,キカイジマコウ,テクヅクコウ,喜界島港,手久津久港',
    NOW(), NOW(), '12863035', NULL, 'Tabukawa Kō', 'Tabukawa Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    30.40416, 130.62261, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tabukawa kō tabukawa ko japan jp tabukawa ko,tabukawa kō,fu chuan gang,tabukawakou,たぶかわこう,タブカワコウ,椨川港',
    NOW(), NOW(), '12863036', NULL, 'Takarajima Kō', 'Takarajima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    29.14553, 129.21955, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takarajima kō takarajima ko japan jp takarajima ko,takarajima kō,bao dao gang,takarajimakou,たからじまこう,タカラジマコウ,宝島港',
    NOW(), NOW(), '12863037', NULL, 'Wano Kō', 'Wano Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.42126, 129.70394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wano kō wano ko japan jp wano ko,wano kō,he ye gang,wanokou,わのこう,ワノコウ,和野港',
    NOW(), NOW(), '12863038', NULL, 'Kakeroma Kō', 'Kakeroma Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.13582, 129.24367, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kakeroma kō kakeroma ko japan jp hyo ko,hyō kō,kakeroma ko,kakeroma kō,biao gang,hyoukou,jia ji lu ma gang,kakeromakou,かけろまこう,ひょうこう,カケロマコウ,ヒョウコウ,俵港,加計呂麻港',
    NOW(), NOW(), '12863039', NULL, 'Imaizumi Gyokō', 'Imaizumi Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.29234, 130.60488, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'imaizumi gyokō imaizumi gyoko japan jp imaizumi gyoko,imaizumi gyokō,imaizumigyokou,jin he quan yu gang,いまいずみぎょこう,イマイズミギョコウ,今和泉漁港',
    NOW(), NOW(), '12863040', NULL, 'Yanma Kō', 'Yanma Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.24468, 129.42656, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yanma kō yanma ko japan jp yanma ko,yanma kō,shan jian gang,yanmakou,やんまこう,ヤンマコウ,山間港',
    NOW(), NOW(), '12863041', NULL, 'Nagashima Kō', 'Nagashima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.20909, 130.1098, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nagashima kō nagashima ko japan jp hoppozaki ko,hoppōzaki kō,nagashima ko,nagashima kō,bei fang qi gang,hoppouzakikou,nagashimakou,zhang dao gang,ながしまこう,ほっぽうざきこう,ナガシマコウ,ホッポウザキコウ,北方崎港,長島港',
    NOW(), NOW(), '12863042', NULL, 'Miyanoura Kō', 'Miyanoura Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.19979, 130.19214, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miyanoura kō miyanoura ko japan jp miyanoura ko,miyanoura kō,gong zhi pu gang,miyanourakou,みやのうらこう,ミヤノウラコウ,宮之浦港',
    NOW(), NOW(), '12863043', NULL, 'Nishishioya Kō', 'Nishishioya Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.25288, 130.36869, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nishishioya kō nishishioya ko japan jp nishishioya ko,nishishioya kō,nishishioyakou,xi yan wu gang,にししおやこう,ニシシオヤコウ,西塩屋港',
    NOW(), NOW(), '12863044', NULL, 'Ushinefumoto Gyokō', 'Ushinefumoto Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.56025, 130.72127, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ushinefumoto gyokō ushinefumoto gyoko japan jp ushinefumoto gyoko,ushinefumoto gyokō,niu gen lu yu gang,ushinefumotogyokou,うしねふもとぎょこう,ウシネフモトギョコウ,牛根麓漁港',
    NOW(), NOW(), '12863045', NULL, 'Yamato Kō', 'Yamato Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.36048, 129.40036, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yamato kō yamato ko japan jp ongachi ko,ongachi kō,yamato ko,yamato kō,da he gang,ongachikou,si sheng gang,yamatokou,おんがちこう,やまとこう,オンガチコウ,ヤマトコウ,大和港,思勝港',
    NOW(), NOW(), '12863046', NULL, 'Kajiki Kō', 'Kajiki Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.72799, 130.66501, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kajiki kō kajiki ko japan jp kajiki ko,kajiki kō,jia zhi mu gang,kajikikou,かじきこう,カジキコウ,加治木港',
    NOW(), NOW(), '12863047', NULL, 'Kominato Kō', 'Kominato Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.42038, 130.25456, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kominato kō kominato ko japan jp kominato ko,kominato kō,mansei ko,mansei kō,kominatokou,manseikou,wan shi gang,xiao cou gang,こみなとこう,まんせいこう,コミナトコウ,マンセイコウ,万世港,小湊港',
    NOW(), NOW(), '12863048', NULL, 'Seto Kō', 'Seto Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.1039, 130.16964, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'seto kō seto ko japan jp seto ko,seto kō,lai hu gang,setokou,せとこう,セトコウ,瀬戸港',
    NOW(), NOW(), '12863049', NULL, 'Ukejima Kō', 'Ukejima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    28.03362, 129.23404, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ukejima kō ukejima ko japan jp ikeji ko,ikeji kō,ukejima ko,ukejima kō,chi de gang,ikejikou,qing dao gang,ukejimakou,いけじこう,うけじまこう,イケジコウ,ウケジマコウ,池地港,請島港',
    NOW(), NOW(), '12863050', NULL, 'Kushi Gyokō', 'Kushi Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.30373, 130.22044, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kushi gyokō kushi gyoko japan jp kushi gyoko,kushi gyokō,jiu zhi yu gang,kushigyokou,くしぎょこう,クシギョコウ,久志漁港',
    NOW(), NOW(), '12863051', NULL, 'Kataura Gyokō', 'Kataura Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.41936, 130.18343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kataura gyokō kataura gyoko japan jp kataura gyoko,kataura gyokō,katauragyokou,pian pu yu gang,かたうらぎょこう,カタウラギョコウ,片浦漁港',
    NOW(), NOW(), '12863052', NULL, 'Shinkawa Kō', 'Shinkawa Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.44594, 130.29531, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shinkawa kō shinkawa ko japan jp shinkawa ko,shinkawa kō,shinkawakou,xin chuan gang,しんかわこう,シンカワコウ,新川港',
    NOW(), NOW();