INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12908813', NULL, 'Kagikake Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.90486, 140.86101, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kagikake fishing port kagikake fishing port japan jp',
    NOW(), NOW(), '12908815', NULL, 'Tsuchiya Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.90809, 140.86746, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tsuchiya fishing port tsuchiya fishing port japan jp',
    NOW(), NOW(), '12908816', NULL, 'Namiuchi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.92393, 140.86789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'namiuchi fishing port namiuchi fishing port japan jp',
    NOW(), NOW(), '12908817', NULL, 'Moura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.94454, 140.8713, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moura fishing port moura fishing port japan jp',
    NOW(), NOW(), '12908820', NULL, 'Inou Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.97787, 140.87276, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inou port inou port japan jp',
    NOW(), NOW(), '12908821', NULL, 'Shimofuro Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.46912, 141.09138, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimofuro port shimofuro port japan jp',
    NOW(), NOW(), '12908822', NULL, 'Uenohata Ikokuma Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.48344, 141.02176, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uenohata ikokuma port uenohata ikokuma port japan jp',
    NOW(), NOW(), '12908823', NULL, 'Shinmachi Ikokuma Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.48887, 140.99841, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shinmachi ikokuma port shinmachi ikokuma port japan jp',
    NOW(), NOW(), '12908824', NULL, 'Hebiura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.50572, 140.96845, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hebiura fishing port hebiura fishing port japan jp',
    NOW(), NOW(), '12908852', NULL, 'Oma Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.5294, 140.90458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oma fishing port oma fishing port japan jp',
    NOW(), NOW(), '12908853', NULL, 'Oma Ferry Terminal', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.52597, 140.89907, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'oma ferry terminal oma ferry terminal japan jp',
    NOW(), NOW(), '12908854', NULL, 'Oma Nuclear Power Plant Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.5115, 140.90215, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oma nuclear power plant port oma nuclear power plant port japan jp',
    NOW(), NOW(), '12908861', NULL, 'Okudo Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.49263, 140.90629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okudo port okudo port japan jp',
    NOW(), NOW(), '12908886', NULL, 'Kurosaki Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.51236, 139.94668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kurosaki fishing port kurosaki fishing port japan jp',
    NOW(), NOW(), '12908887', NULL, 'Kanita Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.04769, 140.64623, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kanita port kanita port japan jp',
    NOW(), NOW(), '12908888', NULL, 'Seheji Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.00817, 140.65207, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'seheji fishing port seheji fishing port japan jp',
    NOW(), NOW(), '12908889', NULL, 'Yomogida Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.98439, 140.65716, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yomogida port yomogida port japan jp',
    NOW(), NOW(), '12908890', NULL, 'Ushirogata Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.93335, 140.66648, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ushirogata port ushirogata port japan jp',
    NOW(), NOW(), '12908891', NULL, 'Okunai Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.89136, 140.67864, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okunai port okunai port japan jp',
    NOW(), NOW(), '12908902', NULL, 'Asuka Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.87364, 140.68642, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'asuka port asuka port japan jp',
    NOW(), NOW(), '12908903', NULL, 'Aburakawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.85456, 140.7014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aburakawa fishing port aburakawa fishing port japan jp',
    NOW(), NOW(), '12908904', NULL, 'Nonai Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.85192, 140.81617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nonai port nonai port japan jp',
    NOW(), NOW(), '12908905', NULL, 'Asamushi Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.89248, 140.85914, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'asamushi port asamushi port japan jp',
    NOW(), NOW(), '12908906', NULL, 'Inou Urata Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.96273, 140.8612, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inou urata port inou urata port japan jp',
    NOW(), NOW(), '12908909', NULL, 'Higashi Tazawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.995, 140.91658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'higashi tazawa port higashi tazawa port japan jp',
    NOW(), NOW(), '12908921', NULL, 'Shirasu Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.98447, 140.95095, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shirasu fishing port shirasu fishing port japan jp',
    NOW(), NOW(), '12908922', NULL, 'Mutsu Kominato HigashitakiPort', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.95946, 140.98339, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mutsu kominato higashitakiport mutsu kominato higashitakiport japan jp',
    NOW(), NOW(), '12908923', NULL, 'Kominato Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.94256, 140.97899, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kominato fishing port kominato fishing port japan jp',
    NOW(), NOW(), '12908924', NULL, 'Horikae Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.93495, 140.98978, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horikae fishing port horikae fishing port japan jp',
    NOW(), NOW(), '12908925', NULL, 'Shimizugawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.92629, 141.02293, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimizugawa port shimizugawa port japan jp',
    NOW(), NOW(), '12908926', NULL, 'Kuchihiro Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.91544, 141.04129, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kuchihiro port kuchihiro port japan jp',
    NOW(), NOW(), '12908927', NULL, 'Karibasawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.89762, 141.07885, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karibasawa fishing port karibasawa fishing port japan jp',
    NOW(), NOW(), '12908928', NULL, 'Makado Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.87973, 141.09236, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'makado fishing port makado fishing port japan jp',
    NOW(), NOW(), '12908929', NULL, 'Arito Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    40.90816, 141.18078, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arito fishing port arito fishing port japan jp',
    NOW(), NOW(), '12908930', NULL, 'Yokohama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.08658, 141.24561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yokohama fishing port yokohama fishing port japan jp',
    NOW(), NOW(), '12908931', NULL, 'Hamaokuchi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.19949, 141.26096, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hamaokuchi fishing port hamaokuchi fishing port japan jp',
    NOW(), NOW(), '12908932', NULL, 'Ominato Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.28098, 141.177, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ominato port ominato port japan jp',
    NOW(), NOW(), '12908933', NULL, 'Ominato JMSDF Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.25556, 141.14431, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ominato jmsdf port ominato jmsdf port japan jp',
    NOW(), NOW(), '12908934', NULL, 'Sumichigai Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.20883, 141.09164, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sumichigai fishing port sumichigai fishing port japan jp',
    NOW(), NOW(), '12908935', NULL, 'Kawauchi Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.19772, 140.98768, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kawauchi port kawauchi port japan jp',
    NOW(), NOW(), '12908938', NULL, 'Hinokigawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.18679, 140.95977, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hinokigawa fishing port hinokigawa fishing port japan jp hikawa fishing port',
    NOW(), NOW(), '12908939', NULL, 'Shukanohe Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.1732, 140.93233, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shukanohe fishing port shukanohe fishing port japan jp sukanobe',
    NOW(), NOW(), '12908940', NULL, 'Kakizaki Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.16643, 140.89876, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kakizaki fishing port kakizaki fishing port japan jp',
    NOW(), NOW(), '12908941', NULL, 'Ozawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.16601, 140.87473, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ozawa fishing port ozawa fishing port japan jp',
    NOW(), NOW(), '12908942', NULL, 'Wakinosawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.14475, 140.82458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wakinosawa port wakinosawa port japan jp',
    NOW(), NOW(), '12908943', NULL, 'Kuroiwa Wakinosawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.13571, 140.81741, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kuroiwa wakinosawa port kuroiwa wakinosawa port japan jp',
    NOW(), NOW(), '12908944', NULL, 'Niida Wakinosawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.1326, 140.81545, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'niida wakinosawa port niida wakinosawa port japan jp',
    NOW(), NOW(), '12908945', NULL, 'Kinami Wakinosawa', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.12922, 140.80653, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kinami wakinosawa kinami wakinosawa japan jp',
    NOW(), NOW(), '12908946', NULL, 'Takoda Wakinosawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.13222, 140.79127, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takoda wakinosawa fishing port takoda wakinosawa fishing port japan jp',
    NOW(), NOW(), '12908947', NULL, 'Kusodomari Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    41.14209, 140.77302, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kusodomari fishing port kusodomari fishing port japan jp',
    NOW(), NOW();