INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('10056254', NULL, 'Amaris Hotel Bandara Soekarno Hatta', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.11231, 106.6884, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amaris hotel bandara soekarno hatta amaris hotel bandara soekarno hatta indonesia id',
    NOW(), NOW(), '10097744', NULL, 'Sahid Bandar Lampung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.45832, 105.26059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sahid bandar lampung sahid bandar lampung indonesia id',
    NOW(), NOW(), '10097747', NULL, 'Allium Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.17401, 106.65736, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'allium airport allium airport indonesia id',
    NOW(), NOW(), '10097872', NULL, 'Aston Soll Marina', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.16519, 106.13498, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aston soll marina aston soll marina indonesia id',
    NOW(), NOW(), '10097947', NULL, 'Ibis Styles Jakarta Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.11592, 106.68306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ibis styles jakarta airport ibis styles jakarta airport indonesia id',
    NOW(), NOW(), '10098053', NULL, 'Novotel Banjarmasin Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.44557, 114.76499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novotel banjarmasin airport novotel banjarmasin airport indonesia id',
    NOW(), NOW(), '10106934', NULL, 'Ibis Budget Surabaya Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.28917, 112.7344, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ibis budget surabaya airport ibis budget surabaya airport indonesia id',
    NOW(), NOW(), '10107055', NULL, 'Swiss-Belhotel Harbour Bay', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.15675, 104.00546, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'swiss-belhotel harbour bay swiss-belhotel harbour bay indonesia id',
    NOW(), NOW(), '10114512', NULL, 'Novotel Banjarmasin Airport Opening End Of 2013', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.44557, 114.76499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novotel banjarmasin airport opening end of 2013 novotel banjarmasin airport opening end of 2013 indonesia id',
    NOW(), NOW(), '10126070', NULL, 'Ramada Pudong Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.72718, 121.79457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ramada pudong airport ramada pudong airport indonesia id',
    NOW(), NOW(), '10229300', NULL, 'Pop! Hotel Airport Jakarta', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.14187, 106.65167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pop! hotel airport jakarta pop! hotel airport jakarta indonesia id',
    NOW(), NOW(), '10230574', NULL, 'Aston Soll Marina Hotel & Conference Centre', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.23362, 106.14702, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aston soll marina hotel & conference centre aston soll marina hotel & conference centre indonesia id',
    NOW(), NOW(), '10230724', NULL, 'Aston Marina Hotel & Residence', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.12852, 106.82848, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aston marina hotel & residence aston marina hotel & residence indonesia id',
    NOW(), NOW(), '10233836', NULL, 'Swiss-Belinn Airport Jakarta', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.12149, 106.68606, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'swiss-belinn airport jakarta swiss-belinn airport jakarta indonesia id',
    NOW(), NOW(), '10247071', NULL, 'Hilton Garden Bali Ngurah Rai Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.743, 115.17101, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hilton garden bali ngurah rai airport hilton garden bali ngurah rai airport indonesia id',
    NOW(), NOW(), '10338618', NULL, 'Gili T Resort and Terminal Restaurant', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.35503, 116.04255, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gili t resort and terminal restaurant gili t resort and terminal restaurant indonesia id',
    NOW(), NOW(), '10343624', NULL, 'Pop Hotel Airport Jakarta', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.14183, 106.65165, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pop hotel airport jakarta pop hotel airport jakarta indonesia id',
    NOW(), NOW(), '10943302', NULL, 'Yahukimo Nop Goliath Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.85614, 139.48105, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yahukimo nop goliath airport yahukimo nop goliath airport indonesia id dex,dki,dekai airport,wavd,yahukimo nop goliath airport',
    NOW(), NOW(), '11010247', NULL, 'Bandar Seri Bentan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.05417, 104.48, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar seri bentan bandar seri bentan indonesia id bandar seri bentan',
    NOW(), NOW(), '11054659', NULL, 'Cakrabhuwana Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.75492, 108.53988, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cakrabhuwana airport cakrabhuwana airport indonesia id',
    NOW(), NOW(), '11054660', NULL, 'Bandara Syamsudin Noor', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.43806, 114.75421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandara syamsudin noor bandara syamsudin noor indonesia id',
    NOW(), NOW(), '11153643', NULL, 'Days Hotel & Suites Jakarta Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.15841, 106.64028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'days hotel & suites jakarta airport days hotel & suites jakarta airport indonesia id',
    NOW(), NOW(), '11184549', NULL, 'Harun Thohir Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.72373, 112.67913, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'harun thohir airport harun thohir airport indonesia id bxw,bandar udara harun thohir,bawean airport,harun thohir airport',
    NOW(), NOW(), '11184551', NULL, 'Tiakur Jos Orno Imsula Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.14047, 127.90712, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiakur jos orno imsula airport tiakur jos orno imsula airport indonesia id jio,tiakur jos orno imsula airport',
    NOW(), NOW(), '11184553', NULL, 'Lahat Pagar Alam Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.02404, 103.37826, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lahat pagar alam airport lahat pagar alam airport indonesia id lahat pagar alam airport,pxa',
    NOW(), NOW(), '11184554', NULL, 'Takengon Rembele Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    4.72083, 96.84937, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takengon rembele airport takengon rembele airport indonesia id aeroport de takengon rembele,aéroport de takengon rembele,bandar udara rembele,txe,takengon rembele airport,witk',
    NOW(), NOW(), '11184555', NULL, 'Palopo Lagaligo Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.08464, 120.24519, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palopo lagaligo airport palopo lagaligo airport indonesia id llo,palopo lagaligo airport,wafd',
    NOW(), NOW(), '11184636', NULL, 'Seruyan Kuala Pembuang Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.37634, 112.53691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'seruyan kuala pembuang airport seruyan kuala pembuang airport indonesia id klp,seruyan kuala pembuang airport,wagf',
    NOW(), NOW(), '11185333', NULL, 'Waisai Harbour', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -0.43078, 130.80365, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'waisai harbour waisai harbour indonesia id rjm,waisai harbour',
    NOW(), NOW(), '11185340', NULL, 'Tomia Maranggo Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.76673, 123.91891, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tomia maranggo airport tomia maranggo airport indonesia id aeroport de tomia maranggo,aéroport de tomia maranggo,tqq,tomia maranggo airport',
    NOW(), NOW(), '11524818', NULL, 'Amamapare', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.86628, 136.79498, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amamapare amamapare indonesia id',
    NOW(), NOW(), '11524860', NULL, 'Indonesia Bulk Terminal', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.21483, 106.81966, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'indonesia bulk terminal indonesia bulk terminal indonesia id',
    NOW(), NOW(), '11549302', NULL, 'Jakarta UTC1', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.10478, 106.89405, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jakarta utc1 jakarta utc1 indonesia id',
    NOW(), NOW(), '11549303', NULL, 'Tanjung Priok Car Terminal: IPC', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.10411, 106.9138, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'tanjung priok car terminal: ipc tanjung priok car terminal: ipc indonesia id',
    NOW(), NOW(), '11549304', NULL, 'Jakarta UTC3', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.10339, 106.90418, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jakarta utc3 jakarta utc3 indonesia id',
    NOW(), NOW(), '11549427', NULL, 'Jababeka Port', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.2665, 107.16431, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jababeka port jababeka port indonesia id',
    NOW(), NOW(), '11549514', NULL, 'Tanjung Bara Coal Terminal', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.53231, 117.64637, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'tanjung bara coal terminal tanjung bara coal terminal indonesia id tbct',
    NOW(), NOW(), '11550092', NULL, 'Taboneo', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.73887, 114.56062, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taboneo taboneo indonesia id',
    NOW(), NOW(), '11593958', NULL, 'Pelabuhan Ratu Coal Power Plant', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.02393, 106.54683, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan ratu coal power plant pelabuhan ratu coal power plant indonesia id',
    NOW(), NOW(), '11749267', NULL, 'APT Pranoto Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -0.37306, 117.25682, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'apt pranoto airport apt pranoto airport indonesia id aap,apt pranoto international airport,aji pangeran tumenggung pranoto international airport,samarinda international airport,sungai siring airport,wals',
    NOW(), NOW(), '11749843', NULL, 'Pelabuhan Bakauheni', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.87084, 105.75394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan bakauheni pelabuhan bakauheni indonesia id pelabuhan bakauheni',
    NOW(), NOW(), '11749877', NULL, 'Nongsa Pura Ferry Terminal', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.18834, 104.09463, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'nongsa pura ferry terminal nongsa pura ferry terminal indonesia id nongsa pura,nongsa pura ferry terminal',
    NOW(), NOW(), '11778474', NULL, 'Majalengka Kertajati International Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.64466, 108.16074, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'majalengka kertajati international airport majalengka kertajati international airport indonesia id kjt,majalengka kertajati international airport,wica',
    NOW(), NOW(), '11778488', NULL, 'Morowali Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.20385, 121.65989, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'morowali airport morowali airport indonesia id moh,morowali airport,wafo',
    NOW(), NOW(), '11789255', NULL, 'Matahora Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.29096, 123.63499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'matahora airport matahora airport indonesia id aeroport de matahora,aéroport de matahora,matahora airport,wawd,wni',
    NOW(), NOW(), '11838784', NULL, 'Kebandaran', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.98037, 109.49421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kebandaran kebandaran indonesia id',
    NOW(), NOW(), '11862126', NULL, 'Jemaja Island Letung Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.96427, 105.75457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jemaja island letung airport jemaja island letung airport indonesia id bandar udara letung,jemaja island letung airport,lmu,widl',
    NOW(), NOW(), '11876634', NULL, 'Kasim Terminal', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.31066, 131.02548, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'kasim terminal kasim terminal indonesia id',
    NOW(), NOW(), '11876762', NULL, 'Palembang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.99412, 104.75783, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palembang palembang indonesia id',
    NOW(), NOW(), '11886624', NULL, 'Ujung Pandang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.13068, 119.40345, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ujung pandang ujung pandang indonesia id',
    NOW(), NOW();