INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('11506376', NULL, 'C 830 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.95647, 128.57099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'c 830 heliport c 830 heliport south korea kr',
    NOW(), NOW(), '11506377', NULL, 'C 832 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.56146, 129.41148, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'c 832 heliport c 832 heliport south korea kr',
    NOW(), NOW(), '11506379', NULL, 'Chinhae Naval Academy Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.13336, 128.66603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chinhae naval academy heliport chinhae naval academy heliport south korea kr chinhae naval academy heliport,jinhae haegun sagwanhaggyo hellikobteo,진해 해군 사관학교 헬리콥터',
    NOW(), NOW(), '11506386', NULL, 'Deoksong Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.67056, 127.11016, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'deoksong heliport deoksong heliport south korea kr',
    NOW(), NOW(), '11506444', NULL, 'Ganghwa Do Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.76749, 126.43716, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ganghwa do heliport ganghwa do heliport south korea kr',
    NOW(), NOW(), '11506446', NULL, 'H 122 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.90138, 126.73559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 122 heliport h 122 heliport south korea kr',
    NOW(), NOW(), '11506447', NULL, 'H 127 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.93328, 126.72705, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 127 heliport h 127 heliport south korea kr',
    NOW(), NOW(), '11506448', NULL, 'H 128 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.9546, 126.6772, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 128 heliport h 128 heliport south korea kr',
    NOW(), NOW(), '11506449', NULL, 'H 172 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.86371, 126.80899, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 172 heliport h 172 heliport south korea kr',
    NOW(), NOW(), '11506450', NULL, 'H 173 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.90758, 126.87571, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 173 heliport h 173 heliport south korea kr h 173 heliport,rk6m',
    NOW(), NOW(), '11506451', NULL, 'H 173A Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.91179, 126.87894, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 173a heliport h 173a heliport south korea kr',
    NOW(), NOW(), '11506453', NULL, 'H 177 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.83571, 126.80715, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 177 heliport h 177 heliport south korea kr',
    NOW(), NOW(), '11506455', NULL, 'H 202 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.94114, 126.9699, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 202 heliport h 202 heliport south korea kr',
    NOW(), NOW(), '11506456', NULL, 'H 209 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.75126, 127.0262, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 209 heliport h 209 heliport south korea kr',
    NOW(), NOW(), '11506457', NULL, 'H 211 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.76834, 127.04006, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 211 heliport h 211 heliport south korea kr',
    NOW(), NOW(), '11506458', NULL, 'H 220A Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.93952, 127.05741, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 220a heliport h 220a heliport south korea kr',
    NOW(), NOW(), '11506459', NULL, 'H 221 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.92168, 127.08603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 221 heliport h 221 heliport south korea kr',
    NOW(), NOW(), '11506460', NULL, 'H 233 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    38.24115, 127.10836, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 233 heliport h 233 heliport south korea kr',
    NOW(), NOW(), '11506461', NULL, 'H 245 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.51673, 127.22806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 245 heliport h 245 heliport south korea kr',
    NOW(), NOW(), '11506462', NULL, 'H 247 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.76311, 127.0056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 247 heliport h 247 heliport south korea kr h 247 heliport,rk09',
    NOW(), NOW(), '11506463', NULL, 'H 248 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.69908, 127.04417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 248 heliport h 248 heliport south korea kr',
    NOW(), NOW(), '11506464', NULL, 'H 250 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.52493, 126.79068, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 250 heliport h 250 heliport south korea kr',
    NOW(), NOW(), '11506465', NULL, 'H 263 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.909, 127.08031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 263 heliport h 263 heliport south korea kr',
    NOW(), NOW(), '11506467', NULL, 'H 302 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.55977, 127.54135, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 302 heliport h 302 heliport south korea kr h 302 heliport,rka8',
    NOW(), NOW(), '11506468', NULL, 'H 310 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.996, 127.50411, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 310 heliport h 310 heliport south korea kr h 310 heliport,rk94',
    NOW(), NOW(), '11506469', NULL, 'H 401 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.45389, 127.97331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 401 heliport h 401 heliport south korea kr',
    NOW(), NOW(), '11506470', NULL, 'H 502 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.3016, 127.47961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 502 heliport h 502 heliport south korea kr h 502 heliport,rk96',
    NOW(), NOW(), '11506471', NULL, 'H 508 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.79728, 127.20791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 508 heliport h 508 heliport south korea kr',
    NOW(), NOW(), '11506474', NULL, 'H 704 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.97576, 126.80494, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 704 heliport h 704 heliport south korea kr',
    NOW(), NOW(), '11506475', NULL, 'H 809 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.19701, 129.14902, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'h 809 heliport h 809 heliport south korea kr h 809 heliport,rk4w',
    NOW(), NOW(), '11506480', NULL, 'Incheon Coast Guard Academy Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.51754, 126.49704, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheon coast guard academy heliport incheon coast guard academy heliport south korea kr',
    NOW(), NOW(), '11506481', NULL, 'Irwol San Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.80333, 129.10129, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'irwol san heliport irwol san heliport south korea kr',
    NOW(), NOW(), '11506488', NULL, 'Mangyong Dae Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.42084, 127.04348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mangyong dae heliport mangyong dae heliport south korea kr',
    NOW(), NOW(), '11506491', NULL, 'Mukhojin Ni Port Helipads', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.54036, 129.11461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mukhojin ni port helipads mukhojin ni port helipads south korea kr',
    NOW(), NOW(), '11506516', NULL, 'N 308 Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.68259, 125.436, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'n 308 heliport n 308 heliport south korea kr',
    NOW(), NOW(), '11506524', NULL, 'Onnam Ni Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.29417, 127.13238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onnam ni heliport onnam ni heliport south korea kr',
    NOW(), NOW(), '11506527', NULL, 'Palgong San Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.02454, 128.69617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palgong san heliport palgong san heliport south korea kr',
    NOW(), NOW(), '11506528', NULL, 'Pangmi Army Barracks Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.87384, 126.83407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pangmi army barracks heliport pangmi army barracks heliport south korea kr',
    NOW(), NOW(), '11506530', NULL, 'Pier 8 Helipad', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.11819, 129.07019, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pier 8 helipad pier 8 helipad south korea kr',
    NOW(), NOW(), '11506532', NULL, 'Poseung Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.99299, 126.80685, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'poseung heliport poseung heliport south korea kr',
    NOW(), NOW(), '11506535', NULL, 'Saemal Army Barracks Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.781, 126.754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saemal army barracks heliport saemal army barracks heliport south korea kr',
    NOW(), NOW(), '11506544', NULL, 'Taechong Do West Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.83418, 124.69424, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taechong do west heliport taechong do west heliport south korea kr',
    NOW(), NOW(), '11506546', NULL, 'Taejon North Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.37052, 127.3802, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taejon north heliport taejon north heliport south korea kr',
    NOW(), NOW(), '11506553', NULL, 'Uljin Airport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.777, 129.46178, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uljin airport uljin airport south korea kr rktl,ujn,uljin airport,uljinbihaengjang,wei zhen fei xing chang,蔚珍飛行場,울진비행장',
    NOW(), NOW(), '11506554', NULL, 'Uljin Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.78461, 129.45384, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uljin heliport uljin heliport south korea kr',
    NOW(), NOW(), '11506560', NULL, 'Yongmun San Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.55139, 127.61846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yongmun san heliport yongmun san heliport south korea kr',
    NOW(), NOW(), '11506561', NULL, 'Yonhwa Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.95491, 124.63561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yonhwa heliport yonhwa heliport south korea kr',
    NOW(), NOW(), '11506562', NULL, 'Yusong Heliport', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.41535, 127.31983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yusong heliport yusong heliport south korea kr',
    NOW(), NOW(), '11523617', NULL, 'Okchuk-tong Port', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.84766, 124.70706, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okchuk-tong port okchuk-tong port south korea kr',
    NOW(), NOW(), '11523640', NULL, 'Ha-ri Port', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.72812, 126.28743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ha-ri port ha-ri port south korea kr',
    NOW(), NOW();