INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12952990', NULL, 'Honjomachi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.73766, 140.81217, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'honjomachi fishing port honjomachi fishing port japan jp',
    NOW(), NOW(), '12952991', NULL, 'Nakatone Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.79508, 140.7249, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nakatone fishing port nakatone fishing port japan jp',
    NOW(), NOW(), '12952992', NULL, 'Askisakicho Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.76193, 140.77291, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'askisakicho fishing port askisakicho fishing port japan jp',
    NOW(), NOW(), '12952993', NULL, 'Shinobicho Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.78031, 140.74073, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shinobicho fishing port shinobicho fishing port japan jp',
    NOW(), NOW(), '12952994', NULL, 'Takadacho Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.76721, 140.76379, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takadacho fishing port takadacho fishing port japan jp',
    NOW(), NOW(), '12952995', NULL, 'Takahama City Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    34.94751, 136.98405, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takahama city port takahama city port japan jp',
    NOW(), NOW(), '12952996', NULL, 'Takaishi Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    34.5308, 135.43165, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takaishi port takaishi port japan jp',
    NOW(), NOW(), '12952997', NULL, 'Kurohae Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.73151, 140.86972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kurohae port kurohae port japan jp',
    NOW(), NOW(), '12952998', NULL, 'Tokawamachi Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.69684, 140.85115, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tokawamachi port tokawamachi port japan jp',
    NOW(), NOW(), '12952999', NULL, 'Naarai Port Choshi Marina', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.7053, 140.83949, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'naarai port choshi marina naarai port choshi marina japan jp',
    NOW(), NOW(), '12953000', NULL, 'Iioka Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.6919, 140.731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iioka fishing port iioka fishing port japan jp',
    NOW(), NOW(), '12953001', NULL, 'Katagae Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.53465, 140.46739, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katagae fishing port katagae fishing port japan jp',
    NOW(), NOW(), '12953002', NULL, 'Ichinomiya River Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.39232, 140.39191, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ichinomiya river port ichinomiya river port japan jp',
    NOW(), NOW(), '12953003', NULL, 'Taito Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.32962, 140.40139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taito fishing port taito fishing port japan jp',
    NOW(), NOW(), '12953004', NULL, 'Boso Marina', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.29912, 140.39366, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'boso marina boso marina japan jp',
    NOW(), NOW(), '12953005', NULL, 'Ohara Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.25213, 140.4056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ohara fishing port ohara fishing port japan jp',
    NOW(), NOW(), '12953006', NULL, 'Iwafune Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.20897, 140.39286, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iwafune fishing port iwafune fishing port japan jp',
    NOW(), NOW(), '12953007', NULL, 'Iwawada Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.1797, 140.36558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iwawada fishing port iwawada fishing port japan jp',
    NOW(), NOW(), '12953871', NULL, 'Onjuku Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.17905, 140.34875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onjuku fishing port onjuku fishing port japan jp',
    NOW(), NOW(), '12953872', NULL, 'Hebara Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.15977, 140.33254, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hebara fishing port hebara fishing port japan jp',
    NOW(), NOW(), '12953873', NULL, 'Katsuura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.15627, 140.33244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura fishing port katsuura fishing port japan jp',
    NOW(), NOW(), '12953874', NULL, 'Katsuura Fishing Port (Sawakura)', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14937, 140.32658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura fishing port (sawakura) katsuura fishing port (sawakura) japan jp',
    NOW(), NOW(), '12953875', NULL, 'Katsuura Fishing Port (Kawazu)', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14526, 140.32626, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura fishing port (kawazu) katsuura fishing port (kawazu) japan jp',
    NOW(), NOW(), '12953876', NULL, 'Katsuura East Fishing Port (Toyohama)', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.15369, 140.32877, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura east fishing port (toyohama) katsuura east fishing port (toyohama) japan jp',
    NOW(), NOW(), '12953877', NULL, 'Katsuura Marina', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13829, 140.31038, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura marina katsuura marina japan jp',
    NOW(), NOW(), '12953878', NULL, 'Katsuura Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14643, 140.31255, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura port katsuura port japan jp',
    NOW(), NOW(), '12953879', NULL, 'Katsuura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14403, 140.3127, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'katsuura fishing port katsuura fishing port japan jp',
    NOW(), NOW(), '12953880', NULL, 'Kushihama Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14988, 140.29656, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kushihama fishing port kushihama fishing port japan jp',
    NOW(), NOW(), '12953881', NULL, 'Matsube Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.14282, 140.28999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'matsube fishing port matsube fishing port japan jp',
    NOW(), NOW(), '12953882', NULL, 'Yoshio Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13714, 140.28699, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yoshio fishing port yoshio fishing port japan jp',
    NOW(), NOW(), '12953883', NULL, 'Ubara Fishing Port (Nageri)', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13379, 140.28009, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ubara fishing port (nageri) ubara fishing port (nageri) japan jp',
    NOW(), NOW(), '12953884', NULL, 'Ubara Fishing Port (Katsuba)', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.1339, 140.27914, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ubara fishing port (katsuba) ubara fishing port (katsuba) japan jp',
    NOW(), NOW(), '12953885', NULL, 'Moriya Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13649, 140.25668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moriya fishing port moriya fishing port japan jp',
    NOW(), NOW(), '12953886', NULL, 'Okitsu East Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13467, 140.2524, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okitsu east fishing port okitsu east fishing port japan jp',
    NOW(), NOW(), '12953887', NULL, 'Okitsu Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.13043, 140.24773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okitsu fishing port okitsu fishing port japan jp',
    NOW(), NOW(), '12953888', NULL, 'Hamanamegawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.12159, 140.2357, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hamanamegawa fishing port hamanamegawa fishing port japan jp',
    NOW(), NOW(), '12953889', NULL, 'Osawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.11643, 140.22048, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'osawa fishing port osawa fishing port japan jp',
    NOW(), NOW(), '12953890', NULL, 'Kominato Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.12128, 140.1946, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kominato fishing port kominato fishing port japan jp',
    NOW(), NOW(), '12953891', NULL, 'Uchiura Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.12339, 140.18514, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uchiura fishing port uchiura fishing port japan jp',
    NOW(), NOW(), '12953892', NULL, 'Amatsu Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.12258, 140.16187, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amatsu fishing port amatsu fishing port japan jp',
    NOW(), NOW(), '12953898', NULL, 'Hamaogi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.11795, 140.14489, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hamaogi fishing port hamaogi fishing port japan jp',
    NOW(), NOW(), '12953899', NULL, 'Fisherina Kamogawa Marina', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.09827, 140.10663, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fisherina kamogawa marina fisherina kamogawa marina japan jp',
    NOW(), NOW(), '12953900', NULL, 'Kamogawa Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.09552, 140.10625, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kamogawa port kamogawa port japan jp',
    NOW(), NOW(), '12953901', NULL, 'Kamogawa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.09179, 140.10475, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kamogawa fishing port kamogawa fishing port japan jp',
    NOW(), NOW(), '12953902', NULL, 'Futomi Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.07685, 140.10104, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'futomi fishing port futomi fishing port japan jp',
    NOW(), NOW(), '12953903', NULL, 'Niemon Ferry Pier', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.07755, 140.10228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'niemon ferry pier niemon ferry pier japan jp',
    NOW(), NOW(), '12953905', NULL, 'Niemonjima Ferry Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.0768, 140.10387, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'niemonjima ferry port niemonjima ferry port japan jp',
    NOW(), NOW(), '12953906', NULL, 'Amatsura FIshing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.07321, 140.08516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amatsura fishing port amatsura fishing port japan jp',
    NOW(), NOW(), '12953907', NULL, 'Komasa Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.06943, 140.08273, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'komasa fishing port komasa fishing port japan jp',
    NOW(), NOW(), '12953908', NULL, 'Tayuzaki Fishing Port', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.06283, 140.07793, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tayuzaki fishing port tayuzaki fishing port japan jp',
    NOW(), NOW();