INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('7289830', NULL, 'Terminal Pasar Sentral', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.54593, 123.05868, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal pasar sentral terminal pasar sentral indonesia id',
    NOW(), NOW(), '7303759', NULL, 'Terminal Bus Mandalika', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.59529, 116.15633, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal bus mandalika terminal bus mandalika indonesia id',
    NOW(), NOW(), '7333752', NULL, 'Tukad Celukapuh', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.5859, 115.063, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tukad celukapuh tukad celukapuh indonesia id tukad celukapuh',
    NOW(), NOW(), '7334231', NULL, 'Banjar Pemalukan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.62037, 115.20785, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'banjar pemalukan banjar pemalukan indonesia id banjar pemalukan',
    NOW(), NOW(), '7336027', NULL, 'Kalimanting', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.5585, 116.2346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalimanting kalimanting indonesia id kalimanting',
    NOW(), NOW(), '7336028', NULL, 'Kalimanting Lauq', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.5603, 116.2375, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalimanting lauq kalimanting lauq indonesia id kalimanting lauq',
    NOW(), NOW(), '7336483', NULL, 'Galukarambu', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.4641, 119.2254, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'galukarambu galukarambu indonesia id galukarambu',
    NOW(), NOW(), '7336574', NULL, 'Lede Kalumbang Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.4098, 119.2462, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lede kalumbang airport lede kalumbang airport indonesia id lapangan terbang tambolaka,tmc,tambolaka airport,watk',
    NOW(), NOW(), '7336589', NULL, 'Pelabuhan Waikelo', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.3884, 119.2189, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan waikelo pelabuhan waikelo indonesia id pelabuhan waikelo',
    NOW(), NOW(), '7337729', NULL, 'Kombandaru', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.7869, 121.6033, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kombandaru kombandaru indonesia id kombandaru',
    NOW(), NOW(), '7338057', NULL, 'Lapangan Terbang Ipi', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.849, 121.6633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lapangan terbang ipi lapangan terbang ipi indonesia id ene,ende airport,h. hasan aroeboesman airport,isi airport,lapangan terbang ipi,wate',
    NOW(), NOW(), '7338066', NULL, 'Pelabuhan Ende', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.8457, 121.6419, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan ende pelabuhan ende indonesia id pelabuhan ende',
    NOW(), NOW(), '7338069', NULL, 'Pelabuhan Ende', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.8551, 121.6384, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan ende pelabuhan ende indonesia id pelabuhan ende',
    NOW(), NOW(), '7338079', NULL, 'Pelabuhan Ipi', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.8549, 121.6634, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan ipi pelabuhan ipi indonesia id pelabuhan ipi',
    NOW(), NOW(), '7339680', NULL, 'Jeliman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.5727, 116.3056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jeliman jeliman indonesia id jeliman',
    NOW(), NOW(), '7351426', NULL, 'Tanjung Purakaliman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.8326, 115.8895, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanjung purakaliman tanjung purakaliman indonesia id tanjung purakaliman',
    NOW(), NOW(), '7351913', NULL, 'Desa Kalimango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.55361, 116.99722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'desa kalimango desa kalimango indonesia id desa kalimango',
    NOW(), NOW(), '7351981', NULL, 'Kalimango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.52212, 116.9954, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalimango kalimango indonesia id kalimango',
    NOW(), NOW(), '7375546', NULL, 'Kalimango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.1108, 111.3034, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalimango kalimango indonesia id kalimango',
    NOW(), NOW(), '7377450', NULL, 'Kalimango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6078, 117.3746, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalimango kalimango indonesia id kalimango',
    NOW(), NOW(), '7377567', NULL, 'Kokar Kalimango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6053, 117.3752, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kokar kalimango kokar kalimango indonesia id kokar kalimango',
    NOW(), NOW(), '7379709', NULL, 'Salukanan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.5151, 120.0531, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salukanan salukanan indonesia id salukanan',
    NOW(), NOW(), '7379853', NULL, 'Salukarondang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.692, 120.1822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salukarondang salukarondang indonesia id salukarondang',
    NOW(), NOW(), '7384476', NULL, 'Koro Salukaia', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.8655, 120.5385, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koro salukaia koro salukaia indonesia id koro salukaia',
    NOW(), NOW(), '7384980', NULL, 'Kalukaluku', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.1986, 118.9679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalukaluku kalukaluku indonesia id kalukaluku',
    NOW(), NOW(), '7385981', NULL, 'Sullukan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.0941, 119.9264, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sullukan sullukan indonesia id sullukan',
    NOW(), NOW(), '7386066', NULL, 'Panglulukan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.1051, 119.9927, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'panglulukan panglulukan indonesia id panglulukan',
    NOW(), NOW(), '7389221', NULL, 'Luku Marina', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -10.2096, 120.1942, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luku marina luku marina indonesia id luku marina',
    NOW(), NOW(), '7389584', NULL, 'Lilimani', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.7771, 120.0556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lilimani lilimani indonesia id lilimani',
    NOW(), NOW(), '7390273', NULL, 'Nanga Limang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6186, 122.2196, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nanga limang nanga limang indonesia id nanga limang',
    NOW(), NOW(), '7390280', NULL, 'Pelabuhan Maumere', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6144, 122.2201, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan maumere pelabuhan maumere indonesia id pelabuhan maumere',
    NOW(), NOW(), '7405996', NULL, 'Bandarangin', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.2231, 112.5403, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarangin bandarangin indonesia id bandarangin',
    NOW(), NOW(), '7405998', NULL, 'Bandarangin Kidul', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.2288, 112.5464, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarangin kidul bandarangin kidul indonesia id bandarangin kidul',
    NOW(), NOW(), '7406761', NULL, 'Pangkung Lukaha', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.2938, 114.9262, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pangkung lukaha pangkung lukaha indonesia id pangkung lukaha',
    NOW(), NOW(), '7411422', NULL, 'Ghalukalolo', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.5376, 119.0013, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ghalukalolo ghalukalolo indonesia id ghalukalolo',
    NOW(), NOW(), '7411451', NULL, 'Gallukalogho', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.5444, 119.0154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gallukalogho gallukalogho indonesia id gallukalogho',
    NOW(), NOW(), '7412732', NULL, 'Buttu Kalukalukku', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.7929, 118.8934, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buttu kalukalukku buttu kalukalukku indonesia id buttu kalukalukku',
    NOW(), NOW(), '7429894', NULL, 'Frans Seda Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6391, 122.2386, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'frans seda airport frans seda airport indonesia id bandar udara frans seda,lapangan terbang waioti,mof,maumere airport,watc,wai oti airport',
    NOW(), NOW(), '7439878', NULL, 'Dolok Portortoran', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.06074, 98.65357, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dolok portortoran dolok portortoran indonesia id dolok portortoran',
    NOW(), NOW(), '7443148', NULL, 'Kelurahan Nangalimang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.64833, 122.20111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kelurahan nangalimang kelurahan nangalimang indonesia id kelurahan nangalimang',
    NOW(), NOW(), '7455879', NULL, 'Doro Kilimani', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.6539, 118.3014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'doro kilimani doro kilimani indonesia id doro kilimani',
    NOW(), NOW(), '7456028', NULL, 'Galukatang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.6262, 119.456, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'galukatang galukatang indonesia id galukatang',
    NOW(), NOW(), '7456033', NULL, 'Dalukabanga', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.6255, 119.4715, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dalukabanga dalukabanga indonesia id dalukabanga',
    NOW(), NOW(), '7456036', NULL, 'Golukadango', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.6326, 119.4698, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'golukadango golukadango indonesia id golukadango',
    NOW(), NOW(), '7456114', NULL, 'Gulukadelo', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.6571, 119.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gulukadelo gulukadelo indonesia id gulukadelo',
    NOW(), NOW(), '7456574', NULL, 'Galukalitu', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.6586, 119.5753, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'galukalitu galukalitu indonesia id galukalitu',
    NOW(), NOW(), '7456627', NULL, 'Lulukalay', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -9.7075, 119.6458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lulukalay lulukalay indonesia id lulukalay',
    NOW(), NOW(), '7458752', NULL, 'Tampa Padang Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.5867, 119.0293, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tampa padang airport tampa padang airport indonesia id bandara tampa padang,lapangan terbang balakalumpang,mju,tampa padang airport,wafj',
    NOW(), NOW(), '7473902', NULL, 'Pelabuhan Hutamela', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.3363, 123.4582, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan hutamela pelabuhan hutamela indonesia id pelabuhan hutamela',
    NOW(), NOW(), '7473903', NULL, 'Pelabuhan Huata', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.3339, 123.4613, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan huata pelabuhan huata indonesia id pelabuhan huata',
    NOW(), NOW();