INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('1839779', NULL, 'Panpopogu', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.36667, 126.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'panpopogu panpopogu south korea kr omsu,panpopogu,panpopogu,ŏmsu,판포포구',
    NOW(), NOW(), '1839877', NULL, 'Chori’p’o', 'Chori''p''o',
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.46222, 126.925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chori’p’o chori''p''o south korea kr chori''p''o,chori’p’o,goshori-ho,goshōri-ho,gosyori ho,gosyōri ho,ojori-p''o,ojori-p’o',
    NOW(), NOW(), '1840073', NULL, 'Ocheon-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.43935, 126.51964, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ocheon-hang ocheon-hang south korea kr och''on-hang,ocheon-hang,och’ŏn-hang,ocheonhang,오천항',
    NOW(), NOW(), '1840255', NULL, 'Noktong-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.525, 127.13194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'noktong-hang noktong-hang south korea kr',
    NOW(), NOW(), '1840937', NULL, 'Mukho-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.54642, 129.11497, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mukho-hang mukho-hang south korea kr boku,boku ko,bokuko-ko,bokuko-kō,mukho-hang',
    NOW(), NOW(), '1841064', NULL, 'Mokpooehangbudu', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.78165, 126.39243, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mokpooehangbudu mokpooehangbudu south korea kr mokp''o-hang,mokpooehangbudu,mokp’o-hang,moppo-ko,moppo-kō,mogpooehangbudu,목포외항부두',
    NOW(), NOW(), '1841163', NULL, 'Mip’o', 'Mip''o',
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.51667, 129.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mip’o mip''o south korea kr',
    NOW(), NOW(), '1841366', NULL, 'Manji Po', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.79222, 128.67389, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manji po manji po south korea kr bochi-ho,boji-ho,bozi ho,bōchi-ho,bōji-ho,bōzi ho,inner harbor,mangch''i-p''o,mangch’i-p’o,manji po',
    NOW(), NOW(), '1841961', NULL, 'Guryongpohang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.98671, 129.55617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'guryongpohang guryongpohang south korea kr guryongpohang,ku ryu po,kuryongp''o,kuryongp''o-hang,kuryongp''o-ko,kuryongp’o,kuryongp’o-hang,kuryongp’o-ko,kuyongp''o-hang,kuyongp’o-hang,kyuryuho-ko,kyūryūho-kō,gulyongpohang,구룡포항',
    NOW(), NOW(), '1842024', NULL, 'Kunsan-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.98028, 126.63944, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kunsan-hang kunsan-hang south korea kr gunzan bay,gunzan-ko,gunzan-kō,kunsan po,kunsan-hang',
    NOW(), NOW(), '1842649', NULL, 'Santo Group', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.05683, 127.35363, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santo group santo group south korea kr geomun island,geomun-do,komun-do,kyobun-to,kyobun-tō,kyomon,kyomon-gunto,kyomon-guntō,kyomun islands,kŏmun-do,port hamilton island,santo group',
    NOW(), NOW(), '1842744', NULL, 'Geojinhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    38.44306, 128.46111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'geojinhang geojinhang south korea kr geojinhang,kojin road,kojin-hang,kojin-pakchi,kyoshin-hakuchi,kyosin hakuti,kŏjin-hang,kŏjin-pakchi,geojinhang,거진항',
    NOW(), NOW(), '1843168', NULL, 'Gangguhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.35568, 129.39051, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gangguhang gangguhang south korea kr eguchi bay,gangguhang,kanggu-hang,koko-ko,kōkō-kō,gang-guhang,강구항',
    NOW(), NOW(), '1843209', NULL, 'Gampohang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.80616, 129.50598, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gampohang gampohang south korea kr gampohang,kamp''o-hang,kampo ko,kamp’o-hang,kanho-ho,kanp''o-hang,kanpo ko,kanp’o-hang,gampohang,감포항',
    NOW(), NOW(), '1843562', NULL, 'Incheonhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.46423, 126.60864, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'incheonhang incheonhang south korea kr chemulpo anchorage,chemulpo bay,inch''on harbor,inch''on-hang,incheon-hang,incheonhang,inch’on harbor,inch’ŏn-hang,jinsen-ko,jinsen-kō,incheonhang,인천항',
    NOW(), NOW(), '1844075', NULL, 'Hubo-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.67811, 129.45693, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hubo-hang hubo-hang south korea kr hubo-hang,hup''o-hang,hup’o-hang,koho ko,koho-ko,kōho-kō,hupohang,후포항',
    NOW(), NOW(), '1844440', NULL, 'Hansan-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.8, 128.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hansan-hang hansan-hang south korea kr hansan-hang,hansang hang,kansan-ko,kansan-kō',
    NOW(), NOW(), '1844531', NULL, 'Kanetsu-ri', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.05833, 126.91111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kanetsu-ri kanetsu-ri south korea kr hamnyol-li,hamyol-li,hamyŏl-li,kanetsu-ri',
    NOW(), NOW(), '1845019', NULL, 'Toguyogu Ko', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.83544, 128.42858, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'toguyogu ko toguyogu ko south korea kr ch''ungmu-hang,chungmoo,ch’ungmu-hang,t''ongyong-hang,t''ongyong-p''o,toei-ko,toguyogu ko,tōei-kō,t’ongyŏng-hang,t’ongyŏng-p’o,chungmuhang,충무항',
    NOW(), NOW(), '1845140', NULL, 'Chumunjin-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.89002, 128.831, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chumunjin-hang chumunjin-hang south korea kr chumonjin road,chumonshin-ko,chumunjin-hang,chūmonshin-kō,tyumonsin ko,tyūmonsin kō,jumunjinhang,주문진항',
    NOW(), NOW(), '1845205', NULL, 'Chusan Wan', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.50364, 129.44848, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chusan wan chusan wan south korea kr ch''uksan man,ch''uksan-hang,ch''uksan-p''o,chosen-ho,chucksan-man,chukusan bay,chukusan po,chusan po,chusan wan,chusan-ho,chuzan ho,chūsan-ho,ch’uksan man,ch’uksan-hang,ch’uksan-p’o,tyusan po,tyūsan po',
    NOW(), NOW(), '1845592', NULL, 'Samch’ŏk-hang', 'Samch''ok-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.43566, 129.19149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'samch’ŏk-hang samch''ok-hang south korea kr chongna-hang,chŏngna-hang,samch''ok-hang,samch’ŏk-hang,teira-ko,teira-kō,tiera ko,samcheoghang,삼척항',
    NOW(), NOW(), '1845909', NULL, 'Chŏdong-hang', 'Chodong-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.49426, 130.91207, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chŏdong-hang chodong-hang south korea kr chodong-hang,chŏdong-hang,jeodonghang,저동항',
    NOW(), NOW(), '1845974', NULL, 'Tise Po', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.83639, 128.70833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tise po tise po south korea kr center harbor,chise ho,chise-p''o,chise-p’o,seji-p''o,seji-p’o,tise ho,tise po',
    NOW(), NOW(), '1846067', NULL, 'Chinhae-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.13861, 128.63528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chinhae-hang chinhae-hang south korea kr anguk bay,chinhae-hang,chinhae-ko,chinkai-ko,chinkai-kō,gyogan-wan,gyōgan-wan,haengam-man,henamu bay,henamu wan,hoengam-man,kogan-wan,kōgan-wan,tinkai ko,tinkai kō',
    NOW(), NOW(), '1846262', NULL, 'Cheju-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.52306, 126.53583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cheju-hang cheju-hang south korea kr cheju-hang,saishu-ko,saishū-kō,saisyu ko,saisyū kō',
    NOW(), NOW(), '1846404', NULL, 'Chanshin Po', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.48333, 129.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chanshin po chanshin po south korea kr changsaeng-p''o,changsaeng-p’o,changsaengp''o-hang,changsaengp’o-hang,chanshin po,chosei-ho,chōsei-ho,tyosei ho,tyōsei ho',
    NOW(), NOW(), '1846742', NULL, 'Jamjindo', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.41828, 126.41439, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jamjindo jamjindo south korea kr chamjin-do,chamnaru,jamjindo,sanshin-to,sanshin-tō,sansin to,sansin tō,jamjindo,잠진도',
    NOW(), NOW(), '1846804', NULL, 'Tangsa-do', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.10493, 126.59391, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tangsa-do tangsa-do south korea kr chachi to,chagae-do,chaji-do,chasi-do,cheki to,hangmun-do,harbor entrance island,komon-to,kŏmon-tŏ,shashi to,syasi to,syasi tō,tangsa-do,tyati to,tyati tō,dangsado,당사도',
    NOW(), NOW(), '1883736', NULL, 'Changho-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.28806, 129.31583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'changho-hang changho-hang south korea kr',
    NOW(), NOW(), '1883823', NULL, 'Hwasun-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.23028, 126.32556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hwasun-hang hwasun-hang south korea kr hwasun-hang,hwasunhang,화순항',
    NOW(), NOW(), '1883824', NULL, 'Ch’uja-hang', 'Ch''uja-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.95889, 126.31139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ch’uja-hang ch''uja-hang south korea kr',
    NOW(), NOW(), '1883918', NULL, 'Imwŏnjin-hang', 'Imwonjin-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.22917, 129.345, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'imwŏnjin-hang imwonjin-hang south korea kr imwon-hang,imwonjin-hang,imwŏn-hang,imwŏnjin-hang,im-wonjinhang,임원진항',
    NOW(), NOW(), '1884085', NULL, 'Ayajinhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    38.27235, 128.5578, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ayajinhang ayajinhang south korea kr ayajinhang,ayajinhang,아야진항',
    NOW(), NOW(), '1885837', NULL, 'Yangpohang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.87935, 129.52335, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yangpohang yangpohang south korea kr yangp''o-hang,yangpohang,yangp’o-hang,yangpohang,양포항',
    NOW(), NOW(), '1885840', NULL, 'Taebyŏn-hang', 'Taebyon-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.22028, 129.22972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taebyŏn-hang taebyon-hang south korea kr',
    NOW(), NOW(), '1915519', NULL, 'P’yŏngt’aek-hang', 'P''yongt''aek-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.961, 126.8333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'p’yŏngt’aek-hang p''yongt''aek-hang south korea kr p''yongt''aek-hang,p’yŏngt’aek-hang,pyeongtaeghang,평택항',
    NOW(), NOW(), '1915524', NULL, 'Taesan-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    37.01944, 126.33722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taesan-hang taesan-hang south korea kr daesan hang,taesan-hang',
    NOW(), NOW(), '1915549', NULL, 'Seocheon-maryangpogu', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.12911, 126.50483, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'seocheon-maryangpogu seocheon-maryangpogu south korea kr piin-hang,seocheon-maryangpogu,seocheonmalyangpogu,서천마량포구',
    NOW(), NOW(), '1915583', NULL, 'Gyemahang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    35.38942, 126.40722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gyemahang gyemahang south korea kr gyemahang,kyema-hang,gyemahang,계마항',
    NOW(), NOW(), '1915625', NULL, 'Chuk-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.67556, 125.195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chuk-hang chuk-hang south korea kr',
    NOW(), NOW(), '1915626', NULL, 'Taehŭksando-hang', 'Taehuksando-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.68861, 125.43583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taehŭksando-hang taehuksando-hang south korea kr',
    NOW(), NOW(), '1915646', NULL, 'Wando-hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.31917, 126.75556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wando-hang wando-hang south korea kr',
    NOW(), NOW(), '1915655', NULL, 'Sŏgoch’a-hang', 'Sogoch''a-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.23361, 126.92361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sŏgoch’a-hang sogoch''a-hang south korea kr',
    NOW(), NOW(), '1915657', NULL, 'Aewolhang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    33.46732, 126.32374, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aewolhang aewolhang south korea kr aewol-hang,aewolhang,aewŏl-hang,aewolhang,애월항',
    NOW(), NOW(), '1918021', NULL, 'Gwangyanghang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.90627, 127.67247, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gwangyanghang gwangyanghang south korea kr gwangyanghang,kwangyang-hang,gwang-yanghang,광양항',
    NOW(), NOW(), '1918033', NULL, 'Kohyŏn-hang', 'Kohyon-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.90694, 128.60111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kohyŏn-hang kohyon-hang south korea kr',
    NOW(), NOW(), '1930626', NULL, 'Janghanghang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.0074, 126.68902, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'janghanghang janghanghang south korea kr changhang-hang,janghanghang,janghanghang,장항항',
    NOW(), NOW(), '1930691', NULL, 'T’aean-hang', 'T''aean-hang',
    NULL, 'KR', 'South Korea', NULL, NULL,
    36.91389, 126.22833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 't’aean-hang t''aean-hang south korea kr',
    NOW(), NOW(), '1930785', NULL, 'Yeosu Gu Hang', NULL,
    NULL, 'KR', 'South Korea', NULL, NULL,
    34.7323, 127.73376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yeosu gu hang yeosu gu hang south korea kr ku-hang,yeosu gu hang,yeosu old port,yeosuguhang,여수구항',
    NOW(), NOW();