INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('9952892', NULL, 'Olympic Airportel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.05206, 116.555, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic airportel olympic airportel china cn',
    NOW(), NOW(), '9952894', NULL, 'Crowne Plaza International Airport Beijing', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.07099, 116.5586, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'crowne plaza international airport beijing crowne plaza international airport beijing china cn',
    NOW(), NOW(), '9952912', NULL, 'Langham Place Capital Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.04806, 116.61366, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'langham place capital airport langham place capital airport china cn',
    NOW(), NOW(), '9952975', NULL, 'Super 8 Hotel Beijing Capital International Airport Shunyi X', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.10672, 116.54321, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'super 8 hotel beijing capital international airport shunyi x super 8 hotel beijing capital international airport shunyi x china cn',
    NOW(), NOW(), '9953019', NULL, 'Beijing Aulympic Airport Hotel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.05645, 116.58035, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beijing aulympic airport hotel beijing aulympic airport hotel china cn',
    NOW(), NOW(), '9953026', NULL, 'Olympic Airport Hotel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.04577, 116.59109, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic airport hotel olympic airport hotel china cn',
    NOW(), NOW(), '9953056', NULL, 'Somerset Harbour Court', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    38.92337, 121.64867, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'somerset harbour court somerset harbour court china cn',
    NOW(), NOW(), '9953084', NULL, 'Grand Park Hotel (previously called Harbour Plaza)', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    25.04619, 102.6967, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand park hotel (previously called harbour plaza) grand park hotel (previously called harbour plaza) china cn',
    NOW(), NOW(), '9957958', NULL, 'Pullman Guangzhou Baiyun Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.39054, 113.30408, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pullman guangzhou baiyun airport pullman guangzhou baiyun airport china cn',
    NOW(), NOW(), '9964372', NULL, 'Crowne Plaza Harbourview', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.45377, 118.07729, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'crowne plaza harbourview crowne plaza harbourview china cn',
    NOW(), NOW(), '9970503', NULL, 'Pullman Guangzhou Baiyun Airport(Deluxe)', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.39151, 113.2981, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pullman guangzhou baiyun airport(deluxe) pullman guangzhou baiyun airport(deluxe) china cn',
    NOW(), NOW(), '9987500', NULL, 'Limandai', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.454, 97.8781, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limandai limandai china cn limandai,li man dai,李曼呆',
    NOW(), NOW(), '9987746', NULL, 'Tonglukan', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.6732, 97.7666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tonglukan tonglukan china cn tonglukan,tong lu kan,同路坎',
    NOW(), NOW(), '10005419', NULL, 'Liman', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    25.2723, 106.209, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'liman liman china cn liman,li man,里满',
    NOW(), NOW(), '10010499', NULL, 'Lukanjiao', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    23.4334, 105.116, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukanjiao lukanjiao china cn lukanjiao,lu kan jiao,路坎脚',
    NOW(), NOW(), '10018269', NULL, 'Wulukai', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    26.9928, 105.207, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wulukai wulukai china cn wulukai,wu lu kai,乌路开',
    NOW(), NOW(), '10033523', NULL, 'Dalukan', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    27.4037, 108.461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dalukan dalukan china cn dalukan,da lu kan,大路坎',
    NOW(), NOW(), '10036166', NULL, 'Lukanjiao', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.7965, 103.07, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukanjiao lukanjiao china cn lukanjiao,lu kan jiao,路坎脚',
    NOW(), NOW(), '10047655', NULL, 'Liman', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    25.5814, 108.053, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'liman liman china cn liman,li man,里满',
    NOW(), NOW(), '10049629', NULL, 'Dalukan', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    27.0081, 108.563, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dalukan dalukan china cn dalukan,da lu kan,大路坎',
    NOW(), NOW(), '10098276', NULL, 'Hotel Indigo Xiamen Harbour', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.45144, 118.07646, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hotel indigo xiamen harbour hotel indigo xiamen harbour china cn',
    NOW(), NOW(), '10098285', NULL, 'Millennium Harbourview', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.4512, 118.08257, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'millennium harbourview millennium harbourview china cn',
    NOW(), NOW(), '10098319', NULL, 'Grand Mercure Qingdao Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    36.26997, 120.39025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand mercure qingdao airport grand mercure qingdao airport china cn',
    NOW(), NOW(), '10098389', NULL, 'The Oct Harbour Marriott Ap', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.52556, 113.98933, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'the oct harbour marriott ap the oct harbour marriott ap china cn',
    NOW(), NOW(), '10098437', NULL, 'Portman Plaza Dong Gang', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    29.87044, 121.56573, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portman plaza dong gang portman plaza dong gang china cn',
    NOW(), NOW(), '10098475', NULL, 'Ztg Grand Hotel Airport Hangzh', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.23196, 120.42673, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ztg grand hotel airport hangzh ztg grand hotel airport hangzh china cn',
    NOW(), NOW(), '10098487', NULL, 'Howard Johnson New Port Resort', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    20.03927, 110.34158, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'howard johnson new port resort howard johnson new port resort china cn',
    NOW(), NOW(), '10098490', NULL, 'Baohua Harbour View', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    20.03101, 110.31718, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'baohua harbour view baohua harbour view china cn',
    NOW(), NOW(), '10105807', NULL, 'Vienna Hotels Pudong Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.1757, 121.7457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vienna hotels pudong airport vienna hotels pudong airport china cn',
    NOW(), NOW(), '10106981', NULL, 'Citic Hotel Beijing Airport (Sino-Swiss)', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.04969, 116.59051, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'citic hotel beijing airport (sino-swiss) citic hotel beijing airport (sino-swiss) china cn',
    NOW(), NOW(), '10108407', NULL, 'Hongqiao Airport (Air China)', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.19337, 121.32479, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hongqiao airport (air china) hongqiao airport (air china) china cn',
    NOW(), NOW(), '10108576', NULL, 'Howard Johnson Hong Qiao Airport Hotel Shanghai', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.1891, 121.41015, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'howard johnson hong qiao airport hotel shanghai howard johnson hong qiao airport hotel shanghai china cn',
    NOW(), NOW(), '10108813', NULL, 'Jinjiang Inn Wenzhou Shuangyu The Terminal', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    28.01966, 120.5999, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'jinjiang inn wenzhou shuangyu the terminal jinjiang inn wenzhou shuangyu the terminal china cn',
    NOW(), NOW(), '10108824', NULL, 'Marina Spa Hotel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    18.22902, 109.49354, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina spa hotel marina spa hotel china cn',
    NOW(), NOW(), '10108854', NULL, 'Boyue Shanghai Hongqiao Airport Hotel Air China', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.19285, 121.3319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'boyue shanghai hongqiao airport hotel air china boyue shanghai hongqiao airport hotel air china china cn',
    NOW(), NOW(), '10109976', NULL, 'Jinjiang Inn Shenzhen Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.64856, 113.8238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jinjiang inn shenzhen airport jinjiang inn shenzhen airport china cn',
    NOW(), NOW(), '10110048', NULL, 'Jinjiang Inn Shanghai New Lingang Harbor', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.88895, 121.87901, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'jinjiang inn shanghai new lingang harbor jinjiang inn shanghai new lingang harbor china cn',
    NOW(), NOW(), '10110067', NULL, 'Xiamen International Airport Garden Hotel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    24.52946, 118.12562, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'xiamen international airport garden hotel xiamen international airport garden hotel china cn',
    NOW(), NOW(), '10110078', NULL, 'South China Harbor View Hotel', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.18043, 120.28418, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'south china harbor view hotel south china harbor view hotel china cn',
    NOW(), NOW(), '10113535', NULL, 'Super 8 Hotel Shanghai Hongqiao Transportation Hub Jiu Du Lu', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.1426, 121.36644, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'super 8 hotel shanghai hongqiao transportation hub jiu du lu super 8 hotel shanghai hongqiao transportation hub jiu du lu china cn',
    NOW(), NOW(), '10114953', NULL, 'Ibis Beijing Capital Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.06229, 116.58512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ibis beijing capital airport ibis beijing capital airport china cn',
    NOW(), NOW(), '10119614', NULL, 'Holiday Inn Express Beijing Airport Zone', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.02306, 116.52823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'holiday inn express beijing airport zone holiday inn express beijing airport zone china cn',
    NOW(), NOW(), '10119944', NULL, 'Super 8 Hotel Shanghai Fengxian Sports Center', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    30.90439, 121.46836, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'super 8 hotel shanghai fengxian sports center super 8 hotel shanghai fengxian sports center china cn',
    NOW(), NOW(), '10119962', NULL, 'Howard Johnson New Port Resort Haikou', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    20.05314, 110.36857, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'howard johnson new port resort haikou howard johnson new port resort haikou china cn',
    NOW(), NOW(), '10119983', NULL, 'Super 8 Hotel Beijing Int''l Airport Shunyi X', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.10091, 116.54416, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'super 8 hotel beijing int''l airport shunyi x super 8 hotel beijing int''l airport shunyi x china cn',
    NOW(), NOW(), '10123113', NULL, 'Dazhong Airport North', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.18569, 121.74457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dazhong airport north dazhong airport north china cn',
    NOW(), NOW(), '10124578', NULL, 'Airport Gr International Business', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    40.06406, 116.57666, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'airport gr international business airport gr international business china cn',
    NOW(), NOW(), '10126954', NULL, 'Dazhong Airport South', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.1515, 121.8054, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dazhong airport south dazhong airport south china cn',
    NOW(), NOW(), '10126956', NULL, 'Airlines Travel Pudong Airport', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    31.17872, 121.78737, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airlines travel pudong airport airlines travel pudong airport china cn',
    NOW(), NOW(), '10127370', NULL, 'Harbour View', NULL,
    NULL, 'CN', 'China', NULL, NULL,
    22.25571, 113.5855, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour view harbour view china cn',
    NOW(), NOW();