INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('1850817', NULL, 'Taketoyo-kō', 'Taketoyo-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.83333, 136.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taketoyo-kō taketoyo-ko japan jp taketoyo-ko,taketoyo-kō',
    NOW(), NOW(), '1850859', NULL, 'Takehara Kō', 'Takehara Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.32946, 132.91551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takehara kō takehara ko japan jp takehara ko,takehara kō,takehara-ko,takehara-kō,zhu yuan gang,竹原港',
    NOW(), NOW(), '1851006', NULL, 'Takasago-kō', 'Takasago-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.73333, 134.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takasago-kō takasago-ko japan jp takasago,takasago-ko,takasago-kō',
    NOW(), NOW(), '1851098', NULL, 'Takamatsu Kō', 'Takamatsu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.35915, 134.05533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takamatsu kō takamatsu ko japan jp takamatsu ko,takamatsu kō,takamatsu-ko,takamatsu-kō,takamatu-ko,takamatu-kô,gao song gang,高松港',
    NOW(), NOW(), '1851147', NULL, 'Takahama-kō', 'Takahama-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.25, 129.31667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takahama-kō takahama-ko japan jp kechi-ura,takahama-ko,takahama-kō',
    NOW(), NOW(), '1851148', NULL, 'Takahama-kō', 'Takahama-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.88215, 132.69996, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takahama-kō takahama-ko japan jp takahama-ko,takahama-kō',
    NOW(), NOW(), '1851213', NULL, 'Taisha Gyokō', 'Taisha Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.4, 132.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taisha gyokō taisha gyoko japan jp taisha gyoko,taisha gyokō,taisha-ko,taisha-kō,taisya ko,da she yu gang,大社漁港',
    NOW(), NOW(), '1851222', NULL, 'Taira-kō', 'Taira-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    26.61667, 128.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taira-kō taira-ko japan jp heira-ko,heira-kō,taira-ko,taira-kō',
    NOW(), NOW(), '1851264', NULL, 'Tago Gyokō', 'Tago Gyoko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.80884, 138.7584, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tago gyokō tago gyoko japan jp tago gyoko,tago gyokō,tago ko,tago-minato,tian zi yu gang,田子魚港',
    NOW(), NOW(), '1851280', NULL, 'Tadotsu Kō', 'Tadotsu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.27738, 133.74152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tadotsu kō tadotsu ko japan jp tadotsu ko,tadotsu kō,tadotsu-ko,tadotsu-kō,tadotu ko,duo du jin gang,多度津港',
    NOW(), NOW(), '1851314', NULL, 'Tachibana Kō', 'Tachibana Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.86667, 134.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tachibana kō tachibana ko japan jp tachibana ko,tachibana kō,tachibana-ko,tachibana-kō,ju gang,橘港',
    NOW(), NOW(), '1851384', NULL, 'Susa-kō', 'Susa-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.62711, 131.60014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'susa-kō susa-ko japan jp susa-ko,susa-kō,susa-wan',
    NOW(), NOW(), '1851425', NULL, 'Sumoto Kō', 'Sumoto Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.34824, 134.90224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sumoto kō sumoto ko japan jp sumoto ko,sumoto kō,sumoto-ko,sumoto-kō,zhou ben gang,洲本港',
    NOW(), NOW(), '1851447', NULL, 'Suminoe Kō', 'Suminoe Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.19515, 130.20872, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'suminoe kō suminoe ko japan jp suminoe ko,suminoe kō,suminoe-ko,suminoe-kō,zhuno jiang gang,住ノ江港',
    NOW(), NOW(), '1851460', NULL, 'Sukumo-wan', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    32.88333, 132.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sukumo-wan sukumo-wan japan jp sukumo-ko,sukumo-wan',
    NOW(), NOW(), '1851771', NULL, 'Shishimi Kō', 'Shishimi Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.51621, 129.31364, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shishimi kō shishimi ko japan jp shikami-ko,shishimi ko,shishimi kō,shishimi-ko,shishimi-kō,sisimi ko,lu jian gang,shishimikou,ししみこう,シシミコウ,鹿見港',
    NOW(), NOW(), '1851932', NULL, 'Shirahama-kō', 'Shirahama-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.9, 139.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shirahama-kō shirahama-ko japan jp shirahama-ko,shirahama-kō,sirahama ko,sirahama kô',
    NOW(), NOW(), '1851973', NULL, 'Shiotsu-kō', 'Shiotsu-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.13539, 135.16873, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shiotsu-kō shiotsu-ko japan jp shiotsu-ko,shiotsu-kō,siotu ko,siotu kō',
    NOW(), NOW(), '1852164', NULL, 'Shimotsu Kō', 'Shimotsu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.1164, 135.13742, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimotsu kō shimotsu ko japan jp shimotsu,shimotsu ko,shimotsu kō,shimotsu ura,shimotsu-ko,shimotsu-ku,shimotsu-kō,simotu ko,xia jin gang,下津港',
    NOW(), NOW(), '1852223', NULL, 'Shimonoseki District', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    33.94173, 130.93672, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimonoseki district shimonoseki district japan jp shimonoseki,shimonoseki district,shimonoseki ko,shimonoseki kō,shimonoseki-ko,shimonoseki-ku,shimonoseki-kō,shimonoseki-minato,simo-no-seki ko,xia guan gang,下関港',
    NOW(), NOW(), '1852350', NULL, 'Shimoda Kō', 'Shimoda Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.66742, 138.95408, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimoda kō shimoda ko japan jp shimoda harbor,shimoda ko,shimoda kō,shimoda-ko,shimoda-kō,simoda ko,simoda kô,xia tian gang,下田港',
    NOW(), NOW(), '1852404', NULL, 'Shimizu-kō', 'Shimizu-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.02218, 138.50784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimizu-kō shimizu-ko japan jp shimizu-ko,shimizu-kō,simizu ko,simizu kô',
    NOW(), NOW(), '1852405', NULL, 'Shimizu-kō', 'Shimizu-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.14406, 135.1966, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimizu-kō shimizu-ko japan jp shimizu-ko,shimizu-kō,simizu ko,simizu kō',
    NOW(), NOW(), '1852406', NULL, 'Shimizu-kō', 'Shimizu-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.77481, 132.9589, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimizu-kō shimizu-ko japan jp shimizu-ko,shimizu-kō,simizu ko,simizu kô',
    NOW(), NOW(), '1852412', NULL, 'Shimizu', NULL,
    NULL, 'JP', 'Japan', NULL, NULL,
    35.01667, 138.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimizu shimizu japan jp ejiri station,shimizu,shimizu eki,shimizu railroad terminal,qing shui,qing shui yi,shimizu,shimizueki,しみず,しみずえき,シミズ,シミズエキ,清水,清水駅',
    NOW(), NOW(), '1852455', NULL, 'Shimajiri-kō', 'Shimajiri-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    27.01667, 127.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimajiri-kō shimajiri-ko japan jp shimajir-wan,shimajiri-ko,shimajiri-kō,simaziri ko,simaziri kô',
    NOW(), NOW(), '1852477', NULL, 'Shimabara Kō', 'Shimabara Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.76667, 130.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shimabara kō shimabara ko japan jp shimabara ko,shimabara kō,shimabara-ko,shimabara-kō,simabara ko,simabara kō,dao yuan gang,shimabarakou,しまばらこう,シマバラコウ,島原港',
    NOW(), NOW(), '1852505', NULL, 'Shikaura Kō', 'Shikaura Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    27.6919, 128.91695, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shikaura kō shikaura ko japan jp shikaura ko,shikaura kō,shikaura-ko,shikaura-kō,lu pu gang,shikaurakou,しかうらこう,シカウラコウ,鹿浦港',
    NOW(), NOW(), '1852516', NULL, 'Shikama-kō', 'Shikama-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.78333, 134.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shikama-kō shikama-ko japan jp himezi ko,shikama-ko,shikama-kō,sikama ko,sikama kô',
    NOW(), NOW(), '1852586', NULL, 'Shibushi-kō', 'Shibushi-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    31.46667, 131.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shibushi-kō shibushi-ko japan jp shibushi-ko,shibushi-kō,sibusi ko,sibusi kō',
    NOW(), NOW(), '1852601', NULL, 'Shibayama-kō', 'Shibayama-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.65984, 134.66765, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shibayama-kō shibayama-ko japan jp shibayama-ko,shibayama-kō,sibayama ko',
    NOW(), NOW(), '1852682', NULL, 'Sesoko-byōchi', 'Sesoko-byochi',
    NULL, 'JP', 'Japan', NULL, NULL,
    26.63333, 127.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sesoko-byōchi sesoko-byochi japan jp sesoki byochi,sesoko byoti,sesoko byōti,sesoko-byochi,sesoko-byōchi,suco harbor',
    NOW(), NOW(), '1852698', NULL, 'Senzaki Kō', 'Senzaki Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.38712, 131.21483, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senzaki kō senzaki ko japan jp senzaki ko,senzaki kō,senzaki-ko,senzaki-kō,xian qi gang,仙崎港',
    NOW(), NOW(), '1852896', NULL, 'Sasebo Kō', 'Sasebo Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.11897, 129.71984, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sasebo kō sasebo ko japan jp sasebo ko,sasebo kō,sasebo-ko,sasebo-kō,sasebokou,zuo shi bao gang,させぼこう,サセボコウ,佐世保港',
    NOW(), NOW(), '1852976', NULL, 'San-kō', 'San-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    27.86667, 128.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san-kō san-ko japan jp',
    NOW(), NOW(), '1853098', NULL, 'Sakito Kō', 'Sakito Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.01514, 129.55877, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakito kō sakito ko japan jp sakito ko,sakito kō,sakito-ko,sakito-kō,qi hu gang,sakitokou,さきとこう,サキトコウ,崎戸港',
    NOW(), NOW(), '1853138', NULL, 'Sakata Kō', 'Sakata Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    38.94125, 139.80528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakata kō sakata ko japan jp sakata ko,sakata kō,sakata-ko,sakata-kō,jiu tian gang,酒田港',
    NOW(), NOW(), '1853178', NULL, 'Sakai Kō', 'Sakai Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.53314, 133.25272, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakai kō sakai ko japan jp sakai ko,sakai kō,sakai-ko,sakai-kō,jing gang,境港',
    NOW(), NOW(), '1853179', NULL, 'Sakai-senboku Kō', 'Sakai-senboku Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.57353, 135.44713, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakai-senboku kō sakai-senboku ko japan jp sakai-ko,sakai-kō,sakai-minato,sakai-senboku ko,sakai-senboku kō,jie quan bei gang,堺泉北港',
    NOW(), NOW(), '1853187', NULL, 'Sakaide Kō', 'Sakaide Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.33595, 133.85715, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sakaide kō sakaide ko japan jp sakaide ko,sakaide kō,sakaide-ko,sakaide-kō,ban chu gang,坂出港',
    NOW(), NOW(), '1853235', NULL, 'Saiki-kō', 'Saiki-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    32.97492, 131.91441, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saiki-kō saiki-ko japan jp saeki ko,saeki kō,saiki-ko,saiki-kō,zuo bo gang,佐伯港',
    NOW(), NOW(), '1853271', NULL, 'Sagi-kō', 'Sagi-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    35.44205, 132.68614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sagi-kō sagi-ko japan jp sagi-ko,sagi-kō,sagi-minato',
    NOW(), NOW(), '1853284', NULL, 'Saganoseki Kō', 'Saganoseki Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.25, 131.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saganoseki kō saganoseki ko japan jp saganoseki ko,saganoseki kō,saganoseki-ko,saganoseki-kō,sagaseki-ko,sagaseki-kō,zuo he guan gang,佐賀関港',
    NOW(), NOW(), '1853370', NULL, 'Ryōtsu Kō', 'Ryotsu Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    38.08333, 138.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ryōtsu kō ryotsu ko japan jp ebisu-ko,ebisu-kō,ryo zu byochi,ryoto-kiwan,ryotsu ko,ryotsu-ko,ryozu ko,ryôzu kô,ryōtsu kō,ryōtsu-kō,liang jin gang,両津港',
    NOW(), NOW(), '1853734', NULL, 'Ōshima Kō', 'Oshima Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.48271, 129.52708, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōshima kō oshima ko japan jp oshima,oshima ko,oshima-ko,da dao gang,ooshimakou,ōshima kō,ōshima-kō,おおしまこう,オオシマコウ,大島港',
    NOW(), NOW(), '1853735', NULL, 'Ōshima-kō', 'Oshima-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.45658, 135.81145, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōshima-kō oshima-ko japan jp kushimoto-ko,kushimoto-kō,oshima-ko,osima ko,osima kō,ōshima-kō',
    NOW(), NOW(), '1853901', NULL, 'Ōsaka Kō', 'Osaka Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.67881, 135.403, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōsaka kō osaka ko japan jp osaka harbor,osaka ko,osaka-ko,da ban gang,ōsaka kō,ōsaka-kō,大阪港',
    NOW(), NOW(), '1853991', NULL, 'Onomichi-itozaki Kō', 'Onomichi-itozaki Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    34.39369, 133.16872, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onomichi-itozaki kō onomichi-itozaki ko japan jp onomichi-itozaki ko,onomichi-itozaki kō,onomichi-ko,onomichi-ku,onomichi-kō,wei dao mi qi gang,尾道糸崎港',
    NOW(), NOW(), '1853997', NULL, 'Ōno-kō', 'Ono-ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    36.61667, 136.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ōno-kō ono-ko japan jp',
    NOW(), NOW(), '1854015', NULL, 'Onoda Kō', 'Onoda Ko',
    NULL, 'JP', 'Japan', NULL, NULL,
    33.97251, 131.16187, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onoda kō onoda ko japan jp onoda ko,onoda kō,onoda-ko,onoda-kō,xiao ye tian gang,小野田港',
    NOW(), NOW();