INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('1713471', NULL, 'Port Gaboc', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    9.86028, 125.6875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port gaboc port gaboc philippines ph port gab,port gabo,port gaboc',
    NOW(), NOW(), '1713585', NULL, 'Fort Pikit', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    7.06667, 124.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fort pikit fort pikit philippines ph fort pikit,pikit,port pikit',
    NOW(), NOW(), '1713816', NULL, 'Escalante Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    10.83333, 123.55, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'escalante harbor escalante harbor philippines ph escalante harbor',
    NOW(), NOW(), '1713994', NULL, 'East Arm Halsey Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.7751, 119.982, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'east arm halsey harbor east arm halsey harbor philippines ph east arm,east arm halsey harbor',
    NOW(), NOW(), '1714526', NULL, 'Doliman', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    15.8082, 119.9601, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'doliman doliman philippines ph doleman,doliman',
    NOW(), NOW(), '1714849', NULL, 'Port Dimalansan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    17.35222, 122.38155, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port dimalansan port dimalansan philippines ph port dimalansan',
    NOW(), NOW(), '1714864', NULL, 'Diliman Creek', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.63333, 121.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'diliman creek diliman creek philippines ph diliman creek',
    NOW(), NOW(), '1714865', NULL, 'Diliman Primero', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    15.0247, 120.95208, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'diliman primero diliman primero philippines ph diliman,diliman primero',
    NOW(), NOW(), '1714866', NULL, 'Diliman', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.65889, 121.07361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'diliman diliman philippines ph diliman,diliman district',
    NOW(), NOW(), '1715042', NULL, 'Casiguran Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    16.2, 122.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'casiguran airport casiguran airport philippines ph cgg,dibet',
    NOW(), NOW(), '1715074', NULL, 'Laguindingan International Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    8.61166, 124.45553, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'laguindingan international airport laguindingan international airport philippines ph cgy,diamond,laguindingan international airport,paliparang pandaigdig ng laguindingan,rpmy,tugpahanang pangkalibutanon sa laguindingan',
    NOW(), NOW(), '1715343', NULL, 'Davao Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    7.05, 125.65, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'davao harbor davao harbor philippines ph davao harbor',
    NOW(), NOW(), '1715429', NULL, 'Dasmariñas River', 'Dasmarinas River',
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.33213, 120.9238, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dasmariñas river dasmarinas river philippines ph dasmarinas,dasmarinas river,dasmariñas,dasmariñas river',
    NOW(), NOW(), '1715430', NULL, 'Dasmariñas', 'Dasmarinas',
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.32944, 120.93667, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'dasmariñas dasmarinas philippines ph dasmarin''jas,dasmarinas,dasmarinas lakanbalen,dasmarines,dasmariñas,dasmariñas lakanbalen,kota dasmarinas,kota dasmariñas,da si ma li ni ya si,daseumalinyaseu,dasmarngas,dasmarynyas,dasumarinyasu,дасмариньяс,داسمارنگاس,داسمارینیاس,ダスマリニャス,达斯马里尼亚斯,다스마리냐스',
    NOW(), NOW(), '1715431', NULL, 'City of Dasmariñas', 'City of Dasmarinas',
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.3209, 120.96452, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'city of dasmariñas city of dasmarinas philippines ph city of dasmarinas,city of dasmariñas,dasmarinas,dasmariñas',
    NOW(), NOW(), '1715938', NULL, 'Dalrymple Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    6.01667, 121.31667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'dalrymple harbor dalrymple harbor philippines ph dalrymple harbor,port tulayan,tulayan harbor',
    NOW(), NOW(), '1715984', NULL, 'Delemono', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    17.4056, 121.3575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delemono delemono philippines ph dalimano,delemono',
    NOW(), NOW(), '1716191', NULL, 'Port of Dagupan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    16.05, 120.31667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port of dagupan port of dagupan philippines ph',
    NOW(), NOW(), '1716445', NULL, 'Port Currimao', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    18.0134, 120.484, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port currimao port currimao philippines ph port currimao',
    NOW(), NOW(), '1716530', NULL, 'Port Culion', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.8872, 120.0244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port culion port culion philippines ph port culion',
    NOW(), NOW(), '1716767', NULL, 'Awang Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    7.16464, 124.21001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'awang airport awang airport philippines ph aeroportul awang,aeropuerto de awang,aeropuertu d''awang,awang airport,cbo,cotabato airport,lapangan terbang cotabato,maes awyr awang,paliparan ng awang,port lotniczy awang,rpwc,san bay awang,sân bay awang,aerodrome d''awang,awan kong gang,aérodrome d''awang,frwdgah awang,ge da ba tuo ji chang,фурудгоҳи овонг,فرودگاه آوانگ,アワン空港,哥打巴托机场',
    NOW(), NOW(), '1716770', NULL, 'Cotabato City', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    7.21667, 124.25, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'cotabato city cotabato city philippines ph bandar a kotawato,cotabato,kuta nu kutawatu,lungsod ng cotabato,lungsod ng kutabato',
    NOW(), NOW(), '1716799', NULL, 'Corregidor Bay', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.3906, 120.58579, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'corregidor bay corregidor bay philippines ph corregidor bay,puertecillo,puertocello',
    NOW(), NOW(), '1716821', NULL, 'Coron Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.9947, 120.1896, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coron harbor coron harbor philippines ph coron harbor',
    NOW(), NOW(), '1716899', NULL, 'Port Contra Costa', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    20.43835, 121.98757, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port contra costa port contra costa philippines ph port contra costa',
    NOW(), NOW(), '1716986', NULL, 'Port Concepcion', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    12.90611, 121.72172, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port concepcion port concepcion philippines ph port concepcion',
    NOW(), NOW(), '1717329', NULL, 'Coal Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    13.2323, 123.9278, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coal harbor coal harbor philippines ph coal harbor',
    NOW(), NOW(), '1717392', NULL, 'Port Ciego', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    8.0649, 116.9977, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port ciego port ciego philippines ph port ciego',
    NOW(), NOW(), '1717505', NULL, 'Cebu Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    10.28333, 123.88333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cebu harbor cebu harbor philippines ph cebu strait',
    NOW(), NOW(), '1717641', NULL, 'Cavite City', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    14.48369, 120.89878, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'cavite city cavite city philippines ph bandar cavite,cavite,cavite city,cavite lakanbalen,ciudad ti cavite,dakbayan sa cavite,kavite,lungsod ng kabite,siyudad na cavite,syudad han cavite,jia mi de,kabite,kavuite,кавите,カヴィテ,甲米地,카비테',
    NOW(), NOW(), '1717739', NULL, 'Cauayan Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    16.93333, 121.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cauayan airport cauayan airport philippines ph cyz,cauayan,rpuy',
    NOW(), NOW(), '1717910', NULL, 'Catbalogan Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.78333, 124.86667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'catbalogan harbor catbalogan harbor philippines ph catbalogan harbor',
    NOW(), NOW(), '1717993', NULL, 'Port Cataingan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.9884, 123.9928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port cataingan port cataingan philippines ph port cataingan,port cataiwgan',
    NOW(), NOW(), '1718054', NULL, 'Port Cataaba', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.02, 119.34028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port cataaba port cataaba philippines ph port cataaba',
    NOW(), NOW(), '1718081', NULL, 'Port Castilla', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    9.71667, 126, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port castilla port castilla philippines ph port castilla',
    NOW(), NOW(), '1718151', NULL, 'Port Casiguran', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    16.25, 122.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port casiguran port casiguran philippines ph port casiguran',
    NOW(), NOW(), '1718213', NULL, 'Port Casambalangan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    18.38333, 122.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port casambalangan port casambalangan philippines ph casamblangen,port casambalangan',
    NOW(), NOW(), '1718318', NULL, 'Port Carmen', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    10.58333, 124.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port carmen port carmen philippines ph port carmen',
    NOW(), NOW(), '1718507', NULL, 'Port Caramoan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    13.81667, 123.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port caramoan port caramoan philippines ph port caramoan',
    NOW(), NOW(), '1718513', NULL, 'Caramay Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    10.16667, 119.23333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'caramay harbor caramay harbor philippines ph caramay harbor',
    NOW(), NOW(), '1718642', NULL, 'Port Capiz', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.575, 122.70861, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port capiz port capiz philippines ph port capiz',
    NOW(), NOW(), '1718989', NULL, 'Port Canoan', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    9.25216, 123.59109, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port canoan port canoan philippines ph port canoan',
    NOW(), NOW(), '1719696', NULL, 'Camiguin Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    9.25361, 124.70694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camiguin airport camiguin airport philippines ph aeroportul camiguin,cgm,camiguin airport,lapangan terbang mambajao,paliparan ng camiguin,port lotniczy camiguin,rpmh,tugpahanan sa camiguin,aerodrome de camiguin,aérodrome de camiguin,frwdgah kamygwyyn,gan mi yin,gan mi yin ji chang,kamigin kong gang,фурудгоҳи комигуеҳин,فرودگاه کامیگوئین,カミギン空港,甘米銀,甘米銀機場',
    NOW(), NOW(), '1720105', NULL, 'Port Calubian', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.4435, 124.4345, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port calubian port calubian philippines ph port calubian',
    NOW(), NOW(), '1720119', NULL, 'Port Calton', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    12.18936, 120.10121, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port calton port calton philippines ph port caltom,port calton',
    NOW(), NOW(), '1720303', NULL, 'Calimanco', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    10.79424, 123.4315, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'calimanco calimanco philippines ph calimanco,calimonoc',
    NOW(), NOW(), '1720310', NULL, 'Calimango River', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    11.10952, 119.42386, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'calimango river calimango river philippines ph calimango,calimango river',
    NOW(), NOW(), '1720403', NULL, 'Calbayog Airport', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    12.06667, 124.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'calbayog airport calbayog airport philippines ph cyp,calbayog,rpvc',
    NOW(), NOW(), '1720629', NULL, 'Calandorang Bay', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    7.99158, 117.06117, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'calandorang bay calandorang bay philippines ph balabac harbor,calandorang bay',
    NOW(), NOW(), '1720936', NULL, 'Caguait Harbor', NULL,
    NULL, 'PH', 'Philippines', NULL, NULL,
    8.93333, 126.3, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'caguait harbor caguait harbor philippines ph caguait harbor',
    NOW(), NOW();