INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('6468445', NULL, 'Marina Mandarin', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2921, 103.8573, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina mandarin marina mandarin singapore sg',
    NOW(), NOW(), '6475037', NULL, 'Conrad Singapore Marina Bay', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2937, 103.8585, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'conrad singapore marina bay conrad singapore marina bay singapore sg conrad singapore marina bay',
    NOW(), NOW(), '6496846', NULL, 'Harbour Ville Hotel', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2727, 103.8282, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour ville hotel harbour ville hotel singapore sg',
    NOW(), NOW(), '6620442', NULL, 'Harbour Front MRT Station', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.26542, 103.82121, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour front mrt station harbour front mrt station singapore sg',
    NOW(), NOW(), '7289766', NULL, 'HarbourFront', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2652, 103.8201, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbourfront harbourfront singapore sg',
    NOW(), NOW(), '8354422', NULL, 'Marina Bay', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.28105, 103.85972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina bay marina bay singapore sg marina da baia,marina da baía,marinos ilanka,marinos įlanka,teluk marina,bin hai wan,malinabei,marina be,xaw ma ri na,मरीना बे,อ่าวมารีนา,濱海灣,마리나베이',
    NOW(), NOW(), '8394304', NULL, 'Marina Bay Street Circuit', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29156, 103.86395, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina bay street circuit marina bay street circuit singapore sg circuit de singapur,circuit urbain de singapour,circuito urbano marina bay,circuito urbano de marina bay,circuito urbano de singapur,circuitul marina bay,circuíto urbano de singapur,litar jalan teluk marina,marina bay,marina bej,marina bej strijt,marinabaai straatrenbaan,singapore street circuit,singaporen katurata,singapuras ielu trase,singapūras ielu trase,sirkuit jalan raya marina bay,bin hai wan shi jie sai dao,shingaporu shi jie dekosu,марина бей,марина бей стрийт,حلبة شارع مارينا باي,シンガポール市街地コース,濱海灣市街賽道',
    NOW(), NOW(), '9853641', NULL, 'Tanah Merah Port', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2632, 103.69321, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanah merah port tanah merah port singapore sg tanah merah ferry port,tanah merah harbour',
    NOW(), NOW(), '9882677', NULL, 'Marina Bay Sands', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.28411, 103.85976, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina bay sands marina bay sands singapore sg',
    NOW(), NOW(), '9957779', NULL, 'Crowne Plaza Changi Airport Hotel', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.35027, 103.98552, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'crowne plaza changi airport hotel crowne plaza changi airport hotel singapore sg',
    NOW(), NOW(), '9958305', NULL, 'Marina Mandarin Deluxe', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29083, 103.85998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina mandarin deluxe marina mandarin deluxe singapore sg',
    NOW(), NOW(), '9958402', NULL, 'Mandarin Oriental Premier Harbour', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29055, 103.8583, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mandarin oriental premier harbour mandarin oriental premier harbour singapore sg',
    NOW(), NOW(), '10105277', NULL, 'Marina Bay Sands (Grand Club)', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.28406, 103.85971, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina bay sands (grand club) marina bay sands (grand club) singapore sg',
    NOW(), NOW(), '10106223', NULL, 'Swissotel Stamford (Classic Harbour Vw)', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.2931, 103.85342, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'swissotel stamford (classic harbour vw) swissotel stamford (classic harbour vw) singapore sg',
    NOW(), NOW(), '10106228', NULL, 'Marina Mandarin (Executive Deluxe)', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29095, 103.86004, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina mandarin (executive deluxe) marina mandarin (executive deluxe) singapore sg',
    NOW(), NOW(), '10109650', NULL, 'One 15 Marina Club', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.24529, 103.83978, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'one 15 marina club one 15 marina club singapore sg',
    NOW(), NOW(), '10125115', NULL, 'Ritz Carlton Millenia (Deluxe Marina)', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29031, 103.85994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ritz carlton millenia (deluxe marina) ritz carlton millenia (deluxe marina) singapore sg',
    NOW(), NOW(), '10128872', NULL, 'Pan Pacific Singapore (Harbour Studio)', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29244, 103.85841, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'pan pacific singapore (harbour studio) pan pacific singapore (harbour studio) singapore sg',
    NOW(), NOW(), '10174139', NULL, 'Marina Mandarin Exec Dlx Marina Bay', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29083, 103.85998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina mandarin exec dlx marina bay marina mandarin exec dlx marina bay singapore sg',
    NOW(), NOW(), '11185300', NULL, 'Marina Bay Cruise Centre Singapore', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.26564, 103.86052, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina bay cruise centre singapore marina bay cruise centre singapore singapore sg mcr,marina bay cruise centre singapore,xin jia po bin hai wan you lun zhong xin,新加坡濱海灣郵輪中心',
    NOW(), NOW(), '11524256', NULL, 'Singapore Container Terminal', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.28328, 103.7736, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'singapore container terminal singapore container terminal singapore sg',
    NOW(), NOW(), '11749727', NULL, 'Main Wharf', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.26781, 103.83612, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'main wharf main wharf singapore sg',
    NOW(), NOW(), '12047155', NULL, 'Tanah Merah Ferry Terminal', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.31417, 103.98843, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'tanah merah ferry terminal tanah merah ferry terminal singapore sg',
    NOW(), NOW(), '12747039', NULL, 'Republic of Singapore Yacht Club', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29381, 103.76169, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'republic of singapore yacht club republic of singapore yacht club singapore sg',
    NOW(), NOW(), '12954144', NULL, 'ONE 15 Marina Sentosa Cove', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.24566, 103.84052, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'one 15 marina sentosa cove one 15 marina sentosa cove singapore sg one°15 marina sentosa cove',
    NOW(), NOW(), '13118132', NULL, 'Marina Centre', NULL,
    NULL, 'SG', 'Singapore', NULL, NULL,
    1.29439, 103.85805, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina centre marina centre singapore sg',
    NOW(), NOW();