INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('1901173', NULL, 'New Liberty Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.27325, 115.24433, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'new liberty wharf new liberty wharf malaysia my',
    NOW(), NOW(), '1901174', NULL, 'Liberty Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.27571, 115.24195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'liberty wharf liberty wharf malaysia my',
    NOW(), NOW(), '1901182', NULL, 'Labuan Terminal', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.26528, 115.11944, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'labuan terminal labuan terminal malaysia my',
    NOW(), NOW(), '1903355', NULL, 'Tanah Puteh Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.55806, 110.37694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanah puteh wharf tanah puteh wharf malaysia my',
    NOW(), NOW(), '1903361', NULL, 'Pelabuhan Pending', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.55472, 110.38944, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan pending pelabuhan pending malaysia my',
    NOW(), NOW(), '1903385', NULL, 'Ban Hock Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.56056, 110.33806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ban hock wharf ban hock wharf malaysia my',
    NOW(), NOW(), '1903386', NULL, 'Dockyard Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.56028, 110.3375, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dockyard wharf dockyard wharf malaysia my',
    NOW(), NOW(), '1903387', NULL, 'Lorna Doone Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.56111, 110.33917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lorna doone wharf lorna doone wharf malaysia my',
    NOW(), NOW(), '1903388', NULL, 'Main Bazaar Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.55944, 110.34333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'main bazaar wharf main bazaar wharf malaysia my',
    NOW(), NOW(), '1903389', NULL, 'KTS Wharf', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.55861, 110.35139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kts wharf kts wharf malaysia my',
    NOW(), NOW(), '1904214', NULL, 'Pelabuhan Kelang Utara', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    3.07361, 101.42083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan kelang utara pelabuhan kelang utara malaysia my',
    NOW(), NOW(), '1942214', NULL, 'Lumut Naval Base', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.23333, 100.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lumut naval base lumut naval base malaysia my lumut naval base',
    NOW(), NOW(), '6301209', NULL, 'Bintulu Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    3.12385, 113.02047, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bintulu airport bintulu airport malaysia my aeroportul bintulu,btu,bandar udara bintulu,bintulu,bintulu airport,lapangan terbang bintulu,maes awyr bintulu,port lotniczy bintulu,san bay bintulu,sân bay bintulu,wbgb,aeroport de bintulu,aeroporto di bintulu,aéroport de bintulu,bintouru kong gang,frwdgah byntwlw,min dou lu ji chang,pintulu vanurti nilaiyam,фурудгоҳи бинтулу,فرودگاه بینتولو,பிந்துலு வானூர்தி நிலையம்,ビントゥル空港,民都魯機場',
    NOW(), NOW(), '6301210', NULL, 'Miri Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.32201, 113.98681, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miri airport miri airport malaysia my aeroportul miri,aeropuerto de miri,bandar udara miri,flughafen miri,lapangan terbang miri,myy,miri,miri airport,port lotniczy miri,san bay miri,sân bay miri,wbgr,aeroport de miri,aeroporto di miri,aéroport de miri,frwdgah myry,mei li ji chang,mili gonghang,miri kong gang,miri vanurti nilaiyam,فرودگاه میری,மிரி வானூர்தி நிலையம்,ミリ空港,美里機場,미리 공항',
    NOW(), NOW(), '6301211', NULL, 'Sibu Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.2616, 111.98532, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sibu airport sibu airport malaysia my aeroportul sibu,bandar udara sibu,lapangan terbang sibu,port lotniczy sibu,sbw,san bay sibu,sibu,sibu airport,sân bay sibu,wbgs,aeroport de sibu,aeroporto di sibu,aéroport de sibu,cipu vanurti nilaiyam,frwdgah sybw,shi wu ji chang,shibu kong gang,sybw ayrpwrt,фурудгоҳи сибу,سيبو ايرپورت,فرودگاه سیبو,சிபு வானூர்தி நிலையம்,シブ空港,诗巫机场',
    NOW(), NOW(), '6301212', NULL, 'Labuan Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.3, 115.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'labuan airport labuan airport malaysia my aeroportul labuan,bandar udara labuan,lbu,labuan,labuan airport,lapangan terbang labuan,port lotniczy labuan,san bay labuan,sân bay labuan,wbkl,aeroport de labuan,aeroporto di labuan,aéroport de labuan,frwdgah labwan,lapuvan pannattu vanurti nilaiyam,na min,na min guo ji ji chang,rabuan kong gang,фурудгоҳи лобуон,فرودگاه لابوآن,லபுவான் பன்னாட்டு வானூர்தி நிலையம்,ラブアン空港,納閩,纳闽国际机场',
    NOW(), NOW(), '6301213', NULL, 'Sandakan Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.9009, 118.05949, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sandakan airport sandakan airport malaysia my aeroporto di sandakan,aeroportul sandakan,bandar udara sandakan,flughafen sandakan,lapangan terbang sandakan,maes awyr sandakan,port lotniczy sandakan,sdk,san bay sandakan,sandakan,sandakan airport,sân bay sandakan,wbks,aeroport de sandakan,aéroport de sandakan,frwdgah sandakan,sandakan kong gang,shan da gen guo ji ji chang,фурудгоҳи сондокон,فرودگاه سانداکان,サンダカン空港,山打根国际机场',
    NOW(), NOW(), '6301214', NULL, 'Kudat Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.91667, 116.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kudat airport kudat airport malaysia my kud,kudat,kudat airport,wbkt',
    NOW(), NOW(), '6301215', NULL, 'Tawau Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.31337, 118.12195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tawau airport tawau airport malaysia my aeroport de tawau,aeroporto di tawau,aeroportul tawau,aeropuerto de tawau,aeropuertu de tawau,aéroport de tawau,bandar udara tawau,flughafen tawau,lapangan terbang tawau,port lotniczy tawau,san bay tawau,sân bay tawau,twu,tawau airport,wbkw,dou hu guo ji ji chang,frwdgah tawayw,tawau kong gang,фурудгоҳи товоеҳв,فرودگاه تاوائو,タワウ空港,斗湖国际机场',
    NOW(), NOW(), '6301252', NULL, 'Sitiawan Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.21667, 100.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sitiawan airport sitiawan airport malaysia my aeroportul sitiawan,bandar udara sitiawan,lapangan terbang sitiawan,maes awyr sitiawan,swy,sitiawan,sitiawan airport,wmba,frwdgah sytyawan,shi zhao yuan ji chang,фурудгоҳи ситиовон,فرودگاه سیتیاوان,实兆远机场,實兆遠機場',
    NOW(), NOW(), '6301253', NULL, 'Kota Bharu Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.16685, 102.29301, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kota bharu airport kota bharu airport malaysia my kbr,wmkc',
    NOW(), NOW(), '6301254', NULL, 'Sultan Haji Ahmad Shah Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    3.77539, 103.20906, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sultan haji ahmad shah airport sultan haji ahmad shah airport malaysia my kua,sultan haji ahmad shah airport,wmkd',
    NOW(), NOW(), '6301255', NULL, 'Kuala Lumpur International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.74558, 101.70992, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'kuala lumpur international airport kuala lumpur international airport malaysia my aeroport international de kuala lumpur,aeroporto internacional de kuala lumpur,aeroporto internazionale di kuala lumpur,aeroportul international kuala lumpur,aeroportul internațional kuala lumpur,aeropuerto internacional de kuala lumpur,aeropuertu internacional de kuala lumpur,aéroport international de kuala lumpur,bandar udara antarbangsa kuala lumpur,bandar udara internasional kuala lumpur,bandara internasional kuala lumpur,bandhar udara internasional kuala lumpur,diethnes aerodromio kouala loumpour,flughafen kuala lumpur,internacia flughaveno kuala-lumpuro,kul,kit-lung-po koet-chi ki-chhong,kit-lùng-po koet-chi kî-chhòng,kuala lumpur internaitional airport,kuala lumpur internasionale lughawe,kuala lumpur international airport,kuala lumpur uluslararasi havalimani,kuala lumpur uluslararası havalimanı,kuala lumpur flygplats,kuala lumpur internasjonale lufthavn,kuala lumpur nemzetkoezi repueloter,kuala lumpur nemzetközi repülőtér,kuala lumpuri rahvusvaheline lennujaam,kuala lumpurin kansainvaelinen lentoasema,kuala lumpurin kansainvälinen lentoasema,kvala lumpuro tarptautinis oro uostas,kvala lumpūro tarptautinis oro uostas,lapangan terbang antarabangsa kuala lumpur,maes awyr rhyngwladol kuala lumpur,mezhdunarodnyj aehroport kuala-lumpur,mezinarodni letiste kuala lumpur,mezinárodní letiště kuala lumpur,mizhnarodnij aeroport «kuala-lumpur»,mizhnarodny aehraport kuala-lumpur,palabuahan udaro internasional kuala lumpur,port lotniczy kuala lumpur,san bay quoc te kuala lumpur,sepang/kl international airport,sân bay quốc tế kuala lumpur,tóʼahidiilį́į́łchíidi chidí naatʼaʼí ńdinibįįhígi,wmkk,frwdgah byn‌almlly kwalalampwr,ji long po guo ji ji chang,kolalampur pannattu vanurti nilaiyam,kuallalumpuleu gugjegonghang,kuararunpuru guo ji kong gang,kuyalalamapura antarjatika bimanabandara,kvalalampura antararastriya vimanatala,mtar kwalalmbwr aldwly,nml htʻwph hbynlʼwmy sl qwʼlh lwmpwr,tha xakasyan nanachati kawlalampexr,διεθνές αεροδρόμιο κουάλα λουμπούρ,международный аэропорт куала-лумпур,міжнародний аеропорт «куала-лумпур»,міжнародны аэрапорт куала-лумпур,נמל התעופה הבינלאומי של קואלה לומפור,فرودگاه بین‌المللی کوالالامپور,مطار كوالالمبور الدولى,مطار كوالالمبور الدولي,کوالالمپور انٹرنیشنل ایئرپورٹ,क्वालालंपूर आंतरराष्ट्रीय विमानतळ,কুয়ালালামপুর আন্তর্জাতিক বিমানবন্দর,கோலாலம்பூர் பன்னாட்டு வானூர்தி நிலையம்,ക്വാലാലമ്പൂർ അന്താരാഷ്ട്ര വിമാനതാവളം,කවාලාලමපර ජාත‍යනතර ගවනතොටපළ,ක්වාලාලම්පූර් ජාත්‍යන්තර ගුවන්තොටුපළ,ท่าอากาศยานนานาชาติกัวลาลัมเปอร์,ကွာလာလမ်ပူ အပြည်ပြည်ဆိုင်ရာ လေဆိပ်,ᱠᱩᱣᱟᱞᱟ ᱞᱟᱢᱯᱩᱨ ᱡᱮᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱩᱰᱟᱹᱱ ᱰᱟᱹᱦᱤ,クアラルンプール国際空港,吉隆坡国际机场,吉隆坡國際機場,쿠알라룸푸르 국제공항',
    NOW(), NOW(), '6301256', NULL, 'Langkawi International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.32973, 99.72867, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'langkawi international airport langkawi international airport malaysia my aeroport international de langkawi,aeroporto di pulau-langkawi,aeroportul international langkawi,aeroportul internațional langkawi,aeropuerto internacional de langkawi,aéroport international de langkawi,bandar udara internasional langkawi,flughafen langkawi,lgk,langkawi international airport,langkawi uluslararasi havalimani,langkawi uluslararası havalimanı,langkawi internasjonale lufthavn,langkawin kansainvaelinen lentoasema,langkawin kansainvälinen lentoasema,lapangan terbang antarabangsa langkawi,maes awyr rhyngwladol langkawi,port lotniczy langkawi,san bay quoc te langkawi,sân bay quốc tế langkawi,wmkl,fu luo jiao yi guo ji ji chang,langkawi gugjegonghang,lankavi pannattu vanurti nilaiyam,rankaui guo ji kong gang,tha xakasyan nanachati langka wi,фурудгоҳи бин‌алмилалӣ лонгкови,فرودگاه بین‌المللی لانگکاوی,லங்காவி பன்னாட்டு வானூர்தி நிலையம்,ท่าอากาศยานนานาชาติลังกาวี,ランカウイ国際空港,浮羅交怡國際機場,랑카위 국제공항',
    NOW(), NOW(), '6301257', NULL, 'Penang International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.29714, 100.27686, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'penang international airport penang international airport malaysia my aeroporto internacional de penang,aeroporto internazionale di penang,aeroportul international penang,aeroportul internațional penang,aeropuerto internacional de penang,aeropuertu internacional de penang - malasia,bandar udara internasional pulau pinang,bayan lepas international airport,flughafen penang,lapangan terbang antarabangsa pulau pinang,maes awyr rhyngwladol penang,mezhdunarodnyj aehroport pinang,mizhnarodnij aeroport pinang,pen,penang international airport,penang uluslararasi havalimani,penang uluslararası havalimanı,penang internasjonale lufthavn,penangin kansainvaelinen lentoasema,penangin kansainvälinen lentoasema,port lotniczy penang,san bay quoc te penang,sân bay quốc tế penang,wmkp,aeroport international de penang,aéroport international de penang,bin cheng guo ji ji chang,mtar bynanq aldwly,penan guo ji kong gang,pinang gugjegonghang,pinanku pannattu vanurti nilaiyam,tha xakasyan nanachati pinang,международный аэропорт пинанг,міжнародний аеропорт пінанг,фурудгоҳи бин‌алмилалӣ пнонг,فرودگاه بین‌المللی پنانگ,مطار بينانق الدولي,பினாங்கு பன்னாட்டு வானூர்தி நிலையம்,ท่าอากาศยานนานาชาติปีนัง,ပီနန် အပြည်ပြည်ဆိုင်ရာ လေဆိပ်,ペナン国際空港,檳城國際機場,피낭 국제공항',
    NOW(), NOW(), '6301258', NULL, 'Sultan Abdul Aziz Shah Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    3.13058, 101.54933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sultan abdul aziz shah airport sultan abdul aziz shah airport malaysia my lapangan terbang sultan abdul aziz shah,szb,subang airport,subang international airport/kuala lumpur international airport,subang skypark,wmsa',
    NOW(), NOW(), '6301879', NULL, 'Senai International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    1.64131, 103.66962, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'senai international airport senai international airport malaysia my aeroporto internazionale di johor bahru-senai,aeroportul international senai,aeroportul internațional senai,bandar udara internasional senai,jhb,johore bharu / senai,lapangan terbang antarabangsa senai,maes awyr rhyngwladol senai,mezhdunarodnyj aehroport senaj,port lotniczy johor bahru-senai,san bay quoc te senai,senai international airport,senai internasjonale lufthavn,senain kansainvaelinen lentoasema,senain kansainvälinen lentoasema,sultan ismail international airport,sân bay quốc tế senai,wmkj,aeroport international de senai,aéroport international de senai,cenay pannattu vanurti nilaiyam,mtar synay aldwly,sena''i antarjatika bimanabandara,senai gugjegonghang,shi nai guo ji ji chang,sunai guo ji kong gang,международный аэропорт сенай,фурудгоҳи бин‌алмилалӣ сн,فرودگاه بین‌المللی ثنای,مطار سيناى الدولى,সেনাই আন্তর্জাতিক বিমানবন্দর,செனாய் பன்னாட்டு வானூர்தி நிலையம்,ᱥᱮᱱᱟᱭ ᱡᱮᱡᱟᱹᱛᱤᱭᱟᱹᱨᱤ ᱩᱰᱟᱹᱱ ᱰᱟᱹᱦᱤ,スナイ国際空港,士乃国际机场,士乃國際機場,세나이 국제공항',
    NOW(), NOW(), '6354928', NULL, 'Tioman Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.81789, 104.15949, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tioman airport tioman airport malaysia my tod,wmbt',
    NOW(), NOW(), '6354945', NULL, 'Mulu Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    4.04655, 114.80567, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mulu airport mulu airport malaysia my lapangan terbang mulu,mzv,wbmu,mu lu ji chang,姆鲁机场',
    NOW(), NOW(), '6452629', NULL, 'Sultan Abdul Halim Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.19423, 100.40234, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sultan abdul halim airport sultan abdul halim airport malaysia my aor,sultan abdul halim,sultan abdul halim airport,wmka',
    NOW(), NOW(), '6468350', NULL, 'Pan Pacific Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.75686, 101.7468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pan pacific airport pan pacific airport malaysia my',
    NOW(), NOW(), '6497548', NULL, 'Concorde Inn - Kuala Lumpur International Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.7408, 101.7465, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'concorde inn - kuala lumpur international airport concorde inn - kuala lumpur international airport malaysia my',
    NOW(), NOW(), '6500631', NULL, 'Pan Pacific Kuala Lumpur Airport', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    2.7266, 101.7318, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pan pacific kuala lumpur airport pan pacific kuala lumpur airport malaysia my',
    NOW(), NOW(), '6805011', NULL, 'Ladang Bandar Hin', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.76275, 100.88595, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ladang bandar hin ladang bandar hin malaysia my ladang bandar hin',
    NOW(), NOW(), '6805012', NULL, 'Charok Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.87835, 100.89507, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'charok bandar charok bandar malaysia my charok bandar',
    NOW(), NOW(), '6805013', NULL, 'Kampung Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.74838, 100.89163, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung bandar kampung bandar malaysia my kampung bandar',
    NOW(), NOW(), '6805071', NULL, 'Kampung Hujong Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.77738, 100.75001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung hujong bandar kampung hujong bandar malaysia my kampung hujong bandar',
    NOW(), NOW(), '6807118', NULL, 'Bukit Bandar Sah', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.37366, 100.46414, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bukit bandar sah bukit bandar sah malaysia my bukit bandar sah',
    NOW(), NOW(), '6807282', NULL, 'Kampung Belukar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.16369, 100.40327, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung belukar kampung belukar malaysia my kampung belukar',
    NOW(), NOW(), '6807290', NULL, 'Taman Seri Marina', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.09364, 100.30157, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taman seri marina taman seri marina malaysia my taman seri marina',
    NOW(), NOW(), '6818757', NULL, 'Kampung Terap Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.2857, 100.62903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung terap bandar kampung terap bandar malaysia my kampung terap bandar',
    NOW(), NOW(), '6818890', NULL, 'Kampung Belukar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.46271, 100.30018, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung belukar kampung belukar malaysia my kampung belukar',
    NOW(), NOW(), '6818901', NULL, 'Kampung Belukar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.4637, 100.25871, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung belukar kampung belukar malaysia my kampung belukar',
    NOW(), NOW(), '6819163', NULL, 'Taman Bandar Jaya', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.35141, 100.48211, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taman bandar jaya taman bandar jaya malaysia my taman bandar jaya',
    NOW(), NOW(), '6820173', NULL, 'Kampung Teluk Belukar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.2922, 100.37662, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung teluk belukar kampung teluk belukar malaysia my kampung teluk belukar',
    NOW(), NOW(), '6820190', NULL, 'Kampung Belukar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    6.20217, 100.49654, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung belukar kampung belukar malaysia my kampung belukar',
    NOW(), NOW(), '6823186', NULL, 'Kampung Dock', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.38125, 100.37747, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung dock kampung dock malaysia my kampong dock,kampung dock',
    NOW(), NOW(), '6823216', NULL, 'Gereja Saint Pier', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.41498, 100.34403, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gereja saint pier gereja saint pier malaysia my gereja saint pier',
    NOW(), NOW(), '6848410', NULL, 'Kampung Tok Bandar', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.51028, 100.48564, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kampung tok bandar kampung tok bandar malaysia my kampung tok bandar',
    NOW(), NOW(), '6862002', NULL, 'Bandar Nibong Tebal', NULL,
    NULL, 'MY', 'Malaysia', NULL, NULL,
    5.17209, 100.48134, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar nibong tebal bandar nibong tebal malaysia my bandar nibong tebal',
    NOW(), NOW();