INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('7731355', NULL, 'Obano Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.9, 136.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'obano airport obano airport indonesia id obd,wabr',
    NOW(), NOW(), '7731363', NULL, 'Oksibil Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.90668, 140.62646, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oksibil airport oksibil airport indonesia id aeroport d''oksibil,aeropuerto de oksibil,aéroport d''oksibil,okl,oksibil airport,wajo',
    NOW(), NOW(), '7731364', NULL, 'Okaba Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -8.08822, 139.71899, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'okaba airport okaba airport indonesia id okq,okaba airport,wako',
    NOW(), NOW(), '7731368', NULL, 'Moanamani Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.9834, 136.0833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moanamani airport moanamani airport indonesia id oni,wabd',
    NOW(), NOW(), '7731403', NULL, 'Tjilik Riwut Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.22513, 113.943, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tjilik riwut airport tjilik riwut airport indonesia id aeroportul tjilik riwut,bandar udara tjilik riwut,flughafen palangka raya,lapangan terbang tjilik riwut,pky,panarung airport,port lotniczy palangkaraya-tjilik riwut,san bay tjilik riwut,sân bay tjilik riwut,tjilik riwut airport,wagg,aeroport de tjilik riwut,aéroport de tjilik riwut,frwdgah tylyk rywwt,ji li li wu ji chang,фурудгоҳи тилик рювт,فرودگاه تیلیک ریووت,トゥジリク・リウトゥ空港,吉利里乌机场',
    NOW(), NOW(), '7731408', NULL, 'Pasir Pangaraan Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.84543, 100.37, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pasir pangaraan airport pasir pangaraan airport indonesia id ppr,wide',
    NOW(), NOW(), '7731453', NULL, 'Sugimanuru Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.763, 122.566, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sugimanuru airport sugimanuru airport indonesia id raq,sugimanuru airport,wawr',
    NOW(), NOW(), '7731459', NULL, 'Merdei Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.58333, 133.33299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'merdei airport merdei airport indonesia id rde,wasm',
    NOW(), NOW(), '7731464', NULL, 'Rokot Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.08282, 99.69398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rokot airport rokot airport indonesia id bandar udara rokot,rki,rokot airport,sipora airport,sipura airport,wibr',
    NOW(), NOW(), '7731470', NULL, 'Abresso Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.50845, 134.187, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'abresso airport abresso airport indonesia id rsk,wasc',
    NOW(), NOW(), '7731471', NULL, 'Roti Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -10.4843, 123.374, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'roti airport roti airport indonesia id rti',
    NOW(), NOW(), '7731474', NULL, 'Yuruf Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.63333, 140.933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yuruf airport yuruf airport indonesia id ruf,waje',
    NOW(), NOW(), '7731485', NULL, 'Senggeh Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.43333, 140.817, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senggeh airport senggeh airport indonesia id seh,wajs',
    NOW(), NOW(), '7731486', NULL, 'Sungai Pakning Bengkalis Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.37, 102.14, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sungai pakning bengkalis airport sungai pakning bengkalis airport indonesia id seq,wibs',
    NOW(), NOW(), '7731490', NULL, 'Sanggata Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    0.5, 117.33336, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sanggata airport sanggata airport indonesia id sgq,wrla',
    NOW(), NOW(), '7731499', NULL, 'Sampit H. Asan Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.49919, 112.975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sampit h. asan airport sampit h. asan airport indonesia id aeroport de sampit h. asan,aéroport de sampit h. asan,bandar udara h. asan,lapangan terbang sampit,smq,sampit h. asan airport,waos,frwdgah smpyt,فرودگاه سمپیت',
    NOW(), NOW(), '7731506', NULL, 'Soroako Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.5312, 121.358, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'soroako airport soroako airport indonesia id sqr,soroako airport,waws',
    NOW(), NOW(), '7731517', NULL, 'Trunojoyo Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.02425, 113.89021, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'trunojoyo airport trunojoyo airport indonesia id aeroportul trunojoyo,bandar udara trunojoyo,lapangan terbang trunojoyo,papan anggegana trunojoyo,sup,trunojoyo airport,wart,frwdgah trwnwjwyw,luo shui,фурудгоҳи трунуҷую,فرودگاه ترونوجویو,漯水',
    NOW(), NOW(), '7731534', NULL, 'Tumbang Samba Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.46895, 113.08312, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tumbang samba airport tumbang samba airport indonesia id tbm',
    NOW(), NOW(), '7731546', NULL, 'Sei Bati Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.05248, 103.39255, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sei bati airport sei bati airport indonesia id aeroportul sei bati,bandar udara sei bati,lapangan terbang sei bati,sei bati airport,tjb,wibt,frwdgah sya bty,фурудгоҳи сеё бут,فرودگاه سیا بتی,拉贾·哈吉·阿卜杜拉机场',
    NOW(), NOW(), '7731554', NULL, 'Tiom Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.92556, 138.45538, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiom airport tiom airport indonesia id aeroport de tiom,aéroport de tiom,tmy,tiom airport',
    NOW(), NOW(), '7731555', NULL, 'Tanah Grogot Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.91013, 116.202, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanah grogot airport tanah grogot airport indonesia id tnb,wrlh',
    NOW(), NOW(), '7731559', NULL, 'Teuku Cut Ali Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    3.17104, 97.2886, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'teuku cut ali airport teuku cut ali airport indonesia id tpk,wita',
    NOW(), NOW(), '7731564', NULL, 'Tanjung Santan Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -0.093, 117.439, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanjung santan airport tanjung santan airport indonesia id tsx,walt',
    NOW(), NOW(), '7731567', NULL, 'Teminabuan Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -1.44472, 132.021, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'teminabuan airport teminabuan airport indonesia id txm,wast',
    NOW(), NOW(), '7731573', NULL, 'Ubrub Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.66667, 140.85001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ubrub airport ubrub airport indonesia id ubr,waju',
    NOW(), NOW(), '7731588', NULL, 'Pogogul Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    1.10217, 121.4136, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pogogul airport pogogul airport indonesia id lapangan terbang pogogul,pogogul airport,uol,wamq',
    NOW(), NOW(), '7731610', NULL, 'Waris Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -3.22243, 140.979, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'waris airport waris airport indonesia id wajr,war',
    NOW(), NOW(), '7731616', NULL, 'Wagethe Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -4.04423, 136.278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wagethe airport wagethe airport indonesia id wabg,wet',
    NOW(), NOW(), '7731628', NULL, 'Wasior Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -2.73359, 134.51801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wasior airport wasior airport indonesia id wasw,wsr',
    NOW(), NOW(), '7731651', NULL, 'Senggo Airport', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.69062, 139.34992, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senggo airport senggo airport indonesia id zeg',
    NOW(), NOW(), '7742901', NULL, 'Binanga Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.7487, 98.9095, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'binanga bandar binanga bandar indonesia id binanga bandar',
    NOW(), NOW(), '7742977', NULL, 'Aek Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.7262, 98.8827, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aek bandar aek bandar indonesia id aek bandar',
    NOW(), NOW(), '7742983', NULL, 'Bandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.7239, 98.8856, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar indonesia id badar,bandar',
    NOW(), NOW(), '7743037', NULL, 'Porti', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.6224, 98.9802, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porti porti indonesia id porti',
    NOW(), NOW(), '7743489', NULL, 'Bandar Mariah', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.9785, 98.675, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar mariah bandar mariah indonesia id bandar mariah',
    NOW(), NOW(), '7743519', NULL, 'Bandar Raya', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.9289, 98.623, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar raya bandar raya indonesia id bandar raya',
    NOW(), NOW(), '7743521', NULL, 'Bandarhinalang', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.91978, 98.62651, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarhinalang bandarhinalang indonesia id bandarhinalang,bandarkinalang',
    NOW(), NOW(), '7743796', NULL, 'Bandar Manik', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.8141, 98.8906, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar manik bandar manik indonesia id bandar manik',
    NOW(), NOW(), '7743838', NULL, 'Bandar Huta', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.825, 98.9556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar huta bandar huta indonesia id bandar hoeta,bandar huta',
    NOW(), NOW(), '7743895', NULL, 'Bandar Jawa', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    2.8188, 98.9681, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar jawa bandar jawa indonesia id bandar jawa',
    NOW(), NOW(), '7766018', NULL, 'Sogeciliman', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.4892, 105.8062, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sogeciliman sogeciliman indonesia id sogeciliman',
    NOW(), NOW(), '7780751', NULL, 'Pantai Marina', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.1438, 105.856, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pantai marina pantai marina indonesia id pantai marina',
    NOW(), NOW(), '7780753', NULL, 'Marinaanyer', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.1421, 105.8576, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marinaanyer marinaanyer indonesia id marinaanyer',
    NOW(), NOW(), '7845357', NULL, 'Limangan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.3177, 106.5225, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limangan limangan indonesia id limangan',
    NOW(), NOW(), '7846121', NULL, 'Kecamatan Palabuhanratu', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -6.79111, 106.705, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kecamatan palabuhanratu kecamatan palabuhanratu indonesia id kecamatan palabuhanratu,kecamatan pelabuhanratu',
    NOW(), NOW(), '7847447', NULL, 'Pelabuhan', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.5287, 107.48, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelabuhan pelabuhan indonesia id pelabuhan',
    NOW(), NOW(), '7861037', NULL, 'Talukagung', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -7.2601, 107.0147, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'talukagung talukagung indonesia id talukagung',
    NOW(), NOW(), '7861913', NULL, 'Bandardalam', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.1192, 103.85098, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandardalam bandardalam indonesia id bandar,bandardalam',
    NOW(), NOW(), '7862153', NULL, 'Limangandar', NULL,
    NULL, 'ID', 'Indonesia', NULL, NULL,
    -5.8585, 104.6524, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limangandar limangandar indonesia id limangandar,limaugandar',
    NOW(), NOW();