INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12505090', NULL, 'Prefeitura Municipal de Porto Real', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4193, -44.3023, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'prefeitura municipal de porto real prefeitura municipal de porto real brazil br prefeitura municipal de porto real',
    NOW(), NOW()), ('12505133', NULL, 'Câmara Municipal de Porto Real', 'Camara Municipal de Porto Real',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4143, -44.2955, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'câmara municipal de porto real camara municipal de porto real brazil br camara municipal de porto real,câmara municipal de porto real',
    NOW(), NOW()), ('12506607', NULL, 'Linhares Regional Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.35848, -40.07303, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'linhares regional airport linhares regional airport brazil br aerodromo municipal de linhares,aeródromo municipal de linhares,lhn,linhares regional airport,snln',
    NOW(), NOW()), ('12506970', NULL, 'Cemitério do Aeroporto', 'Cemiterio do Aeroporto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.8277, -41.175, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cemitério do aeroporto cemiterio do aeroporto brazil br cemiterio do aeroporto,cemitério do aeroporto',
    NOW(), NOW()), ('12507060', NULL, 'Cemitério Municipal de Porto das Barcas', 'Cemiterio Municipal de Porto das Barcas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.5101, -40.5602, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cemitério municipal de porto das barcas cemiterio municipal de porto das barcas brazil br cemiterio municipal de porto das barcas,cemitério municipal de porto das barcas',
    NOW(), NOW()), ('12507225', NULL, 'Escola Estadual de Ensino Fundamental e Médio Ana Portela de Sá', 'Escola Estadual de Ensino Fundamental e Medio Ana Portela de Sa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.61941, -40.59889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'escola estadual de ensino fundamental e médio ana portela de sá escola estadual de ensino fundamental e medio ana portela de sa brazil br escola estadual de ensino fundamental e medio ana portela de sa,escola estadual de ensino fundamental e médio ana portela de sá',
    NOW(), NOW()), ('12507546', NULL, 'Escola Municipal de Ensino Fundamental Marinalva Aragão Amorim', 'Escola Municipal de Ensino Fundamental Marinalva Aragao Amorim',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.6168, -40.4595, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'escola municipal de ensino fundamental marinalva aragão amorim escola municipal de ensino fundamental marinalva aragao amorim brazil br escola municipal de ensino fundamental marinalva aragao amorim,escola municipal de ensino fundamental marinalva aragão amorim',
    NOW(), NOW()), ('12507941', NULL, 'Prefeitura Municipal de Porto da Folha', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.91503, -37.2794, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'prefeitura municipal de porto da folha prefeitura municipal de porto da folha brazil br prefeitura municipal de porto da folha',
    NOW(), NOW()), ('12508022', NULL, 'Cemitério Porta do Céu', 'Cemiterio Porta do Ceu',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.02446, -37.46529, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cemitério porta do céu cemiterio porta do ceu brazil br cemiterio porta do ceu,cemitério porta do céu',
    NOW(), NOW()), ('12508255', NULL, 'Aeroporto Veranópolis', 'Aeroporto Veranopolis',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.93545, -51.56771, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto veranópolis aeroporto veranopolis brazil br aeroporto veranopolis,aeroporto veranópolis',
    NOW(), NOW()), ('12508280', NULL, 'Aeroporto Arroio Grande', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -32.22898, -53.05528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto arroio grande aeroporto arroio grande brazil br aeroporto arroio grande',
    NOW(), NOW()), ('12508285', NULL, 'Aeroporto Torres', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.41479, -49.81001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto torres aeroporto torres brazil br aeroporto torres',
    NOW(), NOW()), ('12508286', NULL, 'Policlínica Militar de Porto Alegre', 'Policlinica Militar de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.0377, -51.2195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'policlínica militar de porto alegre policlinica militar de porto alegre brazil br policlinica militar de porto alegre,policlínica militar de porto alegre',
    NOW(), NOW()), ('12508322', NULL, 'Mercado Público Central de Porto Alegre', 'Mercado Publico Central de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.02751, -51.22784, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'mercado público central de porto alegre mercado publico central de porto alegre brazil br mercado publico central de porto alegre,mercado público central de porto alegre',
    NOW(), NOW()), ('12508337', NULL, 'Aeroporto São Sepé', 'Aeroporto Sao Sepe',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.18199, -53.57977, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto são sepé aeroporto sao sepe brazil br aeroporto sao sepe,aeroporto são sepé',
    NOW(), NOW()), ('12508339', NULL, 'Aeroporto Julio de Castilhos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.15334, -53.74274, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto julio de castilhos aeroporto julio de castilhos brazil br aeroporto julio de castilhos',
    NOW(), NOW()), ('12508348', NULL, 'Aeroporto Garibaldi', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.26929, -51.5314, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto garibaldi aeroporto garibaldi brazil br aeroporto garibaldi',
    NOW(), NOW()), ('12508356', NULL, 'Aeroporto Osório', 'Aeroporto Osorio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.90228, -50.24774, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto osório aeroporto osorio brazil br aeroporto osorio,aeroporto osório',
    NOW(), NOW()), ('12508370', NULL, 'Aeroporto Belém Novo', 'Aeroporto Belem Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.18876, -51.1815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto belém novo aeroporto belem novo brazil br aeroporto belem novo,aeroporto belém novo',
    NOW(), NOW()), ('12508372', NULL, 'Aeroporto Palmeira das Missões', 'Aeroporto Palmeira das Missoes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.90167, -53.3299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto palmeira das missões aeroporto palmeira das missoes brazil br aeroporto palmeira das missoes,aeroporto palmeira das missões',
    NOW(), NOW()), ('12508389', NULL, 'Aeroporto Guaporé', 'Aeroporto Guapore',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.89508, -51.8546, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto guaporé aeroporto guapore brazil br aeroporto guapore,aeroporto guaporé',
    NOW(), NOW()), ('12508391', NULL, 'Aeroporto São Luiz Gonzaga', 'Aeroporto Sao Luiz Gonzaga',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.3758, -55.0348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto são luiz gonzaga aeroporto sao luiz gonzaga brazil br aeroporto sao luiz gonzaga,aeroporto são luiz gonzaga',
    NOW(), NOW()), ('12508392', NULL, 'Estação Rodoviária de Porto Lucena', 'Estacao Rodoviaria de Porto Lucena',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.8518, -55.0208, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estação rodoviária de porto lucena estacao rodoviaria de porto lucena brazil br estacao rodoviaria de porto lucena,estação rodoviária de porto lucena',
    NOW(), NOW()), ('12508413', NULL, 'Aeroporto Ibirubá', 'Aeroporto Ibiruba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.60421, -53.07851, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto ibirubá aeroporto ibiruba brazil br aeroporto ibiruba,aeroporto ibirubá',
    NOW(), NOW()), ('12508415', NULL, 'Aeroporto Espumoso', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.73869, -52.85731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto espumoso aeroporto espumoso brazil br aeroporto espumoso',
    NOW(), NOW()), ('12508420', NULL, 'Estação Rodoviária de Portão', 'Estacao Rodoviaria de Portao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.693, -51.2303, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estação rodoviária de portão estacao rodoviaria de portao brazil br estacao rodoviaria de portao,estação rodoviária de portão',
    NOW(), NOW()), ('12508423', NULL, 'Heliponto Santa Casa de Misericórdia de Porto Alegre', 'Heliponto Santa Casa de Misericordia de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.03009, -51.22042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'heliponto santa casa de misericórdia de porto alegre heliponto santa casa de misericordia de porto alegre brazil br heliponto santa casa de misericordia de porto alegre,heliponto santa casa de misericórdia de porto alegre',
    NOW(), NOW()), ('12508429', NULL, 'Hospital Militar de Área de Porto Alegre', 'Hospital Militar de Area de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.01846, -51.19245, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hospital militar de área de porto alegre hospital militar de area de porto alegre brazil br hospital militar de area de porto alegre,hospital militar de área de porto alegre',
    NOW(), NOW()), ('12508430', NULL, 'Aeroporto Nova Prata', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.80424, -51.60161, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto nova prata aeroporto nova prata brazil br aeroporto nova prata',
    NOW(), NOW()), ('12508458', NULL, 'Estação Rodoviária de Porto Alegre', 'Estacao Rodoviaria de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.023, -51.2192, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estação rodoviária de porto alegre estacao rodoviaria de porto alegre brazil br estacao rodoviaria de porto alegre,estação rodoviária de porto alegre',
    NOW(), NOW()), ('12508480', NULL, 'Aeroporto Mostardas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -31.10071, -50.90757, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto mostardas aeroporto mostardas brazil br aeroporto mostardas',
    NOW(), NOW()), ('12508488', NULL, 'Aeroporto Tobias Bacci', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.98066, -52.86423, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto tobias bacci aeroporto tobias bacci brazil br aeroporto tobias bacci',
    NOW(), NOW()), ('12508500', NULL, 'Aeroporto Soledade', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.86414, -52.5401, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto soledade aeroporto soledade brazil br aeroporto soledade',
    NOW(), NOW()), ('12508512', NULL, 'Aeroporto Regional do Vale do Taquari', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.45427, -51.93538, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto regional do vale do taquari aeroporto regional do vale do taquari brazil br aeroporto regional do vale do taquari',
    NOW(), NOW()), ('12508536', NULL, 'Hospital da Brigada Militar de Porto Alegre', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.0979, -51.2511, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hospital da brigada militar de porto alegre hospital da brigada militar de porto alegre brazil br hospital da brigada militar de porto alegre',
    NOW(), NOW()), ('12508546', NULL, 'Aeroporto Dário Brasil Capoano de Oliveira', 'Aeroporto Dario Brasil Capoano de Oliveira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.27738, -54.92478, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto dário brasil capoano de oliveira aeroporto dario brasil capoano de oliveira brazil br aeroporto dario brasil capoano de oliveira,aeroporto dário brasil capoano de oliveira',
    NOW(), NOW()), ('12508548', NULL, 'Aeroporto São Gabriel', 'Aeroporto Sao Gabriel',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.3456, -54.26742, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto são gabriel aeroporto sao gabriel brazil br aeroporto sao gabriel,aeroporto são gabriel',
    NOW(), NOW()), ('12508549', NULL, 'Aeroporto Capão da Canoa', 'Aeroporto Capao da Canoa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.76354, -50.03703, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto capão da canoa aeroporto capao da canoa brazil br aeroporto capao da canoa,aeroporto capão da canoa',
    NOW(), NOW()), ('12508556', NULL, 'Aeroporto Caçapava do Sul', 'Aeroporto Cacapava do Sul',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.54797, -53.46581, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto caçapava do sul aeroporto cacapava do sul brazil br aeroporto cacapava do sul,aeroporto caçapava do sul',
    NOW(), NOW()), ('12508568', NULL, 'Aeroporto Campos Belos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.006, -46.7114, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto campos belos aeroporto campos belos brazil br aeroporto campos belos',
    NOW(), NOW()), ('12508571', NULL, 'Aeroporto Iaciara', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.10736, -46.66706, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto iaciara aeroporto iaciara brazil br aeroporto iaciara',
    NOW(), NOW()), ('12508572', NULL, 'Aeroporto Quirinópolis', 'Aeroporto Quirinopolis',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.44804, -50.40906, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto quirinópolis aeroporto quirinopolis brazil br aeroporto quirinopolis,aeroporto quirinópolis,pista de pouso do aeroporto de quirinopolis-chico anta,pista de pouso do aeroporto de quirinópolis-chico anta',
    NOW(), NOW()), ('12508573', NULL, 'Aeroporto Cavalcante', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.7786, -47.4124, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto cavalcante aeroporto cavalcante brazil br aeroporto cavalcante',
    NOW(), NOW()), ('12508591', NULL, 'Aeroporto Buriti Alegre', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.1161, -49.049, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto buriti alegre aeroporto buriti alegre brazil br aeroporto buriti alegre',
    NOW(), NOW()), ('12508597', NULL, 'Aeroporto Aruanã', 'Aeroporto Aruana',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.9323, -51.048, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto aruanã aeroporto aruana brazil br aeroporto aruana,aeroporto aruanã',
    NOW(), NOW()), ('12508598', NULL, 'Aeroporto Pires do Rio', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.3188, -48.3348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto pires do rio aeroporto pires do rio brazil br aeroporto pires do rio',
    NOW(), NOW()), ('12508603', NULL, 'Aeroporto Mineiros', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.5514, -52.5567, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto mineiros aeroporto mineiros brazil br aeroporto mineiros',
    NOW(), NOW()), ('12508617', NULL, 'Aeroporto Formosa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.556, -47.3446, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto formosa aeroporto formosa brazil br aeroporto formosa',
    NOW(), NOW()), ('12508619', NULL, 'Aeroporto Mozarlândia', 'Aeroporto Mozarlandia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.7706, -50.5642, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto mozarlândia aeroporto mozarlandia brazil br aeroporto mozarlandia,aeroporto mozarlândia',
    NOW(), NOW()), ('12508663', NULL, 'Aeroporto Porangatu', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.4048, -49.1584, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto porangatu aeroporto porangatu brazil br aeroporto porangatu',
    NOW(), NOW());