INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('2149854', NULL, 'Settlement Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.58333, 148.06667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'settlement harbour settlement harbour australia au settlement harbour',
    NOW(), NOW()), ('2150462', NULL, 'Sandridge Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.16667, 146.91667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sandridge paddock bore sandridge paddock bore australia au',
    NOW(), NOW()), ('2151236', NULL, 'Rodds Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.03333, 151.61667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'rodds harbour rodds harbour australia au rodd harbour,rodds harbour',
    NOW(), NOW()), ('2151540', NULL, 'River Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.13333, 146.4, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'river paddock bore river paddock bore australia au',
    NOW(), NOW()), ('2152146', NULL, 'Ram Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.33333, 146.3, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock tank ram paddock tank australia au',
    NOW(), NOW()), ('2152147', NULL, 'Ram Paddock Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.71667, 143.36667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock dam ram paddock dam australia au',
    NOW(), NOW()), ('2152148', NULL, 'Ram Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.16667, 146.36667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock bore ram paddock bore australia au',
    NOW(), NOW()), ('2152149', NULL, 'Ram Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.11667, 143.46667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock bore ram paddock bore australia au',
    NOW(), NOW()), ('2152650', NULL, 'Portwine Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.8, 147.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portwine creek portwine creek australia au',
    NOW(), NOW()), ('2152651', NULL, 'Port Welshpool', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.69917, 146.45312, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port welshpool port welshpool australia au port welshpool,welshpool',
    NOW(), NOW()), ('2152652', NULL, 'Port Stephens Shire', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.72855, 151.89952, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port stephens shire port stephens shire australia au',
    NOW(), NOW()), ('2152653', NULL, 'Port Sorell', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.16652, 146.55283, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port sorell port sorell australia au port sorell,pwrt swrl,порт сорелл,پورت سورل',
    NOW(), NOW()), ('2152654', NULL, 'Portsea', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.32382, 144.7099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portsea portsea australia au portsea',
    NOW(), NOW()), ('2152655', NULL, 'Portree', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.71667, 151.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portree portree australia au',
    NOW(), NOW()), ('2152656', NULL, 'Port Phillip Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.06107, 144.85336, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port phillip bay port phillip bay australia au port phillip,port-fillip,zaliv port-fillip,залив порт-филлип,порт-филлип',
    NOW(), NOW()), ('2152657', NULL, 'Porto Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.5652, 151.2179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto bay porto bay australia au porto bay',
    NOW(), NOW()), ('2152658', NULL, 'Port Melbourne', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.83961, 144.94228, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port melbourne port melbourne australia au sandridge',
    NOW(), NOW()), ('2152659', NULL, 'Port Macquarie', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.43084, 152.90894, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port macquarie port macquarie australia au pqq,port macqarie,port macquarie,port makkuori,port makvori,porth macquarie,bwrt makwary,mai jue li gang,porta makvari,potomakkori,pwrt makwary,pwrt mkwayr,порт маквори,порт маккуори,פורט מקווארי,بورت ماكواري,پورت ماكوارى,پورت مکوایر,پورٹ مکوائری,पोर्ट मक्वारी,პორტ-მაკუარი,ポートマッコリー,麥覺理港,麦觉理港',
    NOW(), NOW()), ('2152660', NULL, 'Port MacDonnell', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.05313, 140.69963, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port macdonnell port macdonnell australia au port macdonnell,port-mak-donnel,порт-мак-доннел',
    NOW(), NOW()), ('2152661', NULL, 'Portlock Island', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.11656, 142.35863, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portlock island portlock island australia au portlock island,portlock islet',
    NOW(), NOW()), ('2152662', NULL, 'Port Latta', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.859, 145.385, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port latta port latta australia au port iatta,port latta',
    NOW(), NOW()), ('2152663', NULL, 'Portland Road', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.58333, 143.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland road portland road australia au',
    NOW(), NOW()), ('2152664', NULL, 'Portland Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.1288, 144.58356, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland downs portland downs australia au portland downs',
    NOW(), NOW()), ('2152665', NULL, 'Portland Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.32903, 141.63625, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland bay portland bay australia au portland bay',
    NOW(), NOW()), ('2152666', NULL, 'Cape Portland', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.75, 147.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cape portland cape portland australia au cape portland',
    NOW(), NOW()), ('2152667', NULL, 'Portland', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.3462, 141.60257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland portland australia au ptj,portland,portlend,портленд,پورٹلینڈ,پورٹلینڈ، وکٹوریہ,پۆرتلەند، ڤیکتۆریا',
    NOW(), NOW()), ('2152668', NULL, 'Portland', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.35709, 149.98148, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland portland australia au portland',
    NOW(), NOW()), ('2152669', NULL, 'Port Kennedy', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.585, 142.21778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kennedy port kennedy australia au',
    NOW(), NOW()), ('2152670', NULL, 'Port Kembla North', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.46667, 150.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla north port kembla north australia au',
    NOW(), NOW()), ('2152671', NULL, 'Port Kembla', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.4818, 150.9012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla port kembla australia au port kembla',
    NOW(), NOW()), ('2152672', NULL, 'Port Huon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.15636, 146.96377, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port huon port huon australia au port huon',
    NOW(), NOW()), ('2152673', NULL, 'Hacking River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.06667, 151.08333, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hacking river hacking river australia au hacking river,port hacking river',
    NOW(), NOW()), ('2152674', NULL, 'Port Hacking', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.06791, 151.12561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hacking port hacking australia au port hacking',
    NOW(), NOW()), ('2152675', NULL, 'Port Franklin', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.68333, 146.26667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port franklin port franklin australia au port franklin,port tranklin',
    NOW(), NOW()), ('2152676', NULL, 'Port Fairy', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.38535, 142.2371, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port fairy port fairy australia au port fairy,port-fehri,порт-фэри',
    NOW(), NOW()), ('2152677', NULL, 'Porters Retreat', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34, 149.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters retreat porters retreat australia au',
    NOW(), NOW()), ('2152678', NULL, 'Porters Mountain', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.73333, 147.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters mountain porters mountain australia au',
    NOW(), NOW()), ('2152679', NULL, 'Porters Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.68333, 144.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters dam porters dam australia au',
    NOW(), NOW()), ('2152680', NULL, 'Porter Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.15, 150.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter creek porter creek australia au',
    NOW(), NOW()), ('2152681', NULL, 'Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.48383, 145.46725, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port douglas port douglas australia au pti,port douglas,port duglas,port-duglas,poteudeogeullaseu,potodagurasu,порт дуглас,порт-дуглас,ポートダグラス,포트더글라스',
    NOW(), NOW()), ('2152682', NULL, 'Port Curtis Junction', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.4, 150.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port curtis junction port curtis junction australia au',
    NOW(), NOW()), ('2152683', NULL, 'Port Campbell', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.61919, 142.99583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port campbell port campbell australia au port campbell,port kehmpbell,порт кэмпбелл',
    NOW(), NOW()), ('2152684', NULL, 'Port Bundaberg', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.76667, 152.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port bundaberg port bundaberg australia au',
    NOW(), NOW()), ('2152685', NULL, 'Port Arthur', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.1458, 147.84366, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port arthur port arthur australia au carnarvon,carnavon,port arthur,port artur,port-artur,porth arthur,a se gang,phxrt xar the xr,poteuaseo,порт артур,порт-артур,พอร์ตอาร์เทอร์,ポート・アーサー,阿瑟港,포트아서',
    NOW(), NOW()), ('2152686', NULL, 'Portarlington', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.11542, 144.65559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portarlington portarlington australia au portarlington,портарлингтон',
    NOW(), NOW()), ('2152687', NULL, 'Port Alma', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.58314, 150.86079, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port alma port alma australia au port alma',
    NOW(), NOW()), ('2152688', NULL, 'Portal Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.41667, 140.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal creek portal creek australia au',
    NOW(), NOW()), ('2152689', NULL, 'Port Albert Entrance', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.75, 146.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port albert entrance port albert entrance australia au',
    NOW(), NOW()), ('2152690', NULL, 'Port Albert', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.66544, 146.68847, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port albert port albert australia au port al''bert,port albert,порт альберт',
    NOW(), NOW()), ('2152898', NULL, 'Plain Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.66667, 143.98333, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'plain paddock well plain paddock well australia au',
    NOW(), NOW());