INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('7281681', NULL, 'Best Western Solar Porto de Galinhas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.43709, -35.0124, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'best western solar porto de galinhas best western solar porto de galinhas brazil br',
    NOW(), NOW()), ('7281830', NULL, 'Bristol Multy Marinas Praia Hotel', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.12351, -34.8239, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bristol multy marinas praia hotel bristol multy marinas praia hotel brazil br',
    NOW(), NOW()), ('7281884', NULL, 'Dorisol Porto de Galinhas Ancorar Suite Hotel', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.48137, -35.0012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dorisol porto de galinhas ancorar suite hotel dorisol porto de galinhas ancorar suite hotel brazil br',
    NOW(), NOW()), ('7282053', NULL, 'Harbor Self Graciosa Hotel', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.3632, -49.0792, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbor self graciosa hotel harbor self graciosa hotel brazil br',
    NOW(), NOW()), ('7282289', NULL, 'Marina Travel Hotel', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.77445, -35.1947, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina travel hotel marina travel hotel brazil br',
    NOW(), NOW()), ('7282311', NULL, 'Hotel Porto do Mar', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.83007, -35.1828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel porto do mar hotel porto do mar brazil br',
    NOW(), NOW()), ('7282314', NULL, 'Porto Ingleses Hotel', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.4319, -48.3957, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto ingleses hotel porto ingleses hotel brazil br',
    NOW(), NOW()), ('7282387', NULL, 'Hotel Quinta do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.459, -39.0606, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel quinta do porto hotel quinta do porto brazil br',
    NOW(), NOW()), ('7282430', NULL, 'Hotel Villa Rasa Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7616, -41.9406, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel villa rasa marina hotel villa rasa marina brazil br',
    NOW(), NOW()), ('7283837', NULL, 'Mercure Apartments Andra dos Reis Porto Bali', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.006, -44.2972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mercure apartments andra dos reis porto bali mercure apartments andra dos reis porto bali brazil br',
    NOW(), NOW()), ('7283917', NULL, 'Marina Porto Abrolhos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.7261, -39.178, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina porto abrolhos marina porto abrolhos brazil br',
    NOW(), NOW()), ('7283923', NULL, 'Hotel Luxor Aeroporto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8264, -43.2334, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel luxor aeroporto hotel luxor aeroporto brazil br',
    NOW(), NOW()), ('7283928', NULL, 'Portalo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.3995, -38.9206, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portalo portalo brazil br',
    NOW(), NOW()), ('7283929', NULL, 'Porto Dajuda Praia', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.4733, -39.0634, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto dajuda praia porto dajuda praia brazil br',
    NOW(), NOW()), ('7283930', NULL, 'Porto do Zimbo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.3798, -38.9169, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto do zimbo porto do zimbo brazil br',
    NOW(), NOW()), ('7283931', NULL, 'Pousada Porto Imperial', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.2196, -44.7212, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pousada porto imperial pousada porto imperial brazil br',
    NOW(), NOW()), ('7283932', NULL, 'Porto Zarpa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.3952, -37.8918, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto zarpa porto zarpa brazil br',
    NOW(), NOW()), ('7283940', NULL, 'Hotel Porto da Lua', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.5761, -38.0013, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel porto da lua hotel porto da lua brazil br',
    NOW(), NOW()), ('7305256', NULL, 'porto seguro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.43082, -39.19373, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto seguro porto seguro brazil br',
    NOW(), NOW()), ('7534511', NULL, 'Sorocaba Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.47789, -47.49046, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sorocaba airport sorocaba airport brazil br aeroporto bertram luiz leupolz,aeroporto estadual de sorocaba,aeroporto de sorocaba,bertram luiz leupolz airport,sdco,sod,sorocaba airport',
    NOW(), NOW()), ('7535479', NULL, 'Estação Rodoviária de Porto Alegre', 'Estacao Rodoviaria de Porto Alegre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.02278, -51.21917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estação rodoviária de porto alegre estacao rodoviaria de porto alegre brazil br estacao rodoviaria de porto alegre,estação rodoviária de porto alegre',
    NOW(), NOW()), ('7535944', NULL, 'Porto de Galinhas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.50417, -35.00111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de galinhas porto de galinhas brazil br porto de galinhas,praia de porto de galinhas',
    NOW(), NOW()), ('7537675', NULL, 'Canal do Portinho', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.04229, -43.57677, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal do portinho canal do portinho brazil br canal do portinho',
    NOW(), NOW()), ('7537694', NULL, 'Morro do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.00275, -43.54685, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'morro do porto morro do porto brazil br morro do porto',
    NOW(), NOW()), ('7537783', NULL, 'Centro Esportivo Miécimo da Silva', 'Centro Esportivo Miecimo da Silva',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91387, -43.55525, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'centro esportivo miécimo da silva centro esportivo miecimo da silva brazil br centro esportivo miecimo da silva,centro esportivo miécimo da silva',
    NOW(), NOW()), ('7538032', NULL, 'Canal do Portelo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.99092, -43.42903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal do portelo canal do portelo brazil br canal do portelo',
    NOW(), NOW()), ('7538064', NULL, 'Santa Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.99642, -43.38115, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa marina santa marina brazil br santa marina',
    NOW(), NOW()), ('7538074', NULL, 'Jacarepagua-Roberto Marinho Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.98597, -43.3709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jacarepagua-roberto marinho airport jacarepagua-roberto marinho airport brazil br aehroport zhakarepagua,aeroporto de jacarepagua,aeroporto de jacarepaguá–roberto marinho,jacarepagua airport,jacarepagua-roberto marinho airport,jacarepagua–roberto marinho airport,jacarepaguá airport,jacarepaguá–roberto marinho airport,rrj,sbjr,аэропорт жакарепагуа',
    NOW(), NOW()), ('7538106', NULL, 'Complexo Esportivo do Autódromo', 'Complexo Esportivo do Autodromo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.97513, -43.39149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'complexo esportivo do autódromo complexo esportivo do autodromo brazil br complexo esportivo do autodromo,complexo esportivo do autódromo',
    NOW(), NOW()), ('7538108', NULL, 'Complexo Esportivo da Cidade do Rock', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.98211, -43.41372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'complexo esportivo da cidade do rock complexo esportivo da cidade do rock brazil br complexo esportivo da cidade do rock',
    NOW(), NOW()), ('7538198', NULL, 'Complexo Esportivo de Deodoro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.85837, -43.40769, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'complexo esportivo de deodoro complexo esportivo de deodoro brazil br complexo esportivo de deodoro',
    NOW(), NOW()), ('7538376', NULL, 'Terminal Méier', 'Terminal Meier',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.90118, -43.27523, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal méier terminal meier brazil br terminal meier,terminal méier',
    NOW(), NOW()), ('7538506', NULL, 'Porto dos Cabritos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0007, -43.32305, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto dos cabritos porto dos cabritos brazil br porto dos cabritos',
    NOW(), NOW()), ('7538510', NULL, 'Marina Barra Clube', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.00364, -43.30628, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina barra clube marina barra clube brazil br marina barra clube',
    NOW(), NOW()), ('7538603', NULL, 'Túnel Coelho Cintra e Marques Porto', 'Tunel Coelho Cintra e Marques Porto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.96041, -43.1761, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'túnel coelho cintra e marques porto tunel coelho cintra e marques porto brazil br tunel coelho cintra e marques porto,túnel coelho cintra e marques porto',
    NOW(), NOW()), ('7538665', NULL, 'Cais do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.89113, -43.21428, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cais do porto cais do porto brazil br cais do porto',
    NOW(), NOW()), ('7538673', NULL, 'Teleporto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91006, -43.20357, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'teleporto teleporto brazil br teleporto',
    NOW(), NOW()), ('7538685', NULL, 'Píer Mauá', 'Pier Maua',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.89313, -43.17933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'píer mauá pier maua brazil br pier maua,píer mauá',
    NOW(), NOW()), ('7538693', NULL, 'Marina da Glória', 'Marina da Gloria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91937, -43.17094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina da glória marina da gloria brazil br marina da gloria,marina da glória',
    NOW(), NOW()), ('7538749', NULL, 'Portuguesa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.79891, -43.20807, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portuguesa portuguesa brazil br portuguesa',
    NOW(), NOW()), ('7538750', NULL, 'Associação Atlética Portuguesa', 'Associacao Atletica Portuguesa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.80135, -43.20854, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'associação atlética portuguesa associacao atletica portuguesa brazil br associacao atletica portuguesa,associação atlética portuguesa',
    NOW(), NOW()), ('7547307', NULL, 'Ribeirão Portinho', 'Ribeirao Portinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4634, -44.48954, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ribeirão portinho ribeirao portinho brazil br ribeirao portinho,ribeirao do portinho,ribeirão portinho,ribeirão do portinho',
    NOW(), NOW()), ('7547373', NULL, 'Escola Marina Graciani Fontanezzi', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4639, -44.3552, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'escola marina graciani fontanezzi escola marina graciani fontanezzi brazil br escola marina graciani fontanezzi',
    NOW(), NOW()), ('7547430', NULL, 'Usina Porto Real', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4257, -44.2877, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'usina porto real usina porto real brazil br usina porto real',
    NOW(), NOW()), ('7547483', NULL, 'Fazenda Porto Simão', 'Fazenda Porto Simao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.4106, -44.3317, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto simão fazenda porto simao brazil br fazenda porto simao,fazenda porto simão',
    NOW(), NOW()), ('7555324', NULL, 'Jardim Portugal', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.3035, -46.2156, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jardim portugal jardim portugal brazil br jardim portugal',
    NOW(), NOW()), ('7555362', NULL, 'Sítio Porta do Céu', 'Sitio Porta do Ceu',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.3343, -46.2467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porta do céu sitio porta do ceu brazil br sitio porta do ceu,stio porta do cu,sítio porta do céu',
    NOW(), NOW()), ('7555374', NULL, 'Stio Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.3288, -46.187, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stio portela stio portela brazil br stio portela',
    NOW(), NOW()), ('7555649', NULL, 'Stio do Portugus', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.348, -46.1657, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stio do portugus stio do portugus brazil br stio do portugus',
    NOW(), NOW()), ('7568635', NULL, 'Porto Grande', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.4146, -48.7426, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto grande porto grande brazil br porto grande',
    NOW(), NOW());