INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3429776', NULL, 'Puerto Ingeniero Morandi', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.90818, -55.13619, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto ingeniero morandi puerto ingeniero morandi argentina ar',
    NOW(), NOW()), ('3429777', NULL, 'Puerto Iguazú', 'Puerto Iguazu',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.59912, -54.57355, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto iguazú puerto iguazu argentina ar eva peron,eva perón,igr,iguassu,iguazu,iguazú,puehrto-iguasu,puerto aguirre,puerto iguasu,puerto iguazu,puerto iguazú,puerto igvasu,puerto-iguasu,bwyrtw jwasyw,pueleutoigwasu,pwrtw ywasw,yi gua su gang,пуерто-іґуасу,пуэрто-игуасу,պուերտո իգուասու,פוארטו איגואסו,بويرتو جواسيو,پورتو یواسو,پوێرتۆ ئیگواسوو,プエルト・イグアス,伊瓜蘇港,푸에르토이과수',
    NOW(), NOW()), ('3429778', NULL, 'Puerto Ibicuy', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.75305, -59.17762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto ibicuy puerto ibicuy argentina ar puerto ibicuy,punta ibicuy',
    NOW(), NOW()), ('3429779', NULL, 'Puerto Helvecia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.05097, -54.64223, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto helvecia puerto helvecia argentina ar puerto helvecia',
    NOW(), NOW()), ('3429780', NULL, 'Puerto Gramajo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.42222, -55.70737, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto gramajo puerto gramajo argentina ar gramajo,puerto gramajo',
    NOW(), NOW()), ('3429781', NULL, 'Puerto Goya', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.16765, -59.33548, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto goya puerto goya argentina ar',
    NOW(), NOW()), ('3429782', NULL, 'Puerto Gisela', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.00692, -55.42367, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto gisela puerto gisela argentina ar gisela,puerto gisela,puerto gisete',
    NOW(), NOW()), ('3429783', NULL, 'Puerto Garuhapé', 'Puerto Garuhape',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.79186, -54.96518, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto garuhapé puerto garuhape argentina ar puerto caruhape,puerto caruhapé,puerto garuhape,puerto garuhapé',
    NOW(), NOW()), ('3429784', NULL, 'Puerto Galileo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.08333, -57.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto galileo puerto galileo argentina ar',
    NOW(), NOW()), ('3429785', NULL, 'Puerto Filipini', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.95125, -58.21146, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto filipini puerto filipini argentina ar puerto filipini,puesto filipini',
    NOW(), NOW()), ('3429786', NULL, 'Puerto Esperanza', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.02267, -54.61356, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto esperanza puerto esperanza argentina ar esperanza,puerto esperanza',
    NOW(), NOW()), ('3429787', NULL, 'Puerto España', 'Puerto Espana',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.04308, -55.44513, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto españa puerto espana argentina ar puerto espana,puerto españa',
    NOW(), NOW()), ('3429788', NULL, 'Puerto Errecaborde', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.89586, -54.62189, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto errecaborde puerto errecaborde argentina ar errecaborda,puerto errecaborde,puerto martin errecaborde,puerto martín errecaborde',
    NOW(), NOW()), ('3429789', NULL, 'Puerto El Zapallar', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.31313, -59.38041, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto el zapallar puerto el zapallar argentina ar puerto el zapallar,puerto zapallar',
    NOW(), NOW()), ('3429790', NULL, 'Puerto Eldorado', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.40843, -54.69463, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto eldorado puerto eldorado argentina ar eldorado,puerto eldorado',
    NOW(), NOW()), ('3429791', NULL, 'Puerto Doce', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.15, -55.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto doce puerto doce argentina ar',
    NOW(), NOW()), ('3429792', NULL, 'Puerto Delicia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.1872, -54.59174, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto delicia puerto delicia argentina ar',
    NOW(), NOW()), ('3429793', NULL, 'Puerto Dalmacia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.87498, -57.87384, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto dalmacia puerto dalmacia argentina ar puerto dalmacia,villa dalmacia',
    NOW(), NOW()), ('3429794', NULL, 'Puerto Cupalén', 'Puerto Cupalen',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.7492, -58.20003, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto cupalén puerto cupalen argentina ar',
    NOW(), NOW()), ('3429795', NULL, 'Puerto Constanza', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.83454, -59.0381, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto constanza puerto constanza argentina ar puerto constanza,puerto evita,punta constanza',
    NOW(), NOW()), ('3429796', NULL, 'Puerto Cazador', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.15906, -55.55578, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto cazador puerto cazador argentina ar',
    NOW(), NOW()), ('3429797', NULL, 'Puerto Catorce de Mayo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.66667, -54.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto catorce de mayo puerto catorce de mayo argentina ar',
    NOW(), NOW()), ('3429798', NULL, 'Puerto Canoas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.70392, -54.42805, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto canoas puerto canoas argentina ar',
    NOW(), NOW()), ('3429799', NULL, 'Puerto Campichuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.6935, -58.18406, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto campichuelo puerto campichuelo argentina ar puerto campichuelo',
    NOW(), NOW()), ('3429800', NULL, 'Puerto Bossetti', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.86529, -54.57044, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto bossetti puerto bossetti argentina ar puerto bossetti',
    NOW(), NOW()), ('3429801', NULL, 'Puerto Bermejo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.92739, -58.50917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto bermejo puerto bermejo argentina ar bermejo,puerto bermejo,timbo',
    NOW(), NOW()), ('3429802', NULL, 'Puerto Basilio', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.25926, -58.43654, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto basilio puerto basilio argentina ar',
    NOW(), NOW()), ('3429803', NULL, 'Avellaneda', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.75536, -54.69824, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'avellaneda avellaneda argentina ar avellaneda,puerto avellaneda',
    NOW(), NOW()), ('3429804', NULL, 'Puerto Artur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.71667, -54.93333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto artur puerto artur argentina ar',
    NOW(), NOW()), ('3429805', NULL, 'Puerto Antequera', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.44203, -58.85116, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto antequera puerto antequera argentina ar puerto antequera',
    NOW(), NOW()), ('3429806', NULL, 'Puerto Amarillo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.03333, -59.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto amarillo puerto amarillo argentina ar',
    NOW(), NOW()), ('3429807', NULL, 'Puerto Alicia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.75583, -57.82314, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto alicia puerto alicia argentina ar',
    NOW(), NOW()), ('3429808', NULL, 'Puerto La Esmeralda', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.64271, -59.58199, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto la esmeralda puerto la esmeralda argentina ar puerto algarrobo,puerto la esmeralda',
    NOW(), NOW()), ('3429809', NULL, 'Puerto Abra', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.31644, -57.89059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto abra puerto abra argentina ar abra,puerto abra,puerto guazu,puerto guazú',
    NOW(), NOW()), ('3429810', NULL, 'Isla del Puerto', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.49542, -58.22097, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'isla del puerto isla del puerto argentina ar isla del puerto',
    NOW(), NOW()), ('3429811', NULL, 'Arroyo Puerto', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.61202, -59.00423, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo puerto arroyo puerto argentina ar',
    NOW(), NOW()), ('3429821', NULL, 'Puerto Algarrobo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.11058, -59.8482, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto algarrobo puerto algarrobo argentina ar leguizamon,leguizamón,pueblo leguizamon,pueblo leguizamón,puerto algarrobo',
    NOW(), NOW()), ('3429866', NULL, 'Presidencia de la Plaza', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.00213, -59.84476, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'presidencia de la plaza presidencia de la plaza argentina ar presidencia de la plaza,presidente de la plaza,puerto de la plaza',
    NOW(), NOW()), ('3429888', NULL, 'Monte de los Portugueses', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.48333, -57.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'monte de los portugueses monte de los portugueses argentina ar',
    NOW(), NOW()), ('3429889', NULL, 'Paso del Portugués', 'Paso del Portugues',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.02995, -58.6651, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso del portugués paso del portugues argentina ar paso del portugues,paso del portugués',
    NOW(), NOW()), ('3429890', NULL, 'Puesto Portón Negro', 'Puesto Porton Negro',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.4122, -57.822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto portón negro puesto porton negro argentina ar',
    NOW(), NOW()), ('3429891', NULL, 'Arroyo Portillo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.27718, -58.04197, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo portillo arroyo portillo argentina ar',
    NOW(), NOW()), ('3429892', NULL, 'Arroyo Portera', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.85049, -55.19097, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo portera arroyo portera argentina ar arroyo fraga,arroyo fragá,arroyo portera',
    NOW(), NOW()), ('3429893', NULL, 'Riacho Porteño', 'Riacho Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.27749, -57.72274, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'riacho porteño riacho porteno argentina ar riacho porteno,riacho porteño,rio porteno,río porteño',
    NOW(), NOW()), ('3429894', NULL, 'Paso Porteño', 'Paso Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.02361, -55.55864, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso porteño paso porteno argentina ar',
    NOW(), NOW()), ('3429895', NULL, 'Riacho Porteñito', 'Riacho Portenito',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.26177, -57.73968, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'riacho porteñito riacho portenito argentina ar',
    NOW(), NOW()), ('3429896', NULL, 'Estancia Portau', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.44487, -57.54559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia portau estancia portau argentina ar',
    NOW(), NOW()), ('3429993', NULL, 'Pieres', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.39412, -58.67238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pieres pieres argentina ar pieres',
    NOW(), NOW()), ('3430178', NULL, 'Panambí', 'Panambi',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.72199, -54.91486, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'panambí panambi argentina ar panambi,panambí,puerto panambi',
    NOW(), NOW()), ('3430444', NULL, 'Necochea Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.4854, -58.81387, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'necochea airport necochea airport argentina ar aeroport de necochea,aeropuerto de necochea,aéroport de necochea,nec,necochea airport,sazo',
    NOW(), NOW());