INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8236786', NULL, 'Horse Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.45512, 137.16974, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horse paddock horse paddock australia au horse paddock',
    NOW(), NOW()), ('8237125', NULL, 'East Napier Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.09403, 143.82208, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east napier mine east napier mine australia au east napier mine',
    NOW(), NOW()), ('8237147', NULL, 'Gosport Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.56097, 147.26042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gosport mine gosport mine australia au gosport mine',
    NOW(), NOW()), ('8237208', NULL, 'Napier Freehold Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.09153, 143.80624, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier freehold mine napier freehold mine australia au napier freehold mine',
    NOW(), NOW()), ('8237659', NULL, 'Harbor Lights Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.87063, 121.3197, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbor lights mine harbor lights mine australia au harbor lights mine',
    NOW(), NOW()), ('8237660', NULL, 'Harbour View Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.67778, 120.1889, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour view mine harbour view mine australia au harbour view mine',
    NOW(), NOW()), ('8237753', NULL, 'Kumarina Copper Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.69062, 119.5378, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kumarina copper mine kumarina copper mine australia au kumarina copper mine,kumarina mine',
    NOW(), NOW()), ('8237964', NULL, 'Portree Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.24032, 119.7277, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portree mine portree mine australia au portree mine',
    NOW(), NOW()), ('8260198', NULL, 'Mungindi Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.9676, 149.05186, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mungindi airport mungindi airport australia au ymgi',
    NOW(), NOW()), ('8260374', NULL, 'Mystery Flight Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.27999, 142.90007, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mystery flight airport mystery flight airport australia au zzf',
    NOW(), NOW()), ('8260687', NULL, 'Koonibba Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.89734, 133.42247, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koonibba airport koonibba airport australia au kqb',
    NOW(), NOW()), ('8260692', NULL, 'Port Stephens Airfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.75052, 152.07711, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port stephens airfield port stephens airfield australia au pte',
    NOW(), NOW()), ('8260756', NULL, 'Prominent Hill Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.72108, 135.52348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'prominent hill airport prominent hill airport australia au pxh,prominent hill airport,ypmh',
    NOW(), NOW()), ('8260817', NULL, 'Gascoyne Junction Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.0538, 115.20144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gascoyne junction airport gascoyne junction airport australia au gsc,gascoyne junction airport,ygsc',
    NOW(), NOW()), ('8260869', NULL, 'Osborne Mine Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.08254, 140.55779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'osborne mine airport osborne mine airport australia au aeroportul osborne mine,lapangan terbang osborne mine,oso,osborne mine airport,osborne mine ji chang,osborne mine機場,yosb,ozubonmain kong gang,オズボーンマイン空港',
    NOW(), NOW()), ('8260968', NULL, 'Woodgreen Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.65212, 134.23499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woodgreen airport woodgreen airport australia au wog,woodgreen airport',
    NOW(), NOW()), ('8260970', NULL, 'Lady Elliot Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.11332, 152.71545, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lady elliot island airport lady elliot island airport australia au lyt',
    NOW(), NOW()), ('8260971', NULL, 'Tableland Homestead Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.296, 126.913, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tableland homestead airport tableland homestead airport australia au tbl,tableland homestead airport,tablelands airport,ytab',
    NOW(), NOW()), ('8260976', NULL, 'Yandicoogina Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.77, 119.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yandicoogina airport yandicoogina airport australia au ynn,yycn,yandicoogina airport',
    NOW(), NOW()), ('8261038', NULL, 'Ouyen Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.20002, 142.49955, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ouyen airport ouyen airport australia au oyn,ouyen airport',
    NOW(), NOW()), ('8261068', NULL, 'Christmas Creek Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.87218, 125.93662, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'christmas creek airport christmas creek airport australia au cxq,ycrk',
    NOW(), NOW()), ('8261072', NULL, 'Onslow Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.66844, 115.11269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'onslow airport onslow airport australia au aeroportul onslow,flughafen onslow,lapangan terbang onslow,ons,onslow airport,onslow havaalani,onslow havaalanı,yolw,onzuro kong gang,オンズロー空港',
    NOW(), NOW()), ('8288517', NULL, 'Abingdon Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.60856, 143.18389, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'abingdon airport abingdon airport australia au abg,abingdon airport,abingdon downs,abingdon lufthavn,aeroportul abingdon,lapangan terbang abingdon,yabi,a bin deng ji chang,aerodrome d''abingdon,aérodrome d''abingdon,frwdgah abyngdwn,фурудгоҳи обингдун,فرودگاه آبینگدون,阿賓登機場',
    NOW(), NOW()), ('8298711', NULL, 'Brighton Downs Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.36542, 141.56283, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brighton downs airport brighton downs airport australia au bht,brighton downs airport',
    NOW(), NOW()), ('8298715', NULL, 'Henbury Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.584, 133.235, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'henbury airport henbury airport australia au hry,henbury airport,yhby',
    NOW(), NOW()), ('8298781', NULL, 'Musgrave Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.77302, 143.50492, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'musgrave airport musgrave airport australia au mvu,musgrave airport,ymgv',
    NOW(), NOW()), ('8298783', NULL, 'Orientos Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.06005, 141.53614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'orientos airport orientos airport australia au oxo,orientos airport',
    NOW(), NOW()), ('8298789', NULL, 'Coolawanyah Station Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.79415, 117.7593, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coolawanyah station airport coolawanyah station airport australia au aeroport de coolawanyah,aeroportul coolawanyah station,aéroport de coolawanyah,coy,coolawanyah station airport,coolawanyah station ji chang,coolawanyah station機場,ycwy',
    NOW(), NOW()), ('8298794', NULL, 'Moolawatana Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.90673, 139.76631, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moolawatana airport moolawatana airport australia au mwt,moolawatana airport,mulavatana,ymwt,мулаватана',
    NOW(), NOW()), ('8298809', NULL, 'Doogan Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.3833, 126.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'doogan airport doogan airport australia au dng,ydgn',
    NOW(), NOW()), ('8298810', NULL, 'Roy Hill Station Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.62534, 119.95869, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'roy hill station airport roy hill station airport australia au rhl,roy hill station airport,yryh',
    NOW(), NOW()), ('8298873', NULL, 'Forrest River Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.16704, 127.84236, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'forrest river airport forrest river airport australia au aeroport de forrest river,aeropuerto de forrest river,aéroport de forrest river,fvr,flughafen forrest river,forrest river airport,yfrv',
    NOW(), NOW()), ('8298882', NULL, 'Collie Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.359, 116.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'collie airport collie airport australia au cie,ycoi',
    NOW(), NOW()), ('8298892', NULL, 'Wondoola Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.57352, 140.89348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wondoola airport wondoola airport australia au won,wondoola airport,ywdl',
    NOW(), NOW()), ('8298898', NULL, 'Silver Plains Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.976, 143.552, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'silver plains airport silver plains airport australia au aeroport de silver plains,aeropuerto de silver plains,aéroport de silver plains,flughafen silver plains,ssp,silver plains airport,ysvp',
    NOW(), NOW()), ('8298910', NULL, 'Tanbar Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.847, 141.928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanbar airport tanbar airport australia au txr,tanbar airport,ytnb',
    NOW(), NOW()), ('8298945', NULL, 'Cordillo Downs Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.74519, 140.63787, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cordillo downs airport cordillo downs airport australia au cordillo downs airport,odl,ycod',
    NOW(), NOW()), ('8298954', NULL, 'Mainoru Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.05424, 134.09504, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'mainoru airport mainoru airport australia au miz,mainoru airport',
    NOW(), NOW()), ('8298958', NULL, 'Lakeland Downs Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.84444, 144.85027, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lakeland downs airport lakeland downs airport australia au lkd,lakeland downs airport,ylnd',
    NOW(), NOW()), ('8298980', NULL, 'Gamboola Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.54375, 143.66989, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gamboola airport gamboola airport australia au gbp,gamboola airport,ygam',
    NOW(), NOW()), ('8298988', NULL, 'Waverney Airport (historical)', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.3667, 141.933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'waverney airport (historical) waverney airport (historical) australia au wan,waverney airport',
    NOW(), NOW()), ('8299011', NULL, 'Beagle Bay Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.01619, 122.64715, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beagle bay airport beagle bay airport australia au aeroport de beagle bay,aéroport de beagle bay,bee,beagle bay airport,ybgb',
    NOW(), NOW()), ('8299057', NULL, 'Carpentaria Downs Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.71696, 144.31244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carpentaria downs airport carpentaria downs airport australia au cfp,carpentaria downs airport,ycpn',
    NOW(), NOW()), ('8299104', NULL, 'Stephens Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -9.50731, 143.54706, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stephens island airport stephens island airport australia au stf,stephens island airport,ysti',
    NOW(), NOW()), ('8299131', NULL, 'Roper Bar Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.7344, 134.525, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'roper bar airport roper bar airport australia au rpb,roper bar airport,yrrb',
    NOW(), NOW()), ('8299176', NULL, 'Orpheus Island Waterport Seaplane Base', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.63392, 146.49801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'orpheus island waterport seaplane base orpheus island waterport seaplane base australia au ors,orpheus island waterport seaplane base,waterport spb',
    NOW(), NOW()), ('8299359', NULL, 'HVDC Basslink - Low Head Cable Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.04249, 146.86877, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hvdc basslink - low head cable terminal hvdc basslink - low head cable terminal australia au',
    NOW(), NOW()), ('8310232', NULL, 'Shute Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.29207, 148.78415, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shute harbour shute harbour australia au shute harbour',
    NOW(), NOW()), ('8310682', NULL, 'Boat Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.78955, 152.10906, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour boat harbour australia au boat harbour',
    NOW(), NOW()), ('8348272', NULL, 'Dampier Peninsula', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.93241, 122.86559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier peninsula dampier peninsula australia au',
    NOW(), NOW());