INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8175085', NULL, 'Otruby', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.5969, 29.9847, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'otruby otruby by by otruby,pristan'' otruby,pristan’ otruby,пристань отрубы',
    NOW(), NOW()), ('8178366', NULL, 'Sherstin', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.65617, 31.08743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sherstin sherstin by by pristan'' sherstin,pristan’ sherstin,sherstin,пристань шерстин,шерстин',
    NOW(), NOW()), ('8178367', NULL, 'Pristan’ Pavozhbor’ye', 'Pristan'' Pavozhbor''ye',
    NULL, 'BY', 'BY', NULL, NULL,
    52.64046, 31.14088, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ pavozhbor’ye pristan'' pavozhbor''ye by by ostanovochnyj punkt pavozhbor''e,ostanovochnyy punkt pavozhbor''ye,ostanovochnyy punkt pavozhbor’ye,pavozhbor''e,pavozhbor''ye,pavozhbor’ye,pristan'' pavozhbor''e,pristan'' pavozhbor''ye,pristan’ pavozhbor’ye,остановочный пункт павожборье,павожборье,пристань павожборье',
    NOW(), NOW()), ('8178394', NULL, 'Pristan’ Novosëlki', 'Pristan'' Novoselki',
    NULL, 'BY', 'BY', NULL, NULL,
    52.61262, 31.10458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ novosëlki pristan'' novoselki by by novoselki,novosjolki,novosëlki,pristan'' novoselki,pristan'' novosjolki,pristan’ novosëlki,новосёлки,пристань новосёлки',
    NOW(), NOW()), ('8178414', NULL, 'Krysin', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.52819, 31.16797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'krysin krysin by by krysin,ostanovochnyj punkt krysin,ostanovochnyy punkt krysin,pristan'' krysin,pristan’ krysin,крысин,остановочный пункт крысин,пристань крысин',
    NOW(), NOW()), ('8178430', NULL, 'Volodino', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.4298, 31.047, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'volodino volodino by by ostanovochnyj punkt volodino,ostanovochnyy punkt volodino,pristan'' volodino,pristan’ volodino,volodino,володино,остановочный пункт володино,пристань володино',
    NOW(), NOW()), ('8178432', NULL, 'Pristan’ Klënki', 'Pristan'' Klenki',
    NULL, 'BY', 'BY', NULL, NULL,
    52.4547, 31.0832, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ klënki pristan'' klenki by by klenki,kljonki,klënki,pristan'' klenki,pristan'' kljonki,pristan’ klënki,клёнки,пристань клёнки',
    NOW(), NOW()), ('8178434', NULL, 'Pristan’ Plësy', 'Pristan'' Plesy',
    NULL, 'BY', 'BY', NULL, NULL,
    52.44933, 31.06277, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ plësy pristan'' plesy by by plesy,pljosy,plësy,pristan'' plesy,pristan'' pljosy,pristan’ plësy,плёсы,пристань плёсы',
    NOW(), NOW()), ('8178439', NULL, 'Rachny Port Homyel’', 'Rachny Port Homyel''',
    NULL, 'BY', 'BY', NULL, NULL,
    52.4356, 31.029, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rachny port homyel’ rachny port homyel'' by by gomel'',homyel'',homyel’,rachny port gomel'',rachny port homyel'',rachny port homyel’,гомель,рачны порт гомель',
    NOW(), NOW()), ('8178450', NULL, 'Peramoga', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.3973, 31.071, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'peramoga peramoga by by peramoga,peremoga,pieramoha,pobeda,перамога,перемога,победа',
    NOW(), NOW()), ('8181333', NULL, 'Akulinka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.9665, 29.398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'akulinka akulinka by by akulinka,pristan'' akulinka,pristan’ akulinka,пристань акулинка',
    NOW(), NOW()), ('8181378', NULL, 'Pristan’ Strel’sk', 'Pristan'' Strel''sk',
    NULL, 'BY', 'BY', NULL, NULL,
    51.9561, 29.4312, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ strel’sk pristan'' strel''sk by by pristan'' strel''sk,pristan’ strel’sk,strel''sk,strel’sk,пристань стрельск',
    NOW(), NOW()), ('8181384', NULL, 'Serp i Molot', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.9345, 29.4872, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serp i molot serp i molot by by pristan'' serp i molot,pristan’ serp i molot,serp i molot,пристань серп и молот',
    NOW(), NOW()), ('8181385', NULL, 'Yurovichi', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.92629, 29.50837, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yurovichi yurovichi by by jurovichi,pristan'' jurovichi,pristan'' yurovichi,pristan’ yurovichi,yurovichi,пристань юровичи,юровичи',
    NOW(), NOW()), ('8181405', NULL, 'Pristan’ Dërnovichi', 'Pristan'' Dernovichi',
    NULL, 'BY', 'BY', NULL, NULL,
    51.60898, 29.7785, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ dërnovichi pristan'' dernovichi by by dernovichi,djornovichi,dërnovichi,pristan'' dernovichi,pristan'' djornovichi,pristan’ dërnovichi,дёрновичи,пристань дёрновичи',
    NOW(), NOW()), ('8181415', NULL, 'Barbarov', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.895, 29.4765, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barbarov barbarov by by barbarov,pristan'' barbarov,pristan’ barbarov,пристань барбаров',
    NOW(), NOW()), ('8181419', NULL, 'Pristan’ Tul’govichi', 'Pristan'' Tul''govichi',
    NULL, 'BY', 'BY', NULL, NULL,
    51.76289, 29.6742, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ tul’govichi pristan'' tul''govichi by by pristan'' tul''govichi,pristan’ tul’govichi,tul''govichi,tul’govichi,пристань тульговичи,тульговичи',
    NOW(), NOW()), ('8181430', NULL, 'Konotop', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.7642, 29.57617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'konotop konotop by by konotop,pristan'' konotop,pristan’ konotop,конотоп,пристань конотоп',
    NOW(), NOW()), ('8181504', NULL, 'Pristanskoye', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.51771, 30.3758, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristanskoye pristanskoye by by pristanskoe,pristanskoye,пристанское',
    NOW(), NOW()), ('8181526', NULL, 'Novaya Iolcha', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.51248, 30.56604, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novaya iolcha novaya iolcha by by novaja iolcha,novaya iolcha,pristan'' novaja iolcha,pristan'' novaya iolcha,pristan’ novaya iolcha,новая иолча,пристань новая иолча',
    NOW(), NOW()), ('8181551', NULL, 'Derazhichi', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.78577, 30.63819, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'derazhichi derazhichi by by derazhichi,pristan'' derazhichi,pristan’ derazhichi,деражичи,пристань деражичи',
    NOW(), NOW()), ('8181552', NULL, 'Abakumy', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    51.97307, 30.86281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'abakumy abakumy by by abakumy,pristan'' abakumy,pristan’ abakumy,абакумы,пристань абакумы',
    NOW(), NOW()), ('8194491', NULL, 'Pristan’ Sverzhen’', 'Pristan'' Sverzhen''',
    NULL, 'BY', 'BY', NULL, NULL,
    53.1227, 30.304, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ sverzhen’ pristan'' sverzhen'' by by pristan'' sverzhen'',pristan’ sverzhen’,sverzhen'',sverzhen’,пристань свержень',
    NOW(), NOW()), ('8194567', NULL, 'Krasnyy Bereg', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.9382, 30.9463, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'krasnyy bereg krasnyy bereg by by krasnyy bereg,pristan'' krasnyj bereg,pristan'' krasnyy bereg,pristan’ krasnyy bereg,пристань красный берег',
    NOW(), NOW()), ('8194617', NULL, 'Zhlobin', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.8939, 30.0651, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'zhlobin zhlobin by by pristan'' zhlobin,pristan’ zhlobin,zhlobin,пристань жлобин',
    NOW(), NOW()), ('8194618', NULL, 'Gorodovka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.8433, 30.9998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gorodovka gorodovka by by gorodovka,pristan'' gorodovka,pristan’ gorodovka,пристань городовка',
    NOW(), NOW()), ('8194644', NULL, 'Shepotovichi', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.7679, 30.9435, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shepotovichi shepotovichi by by pristan'' shepotovichi,pristan’ shepotovichi,shepotovichi,пристань шепотовичи',
    NOW(), NOW()), ('8194719', NULL, 'Pristan’ Odnopol’ye', 'Pristan'' Odnopol''ye',
    NULL, 'BY', 'BY', NULL, NULL,
    52.7039, 30.9958, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ odnopol’ye pristan'' odnopol''ye by by odnopol''ye,odnopol’ye,pristan'' odnopol''e,pristan'' odnopol''ye,pristan’ odnopol’ye,пристань однополье',
    NOW(), NOW()), ('8194856', NULL, 'Smedin', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.7046, 31.0256, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'smedin smedin by by pristan'' smedin,pristan’ smedin,smedin,пристань смедин',
    NOW(), NOW()), ('8195667', NULL, 'Gagali', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.5483, 30.0986, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gagali gagali by by gagali,pristan'' gagali,pristan’ gagali,пристань гагали',
    NOW(), NOW()), ('8195668', NULL, 'Pristan’ Gorval’', 'Pristan'' Gorval''',
    NULL, 'BY', 'BY', NULL, NULL,
    52.5672, 30.2023, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ gorval’ pristan'' gorval'' by by gorval'',gorval’,pristan'' gorval'',pristan’ gorval’,пристань горваль',
    NOW(), NOW()), ('8195669', NULL, 'Pristan’ Ust’ye Reki Berezina', 'Pristan'' Ust''ye Reki Berezina',
    NULL, 'BY', 'BY', NULL, NULL,
    52.551, 30.2505, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ ust’ye reki berezina pristan'' ust''ye reki berezina by by pristan'' ust''e reki berezina,pristan'' ust''ye reki berezina,pristan’ ust’ye reki berezina,ust''ye reki berezina,ust’ye reki berezina,пристань устье реки березина',
    NOW(), NOW()), ('8195743', NULL, 'Glushets', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.4875, 30.3151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'glushets glushets by by glushets,pristan'' glushec,pristan'' glushets,pristan’ glushets,пристань глушец',
    NOW(), NOW()), ('8195773', NULL, 'Pristan’ Ozërshchina', 'Pristan'' Ozershchina',
    NULL, 'BY', 'BY', NULL, NULL,
    52.3974, 30.3582, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ ozërshchina pristan'' ozershchina by by ozershchina,ozërshchina,pristan'' ozershchina,pristan'' ozjorshhina,pristan’ ozërshchina,пристань озёрщина',
    NOW(), NOW()), ('8195778', NULL, 'Pristan’ Peskopol’ye', 'Pristan'' Peskopol''ye',
    NULL, 'BY', 'BY', NULL, NULL,
    52.4424, 30.3825, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pristan’ peskopol’ye pristan'' peskopol''ye by by peskopol''ye,peskopol’ye,pristan'' peskopol''e,pristan'' peskopol''ye,pristan’ peskopol’ye,пристань пескополье',
    NOW(), NOW()), ('8195798', NULL, 'Rechytsa', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.3693, 30.4007, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rechytsa rechytsa by by pristan'' rechitsa,pristan’ rechitsa,prystan'' rechytsa,prystan'' rehchyca,prystan’ rechytsa,rechytsa,rehchyca,прыстань рэчыца,рэчыца',
    NOW(), NOW()), ('8195833', NULL, 'Staraya Chenka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.3162, 30.9519, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'staraya chenka staraya chenka by by pristan'' staraja chenka,pristan'' staraya chenka,pristan’ staraya chenka,staraya chenka,пристань старая ченка',
    NOW(), NOW()), ('8195852', NULL, 'Krasnyy Most', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.2442, 30.5319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'krasnyy most krasnyy most by by krasnyy most,pristan'' krasnyj most,pristan'' krasnyy most,pristan’ krasnyy most,пристань красный мост',
    NOW(), NOW()), ('8195867', NULL, 'Velin', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.2023, 30.5754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'velin velin by by pristan'' velin,pristan’ velin,velin,пристань велин',
    NOW(), NOW()), ('8195915', NULL, 'Peredelka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.0293, 30.7372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'peredelka peredelka by by peredelka,pristan'' peredelka,pristan’ peredelka,переделка,пристань переделка',
    NOW(), NOW()), ('8198267', NULL, 'Braslavskaya Luka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.4216, 26.85544, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braslavskaya luka braslavskaya luka by by braslavskaja luka,braslavskaya luka,браславская лука',
    NOW(), NOW()), ('8201993', NULL, 'Chechersk', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.9042, 30.9437, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chechersk chechersk by by chechersk,pristan'' chechersk,pristan’ chechersk,пристань чечерск',
    NOW(), NOW()), ('8202056', NULL, 'Sharpilovka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    52.1016, 30.9244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sharpilovka sharpilovka by by pristan'' sharpilovka,pristan’ sharpilovka,sharpilovka,пристань шарпиловка,шарпиловка',
    NOW(), NOW()), ('8207759', NULL, 'Deriporty', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.73331, 27.57841, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'deriporty deriporty by by deriporty,дерипорты',
    NOW(), NOW()), ('8213596', NULL, 'Lukavtsy', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.6705, 28.7813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavtsy lukavtsy by by lukavcy,lukavtsy,лукавцы',
    NOW(), NOW()), ('8216382', NULL, 'Luka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.57522, 29.85046, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka by by luka,лука',
    NOW(), NOW()), ('8222340', NULL, 'Zhavnina', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.0584, 28.4028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'zhavnina zhavnina by by zhavnina,жавнина',
    NOW(), NOW()), ('8222420', NULL, 'Luka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    55.2622, 28.4646, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka by by luka,лука',
    NOW(), NOW()), ('8222705', NULL, 'Urochishche Krasnaya Luka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    54.7155, 28.4911, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'urochishche krasnaya luka urochishche krasnaya luka by by urochishche krasnaya luka,urochishhe krasnaja luka,урочище красная лука',
    NOW(), NOW()), ('8232699', NULL, 'Luka', NULL,
    NULL, 'BY', 'BY', NULL, NULL,
    54.85574, 29.67368, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka by by chervonnaja luka,chervonnaya luka,luka,лука,червонная лука',
    NOW(), NOW());