INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3452832', NULL, 'Pôrto de Manga', 'Porto de Manga',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.28333, -44.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto de manga porto de manga brazil br porto de manga,pôrto de manga',
    NOW(), NOW()), ('3452833', NULL, 'Porto de Índios', 'Porto de Indios',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.58433, -55.64722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de índios porto de indios brazil br porto de indio,porto de indios,porto de índios,pôrto de indio',
    NOW(), NOW()), ('3452834', NULL, 'Pôrto de Fora', 'Porto de Fora',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.11667, -55.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto de fora porto de fora brazil br porto da fora,porto da fóra,porto de fora,porto do fora,pôrto de fora',
    NOW(), NOW()), ('3452835', NULL, 'Porto de Cima', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.43694, -48.87639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de cima porto de cima brazil br',
    NOW(), NOW()), ('3452836', NULL, 'Porto de Cima', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.86667, -55.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de cima porto de cima brazil br jaguarasinho,porto de cima,taquaralzinho',
    NOW(), NOW()), ('3452837', NULL, 'Pôrto de Cariacica', 'Porto de Cariacica',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.28333, -40.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto de cariacica porto de cariacica brazil br porto de cariacica,pôrto de cariacica',
    NOW(), NOW()), ('3452838', NULL, 'Pôrto da Telha', 'Porto da Telha',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.41667, -60, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da telha porto da telha brazil br passaje,porto da telha,pôrto da telha',
    NOW(), NOW()), ('3452839', NULL, 'Pôrto das Pombas', 'Porto das Pombas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.31667, -51.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das pombas porto das pombas brazil br pombas,porto das pombas,pôrto das pombas',
    NOW(), NOW()), ('3452840', NULL, 'Pôrto das Pedras', 'Porto das Pedras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.38333, -52.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das pedras porto das pedras brazil br porto das pedras,pôrto das pedras',
    NOW(), NOW()), ('3452841', NULL, 'Pôrto das Pedras', 'Porto das Pedras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.41667, -56.31667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das pedras porto das pedras brazil br',
    NOW(), NOW()), ('3452842', NULL, 'Pôrto das Melancias', 'Porto das Melancias',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.5, -45.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das melancias porto das melancias brazil br porto das melancias,porto dos melancios,pôrto das melancias,pôrto dos melancios',
    NOW(), NOW()), ('3452843', NULL, 'Porto das Flores', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.0825, -43.56083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto das flores porto das flores brazil br das flores,das flôres',
    NOW(), NOW()), ('3452844', NULL, 'Pôrto das Éguas', 'Porto das Eguas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.81667, -56.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das éguas porto das eguas brazil br porto das eguas,pôrto das éguas',
    NOW(), NOW()), ('3452845', NULL, 'Porto da Cruz', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.69984, -42.23546, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da cruz porto da cruz brazil br porto da cruz,porto das cruzes,pôrto das cruzes',
    NOW(), NOW()), ('3452846', NULL, 'Pôrto das Canoas', 'Porto das Canoas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.18333, -42.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das canoas porto das canoas brazil br porto das canoas,pôrto das canoas',
    NOW(), NOW()), ('3452847', NULL, 'Pôrto das Canoas', 'Porto das Canoas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.45, -57.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das canoas porto das canoas brazil br porto canoas,porto das canoas,pôrto canoas,pôrto das canoas',
    NOW(), NOW()), ('3452848', NULL, 'Porto das Caixas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.70083, -42.875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto das caixas porto das caixas brazil br',
    NOW(), NOW()), ('3452849', NULL, 'Pôrto das Cabras', 'Porto das Cabras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.83333, -36.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto das cabras porto das cabras brazil br',
    NOW(), NOW()), ('3452850', NULL, 'Porto da Pedra', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.81667, -43.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da pedra porto da pedra brazil br ponta da pedra,porto da pedra,porto de pedra,pôrto de pedra',
    NOW(), NOW()), ('3452851', NULL, 'Pôrto da Olaria', 'Porto da Olaria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.85, -48.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da olaria porto da olaria brazil br porto da olaria,pôrto da olaria',
    NOW(), NOW()), ('3452852', NULL, 'Pôrto da Glória', 'Porto da Gloria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.65, -46.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da glória porto da gloria brazil br porto da gloria,pôrto da glória',
    NOW(), NOW()), ('3452853', NULL, 'Pôrto da Galinha', 'Porto da Galinha',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.9, -45.41667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da galinha porto da galinha brazil br porto da galinha,porto do galinha,pôrto da galinha,pôrto do galinha',
    NOW(), NOW()), ('3452854', NULL, 'Pôrto da Fotografia', 'Porto da Fotografia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.2, -59.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da fotografia porto da fotografia brazil br porto da fotografia,porto da photographia,pôrto da fotografia',
    NOW(), NOW()), ('3452855', NULL, 'Pôrto da Espada', 'Porto da Espada',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.1, -38.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da espada porto da espada brazil br',
    NOW(), NOW()), ('3452856', NULL, 'Pôrto da Barra', 'Porto da Barra',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.63333, -52.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto da barra porto da barra brazil br porto da barra,porto da farra,pôrto da barra,pôrto da farra',
    NOW(), NOW()), ('3452857', NULL, 'Pôrto Curupaí', 'Porto Curupai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.83333, -53.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto curupaí porto curupai brazil br curupai,porto curupai,pôrto curupaí,rio curupahy',
    NOW(), NOW()), ('3452858', NULL, 'Pôrto Cristalino', 'Porto Cristalino',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.38333, -53.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cristalino porto cristalino brazil br',
    NOW(), NOW()), ('3452859', NULL, 'Pôrto Corupá', 'Porto Corupa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.75, -54.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto corupá porto corupa brazil br',
    NOW(), NOW()), ('3452860', NULL, 'Pôrto Coqueirinho', 'Porto Coqueirinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.6, -53.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto coqueirinho porto coqueirinho brazil br porto coqueirinha,porto coqueirinho,pôrto coqueirinha,pôrto coqueirinho',
    NOW(), NOW()), ('3452861', NULL, 'Copacabana do Norte', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.52857, -52.3808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'copacabana do norte copacabana do norte brazil br copacabana do norte,porto andira,porto andirá,porto copacabana do norte,pôrto copacabana do norte',
    NOW(), NOW()), ('3452862', NULL, 'Pôrto Conceição', 'Porto Conceicao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.15, -57.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto conceição porto conceicao brazil br porto conceicao,porto da conceicao,porto da conceição,pôrto conceição',
    NOW(), NOW()), ('3452863', NULL, 'Hidrelétrica Pôrto Colômbia', 'Hidreletrica Porto Colombia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.16667, -48.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hidrelétrica pôrto colômbia hidreletrica porto colombia brazil br hidreletrica porto colombia,hidrelétrica pôrto colômbia',
    NOW(), NOW()), ('3452864', NULL, 'Pôrto Ciríaco', 'Porto Ciriaco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.7, -56.26667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ciríaco porto ciriaco brazil br porto ciriaco,porto cyriaco,pôrto ciríaco',
    NOW(), NOW()), ('3452865', NULL, 'Pôrto Cinco de Maio', 'Porto Cinco de Maio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.55, -53.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cinco de maio porto cinco de maio brazil br',
    NOW(), NOW()), ('3452866', NULL, 'Pôrto Chalana', 'Porto Chalana',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.18333, -52.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto chalana porto chalana brazil br chalana,porto chalana,porto da chatana,pôrto chalana',
    NOW(), NOW()), ('3452867', NULL, 'Ilha Pôrto Cemitério', 'Ilha Porto Cemiterio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.13333, -48.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilha pôrto cemitério ilha porto cemiterio brazil br ilha porto cemiterio,ilha pôrto cemitério',
    NOW(), NOW()), ('3452868', NULL, 'Pôrto Cedro', 'Porto Cedro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.28333, -55.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cedro porto cedro brazil br cedro,porto cedro,pôrto cedro',
    NOW(), NOW()), ('3452869', NULL, 'Pôrto Cecílio-cuê', 'Porto Cecilio-cue',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.13333, -53.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cecílio-cuê porto cecilio-cue brazil br porto cecilio,porto cecilio-cue,pôrto cecílio,pôrto cecílio-cuê',
    NOW(), NOW()), ('3452870', NULL, 'Pôrto Cavalheiro', 'Porto Cavalheiro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.21667, -48.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cavalheiro porto cavalheiro brazil br porto cavalheiro,pôrto cavalheiro',
    NOW(), NOW()), ('3452871', NULL, 'Pôrto Castro Alves', 'Porto Castro Alves',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.51667, -39.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto castro alves porto castro alves brazil br porto castro alves,porto do papagente,pôrto castro alves',
    NOW(), NOW()), ('3452872', NULL, 'Pôrto Castilho', 'Porto Castilho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.25, -52.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto castilho porto castilho brazil br',
    NOW(), NOW()), ('3452873', NULL, 'Pôrto Cassange', 'Porto Cassange',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.56667, -56.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cassange porto cassange brazil br porto cassange,porto do cassange,pôrto cassange,pôrto do cassange',
    NOW(), NOW()), ('3452874', NULL, 'Pôrto Casa Nova', 'Porto Casa Nova',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.78333, -51.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto casa nova porto casa nova brazil br porto casa nova,porto tibagi,pôrto casa nova,pôrto tibagi',
    NOW(), NOW()), ('3452875', NULL, 'Pôrto Carrito', 'Porto Carrito',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.95, -46.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto carrito porto carrito brazil br porto carrito,pôrto carrito',
    NOW(), NOW()), ('3452876', NULL, 'Pôrto Carreiro', 'Porto Carreiro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.96667, -56.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto carreiro porto carreiro brazil br porto carreiro,porto carrero,pôrto carreiro',
    NOW(), NOW()), ('3452877', NULL, 'Pôrto Caracará', 'Porto Caracara',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.86667, -57.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto caracará porto caracara brazil br',
    NOW(), NOW()), ('3452878', NULL, 'Pôrto Capim', 'Porto Capim',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.65, -51.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto capim porto capim brazil br',
    NOW(), NOW()), ('3452879', NULL, 'Pôrto Caneca', 'Porto Caneca',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.66667, -56.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto caneca porto caneca brazil br',
    NOW(), NOW()), ('3452880', NULL, 'Pôrto Cambira', 'Porto Cambira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.33333, -54.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto cambira porto cambira brazil br',
    NOW(), NOW()), ('3452881', NULL, 'Porto Camargo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.36806, -53.74306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto camargo porto camargo brazil br camargo',
    NOW(), NOW());