INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8986237', NULL, 'Sankt Johann Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.51947, 12.4489, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sankt johann airport sankt johann airport austria at flugplatz sankt johann,loij',
    NOW(), NOW()), ('8989457', NULL, 'Schärding-Suben Airport', 'Schaerding-Suben Airport',
    NULL, 'AT', 'Austria', NULL, NULL,
    48.40282, 13.44842, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'schärding-suben airport schaerding-suben airport austria at flugplatz schaerding-suben,flugplatz schärding-suben,lols',
    NOW(), NOW()), ('8989459', NULL, 'Dobersberg Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.92222, 15.29602, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dobersberg airport dobersberg airport austria at flugplatz dobersberg,loab',
    NOW(), NOW()), ('8989460', NULL, 'Gmunden Laakirchen Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.95159, 13.8664, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gmunden laakirchen airport gmunden laakirchen airport austria at flugplatz gmunden laarkirchen,gmunden laarkirchen airport,lolu',
    NOW(), NOW()), ('9034540', NULL, 'Weiz-Unterfladnitz Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.1705, 15.6644, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'weiz-unterfladnitz airport weiz-unterfladnitz airport austria at flugplatz weiz-unterfladnitz,logw',
    NOW(), NOW()), ('9034542', NULL, 'Mauterndorf Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.13201, 13.69583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mauterndorf airport mauterndorf airport austria at flugplatz mauterndorf,losm',
    NOW(), NOW()), ('9034544', NULL, 'Scharnstein Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.89747, 13.93762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'scharnstein airport scharnstein airport austria at lolc',
    NOW(), NOW()), ('9034556', NULL, 'Ried-Kirchheim Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.21253, 13.34485, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ried-kirchheim airport ried-kirchheim airport austria at flugplatz ried-kirchheim,lolk',
    NOW(), NOW()), ('9034564', NULL, 'Wolfsberg Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.81916, 14.82534, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wolfsberg airport wolfsberg airport austria at flugplatz wolfsberg,lokw',
    NOW(), NOW()), ('9034567', NULL, 'Völtendorf Airport', 'Voeltendorf Airport',
    NULL, 'AT', 'Austria', NULL, NULL,
    48.16001, 15.58638, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'völtendorf airport voeltendorf airport austria at flugplatz voeltendorf,flugplatz völtendorf,load',
    NOW(), NOW()), ('9034574', NULL, 'Glainach-Ferlach Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.53356, 14.33162, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'glainach-ferlach airport glainach-ferlach airport austria at lokg',
    NOW(), NOW()), ('9034659', NULL, 'Spitzerberg Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.09895, 16.93359, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'spitzerberg airport spitzerberg airport austria at flugplatz spitzerberg,loas',
    NOW(), NOW()), ('9034661', NULL, 'Leoben-Timmersdorf Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.37975, 14.96329, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leoben-timmersdorf airport leoben-timmersdorf airport austria at flugplatz leoben-timmersdorf,logt',
    NOW(), NOW()), ('9034677', NULL, 'Stockerau Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.4086, 16.19033, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stockerau airport stockerau airport austria at flugplatz stockerau,loau',
    NOW(), NOW()), ('9034679', NULL, 'Fürstenfeld Airport', 'Fuerstenfeld Airport',
    NULL, 'AT', 'Austria', NULL, NULL,
    47.06211, 16.08349, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fürstenfeld airport fuerstenfeld airport austria at flugplatz fuerstenfeld,flugplatz fürstenfeld,logf',
    NOW(), NOW()), ('9034680', NULL, 'Sankt Georgen Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.10291, 14.95042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sankt georgen airport sankt georgen airport austria at flugplatz sankt georgen,lolg',
    NOW(), NOW()), ('9034681', NULL, 'Friesach-Hirth Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.92809, 14.43166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'friesach-hirth airport friesach-hirth airport austria at flugplatz friesach-hirth,lokh',
    NOW(), NOW()), ('9035105', NULL, 'Kufstein-Langkampfen Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.56425, 12.12633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kufstein-langkampfen airport kufstein-langkampfen airport austria at flugplatz kufstein-langkampfen,loik',
    NOW(), NOW()), ('9035295', NULL, 'Eferding Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.33815, 13.98566, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eferding airport eferding airport austria at flugplatz eferding,lole',
    NOW(), NOW()), ('9035664', NULL, 'Reutte-Höfen Airport', 'Reutte-Hoefen Airport',
    NULL, 'AT', 'Austria', NULL, NULL,
    47.47055, 10.68995, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'reutte-höfen airport reutte-hoefen airport austria at flugplatz reutte-hoefen,flugplatz reutte-höfen,loir',
    NOW(), NOW()), ('9035695', NULL, 'Kapfenberg Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.45743, 15.33117, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kapfenberg airport kapfenberg airport austria at flugplatz kapfenberg,logk',
    NOW(), NOW()), ('9035697', NULL, 'Lanzen-Turnau Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.55584, 15.3191, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lanzen-turnau airport lanzen-turnau airport austria at flugplatz lanzen-turnau,logl',
    NOW(), NOW()), ('9035702', NULL, 'Linz-East Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.29925, 14.33408, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'linz-east airport linz-east airport austria at flugplatz linz-ost,lolo',
    NOW(), NOW()), ('9035707', NULL, 'Pinkafeld Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.3865, 16.11291, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pinkafeld airport pinkafeld airport austria at flugplatz pinkafeld,logp',
    NOW(), NOW()), ('9035755', NULL, 'Hofkirchen Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.13894, 14.33553, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hofkirchen airport hofkirchen airport austria at flugplatz hofkirchen,lolh',
    NOW(), NOW()), ('9035758', NULL, 'Mayerhofen Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.96855, 14.36842, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mayerhofen airport mayerhofen airport austria at lokm',
    NOW(), NOW()), ('9255827', NULL, 'Austria Trend Sporthotel Fontana', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.46886, 12.55013, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'austria trend sporthotel fontana austria trend sporthotel fontana austria at',
    NOW(), NOW()), ('9255838', NULL, 'Airport Boutiquehotel Hein', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.14711, 16.514, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport boutiquehotel hein airport boutiquehotel hein austria at',
    NOW(), NOW()), ('9255866', NULL, 'Arion Airport Hotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.1499, 16.4769, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arion airport hotel arion airport hotel austria at',
    NOW(), NOW()), ('9256050', NULL, 'Alpin Resort Sport And Spa Reiterhof', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.39012, 12.6373, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alpin resort sport and spa reiterhof alpin resort sport and spa reiterhof austria at',
    NOW(), NOW()), ('9256079', NULL, 'Singer Sporthotel & Spa', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.40968, 10.75145, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'singer sporthotel & spa singer sporthotel & spa austria at',
    NOW(), NOW()), ('9256139', NULL, 'Sporthotel Austria', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.51763, 12.42314, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sporthotel austria sporthotel austria austria at',
    NOW(), NOW()), ('9256141', NULL, 'Lukasmayr Hotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.28748, 12.8244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukasmayr hotel lukasmayr hotel austria at',
    NOW(), NOW()), ('9256931', NULL, 'Kur & Sport Hotel Palace', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.16725, 13.10823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kur & sport hotel palace kur & sport hotel palace austria at',
    NOW(), NOW()), ('9256963', NULL, 'Vienna Sporthotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.19141, 16.40803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vienna sporthotel vienna sporthotel austria at',
    NOW(), NOW()), ('9257072', NULL, 'Star Inn Hotel Salzburg Airport Messe', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.79262, 12.98476, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'star inn hotel salzburg airport messe star inn hotel salzburg airport messe austria at',
    NOW(), NOW()), ('9257093', NULL, 'Sporthotel Kogler', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.27837, 12.48331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sporthotel kogler sporthotel kogler austria at',
    NOW(), NOW()), ('9257126', NULL, 'Sport & Spass Neuhaus', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.39256, 12.63611, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sport & spass neuhaus sport & spass neuhaus austria at',
    NOW(), NOW()), ('9257165', NULL, 'Sporthotel Molltal', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.93476, 13.13099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sporthotel molltal sporthotel molltal austria at',
    NOW(), NOW()), ('9257302', NULL, 'Berger''S Sporthotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.39087, 12.63609, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'berger''s sporthotel berger''s sporthotel austria at',
    NOW(), NOW()), ('9257303', NULL, 'Silvretta Montafon Sporthotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.9869, 10.02713, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'silvretta montafon sporthotel silvretta montafon sporthotel austria at',
    NOW(), NOW()), ('9257316', NULL, 'Sport & Vital Hotel Seppl', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    46.99565, 10.86713, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sport & vital hotel seppl sport & vital hotel seppl austria at',
    NOW(), NOW()), ('9613171', NULL, 'Sport Natter', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.3513, 9.88279, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sport natter sport natter austria at',
    NOW(), NOW()), ('9645271', NULL, 'Portlaalpe', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.27969, 9.83931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portlaalpe portlaalpe austria at',
    NOW(), NOW()), ('9794277', NULL, 'Bregenz Hafen', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.50619, 9.74795, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bregenz hafen bregenz hafen austria at',
    NOW(), NOW()), ('9947734', NULL, 'Arion Vienna Airport', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.15041, 16.47683, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arion vienna airport arion vienna airport austria at',
    NOW(), NOW()), ('9956325', NULL, 'Das Reinisch Vienna Airport Hotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    48.15914, 16.48779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'das reinisch vienna airport hotel das reinisch vienna airport hotel austria at',
    NOW(), NOW()), ('9956328', NULL, 'Sporthotel Penz', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.25747, 11.35813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sporthotel penz sporthotel penz austria at',
    NOW(), NOW()), ('9956332', NULL, 'Sporthotel St.Aanton', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.12744, 10.26377, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sporthotel st.aanton sporthotel st.aanton austria at',
    NOW(), NOW()), ('9956348', NULL, 'Strass Sporthotel', NULL,
    NULL, 'AT', 'Austria', NULL, NULL,
    47.1633, 11.86104, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'strass sporthotel strass sporthotel austria at',
    NOW(), NOW());