INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('5906674', NULL, 'Bowdoin Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    60.33351, -64.48167, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bowdoin harbour bowdoin harbour canada ca',
    NOW(), NOW()), ('5906833', NULL, 'Bowmanville Harbour Conservation Area', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.90012, -78.66625, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bowmanville harbour conservation area bowmanville harbour conservation area canada ca',
    NOW(), NOW()), ('5906892', NULL, 'Boxey Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.44994, -55.54832, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boxey harbour boxey harbour canada ca',
    NOW(), NOW()), ('5906893', NULL, 'Boxey Harbour Head', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.44994, -55.54832, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boxey harbour head boxey harbour head canada ca',
    NOW(), NOW()), ('5907155', NULL, 'Braddock', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.10006, -107.38461, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braddock braddock canada ca',
    NOW(), NOW()), ('5907156', NULL, 'Braddock Reservoir', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.08336, -107.36801, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braddock reservoir braddock reservoir canada ca',
    NOW(), NOW()), ('5907204', NULL, 'Bradley Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.03337, -81.44976, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bradley harbour bradley harbour canada ca',
    NOW(), NOW()), ('5907283', NULL, 'Brae Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.61685, -64.18204, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brae harbour brae harbour canada ca',
    NOW(), NOW()), ('5907284', NULL, 'Brae Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.61685, -64.18204, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brae harbour brae harbour canada ca',
    NOW(), NOW()), ('5907707', NULL, 'Branche Nadeau-Lapierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.16447, -73.50476, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'branche nadeau-lapierre branche nadeau-lapierre canada ca',
    NOW(), NOW()), ('5907723', NULL, 'Branche Nord-Est de la Pierriche', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.1001, -73.09912, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'branche nord-est de la pierriche branche nord-est de la pierriche canada ca',
    NOW(), NOW()), ('5907757', NULL, 'Branche Pierre-Boucher', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.14976, -72.12549, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'branche pierre-boucher branche pierre-boucher canada ca',
    NOW(), NOW()), ('5907798', NULL, 'Branche Saint-Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.10687, -79.09653, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'branche saint-pierre branche saint-pierre canada ca',
    NOW(), NOW()), ('5908022', NULL, 'Bras de la Rivière Pierre-Paul', 'Bras de la Riviere Pierre-Paul',
    NULL, 'CA', 'Canada', NULL, NULL,
    46.73146, -72.4447, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bras de la rivière pierre-paul bras de la riviere pierre-paul canada ca',
    NOW(), NOW()), ('5908043', NULL, 'Bras du Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.96678, -70.79904, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bras du portage bras du portage canada ca',
    NOW(), NOW()), ('5908111', NULL, 'Braund Port', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.26682, -78.33283, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braund port braund port canada ca',
    NOW(), NOW()), ('5908421', NULL, 'Brennan Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.18337, -82.38314, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brennan harbour brennan harbour canada ca',
    NOW(), NOW()), ('5908422', NULL, 'Brennan Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.18757, -82.38594, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brennan harbour brennan harbour canada ca',
    NOW(), NOW()), ('5908423', NULL, 'Brennan Harbour Conservation Reserve', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.20007, -82.39154, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brennan harbour conservation reserve brennan harbour conservation reserve canada ca',
    NOW(), NOW()), ('5908522', NULL, 'Brevoort Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    63.31722, -64.1306, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brevoort harbour brevoort harbour canada ca',
    NOW(), NOW()), ('5908689', NULL, 'Bridgeport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.86485, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport bridgeport canada ca',
    NOW(), NOW()), ('5908690', NULL, 'Bridgeport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.20733, -59.99341, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport bridgeport canada ca',
    NOW(), NOW()), ('5908691', NULL, 'Bridgeport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.4834, -80.48299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport bridgeport canada ca',
    NOW(), NOW()), ('5908692', NULL, 'Bridgeport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.192, -123.092, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport bridgeport canada ca',
    NOW(), NOW()), ('5908693', NULL, 'Bridgeport Cove', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.21684, -59.99845, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport cove bridgeport cove canada ca',
    NOW(), NOW()), ('5908694', NULL, 'Bridgeport Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.86485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bridgeport harbour bridgeport harbour canada ca',
    NOW(), NOW()), ('5908695', NULL, 'Bridgeport Harbour Head', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.53322, -54.89815, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bridgeport harbour head bridgeport harbour head canada ca',
    NOW(), NOW()), ('5908696', NULL, 'Bridgeport Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.89815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport island bridgeport island canada ca',
    NOW(), NOW()), ('5908697', NULL, 'Bridgeport Rock', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.53322, -54.89815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridgeport rock bridgeport rock canada ca',
    NOW(), NOW()), ('5908739', NULL, 'Bridport Inlet', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    75.02624, -108.73444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridport inlet bridport inlet canada ca',
    NOW(), NOW()), ('5908907', NULL, 'Brimball Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.69995, -55.89833, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brimball harbour brimball harbour canada ca',
    NOW(), NOW()), ('5909053', NULL, 'British Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.2666, -53.49808, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'british harbour british harbour canada ca',
    NOW(), NOW()), ('5909054', NULL, 'British Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.2499, -53.49808, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'british harbour british harbour canada ca',
    NOW(), NOW()), ('5909055', NULL, 'British Harbour Point', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.2499, -53.49808, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'british harbour point british harbour point canada ca',
    NOW(), NOW()), ('5909333', NULL, 'Brodskys Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.97921, -97.53628, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brodskys harbour brodskys harbour canada ca',
    NOW(), NOW()), ('5909432', NULL, 'Bronte Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.39011, -79.71212, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bronte harbour bronte harbour canada ca',
    NOW(), NOW()), ('5909469', NULL, 'Brook Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.36663, -55.23147, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brook harbour brook harbour canada ca',
    NOW(), NOW()), ('5909510', NULL, 'Brookport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.25428, -72.86103, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brookport brookport canada ca',
    NOW(), NOW()), ('5909572', NULL, 'Brooks Wharf', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.65014, -63.91543, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brooks wharf brooks wharf canada ca',
    NOW(), NOW()), ('5909586', NULL, 'Broomclose Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.6832, -53.63139, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'broomclose harbour broomclose harbour canada ca',
    NOW(), NOW()), ('5909684', NULL, 'Broughton Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    67.51746, -64.09685, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'broughton harbour broughton harbour canada ca',
    NOW(), NOW()), ('5909804', NULL, 'Brown Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.26664, -55.315, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brown harbour brown harbour canada ca',
    NOW(), NOW()), ('5909805', NULL, 'Brown Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    65.9507, -65.94724, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brown harbour brown harbour canada ca',
    NOW(), NOW()), ('5910001', NULL, 'Browns Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.27214, -55.3119, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'browns harbour browns harbour canada ca',
    NOW(), NOW()), ('5910002', NULL, 'Browns Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    70.11977, -124.39665, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'browns harbour browns harbour canada ca',
    NOW(), NOW()), ('5910003', NULL, 'Browns Harbour Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.27434, -55.3208, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'browns harbour island browns harbour island canada ca',
    NOW(), NOW()), ('5910004', NULL, 'Browns Harbour Pond', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.26994, -55.3111, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'browns harbour pond browns harbour pond canada ca',
    NOW(), NOW()), ('5910093', NULL, 'Bruce Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    62.75085, -70.13145, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bruce harbour bruce harbour canada ca',
    NOW(), NOW()), ('5910196', NULL, 'Brule Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.75015, -63.18197, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brule harbour brule harbour canada ca',
    NOW(), NOW()), ('5910197', NULL, 'Brulé Harbour', 'Brule Harbour',
    NULL, 'CA', 'Canada', NULL, NULL,
    47.81679, -84.93318, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'brulé harbour brule harbour canada ca',
    NOW(), NOW());