INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8815522', NULL, 'Old Mission', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.12904, 129.49782, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'old mission old mission australia au old mission,port keats mission',
    NOW(), NOW()), ('8815669', NULL, 'Portana', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.76138, 135.37768, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portana portana australia au portana',
    NOW(), NOW()), ('8815717', NULL, 'Narraport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.64723, 144.34503, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'narraport narraport australia au narraport',
    NOW(), NOW()), ('8816190', NULL, 'Spier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.30019, 150.38224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'spier spier australia au spier',
    NOW(), NOW()), ('8816454', NULL, 'Locharbor', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.47771, 148.31997, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'locharbor locharbor australia au locharbor',
    NOW(), NOW()), ('8816535', NULL, 'Airport Block', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.55181, 148.17872, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport block airport block australia au airport block',
    NOW(), NOW()), ('8816557', NULL, 'Portwine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.82656, 147.15541, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portwine portwine australia au portwine',
    NOW(), NOW()), ('8817172', NULL, 'Narraport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.02862, 142.92915, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'narraport narraport australia au narraport',
    NOW(), NOW()), ('8817454', NULL, 'Comdock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.50185, 143.52593, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comdock comdock australia au comdock',
    NOW(), NOW()), ('8818074', NULL, 'Maes-Y-Porth', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.22772, 142.51037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maes-y-porth maes-y-porth australia au maes-y-porth',
    NOW(), NOW()), ('8818421', NULL, 'Lyndock Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.43641, 141.33218, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lyndock park lyndock park australia au lyndock park',
    NOW(), NOW()), ('8818504', NULL, 'Pieracle', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.76803, 141.29687, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pieracle pieracle australia au pieracle',
    NOW(), NOW()), ('8818657', NULL, 'Jallukar', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.21203, 142.68648, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jallukar jallukar australia au jallukar',
    NOW(), NOW()), ('8819020', NULL, 'Importna', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.94048, 132.74341, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'importna importna australia au importna',
    NOW(), NOW()), ('8819107', NULL, 'Palm Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.08534, 132.68126, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palm paddock palm paddock australia au palm paddock',
    NOW(), NOW()), ('8819437', NULL, 'Aluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.58678, 135.86182, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aluka aluka australia au aluka',
    NOW(), NOW()), ('8819439', NULL, 'Aluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.79331, 137.78323, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aluka aluka australia au aluka',
    NOW(), NOW()), ('8819442', NULL, 'Amarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.92416, 138.73793, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amarina amarina australia au amarina',
    NOW(), NOW()), ('8819443', NULL, 'Amarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.48252, 140.77372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amarina amarina australia au amarina',
    NOW(), NOW()), ('8819797', NULL, 'Amarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.75413, 138.97507, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amarina amarina australia au amarina',
    NOW(), NOW()), ('8819930', NULL, 'Bandar Log', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.65651, 138.8766, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar log bandar log australia au bandar log',
    NOW(), NOW()), ('8819992', NULL, 'Denport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.45528, 138.37565, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'denport denport australia au denport',
    NOW(), NOW()), ('8820165', NULL, 'Big Prices Paddock Run', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.31546, 140.15208, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big prices paddock run big prices paddock run australia au big prices paddock run',
    NOW(), NOW()), ('8821925', NULL, 'Iluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.94212, 137.14755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka iluka australia au iluka',
    NOW(), NOW()), ('8822417', NULL, 'Lluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.35443, 137.92521, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lluka lluka australia au lluka',
    NOW(), NOW()), ('8822461', NULL, 'Portreath', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.65119, 134.31243, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portreath portreath australia au portreath',
    NOW(), NOW()), ('8822575', NULL, 'Maluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.1759, 135.75337, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maluka maluka australia au maluka',
    NOW(), NOW()), ('8822576', NULL, 'Maluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.15663, 138.87038, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maluka maluka australia au maluka',
    NOW(), NOW()), ('8822577', NULL, 'Maluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.08114, 138.5927, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maluka maluka australia au maluka',
    NOW(), NOW()), ('8823375', NULL, 'Puddledock Farm', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.74318, 138.90696, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puddledock farm puddledock farm australia au puddledock farm',
    NOW(), NOW()), ('8824980', NULL, 'Portlands', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.24786, 138.58013, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portlands portlands australia au portlands',
    NOW(), NOW()), ('8825707', NULL, 'Olierdock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.68751, 138.88459, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olierdock olierdock australia au olierdock',
    NOW(), NOW()), ('8826484', NULL, 'Porto Bella Farm', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.92877, 116.9762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto bella farm porto bella farm australia au porto bella farm',
    NOW(), NOW()), ('8826494', NULL, 'Mount Pierre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.5897, 126.1396, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre mount pierre australia au mount pierre',
    NOW(), NOW()), ('8826560', NULL, 'Port Melbourne Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.84042, 144.93292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port melbourne station port melbourne station australia au port melbourne station',
    NOW(), NOW()), ('8826947', NULL, 'Southport Siding', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.7706, 131.01, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'southport siding southport siding australia au southport siding',
    NOW(), NOW()), ('8827230', NULL, 'Mackay Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.10691, 149.22159, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mackay harbour mackay harbour australia au mackay harbour',
    NOW(), NOW()), ('8827874', NULL, 'Beachport Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.4737, 140.00311, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beachport railway station beachport railway station australia au beachport railway station',
    NOW(), NOW()), ('8828096', NULL, 'Port Broughton Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.60181, 137.93444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton railway station port broughton railway station australia au port broughton railway station',
    NOW(), NOW()), ('8828097', NULL, 'Port Elliot Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.5327, 138.6806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot railway station port elliot railway station australia au port elliot railway station',
    NOW(), NOW()), ('8828098', NULL, 'Port Germein Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.00952, 138.00461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port germein railway station port germein railway station australia au port germein railway station',
    NOW(), NOW()), ('8828099', NULL, 'Port Lincoln Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.72458, 135.86719, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln railway station port lincoln railway station australia au port lincoln railway station',
    NOW(), NOW()), ('8828100', NULL, 'Port Pirie Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.18156, 138.01131, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port pirie railway station port pirie railway station australia au port pirie railway station',
    NOW(), NOW()), ('8828101', NULL, 'Port Wakefield Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.18298, 138.15111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port wakefield railway station port wakefield railway station australia au port wakefield railway station',
    NOW(), NOW()), ('8828200', NULL, 'Outer Harbor Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.77819, 138.48451, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'outer harbor railway station outer harbor railway station australia au outer harbor railway station',
    NOW(), NOW()), ('8828260', NULL, 'Stockport Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.33404, 138.73431, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stockport railway station stockport railway station australia au stockport railway station',
    NOW(), NOW()), ('8828289', NULL, 'Victor Harbor Railway Station', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.55449, 138.62396, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'victor harbor railway station victor harbor railway station australia au victor harbor railway station',
    NOW(), NOW()), ('8828366', NULL, 'Boat Harbour Siding', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.96, 145.61, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour siding boat harbour siding australia au boat harbour siding',
    NOW(), NOW()), ('8828436', NULL, 'Harbourside Docklands Tram Stop', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.81833, 144.94611, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbourside docklands tram stop harbourside docklands tram stop australia au harbourside docklands tram stop',
    NOW(), NOW()), ('8828525', NULL, 'Barraport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.00792, 143.66514, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barraport barraport australia au barraport',
    NOW(), NOW());