INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('9034683', NULL, 'El Triunfo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.85325, -65.80441, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el triunfo airport el triunfo airport bolivia bo aeroportul el triunfo,el triunfo airport,slef,aerodrome de el triunfo,aérodrome de el triunfo,エル・トリウンフォ空港',
    NOW(), NOW()), ('9034684', NULL, 'Laguna Colorada Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -22.2735, -67.77376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna colorada airport laguna colorada airport bolivia bo sllc',
    NOW(), NOW()), ('9034685', NULL, 'Izozog Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.67025, -63.00234, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'izozog airport izozog airport bolivia bo aeroportul izozog,izozog airport,sliz,isosogu kong gang,イソソグ空港',
    NOW(), NOW()), ('9034732', NULL, 'El Desengaño Airport', 'El Desengano Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.27355, -65.43999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el desengaño airport el desengano airport bolivia bo sldn',
    NOW(), NOW()), ('9034734', NULL, 'Choreti Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.50967, -64.96696, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'choreti airport choreti airport bolivia bo aeroportul choreti,aeropuerto choreti,choreti airport,slct,choreti kong gang,チョレティ空港',
    NOW(), NOW()), ('9034735', NULL, 'El Porvenir Sur Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.7548, -63.20937, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el porvenir sur airport el porvenir sur airport bolivia bo slpw',
    NOW(), NOW()), ('9034738', NULL, 'Camiare Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.0823, -65.65812, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camiare airport camiare airport bolivia bo aeroportul camiare,camiare airport,slcm,kamiare kong gang,カミアレ空港',
    NOW(), NOW()), ('9034739', NULL, 'Itaguazurenda Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.78459, -63.08558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itaguazurenda airport itaguazurenda airport bolivia bo aeroportul itaguazurenda,aeropuerto itaguazurenda,itaguazurenda airport,slit,itauasurenda kong gang,イタウアスレンダ空港',
    NOW(), NOW()), ('9034743', NULL, 'Nieve Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.02248, -65.81197, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nieve airport nieve airport bolivia bo slnv',
    NOW(), NOW()), ('9034745', NULL, 'El Cairo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.79078, -66.3215, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el cairo airport el cairo airport bolivia bo aeroportul el cairo,el cairo airport,slec,エル・カイロ空港',
    NOW(), NOW()), ('9034746', NULL, 'Cachascani Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.52687, -64.2342, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cachascani airport cachascani airport bolivia bo slha',
    NOW(), NOW()), ('9034747', NULL, 'San Juan Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.16387, -64.75849, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san juan airport san juan airport bolivia bo sljn',
    NOW(), NOW()), ('9034748', NULL, 'Irobi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.26898, -63.69182, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'irobi airport irobi airport bolivia bo aeroportul irobi,irobi airport,slir,irobi kong gang,イロビ空港',
    NOW(), NOW()), ('9034751', NULL, 'Josuani Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.10796, -66.17364, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'josuani airport josuani airport bolivia bo sljs',
    NOW(), NOW()), ('9034756', NULL, 'La Vertiente Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.28738, -63.29558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la vertiente airport la vertiente airport bolivia bo slvt',
    NOW(), NOW()), ('9034761', NULL, 'El Paraíso Airport', 'El Paraiso Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.40399, -65.87994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el paraíso airport el paraiso airport bolivia bo sleo',
    NOW(), NOW()), ('9034763', NULL, 'Taquipirenda Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.33702, -63.14083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taquipirenda airport taquipirenda airport bolivia bo aeroportul taquipirenda,slta,taquipirenda airport,takipirenda kong gang,タキピレンダ空港',
    NOW(), NOW()), ('9035116', NULL, 'La Esperanza Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.41725, -65.51774, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la esperanza airport la esperanza airport bolivia bo slez',
    NOW(), NOW()), ('9035117', NULL, 'El Salvador Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.49839, -66.76301, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el salvador airport el salvador airport bolivia bo slev',
    NOW(), NOW()), ('9035118', NULL, 'Florencia Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.68738, -65.53025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'florencia airport florencia airport bolivia bo aeroportul florencia,florencia airport,slfr,furorenshia kong gang,フロレンシア空港',
    NOW(), NOW()), ('9035120', NULL, 'Palmira Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.73741, -66.40967, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palmira airport palmira airport bolivia bo aeroportul palmira,palmira airport,slpm,parumira kong gang,パルミラ空港',
    NOW(), NOW()), ('9035122', NULL, 'Santa Ana de Huachi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.49463, -67.44329, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa ana de huachi airport santa ana de huachi airport bolivia bo aeroportul santa ana de huachi,slsh,santa ana de huachi airport,サンタ・アナ・デ・ウアチ空港',
    NOW(), NOW()), ('9035124', NULL, 'Santa Rita Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.90872, -66.36251, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa rita airport santa rita airport bolivia bo aeroportul santa rita,slrt,santa rita airport,サンタ・リタ空港',
    NOW(), NOW()), ('9035125', NULL, 'Villazon Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -22.05152, -65.63803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villazon airport villazon airport bolivia bo aeroportul villazon,slvz,villazon airport,biryason kong gang,ビリャソン空港',
    NOW(), NOW()), ('9035127', NULL, 'Urusi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.32365, -66.12804, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'urusi airport urusi airport bolivia bo aeroportul urusi,slus,urusi airport,urushi kong gang,ウルシ空港',
    NOW(), NOW()), ('9035128', NULL, 'San Francisco Naciff Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.75673, -64.47228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san francisco naciff airport san francisco naciff airport bolivia bo aeroportul san francisco naciff,slzf,san francisco naciff airport,サン・フランシスコ・ナシフ空港',
    NOW(), NOW()), ('9035129', NULL, 'San Pedro del Rio Blanco Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.1876, -63.54801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san pedro del rio blanco airport san pedro del rio blanco airport bolivia bo slzj',
    NOW(), NOW()), ('9035130', NULL, 'Venecia Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.63641, -66.75031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'venecia airport venecia airport bolivia bo aeroportul venecia,slve,venecia airport,beneshia kong gang,ベネシア空港',
    NOW(), NOW()), ('9035131', NULL, 'Tupiza Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.33944, -65.61275, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tupiza airport tupiza airport bolivia bo sltz',
    NOW(), NOW()), ('9035132', NULL, 'Tiguipa Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.00508, -63.30421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiguipa airport tiguipa airport bolivia bo slty',
    NOW(), NOW()), ('9035136', NULL, 'Santiago Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.229, -65.45058, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santiago airport santiago airport bolivia bo sltg',
    NOW(), NOW()), ('9035269', NULL, 'Angora Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.42837, -65.7918, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'angora airport angora airport bolivia bo aeroportul angora,aeropuerto de angora,angora airport,angora flygfaelt,angora flygfält,slan,angora kong gang,アンゴラ空港',
    NOW(), NOW()), ('9035275', NULL, 'Bella Unión Airport', 'Bella Union Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.62743, -65.27372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bella unión airport bella union airport bolivia bo aeroporto bella union,aeroporto bella unión,aeroportul bella union,aeroportul bella unión,aeropuerto de bella union,aeropuerto de bella unión,bella union airport,bella unión airport,slbn,ベジャ・ウニオン空港',
    NOW(), NOW()), ('9035276', NULL, 'Bella Vista Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.86825, -66.33081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bella vista airport bella vista airport bolivia bo slbv',
    NOW(), NOW()), ('9035279', NULL, 'Buen Retiro Ballivian Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.91318, -66.56269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buen retiro ballivian airport buen retiro ballivian airport bolivia bo aeroportul buen retiro ballivian,aeropuerto de buen retiro ballivian,aeropuerto de buen retiro ballivián,buen retiro ballivian airport,slbt,ブエン・レティロ・バリビアン空港',
    NOW(), NOW()), ('9035280', NULL, 'Buen Retiro Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.44469, -63.50278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buen retiro airport buen retiro airport bolivia bo aeroportul buen retiro,buen retiro airport,slbr,ブエン・レティロ空港',
    NOW(), NOW()), ('9035654', NULL, 'Retiro Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.48682, -66.30773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'retiro airport retiro airport bolivia bo slrr',
    NOW(), NOW()), ('9035656', NULL, 'Yabog Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.65493, -63.13281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yabog airport yabog airport bolivia bo aeroportul yabog,maes awyr yabog,slyg,yabog airport',
    NOW(), NOW()), ('9035658', NULL, 'Villa Negrita Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.28214, -65.80266, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa negrita airport villa negrita airport bolivia bo aeroportul villa negrita,slvn,villa negrita airport,ビジャ・ネグリタ空港',
    NOW(), NOW()), ('9035745', NULL, 'San Carlos Gutierrez Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.56371, -65.52617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san carlos gutierrez airport san carlos gutierrez airport bolivia bo aeropuerto san carlos gutierrez,slsd',
    NOW(), NOW()), ('9035746', NULL, 'San Pedro Salvatierra Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.83716, -65.70335, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san pedro salvatierra airport san pedro salvatierra airport bolivia bo aeroportul san pedro salvatierra,slzb,san pedro salvatierra airport,サン・ペドロ・サルバティエラ空港',
    NOW(), NOW()), ('9036029', NULL, 'Huacaraje Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.60591, -63.87928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'huacaraje airport huacaraje airport bolivia bo aeroportul huacaraje,bvk,huacaraje airport,slhj,uakarahe kong gang,wa ka la he ji chang,ウアカラヘ空港,瓦卡拉赫機場',
    NOW(), NOW()), ('9882982', NULL, 'La Terminal', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.54363, -64.72763, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'la terminal la terminal bolivia bo',
    NOW(), NOW()), ('10400331', NULL, 'Puerto Acosta Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.5, -69.16667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto acosta municipality puerto acosta municipality bolivia bo',
    NOW(), NOW()), ('10400341', NULL, 'Puerto Carabuco Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.58333, -69, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto carabuco municipality puerto carabuco municipality bolivia bo',
    NOW(), NOW()), ('10400500', NULL, 'Puerto Villarroel Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.9167, -64.75, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto villarroel municipality puerto villarroel municipality bolivia bo',
    NOW(), NOW()), ('10400599', NULL, 'Puerto Perez Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.3333, -68.5833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto perez municipality puerto perez municipality bolivia bo',
    NOW(), NOW()), ('10400840', NULL, 'Puerto Rico Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.36667, -67.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto rico municipality puerto rico municipality bolivia bo',
    NOW(), NOW()), ('11138010', NULL, 'Portezuelo Armasaya', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.63872, -68.5968, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo armasaya portezuelo armasaya bolivia bo portezuelo armasaya',
    NOW(), NOW()), ('11140761', NULL, 'Hito XXXV', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.44086, -68.44047, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hito xxxv hito xxxv bolivia bo hito xxxv,portezuelo de la sierra de huilla',
    NOW(), NOW());