INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3833193', NULL, 'Laguna Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.99364, -60.52734, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna vallimanca laguna vallimanca argentina ar',
    NOW(), NOW()), ('3833194', NULL, 'Estancia Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.95199, -60.47615, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia vallimanca estancia vallimanca argentina ar',
    NOW(), NOW()), ('3833195', NULL, 'Arroyo Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.82394, -60.2973, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo vallimanca arroyo vallimanca argentina ar',
    NOW(), NOW()), ('3833196', NULL, 'Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.93333, -60.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vallimanca vallimanca argentina ar',
    NOW(), NOW()), ('3833197', NULL, 'Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.3429, -61.03302, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vallimanca vallimanca argentina ar vallimanca',
    NOW(), NOW()), ('3833232', NULL, 'Paso Vallecito', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.45, -70.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso vallecito paso vallecito argentina ar paso vallecillo,paso vallecito,portezuelo vallecillos,portezuelo vallecitos,portezuelo de vallecita,punto accesible vallecito',
    NOW(), NOW()), ('3833247', NULL, 'Portezuelo de Valle Ancho Sur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.43333, -68.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de valle ancho sur portezuelo de valle ancho sur argentina ar portezuelo valle ancho ii,portezuelo valle ancho segundo,portezuelo valle ancho sur,portezuelo de valle ancho sur',
    NOW(), NOW()), ('3833248', NULL, 'Portezuelo de Valle Ancho Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.41667, -68.93333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de valle ancho norte portezuelo de valle ancho norte argentina ar portezuelo valle ancho i,portezuelo valle ancho norte,portezuelo valle ancho norte primero,portezuelo de valle ancho norte',
    NOW(), NOW()), ('3833276', NULL, 'Estancia Valdés', 'Estancia Valdes',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.44474, -63.649, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia valdés estancia valdes argentina ar estancia valdes,estancia valdés,puerto valdes,puerto valdés',
    NOW(), NOW()), ('3833305', NULL, 'Portillo de las Vacas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.83333, -69.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de las vacas portillo de las vacas argentina ar',
    NOW(), NOW()), ('3833353', NULL, 'Uspallata Pass', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.8253, -70.08295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uspallata pass uspallata pass argentina ar boquete uspallata,la cumbre,paso de uspallata,paso de la cumbre,portillo de uspallata,uspallata pass,uspallata-juncal pass',
    NOW(), NOW()), ('3833359', NULL, 'Uspallata', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.55, -69.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uspallata uspallata argentina ar aeropuerto de uspallata,uspallata,uspallata airport',
    NOW(), NOW()), ('3833376', NULL, 'Portillo Urrutia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.44379, -70.38662, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo urrutia portillo urrutia argentina ar',
    NOW(), NOW()), ('3833610', NULL, 'Paso Tromen Primero', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.5, -71.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso tromen primero paso tromen primero argentina ar paso tromen i,paso tromen primero,portezuelo tromen,portezuelo tromén',
    NOW(), NOW()), ('3833622', NULL, 'Paso Trolón', 'Paso Trolon',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.78333, -70.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso trolón paso trolon argentina ar paso trolon,paso trolón,portezuelo trolon sur,portezuelo trolón sur',
    NOW(), NOW()), ('3833688', NULL, 'Paso de Tres Quebradas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.31667, -68.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de tres quebradas paso de tres quebradas argentina ar paso toro muerto,paso tres quebradas,paso de toro muerto,paso de tres quebradas,portezuelo de tres quebradas',
    NOW(), NOW()), ('3833724', NULL, 'Tres Porteñas', 'Tres Portenas',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.89884, -68.38811, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tres porteñas tres portenas argentina ar tres portenas,tres porteñas',
    NOW(), NOW()), ('3833860', NULL, 'Tres Arroyos Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.38876, -60.32928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tres arroyos airport tres arroyos airport argentina ar oyo,sazh,tres arroyos airport',
    NOW(), NOW()), ('3834028', NULL, 'Portillo la Totora', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.23175, -70.14542, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo la totora portillo la totora argentina ar',
    NOW(), NOW()), ('3834056', NULL, 'Portezuelo Toscoso', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.54828, -70.16731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo toscoso portezuelo toscoso argentina ar portezuelo toscoso,portillo toscoso',
    NOW(), NOW()), ('3834292', NULL, 'Portezuelo de Tocino', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.8, -67.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de tocino portezuelo de tocino argentina ar',
    NOW(), NOW()), ('3834416', NULL, 'Portillo del Tigre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.14198, -69.5509, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del tigre portillo del tigre argentina ar',
    NOW(), NOW()), ('3834544', NULL, 'Portillo del Telégrafo', 'Portillo del Telegrafo',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.78813, -68.99957, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del telégrafo portillo del telegrafo argentina ar',
    NOW(), NOW()), ('3834614', NULL, 'Portezuelo Tar', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -48.95, -72, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo tar portezuelo tar argentina ar',
    NOW(), NOW()), ('3834982', NULL, 'Portezuelo Sumich', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.8, -70.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sumich portezuelo sumich argentina ar',
    NOW(), NOW()), ('3835072', NULL, 'Portezuelo de Soroche', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.0778, -67.46224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de soroche portezuelo de soroche argentina ar',
    NOW(), NOW()), ('3835119', NULL, 'Cajón Solimán', 'Cajon Soliman',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.01667, -71.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cajón solimán cajon soliman argentina ar',
    NOW(), NOW()), ('3835211', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.15, -71.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar paso pulul norte,portezuelo santa pola,portezuelo sin nombre',
    NOW(), NOW()), ('3835212', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.11667, -71.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo san rosario,portezuelo sin nombre',
    NOW(), NOW()), ('3835213', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.01667, -71.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo sin nombre',
    NOW(), NOW()), ('3835214', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.95, -71.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo sin nombre',
    NOW(), NOW()), ('3835356', NULL, 'Portezuelo Laguna Fea', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.16667, -70.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo laguna fea portezuelo laguna fea argentina ar paso saco,paso de sepulveda,paso de sepúlveda,portezuelo laguna fea',
    NOW(), NOW()), ('3835953', NULL, 'Portezuelo Santa Rosa', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.93333, -67.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo santa rosa portezuelo santa rosa argentina ar',
    NOW(), NOW()), ('3836082', NULL, 'Colonia Santamarina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.3, -64.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colonia santamarina colonia santamarina argentina ar',
    NOW(), NOW()), ('3836280', NULL, 'Aerodromo Santa Fe', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.66667, -60.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aerodromo santa fe aerodromo santa fe argentina ar safe,santa fe airport,santa fé airport',
    NOW(), NOW()), ('3836297', NULL, 'Puerto Santa Elena', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -44.52289, -65.34865, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto santa elena puerto santa elena argentina ar port santa elena,puerto santa elena',
    NOW(), NOW()), ('3836383', NULL, 'Portillo Santa Clara', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.26649, -69.69321, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo santa clara portillo santa clara argentina ar portillo santa clara,portillo del azufre',
    NOW(), NOW()), ('3836607', NULL, 'Fondeadero San Román', 'Fondeadero San Roman',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.25242, -64.25867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fondeadero san román fondeadero san roman argentina ar fondeadero roman,fondeadero san roman,fondeadero san román,puerto san roman,puerto san román',
    NOW(), NOW()), ('3836687', NULL, 'Portezuelo Sanquilcó', 'Portezuelo Sanquilco',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.73513, -70.8114, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sanquilcó portezuelo sanquilco argentina ar',
    NOW(), NOW()), ('3837055', NULL, 'Caleta San Luis', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.73632, -63.95931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caleta san luis caleta san luis argentina ar puerto san luis,puerto shank',
    NOW(), NOW()), ('3837131', NULL, 'Bahía San Julián', 'Bahia San Julian',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.34035, -67.709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bahía san julián bahia san julian argentina ar bahia san julian,bahía san julián,puerto san julian,san julian bay,san julián bay',
    NOW(), NOW()), ('3837140', NULL, 'Puerto San Juan del Salvamento', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.73949, -63.85529, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san juan del salvamento puerto san juan del salvamento argentina ar puerto san juan,puerto san juan del salvamento,saint john harbour',
    NOW(), NOW()), ('3837255', NULL, 'Puerto San José', 'Puerto San Jose',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.41729, -64.12117, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san josé puerto san jose argentina ar',
    NOW(), NOW()), ('3837639', NULL, 'Paso de San Francisco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.87169, -68.29731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de san francisco paso de san francisco argentina ar paso de san francisco,portezuelo san francisco,san francisco pass',
    NOW(), NOW()), ('3837913', NULL, 'Portezuelo de San Buenaventura', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.78479, -67.88299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de san buenaventura portezuelo de san buenaventura argentina ar',
    NOW(), NOW()), ('3837980', NULL, 'San Antonio Oeste', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.73193, -64.94769, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'san antonio oeste san antonio oeste argentina ar oes,puerto san antonio oeste,san antonio oeste,san antonio oestė,xi sheng an dong ni ao,西圣安东尼奥',
    NOW(), NOW()), ('3837999', NULL, 'Puerto San Antonio', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.74526, -64.86488, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san antonio puerto san antonio argentina ar',
    NOW(), NOW()), ('3838282', NULL, 'Portezuelo de Salin Sur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.36667, -68.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de salin sur portezuelo de salin sur argentina ar paso del salin,paso del salín,portezuelo salin,portezuelo salín,portezuelo de salin sur',
    NOW(), NOW()), ('3838559', NULL, 'Rosario International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.90361, -60.785, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'rosario international airport rosario international airport argentina ar aeroporto internacional rosario islas malvinas,aeroporto de rosario-illas malvinas,aeroporto di rosario,aeroportul international rosario - islas malvinas,aeroportul internațional rosario – islas malvinas,aeropuerto internacional rosario,aeropuerto internacional rosario islas malvinas,bandar udara internasional rosario - islas malvinas,bandar udara internasional rosario – islas malvinas,flughafen rosario,lapangan terbang rosario,port lotniczy rosario,ros,rosario - islas malvinas international airport,rosario international airport,rosario – islas malvinas international airport,saar,aeroport de rosario,aéroport de rosario,luo sa li ao,mtar rwzaryw aldwlyt,rosario,фурудгоҳи бин‌алмилалӣ рсрю – оислс млуинс,נמל התעופה הבינלאומי רוסאריו איסלאס מלווינס,فرودگاه بین‌المللی رسریو – ایسلس ملوینس,مطار روزاريو الدولية,ロサリオ,羅薩里奧',
    NOW(), NOW()), ('3838597', NULL, 'Portezuelo del Rosal', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.46667, -64.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del rosal portezuelo del rosal argentina ar',
    NOW(), NOW());