INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('11280047', NULL, 'Sheraton Mirage Port Douglas Resort', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.50171, 145.4655, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sheraton mirage port douglas resort sheraton mirage port douglas resort australia au',
    NOW(), NOW()), ('11287896', NULL, 'Point Stephens Lighthouse', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.74704, 152.20142, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point stephens lighthouse point stephens lighthouse australia au port stephens lighthouse',
    NOW(), NOW()), ('11287908', NULL, 'Port Denison', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.02723, 148.24522, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port denison port denison australia au',
    NOW(), NOW()), ('11287909', NULL, 'North Head Lighthouse (historical)', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.02004, 148.27496, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north head lighthouse (historical) north head lighthouse (historical) australia au bower light,port denison light',
    NOW(), NOW()), ('11287996', NULL, 'Kiama Light', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.67181, 150.8626, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kiama light kiama light australia au kiama harbour light',
    NOW(), NOW()), ('11288045', NULL, 'Fremantle Heliport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.04147, 115.75603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fremantle heliport fremantle heliport australia au fremantle heliport,jfm',
    NOW(), NOW()), ('11353059', NULL, 'Yorkey''s Knob Boating Club', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.80158, 145.71789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yorkey''s knob boating club yorkey''s knob boating club australia au',
    NOW(), NOW()), ('11398192', NULL, 'Port Kingscote', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.64575, 137.66217, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kingscote port kingscote australia au',
    NOW(), NOW()), ('11398199', NULL, 'Flinders Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.47533, 145.02498, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'flinders pier flinders pier australia au',
    NOW(), NOW()), ('11429285', NULL, 'Sydney Harbour National Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.85329, 151.19647, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'sydney harbour national park sydney harbour national park australia au sydney harbour national park',
    NOW(), NOW()), ('11497237', NULL, 'Shellharbour Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.58045, 150.87513, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour reserve shellharbour reserve australia au',
    NOW(), NOW()), ('11497238', NULL, 'Shellharbour City Cemetery', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5839, 150.85914, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour city cemetery shellharbour city cemetery australia au',
    NOW(), NOW()), ('11497257', NULL, 'Boat Harbour Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.03115, 151.19565, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour park boat harbour park australia au',
    NOW(), NOW()), ('11497870', NULL, 'Dixie Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.11759, 143.31545, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dixie airport dixie airport australia au dxd,dixie airport,ydix',
    NOW(), NOW()), ('11524332', NULL, 'Ballidonia Station Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.46683, 123.84244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ballidonia station airport ballidonia station airport australia au',
    NOW(), NOW()), ('11550608', NULL, 'Kalpowar Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.89031, 144.22049, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalpowar airport kalpowar airport australia au kpp,kalpowar airport,ykpr',
    NOW(), NOW()), ('11551522', NULL, 'Breaden Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.27689, 147.73481, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'breaden sports ground breaden sports ground australia au breaden sports ground,tarcutta recreation ground',
    NOW(), NOW()), ('11592579', NULL, 'Finley Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.65857, 145.56112, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'finley airport finley airport australia au fly,yfil',
    NOW(), NOW()), ('11592717', NULL, 'Coral Bay Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.12674, 113.78141, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coral bay airport coral bay airport australia au ycoy',
    NOW(), NOW()), ('11612397', NULL, 'Constitution Dock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.88261, 147.33316, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'constitution dock constitution dock australia au',
    NOW(), NOW()), ('11612398', NULL, 'Victoria Dock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.88184, 147.33435, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'victoria dock victoria dock australia au',
    NOW(), NOW()), ('11612399', NULL, 'Elizabeth Street Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.88416, 147.3339, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'elizabeth street pier elizabeth street pier australia au',
    NOW(), NOW()), ('11612400', NULL, 'Princess Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.88592, 147.33501, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'princess wharf princess wharf australia au',
    NOW(), NOW()), ('11612438', NULL, 'Strand Pier, Townsville', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -19.24495, 146.81042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'strand pier, townsville strand pier, townsville australia au',
    NOW(), NOW()), ('11669665', NULL, 'Duckport Lagoon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.43167, 150.51435, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'duckport lagoon duckport lagoon australia au',
    NOW(), NOW()), ('11670293', NULL, 'Mary River Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.53957, 152.7067, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mary river marina mary river marina australia au',
    NOW(), NOW()), ('11670594', NULL, 'Mustering Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.16504, 146.73894, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mustering paddock tank mustering paddock tank australia au mustering paddock tank',
    NOW(), NOW()), ('11703734', NULL, 'Dongara Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.29922, 114.92729, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dongara airport dongara airport australia au dox,ydra',
    NOW(), NOW()), ('11703735', NULL, 'Porepunkah Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.71875, 146.88961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porepunkah airport porepunkah airport australia au mbf,ypok',
    NOW(), NOW()), ('11704269', NULL, 'East Devonport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.18792, 146.3866, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east devonport east devonport australia au',
    NOW(), NOW()), ('11704285', NULL, 'Port Pirie West', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1779, 137.9985, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port pirie west port pirie west australia au',
    NOW(), NOW()), ('11704377', NULL, 'New Port', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84431, 138.49438, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'new port new port australia au',
    NOW(), NOW()), ('11704423', NULL, 'Portland North', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.30853, 141.57068, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland north portland north australia au',
    NOW(), NOW()), ('11745906', NULL, 'Port Mannum', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.92419, 139.30377, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port mannum port mannum australia au',
    NOW(), NOW()), ('11746042', NULL, 'Boat Harbour Beach', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.92947, 145.61687, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour beach boat harbour beach australia au boat harbour beach',
    NOW(), NOW()), ('11746424', NULL, 'Port Pirie South', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.19797, 138.01446, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port pirie south port pirie south australia au',
    NOW(), NOW()), ('11746445', NULL, 'Port Albany', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.03186, 117.9003, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port albany port albany australia au',
    NOW(), NOW()), ('11746584', NULL, 'Gladstone Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.7748, 151.32648, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gladstone harbour gladstone harbour australia au',
    NOW(), NOW()), ('11746846', NULL, 'Granville Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.80795, 145.03627, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'granville harbour granville harbour australia au granville harbour',
    NOW(), NOW()), ('11747026', NULL, 'Pierces Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.16561, 152.02894, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierces creek pierces creek australia au',
    NOW(), NOW()), ('11747640', NULL, 'Blanche Harbor', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.69072, 137.75527, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'blanche harbor blanche harbor australia au blanche harbor',
    NOW(), NOW()), ('11747682', NULL, 'Trial Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.92942, 145.17519, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'trial harbour trial harbour australia au',
    NOW(), NOW()), ('11747966', NULL, 'Dockers Plains', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.29659, 146.3372, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dockers plains dockers plains australia au',
    NOW(), NOW()), ('11749085', NULL, 'Porter Lagoon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.82276, 138.87908, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter lagoon porter lagoon australia au',
    NOW(), NOW()), ('11749189', NULL, 'Port Wine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.61637, 147.28975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port wine port wine australia au',
    NOW(), NOW()), ('11775093', NULL, 'Port Kembla RSL Lodge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.36051, 148.5108, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla rsl lodge port kembla rsl lodge australia au port kembla rsl lodge',
    NOW(), NOW()), ('11776329', NULL, 'Cold Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.88729, 116.83724, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cold harbour cold harbour australia au',
    NOW(), NOW()), ('11776407', NULL, 'Port Gawler', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.64168, 138.47533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port gawler port gawler australia au',
    NOW(), NOW()), ('11776510', NULL, 'Napier Lane', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.29857, 149.43861, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier lane napier lane australia au',
    NOW(), NOW()), ('11793356', NULL, 'Bundocks Crossing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.18069, 153.05759, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bundocks crossing bundocks crossing australia au bundocks crossing',
    NOW(), NOW());