INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('13000701', NULL, 'Loteamento Matão', 'Loteamento Matao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.81542, -48.90397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'loteamento matão loteamento matao brazil br biondo,loteamento adriana,loteamento matao,loteamento matão,n esp. porto carolina',
    NOW(), NOW()), ('13000874', NULL, 'Arroio Porteira da Chave', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.26869, -50.78315, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroio porteira da chave arroio porteira da chave brazil br arroio porteira da chave',
    NOW(), NOW()), ('13001160', NULL, 'Arroio da Porteira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.83109, -50.74902, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroio da porteira arroio da porteira brazil br arroio da porteira',
    NOW(), NOW()), ('13002029', NULL, 'Porteiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.69735, -49.64409, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteiras porteiras brazil br paiol do meio,porteiras',
    NOW(), NOW()), ('13003351', NULL, 'Fazenda Porto Alegre', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.16881, -41.88829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto alegre fazenda porto alegre brazil br fazenda porto alegre',
    NOW(), NOW()), ('13003628', NULL, 'Recanto Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.25794, -47.48721, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'recanto portela recanto portela brazil br recanto portela',
    NOW(), NOW()), ('13003634', NULL, 'Estrada Porto Feliz-Boituva, Fazenda Jupira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.25258, -47.58649, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estrada porto feliz-boituva, fazenda jupira estrada porto feliz-boituva, fazenda jupira brazil br estrada porto feliz-boituva  fazenda jupira',
    NOW(), NOW()), ('13003640', NULL, 'Agrovila do Projeto de Assentamento Porto Feliz', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.33497, -47.53995, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'agrovila do projeto de assentamento porto feliz agrovila do projeto de assentamento porto feliz brazil br agrovila do pa porto feliz,agrovila do projeto de assentamento porto feliz',
    NOW(), NOW()), ('13003683', NULL, 'Porto de Areia Cometa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.628, -47.62, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de areia cometa porto de areia cometa brazil br porto de areia cometa',
    NOW(), NOW()), ('13004122', NULL, 'Córrego dos Portões', 'Corrego dos Portoes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.95038, -41.49534, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego dos portões corrego dos portoes brazil br corrego dos pontoes,corrego dos portoes,córrego dos pontões,córrego dos portões',
    NOW(), NOW()), ('13004648', NULL, 'Sítio Porto da Madeira', 'Sitio Porto da Madeira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.32845, -41.72781, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto da madeira sitio porto da madeira brazil br sitio porto da madeira,sítio porto da madeira',
    NOW(), NOW()), ('13005197', NULL, 'Porto da Madeira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.32995, -41.72224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da madeira porto da madeira brazil br porto da madeira',
    NOW(), NOW()), ('13005310', NULL, 'Parelheiros', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.78306, -46.67528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parelheiros parelheiros brazil br parelheiros,porto de areia paineiras',
    NOW(), NOW()), ('13005342', NULL, 'Porto de Areia Sete Praias', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.70672, -46.63711, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de areia sete praias porto de areia sete praias brazil br porto de areia sete praias',
    NOW(), NOW()), ('13005531', NULL, 'Bairro do Porto I, II, III', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.70231, -47.45267, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bairro do porto i, ii, iii bairro do porto i, ii, iii brazil br bairro do porto i  ii  iii',
    NOW(), NOW()), ('13006035', NULL, 'Sítio Bandarra', 'Sitio Bandarra',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.38006, -41.86527, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio bandarra sitio bandarra brazil br sitio bandarra,sítio bandarra',
    NOW(), NOW()), ('13006038', NULL, 'Bandarra', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.38385, -41.86039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandarra bandarra brazil br bandarra',
    NOW(), NOW()), ('13006354', NULL, 'Sítio Cascata Portela', 'Sitio Cascata Portela',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.63613, -41.94861, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio cascata portela sitio cascata portela brazil br sitio cascata portela,sítio cascata portela',
    NOW(), NOW()), ('13006801', NULL, 'Fazenda Porto dos Santos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.68892, -42.20024, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto dos santos fazenda porto dos santos brazil br fazenda porto dos santos',
    NOW(), NOW()), ('13006960', NULL, 'Porto das Barcas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.64989, -42.07263, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto das barcas porto das barcas brazil br porto das barcas',
    NOW(), NOW()), ('13007058', NULL, 'Duas Porteiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.65678, -42.03971, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'duas porteiras duas porteiras brazil br duas porteiras',
    NOW(), NOW()), ('13007288', NULL, 'Serra do Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.68755, -42.01318, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra do portela serra do portela brazil br serra do portela',
    NOW(), NOW()), ('13007385', NULL, 'Sítio Porto da Cruz', 'Sitio Porto da Cruz',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.7064, -42.2337, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto da cruz sitio porto da cruz brazil br sitio porto da cruz,sítio porto da cruz',
    NOW(), NOW()), ('13007470', NULL, 'Portozil', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.86106, -42.1942, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portozil portozil brazil br portozil',
    NOW(), NOW()), ('13007491', NULL, 'Porto dos Santos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.6931, -42.2052, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto dos santos porto dos santos brazil br porto dos santos',
    NOW(), NOW()), ('13007526', NULL, 'Córrego Portozil', 'Corrego Portozil',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.85183, -42.19996, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego portozil corrego portozil brazil br corrego portozil,córrego portozil',
    NOW(), NOW()), ('13007838', NULL, 'Porto da Cascata', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.84706, -46.6797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da cascata porto da cascata brazil br porto da cascata',
    NOW(), NOW()), ('13008930', NULL, 'Fazenda Santo Antônio do Porto d''Anta', 'Fazenda Santo Antonio do Porto d''Anta',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.5436, -41.2925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda santo antônio do porto d''anta fazenda santo antonio do porto d''anta brazil br fazenda santo antonio do porto d''anta,fazenda santo antônio do porto d''anta',
    NOW(), NOW()), ('13008986', NULL, 'Porto do Bonde', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.70894, -41.24469, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto do bonde porto do bonde brazil br porto do bonde',
    NOW(), NOW()), ('13009819', NULL, 'Sítio Portal do Paraíso', 'Sitio Portal do Paraiso',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.27693, -42.19743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portal do paraíso sitio portal do paraiso brazil br sitio portal do paraiso,sítio portal do paraíso',
    NOW(), NOW()), ('13009997', NULL, 'Sítio Esmarina', 'Sitio Esmarina',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.34803, -42.21816, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio esmarina sitio esmarina brazil br sitio esmarina,sítio esmarina',
    NOW(), NOW()), ('13010165', NULL, 'Porto Pinheiro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.09988, -41.78154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto pinheiro porto pinheiro brazil br porto pinheiro',
    NOW(), NOW()), ('13010490', NULL, 'Porto dos Sonhos', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.76173, -41.94177, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto dos sonhos porto dos sonhos brazil br porto dos sonhos',
    NOW(), NOW()), ('13010569', NULL, 'Canal da Marina Porto Búzios', 'Canal da Marina Porto Buzios',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.74463, -41.95159, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal da marina porto búzios canal da marina porto buzios brazil br canal da marina porto buzios,canal da marina porto búzios',
    NOW(), NOW()), ('13011000', NULL, 'Fazenda Porta do Céu', 'Fazenda Porta do Ceu',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6542, -42.3772, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porta do céu fazenda porta do ceu brazil br fazenda porta do ceu,fazenda porta do céu',
    NOW(), NOW()), ('13011001', NULL, 'Fazenda Portolândia', 'Fazenda Portolandia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7028, -42.3706, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda portolândia fazenda portolandia brazil br fazenda portolandia,fazenda portolândia',
    NOW(), NOW()), ('13011258', NULL, 'Sítio do Portugues', 'Sitio do Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6568, -42.4733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio do portugues sitio do portugues brazil br sitio do portugues,sítio do portugues',
    NOW(), NOW()), ('13011456', NULL, 'Sítio Portal do Paraíso', 'Sitio Portal do Paraiso',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.33778, -42.49012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portal do paraíso sitio portal do paraiso brazil br sitio portal do paraiso,sítio portal do paraíso',
    NOW(), NOW()), ('13011457', NULL, 'Sítio Portal do Rio Seco', 'Sitio Portal do Rio Seco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8635, -42.4964, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portal do rio seco sitio portal do rio seco brazil br sitio portal do rio seco,sítio portal do rio seco',
    NOW(), NOW()), ('13011683', NULL, 'Salina Santa Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9173, -42.3425, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salina santa marina salina santa marina brazil br salina santa marina',
    NOW(), NOW()), ('13011884', NULL, 'Fazenda Limange', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63736, -42.51733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda limange fazenda limange brazil br fazenda limange',
    NOW(), NOW()), ('13011903', NULL, 'Fazenda Portal das Palmeiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.67748, -42.5661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda portal das palmeiras fazenda portal das palmeiras brazil br fazenda portal das palmeiras',
    NOW(), NOW()), ('13012285', NULL, 'Sítio Portimão', 'Sitio Portimao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63781, -42.70732, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portimão sitio portimao brazil br sitio portimao,sítio portimão',
    NOW(), NOW()), ('13012286', NULL, 'Sítio Porto Taboado', 'Sitio Porto Taboado',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.52375, -42.69194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto taboado sitio porto taboado brazil br sitio porto taboado,sítio porto taboado',
    NOW(), NOW()), ('13012571', NULL, 'Rio Porto das Caixas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.69307, -42.93492, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rio porto das caixas rio porto das caixas brazil br rio porto das caixas',
    NOW(), NOW()), ('13012633', NULL, 'Sítio Portal do Eder', 'Sitio Portal do Eder',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6626, -42.7777, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portal do eder sitio portal do eder brazil br sitio portal do eder,sítio portal do eder',
    NOW(), NOW()), ('13012634', NULL, 'Sítio Porto Barão', 'Sitio Porto Barao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8015, -42.9208, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto barão sitio porto barao brazil br sitio porto barao,sítio porto barão',
    NOW(), NOW()), ('13012635', NULL, 'Sítio Porto Seguro', 'Sitio Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6525, -42.9874, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto seguro sitio porto seguro brazil br sitio porto seguro,sítio porto seguro',
    NOW(), NOW()), ('13012930', NULL, 'Porto de Caixas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.69686, -42.88571, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de caixas porto de caixas brazil br porto de caixas',
    NOW(), NOW()), ('13013137', NULL, 'Terminal Internacional de Cruzeiros do Pier Mauá', 'Terminal Internacional de Cruzeiros do Pier Maua',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.89411, -43.18537, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal internacional de cruzeiros do pier mauá terminal internacional de cruzeiros do pier maua brazil br terminal internacional de cruzeiros do pier maua,terminal internacional de cruzeiros do pier mauá',
    NOW(), NOW());