INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8153240', NULL, 'Campbelltown Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0499, 150.834, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campbelltown sportsground campbelltown sportsground australia au campbelltown sportsground',
    NOW(), NOW()), ('8153260', NULL, 'David Wood Sporting Fields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.4896, 150.44679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'david wood sporting fields david wood sporting fields australia au david wood sporting fields',
    NOW(), NOW()), ('8153294', NULL, 'Cookbundoon Sports Fields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.7166, 149.7471, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cookbundoon sports fields cookbundoon sports fields australia au cookbundoon sports fields',
    NOW(), NOW()), ('8153416', NULL, 'Cootamundra Sports Stadium', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.6346, 148.0248, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cootamundra sports stadium cootamundra sports stadium australia au cootamundra sports stadium',
    NOW(), NOW()), ('8153675', NULL, 'Franklin Harbour Pioneers Memorial Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.67946, 136.92445, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'franklin harbour pioneers memorial oval franklin harbour pioneers memorial oval australia au franklin harbour pioneers memorial oval',
    NOW(), NOW()), ('8153724', NULL, 'Community Sports Show and Recreation Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.34252, 138.06262, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'community sports show and recreation ground community sports show and recreation ground australia au community sports show and recreation ground',
    NOW(), NOW()), ('8153730', NULL, 'Davenport Olive Plantation', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.95006, 138.65234, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport olive plantation davenport olive plantation australia au davenport olive plantation',
    NOW(), NOW()), ('8153733', NULL, 'Franklin Harbor Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.74428, 136.93806, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'franklin harbor conservation park franklin harbor conservation park australia au franklin harbor conservation park',
    NOW(), NOW()), ('8153735', NULL, 'Franklin Harbor Marine Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.66922, 137.22276, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'franklin harbor marine park franklin harbor marine park australia au franklin harbor marine park',
    NOW(), NOW()), ('8153840', NULL, 'Davenport Square', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.17088, 138.83597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport square davenport square australia au davenport square',
    NOW(), NOW()), ('8153924', NULL, 'Cape Portland Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.75, 147.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cape portland conservation area cape portland conservation area australia au cape portland conservation area',
    NOW(), NOW()), ('8153951', NULL, 'Clare Street Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.86, 147.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clare street sports ground clare street sports ground australia au clare street sports ground',
    NOW(), NOW()), ('8153968', NULL, 'Cornelian Bay Sports Grounds', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.85, 147.31, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cornelian bay sports grounds cornelian bay sports grounds australia au cornelian bay sports grounds',
    NOW(), NOW()), ('8153977', NULL, 'Crossroads Sports Grounds', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.86, 147.32001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'crossroads sports grounds crossroads sports grounds australia au crossroads sports grounds',
    NOW(), NOW()), ('8154007', NULL, 'Devonport Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.16, 146.35001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'devonport oval devonport oval australia au devonport oval',
    NOW(), NOW()), ('8154008', NULL, 'Devonport Showground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.17, 146.35001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'devonport showground devonport showground australia au devonport showground',
    NOW(), NOW()), ('8154133', NULL, 'Fergusons Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.63597, 145.19431, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fergusons paddock fergusons paddock australia au fergusons paddock',
    NOW(), NOW()), ('8154303', NULL, 'Dampier Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.57222, 115.6783, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier reserve dampier reserve australia au dampier reserve',
    NOW(), NOW()), ('8154333', NULL, 'Dick Piercy Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.06, 115.8158, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dick piercy park dick piercy park australia au dick piercy park',
    NOW(), NOW()), ('8154547', NULL, 'Gipps Street Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.2602, 150.9279, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gipps street sportsground gipps street sportsground australia au gipps street sportsground',
    NOW(), NOW()), ('8154666', NULL, 'Greystanes Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 150.9346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'greystanes sportsground greystanes sportsground australia au greystanes sportsground',
    NOW(), NOW()), ('8154708', NULL, 'Harbord Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.77135, 151.28234, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbord park harbord park australia au harbord park',
    NOW(), NOW()), ('8154769', NULL, 'Hillsborough Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.9485, 151.66789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hillsborough sports centre hillsborough sports centre australia au hillsborough sports centre',
    NOW(), NOW()), ('8154810', NULL, 'Howard Fowles Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5402, 150.86791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'howard fowles sports oval howard fowles sports oval australia au howard fowles sports oval',
    NOW(), NOW()), ('8154852', NULL, 'Iluka Nature Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.4027, 153.3609, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka nature reserve iluka nature reserve australia au iluka nature reserve',
    NOW(), NOW()), ('8154853', NULL, 'Iluka Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.5985, 151.3179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka park iluka park australia au iluka park',
    NOW(), NOW()), ('8154934', NULL, 'Kahibah Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.9652, 151.7179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kahibah sportsground kahibah sportsground australia au kahibah sportsground',
    NOW(), NOW()), ('8154941', NULL, 'Kandos Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.8485, 149.9679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kandos sportsground kandos sportsground australia au kandos sportsground',
    NOW(), NOW()), ('8154980', NULL, 'Hall Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 151.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hall sportsground hall sportsground australia au hall sportsground',
    NOW(), NOW()), ('8155001', NULL, 'Howlong Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.9827, 146.63373, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'howlong sportsground howlong sportsground australia au howlong sportsground',
    NOW(), NOW()), ('8155086', NULL, 'Kitchener Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.9818, 150.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kitchener sportsground kitchener sportsground australia au kitchener sportsground',
    NOW(), NOW()), ('8155087', NULL, 'Kitchener Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.9818, 150.2679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kitchener sports ground kitchener sports ground australia au kitchener sports ground',
    NOW(), NOW()), ('8155154', NULL, 'Gulargambone Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.3318, 148.4346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gulargambone sportsground gulargambone sportsground australia au gulargambone sportsground',
    NOW(), NOW()), ('8155180', NULL, 'Iluka Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7818, 152.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka reserve iluka reserve australia au iluka reserve',
    NOW(), NOW()), ('8155190', NULL, 'Jock Brown Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jock brown sportsfield jock brown sportsfield australia au jock brown sportsfield',
    NOW(), NOW()), ('8155200', NULL, 'Jubilee Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5818, 149.55119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jubilee sportsground jubilee sportsground australia au jubilee sportsground',
    NOW(), NOW()), ('8155312', NULL, 'Harry Moore Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.2693, 151.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'harry moore sportsground harry moore sportsground australia au harry moore sportsground',
    NOW(), NOW()), ('8155382', NULL, 'Halls Creek Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7235, 151.5318, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'halls creek sports area halls creek sports area australia au halls creek sports area',
    NOW(), NOW()), ('8155478', NULL, 'Kariong Sport and Recreation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4321, 151.29289, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kariong sport and recreation area kariong sport and recreation area australia au kariong sport and recreation area',
    NOW(), NOW()), ('8155577', NULL, 'Jim Rutherford Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.8124, 149.2915, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jim rutherford sportsground jim rutherford sportsground australia au jim rutherford sportsground',
    NOW(), NOW()), ('8155640', NULL, 'Joshua Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1735, 151.5623, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'joshua porter reserve joshua porter reserve australia au joshua porter reserve',
    NOW(), NOW()), ('8155861', NULL, 'Hope Valley Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8473, 138.70001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hope valley sports area hope valley sports area australia au hope valley sports area',
    NOW(), NOW()), ('8155911', NULL, 'Goose Island Conservation Park, Port Victoria', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.45342, 137.37176, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'goose island conservation park, port victoria goose island conservation park, port victoria australia au goose island conservation park',
    NOW(), NOW()), ('8155943', NULL, 'Paringa Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.18283, 140.76326, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paringa paddock paringa paddock australia au koala sanctuary',
    NOW(), NOW()), ('8155953', NULL, 'Golden Grove Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.78692, 138.70067, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'golden grove sports area golden grove sports area australia au golden grove sports area',
    NOW(), NOW()), ('8156012', NULL, 'Jubilee Sports Arena', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.91652, 138.63032, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jubilee sports arena jubilee sports arena australia au jubilee sports arena',
    NOW(), NOW()), ('8156020', NULL, 'Harbour View Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.71984, 135.8409, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour view reserve harbour view reserve australia au harbour view reserve',
    NOW(), NOW()), ('8156037', NULL, 'Greenwith Sports Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.77225, 138.71876, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'greenwith sports park greenwith sports park australia au greenwith sports park',
    NOW(), NOW()), ('8156150', NULL, 'Hewett Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.0306, 138.62012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hewett sports ground hewett sports ground australia au hewett sports ground',
    NOW(), NOW()), ('8156184', NULL, 'International Sports Shooting Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66603, 138.54289, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'international sports shooting park international sports shooting park australia au international sports shooting park',
    NOW(), NOW());