INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('5896815', NULL, 'Beaver Harbour Big Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.94054, -62.45186, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour big lake beaver harbour big lake canada ca',
    NOW(), NOW()), ('5896870', NULL, 'Beaver Island Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.91677, -81.8498, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver island harbour beaver island harbour canada ca',
    NOW(), NOW()), ('5897121', NULL, 'Beaver Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.45022, -83.38312, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beaver portage beaver portage canada ca',
    NOW(), NOW()), ('5897185', NULL, 'Beaverton Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.43342, -79.1663, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaverton harbour beaverton harbour canada ca',
    NOW(), NOW()), ('5897341', NULL, 'Bedford Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.03337, -82.01651, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bedford harbour bedford harbour canada ca',
    NOW(), NOW()), ('5897342', NULL, 'Bedford Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    63.40056, -71.96495, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bedford harbour bedford harbour canada ca',
    NOW(), NOW()), ('5897382', NULL, 'Bedwell Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.75342, -123.24871, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bedwell harbour bedwell harbour canada ca',
    NOW(), NOW()), ('5897383', NULL, 'Bedwell Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.74835, -123.2372, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bedwell harbour bedwell harbour canada ca',
    NOW(), NOW()), ('5897823', NULL, 'Belle Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.68323, -55.31499, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'belle harbour belle harbour canada ca',
    NOW(), NOW()), ('5897857', NULL, 'Belleoram Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.51664, -55.41501, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'belleoram harbour belleoram harbour canada ca',
    NOW(), NOW()), ('5897886', NULL, 'Belleville Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.15012, -77.38277, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'belleville harbour belleville harbour canada ca',
    NOW(), NOW()), ('5897918', NULL, 'Bell Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    57.95043, -77.11612, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bell harbour bell harbour canada ca',
    NOW(), NOW()), ('5898077', NULL, 'Bells Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.23329, -94.55045, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bells harbour bells harbour canada ca',
    NOW(), NOW()), ('5898202', NULL, 'Belvédère Pierre-Drapeau', 'Belvedere Pierre-Drapeau',
    NULL, 'CA', 'Canada', NULL, NULL,
    49.22229, -65.90127, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belvédère pierre-drapeau belvedere pierre-drapeau canada ca',
    NOW(), NOW()), ('5898274', NULL, 'Bendickson Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.4146, -125.92268, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bendickson harbour bendickson harbour canada ca',
    NOW(), NOW()), ('5898577', NULL, 'Bent Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.5146, -129.05279, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bent harbour bent harbour canada ca',
    NOW(), NOW()), ('5898818', NULL, 'Bernard Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    68.7675, -114.70335, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bernard harbour bernard harbour canada ca',
    NOW(), NOW()), ('5899014', NULL, 'Berthie Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    65.31752, -87.33278, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'berthie harbour berthie harbour canada ca',
    NOW(), NOW()), ('5899135', NULL, 'Best''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.5832, -54.21485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'best''s harbour best''s harbour canada ca',
    NOW(), NOW()), ('5899136', NULL, 'Best''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.5832, -54.21485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'best''s harbour best''s harbour canada ca',
    NOW(), NOW()), ('5899379', NULL, 'Bibliothèque Lise-Bourque-St-Pierre', 'Bibliotheque Lise-Bourque-St-Pierre',
    NULL, 'CA', 'Canada', NULL, NULL,
    45.73337, -72.86583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bibliothèque lise-bourque-st-pierre bibliotheque lise-bourque-st-pierre canada ca',
    NOW(), NOW()), ('5899860', NULL, 'Big Dock Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.5166, -54.28146, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big dock island big dock island canada ca',
    NOW(), NOW()), ('5899862', NULL, 'Big Dog Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.5666, -54.14814, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big dog harbour big dog harbour canada ca',
    NOW(), NOW()), ('5900083', NULL, 'Big Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.71665, -56.08164, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour big harbour canada ca',
    NOW(), NOW()), ('5900084', NULL, 'Big Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.13344, -60.61518, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour big harbour canada ca',
    NOW(), NOW()), ('5900085', NULL, 'Big Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.14854, -60.60018, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour big harbour canada ca',
    NOW(), NOW()), ('5900086', NULL, 'Big Harbour Brook', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.15014, -60.63178, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour brook big harbour brook canada ca',
    NOW(), NOW()), ('5900087', NULL, 'Big Harbour Centre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.86684, -60.98181, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour centre big harbour centre canada ca',
    NOW(), NOW()), ('5900088', NULL, 'Big Harbour Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.86684, -60.9485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour island big harbour island canada ca',
    NOW(), NOW()), ('5900089', NULL, 'Big Harbour Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.86684, -60.9485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour island big harbour island canada ca',
    NOW(), NOW()), ('5900090', NULL, 'Big Harbour Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.86685, -62.3319, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour island big harbour island canada ca',
    NOW(), NOW()), ('5900093', NULL, 'Big Hardwood Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.33346, -65.26551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big hardwood portage big hardwood portage canada ca',
    NOW(), NOW()), ('5900395', NULL, 'Big Knife Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.06648, -91.31692, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big knife portage big knife portage canada ca',
    NOW(), NOW()), ('5900471', NULL, 'Big Lorraine Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.93344, -59.91513, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big lorraine harbour big lorraine harbour canada ca',
    NOW(), NOW()), ('5900502', NULL, 'Big McCaulay Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.69983, -92.03352, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big mccaulay portage big mccaulay portage canada ca',
    NOW(), NOW()), ('5900608', NULL, 'Big Pierre Jacques River', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.61685, -64.31544, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big pierre jacques river big pierre jacques river canada ca',
    NOW(), NOW()), ('5900751', NULL, 'Big River Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.01481, -84.3562, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big river portage big river portage canada ca',
    NOW(), NOW()), ('5900777', NULL, 'Big Rock Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.95007, -81.26646, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big rock portage big rock portage canada ca',
    NOW(), NOW()), ('5901001', NULL, 'Big Tub Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.26677, -81.68307, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big tub harbour big tub harbour canada ca',
    NOW(), NOW()), ('5901163', NULL, 'Bill of Portland Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    55.3753, -77.7162, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bill of portland island bill of portland island canada ca',
    NOW(), NOW()), ('5901645', NULL, 'Birch Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.41677, -92.13361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birch portage birch portage canada ca',
    NOW(), NOW()), ('5901646', NULL, 'Birch Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    55.58344, -105.40094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birch portage birch portage canada ca',
    NOW(), NOW()), ('5901647', NULL, 'Birch Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    63.31715, -114.18587, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birch portage birch portage canada ca',
    NOW(), NOW()), ('5901648', NULL, 'Birch Portage 184A', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    54.88485, -102.58973, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birch portage 184a birch portage 184a canada ca',
    NOW(), NOW()), ('5901923', NULL, 'Biscuit Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.59361, -96.82064, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'biscuit harbour biscuit harbour canada ca',
    NOW(), NOW()), ('5901993', NULL, 'Bishop''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.6832, -53.63139, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bishop''s harbour bishop''s harbour canada ca',
    NOW(), NOW()), ('5901994', NULL, 'Bishops Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.6832, -53.64809, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bishops harbour bishops harbour canada ca',
    NOW(), NOW()), ('5901995', NULL, 'Bishops Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.20006, -83.21658, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bishops harbour bishops harbour canada ca',
    NOW(), NOW()), ('5902193', NULL, 'Black Bear Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.77191, -96.91254, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'black bear harbour black bear harbour canada ca',
    NOW(), NOW()), ('5902202', NULL, 'Black Bear Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.11671, -94.70046, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'black bear portage black bear portage canada ca',
    NOW(), NOW());