INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3849320', NULL, 'Salinas La Porteña', 'Salinas La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.25, -63.78333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salinas la porteña salinas la portena argentina ar',
    NOW(), NOW()), ('3849321', NULL, 'Puesto La Porteña', 'Puesto La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.84628, -69.06931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto la porteña puesto la portena argentina ar',
    NOW(), NOW()), ('3849322', NULL, 'Laguna La Porteña', 'Laguna La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -47.34476, -65.73299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna la porteña laguna la portena argentina ar',
    NOW(), NOW()), ('3849323', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.58487, -68.88217, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849324', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -48.14347, -67.08453, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849325', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -48.07663, -71.85982, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849326', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.54039, -69.58867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849327', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.34477, -71.11238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849328', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -45.75032, -69.17752, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849329', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -44.68767, -67.97651, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849330', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.37584, -70.94849, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849331', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.57216, -70.33189, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849332', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.21193, -63.72491, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849333', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.66679, -60.75512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849334', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.62285, -60.93956, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849335', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.43333, -66.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849336', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.79648, -63.62448, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849337', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.19935, -61.78227, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849338', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.93552, -64.19195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3849339', NULL, 'Colonia La Porteña', 'Colonia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.58003, -60.95723, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colonia la porteña colonia la portena argentina ar',
    NOW(), NOW()), ('3849340', NULL, 'Cerro La Porteña', 'Cerro La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.86448, -69.03041, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro la porteña cerro la portena argentina ar',
    NOW(), NOW()), ('3849341', NULL, 'Arroyo La Porteña', 'Arroyo La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -50.57896, -71.52053, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo la porteña arroyo la portena argentina ar',
    NOW(), NOW()), ('3849342', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.26667, -63.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849343', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.36478, -62.71948, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar la portena,la porteña',
    NOW(), NOW()), ('3849344', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.70423, -64.80388, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849345', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.95, -64.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849346', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.4467, -65.19517, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849347', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.58333, -60.98333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849348', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.51667, -70.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849349', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.48333, -65.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar',
    NOW(), NOW()), ('3849350', NULL, 'Puesto La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.16667, -64.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto la portada puesto la portada argentina ar',
    NOW(), NOW()), ('3849351', NULL, 'Estancia La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.75311, -65.26729, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la portada estancia la portada argentina ar',
    NOW(), NOW()), ('3849352', NULL, 'Estancia La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.6, -63.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la portada estancia la portada argentina ar',
    NOW(), NOW()), ('3849353', NULL, 'La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.48333, -68.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la portada la portada argentina ar',
    NOW(), NOW()), ('3849354', NULL, 'La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.42462, -65.483, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la portada la portada argentina ar la portada',
    NOW(), NOW()), ('3849355', NULL, 'La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.9, -66.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la portada la portada argentina ar',
    NOW(), NOW()), ('3849425', NULL, 'Estancia La Pierina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.30035, -69.82982, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la pierina estancia la pierina argentina ar',
    NOW(), NOW()), ('3849575', NULL, 'Portillo de La Pampa', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.28333, -69.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la pampa portillo de la pampa argentina ar',
    NOW(), NOW()), ('3849689', NULL, 'Almacén La Nueva Porteña', 'Almacen La Nueva Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.47455, -60.06784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'almacén la nueva porteña almacen la nueva portena argentina ar',
    NOW(), NOW()), ('3850016', NULL, 'Estancia La Marina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.3, -68.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la marina estancia la marina argentina ar',
    NOW(), NOW()), ('3850017', NULL, 'Estancia La Marina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -50.19486, -69.83315, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la marina estancia la marina argentina ar',
    NOW(), NOW()), ('3850018', NULL, 'Estancia La Marina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.35469, -60.11487, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la marina estancia la marina argentina ar',
    NOW(), NOW()), ('3850019', NULL, 'La Marina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.31667, -68.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la marina la marina argentina ar estancia la marina,la marina',
    NOW(), NOW()), ('3850473', NULL, 'Portillo de La Laguna', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.26947, -69.96945, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la laguna portillo de la laguna argentina ar',
    NOW(), NOW()), ('3850912', NULL, 'Portezuelo de Lagunas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.05, -70.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de lagunas portezuelo de lagunas argentina ar portezuelo de lagunas',
    NOW(), NOW()), ('3850943', NULL, 'Portezuelo los Cristales', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.2, -70.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo los cristales portezuelo los cristales argentina ar paso cristales,paso laguna fea,portezuelo los cristales',
    NOW(), NOW()), ('3850979', NULL, 'Portezuelo Laguna Campana', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.6, -71.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo laguna campana portezuelo laguna campana argentina ar portezuelo laguna campana',
    NOW(), NOW()), ('3850999', NULL, 'Portillo de la Laguna', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.26667, -69.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la laguna portillo de la laguna argentina ar',
    NOW(), NOW()), ('3851060', NULL, 'Portillo de la Lágrima Viva', 'Portillo de la Lagrima Viva',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.59456, -69.61545, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la lágrima viva portillo de la lagrima viva argentina ar',
    NOW(), NOW()), ('3851061', NULL, 'Portezuelo de las Lágrimas', 'Portezuelo de las Lagrimas',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.68333, -70.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de las lágrimas portezuelo de las lagrimas argentina ar portezuelo de las lagrima,portezuelo de las lagrimas,portezuelo de las lágrima,portezuelo de las lágrimas',
    NOW(), NOW());