INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('5915826', NULL, 'Cape George Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.73344, -60.8152, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cape george harbour cape george harbour canada ca',
    NOW(), NOW()), ('5915851', NULL, 'Cape Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.78341, -87.03325, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cape harbour cape harbour canada ca',
    NOW(), NOW()), ('5916154', NULL, 'Cape Porter', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    69.1678, -94.30045, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cape porter cape porter canada ca',
    NOW(), NOW()), ('5916199', NULL, 'Cape Roger Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.38322, -54.73155, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cape roger harbour cape roger harbour canada ca',
    NOW(), NOW()), ('5916209', NULL, 'Cape Rouge Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.91678, -55.86477, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cape rouge harbour cape rouge harbour canada ca',
    NOW(), NOW()), ('5916819', NULL, 'Card''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.51664, -55.63149, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'card''s harbour card''s harbour canada ca',
    NOW(), NOW()), ('5916858', NULL, 'Carey Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    76.56839, -98.25212, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'carey harbour carey harbour canada ca',
    NOW(), NOW()), ('5916977', NULL, 'Caribou Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.73344, -62.69864, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'caribou harbour caribou harbour canada ca',
    NOW(), NOW()), ('5916978', NULL, 'Caribou Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.66681, -88.85006, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'caribou harbour caribou harbour canada ca',
    NOW(), NOW()), ('5917430', NULL, 'Caronport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.45006, -105.81787, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caronport caronport canada ca',
    NOW(), NOW()), ('5917867', NULL, 'Cascade Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.90918, -127.73791, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cascade harbour cascade harbour canada ca',
    NOW(), NOW()), ('5917881', NULL, 'Cascade Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.05112, -96.20808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cascade portage cascade portage canada ca',
    NOW(), NOW()), ('5917882', NULL, 'Cascade Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    56.70463, -110.27998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cascade portage cascade portage canada ca',
    NOW(), NOW()), ('5918215', NULL, 'Castors Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.91677, -56.98144, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'castors harbour castors harbour canada ca',
    NOW(), NOW()), ('5918244', NULL, 'Catalina Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.51659, -53.06475, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'catalina harbour catalina harbour canada ca',
    NOW(), NOW()), ('5918439', NULL, 'Cat Lake Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.19398, -81.28586, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cat lake portage cat lake portage canada ca',
    NOW(), NOW()), ('5918446', NULL, 'Cator Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    76.73499, -99.56915, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cator harbour cator harbour canada ca',
    NOW(), NOW()), ('5918452', NULL, 'Cat Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.96678, -84.49983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cat portage cat portage canada ca',
    NOW(), NOW()), ('5918563', NULL, 'Cave Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.4334, -86.21661, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cave harbour cave harbour canada ca',
    NOW(), NOW()), ('5918820', NULL, 'Cedar Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.31669, -79.53267, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cedar harbour cedar harbour canada ca',
    NOW(), NOW()), ('5918899', NULL, 'Cedar Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.56653, -91.6669, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cedar portage cedar portage canada ca',
    NOW(), NOW()), ('5919065', NULL, 'Centrale de Port-Menier', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.81957, -64.34896, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'centrale de port-menier centrale de port-menier canada ca',
    NOW(), NOW()), ('5919125', NULL, 'Central Lot 16 Wharf', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.50014, -63.88203, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'central lot 16 wharf central lot 16 wharf canada ca',
    NOW(), NOW()), ('5919135', NULL, 'Central Port Mouton', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.91685, -64.84626, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'central port mouton central port mouton canada ca',
    NOW(), NOW()), ('5919140', NULL, 'Central Woods Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.54141, -65.73345, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'central woods harbour central woods harbour canada ca',
    NOW(), NOW()), ('5919226', NULL, 'Centre municipal de Pierrefonds', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.50478, -73.85199, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'centre municipal de pierrefonds centre municipal de pierrefonds canada ca',
    NOW(), NOW()), ('5919244', NULL, 'Centre sportif de la Petite-Bourgogne', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.48832, -73.56911, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'centre sportif de la petite-bourgogne centre sportif de la petite-bourgogne canada ca',
    NOW(), NOW()), ('5919245', NULL, 'Centre sportif J.-A.-Lemay', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.57338, -71.99269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'centre sportif j.-a.-lemay centre sportif j.-a.-lemay canada ca',
    NOW(), NOW()), ('5919429', NULL, 'Chain of Lakes Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.9793, -84.29539, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chain of lakes portage chain of lakes portage canada ca',
    NOW(), NOW()), ('5919465', NULL, 'Chaleur Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.58326, -56.66509, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chaleur harbour chaleur harbour canada ca',
    NOW(), NOW()), ('5919575', NULL, 'Chamcook Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.11433, -67.0542, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chamcook harbour chamcook harbour canada ca',
    NOW(), NOW()), ('5919588', NULL, 'Chamney Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    54.60012, -102.16749, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chamney island chamney island canada ca',
    NOW(), NOW()), ('5919693', NULL, 'Champneuf', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.58349, -77.49948, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'champneuf champneuf canada ca champneuf,shamnwf  kbk,shwnwf,чампнеуф,شامنوف، کبک,شونوف',
    NOW(), NOW()), ('5919721', NULL, 'Chance Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.67127, -62.60595, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour chance harbour canada ca',
    NOW(), NOW()), ('5919722', NULL, 'Chance Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.66684, -62.56533, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour chance harbour canada ca',
    NOW(), NOW()), ('5919723', NULL, 'Chance Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.12968, -66.34511, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour chance harbour canada ca',
    NOW(), NOW()), ('5919724', NULL, 'Chance Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.12821, -66.35277, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour chance harbour canada ca',
    NOW(), NOW()), ('5919725', NULL, 'Chance Harbour Beach', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.68344, -62.58193, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour beach chance harbour beach canada ca',
    NOW(), NOW()), ('5919726', NULL, 'Chance Harbour Island', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.79815, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour island chance harbour island canada ca',
    NOW(), NOW()), ('5919727', NULL, 'Chance Harbour Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.66981, -62.61032, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour lake chance harbour lake canada ca',
    NOW(), NOW()), ('5919728', NULL, 'Chance Harbour Ledge', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.5499, -53.61478, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chance harbour ledge chance harbour ledge canada ca',
    NOW(), NOW()), ('5919742', NULL, 'Chanceport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.81485, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chanceport chanceport canada ca',
    NOW(), NOW()), ('5919743', NULL, 'Chanceport Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.54992, -54.81485, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chanceport harbour chanceport harbour canada ca',
    NOW(), NOW()), ('5919815', NULL, 'Channel-Port aux Basques', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.57286, -59.13808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'channel-port aux basques channel-port aux basques canada ca channel-port-aux-basques,port aux basques',
    NOW(), NOW()), ('5919824', NULL, 'Channels Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.4832, -54.4982, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'channels harbour channels harbour canada ca',
    NOW(), NOW()), ('5920237', NULL, 'Charlie''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.63341, -88.60004, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'charlie''s harbour charlie''s harbour canada ca',
    NOW(), NOW()), ('5920269', NULL, 'Charlotte Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.45009, -55.76468, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'charlotte harbour charlotte harbour canada ca',
    NOW(), NOW()), ('5920290', NULL, 'Charlottetown Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.21758, -63.14073, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'charlottetown harbour charlottetown harbour canada ca',
    NOW(), NOW()), ('5920300', NULL, 'Charlton Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.95019, -79.33275, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'charlton harbour charlton harbour canada ca',
    NOW(), NOW()), ('5920544', NULL, 'Chebogue Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.73203, -66.1019, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'chebogue harbour chebogue harbour canada ca',
    NOW(), NOW());