INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8150263', NULL, 'Berkeley Vale Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3318, 151.41789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'berkeley vale sportsground berkeley vale sportsground australia au berkeley vale sportsground',
    NOW(), NOW()), ('8150300', NULL, 'Bigga Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0818, 149.1512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bigga sports oval bigga sports oval australia au bigga sports oval',
    NOW(), NOW()), ('8150407', NULL, 'Bremners Paddock Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8152, 151.1012, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bremners paddock reserve bremners paddock reserve australia au bremners paddock reserve',
    NOW(), NOW()), ('8150430', NULL, 'Broken Hill Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.9485, 141.4429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'broken hill sportsground broken hill sportsground australia au broken hill sportsground',
    NOW(), NOW()), ('8150493', NULL, 'Boatharbour Nature Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.7652, 153.3179, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boatharbour nature reserve boatharbour nature reserve australia au boatharbour nature reserve',
    NOW(), NOW()), ('8150651', NULL, 'Blackwood Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.0306, 138.62012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blackwood sports ground blackwood sports ground australia au blackwood sports ground',
    NOW(), NOW()), ('8150725', NULL, 'Abington Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2818, 151.1846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'abington sportsground abington sportsground australia au abington sportsground',
    NOW(), NOW()), ('8150749', NULL, 'Barrack Heights Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5652, 150.8512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barrack heights sportsground barrack heights sportsground australia au barrack heights sportsground',
    NOW(), NOW()), ('8150774', NULL, 'Bob Graham Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.78461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bob graham sportsfield bob graham sportsfield australia au bob graham sportsfield',
    NOW(), NOW()), ('8150778', NULL, 'Breaden Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.2652, 147.7346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'breaden sports ground breaden sports ground australia au breaden sports ground',
    NOW(), NOW()), ('8150788', NULL, 'Ambarvale Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0652, 150.78461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ambarvale sports complex ambarvale sports complex australia au ambarvale sports complex',
    NOW(), NOW()), ('8150829', NULL, 'Bruce Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.6485, 152.7998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bruce porter reserve bruce porter reserve australia au bruce porter reserve',
    NOW(), NOW()), ('8150893', NULL, 'Bernie Regan Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8416, 150.57761, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bernie regan sporting complex bernie regan sporting complex australia au bernie regan sporting complex',
    NOW(), NOW()), ('8150938', NULL, 'Bernie Mullane Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7038, 150.9704, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bernie mullane sports complex bernie mullane sports complex australia au bernie mullane sports complex',
    NOW(), NOW()), ('8151034', NULL, 'Ash Road Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9518, 150.8748, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ash road sports ground ash road sports ground australia au ash road sports ground',
    NOW(), NOW()), ('8151119', NULL, 'Banksia Park Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.81042, 138.72829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'banksia park sports area banksia park sports area australia au banksia park sports area',
    NOW(), NOW()), ('8151129', NULL, 'Blanche Harbor-Douglas Bank Aquatic Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.71752, 137.79334, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'blanche harbor-douglas bank aquatic reserve blanche harbor-douglas bank aquatic reserve australia au blanche harbor-douglas bank aquatic reserve',
    NOW(), NOW()), ('8151184', NULL, 'Adelaide CAE Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.91021, 138.60908, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'adelaide cae sportsground adelaide cae sportsground australia au adelaide cae sportsground',
    NOW(), NOW()), ('8151190', NULL, 'Buttery Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.91918, 138.64002, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buttery sportsground buttery sportsground australia au buttery sportsground',
    NOW(), NOW()), ('8151240', NULL, 'Braddock Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.49161, 137.76949, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braddock park braddock park australia au braddock park',
    NOW(), NOW()), ('8151246', NULL, 'Banksia Park Sport Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8105, 138.72754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'banksia park sport area banksia park sport area australia au banksia park sport area',
    NOW(), NOW()), ('8151281', NULL, 'Beachport Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.45646, 139.97906, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beachport conservation park beachport conservation park australia au beachport conservation park',
    NOW(), NOW()), ('8151380', NULL, 'Baldocks Grant Private Sanctuary', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.59, 146.35001, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baldocks grant private sanctuary baldocks grant private sanctuary australia au baldocks grant private sanctuary',
    NOW(), NOW()), ('8151427', NULL, 'Boyer Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.77, 147.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'boyer sports ground boyer sports ground australia au boyer sports ground',
    NOW(), NOW()), ('8151438', NULL, 'Bridport Wildflower Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.98, 147.38001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bridport wildflower reserve bridport wildflower reserve australia au bridport wildflower reserve',
    NOW(), NOW()), ('8151845', NULL, 'Cabramatta Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9068, 150.9346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cabramatta sportsground cabramatta sportsground australia au cabramatta sportsground',
    NOW(), NOW()), ('8151866', NULL, 'Donoghoe Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3652, 149.2346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donoghoe sportsground donoghoe sportsground australia au donoghoe sportsground',
    NOW(), NOW()), ('8152183', NULL, 'Clare Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.59546, 143.87863, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clare sportsground clare sportsground australia au clare sportsground',
    NOW(), NOW()), ('8152206', NULL, 'Coffs Harbour Jaycee Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2985, 153.11791, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour jaycee park coffs harbour jaycee park australia au coffs harbour jaycee park',
    NOW(), NOW()), ('8152207', NULL, 'Coffs Harbour Racecourse', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2985, 153.11791, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour racecourse coffs harbour racecourse australia au coffs harbour racecourse',
    NOW(), NOW()), ('8152208', NULL, 'Coffs Harbour Showground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2818, 153.11791, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour showground coffs harbour showground australia au coffs harbour showground',
    NOW(), NOW()), ('8152263', NULL, 'Culcairn Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.66924, 147.0467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'culcairn sportsground culcairn sportsground australia au culcairn sportsground',
    NOW(), NOW()), ('8152489', NULL, 'Edward River Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.52602, 144.96664, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'edward river sportsground edward river sportsground australia au edward river sports ground,edward river sportsground',
    NOW(), NOW()), ('8152524', NULL, 'Endeavour Sports Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8985, 150.9012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'endeavour sports reserve endeavour sports reserve australia au endeavour sports reserve',
    NOW(), NOW()), ('8152576', NULL, 'Fiddens Wharf Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fiddens wharf oval fiddens wharf oval australia au fiddens wharf oval',
    NOW(), NOW()), ('8152595', NULL, 'Five Dock Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8652, 151.1346, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'five dock park five dock park australia au five dock park',
    NOW(), NOW()), ('8152616', NULL, 'Forster Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.1652, 152.5179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'forster sports centre forster sports centre australia au forster sports centre',
    NOW(), NOW()), ('8152685', NULL, 'Dangar Cranebrook Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8735, 151.2679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dangar cranebrook sportsground dangar cranebrook sportsground australia au dangar cranebrook sportsground',
    NOW(), NOW()), ('8152706', NULL, 'Els Hall Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 151.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'els hall sportsground els hall sportsground australia au els hall sportsground',
    NOW(), NOW()), ('8152713', NULL, 'Fiddens Wharf Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fiddens wharf reserve fiddens wharf reserve australia au fiddens wharf reserve',
    NOW(), NOW()), ('8152723', NULL, 'Fraser Park Railways Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9235, 151.15961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fraser park railways sports ground fraser park railways sports ground australia au fraser park railways sports ground',
    NOW(), NOW()), ('8152759', NULL, 'Collina Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.2652, 146.0679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'collina sports ground collina sports ground australia au collina sports ground',
    NOW(), NOW()), ('8152785', NULL, 'Frank Downing Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 151.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'frank downing sportsground frank downing sportsground australia au frank downing sportsground',
    NOW(), NOW()), ('8152803', NULL, 'Crown of Newport Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6485, 151.30119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'crown of newport reserve crown of newport reserve australia au crown of newport reserve',
    NOW(), NOW()), ('8152835', NULL, 'Coonamble Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.9602, 148.39149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coonamble sportsground coonamble sportsground australia au coonamble sportsground',
    NOW(), NOW()), ('8153027', NULL, 'Davenport Aboriginal Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.47054, 137.79828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport aboriginal reserve davenport aboriginal reserve australia au davenport aboriginal reserve',
    NOW(), NOW()), ('8153108', NULL, 'Donnelly Welsh Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.6985, 152.91789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donnelly welsh sporting complex donnelly welsh sporting complex australia au donnelly welsh sporting complex',
    NOW(), NOW()), ('8153141', NULL, 'Camerons Creek Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.3152, 151.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camerons creek sportsground camerons creek sportsground australia au camerons creek sportsground',
    NOW(), NOW()), ('8153195', NULL, 'Eschol Park Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0152, 150.80119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eschol park sports complex eschol park sports complex australia au eschol park sports complex',
    NOW(), NOW()), ('8153226', NULL, 'Coal Wharf Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4077, 152.91119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coal wharf reserve coal wharf reserve australia au coal wharf reserve',
    NOW(), NOW());