INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3907212', NULL, 'Puerto Méndez', 'Puerto Mendez',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.3, -63.31667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto méndez puerto mendez bolivia bo',
    NOW(), NOW()), ('3907213', NULL, 'Puerto Menacho', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.2, -62.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto menacho puerto menacho bolivia bo',
    NOW(), NOW()), ('3907214', NULL, 'Puerto Mateito', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.73333, -64.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto mateito puerto mateito bolivia bo',
    NOW(), NOW()), ('3907215', NULL, 'Puerto Márquez', 'Puerto Marquez',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.8, -66.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto márquez puerto marquez bolivia bo',
    NOW(), NOW()), ('3907216', NULL, 'Puerto Maravilla', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.26667, -66.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto maravilla puerto maravilla bolivia bo maravillas,puerto maravilla,puerto maravillas',
    NOW(), NOW()), ('3907217', NULL, 'Puerto Mamoré', 'Puerto Mamore',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.7, -64.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto mamoré puerto mamore bolivia bo puerto mamore,puerto mamoré,puerto en proyecto',
    NOW(), NOW()), ('3907218', NULL, 'Puerto Luis', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.48333, -63.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto luis puerto luis bolivia bo',
    NOW(), NOW()), ('3907219', NULL, 'Puerto López', 'Puerto Lopez',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.51667, -65.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto lópez puerto lopez bolivia bo',
    NOW(), NOW()), ('3907220', NULL, 'Puerto Linares', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.46667, -67.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto linares puerto linares bolivia bo',
    NOW(), NOW()), ('3907221', NULL, 'Puerto Leytón', 'Puerto Leyton',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.87805, -61.94684, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto leytón puerto leyton bolivia bo puerto leiton,puerto leyton,puerto leytón',
    NOW(), NOW()), ('3907222', NULL, 'Cerro Puerto León', 'Cerro Puerto Leon',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.03333, -67.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro puerto león cerro puerto leon bolivia bo cerro alto puerto leon,cerro puerto leon,cerro puerto león',
    NOW(), NOW()), ('3907223', NULL, 'Puerto Leigue', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.26667, -64.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto leigue puerto leigue bolivia bo',
    NOW(), NOW()), ('3907224', NULL, 'Puerto Julio', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.8, -64.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto julio puerto julio bolivia bo',
    NOW(), NOW()), ('3907225', NULL, 'Puerto Izozog', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.31667, -62.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto izozog puerto izozog bolivia bo puerto izozo,puerto izozog',
    NOW(), NOW()), ('3907226', NULL, 'Puerto Huata', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.3, -66.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto huata puerto huata bolivia bo puerto huara,puerto huata',
    NOW(), NOW()), ('3907227', NULL, 'Puerto Heath', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.50333, -68.64995, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto heath puerto heath bolivia bo fortin puerto heath,fortín puerto heath,heath,puerto heath',
    NOW(), NOW()), ('3907228', NULL, 'Puerto Guillén', 'Puerto Guillen',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.2, -62.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto guillén puerto guillen bolivia bo puerto guillen,puerto guillon,puerto guillén,puerto guillón',
    NOW(), NOW()), ('3907229', NULL, 'Puerto Guaqui', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.59394, -68.85143, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto guaqui puerto guaqui bolivia bo puerto guaqui',
    NOW(), NOW()), ('3907231', NULL, 'Puerto Grether', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.18333, -64.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grether puerto grether bolivia bo puerto grether,puerto gretner',
    NOW(), NOW()), ('3907232', NULL, 'Puerto Grether', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.16667, -64.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grether puerto grether bolivia bo',
    NOW(), NOW()), ('3907233', NULL, 'Puerto Grande', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.63333, -67.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grande puerto grande bolivia bo',
    NOW(), NOW()), ('3907234', NULL, 'Puerto Grande', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.56667, -66.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grande puerto grande bolivia bo',
    NOW(), NOW()), ('3907235', NULL, 'Puerto Grande', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.46667, -67.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grande puerto grande bolivia bo',
    NOW(), NOW()), ('3907236', NULL, 'Puerto Grande', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.55, -67.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto grande puerto grande bolivia bo',
    NOW(), NOW()), ('3907237', NULL, 'Puerto Gonzalo Moreno', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.08255, -66.17367, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto gonzalo moreno puerto gonzalo moreno bolivia bo pekin,puerto gonzalo moreno,gong sa luo mo lei nuo gang,貢薩洛莫雷諾港',
    NOW(), NOW()), ('3907238', NULL, 'Puerto Frey', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.6854, -61.1711, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto frey puerto frey bolivia bo puerte frey,puerto frey',
    NOW(), NOW()), ('3907239', NULL, 'Puerto Frant Yoay', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.26667, -63.1, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto frant yoay puerto frant yoay bolivia bo',
    NOW(), NOW()), ('3907240', NULL, 'Puerto Francisco', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.58333, -62.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto francisco puerto francisco bolivia bo',
    NOW(), NOW()), ('3907241', NULL, 'Puerto Florida', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.08333, -63.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto florida puerto florida bolivia bo',
    NOW(), NOW()), ('3907242', NULL, 'Puerto Flor', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.98333, -69.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto flor puerto flor bolivia bo',
    NOW(), NOW()), ('3907243', NULL, 'Puerto Félix', 'Puerto Felix',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.03333, -63.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto félix puerto felix bolivia bo',
    NOW(), NOW()), ('3907244', NULL, 'Puerto Estacones', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.96753, -66.8046, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto estacones puerto estacones bolivia bo estaciones,estacones,puerto estacones',
    NOW(), NOW()), ('3907245', NULL, 'Puerto Engaño', 'Puerto Engano',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.56667, -61.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto engaño puerto engano bolivia bo',
    NOW(), NOW()), ('3907246', NULL, 'Puerto El Ojo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.08333, -62.63333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto el ojo puerto el ojo bolivia bo',
    NOW(), NOW()), ('3907247', NULL, 'Puerto Doce', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.4, -62.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto doce puerto doce bolivia bo',
    NOW(), NOW()), ('3907248', NULL, 'Puerto de Tumupasa', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.11667, -67.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto de tumupasa puerto de tumupasa bolivia bo puerto de tumpasa,puerto de tumupasa',
    NOW(), NOW()), ('3907249', NULL, 'Puerto de los Ladrones', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.28333, -65.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto de los ladrones puerto de los ladrones bolivia bo',
    NOW(), NOW()), ('3907250', NULL, 'Puerto del Cerro', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.26667, -65.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto del cerro puerto del cerro bolivia bo puerto del carro,puerto del cerro',
    NOW(), NOW()), ('3907251', NULL, 'Puerto del Carmen', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.88333, -63.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto del carmen puerto del carmen bolivia bo puerto carmen,puerto cármen,puerto del carmen',
    NOW(), NOW()), ('3907252', NULL, 'Puerto de la Cruz', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.6, -62.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto de la cruz puerto de la cruz bolivia bo',
    NOW(), NOW()), ('3907253', NULL, 'San Marcos', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.73441, -67.42942, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san marcos san marcos bolivia bo puerto gonzales,puerto de ixiamas,san marcos',
    NOW(), NOW()), ('3907254', NULL, 'Puerto de Concepción', 'Puerto de Concepcion',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.63333, -63.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto de concepción puerto de concepcion bolivia bo puerto concepcion,puerto concepción,puerto de concepcion,puerto de concepción',
    NOW(), NOW()), ('3907255', NULL, 'Puerto Collares', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.26667, -67.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto collares puerto collares bolivia bo',
    NOW(), NOW()), ('3907256', NULL, 'Puerto Chuari', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.48333, -66.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto chuari puerto chuari bolivia bo',
    NOW(), NOW()), ('3907257', NULL, 'Puerto Chico', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.05, -67.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto chico puerto chico bolivia bo',
    NOW(), NOW()), ('3907258', NULL, 'Puerto Chacobos', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.2, -65.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto chacobos puerto chacobos bolivia bo',
    NOW(), NOW()), ('3907259', NULL, 'Puerto Cespedes', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.41667, -62.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto cespedes puerto cespedes bolivia bo hacienda la cubanita,puerto cespedes',
    NOW(), NOW()), ('3907260', NULL, 'Puerto Central', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.83333, -63.08333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'puerto central puerto central bolivia bo',
    NOW(), NOW()), ('3907261', NULL, 'Puerto Cavina', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.50194, -66.88716, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto cavina puerto cavina bolivia bo puerto cavina,puerto cavinas,puerto de cavina,puerto de cavinas',
    NOW(), NOW()), ('3907262', NULL, 'Puerto Capital Castrillo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.56261, -67.83121, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto capital castrillo puerto capital castrillo bolivia bo puerto capital castrillo,puerto capitan castrillo,puerto capitán castrillo,puerto castrillo',
    NOW(), NOW());