INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('5892702', NULL, 'Baptist Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.21087, -81.70478, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'baptist harbour baptist harbour canada ca',
    NOW(), NOW()), ('5892715', NULL, 'Barachois à Lapierre', 'Barachois a Lapierre',
    NULL, 'CA', 'Canada', NULL, NULL,
    47.25454, -61.93917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barachois à lapierre barachois a lapierre canada ca',
    NOW(), NOW()), ('5892737', NULL, 'Barachois Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.51684, -60.98181, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barachois harbour barachois harbour canada ca',
    NOW(), NOW()), ('5892786', NULL, 'Barasway Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.64994, -55.69832, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barasway harbour barasway harbour canada ca',
    NOW(), NOW()), ('5892980', NULL, 'Bargain Harbour SB 24', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.60525, -124.02357, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bargain harbour sb 24 bargain harbour sb 24 canada ca',
    NOW(), NOW()), ('5892995', NULL, 'Bar Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    74.38877, -124.09916, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bar harbour bar harbour canada ca',
    NOW(), NOW()), ('5892996', NULL, 'Bar Harbour Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.47056, -63.67828, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bar harbour lake bar harbour lake canada ca',
    NOW(), NOW()), ('5893015', NULL, 'Baril Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.76682, -90.66689, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baril portage baril portage canada ca',
    NOW(), NOW()), ('5893157', NULL, 'Barnard Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.07201, -129.10618, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barnard harbour barnard harbour canada ca',
    NOW(), NOW()), ('5893347', NULL, 'Barrachois Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.14895, -60.42768, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrachois harbour barrachois harbour canada ca',
    NOW(), NOW()), ('5893348', NULL, 'Barrachois Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.75015, -63.23197, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrachois harbour barrachois harbour canada ca',
    NOW(), NOW()), ('5893349', NULL, 'Barrachois Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.14789, -60.4252, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrachois harbour barrachois harbour canada ca',
    NOW(), NOW()), ('5894043', NULL, 'Barr''d Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.81676, -57.06488, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barr''d harbour barr''d harbour canada ca',
    NOW(), NOW()), ('5894070', NULL, 'Barrel Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.5501, -83.31648, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barrel portage barrel portage canada ca',
    NOW(), NOW()), ('5894122', NULL, 'Barrets Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.20006, -83.23318, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrets harbour barrets harbour canada ca',
    NOW(), NOW()), ('5894214', NULL, 'Barrier Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.95012, -89.86683, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barrier portage barrier portage canada ca',
    NOW(), NOW()), ('5894253', NULL, 'Barr Island Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.7668, -87.44998, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barr island harbour barr island harbour canada ca',
    NOW(), NOW()), ('5894287', NULL, 'Barrow Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.6666, -53.64809, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrow harbour barrow harbour canada ca',
    NOW(), NOW()), ('5894288', NULL, 'Barrow Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    76.55171, -95.95157, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barrow harbour barrow harbour canada ca',
    NOW(), NOW()), ('5894444', NULL, 'Bartletts Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.95008, -56.99813, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bartletts harbour bartletts harbour canada ca',
    NOW(), NOW()), ('5894445', NULL, 'Bartletts Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.95008, -56.99813, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bartletts harbour bartletts harbour canada ca',
    NOW(), NOW()), ('5894568', NULL, 'Bas-fond Port Lewis', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.18009, -74.27754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bas-fond port lewis bas-fond port lewis canada ca',
    NOW(), NOW()), ('5894601', NULL, 'Basin Head Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.3834, -62.11531, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'basin head harbour basin head harbour canada ca',
    NOW(), NOW()), ('5894725', NULL, 'Bassin Pierre-Théberge', 'Bassin Pierre-Theberge',
    NULL, 'CA', 'Canada', NULL, NULL,
    45.37818, -71.90218, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bassin pierre-théberge bassin pierre-theberge canada ca',
    NOW(), NOW()), ('5894858', NULL, 'Batchewaung Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.66653, -91.48349, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'batchewaung portage batchewaung portage canada ca',
    NOW(), NOW()), ('5895003', NULL, 'Batteau Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.40008, -55.76465, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'batteau harbour batteau harbour canada ca',
    NOW(), NOW()), ('5895074', NULL, 'Battle Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.27408, -55.58594, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'battle harbour battle harbour canada ca',
    NOW(), NOW()), ('5895075', NULL, 'Battle Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.27361, -55.58696, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'battle harbour battle harbour canada ca',
    NOW(), NOW()), ('5895137', NULL, 'Batture de la Pierre à Chaux', 'Batture de la Pierre a Chaux',
    NULL, 'CA', 'Canada', NULL, NULL,
    46.15226, -72.78493, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'batture de la pierre à chaux batture de la pierre a chaux canada ca',
    NOW(), NOW()), ('5895160', NULL, 'Battures de l''Île à la Pierre', 'Battures de l''Ile a la Pierre',
    NULL, 'CA', 'Canada', NULL, NULL,
    46.10646, -72.98414, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'battures de l''île à la pierre battures de l''ile a la pierre canada ca',
    NOW(), NOW()), ('5895161', NULL, 'Battures de l''Île à la Pierre', 'Battures de l''Ile a la Pierre',
    NULL, 'CA', 'Canada', NULL, NULL,
    46.07676, -73.03194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'battures de l''île à la pierre battures de l''ile a la pierre canada ca',
    NOW(), NOW()), ('5895176', NULL, 'Battures Saint-Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.48725, -72.2185, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'battures saint-pierre battures saint-pierre canada ca',
    NOW(), NOW()), ('5895248', NULL, 'Baxters Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.22926, -64.51525, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'baxters harbour baxters harbour canada ca baxters harbour',
    NOW(), NOW()), ('5895249', NULL, 'Baxters Harbour Falls', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.22993, -64.51239, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'baxters harbour falls baxters harbour falls canada ca',
    NOW(), NOW()), ('5895267', NULL, 'Baychimo Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    67.70083, -107.95228, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'baychimo harbour baychimo harbour canada ca',
    NOW(), NOW()), ('5895288', NULL, 'Bay de Verde Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.08319, -52.89805, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bay de verde harbour bay de verde harbour canada ca',
    NOW(), NOW()), ('5895313', NULL, 'Bayfield Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.62094, -80.51622, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bayfield harbour bayfield harbour canada ca',
    NOW(), NOW()), ('5895375', NULL, 'Bayly Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    54.81132, -94.50927, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bayly portage bayly portage canada ca',
    NOW(), NOW()), ('5895418', NULL, 'Bayport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.32152, -64.31132, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bayport bayport canada ca',
    NOW(), NOW()), ('5895425', NULL, 'Bay Roberts Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.59989, -53.26478, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bay roberts harbour bay roberts harbour canada ca',
    NOW(), NOW()), ('5895941', NULL, 'Beardrop Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.16677, -82.63316, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beardrop harbour beardrop harbour canada ca',
    NOW(), NOW()), ('5896209', NULL, 'Bear Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.25232, -85.04425, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bear portage bear portage canada ca',
    NOW(), NOW()), ('5896421', NULL, 'Beatty Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.28311, -92.30029, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beatty portage beatty portage canada ca',
    NOW(), NOW()), ('5896524', NULL, 'Beaumont Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    62.93384, -70.83142, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaumont harbour beaumont harbour canada ca',
    NOW(), NOW()), ('5896535', NULL, 'Beauport Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.81639, -95.04883, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beauport lake beauport lake canada ca',
    NOW(), NOW()), ('5896810', NULL, 'Beaver Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.90015, -62.41531, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour beaver harbour canada ca',
    NOW(), NOW()), ('5896811', NULL, 'Beaver Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.88345, -62.38191, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour beaver harbour canada ca',
    NOW(), NOW()), ('5896812', NULL, 'Beaver Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.07294, -66.74553, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour beaver harbour canada ca',
    NOW(), NOW()), ('5896813', NULL, 'Beaver Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.06819, -66.72705, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour beaver harbour canada ca',
    NOW(), NOW()), ('5896814', NULL, 'Beaver Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.70217, -127.41042, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'beaver harbour beaver harbour canada ca beaver bay',
    NOW(), NOW());