INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3452732', NULL, 'Pôrto Manga', 'Porto Manga',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.23333, -57.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto manga porto manga brazil br manga,porto manga,pôrto manga',
    NOW(), NOW()), ('3452733', NULL, 'Pôrto Manduri', 'Porto Manduri',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.91667, -56.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto manduri porto manduri brazil br porto manduri,porto da aldeia do manduri,pôrto manduri,pôrto da aldeia do manduri',
    NOW(), NOW()), ('3452734', NULL, 'Porto Lucena', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.85611, -55.01639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto lucena porto lucena brazil br puerto lucena',
    NOW(), NOW()), ('3452735', NULL, 'Pôrto Lucas', 'Porto Lucas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.30725, -52.24528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto lucas porto lucas brazil br',
    NOW(), NOW()), ('3452736', NULL, 'Pôrto Lorito', 'Porto Lorito',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.58333, -53.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto lorito porto lorito brazil br porto ferreca,porto loreto,porto lorito,porto luiz ferreira,pôrto ferreca,pôrto loreto,pôrto lorito,pôrto luiz ferreira',
    NOW(), NOW()), ('3452737', NULL, 'Pôrto Lindo', 'Porto Lindo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.65, -54.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto lindo porto lindo brazil br',
    NOW(), NOW()), ('3452738', NULL, 'Pôrto Limoeiro', 'Porto Limoeiro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.75, -57.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto limoeiro porto limoeiro brazil br',
    NOW(), NOW()), ('3452739', NULL, 'Pôrto Liberal', 'Porto Liberal',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.41667, -54.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto liberal porto liberal brazil br',
    NOW(), NOW()), ('3452740', NULL, 'Pôrto Liberal', 'Porto Liberal',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.16667, -54.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto liberal porto liberal brazil br occulto,oculto,porto liberal,pôrto liberal',
    NOW(), NOW()), ('3452741', NULL, 'Pôrto Lescano Cuê', 'Porto Lescano Cue',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.45, -53.98333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto lescano cuê porto lescano cue brazil br',
    NOW(), NOW()), ('3452742', NULL, 'Pôrto Leopoldina', 'Porto Leopoldina',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.93333, -50.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto leopoldina porto leopoldina brazil br',
    NOW(), NOW()), ('3452743', NULL, 'Pôrto Lambari', 'Porto Lambari',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.78333, -54.1, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto lambari porto lambari brazil br',
    NOW(), NOW()), ('3452744', NULL, 'Pôrto Laguna', 'Porto Laguna',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.23333, -54.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto laguna porto laguna brazil br laguna,porto laguna,pôrto laguna',
    NOW(), NOW()), ('3452745', NULL, 'Pôrto Labirinto', 'Porto Labirinto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.16667, -51.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto labirinto porto labirinto brazil br o labyrintho,porto labirinto,pôrto labirinto',
    NOW(), NOW()), ('3452746', NULL, 'Pôrto Jofre', 'Porto Jofre',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.36315, -56.77494, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jofre porto jofre brazil br porto joffre,porto jofre,pôrto jofre',
    NOW(), NOW()), ('3452747', NULL, 'Pôrto Joaquim Justino', 'Porto Joaquim Justino',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.43333, -48.43333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto joaquim justino porto joaquim justino brazil br porto joaquim antunes,porto joaquim justino,porto justino,pôrto joaquim antunes,pôrto joaquim justino,pôrto justino',
    NOW(), NOW()), ('3452748', NULL, 'Pôrto Joana', 'Porto Joana',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.31667, -47, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto joana porto joana brazil br porto joana,pôrto joana',
    NOW(), NOW()), ('3452749', NULL, 'Pôrto Jejuí', 'Porto Jejui',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.80203, -54.36687, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jejuí porto jejui brazil br porto jejui,porto jejuy,pôrto jejuy,pôrto jejuí',
    NOW(), NOW()), ('3452750', NULL, 'Pôrto Jatobá', 'Porto Jatoba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.48333, -56.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jatobá porto jatoba brazil br',
    NOW(), NOW()), ('3452751', NULL, 'Pôrto Jatobá', 'Porto Jatoba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.06667, -58.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jatobá porto jatoba brazil br porto jatoba,porto do jatoba,pôrto jatobá',
    NOW(), NOW()), ('3452752', NULL, 'Pôrto Jacaré', 'Porto Jacare',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.96667, -45.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jacaré porto jacare brazil br porto jacare,pôrto jacaré',
    NOW(), NOW()), ('3452753', NULL, 'Pôrto Jacaré', 'Porto Jacare',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.60381, -50.93935, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto jacaré porto jacare brazil br porto jacare,pôrto jacaré',
    NOW(), NOW()), ('3452754', NULL, 'Pôrto Itaparica', 'Porto Itaparica',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.66667, -51.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto itaparica porto itaparica brazil br',
    NOW(), NOW()), ('3452755', NULL, 'Pôrto Ítalo', 'Porto Italo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.33333, -48.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ítalo porto italo brazil br',
    NOW(), NOW()), ('3452756', NULL, 'Pôrto Italiano', 'Porto Italiano',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.01667, -39.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto italiano porto italiano brazil br porto italiano,pôrto italiano',
    NOW(), NOW()), ('3452757', NULL, 'Pôrto Itacorá', 'Porto Itacora',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.10654, -54.3953, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto itacorá porto itacora brazil br porto itacora,puerto itacora,pôrto itacorá',
    NOW(), NOW()), ('3452758', NULL, 'Pôrto Isabel', 'Porto Isabel',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.95, -54.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto isabel porto isabel brazil br',
    NOW(), NOW()), ('3452759', NULL, 'Pôrto Iporã', 'Porto Ipora',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.56667, -54.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto iporã porto ipora brazil br porto ipora,porto vanilha,pôrto iporã,pôrto vanilha',
    NOW(), NOW()), ('3452760', NULL, 'Pôrto Ipiranga', 'Porto Ipiranga',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.21667, -52.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ipiranga porto ipiranga brazil br',
    NOW(), NOW()), ('3452761', NULL, 'Pôrto Independência', 'Porto Independencia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.9839, -51.70343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto independência porto independencia brazil br',
    NOW(), NOW()), ('3452762', NULL, 'Pôrto Gurupaí', 'Porto Gurupai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.18333, -54.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto gurupaí porto gurupai brazil br gurupai,gurupay,porto curupahy,porto gurupai,porto gurupay,pôrto gurupaí',
    NOW(), NOW()), ('3452763', NULL, 'Pôrto Guavirá', 'Porto Guavira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.4, -54.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto guavirá porto guavira brazil br guavira,guavirá,porto guavira,pôrto guavirá',
    NOW(), NOW()), ('3452764', NULL, 'Pôrto Guareí', 'Porto Guarei',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.66667, -53.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto guareí porto guarei brazil br',
    NOW(), NOW()), ('3452765', NULL, 'Pôrto Guarani', 'Porto Guarani',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.3, -53.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto guarani porto guarani brazil br',
    NOW(), NOW()), ('3452766', NULL, 'Pôrto Guaíra', 'Porto Guaira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.38333, -48.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto guaíra porto guaira brazil br ponte guayra,porto guaira,porto guasca,pôrto guasca,pôrto guaíra',
    NOW(), NOW()), ('3452767', NULL, 'Pôrto Góis', 'Porto Gois',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.21667, -47.23333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto góis porto gois brazil br porto gois,pôrto góis',
    NOW(), NOW()), ('3452768', NULL, 'Pôrto Giovani', 'Porto Giovani',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.95, -50.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto giovani porto giovani brazil br',
    NOW(), NOW()), ('3452769', NULL, 'Pôrto Gato Prêto', 'Porto Gato Preto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.33333, -53.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto gato prêto porto gato preto brazil br',
    NOW(), NOW()), ('3452770', NULL, 'Pôrto Galvão', 'Porto Galvao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.95, -50.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto galvão porto galvao brazil br',
    NOW(), NOW()), ('3452771', NULL, 'Porto Fundação', 'Porto Fundacao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.98333, -55.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto fundação porto fundacao brazil br porto fundacao,porto fundação',
    NOW(), NOW()), ('3452772', NULL, 'Pôrto Flores', 'Porto Flores',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.76667, -57.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto flores porto flores brazil br',
    NOW(), NOW()), ('3452773', NULL, 'Pôrto Firmino', 'Porto Firmino',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63207, -51.73037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto firmino porto firmino brazil br porto afonso de camargo,porto firmino,pôrto afonso de camargo,pôrto firmino',
    NOW(), NOW()), ('3452774', NULL, 'Porto Firme', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.67333, -43.08444, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto firme porto firme brazil br porto seguro',
    NOW(), NOW()), ('3452775', NULL, 'Porto Ferreira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.85389, -47.47917, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto ferreira porto ferreira brazil br porto ferreiro,portu-ferrejra,порту-феррейра',
    NOW(), NOW()), ('3452776', NULL, 'Pôrto Ferrão', 'Porto Ferrao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.55, -49.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ferrão porto ferrao brazil br porto ferrao,pôrto ferrão',
    NOW(), NOW()), ('3452777', NULL, 'Porto Ferrão', 'Porto Ferrao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.54018, -49.15537, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto ferrão porto ferrao brazil br porto ferrao,porto ferrão,pôrto ferrão',
    NOW(), NOW()), ('3452778', NULL, 'Pôrto Feliz', 'Porto Feliz',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.8, -50.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto feliz porto feliz brazil br',
    NOW(), NOW()), ('3452779', NULL, 'Porto Feliz', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.21472, -47.52389, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto feliz porto feliz brazil br portu-felis,порту-фелис',
    NOW(), NOW()), ('3452780', NULL, 'Pôrto Feliz', 'Porto Feliz',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.06667, -50.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto feliz porto feliz brazil br porto feliz,pôrto feliz',
    NOW(), NOW()), ('3452781', NULL, 'Pôrto Felicidade', 'Porto Felicidade',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.96667, -54.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto felicidade porto felicidade brazil br porto felicidade,porto roseira,pôrto felicidade',
    NOW(), NOW());