INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('2063036', NULL, 'Port Lincoln', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.72625, 135.87442, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port lincoln port lincoln australia au plo,port lincoln,port-linkol''n,pt lincoln,lin ken gang,poteulingkeon,potorinkan,порт-линкольн,порт-лінкольн,پورٹ لنکولن,პორტ-ლინკოლნი,ポートリンカーン,林肯港,포트링컨',
    NOW(), NOW()), ('2063037', NULL, 'Portland River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.5, 116.83333, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland river portland river australia au portland,portland river',
    NOW(), NOW()), ('2063038', NULL, 'Port Kenny', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.16667, 134.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kenny port kenny australia au port kenny',
    NOW(), NOW()), ('2063040', NULL, 'Port Julia', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66667, 137.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port julia port julia australia au port julia',
    NOW(), NOW()), ('2063041', NULL, 'Port Hughes', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.08333, 137.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hughes port hughes australia au port hughes',
    NOW(), NOW()), ('2063042', NULL, 'Port Hedland', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.31215, 118.61059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hedland port hedland australia au phe,port hedland,port khedland,port-gedlend,port-khedlend,poteuhedeullaendeu,potoheddorando,pwrt hdlnd,порт хедланд,порт-гедленд,порт-хедленд,פורט הדלנד,პორტ-ჰედლანდი,ポートヘッドランド,포트헤들랜드',
    NOW(), NOW()), ('2063044', NULL, 'Port Germein', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.02162, 138.00133, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port germein port germein australia au port germein',
    NOW(), NOW()), ('2063045', NULL, 'Porters Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.43333, 134.23333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters well porters well australia au',
    NOW(), NOW()), ('2063046', NULL, 'Porters Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.98333, 137.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters hill porters hill australia au',
    NOW(), NOW()), ('2063047', NULL, 'Porters Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.9, 130.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters creek porters creek australia au',
    NOW(), NOW()), ('2063048', NULL, 'Porter Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.50249, 123.5268, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter hill porter hill australia au',
    NOW(), NOW()), ('2063049', NULL, 'Porter Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.74037, 135.88268, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter bay porter bay australia au porter bay',
    NOW(), NOW()), ('2063050', NULL, 'Mount Porter', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.635, 131.8203, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount porter mount porter australia au mount porter',
    NOW(), NOW()), ('2063051', NULL, 'Port Elliot', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.53017, 138.67922, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot port elliot australia au port elliot',
    NOW(), NOW()), ('2063052', NULL, 'Port Davis Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.25, 137.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port davis creek port davis creek australia au',
    NOW(), NOW()), ('2063053', NULL, 'Port Clinton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.22429, 138.02055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port clinton port clinton australia au',
    NOW(), NOW()), ('2063054', NULL, 'Port Broughton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6007, 137.93597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton port broughton australia au port broughton',
    NOW(), NOW()), ('2063055', NULL, 'Port Augusta West', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.48611, 137.75833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta west port augusta west australia au',
    NOW(), NOW()), ('2063056', NULL, 'Port Augusta', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.49597, 137.77281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta port augusta australia au haveno augusta,haveno aŭgusta,kurdnatta,pug,port augusta,port avgusta,port ogasta,port onkousta,port-agasta,port-avgusta,port-ogasta,portogasta,puerto augusta,ao gu si ta gang,phxr thx xkas ta,port agasta,port akasta,porta agasta,porta ogasta,poteuogeoseuta,potoogasuta,pwrt agwsta,πορτ ωγκούστα,порт августа,порт-августа,порт-агаста,порт-огаста,պորտ օգաստա,פורט אוגוסטה,ميناء أوغستا,ميناء اوجستا,پورت آگوستا,پورٹ آگستا,پورٹ آگسٹا، جنوبی آسٹریلیا,پۆرت ئۆگەستا,पोर्ट अगस्ता,पोर्ट ऑगस्टा,পোর্ট অগাস্টা,પોર્ટ ઑગસ્ટા,போர்ட் அகஸ்டா,పోర్ట్ అగస్టా,ಪೋರ್ಟ್ ಆಗಸ್ಟಾ,പോർട്ട് അഗസ്റ്റ,පෝර්ට් ඔගස්ටා,พอร์ทออกัสตา,პორტ-ოგასტა,ポートオーガスタ,奥古斯塔港,奧古斯塔港,포트오거스타',
    NOW(), NOW()), ('2063058', NULL, 'Port Adelaide River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.78333, 138.46667, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port adelaide river port adelaide river australia au port adelaide river,port river',
    NOW(), NOW()), ('2063059', NULL, 'Port Adelaide', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8462, 138.50302, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port adelaide port adelaide australia au port adelaide,پورٹ ایڈیلیڈ، جنوبی آسٹریلیا',
    NOW(), NOW()), ('2063171', NULL, 'Point Turton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.95233, 137.35652, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point turton point turton australia au port turton',
    NOW(), NOW()), ('2063181', NULL, 'Point Davenport Shoal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.18333, 137.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point davenport shoal point davenport shoal australia au',
    NOW(), NOW()), ('2063420', NULL, 'Pierre Spring', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.24588, 121.0989, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierre spring pierre spring australia au',
    NOW(), NOW()), ('2063421', NULL, 'Mount Pierre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.29414, 125.8738, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre mount pierre australia au',
    NOW(), NOW()), ('2063422', NULL, 'Piero Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.83815, 118.3614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piero well piero well australia au',
    NOW(), NOW()), ('2063423', NULL, 'Pieradutta Waterhole', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.78333, 136.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pieradutta waterhole pieradutta waterhole australia au',
    NOW(), NOW()), ('2063509', NULL, 'Petermarina Pool', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.78333, 119.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'petermarina pool petermarina pool australia au',
    NOW(), NOW()), ('2063630', NULL, 'Pelican Lagoon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.81249, 137.8016, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelican lagoon pelican lagoon australia au pelican lagoon,port dache',
    NOW(), NOW()), ('2063697', NULL, 'Pear Creek Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.6167, 119.5661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pear creek well pear creek well australia au pear creek well,pier creek well',
    NOW(), NOW()), ('2063749', NULL, 'Port Patterson', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.61667, 130.43333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port patterson port patterson australia au',
    NOW(), NOW()), ('2064011', NULL, 'Oyster Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.9775, 117.95889, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'oyster harbour oyster harbour australia au oyster harbour',
    NOW(), NOW()), ('2064230', NULL, 'Old Napier Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.25, 124.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'old napier downs old napier downs australia au',
    NOW(), NOW()), ('2064833', NULL, 'Port Nelson', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.06869, 125.01532, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port nelson port nelson australia au',
    NOW(), NOW()), ('2064975', NULL, 'Napier Range', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.34806, 124.8444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier range napier range australia au napier range',
    NOW(), NOW()), ('2064976', NULL, 'Napier Peninsula', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.06667, 135.71667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier peninsula napier peninsula australia au napier peninsula',
    NOW(), NOW()), ('2064977', NULL, 'Napier Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.18333, 124.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier downs napier downs australia au',
    NOW(), NOW()), ('2064978', NULL, 'Napier Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83333, 118, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier creek napier creek australia au',
    NOW(), NOW()), ('2064979', NULL, 'Napier Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.34248, 124.6743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier creek napier creek australia au',
    NOW(), NOW()), ('2064980', NULL, 'Napier Broome Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.0433, 126.6121, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier broome bay napier broome bay australia au napier broome bay',
    NOW(), NOW()), ('2064981', NULL, 'Napier Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.5227, 131.4828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier bay napier bay australia au napier bay',
    NOW(), NOW()), ('2064982', NULL, 'Point Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.95605, 135.91359, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point napier point napier australia au napier point,point napier',
    NOW(), NOW()), ('2064983', NULL, 'Mount Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.53583, 129.17, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount napier mount napier australia au mount napier',
    NOW(), NOW()), ('2064984', NULL, 'Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83333, 118, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier napier australia au',
    NOW(), NOW()), ('2065228', NULL, 'Murdock Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.98333, 138.91667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'murdock hill murdock hill australia au murdock hill',
    NOW(), NOW()), ('2065322', NULL, 'Mundoora Arm', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.61667, 137.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mundoora arm mundoora arm australia au mundoora arm,port broughton',
    NOW(), NOW()), ('2065549', NULL, 'Mount Riddoch', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.04112, 134.67257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount riddoch mount riddoch australia au mount riddoch,mount riddock,mount riddock homestead',
    NOW(), NOW()), ('2065553', NULL, 'Mount Pierre Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.33333, 125.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre creek mount pierre creek australia au',
    NOW(), NOW()), ('2065633', NULL, 'Mount Dockrell Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.83333, 127.16667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount dockrell well mount dockrell well australia au',
    NOW(), NOW()), ('2065842', NULL, 'Moonta Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.03571, 137.54407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moonta bay moonta bay australia au moonta bay,port moonta',
    NOW(), NOW());