
    INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('1401', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1402', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1403', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1404', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1405', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1406', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1407', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1408', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1409', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1410', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1411', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1412', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1413', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1414', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1415', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1416', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1417', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1418', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1419', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1420', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1421', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1422', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1423', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1424', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1425', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1426', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1427', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1428', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1429', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1430', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1431', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1432', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1433', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1434', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1435', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1436', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1437', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1438', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1439', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1440', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1441', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1442', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1443', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1444', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1445', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1446', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1447', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1448', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1449', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1450', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1451', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1452', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1453', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1454', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1455', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1456', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1457', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1458', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1459', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1460', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1461', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1462', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1463', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1464', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1465', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1466', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1467', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1468', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1469', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1470', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1471', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1472', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1473', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1474', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1475', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1476', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1477', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1478', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1479', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1480', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1481', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1482', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1483', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1484', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1485', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1486', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1487', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1488', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1489', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1490', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1491', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1492', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1493', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1494', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1495', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW()),
('1496', 'Europe', 'Port of Rotterdam', NULL,
    'NLRTM', 'NL', 'Netherlands', NULL, NULL,
    51.955, 4.125, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of rotterdam netherlands nlrtm seaport europe',
    NOW(), NOW()),
('1497', 'Asia', 'Port of Singapore', NULL,
    'SGSIN', 'SG', 'Singapore', NULL, NULL,
    1.264, 103.84, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of singapore singapore sgsin seaport asia',
    NOW(), NOW()),
('1498', 'Asia', 'Port of Shanghai', NULL,
    'CNSHA', 'CN', 'China', NULL, NULL,
    31.23, 121.49, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of shanghai china cnsha seaport asia',
    NOW(), NOW()),
('1499', 'North America', 'Port of Los Angeles', NULL,
    'USLAX', 'US', 'United States', NULL, NULL,
    33.736, -118.262, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of los angeles united states uslax seaport north america',
    NOW(), NOW()),
('1500', 'Europe', 'Port of Hamburg', NULL,
    'DEHAM', 'DE', 'Germany', NULL, NULL,
    53.546, 9.966, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'port of hamburg germany deham seaport europe',
    NOW(), NOW());
  