INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8847044', NULL, 'Horse Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.28038, 116.8214, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horse paddock well horse paddock well australia au horse paddock well',
    NOW(), NOW()), ('8847220', NULL, 'Poison Paddock Mill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.32344, 118.0959, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'poison paddock mill poison paddock mill australia au poison paddock mill',
    NOW(), NOW()), ('8847388', NULL, 'Horsepaddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.72369, 121.1797, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horsepaddock well horsepaddock well australia au horsepaddock well',
    NOW(), NOW()), ('8847599', NULL, 'Ram Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.2676, 115.8428, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock well ram paddock well australia au ram paddock well',
    NOW(), NOW()), ('8847789', NULL, 'Stallion Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.78801, 128.8885, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stallion paddock bore stallion paddock bore australia au stallion paddock bore',
    NOW(), NOW()), ('8847798', NULL, 'Wooley Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.49755, 118.9105, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wooley paddock well wooley paddock well australia au wooley paddock well',
    NOW(), NOW()), ('8847808', NULL, 'Horse Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.24679, 116.3406, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horse paddock bore horse paddock bore australia au horse paddock bore',
    NOW(), NOW()), ('8847846', NULL, 'Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.6783, 126.9413, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paddock bore paddock bore australia au paddock bore',
    NOW(), NOW()), ('8847862', NULL, 'Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.44886, 127.3554, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paddock bore paddock bore australia au paddock bore',
    NOW(), NOW()), ('8848165', NULL, 'Bullet Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.36136, 126.439, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullet paddock bore bullet paddock bore australia au bullet paddock bore',
    NOW(), NOW()), ('8848374', NULL, 'Ram Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.61846, 116.7486, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock bore ram paddock bore australia au ram paddock bore',
    NOW(), NOW()), ('8848474', NULL, 'Holding Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.70952, 120.0825, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'holding paddock well holding paddock well australia au holding paddock well',
    NOW(), NOW()), ('8848639', NULL, 'Horse Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.064, 117.6684, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horse paddock bore horse paddock bore australia au horse paddock bore',
    NOW(), NOW()), ('8849065', NULL, 'Shed Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.14953, 118.5189, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shed paddock well shed paddock well australia au shed paddock well',
    NOW(), NOW()), ('8849348', NULL, 'Mt Riddock Landing Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.0361, 134.6902, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mt riddock landing ground mt riddock landing ground australia au mt riddock landing ground',
    NOW(), NOW()), ('8849441', NULL, 'Lakes Entrance Airfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.85208, 147.95042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lakes entrance airfield lakes entrance airfield australia au great lakes airport,kepper field,lakes entrance airfield,ygrl',
    NOW(), NOW()), ('8849453', NULL, 'Western Port Aerodrome', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.26514, 145.17903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'western port aerodrome western port aerodrome australia au western port aerodrome',
    NOW(), NOW()), ('8849457', NULL, 'Coldstream Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.72833, 145.40833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coldstream airport coldstream airport australia au coldstream airfield,ycem',
    NOW(), NOW()), ('8849503', NULL, 'Port Melbourne Heliport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.82625, 144.90819, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port melbourne heliport port melbourne heliport australia au port melbourne heliport',
    NOW(), NOW()), ('8849504', NULL, 'HMAS Stirling Helicopter Support Facility', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.24167, 115.6833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hmas stirling helicopter support facility hmas stirling helicopter support facility australia au hmas stirling helicopter support facility',
    NOW(), NOW()), ('8849528', NULL, 'Port Kembla Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.4805, 150.9004, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla post office port kembla post office australia au port kembla post office',
    NOW(), NOW()), ('8849529', NULL, 'Portland Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3568, 149.9762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland post office portland post office australia au portland post office',
    NOW(), NOW()), ('8849708', NULL, 'Cradock Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.06982, 138.4929, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cradock post office cradock post office australia au cradock post office',
    NOW(), NOW()), ('8849741', NULL, 'Australia Post Victor Harbor Post Shop', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.55374, 138.6211, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'australia post victor harbor post shop australia post victor harbor post shop australia au encounter bay post office',
    NOW(), NOW()), ('8849866', NULL, 'Port Augusta East Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.49953, 137.7766, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta east post office port augusta east post office australia au port augusta east post office',
    NOW(), NOW()), ('8849867', NULL, 'Port Augusta Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.49162, 137.76233, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta post office port augusta post office australia au port augusta post office',
    NOW(), NOW()), ('8849868', NULL, 'Port Adelaide Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84417, 138.50446, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port adelaide post office port adelaide post office australia au port adelaide post office',
    NOW(), NOW()), ('8849869', NULL, 'Port Broughton Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.59995, 137.93108, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton post office port broughton post office australia au port broughton post office',
    NOW(), NOW()), ('8849870', NULL, 'Port Elliot Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.53165, 138.68097, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot post office port elliot post office australia au port elliot post office',
    NOW(), NOW()), ('8849871', NULL, 'Port Germein Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.023, 138.00075, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port germein post office port germein post office australia au port germein post office',
    NOW(), NOW()), ('8849872', NULL, 'Port Kenny Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.16854, 134.68456, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kenny post office port kenny post office australia au port kenny post office',
    NOW(), NOW()), ('8849873', NULL, 'Port MacDonnell Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.0529, 140.70106, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port macdonnell post office port macdonnell post office australia au port macdonnell post office',
    NOW(), NOW()), ('8849874', NULL, 'Port Pirie Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.17621, 138.01027, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port pirie post office port pirie post office australia au port pirie post office',
    NOW(), NOW()), ('8849875', NULL, 'Port Victoria Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.49635, 137.48367, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port victoria post office port victoria post office australia au port victoria post office',
    NOW(), NOW()), ('8849876', NULL, 'Port Vincent Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.77908, 137.8591, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port vincent post office port vincent post office australia au port vincent post office',
    NOW(), NOW()), ('8849877', NULL, 'Port Wakefield Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.18435, 138.14796, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port wakefield post office port wakefield post office australia au port wakefield post office',
    NOW(), NOW()), ('8850084', NULL, 'Stockport Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.33439, 138.73178, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stockport post office stockport post office australia au stockport post office',
    NOW(), NOW()), ('8850115', NULL, 'Australia Post Victor Harbor Central CPA', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.55317, 138.62311, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'australia post victor harbor central cpa australia post victor harbor central cpa australia au victor harbor post office',
    NOW(), NOW()), ('8850193', NULL, 'Port Lincoln Post Office', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.72023, 135.85761, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln post office port lincoln post office australia au port lincoln post office',
    NOW(), NOW()), ('8850232', NULL, 'Pierce Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.40539, 148.90163, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierce hill pierce hill australia au pierce hill',
    NOW(), NOW()), ('8850837', NULL, 'Middle Paddock Sandhill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.8318, 144.7179, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'middle paddock sandhill middle paddock sandhill australia au middle paddock sandhill',
    NOW(), NOW()), ('8850986', NULL, 'Port Mantle Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.2152, 150.1679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port mantle hill port mantle hill australia au port mantle hill',
    NOW(), NOW()), ('8851017', NULL, 'Ration Paddock Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.4485, 151.2012, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ration paddock hill ration paddock hill australia au ration paddock hill',
    NOW(), NOW()), ('8852076', NULL, 'Weaning Paddock Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.57861, 152.74778, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'weaning paddock hill weaning paddock hill australia au weaning paddock hill',
    NOW(), NOW()), ('8852202', NULL, 'Boat Harbor Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.50883, 138.22942, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbor hill boat harbor hill australia au boat harbor hill',
    NOW(), NOW()), ('8852520', NULL, 'Porter Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.55157, 138.58882, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter hill porter hill australia au porter hill',
    NOW(), NOW()), ('8852521', NULL, 'Porter Lookout', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.14983, 140.54739, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter lookout porter lookout australia au porter lookout',
    NOW(), NOW()), ('8853167', NULL, 'Portview Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.24, 146.57001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portview hill portview hill australia au portview hill',
    NOW(), NOW()), ('8853219', NULL, 'Portland Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.76, 147.97, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland hill portland hill australia au portland hill',
    NOW(), NOW()), ('8853764', NULL, 'Port Hills', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.91, 144.67, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hills port hills australia au port hills',
    NOW(), NOW());