INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('10526316', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.73053, 45.19733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('10643320', NULL, 'Aghavnots’', 'Aghavnots''',
    NULL, 'AM', 'AM', NULL, NULL,
    39.6889, 45.48749, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnots’ aghavnots'' am am aghavnots'',aghavnots’,աղավնոց',
    NOW(), NOW()), ('10643384', NULL, 'Aghavno', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.68329, 45.49591, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavno aghavno am am agavno,aghavno,աղավնո',
    NOW(), NOW()), ('10643385', NULL, 'Aghavnots’', 'Aghavnots''',
    NULL, 'AM', 'AM', NULL, NULL,
    39.6861, 45.49451, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnots’ aghavnots'' am am aghavnots'',aghavnots’,աղավնոց',
    NOW(), NOW()), ('11108408', NULL, 'Aghavnut', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.42908, 45.03473, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnut aghavnut am am agavnut,aghavnut,աղավնուտ',
    NOW(), NOW()), ('11108887', NULL, 'Aghavnut', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.39172, 45.16528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnut aghavnut am am agavnut,aghavnut,աղավնուտ',
    NOW(), NOW()), ('11110882', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.20007, 44.32507, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('11110883', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.19873, 44.32788, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('11128763', NULL, 'Aghavnabni', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.32507, 44.16248, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabni aghavnabni am am agavnabni,aghavnabni,աղավնաբնի',
    NOW(), NOW()), ('11129276', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.35828, 44.05689, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('11129277', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.35968, 44.05548, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('11132868', NULL, 'Aghavnehand', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.46668, 43.64728, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnehand aghavnehand am am agavnehand,aghavnehand,աղավնեհանդ',
    NOW(), NOW()), ('11190667', NULL, 'Aghavnabuyn', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.91248, 45.26672, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabuyn aghavnabuyn am am agavnabuyn,aghavnabuyn,աղավնաբույն',
    NOW(), NOW()), ('11214928', NULL, 'Aghavnabner', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.48328, 43.91388, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabner aghavnabner am am agavnabner,aghavnabner,աղավնաբներ',
    NOW(), NOW()), ('11214929', NULL, 'Aghavnabuyn', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.48468, 43.91248, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabuyn aghavnabuyn am am agavnabuyn,aghavnabuyn,աղավնաբույն',
    NOW(), NOW()), ('11215084', NULL, 'Aghavnu Kond', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.47369, 43.87231, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnu kond aghavnu kond am am agavnu kond,aghavnu kond,աղավնու կոնդ',
    NOW(), NOW()), ('11224471', NULL, 'Aghavnatan', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.2431, 44.21808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnatan aghavnatan am am agavnatan,aghavnatan,աղավնատան',
    NOW(), NOW()), ('11227330', NULL, 'Aghavnatun', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.23052, 44.2445, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnatun aghavnatun am am agavnatun,aghavnatun,աղավնատուն',
    NOW(), NOW()), ('11231087', NULL, 'Aghavnabner', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.39447, 44.39587, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabner aghavnabner am am agavnabner,aghavnabner,աղավնաբներ',
    NOW(), NOW()), ('11320814', NULL, 'Portni', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.81671, 44.71668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portni portni am am portni,պորտնի',
    NOW(), NOW()), ('11323929', NULL, 'Aghavnu K’arayr', 'Aghavnu K''arayr',
    NULL, 'AM', 'AM', NULL, NULL,
    40.9361, 45.14172, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnu k’arayr aghavnu k''arayr am am aghavnu k''arayr,aghavnu k’arayr,աղավնու քարայր',
    NOW(), NOW()), ('11328542', NULL, 'Aghavnak’ari', 'Aghavnak''ari',
    NULL, 'AM', 'AM', NULL, NULL,
    39.25848, 46.34729, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnak’ari aghavnak''ari am am aghavnak''ari,aghavnak’ari,աղավնաքարի',
    NOW(), NOW()), ('11329821', NULL, 'Aghavnak’ar', 'Aghavnak''ar',
    NULL, 'AM', 'AM', NULL, NULL,
    39.20428, 46.52087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnak’ar aghavnak''ar am am aghavnak''ar,aghavnak’ar,աղավնաքար',
    NOW(), NOW()), ('11330604', NULL, 'Portak’ar', 'Portak''ar',
    NULL, 'AM', 'AM', NULL, NULL,
    39.52508, 46.16107, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portak’ar portak''ar am am portak''ar,portak’ar,պորտաքար',
    NOW(), NOW()), ('11330605', NULL, 'Portak’ar', 'Portak''ar',
    NULL, 'AM', 'AM', NULL, NULL,
    39.52228, 46.15289, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portak’ar portak''ar am am portak''ar,portak’ar,պորտաքար',
    NOW(), NOW()), ('11330606', NULL, 'Portak’ar', 'Portak''ar',
    NULL, 'AM', 'AM', NULL, NULL,
    39.52649, 46.15008, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portak’ar portak''ar am am portak''ar,portak’ar,պորտաքար',
    NOW(), NOW()), ('11330607', NULL, 'Portak’ari', 'Portak''ari',
    NULL, 'AM', 'AM', NULL, NULL,
    39.52368, 46.15008, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portak’ari portak''ari am am portak''ari,portak’ari,պորտաքարի',
    NOW(), NOW()), ('11335790', NULL, 'Shavnidzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.15008, 45.14728, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shavnidzor shavnidzor am am savnijor,shavnidzor,շավնիձոր',
    NOW(), NOW()), ('11336274', NULL, 'Portik', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.13068, 44.68048, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portik portik am am portik,պորտիկ',
    NOW(), NOW()), ('11336275', NULL, 'Portiki Aghbyur', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.12909, 44.67792, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portiki aghbyur portiki aghbyur am am portiki aghbyur,portiki agbyur,պորտիկի աղբյուր',
    NOW(), NOW()), ('11336285', NULL, 'Aghavnu Bner', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.24872, 44.73053, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnu bner aghavnu bner am am agavnu bner,aghavnu bner,աղավնու բներ',
    NOW(), NOW()), ('11341729', NULL, 'Lukashin S.', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.7959, 43.8501, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukashin s. lukashin s. am am lukashin s.,lukasin s.,լուկաշին ս.',
    NOW(), NOW()), ('11342941', NULL, 'Aghavnavank', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.72558, 45.11535, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnavank aghavnavank am am aghavnavank monastery,agnabatʻ vankʻ,anapat surb astvacacin vankʻ,աղավնավանք,աղնաբաթ վանք,անապատ սուրբ աստվածածին վանք',
    NOW(), NOW()), ('11342942', NULL, 'Aghavnavank’i', 'Aghavnavank''i',
    NULL, 'AM', 'AM', NULL, NULL,
    40.72567, 45.06952, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnavank’i aghavnavank''i am am aghavnavank''i,aghavnavank’i,աղավնավանքի',
    NOW(), NOW()), ('11342943', NULL, 'Aghavnut', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.7555, 45.05831, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnut aghavnut am am agavnut,aghavnut,աղավնուտ',
    NOW(), NOW()), ('11363430', NULL, 'Odzaport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    41.02228, 44.58893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'odzaport odzaport am am odzaport,ojaport,օձապորտ',
    NOW(), NOW()), ('11363431', NULL, 'Odzaport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    41.01947, 44.59168, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'odzaport odzaport am am odzaport,ojaport,օձապորտ',
    NOW(), NOW()), ('11363432', NULL, 'Odzaport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    41.01813, 44.58893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'odzaport odzaport am am odzaport,ojaport,օձապորտ',
    NOW(), NOW()), ('11365539', NULL, 'Marinayi K’arap’', 'Marinayi K''arap''',
    NULL, 'AM', 'AM', NULL, NULL,
    40.65973, 44.01813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marinayi k’arap’ marinayi k''arap'' am am marinayi k''arap'',marinayi k’arap’,մարինայի քարափ',
    NOW(), NOW()), ('11370237', NULL, 'Aghavnasar', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.53888, 44.72089, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnasar aghavnasar am am agavnasar,aghavnasar,աղավնասար',
    NOW(), NOW()), ('11370314', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.69733, 44.69733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('11370316', NULL, 'Aghavnabun', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.58612, 44.70148, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnabun aghavnabun am am agavnabun,aghavnabun,աղավնաբուն',
    NOW(), NOW()), ('11370317', NULL, 'Aghavnat’ev', 'Aghavnat''ev',
    NULL, 'AM', 'AM', NULL, NULL,
    40.59027, 44.69733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnat’ev aghavnat''ev am am aghavnat''ev,aghavnat’ev,աղավնաթև',
    NOW(), NOW()), ('11371176', NULL, 'Aghavno', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.53332, 46.58612, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavno aghavno am am agavno,aghavno,աղավնո',
    NOW(), NOW()), ('11500144', NULL, 'Syunik Airport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.20226, 46.45527, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'syunik airport syunik airport am am syunik airport,udck,yuk',
    NOW(), NOW()), ('13156245', NULL, 'Armenian State Institute of Physical Culture and Sport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.17606, 44.52374, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'armenian state institute of physical culture and sport armenian state institute of physical culture and sport am am asipcs,armenian state institute of physical culture and sport,hfkspi,hayastani fizikakan kulturayi ev sporti petakan institut,hayastani fizikakan kulturayi yev sporti petakan institut,հֆկսպի,հայաստանի ֆիզիկական կուլտուրայի և սպորտի պետական ինստիտուտ',
    NOW(), NOW()), ('13156371', NULL, 'Karen Demirchyan Sports and Concerts Complex', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.18834, 44.48334, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karen demirchyan sports and concerts complex karen demirchyan sports and concerts complex am am demirchyan arena,demircyan marzahamalir,hamalir,karen demirchyan sports and concerts complex,karen demircyani anvan marzahamergayin hamalir,դեմիրճյան մարզահամալիր,կարեն դեմիրճյանի անվան մարզահամերգային համալիր,համալիր',
    NOW(), NOW()), ('13433553', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.23608, 44.24872, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnajor,aghavnadzor,աղավնաձոր',
    NOW(), NOW()), ('145724', NULL, 'Lucapa', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -8.41915, 20.74466, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'lucapa lucapa angola ao lbz,lucapa,lukapa,лукапа',
    NOW(), NOW()), ('145775', NULL, 'Chitato', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -7.41914, 20.39811, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chitato chitato angola ao chitato,circunscricao de chitato,circunscricao do chitato,circunscrição de chitato,circunscrição do chitato,concelho de portugalia,concelho de portugália,municipio chitato,municipio do chitato,município chitato,município do chitato',
    NOW(), NOW());