INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('8159754', NULL, 'Rologas Sporting Fields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.511, 151.67371, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rologas sporting fields rologas sporting fields australia au rologas sporting fields',
    NOW(), NOW()), ('8159809', NULL, 'Newport Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.37732, 149.56663, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport conservation park newport conservation park australia au newport conservation park',
    NOW(), NOW()), ('8159824', NULL, 'Police Paddock Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.55841, 152.68384, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'police paddock conservation park police paddock conservation park australia au police paddock conservation park',
    NOW(), NOW()), ('8159880', NULL, 'Port Elliot Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.52991, 138.67548, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot oval port elliot oval australia au port elliot oval',
    NOW(), NOW()), ('8159894', NULL, 'Olympic Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.92169, 138.65269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic sportsfield olympic sportsfield australia au olympic sportsfield',
    NOW(), NOW()), ('8159920', NULL, 'Port Gawler Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66993, 138.4398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port gawler conservation park port gawler conservation park australia au port gawler conservation park',
    NOW(), NOW()), ('8159934', NULL, 'Port Noarlunga Aquatic Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.15296, 138.46394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port noarlunga aquatic reserve port noarlunga aquatic reserve australia au port noarlunga aquatic reserve',
    NOW(), NOW()), ('8159938', NULL, 'Point Davenport Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.16043, 137.33449, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point davenport conservation park point davenport conservation park australia au point davenport conservation park',
    NOW(), NOW()), ('8159956', NULL, 'Port Broughton Caravan Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.60678, 137.92839, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton caravan park port broughton caravan park australia au port broughton caravan park',
    NOW(), NOW()), ('8159989', NULL, 'Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.54744, 138.5925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter reserve porter reserve australia au porter reserve',
    NOW(), NOW()), ('8159996', NULL, 'Philips Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.88145, 138.51852, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'philips sports field philips sports field australia au philips sports field',
    NOW(), NOW()), ('8160017', NULL, 'Olympic Park Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.83283, 140.77457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic park sports field olympic park sports field australia au olympic park sports field',
    NOW(), NOW()), ('8160081', NULL, 'Patterson Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.89301, 138.64343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'patterson sportsground patterson sportsground australia au patterson sportsground',
    NOW(), NOW()), ('8160110', NULL, 'Porter Scrub Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.86496, 138.90778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter scrub conservation park porter scrub conservation park australia au porter scrub conservation park',
    NOW(), NOW()), ('8160138', NULL, 'Newton Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.88373, 138.68986, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newton sports ground newton sports ground australia au newton sports ground',
    NOW(), NOW()), ('8160169', NULL, 'Port Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.19245, 138.00926, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port oval port oval australia au port oval',
    NOW(), NOW()), ('8160195', NULL, 'New Town Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.85, 147.28999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'new town sports ground new town sports ground australia au new town sports ground',
    NOW(), NOW()), ('8160201', NULL, 'North Chigwell Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.8, 147.24001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north chigwell sports ground north chigwell sports ground australia au north chigwell sports ground',
    NOW(), NOW()), ('8160204', NULL, 'North Hobart Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.86, 147.31, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north hobart sports ground north hobart sports ground australia au north hobart sports ground',
    NOW(), NOW()), ('8160245', NULL, 'Pierces Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.92, 147.35001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierces reserve pierces reserve australia au pierces reserve',
    NOW(), NOW()), ('8160246', NULL, 'Piersons Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.05, 147.34, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piersons park piersons park australia au piersons park',
    NOW(), NOW()), ('8160253', NULL, 'Police Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.23, 146.39999, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'police paddock police paddock australia au police paddock',
    NOW(), NOW()), ('8160254', NULL, 'Port Cygnet Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.17, 147.08, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port cygnet conservation area port cygnet conservation area australia au port cygnet conservation area',
    NOW(), NOW()), ('8160255', NULL, 'Port Sorell Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.17, 146.53999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port sorell conservation area port sorell conservation area australia au port sorell conservation area',
    NOW(), NOW()), ('8160277', NULL, 'Ravenswood Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.41, 147.16, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ravenswood sports ground ravenswood sports ground australia au ravenswood sports ground',
    NOW(), NOW()), ('8160317', NULL, 'Royal Derwent Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.78, 147.06, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'royal derwent sports ground royal derwent sports ground australia au royal derwent sports ground',
    NOW(), NOW()), ('8160349', NULL, 'Port Arthur Historic Site', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.15, 147.84, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port arthur historic site port arthur historic site australia au port arthur historic site',
    NOW(), NOW()), ('8160388', NULL, 'Portsea Recreation Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.32458, 144.71542, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portsea recreation reserve portsea recreation reserve australia au portsea recreation reserve',
    NOW(), NOW()), ('8160391', NULL, 'Port Campbell National Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.64144, 143.06813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port campbell national park port campbell national park australia au port campbell national park',
    NOW(), NOW()), ('8160587', NULL, 'Port Hedland Community Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.3081, 118.6055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hedland community park port hedland community park australia au port hedland community park',
    NOW(), NOW()), ('8160588', NULL, 'Port Kennedy Scientific Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.36306, 115.7097, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kennedy scientific park port kennedy scientific park australia au port kennedy scientific park',
    NOW(), NOW()), ('8160589', NULL, 'Portmarnock Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.53528, 115.6978, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portmarnock reserve portmarnock reserve australia au portmarnock reserve',
    NOW(), NOW()), ('8160815', NULL, 'Shellharbour Municipality War Memorial Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour municipality war memorial park shellharbour municipality war memorial park australia au shellharbour municipality war memorial park',
    NOW(), NOW()), ('8160816', NULL, 'Shellharbour Pioneer Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5818, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour pioneer park shellharbour pioneer park australia au shellharbour pioneer park',
    NOW(), NOW()), ('8160817', NULL, 'Shellharbour War Memorial Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour war memorial park shellharbour war memorial park australia au shellharbour war memorial park',
    NOW(), NOW()), ('8160891', NULL, 'Uki Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.4152, 153.3346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uki sports oval uki sports oval australia au uki sports oval',
    NOW(), NOW()), ('8161070', NULL, 'Tenambit Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7457, 151.6123, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tenambit sports area tenambit sports area australia au tenambit sports area',
    NOW(), NOW()), ('8161118', NULL, 'Victoria Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.6985, 147.8346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'victoria sports oval victoria sports oval australia au victoria sports oval',
    NOW(), NOW()), ('8161141', NULL, 'Wimbo Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.88112, 151.20076, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wimbo paddock wimbo paddock australia au wimbo paddock',
    NOW(), NOW()), ('8161150', NULL, 'Wellington Show and Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5485, 148.91789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wellington show and sports ground wellington show and sports ground australia au wellington show and sports ground',
    NOW(), NOW()), ('8161222', NULL, 'Sydney Cricket and Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.89351, 151.22704, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sydney cricket and sports ground sydney cricket and sports ground australia au sydney cricket and sports ground',
    NOW(), NOW()), ('8161243', NULL, 'West Guildford Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 150.9512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west guildford sports centre west guildford sports centre australia au west guildford sports centre',
    NOW(), NOW()), ('8161287', NULL, 'The Boiler Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 150.894, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the boiler paddock the boiler paddock australia au the boiler paddock',
    NOW(), NOW()), ('8161603', NULL, 'Tuncurry Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.1652, 152.4846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tuncurry sports centre tuncurry sports centre australia au tuncurry sports centre',
    NOW(), NOW()), ('8161814', NULL, 'War Memorial Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.8485, 153.4429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'war memorial sportsground war memorial sportsground australia au war memorial sportsground',
    NOW(), NOW()), ('8161879', NULL, 'West End Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5818, 149.55119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west end sporting complex west end sporting complex australia au west end sporting complex',
    NOW(), NOW()), ('8161883', NULL, 'Wharf Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.15961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wharf reserve wharf reserve australia au wharf reserve',
    NOW(), NOW()), ('8161954', NULL, 'Woodberry Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7985, 151.6512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woodberry sports centre woodberry sports centre australia au woodberry sports centre',
    NOW(), NOW()), ('8161977', NULL, 'Wright Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3485, 149.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wright sportsground wright sportsground australia au wright sportsground',
    NOW(), NOW()), ('8162025', NULL, 'Westport Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4152, 152.9012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'westport park westport park australia au westport park',
    NOW(), NOW());