INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12508664', NULL, 'Aeroporto Brigadeiro Araripe Macedo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.2617, -47.9688, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto brigadeiro araripe macedo aeroporto brigadeiro araripe macedo brazil br aeroporto brigadeiro araripe macedo',
    NOW(), NOW()), ('12508672', NULL, 'Aeroporto Santa Rita do Araguaia', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.3208, -53.1939, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto santa rita do araguaia aeroporto santa rita do araguaia brazil br aeroporto santa rita do araguaia',
    NOW(), NOW()), ('12508683', NULL, 'Aeroporto Cristalina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.791, -47.6448, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto cristalina aeroporto cristalina brazil br aeroporto cristalina',
    NOW(), NOW()), ('12512248', NULL, 'Aeroporto de Camapuã', 'Aeroporto de Camapua',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.59847, -54.0209, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto de camapuã aeroporto de camapua brazil br aeroporto de camapua,aeroporto de camapuã',
    NOW(), NOW()), ('12512283', NULL, 'Aeroporto Orlando Chesini Ometto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.0996, -56.7937, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto orlando chesini ometto aeroporto orlando chesini ometto brazil br aeroporto orlando chesini ometto',
    NOW(), NOW()), ('12512285', NULL, 'Aeródromo Porto Walter', 'Aerodromo Porto Walter',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.2752, -72.7457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo porto walter aerodromo porto walter brazil br aerodromo porto walter,aeródromo porto walter',
    NOW(), NOW()), ('12512288', NULL, 'Aeroporto Calçoene', 'Aeroporto Calcoene',
    NULL, 'BR', 'Brazil', NULL, NULL,
    2.49793, -50.96217, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto calçoene aeroporto calcoene brazil br aeroporto calcoene,aeroporto calçoene',
    NOW(), NOW()), ('12512331', NULL, 'Aeroporto Caracaraí', 'Aeroporto Caracarai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    1.84462, -61.12143, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto caracaraí aeroporto caracarai brazil br aeroporto caracarai,aeroporto caracaraí',
    NOW(), NOW()), ('12512338', NULL, 'Aeroporto Teruel Ipanema Estância', 'Aeroporto Teruel Ipanema Estancia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.60406, -54.59553, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto teruel ipanema estância aeroporto teruel ipanema estancia brazil br aeroporto teruel ipanema estancia,aeroporto teruel ipanema estância',
    NOW(), NOW()), ('12512406', NULL, 'Aeródromo Porto Bonito', 'Aerodromo Porto Bonito',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.3441, -53.8723, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo porto bonito aerodromo porto bonito brazil br aerodromo porto bonito,aeródromo porto bonito',
    NOW(), NOW()), ('12512416', NULL, 'Aeroporto General Canrobert Pereira da Costa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.45233, -55.75751, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto general canrobert pereira da costa aeroporto general canrobert pereira da costa brazil br aeroporto general canrobert pereira da costa',
    NOW(), NOW()), ('12512450', NULL, 'Aeroporto Fazenda Campo Verde/Cutias', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    1.04201, -50.51768, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto fazenda campo verde/cutias aeroporto fazenda campo verde/cutias brazil br aeroporto fazenda campo verde/cutias',
    NOW(), NOW()), ('12512488', NULL, 'Aeroporto Bela Vista', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.0815, -56.5386, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto bela vista aeroporto bela vista brazil br aeroporto bela vista',
    NOW(), NOW()), ('12512491', NULL, 'Aeroporto Nioaque', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.184, -55.8311, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto nioaque aeroporto nioaque brazil br aeroporto nioaque',
    NOW(), NOW()), ('12512519', NULL, 'Aeroporto Jardim', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.493, -56.1523, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto jardim aeroporto jardim brazil br aeroporto jardim',
    NOW(), NOW()), ('12512549', NULL, 'Aeródromo Porto Carcará', 'Aerodromo Porto Carcara',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.8335, -57.1668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo porto carcará aerodromo porto carcara brazil br aerodromo porto carcara,aeródromo porto carcará',
    NOW(), NOW()), ('12512596', NULL, 'Aeródromo Frigorífico Santa Marina', 'Aerodromo Frigorifico Santa Marina',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.74414, -52.48088, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo frigorífico santa marina aerodromo frigorifico santa marina brazil br aerodromo frigorifico santa marina,aeródromo frigorífico santa marina',
    NOW(), NOW()), ('12512625', NULL, 'Aeroporto Ariosto da Riva', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0344, -54.1789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto ariosto da riva aeroporto ariosto da riva brazil br aeroporto ariosto da riva',
    NOW(), NOW()), ('12512672', NULL, 'Aeródromo Porto Índio', 'Aerodromo Porto Indio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.02089, -56.82506, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo porto índio aerodromo porto indio brazil br aerodromo porto indio,aeródromo porto índio',
    NOW(), NOW()), ('12512678', NULL, 'Aeroporto de Coxim', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.47849, -54.71477, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto de coxim aeroporto de coxim brazil br aeroporto de coxim',
    NOW(), NOW()), ('12512685', NULL, 'Aeroporto Estância Santa Maria', 'Aeroporto Estancia Santa Maria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.50421, -54.52402, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto estância santa maria aeroporto estancia santa maria brazil br aeroporto estancia santa maria,aeroporto estância santa maria',
    NOW(), NOW()), ('12512689', NULL, 'Aeroporto Porto Murtinho', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.7114, -57.8796, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto porto murtinho aeroporto porto murtinho brazil br aeroporto porto murtinho',
    NOW(), NOW()), ('12512796', NULL, 'Aeroporto de Costa Rica', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.4913, -53.1684, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto de costa rica aeroporto de costa rica brazil br aeroporto de costa rica',
    NOW(), NOW()), ('12512842', NULL, 'Aeródromo Itapará Sport Fishing', 'Aerodromo Itapara Sport Fishing',
    NULL, 'BR', 'Brazil', NULL, NULL,
    0.20895, -61.54609, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo itapará sport fishing aerodromo itapara sport fishing brazil br aerodromo itapara sport fishing,aeródromo itapará sport fishing',
    NOW(), NOW()), ('12512850', NULL, 'Aeródromo Fazenda Porto Oculto', 'Aerodromo Fazenda Porto Oculto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.2111, -54.0958, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo fazenda porto oculto aerodromo fazenda porto oculto brazil br aerodromo fazenda porto oculto,aeródromo fazenda porto oculto',
    NOW(), NOW()), ('12512856', NULL, 'Aeroporto Chapadão do Sul', 'Aeroporto Chapadao do Sul',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.8391, -52.4883, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto chapadão do sul aeroporto chapadao do sul brazil br aeroporto chapadao do sul,aeroporto chapadão do sul',
    NOW(), NOW()), ('12512875', NULL, 'Aeroporto de Saquarema', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.92939, -42.5045, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto de saquarema aeroporto de saquarema brazil br aeroporto de saquarema',
    NOW(), NOW()), ('12512916', NULL, 'Cemitério Parque Portal da Saudade', 'Cemiterio Parque Portal da Saudade',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.5239, -44.0758, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cemitério parque portal da saudade cemiterio parque portal da saudade brazil br cemiterio parque portal da saudade,cemitério parque portal da saudade',
    NOW(), NOW()), ('12512980', NULL, 'Pista de Pouso da Fazenda Portobello', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.92606, -44.08001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pista de pouso da fazenda portobello pista de pouso da fazenda portobello brazil br pista de pouso da fazenda portobello',
    NOW(), NOW()), ('12519279', NULL, 'Paracatu Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.24144, -46.88602, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paracatu airport paracatu airport brazil br pyt,snzr',
    NOW(), NOW()), ('12519286', NULL, 'Aeroporto Regional de Lavras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.23993, -44.96477, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto regional de lavras aeroporto regional de lavras brazil br vrz',
    NOW(), NOW()), ('12519390', NULL, 'Mucugê Airport', 'Mucuge Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.03208, -41.44539, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mucugê airport mucuge airport brazil br chd,snqu',
    NOW(), NOW()), ('12530901', NULL, 'Seringal Porto Seguro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.48978, -66.32408, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'seringal porto seguro seringal porto seguro brazil br seringal porto seguro',
    NOW(), NOW()), ('12532087', NULL, 'Porto Colônia', 'Porto Colonia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.39561, -49.84668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto colônia porto colonia brazil br porto colonia,porto colônia',
    NOW(), NOW()), ('12532458', NULL, 'Corumbá', 'Corumba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.99656, -57.65336, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'corumbá corumba brazil br corumba,corumbá',
    NOW(), NOW()), ('12532520', NULL, 'Porto Carrero', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.94621, -56.87957, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto carrero porto carrero brazil br porto carrero',
    NOW(), NOW()), ('12532532', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.48471, -55.69789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12532540', NULL, 'Ilha Porto Carreiro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.9282, -57.8002, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilha porto carreiro ilha porto carreiro brazil br ilha porto carreiro',
    NOW(), NOW()), ('12533717', NULL, 'Porto dos Tatus', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.83121, -41.82679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto dos tatus porto dos tatus brazil br porto dos tatus',
    NOW(), NOW()), ('12533748', NULL, 'Rio Porto de Areia', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.76923, -42.25829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rio porto de areia rio porto de areia brazil br rio porto de areia',
    NOW(), NOW()), ('12533783', NULL, 'Lagoa da Porta', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.08291, -41.87253, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lagoa da porta lagoa da porta brazil br lagoa da porta',
    NOW(), NOW()), ('12533796', NULL, 'Lagoa do Jiquiri da Porta', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.21049, -41.9372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lagoa do jiquiri da porta lagoa do jiquiri da porta brazil br lagoa do jiquiri da porta',
    NOW(), NOW()), ('12541304', NULL, 'Cajazeiras Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.88137, -38.61828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cajazeiras airport cajazeiras airport brazil br cjz,sjza',
    NOW(), NOW()), ('12541307', NULL, 'Barra Grande Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.90523, -38.93314, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barra grande airport barra grande airport brazil br muu,siri',
    NOW(), NOW()), ('12541721', NULL, 'Manhuacu Elias Breder Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.26406, -42.18286, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manhuacu elias breder airport manhuacu elias breder airport brazil br jma,snjm',
    NOW(), NOW()), ('12542172', NULL, 'Porteira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.99199, -35.51031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteira porteira brazil br porteira',
    NOW(), NOW()), ('12542294', NULL, 'Porto Mirim', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.57583, -35.23661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto mirim porto mirim brazil br porto mirim',
    NOW(), NOW()), ('12542318', NULL, 'Aeroporto Ceará-Mirim', 'Aeroporto Ceara-Mirim',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.66057, -35.41434, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto ceará-mirim aeroporto ceara-mirim brazil br aeroporto ceara-mirim,aeroporto ceará-mirim',
    NOW(), NOW()), ('12542531', NULL, 'Aeroporto Pedro Simões Pimenta', 'Aeroporto Pedro Simoes Pimenta',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.48588, -36.13735, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto pedro simões pimenta aeroporto pedro simoes pimenta brazil br aeroporto pedro simoes pimenta,aeroporto pedro simões pimenta',
    NOW(), NOW()), ('12543347', NULL, 'Riacho da Porta', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.74077, -39.27614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'riacho da porta riacho da porta brazil br riacho da porta',
    NOW(), NOW());