INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('5883472', NULL, 'Alexandra Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.55011, -88.45003, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'alexandra harbour alexandra harbour canada ca',
    NOW(), NOW()), ('5883864', NULL, 'Alle Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    58.81721, -78.54948, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'alle harbour alle harbour canada ca',
    NOW(), NOW()), ('5883943', NULL, 'Allen Rapids Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.8834, -78.81629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'allen rapids portage allen rapids portage canada ca',
    NOW(), NOW()), ('5884032', NULL, 'Allison Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.04782, -127.51299, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'allison harbour allison harbour canada ca',
    NOW(), NOW()), ('5884143', NULL, 'Along the Rock Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    55.51154, -99.31619, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'along the rock portage along the rock portage canada ca',
    NOW(), NOW()), ('5884204', NULL, 'Alport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.02235, -79.35354, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alport alport canada ca',
    NOW(), NOW()), ('5884205', NULL, 'Alport Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.02111, -79.38583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alport lake alport lake canada ca',
    NOW(), NOW()), ('5884411', NULL, 'American Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.25015, -61.31523, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'american harbour american harbour canada ca',
    NOW(), NOW()), ('5884412', NULL, 'American Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    66.26742, -66.56403, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'american harbour american harbour canada ca',
    NOW(), NOW()), ('5884456', NULL, 'Amethyst Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.54267, -88.87291, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'amethyst harbour amethyst harbour canada ca',
    NOW(), NOW()), ('5884457', NULL, 'Amethyst Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.5501, -88.88339, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'amethyst harbour amethyst harbour canada ca',
    NOW(), NOW()), ('5884475', NULL, 'Amherstburg Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    42.10009, -83.11655, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'amherstburg harbour amherstburg harbour canada ca',
    NOW(), NOW()), ('5884648', NULL, 'Amusk Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    56.71305, -98.64231, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amusk portage amusk portage canada ca',
    NOW(), NOW()), ('5884721', NULL, 'Anarnittuq Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    66.33822, -66.91406, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'anarnittuq harbour anarnittuq harbour canada ca',
    NOW(), NOW()), ('5885234', NULL, 'Anglers Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.9668, -78.99959, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anglers portage anglers portage canada ca',
    NOW(), NOW()), ('5885260', NULL, 'Angmallik Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    64.4839, -65.34729, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'angmallik harbour angmallik harbour canada ca',
    NOW(), NOW()), ('5885406', NULL, 'Anna Maria Port', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    63.73389, -67.88102, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anna maria port anna maria port canada ca',
    NOW(), NOW()), ('5885427', NULL, 'Ann Bay Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.08835, -91.73915, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ann bay portage ann bay portage canada ca',
    NOW(), NOW()), ('5885664', NULL, 'Anse à Pierre-Francis', 'Anse a Pierre-Francis',
    NULL, 'CA', 'Canada', NULL, NULL,
    50.26844, -64.82573, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse à pierre-francis anse a pierre-francis canada ca',
    NOW(), NOW()), ('5885789', NULL, 'Anse de la Maison de Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.06682, -58.81493, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse de la maison de pierre anse de la maison de pierre canada ca',
    NOW(), NOW()), ('5885818', NULL, 'Anse de Mont-Saint-Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.23339, -65.79876, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse de mont-saint-pierre anse de mont-saint-pierre canada ca',
    NOW(), NOW()), ('5885858', NULL, 'Anse des Lapierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.26682, -64.76544, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse des lapierre anse des lapierre canada ca',
    NOW(), NOW()), ('5885918', NULL, 'Anse du Port', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.26506, -72.62852, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse du port anse du port canada ca',
    NOW(), NOW()), ('5885919', NULL, 'Anse du Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.23341, -58.28149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse du portage anse du portage canada ca',
    NOW(), NOW()), ('5885920', NULL, 'Anse du Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.26682, -64.84874, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse du portage anse du portage canada ca',
    NOW(), NOW()), ('5885921', NULL, 'Anse du Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.43341, -57.76486, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse du portage anse du portage canada ca',
    NOW(), NOW()), ('5885922', NULL, 'Anse du Portage Sainte-Marguerite', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.16371, -66.50629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'anse du portage sainte-marguerite anse du portage sainte-marguerite canada ca',
    NOW(), NOW()), ('5886129', NULL, 'Antelope Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.0001, -55.84798, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'antelope harbour antelope harbour canada ca',
    NOW(), NOW()), ('5886186', NULL, 'Antigonish Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.71637, -61.90785, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'antigonish harbour antigonish harbour canada ca acarsaid antigonis,antigonish,antigonish harbour,антіґоніш',
    NOW(), NOW()), ('5886187', NULL, 'Antigonish Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.65015, -61.91528, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'antigonish harbour antigonish harbour canada ca',
    NOW(), NOW()), ('5886332', NULL, 'Apeetakamuskakwak Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    54.26491, -93.44571, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'apeetakamuskakwak portage apeetakamuskakwak portage canada ca',
    NOW(), NOW()), ('5886343', NULL, 'Apeschaw Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    56.48524, -96.15229, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'apeschaw portage apeschaw portage canada ca',
    NOW(), NOW()), ('5886512', NULL, 'Aquaforte Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.99989, -52.93136, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'aquaforte harbour aquaforte harbour canada ca',
    NOW(), NOW()), ('5886714', NULL, 'Archipel du Lac Saint-Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.09926, -73.06604, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'archipel du lac saint-pierre archipel du lac saint-pierre canada ca archipel du lac saint-pierre,lac saint-pierre takimadasi,lac saint-pierre takımadası,archipel du lac saint-pierre,san=pieru hu zhu dao,サン＝ピエール湖諸島',
    NOW(), NOW()), ('5886737', NULL, 'Arctic Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    69.51771, -67.53026, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'arctic harbour arctic harbour canada ca',
    NOW(), NOW()), ('5886825', NULL, 'Argentia Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.2999, -53.98143, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'argentia harbour argentia harbour canada ca',
    NOW(), NOW()), ('5886896', NULL, 'Arichat Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.51684, -61.01521, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'arichat harbour arichat harbour canada ca',
    NOW(), NOW()), ('5887022', NULL, 'Armour Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.7501, -87.85001, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'armour harbour armour harbour canada ca',
    NOW(), NOW()), ('5887225', NULL, 'Arpiers', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.95007, -105.78448, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arpiers arpiers canada ca',
    NOW(), NOW()), ('5887559', NULL, 'Ashigami Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.67648, -80.56031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ashigami portage ashigami portage canada ca',
    NOW(), NOW()), ('5887757', NULL, 'Aspotogan Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.51628, -64.04291, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'aspotogan harbour aspotogan harbour canada ca',
    NOW(), NOW()), ('5887823', NULL, 'Assizes Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.26267, -55.6901, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'assizes harbour assizes harbour canada ca',
    NOW(), NOW()), ('5887827', NULL, 'Assomption Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    71.96801, -80.76532, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'assomption harbour assomption harbour canada ca',
    NOW(), NOW()), ('5888574', NULL, 'Avonport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.10015, -64.24875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'avonport avonport canada ca',
    NOW(), NOW()), ('5888575', NULL, 'Avonport Station', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.11021, -64.24825, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'avonport station avonport station canada ca',
    NOW(), NOW()), ('5888917', NULL, 'Back Bay Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.05837, -66.86296, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'back bay harbour back bay harbour canada ca',
    NOW(), NOW()), ('5889014', NULL, 'Back Dock', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.64709, -53.20368, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'back dock back dock canada ca',
    NOW(), NOW()), ('5889020', NULL, 'Back Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.66662, -54.78146, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'back harbour back harbour canada ca',
    NOW(), NOW()), ('5889021', NULL, 'Back Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.45009, -55.73128, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'back harbour back harbour canada ca',
    NOW(), NOW()), ('5889022', NULL, 'Back Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.66662, -54.78146, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'back harbour back harbour canada ca',
    NOW(), NOW());