INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('13013177', NULL, 'Canal da Portuguesa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7999, -43.20771, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal da portuguesa canal da portuguesa brazil br canal da portuguesa',
    NOW(), NOW()), ('13013504', NULL, 'Sítio Porto da Canoa', 'Sitio Porto da Canoa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.43424, -44.34794, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto da canoa sitio porto da canoa brazil br sitio porto da canoa,sítio porto da canoa',
    NOW(), NOW()), ('13014064', NULL, 'Marina Verolme', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9986, -44.249, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina verolme marina verolme brazil br marina verolme',
    NOW(), NOW()), ('13014096', NULL, 'Sítio Porteira Azul', 'Sitio Porteira Azul',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8989, -44.3189, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porteira azul sitio porteira azul brazil br sitio porteira azul,sítio porteira azul',
    NOW(), NOW()), ('13014104', NULL, 'Fazenda do Português', 'Fazenda do Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8694, -44.2637, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda do português fazenda do portugues brazil br fazenda do portugues,fazenda do português',
    NOW(), NOW()), ('13014116', NULL, 'Hotel Portobello', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.94964, -44.07516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel portobello hotel portobello brazil br hotel portobello',
    NOW(), NOW()), ('13014355', NULL, 'Sítio Porto de Areia', 'Sitio Porto de Areia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7801, -44.1594, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto de areia sitio porto de areia brazil br sitio porto de areia,sítio porto de areia',
    NOW(), NOW()), ('13014403', NULL, 'Porto Frade', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.97014, -44.44456, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto frade porto frade brazil br porto frade',
    NOW(), NOW()), ('13014598', NULL, 'Porto São Francisco', 'Porto Sao Francisco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0253, -45.6727, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto são francisco porto sao francisco brazil br porto sao francisco,porto são francisco',
    NOW(), NOW()), ('13015161', NULL, 'Córrego da Marina', 'Corrego da Marina',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.2823, -44.78292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego da marina corrego da marina brazil br corrego da marina,córrego da marina',
    NOW(), NOW()), ('13016103', NULL, 'Fazenda Zé Português', 'Fazenda Ze Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63558, -43.38597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda zé português fazenda ze portugues brazil br fazenda ze portugues,fazenda zé português',
    NOW(), NOW()), ('13016129', NULL, 'Sítio Três Porteiras', 'Sitio Tres Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.39748, -43.4211, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio três porteiras sitio tres porteiras brazil br sitio tres porteiras,sítio três porteiras',
    NOW(), NOW()), ('13016329', NULL, 'Córrego do Porto', 'Corrego do Porto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.002, -43.34657, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego do porto corrego do porto brazil br corrego do porto,córrego do porto',
    NOW(), NOW()), ('13016418', NULL, 'Fazenda Porto Velho', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.20952, -43.45756, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto velho fazenda porto velho brazil br fazenda porto velho',
    NOW(), NOW()), ('13016420', NULL, 'Três Porteiras', 'Tres Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.39531, -43.42574, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'três porteiras tres porteiras brazil br tres porteiras,três porteiras',
    NOW(), NOW()), ('13016722', NULL, 'Porteirinha', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.44931, -43.87099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteirinha porteirinha brazil br porteirinha',
    NOW(), NOW()), ('13016786', NULL, 'Sítio Três Porteiras', 'Sitio Tres Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.0926, -43.7194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio três porteiras sitio tres porteiras brazil br sitio tres porteiras,sítio três porteiras',
    NOW(), NOW()), ('13017591', NULL, 'Sítio da Porteira Preta', 'Sitio da Porteira Preta',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.41269, -43.62425, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio da porteira preta sitio da porteira preta brazil br sitio da porteira preta,sítio da porteira preta',
    NOW(), NOW()), ('13017816', NULL, 'Sítio Santa Maria Cilândia Portela', 'Sitio Santa Maria Cilandia Portela',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.47304, -43.52091, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio santa maria cilândia portela sitio santa maria cilandia portela brazil br sitio santa maria cilandia portela,sítio santa maria cilândia portela',
    NOW(), NOW()), ('13018052', NULL, 'Sítio Porteira Azul', 'Sitio Porteira Azul',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.34898, -43.10886, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porteira azul sitio porteira azul brazil br sitio porteira azul,sítio porteira azul',
    NOW(), NOW()), ('13019245', NULL, 'Porteira Verde', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.03879, -42.66613, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteira verde porteira verde brazil br porteira verde',
    NOW(), NOW()), ('13019770', NULL, 'Ponta do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9587, -43.90691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ponta do porto ponta do porto brazil br ponta do porto',
    NOW(), NOW()), ('13019921', NULL, 'Sítio Porto Esperança', 'Sitio Porto Esperanca',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.82034, -43.71225, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto esperança sitio porto esperanca brazil br sitio porto esperanca,sítio porto esperança',
    NOW(), NOW()), ('13020100', NULL, 'Córrego Porto Seguro', 'Corrego Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.89825, -50.39453, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porto seguro corrego porto seguro brazil br corrego porto seguro,córrego porto seguro',
    NOW(), NOW()), ('13020460', NULL, 'Porto Taquari', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.47941, -49.16056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto taquari porto taquari brazil br porto taquari',
    NOW(), NOW()), ('13020772', NULL, 'Quilombo Porto dos Pilões', 'Quilombo Porto dos Piloes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.48584, -48.48319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quilombo porto dos pilões quilombo porto dos piloes brazil br quilombo porto dos piloes,quilombo porto dos pilões',
    NOW(), NOW()), ('13021237', NULL, 'Córrego Porteiras', 'Corrego Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.15663, -43.97185, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteiras corrego porteiras brazil br corrego porteiras,córrego porteiras',
    NOW(), NOW()), ('13022067', NULL, 'Fazenda Porto Feliz', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.34435, -48.80917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto feliz fazenda porto feliz brazil br fazenda porto feliz',
    NOW(), NOW()), ('13022985', NULL, 'Serra do Português', 'Serra do Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.80342, -42.43391, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra do português serra do portugues brazil br serra do portugues,serra do português',
    NOW(), NOW()), ('13023019', NULL, 'Córrego Português', 'Corrego Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.81608, -42.45188, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego português corrego portugues brazil br corrego portugues,córrego português',
    NOW(), NOW()), ('13023318', NULL, 'Sítio Porto do Surubi', 'Sitio Porto do Surubi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.79626, -42.46979, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porto do surubi sitio porto do surubi brazil br sitio porto do surubi,sítio porto do surubi',
    NOW(), NOW()), ('13023636', NULL, 'Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.77749, -39.97626, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portela portela brazil br portela',
    NOW(), NOW()), ('13023753', NULL, 'Porto Tiririca', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.10583, -39.58963, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto tiririca porto tiririca brazil br porto tiririca',
    NOW(), NOW()), ('13024775', NULL, 'Praia do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.42282, -48.5676, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'praia do porto praia do porto brazil br praia do porto',
    NOW(), NOW()), ('13024832', NULL, 'Arroio da Porteira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.9692, -51.744, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroio da porteira arroio da porteira brazil br arroio da porteira',
    NOW(), NOW()), ('13025058', NULL, 'Portão-Boa Vista', 'Portao-Boa Vista',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.72433, -51.25797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portão-boa vista portao-boa vista brazil br portao-boa vista,portão-boa vista',
    NOW(), NOW()), ('13025059', NULL, 'Porto da Figueira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.81993, -51.34707, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da figueira porto da figueira brazil br porto da figueira',
    NOW(), NOW()), ('13025060', NULL, 'Porto de Estrela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.4741, -51.96023, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de estrela porto de estrela brazil br estrela,porto de estrela',
    NOW(), NOW()), ('13025061', NULL, 'Porto Maratá', 'Porto Marata',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.66933, -51.42691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto maratá porto marata brazil br porto marata,porto maratá',
    NOW(), NOW()), ('13025097', NULL, 'Terminal de Carvão de Charqueadas', 'Terminal de Carvao de Charqueadas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.9493, -51.62023, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de carvão de charqueadas terminal de carvao de charqueadas brazil br terminal de carvao de charqueadas,terminal de carvão de charqueadas',
    NOW(), NOW()), ('13025098', NULL, 'Terminal de Uso Privado Copelmi', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.94953, -51.62427, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de uso privado copelmi terminal de uso privado copelmi brazil br terminal de uso privado copelmi',
    NOW(), NOW()), ('13025099', NULL, 'Terminal Mita', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.81004, -51.86529, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal mita terminal mita brazil br terminal mita',
    NOW(), NOW()), ('13025100', NULL, 'Terminal Moinho Taquariense', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.8061, -51.87197, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal moinho taquariense terminal moinho taquariense brazil br terminal moinho taquariense',
    NOW(), NOW()), ('13025101', NULL, 'Terminal Santa Clara', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.9033, -51.3728, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal santa clara terminal santa clara brazil br terminal santa clara',
    NOW(), NOW()), ('13025124', NULL, 'Terminal Aquaviário de Niterói', 'Terminal Aquaviario de Niteroi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.9672, -51.1791, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal aquaviário de niterói terminal aquaviario de niteroi brazil br terminal aquaviario de niteroi,terminal aquaviário de niterói',
    NOW(), NOW()), ('13025125', NULL, 'Terminal de Uso Privado Bianchini Canoas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.91466, -51.23875, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de uso privado bianchini canoas terminal de uso privado bianchini canoas brazil br terminal de uso privado bianchini canoas',
    NOW(), NOW()), ('13025126', NULL, 'Terminal de Uso Privado Oleoplan', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.96813, -51.18277, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de uso privado oleoplan terminal de uso privado oleoplan brazil br terminal de uso privado oleoplan',
    NOW(), NOW()), ('13025127', NULL, 'Terminal de Uso Privado SHV', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.96787, -51.20315, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de uso privado shv terminal de uso privado shv brazil br terminal de uso privado shv',
    NOW(), NOW()), ('13025128', NULL, 'Terminal de Uso Privado Tergasul', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.9665, -51.2035, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de uso privado tergasul terminal de uso privado tergasul brazil br terminal de uso privado tergasul',
    NOW(), NOW()), ('13025275', NULL, 'Arroio Portão', 'Arroio Portao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.77561, -51.19318, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroio portão arroio portao brazil br arroio portao,arroio portão,arroio do portao,arroio do portão',
    NOW(), NOW());