INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3183874', NULL, 'Tirana International Airport Nënë Tereza', 'Tirana International Airport Nene Tereza',
    NULL, 'AL', 'AL', NULL, NULL,
    41.4219, 19.71296, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'tirana international airport nënë tereza tirana international airport nene tereza al al aerodrom tirana,aeroport international de tirana,aeroporti nderkombetar i tiranes nene tereza,aeroporti ndërkombëtar i tiranës nënë tereza,aeroporti nene tereza,aeroporti nënë tereza,aeroporti i tiranes,aeroporti i tiranës,aeroporto di tirana-rinas,aeropuerto internacional madre teresa,aéroport international de tirana,bandar udara rinas nene tereza,bandar udara rinas nënë tereza,flughafen tirana,lati,lapangan terbang nene tereza,lapangan terbang nënë tereza,letiste tirana,letiště tirana,luchthaven tirana,mizhnarodnij aeroport tirani,moder teresa internasjonale lufthavn,nene terezan kansainvaelinen lentoasema,nënë terezan kansainvälinen lentoasema,port lotniczy rinas,rinas international airport,rinas internationella flygplats,san bay quoc te tirana nene tereza,sân bay quốc tế tirana nënë tereza,tia,terez anya repueloter,teréz anya repülőtér,tiran uluslararasi havalimani,tiran uluslararası havalimanı,tirana,tirana internacia flughaveno patrino teresa,tirana international airport nene tereza,tirana international airport nënë tereza,tirana flygplats,tirana internasjonale lufthamn,tirana lennujaam,tiranako nazioarteko aireportua,tiranas internationella flygplats moder teresa,de la na te lei sha xiu nu guo ji ji chang,mtar tyrana aldwly,аеродром тирана,міжнародний аеропорт тирани,тирана,фурудгоҳи бин‌алмилалӣ модар трз тироно,נמל התעופה האם תרזה,فرودگاه بین‌المللی مادر ترزای تیرانا,مطار تيرانا الدولي,ティラナ・リナ空港,地拉那特蕾莎修女國際機場',
    NOW(), NOW()), ('3183876', NULL, 'Tirana Military Heliport', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.31332, 19.88279, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tirana military heliport tirana military heliport al al tirana military heliport,tirane',
    NOW(), NOW()), ('3184114', NULL, 'Sheq-Marinas', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.77502, 19.42819, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sheq-marinas sheq-marinas al al marina sheq,marinas mesheq,marinas mesheqi,marine sheqi,marinë sheqi,seci marins,seči marins,sheq-marinas,sheq-marinasi,sheq-marines',
    NOW(), NOW()), ('3184299', NULL, 'Gjiri i Rodonit', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.61482, 19.56675, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gjiri i rodonit gjiri i rodonit al al baia di rodoni,gji i rodonit,gjiri i rodonit,liman rodoni,luka rodoni,rada di rodoni,reede rodoni,rodoni roads',
    NOW(), NOW()), ('3184343', NULL, 'Gjiu Rogozhës', 'Gjiu Rogozhes',
    NULL, 'AL', 'AL', NULL, NULL,
    40.35621, 19.40801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gjiu rogozhës gjiu rogozhes al al bucht raguzeo,gji raguzeo,gji i ragunit,gjiu rogozhes,gjiu rogozhës,liman rajcekos,liman rajcëkos,ormos raguzeos,raguseo cove,raguzeo,raguzeo cove,zaliv raguzeo',
    NOW(), NOW()), ('3184419', NULL, 'Porto-Romano', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.36667, 19.42889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto-romano porto-romano al al porta romana,porto-romano',
    NOW(), NOW()), ('3184420', NULL, 'Portëz', 'Portez',
    NULL, 'AL', 'AL', NULL, NULL,
    40.69917, 19.57444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portëz portez al al portez,porteza,porteze,portëz,portëza,portëzë',
    NOW(), NOW()), ('3184421', NULL, 'Kodra e Portës', 'Kodra e Portes',
    NULL, 'AL', 'AL', NULL, NULL,
    41.37056, 19.42111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kodra e portës kodra e portes al al',
    NOW(), NOW()), ('3184533', NULL, 'Liqeni i Pasha-Limanit', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.31744, 19.44123, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'liqeni i pasha-limanit liqeni i pasha-limanit al al laguna e pashalimanit,liqeni pasha-limanit,liqeni i pasha-limanit,paschiliman lake,paschiliman sea,pasha liman lagoon,pellg i dajlanit,pellgu i dajlanit,pellgu i dalanit,pellgu i dejlanit',
    NOW(), NOW()), ('3184534', NULL, 'Pasha Liman', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.32459, 19.42916, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pasha liman pasha liman al al paschiliman cove,pasha liman',
    NOW(), NOW()), ('3184542', NULL, 'Gjiri i Panormës', 'Gjiri i Panormes',
    NULL, 'AL', 'AL', NULL, NULL,
    40.06619, 19.78419, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gjiri i panormës gjiri i panormes al al gji palermo,gji i palermos,gji i panormit,gjiri i palermos,gjiri i panormes,gjiri i panormës,hafen palermo,luka palermo,ormos panormu,port palermo,port'' e palermos,porte e palermos,porto palermoja,portë e palermos,port’ e palermos,thronium',
    NOW(), NOW()), ('3184791', NULL, 'Marinëz', 'Marinez',
    NULL, 'AL', 'AL', NULL, NULL,
    40.74056, 19.67333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marinëz marinez al al marin,marina,marinaj,marine e beratit,marinez,marineza,marineze,marinë e beratit,marinëz,marinëza,marinëzë',
    NOW(), NOW()), ('3184792', NULL, 'Marinë', 'Marine',
    NULL, 'AL', 'AL', NULL, NULL,
    40.98333, 19.89972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marinë marine al al marina,marinas',
    NOW(), NOW()), ('3184932', NULL, 'Skele e Liamanës', 'Skele e Liamanes',
    NULL, 'AL', 'AL', NULL, NULL,
    40.06667, 19.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'skele e liamanës skele e liamanes al al',
    NOW(), NOW()), ('3184993', NULL, 'Lalm-Lukaj', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.79222, 19.70889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lalm-lukaj lalm-lukaj al al lalm,lalm-lukaj,lalme-lukaj,lalmë-lukaj',
    NOW(), NOW()), ('3185722', NULL, 'Porti i Durrësit', 'Porti i Durresit',
    NULL, 'AL', 'AL', NULL, NULL,
    41.30833, 19.45417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porti i durrësit porti i durresit al al durres ferry port,durres harbour,porti detar i durresit enver hoxha,porti detar i durrësit ”enver hoxha”,porti i durresit,porti i durrësit,skele e durresit,skele e durrësit',
    NOW(), NOW()), ('3185735', NULL, 'Gjiri i Dukatit', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.37756, 19.44073, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gjiri i dukatit gjiri i dukatit al al baia di dukatit,bucht dukati,bucht von dukatit,dukatit bay,dukatski zaliv,gji i dukatit,gjiri i dukatit,gjiu dukatit,ormos dukati,port dukati,seno di ducati,zaliv dukatit,дукатски залив',
    NOW(), NOW()), ('3205125', NULL, 'Portat', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    42.19556, 19.62917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portat portat al al',
    NOW(), NOW()), ('3220688', NULL, 'Shkoder-Shtojri', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    42.11611, 19.54056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shkoder-shtojri shkoder-shtojri al al shkoder-shtojri,shkoder/shtojiri airport,shkodër/shtojiri airport',
    NOW(), NOW()), ('3343148', NULL, 'Lukaj', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    42.36444, 19.49167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukaj lukaj al al',
    NOW(), NOW()), ('10055326', NULL, 'Porto Eda', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    39.86722, 20.00889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto eda porto eda al al',
    NOW(), NOW()), ('10118651', NULL, 'Vila Aeroport', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.43702, 19.73011, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vila aeroport vila aeroport al al',
    NOW(), NOW()), ('10119600', NULL, 'Airport Tirana', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.41645, 19.71255, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport tirana airport tirana al al',
    NOW(), NOW()), ('10172766', NULL, 'Port of Durres', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.30972, 19.45722, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port of durres port of durres al al',
    NOW(), NOW()), ('10172781', NULL, 'Port of Saranda', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    39.871, 20.00315, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port of saranda port of saranda al al',
    NOW(), NOW()), ('10172782', NULL, 'Seaport of Shëngjin', 'Seaport of Shengjin',
    NULL, 'AL', 'AL', NULL, NULL,
    41.81396, 19.58781, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'seaport of shëngjin seaport of shengjin al al',
    NOW(), NOW()), ('10237379', NULL, 'Vila Aeroport Rinas', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.43522, 19.69784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vila aeroport rinas vila aeroport rinas al al',
    NOW(), NOW()), ('10282250', NULL, 'Airport Hotel Tirana', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.33163, 19.83184, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport hotel tirana airport hotel tirana al al',
    NOW(), NOW()), ('11204014', NULL, 'Porto Palermo Beach', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.06244, 19.79351, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto palermo beach porto palermo beach al al',
    NOW(), NOW()), ('11983489', NULL, 'Brigjet e Pasha-Limanit', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.32462, 19.4055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brigjet e pasha-limanit brigjet e pasha-limanit al al brigjet e pasha-limanit',
    NOW(), NOW()), ('11983531', NULL, 'Pasha-Limani', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.32028, 19.42933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pasha-limani pasha-limani al al pasha-limani',
    NOW(), NOW()), ('12037420', NULL, 'Përrua Llukajve', 'Perrua Llukajve',
    NULL, 'AL', 'AL', NULL, NULL,
    42.44055, 20.14963, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'përrua llukajve perrua llukajve al al perrua llukajve,përrua llukajve',
    NOW(), NOW()), ('12040560', NULL, 'Mesheçi-Marinasi', 'Mesheci-Marinasi',
    NULL, 'AL', 'AL', NULL, NULL,
    40.78571, 19.44985, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mesheçi-marinasi mesheci-marinasi al al mesheci-marinasi,mesheçi-marinasi',
    NOW(), NOW()), ('12045894', NULL, 'Limani i Patokut', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    41.6428, 19.60359, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limani i patokut limani i patokut al al limani i patokut',
    NOW(), NOW()), ('12501086', NULL, 'Portez', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.68118, 19.58779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portez portez al al',
    NOW(), NOW()), ('13308827', NULL, 'Vlora International Airport', NULL,
    NULL, 'AL', 'AL', NULL, NULL,
    40.60608, 19.42899, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'vlora international airport vlora international airport al al lavl,vlo',
    NOW(), NOW()), ('175002', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.78197, 45.22708, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agaunadzor,agavnadzor,agavnajor,aghavnadzor,aghawnadzor,ahavnadzora,akhavnadzor,axavnadzor,aynadzor,aynazur,aghavnadzori,aghawnadzwr,aqawnzwr,агавнадзор,агаўнадзор,ахавнадзор,աղավնաձոր,آغاونادزور,اقاونزور,აღავნაძორი',
    NOW(), NOW()), ('616464', NULL, 'Lukashin', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.18726, 44.0039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukashin lukashin am am imeni mikoyana,lukashin,lukasin,лукашин,լուկաշին',
    NOW(), NOW()), ('617002', NULL, 'Aghavnatun', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.2333, 44.25295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnatun aghavnatun am am agavnatun,aghavnatun,akhavnatukh,akhavnatun,axavnatun,агавнатун,ахавнатун,աղավնատուն',
    NOW(), NOW()), ('617003', NULL, 'Aghavnadzor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.57848, 44.69948, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzor aghavnadzor am am agavnadzor,agavnajor,aghavnadzor,akhavnadzor,axavnadzor,babakishi,агавнадзор,աղավնաձոր',
    NOW(), NOW()), ('617012', NULL, 'Aghavnavank', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.72259, 45.09253, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnavank aghavnavank am am agavnavank,agavnavankʻ,aghavnavank,aghavnavank'',aghavnavank’,axavnavanq,sala,salah,salakh,salax,агавнаванк,салах,աղավնավանք,սալա,սալախ,սալահ',
    NOW(), NOW()), ('799617', NULL, 'Zvartnots International Airport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.1525, 44.40222, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'zvartnots international airport zvartnots international airport am am evn,udyz,yerevan international airport,zvartnots international airport,zvartʻnocʻ mijazgayin odanavakayan,զվարթնոց միջազգային օդանավակայան',
    NOW(), NOW()), ('866132', NULL, 'Aghavno Lerr', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.49451, 44.46668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavno lerr aghavno lerr am am agavno ler,aghavno lerr,gora kushchi,աղավնո լեռ',
    NOW(), NOW()), ('866165', NULL, 'Lukashin', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.19806, 44.45111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukashin lukashin am am lukashin',
    NOW(), NOW()), ('6300930', NULL, 'Erebuni Airport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.13333, 44.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'erebuni airport erebuni airport am am udye',
    NOW(), NOW()), ('6453423', NULL, 'Shirak Airport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    40.75103, 43.85983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shirak airport shirak airport am am lwn,udsg',
    NOW(), NOW()), ('8431566', NULL, 'Razvaliny Chobandara', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.87036, 44.84544, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'razvaliny chobandara razvaliny chobandara am am',
    NOW(), NOW()), ('8533703', NULL, 'Stepanavan Airport', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    41.04829, 44.33619, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stepanavan airport stepanavan airport am am aeroportul stepanavan,bandar udara stepanavan,lapangan terbang antarabangsa stepanavan,maes awyr stepanavan,port lotniczy stepanawan,stepanavan airport,stepanavan havaalani,stepanavan havaalanı,stepanavan flygplats,stepanavan hava limani,stepanavan hava limanı,udls,aeroport de stepanavan,aeroporto di stepanavan,aéroport de stepanavan,frwdgah astpanawan,sutepanavuan kong gang,аеропорт «степанаван»,фурудгоҳи остпоновон,ստեփանավան,فرودگاه استپاناوان,სტეფანავანის აეროპორტი,ステパナヴァン空港',
    NOW(), NOW()), ('10426583', NULL, 'Aghavnadzori', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.75848, 45.23053, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aghavnadzori aghavnadzori am am agavnajori,aghavnadzori,աղավնաձորի',
    NOW(), NOW()), ('10526288', NULL, 'Portavor', NULL,
    NULL, 'AM', 'AM', NULL, NULL,
    39.6347, 45.20569, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portavor portavor am am portavor,պորտավոր',
    NOW(), NOW());