INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('7730154', NULL, 'Guajará-Mirim Airport', 'Guajara-Mirim Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.7864, -65.2848, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'guajará-mirim airport guajara-mirim airport brazil br aeroport de guajara-mirim,aeroporto de guajara-mirim,aeroporto de guajará-mirim,aeropuerto de guajara-mirim,aeropuerto de guajará-mirim,aéroport de guajará-mirim,flughafen guajara-mirim,flughafen guajará-mirim,gjm,guajara-mirim airport,guajará-mirim airport,sbgm',
    NOW(), NOW()), ('7730155', NULL, 'Itacoatiara Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.12726, -58.4812, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itacoatiara airport itacoatiara airport brazil br ita,sbic',
    NOW(), NOW()), ('7730156', NULL, 'Lages Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.7821, -50.2815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lages airport lages airport brazil br aeroporto de lages,aeroportul lages,aeropuerto de lages,flughafen lages,laj,lages airport,lapangan terbang lages,sblj,aeroport de lages,aéroport de lages,rajesu kong gang,ラジェス空港',
    NOW(), NOW()), ('7730157', NULL, 'Lins Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.664, -49.7305, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lins airport lins airport brazil br aeroporto de lins,aeroportul lins,aeropuerto de lins,flughafen lins,lip,lapangan terbang lins,lins airport,sbln,aerodrome de lins,aérodrome de lins,rinsu kong gang,リンス空港',
    NOW(), NOW()), ('7730158', NULL, 'Minaçu Airport', 'Minacu Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.5491, -48.1953, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'minaçu airport minacu airport brazil br mqh,sbmc',
    NOW(), NOW()), ('7730159', NULL, 'Monte Dourado Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -0.88984, -52.6022, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'monte dourado airport monte dourado airport brazil br aeroporto de monte dourado,aeroportul monte dourado,aeropuerto de monte dourado,flughafen monte dourado,lapangan terbang monte dourado,meu,monte dourado airport,sbmd,aerodrome de monte dourado,aérodrome de monte dourado,frwdgah mwnth dwradw,meng te du la duo ji chang,фурудгоҳи мунта дуроду,فرودگاه مونته دورادو,モンテ・ドウラード空港,蒙特杜拉多機場',
    NOW(), NOW()), ('7730160', NULL, 'Marília Airport', 'Marilia Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.1969, -49.9264, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marília airport marilia airport brazil br mii,sbml',
    NOW(), NOW()), ('7730161', NULL, 'Base de Aviação de Taubaté Airport', 'Base de Aviacao de Taubate Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0401, -45.516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'base de aviação de taubaté airport base de aviacao de taubate airport brazil br qhp,sbta',
    NOW(), NOW()), ('7730162', NULL, 'Tiriós Airport', 'Tirios Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    2.22347, -55.9461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiriós airport tirios airport brazil br sbts',
    NOW(), NOW()), ('7730163', NULL, 'Major Brigadeiro Trompowsky Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.5901, -45.4733, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'major brigadeiro trompowsky airport major brigadeiro trompowsky airport brazil br sbvg,vag',
    NOW(), NOW()), ('7730779', NULL, 'Caldas Novas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.7253, -48.6075, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caldas novas airport caldas novas airport brazil br clv,sbcn',
    NOW(), NOW()), ('7730780', NULL, 'Governador Valadares Airport (GVR, SBGV)', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.8952, -41.9822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'governador valadares airport (gvr, sbgv) governador valadares airport (gvr, sbgv) brazil br aeroporto coronel altino machado de oliveira,coronel altino machado de oliveira airport,gvr,governador valadares airport,sbgv',
    NOW(), NOW()), ('7730781', NULL, 'Chapada Diamantina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.4823, -41.277, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chapada diamantina airport chapada diamantina airport brazil br lec,sble',
    NOW(), NOW()), ('7730782', NULL, 'Una-Comandatuba Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.3574, -38.99822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'una-comandatuba airport una-comandatuba airport brazil br aeroporto de una-comandatuba,sbtc,una,una-comandatuba airport',
    NOW(), NOW()), ('7730783', NULL, 'Luiz dal Canalle Filho Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.6863, -53.6975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luiz dal canalle filho airport luiz dal canalle filho airport brazil br aeroporto luiz dal canalle filho,luiz dal canalle filho airport,sbtd,tow,toledo airport',
    NOW(), NOW()), ('7730811', NULL, 'Aripuanã Airport', 'Aripuana Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.18639, -59.4575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aripuanã airport aripuana airport brazil br air,aeroport d''aripuana,aeroporto de aripuana,aeroporto de aripuanã,aeropuerto de aripuana,aeropuerto de aripuanã,aripuana airport,aripuanã airport,aéroport d''aripuanã,ssou',
    NOW(), NOW()), ('7730818', NULL, 'Alenquer Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.9175, -54.7211, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alenquer airport alenquer airport brazil br alt,sdwq',
    NOW(), NOW()), ('7730821', NULL, 'Cirilo Queiróz Airport', 'Cirilo Queiroz Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.18389, -40.66722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cirilo queiróz airport cirilo queiroz airport brazil br amj,snar',
    NOW(), NOW()), ('7730827', NULL, 'Arapiraca Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.77536, -36.6292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arapiraca airport arapiraca airport brazil br apq,snal',
    NOW(), NOW()), ('7730829', NULL, 'Nova Vida Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.17806, -62.82556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nova vida airport nova vida airport brazil br aqm,swni',
    NOW(), NOW()), ('7730850', NULL, 'Novo Campo Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.83456, -67.3124, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novo campo airport novo campo airport brazil br bcr,swnk',
    NOW(), NOW()), ('7730853', NULL, 'Barra do Corda Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.5025, -45.21583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barra do corda airport barra do corda airport brazil br bdc,snbc',
    NOW(), NOW()), ('7730874', NULL, 'Sócrates Mariani Bittencourt Airport', 'Socrates Mariani Bittencourt Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.2554, -41.8175, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sócrates mariani bittencourt airport socrates mariani bittencourt airport brazil br bms,snbu',
    NOW(), NOW()), ('7730875', NULL, 'Blumenau Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.8306, -49.0903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blumenau airport blumenau airport brazil br bnu,ssbl',
    NOW(), NOW()), ('7730878', NULL, 'Barreiras Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.0789, -45.009, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barreiras airport barreiras airport brazil br aeroporto de barreiras,aeroportul barreiras,aeropuerto de barreiras,bra,barreiras airport,flughafen barreiras,lapangan terbang barreiras,snbr,aerodrome de barreiras,aérodrome de barreiras,ba lei la si ji chang,bareirasu,frwdgah baryras,фурудгоҳи борирос,فرودگاه باریراس,バレイラス,巴雷拉斯機場',
    NOW(), NOW()), ('7730879', NULL, 'Barreirinha Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.79242, -57.0579, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barreirinha airport barreirinha airport brazil br barreirinha airport,swbi',
    NOW(), NOW()), ('7730881', NULL, 'Balsas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.52603, -46.0533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'balsas airport balsas airport brazil br bss,snbs',
    NOW(), NOW()), ('7730890', NULL, 'Belmonte Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.8717, -38.8719, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belmonte airport belmonte airport brazil br bvm,snbl',
    NOW(), NOW()), ('7730891', NULL, 'Breves Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.63653, -50.4436, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'breves airport breves airport brazil br bvs,snvs',
    NOW(), NOW()), ('7730901', NULL, 'Carauari Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.87152, -66.8975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carauari airport carauari airport brazil br aeroporto de carauari,aeroportul carauari,aeropuerto de carauari,caf,carauari airport,flughafen carauari,lapangan terbang carauari,swca,aeroport de carauari,arauari kong gang,aéroport de carauari,frwdgah krawary,ka la wa li ji chang,фурудгоҳи кровори,فرودگاه کراواری,アラウアリ空港,卡拉瓦里機場',
    NOW(), NOW()), ('7730902', NULL, 'Caruaru Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.28239, -36.0135, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caruaru airport caruaru airport brazil br cau,snru',
    NOW(), NOW()), ('7730912', NULL, 'Confresa Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.6344, -51.5636, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'confresa airport confresa airport brazil br cfo,sjhg',
    NOW(), NOW()), ('7730920', NULL, 'Coari Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.13406, -63.1326, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coari airport coari airport brazil br aeroporto de coari,aeroportul coari,aeropuerto de coari,ciz,coari airport,flughafen coari,lapangan terbang coari,maes awyr coari,swko,aeroport de coari,aéroport de coari,frwdgah kwary,koari kong gang,kua li ji chang,фурудгоҳи куори,فرودگاه کواری,コアリ空港,夸里機場,誇里機場',
    NOW(), NOW()), ('7730921', NULL, 'Cornélio Procópio Airport', 'Cornelio Procopio Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.1525, -50.6025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cornélio procópio airport cornelio procopio airport brazil br aeroporto de cornelio procopio,aeroporto de cornélio procópio,aeroportul cornelio procopio,aeroportul cornélio procópio,aeropuerto de cornelio procopio,aeropuerto de cornélio procópio,cko,cornelio procopio airport,cornélio procópio airport,flughafen francisco lacerda junior,flughafen francisco lacerda júnior,lapangan terbang cornelio procopio,sscp,aerodrome de francisco lacerda junior,aérodrome de francisco lacerda júnior,ke nei li wu-pu luo ke pi wu ji chang,コルネーリオ・プロコーピオ空港,科內利烏-普羅科皮烏機場',
    NOW(), NOW()), ('7730925', NULL, 'Camocim Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.89618, -40.858, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camocim airport camocim airport brazil br cmc,snwc',
    NOW(), NOW()), ('7730927', NULL, 'Santana do Araguaia Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.31997, -50.3285, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santana do araguaia airport santana do araguaia airport brazil br cmp,snke',
    NOW(), NOW()), ('7730930', NULL, 'Canavieiras Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.667, -38.9547, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canavieiras airport canavieiras airport brazil br cnv,sned',
    NOW(), NOW()), ('7730937', NULL, 'Campo dos Amarais Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8592, -47.1082, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campo dos amarais airport campo dos amarais airport brazil br aeroporto campo dos amarais,aeroportul campo dos amarais,aeropuerto campo dos amarais,cpq,campinas international airport,campinas-campos dos amarais delstatsflygplats - prefeito francisco amaral,campinas-campos dos amarais delstatsflygplats – prefeito francisco amaral,campo dos amarais airport,flughafen aerodromo estadual de campinas / amarais,flughafen aerodrómo estadual de campinas / amarais,kampu-dus-amarais,lapangan terbang amarais,sdam,aerodrome de estadual de campos dos amarais - prefeito francisco amaral,aérodrome de estadual de campos dos amarais - prefeito francisco amaral,frwdgah kmpww das amarays,кампу-дус-амараис,фурудгоҳи кмпув дос омороис,فرودگاه کمپوو داس آمارایس,カンポ・ドス・アマライス空港',
    NOW(), NOW()), ('7730938', NULL, 'Cururupu Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.82111, -44.86694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cururupu airport cururupu airport brazil br cpu,sncu',
    NOW(), NOW()), ('7730939', NULL, 'Canarana Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.57444, -52.27056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canarana airport canarana airport brazil br aeroporto de canarana,aeroportul canarana,aeropuerto de canarana,cqa,canarana airport,flughafen canarana,lapangan terbang canarana,swek,aerodrome de canarana,aérodrome de canarana',
    NOW(), NOW()), ('7730941', NULL, 'Costa Marques Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.4211, -64.2516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'costa marques airport costa marques airport brazil br cqs,swcq',
    NOW(), NOW()), ('7730949', NULL, 'Santa Cruz do Sul Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.6841, -52.4122, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa cruz do sul airport santa cruz do sul airport brazil br aeroporto luiz beck da silva,aeroporto de santa cruz do sul,aeroportul santa cruz do sul,aeropuerto de santa cruz do sul,csu,flughafen santa cruz do sul,lapangan terbang santa cruz do sul,sssc,santa cruz do sul airport,aerodrome de santa cruz do sul,aérodrome de santa cruz do sul',
    NOW(), NOW()), ('7730950', NULL, 'Carutapera Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.22482, -46.01823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carutapera airport carutapera airport brazil br aeroport de carutapera,aeroporto de carutapera,aeropuerto de carutapera,aéroport de carutapera,ctp,carutapera airport',
    NOW(), NOW()), ('7730951', NULL, 'Santa Vitória do Palmar Airport', 'Santa Vitoria do Palmar Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -33.50222, -53.34417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa vitória do palmar airport santa vitoria do palmar airport brazil br ctq,ssvp',
    NOW(), NOW()), ('7730973', NULL, 'Brigadeiro Cabral Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.1807, -44.8709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brigadeiro cabral airport brigadeiro cabral airport brazil br aeroport de divinopolis,aeroporto brigadeiro cabral,aéroport de divinópolis,brigadeiro cabral airport,diq,divinopolis airport,divinópolis airport,sndv',
    NOW(), NOW()), ('7730979', NULL, 'Diamantino Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.3769, -56.4004, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'diamantino airport diamantino airport brazil br dmt,swdm',
    NOW(), NOW()), ('7730982', NULL, 'Dianópolis Airport', 'Dianopolis Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.5954, -46.8467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dianópolis airport dianopolis airport brazil br dno,dianopolis airport,dianópolis airport,swdn',
    NOW(), NOW()), ('7730986', NULL, 'Dourados Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.2019, -54.9266, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dourados airport dourados airport brazil br aeroporto regional de dourados,aeroportul dourados,aeropuerto regional de dourados,dou,dourados airport,flugplatz sao pedro,flugplatz são pedro,lapangan terbang dourados,maes awyr dourados,ssdo,douradosu,duo la du si ji chang,frwdgah dwradws,mtar dwradws,фурудгоҳи дуродус,فرودگاه دورادوس,مطار دورادوس,ドウラドス,多拉杜斯機場',
    NOW(), NOW()), ('7731012', NULL, 'Eirunepé Airport', 'Eirunepe Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.63953, -69.8798, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eirunepé airport eirunepe airport brazil br ern,swei',
    NOW(), NOW()), ('7731020', NULL, 'Paulo Abdala Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.0592, -53.0635, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paulo abdala airport paulo abdala airport brazil br aeroporto paulo abdala,aeroportul francisco beltrao,aeroportul francisco beltrão,aeropuerto de francisco beltrao,aeropuerto de francisco beltrão,fbe,flughafen paulo abdala,francisco beltrao airport,francisco beltrão airport,lapangan terbang francisco beltrao,paulo abdala airport,ssfb,aerodrome de paulo abdala,aérodrome de paulo abdala,bei er de lang ji chang,frwdgah frnsyskw bltrwn,фурудгоҳи фрнсиску блтрун,فرودگاه فرنسیسکو بلترون,フランシスコ・ベルトラン空港,貝爾德朗機場',
    NOW(), NOW());