INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3571835', NULL, 'Mouth of Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54192, -76.96439, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mouth of harbour cay mouth of harbour cay bahamas bs mouth of harbour cay',
    NOW(), NOW()), ('3571848', NULL, 'Moriah Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.46667, -75.66667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'moriah harbour cay moriah harbour cay bahamas bs moriah harbour cay',
    NOW(), NOW()), ('3571895', NULL, 'Mayaguana Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.379, -73.014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mayaguana airport mayaguana airport bahamas bs myg,mymm,mayaguana',
    NOW(), NOW()), ('3571912', NULL, 'Marsh Harbour District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.4, -77.16667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'marsh harbour district marsh harbour district bahamas bs marsh harbour,marsh harbour district',
    NOW(), NOW()), ('3571913', NULL, 'Marsh Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54124, -77.0636, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'marsh harbour marsh harbour bahamas bs mhh,marsh harbour',
    NOW(), NOW()), ('3571949', NULL, 'Clarence A. Bain Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.28812, -77.679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clarence a. bain airport clarence a. bain airport bahamas bs clarence a. bain airport,may,myab,mangrove cay airport',
    NOW(), NOW()), ('3571956', NULL, 'Major’s Cay Harbour', 'Major''s Cay Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.73615, -74.1418, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'major’s cay harbour major''s cay harbour bahamas bs major cay harbour,major''s cay harbour,major’s cay harbour',
    NOW(), NOW()), ('3571965', NULL, 'Lynyard Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.36968, -76.98195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lynyard cay lynyard cay bahamas bs leonard cay,little harbour cay,lynyard cay',
    NOW(), NOW()), ('3571973', NULL, 'Low Water Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.41667, -75.81667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'low water harbour cay low water harbour cay bahamas bs low water harbour cay',
    NOW(), NOW()), ('3572051', NULL, 'Little Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.57804, -77.72004, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour cay little harbour cay bahamas bs little harbour cay',
    NOW(), NOW()), ('3572052', NULL, 'Little Harbour Bay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.33333, -77.01667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour bay little harbour bay bahamas bs',
    NOW(), NOW()), ('3572053', NULL, 'Little Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.31667, -76.98333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour little harbour bahamas bs',
    NOW(), NOW()), ('3572054', NULL, 'Little Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.98238, -74.85335, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour little harbour bahamas bs little harbour',
    NOW(), NOW()), ('3572096', NULL, 'Lantern Head Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    20.95631, -73.28259, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'lantern head harbour lantern head harbour bahamas bs',
    NOW(), NOW()), ('3572153', NULL, 'Inagua Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    20.97565, -73.67509, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inagua airport inagua airport bahamas bs iga,inagua airport,myig,matthew town airport,port lotniczy inagua,frwdgah aynagwa,فرودگاه ایناگوا',
    NOW(), NOW()), ('3572157', NULL, 'Hurricane Hole', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.33333, -77.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hurricane hole hurricane hole bahamas bs hurricane hole,little harbour',
    NOW(), NOW()), ('3572177', NULL, 'Torch Cay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.39764, -75.49893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'torch cay airport torch cay airport bahamas bs hog cay exuma airfield,myey,tcv',
    NOW(), NOW()), ('3572208', NULL, 'Head of Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.58658, -76.99503, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'head of harbour head of harbour bahamas bs head of harbour',
    NOW(), NOW()), ('3572211', NULL, 'Hawks Nest Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15361, -75.52405, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hawks nest airport hawks nest airport bahamas bs hawks nest airport,mych',
    NOW(), NOW()), ('3572215', NULL, 'Hawks Nest', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15, -75.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hawks nest hawks nest bahamas bs hawks nest,hawks nest harbour',
    NOW(), NOW()), ('3572237', NULL, 'Hard Bargain', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23, -74.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hard bargain hard bargain bahamas bs hard bargain,hard bargain airport',
    NOW(), NOW()), ('3572238', NULL, 'Harbour Island District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.48946, -76.63513, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour island district harbour island district bahamas bs gjao harbour,haborailenda,harboro sala,harbour adasi,harbour adası,harbour island,harbour island district,harbour uhartea,hāborailenda,illa harbour,isla harbour,kharbor-ajlend,nisi charmpor,pulau harbour,pulong harbour,ha bo dao,haba dao,habeoseom,harabara dbipa,harbar divi,harbar dvipa,harbara a''ilenda,harbara a''isalamda,harbara dvipa,harbor-ailendi,harpoyur  aislantu,jzyrh harbwr  bahama,đảo harbour,νησί χάρμπορ,харбор-айленд,جزيرة الميناء,جزیره هاربور، باهاما,حاربوور آئی لینڈ,हार्बर आईसलँड,हार्बर द्वीप,হারবার দ্বীপ,હાર્બર આઇલેન્ડ,ஹார்போயூர்  ஐஸ்லாந்து,హార్బర్ దీవి,ಹಾರ್ಬರ್ ದ್ವೀಪ,හාර්බර් දුපත,ฮาร์เบอร์ ไอส์แลนด์,ჰარბორ-აილენდი,ハーバー島,哈勃岛,哈勃島,하버섬',
    NOW(), NOW()), ('3572239', NULL, 'Harbour Island', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.5, -76.63333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour island harbour island bahamas bs hbi,harbor island,harbour island',
    NOW(), NOW()), ('3572240', NULL, 'Harbour Estate', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.1, -74.51667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour estate harbour estate bahamas bs',
    NOW(), NOW()), ('3572274', NULL, 'Green’s Harbour', 'Green''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.05548, -74.43769, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'green’s harbour green''s harbour bahamas bs',
    NOW(), NOW()), ('3572290', NULL, 'Great Harbour Cay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.74099, -77.84444, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour cay airport great harbour cay airport bahamas bs ghc,great harbour cay airport,mybg',
    NOW(), NOW()), ('3572291', NULL, 'Great Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.7287, -77.84028, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour cay great harbour cay bahamas bs ghc,great harbor cay,great harbour,great harbour cay',
    NOW(), NOW()), ('3572292', NULL, 'Great Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.09893, -74.95202, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour great harbour bahamas bs clarence harbour,great harbour',
    NOW(), NOW()), ('3572310', NULL, 'Grand Bahama Auxiliary Air Force', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.62789, -78.36496, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand bahama auxiliary air force grand bahama auxiliary air force bahamas bs gbi,grand bahama aux af airport,grand bahama aux. a.f.b.,grand bahama auxiliary air force',
    NOW(), NOW()), ('3572311', NULL, 'Graham’s Harbour', 'Graham''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.14187, -74.48185, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'graham’s harbour graham''s harbour bahamas bs',
    NOW(), NOW()), ('3572312', NULL, 'Governor''s Harbour District (historical)', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.25952, -76.31164, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'governor''s harbour district (historical) governor''s harbour district (historical) bahamas bs ghb,governor''s harbour,governor''s harbour district',
    NOW(), NOW()), ('3572313', NULL, 'Governor’s Harbour', 'Governor''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.16667, -76.23333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'governor’s harbour governor''s harbour bahamas bs governor harbor,governor harbour,governor''s harbour,governors harbor,governor’s harbour',
    NOW(), NOW()), ('3572320', NULL, 'Gorda Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.09123, -77.54065, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gorda cay gorda cay bahamas bs castaway cay airport,myag',
    NOW(), NOW()), ('3572348', NULL, 'Georgetown Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.49871, -75.76262, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'georgetown harbour georgetown harbour bahamas bs',
    NOW(), NOW()), ('3572372', NULL, 'Grand Bahama International Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.55869, -78.69555, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'grand bahama international airport grand bahama international airport bahamas bs aeroport international de grand bahama,aeropuerto internacional de grand bahama,aéroport international de grand bahama,bandar udara internasional grand bahama,fpo,freeport international airport,grand bahama international airport,grand bahaman kansainvaelinen lentoasema,grand bahaman kansainvälinen lentoasema,lapangan terbang antarabangsa grand bahama,mygf,mezhdunarodnyj aehroport bol''shogo bagamy,port lotniczy wielka bahama,san bay quoc te grand bahama,sân bay quốc tế grand bahama,da ba ha ma guo ji ji chang,frwdgah byn‌almlly grnd bahama,gurandobahama guo ji kong gang,международный аэропорт большого багамы,фурудгоҳи бин‌алмилалӣ грнд баҳама,فرودگاه بین‌المللی گرند باهاما,グランドバハマ国際空港,大巴哈馬國際機場,大巴哈马国际机场',
    NOW(), NOW()), ('3572373', NULL, 'Freeport Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.52087, -78.78035, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'freeport harbour freeport harbour bahamas bs freeport harbour',
    NOW(), NOW()), ('3572374', NULL, 'City of Freeport District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.52028, -78.64528, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'city of freeport district city of freeport district bahamas bs city of freeport,city of freeport district,freeport,freeport district,friiport,frijport,friport,friporta,friportas,frīporta,fri phxrth,fry pwrt,frybwrt,fu li bo te,furipoto,peulipoteu,phri porta,phriport,phriporta,piripport,prypwrt,zi you gang,φρίπορτ,фрийпорт,фрипорт,фріпорт,פריפורט,فريبورت,فری پورت,فری پورٹ، بہاماس,फ्री पोर्ट,फ्रीपोर्ट,ফ্রিপোর্ট,ફ્રીપોર્ટ,பிரிப்போர்ட்,ఫ్రీపోర్ట్,ಫ್ರೀಪೋರ್ಟ್,ෆ්රීපෝර්ට්,ฟรีพอร์ท,ფრიპორტი,フリーポート,弗里波特,自由港,프리포트',
    NOW(), NOW()), ('3572375', NULL, 'Freeport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.53333, -78.7, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'freeport freeport bahamas bs fpo,freeport,freeport city,friport,фрипорт',
    NOW(), NOW()), ('3572381', NULL, 'Fowl Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.26873, -76.53875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fowl cay fowl cay bahamas bs fowl cay,fowl cay airport,myxa',
    NOW(), NOW()), ('3572425', NULL, 'Exuma Harbour Estates', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.5, -75.76667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'exuma harbour estates exuma harbour estates bahamas bs',
    NOW(), NOW()), ('3572426', NULL, 'Exuma Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.54121, -75.81799, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'exuma harbour exuma harbour bahamas bs',
    NOW(), NOW()), ('3572434', NULL, 'Elizabeth Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.50796, -75.73009, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'elizabeth harbour elizabeth harbour bahamas bs elizabeth harbour,elizabeth howbon',
    NOW(), NOW()), ('3572462', NULL, 'Dunmore Town', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.50216, -76.63633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dunmore town dunmore town bahamas bs dunmore town,harbour island',
    NOW(), NOW()), ('3572490', NULL, 'Dollar Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.51667, -79.26667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'dollar harbour dollar harbour bahamas bs',
    NOW(), NOW()), ('3572509', NULL, 'Delaport Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.07965, -77.43158, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delaport point delaport point bahamas bs delaport point',
    NOW(), NOW()), ('3572510', NULL, 'Delaport Bay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.08333, -77.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delaport bay delaport bay bahamas bs',
    NOW(), NOW()), ('3572512', NULL, 'Deep Water Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.63112, -77.92081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'deep water cay deep water cay bahamas bs deep water cay,deep water cay airport,mygd',
    NOW(), NOW()), ('3572535', NULL, 'Cutlass Bay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.14899, -75.39797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cutlass bay airport cutlass bay airport bahamas bs aeroport de la baie de cutlass,aeroportul cutlass bay,aéroport de la baie de cutlass,cutlass bay airport,lapangan terbang cutlass bay,mycx,カットラス・ベイ空港',
    NOW(), NOW()), ('3572558', NULL, 'Cross Harbour Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.91948, -77.28442, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cross harbour point cross harbour point bahamas bs cedar point,cross harbor point,cross harbour point',
    NOW(), NOW()), ('3572559', NULL, 'Cross Harbour Creek', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.93333, -77.26667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cross harbour creek cross harbour creek bahamas bs',
    NOW(), NOW());