INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('6300537', NULL, 'Teniente General Benjamín Matienzo International Airport', 'Teniente General Benjamin Matienzo International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.84086, -65.10494, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'teniente general benjamín matienzo international airport teniente general benjamin matienzo international airport argentina ar aeroporto tenente general benjamin matienzo,aeroporto tenente general benjamín matienzo,sant,tuc,teniente general benjamin matienzo international airport,teniente general benjamín matienzo international airport,frwdgah byn‌almlly sphbd bnjamyn matynzw,فرودگاه بین‌المللی سپهبد بنجامین ماتینزو',
    NOW(), NOW()), ('6300538', NULL, 'Domingo Faustino Sarmiento Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.57147, -68.41819, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'domingo faustino sarmiento airport domingo faustino sarmiento airport argentina ar aeroporto domingo faustino sarmiento,aeroportul domingo faustino sarmiento,aeropuerto de san juan - domingo faustino sarmiento,domingo faustino sarmiento airport,flughafen san juan,lapangan terbang san juan,port lotniczy domingo faustino sarmiento,sanu,san bay domingo faustino sarmiento,sân bay domingo faustino sarmiento,uaq,aeroport de domingo faustino sarmiento,aéroport de domingo faustino sarmiento,frwdgah dmyngww fastynw asarmyntw,фурудгоҳи дмингув фостину осорминту,فرودگاه دمینگوو فاستینو اسارمینتو,ドミンゴ・ファウスティーノ・サルミエント空港,聖胡安-多明哥·福斯蒂諾·薩爾門托機場',
    NOW(), NOW()), ('6300539', NULL, 'Ceres Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.87339, -61.92923, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ceres aerodrome ceres aerodrome argentina ar aeropuerto ceres,crr,ceres airport,sanw',
    NOW(), NOW()), ('6300540', NULL, 'Rio Cuarto Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.08513, -64.26131, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rio cuarto airport rio cuarto airport argentina ar aeroportul las higueras,aeropuerto de rio cuarto,aeropuerto de río cuarto,flughafen rio cuarto,flughafen río cuarto,lapangan terbang area de material,las higueras airport,rcu,rio cuarto airport,saoc,aerodrome de rio cuarto,aérodrome de río cuarto,di si he ji chang,frwdgah la hygwras,фурудгоҳи ло ҳигурос,فرودگاه لا هیگوراس,ラス・イゲラス空港,第四河機場',
    NOW(), NOW()), ('6300542', NULL, 'Laboulaye Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.13544, -63.36225, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laboulaye airport laboulaye airport argentina ar aerodromo de laboulaye,aeroportul laboulaye,aeródromo de laboulaye,laboulaye airport,lapangan terbang laboulaye,saol,la wo la ye,rabouraie kong gang,ラボウライェ空港,拉沃拉耶',
    NOW(), NOW()), ('6300544', NULL, 'Villa Reynolds Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.72514, -65.37809, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa reynolds airport villa reynolds airport argentina ar aeroporto de villa reynolds,aeroportul villa reynolds,aeropuerto mercedes,aeropuerto de villa reynolds,lapangan terbang villa reynolds,saor,vme,villa reynolds airport,aerodrome de villa reynolds,aérodrome de villa reynolds,frwdgah wyla rynaldz,фурудгоҳи вело ринолдз,فرودگاه ویلا رینالدز,ビジャ・レイノルズ空港',
    NOW(), NOW()), ('6300545', NULL, 'Brigadier Mayor César Raúl Ojeda Airport', 'Brigadier Mayor Cesar Raul Ojeda Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.27319, -66.35642, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brigadier mayor césar raúl ojeda airport brigadier mayor cesar raul ojeda airport argentina ar aeropuerto de san luis - brigadier mayor cesar raul ojeda,aeropuerto de san luis - brigadier mayor césar raúl ojeda,brigadier mayor cesar raul ojeda airport,brigadier mayor césar raúl ojeda airport,luq,saou',
    NOW(), NOW()), ('6300546', NULL, 'Corrientes International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.4455, -58.76186, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'corrientes international airport corrientes international airport argentina ar aeroporto internacional doctor fernando piragine niveyro,aeroporto di corrientes,aeroportul international doctor fernando piragine niveyro,aeroportul internațional doctor fernando piragine niveyro,aeropuerto internacional de corrientes,aeropuerto de camba punta,aeropuerto de cambá punta,cnq,corrientes aero.,corrientes international airport,doctor fernando piragine niveyro international airport,fernando piragine niveyro bo shi guo ji ji chang,fernando piragine niveyro博士國際機場,flughafen corrientes,lapangan terbang corrientes,maes awyr rhyngwladol doctor fernando piragine niveyro,port lotniczy corrientes,sarc,aeroport de corrientes,aéroport de corrientes,фурудгоҳи бин‌алмилалӣ доктир фрнонду пирогин нюиру,فرودگاه بین‌المللی داکتر فرناندو پیراگین نیویرو,ドクトル・フェルナンド・ピラヒーネ・ニベイロ国際空港',
    NOW(), NOW()), ('6300547', NULL, 'Resistencia International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.44999, -59.05613, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'resistencia international airport resistencia international airport argentina ar aeroporto internacional de resistencia,aeroporto di resistencia,aeroportul international resistencia,aeroportul internațional resistencia,aeropuerto internacional de resistencia,aeropuerto de resistencia general jose de san martin,aeropuerto de resistencia general josé de san martín,flughafen resistencia,lapangan terbang resistencia,maes awyr rhyngwladol resistencia,port lotniczy resistencia,res,resistencia aero.,resistencia international airport,sare,aeroport de resistencia,aéroport de resistencia,lei xi si teng xi ya guo ji ji chang,reshisutenshia guo ji kong gang,фурудгоҳи бин‌алмилалӣ рзистнсио,فرودگاه بین‌المللی رزیستنسیا,レシステンシア国際空港,雷西斯滕西亞國際機場',
    NOW(), NOW()), ('6300549', NULL, 'Cataratas del Iguazú International Airport', 'Cataratas del Iguazu International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.73728, -54.47344, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'cataratas del iguazú international airport cataratas del iguazu international airport argentina ar aeroport international de puerto iguazu,aeroporto internacional cataratas del iguazu,aeroporto internacional cataratas del iguazú,aeroporto di puerto iguazu,aeroporto di puerto iguazú,aeroportul international cataratas del iguazu,aeroportul internațional cataratas del iguazú,aeropuerto internacional cataratas del iguazu,aeropuerto internacional cataratas del iguazú,aéroport international de puerto iguazú,cataratas del iguazu international airport,cataratas del iguazú international airport,flughafen puerto iguazu,flughafen puerto iguazú,igr,lapangan terbang mayor d carlos eduardo krause,maes awyr rhyngwladol cataratas del iguazu,maes awyr rhyngwladol cataratas del iguazú,mayor carlos eduardo krause airport,port lotniczy cataratas del iguazu,port lotniczy cataratas del iguazú,sari,iguasuno long guo ji kong gang,yi gua su gang,yi gua su pu bu guo ji ji chang,фурудгоҳи бин‌алмилалӣ обшор оигуосу,فرودگاه بین‌المللی آبشار ایگواسو,イグアスの滝国際空港,伊瓜苏瀑布国际机场,伊瓜蘇港,伊瓜蘇瀑布國際機場',
    NOW(), NOW()), ('6300550', NULL, 'Paso de los Libres Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.68942, -57.15208, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de los libres airport paso de los libres airport argentina ar aol,aeroportul paso de los libres,aeropuerto de paso de los libres,flughafen paso de los libres,lapangan terbang paso de los libres,paso de los libres airport,sarl,aerodrome de paso de los libres,aérodrome de paso de los libres,frwdgah pasw dw lws lybrs,pa suo de luo si li bu lei si ji chang,фурудгоҳи посу ду лӯс либрс,فرودگاه پاسو دو لوس لیبرس,パソ・デ・ロス・リブレス空港,帕索德洛斯利佈雷斯機場,帕索德洛斯利布雷斯機場',
    NOW(), NOW()), ('6300552', NULL, 'Posadas Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.38584, -55.97073, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'posadas airport posadas airport argentina ar pss,sarp',
    NOW(), NOW()), ('6300553', NULL, 'Presidencia Roque Sáenz Peña Airport', 'Presidencia Roque Saenz Pena Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.75652, -60.4931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'presidencia roque sáenz peña airport presidencia roque saenz pena airport argentina ar aeropuerto presidencia roque saenz pena,aeropuerto presidencia roque sáenz peña,prq,presidencia roque saenz pena airport,presidencia roque sáenz peña airport,sars',
    NOW(), NOW()), ('6300554', NULL, 'Martín Miguel de Güemes International Airport', 'Martin Miguel de Gueemes International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.85598, -65.48617, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'martín miguel de güemes international airport martin miguel de gueemes international airport argentina ar aeroport international martin miguel de gueemes,aeropuerto internacional de salta martin miguel de gueemes,aeropuerto internacional de salta martín miguel de güemes,aéroport international martín miguel de güemes,el aybal airport,flughafen martin miguel de gueemes,flughafen martín miguel de güemes,martin miguel de gueemes international airport,martín miguel de güemes international airport,sasa,sla,salta flygplats',
    NOW(), NOW()), ('6300555', NULL, 'Gobernador Horacio Guzmán International Airport', 'Gobernador Horacio Guzman International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.39278, -65.09778, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'gobernador horacio guzmán international airport gobernador horacio guzman international airport argentina ar aeropuerto internacional de jujuy - gobernador horacio guzman,aeropuerto internacional de jujuy - gobernador horacio guzmán,gobernador horacio guzman international airport,gobernador horacio guzmán international airport,juj,jujuy airport,jujuy flygplats,sasj',
    NOW(), NOW()), ('6300556', NULL, 'Oran Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -23.15278, -64.32917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oran airport oran airport argentina ar aeroporto de oran,ora,oran airport,saso',
    NOW(), NOW()), ('6300557', NULL, 'La Quiaca Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -22.15056, -65.5775, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la quiaca airport la quiaca airport argentina ar aeropuerto la quiaca,sasq',
    NOW(), NOW()), ('6300559', NULL, 'Tartagal Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -22.61917, -63.79319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tartagal aerodrome tartagal aerodrome argentina ar aeroportul tartagal general enrique mosconi,aeropuerto de tartagal,aeropuertu de tartagal,lapangan terbang general enrique mosconi,sast,ttg,tartagal general enrique mosconi airport,tartagal aerodrome,frwdgah tartagal artshbd anrykh maskny,tarutagaru kong gang,фурудгоҳи тортогол артишбуд онрикҳ москни,فرودگاه تارتاگال ارتشبد انریکه ماسکنی,タルタガル空港,塔塔加爾-恩里克·莫斯科尼將軍機場',
    NOW(), NOW()), ('6300560', NULL, 'Las Lomitas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.7, -60.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'las lomitas las lomitas argentina ar aeropuerto alferez armando rodriguez,aeropuerto alférez armando rodríguez,lls,satk',
    NOW(), NOW()), ('6300561', NULL, 'Reconquista Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.21028, -59.68, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'reconquista airport reconquista airport argentina ar aeroport de reconquista,aeroporto teniente daniel jukic,aeroportul reconquista,aeropuerto de reconquista,aéroport de reconquista,flughafen reconquista,lapangan terbang reconquista,port lotniczy reconquista,rcq,reconquista airport,satr,aeroporto teniente daniel jukic,frwdgah rkwnkwyyysta,lei kong ji si ta ji chang,rekonkisuta kong gang,фурудгоҳи ркункуиеҳисто,فرودگاه رکونکویئیستا,レコンキスタ空港,雷孔基斯塔機場',
    NOW(), NOW()), ('6300562', NULL, 'Curuzú Cuatiá Airport', 'Curuzu Cuatia Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.77056, -57.97889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'curuzú cuatiá airport curuzu cuatia airport argentina ar satu,uzu',
    NOW(), NOW()), ('6300563', NULL, 'General Enrique Mosconi International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -45.78535, -67.46551, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'general enrique mosconi international airport general enrique mosconi international airport argentina ar aeroporto internacional general enrique mosconi,aeroportul international general enrique mosconi,aeroportul internațional general enrique mosconi,aeropuerto internacional general enrigue mosconi,aeropuerto internacional general enrique mosconi,aeropuerto de comodoro,bandar udara internasional general enrique mosconi,crd,comodoro international airport,enrique mosconi jiang jun guo ji ji chang,enrique mosconi將軍國際機場,flughafen comodoro rivadavia,general enrique mosconi international airport,kenraali enrique mosconin kansainvaelinen lentoasema,kenraali enrique mosconin kansainvälinen lentoasema,lapangan terbang antarabangsa gen. enrique mosconi,maes awyr rhyngwladol general enrique mosconi,port lotniczy comodoro rivadavia,rivadavia gral. enrique mosconi,savc,aeroport general enrique mosconi,aeroporto,aéroport general enrique mosconi,фурудгоҳи бин‌алмилалӣ жинирол онрику москуни,хе­не­раль эн­ри­ке мос­ко­ни,فرودگاه بین‌المللی ژنرال انریکو ماسکونی,مطار انريكى موسكونى الدولى العام,ヘネラル・エンリケ・モスコニ国際空港',
    NOW(), NOW()), ('6300564', NULL, 'Esquel Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.90795, -71.13947, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'esquel airport esquel airport argentina ar aeroport d''esquel,aeropuerto de esquel,aéroport d''esquel,eqs,esquel airport,save',
    NOW(), NOW()), ('6300565', NULL, 'Antoine de Saint Exupéry Airport', 'Antoine de Saint Exupery Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.752, -65.03288, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'antoine de saint exupéry airport antoine de saint exupery airport argentina ar aeropuerto antonie de saint exupery,antoine de saint exupery airport,antoine de saint exupéry airport,oes,savn',
    NOW(), NOW()), ('6300567', NULL, 'Almirante Marcos A. Zar Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -43.2105, -65.27032, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'almirante marcos a. zar airport almirante marcos a. zar airport argentina ar aeropuerto almirante marcos a. zar,almirante marcos a. zar airport,rel,savt,trelew aerodrome',
    NOW(), NOW()), ('6300568', NULL, 'Gobernador Edgardo Castello Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.86922, -63.00039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gobernador edgardo castello airport gobernador edgardo castello airport argentina ar savv,vdm',
    NOW(), NOW()), ('6300569', NULL, 'Puerto Madryn, CHT', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.75917, -65.10278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto madryn, cht puerto madryn, cht argentina ar pmy,savy',
    NOW(), NOW()), ('6300571', NULL, 'Puerto Deseado Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -47.73529, -65.9041, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto deseado aerodrome puerto deseado aerodrome argentina ar aeroportul puerto deseado,aeropuerto puerto deseado,lapangan terbang puerto deseado,pud,puerto deseado aerodrome,puerto deseado airport,sawd,aerodrome de puerto deseado,aérodrome de puerto deseado,de sai a duo gang ji chang,frwdgah pwrtw dsyadw,фурудгоҳи пурту дсиоду,فرودگاه پورتو دسیادو,プエルト・デセアド空港,德塞阿多港機場',
    NOW(), NOW()), ('6300572', NULL, 'Hermes Quijada International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -53.77767, -67.74939, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'hermes quijada international airport hermes quijada international airport argentina ar aeroport de rio grande,aeroport international gob. ramon trejo noel,aeropuerto international de rio grande - hermes quijada,aeropuerto international de río grande - hermes quijada,aéroport de río grande,aéroport international gob. ramón trejo noel,flughafen rio grande,flughafen río grande,hermes quijada flughafen,hermes quijada flughafen rio grande,hermes quijada flughafen río grande,hermes quijada international airport,rga,sawe',
    NOW(), NOW()), ('6300573', NULL, 'Piloto Civil Norberto Fernández International Airport', 'Piloto Civil Norberto Fernandez International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -51.60887, -69.31264, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'piloto civil norberto fernández international airport piloto civil norberto fernandez international airport argentina ar aeroport international piloto civil norberto fernandez,aeroporto internacional piloto civil norberto fernandez,aeroporto internacional piloto civil norberto fernández,aeroporto di rio gallegos,aeroporto di río gallegos,aeroportul international piloto civil norberto fernandez,aeroportul internațional piloto civil norberto fernández,aeropuerto internacional piloto civil norberto fernandez,aeropuerto internacional piloto civil norberto fernández,aéroport international piloto civil norberto fernández,flughafen rio gallegos,lapangan terbang norberto fernandez,maes awyr rhyngwladol piloto civil norberto fernandez,maes awyr rhyngwladol piloto civil norberto fernández,piloto civil norberto fernandez international airport,piloto civil norberto fernández international airport,port lotniczy rio gallegos,port lotniczy río gallegos,rgl,rio gallegos aerodrome,sawg,фурудгоҳи бин‌алмилалӣ пилуту сюил нурбрту фрнондз,فرودگاه بین‌المللی پیلوتو سیویل نوربرتو فرناندز,ピロト・シヴィル・ノルベルト・フェルナンデス国際空港,諾韋爾托·費爾南德斯民事飛行員國際機場',
    NOW(), NOW()), ('6300575', NULL, 'Capitán José Daniel Vazquez Airport', 'Capitan Jose Daniel Vazquez Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.30678, -67.80259, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'capitán josé daniel vazquez airport capitan jose daniel vazquez airport argentina ar aeroportul capitan jose daniel vazquez,aeroportul capitán josé daniel vazquez,aeropuerto capitan jose daniel vazquez,aeropuerto capitán josé daniel vázquez,capitan jose daniel vazquez airport,capitán josé daniel vazquez airport,lapangan terbang cap. d. jose d. vasquez,puerto san julian airport,puerto san julián airport,sawj,san julian airport,san julián airport,ula,カピタン・ホセ・ダニエル・バスケス空港',
    NOW(), NOW()), ('6300576', NULL, 'Perito Moreno Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.53791, -70.97869, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'perito moreno aerodrome perito moreno aerodrome argentina ar aeroportul perito moreno,aeropuerto perito moreno,lapangan terbang perito moreno,pmq,perito moreno aerodrome,perito moreno airport,sawp,aerodrome du perito moreno,aérodrome du perito moreno,pei li tuo mo lei nuo ji chang,ペリート・モレノ空港,佩里托莫雷諾機場',
    NOW(), NOW()), ('6300579', NULL, 'Azul Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.83821, -59.88081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'azul airport azul airport argentina ar aerodromo de azul,aeroportul azul,aeródromo de azul,azul airport,saza,a su er ji chang,asuru kong gang,アスル空港,阿蘇爾機場',
    NOW(), NOW()), ('6300580', NULL, 'Comandante Espora Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.72868, -62.15301, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comandante espora airport comandante espora airport argentina ar aeroport commandant espora,aeropuerto comandante espora,aéroport commandant espora,bhi,bahia blanca airport,bahía blanca airport,comandante espora airport,sazb,frwdgah kmandanth aspwr,فرودگاه کماندانته اسپور',
    NOW(), NOW()), ('6300582', NULL, 'Pigue Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.6, -62.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pigue aerodrome pigue aerodrome argentina ar aerodromo piguee,aeródromo pigüé,piguee airport,pigüé airport,saze',
    NOW(), NOW()), ('6300583', NULL, 'General Pico Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.69618, -63.75829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'general pico airport general pico airport argentina ar aeroportul general pico,aeropuerto de general pico,gpo,general pico airport,lapangan terbang general pico,sazg,aerodrome de general pico,aérodrome de general pico,frwdgah zhnral pykw,pi ke jiang jun ji chang,фурудгоҳи жинирол пику,فرودگاه ژنرال پیکو,ヘネラル・ピコ空港,皮科將軍機場',
    NOW(), NOW()), ('6300586', NULL, 'Presidente Perón International Airport', 'Presidente Peron International Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.949, -68.15571, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'presidente perón international airport presidente peron international airport argentina ar nqn,presidente peron international airport,presidente perón international airport,sazn',
    NOW(), NOW()), ('6300587', NULL, 'Comodoro Pedro Zanni Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.84459, -61.85755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comodoro pedro zanni airport comodoro pedro zanni airport argentina ar aeroportul comodoro p. zanni,aeropuerto comodoro p. zanni,comodoro p. zanni airport,comodoro pedro zanni airport,lapangan terbang comodoro p. zanni,peh,pehuajo airport,pehuajó airport,sazp,komodoro p. san''ni kong gang,コモドロ p. サンニ空港',
    NOW(), NOW()), ('6300588', NULL, 'Río Colorado Airport', 'Rio Colorado Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.99518, -64.14029, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'río colorado airport rio colorado airport argentina ar aeroportul rio colorado,aeroportul río colorado,lapangan terbang rio colorado,rio colorado,rio colorado airport,río colorado,río colorado airport,sazq,リオ・コロラド空港',
    NOW(), NOW()), ('6300590', NULL, 'Bariloche Aerodrome', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -41.15117, -71.15754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bariloche aerodrome bariloche aerodrome argentina ar aeroport de san carlos de bariloche,aeroporto internacional teniente luis candelaria,aeroporto internazionale di san carlos de bariloche,aeroporto de san carlos de bariloche,aeroportul san carlos de bariloche,aeropuerto de san carlos de bariloche,aéroport de san carlos de bariloche,brc,bandar udara internasional teniente luis candelaria,bariloche aerodrome,flughafen teniente luis candelaria bariloche,lapangan terbang antarabangsa teniente luis candelaria,maes awyr san carlos de bariloche,port lotniczy bariloche,sazs,san carlos de bariloche airport,san bay quoc te teniente luis candelaria,sân bay quốc tế teniente luis candelaria,sheng ka luo si-de ba li luo qie ji chang,фурудгоҳи бин‌алмилалӣ тнинтҳ лӯйес кндлорио,נמל התעופה הבינלאומי טניאנטה לואיס קנדלריה,فرودگاه بین‌المللی تنینته لوییس کندلاریا,サン・カルロス・デ・バリローチェ空港,聖卡洛斯-德巴里洛切機場',
    NOW(), NOW()), ('6300592', NULL, 'Villa Gesell Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.23541, -57.02924, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa gesell airport villa gesell airport argentina ar aeropuerto de villa gesell,sazv,san bay quoc te villa gesell - pinamar,sân bay quốc tế villa gesell - pinamar,vlg,villa gesell airport',
    NOW(), NOW()), ('6301847', NULL, 'Jorge Newbery Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.55918, -58.41561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jorge newbery airport jorge newbery airport argentina ar aep,aerodromio chorche nioumperi,aeroparque jorge newbery,aeroport khorkhe n''juberi,bandar udara jorge newbery,flughafen buenos aires-jorge newbery,jorge newbery airport,jorge newbery oro uostas,khorkhe n''juberi,lapangan terbang jorge newbery aeroparque,letisko jorgeho newberyho,letiste jorgeho newberyho,letiště jorgeho newberyho,port lotniczy jorge newbery,sabe,san bay jorge newbery,sân bay jorge newbery,a-elopaleuke holeuhenyubeli,aeroport jorge-newbery,aéroport jorge-newbery,mhlh hwayy ywrg nwbry,αεροδρόμιο χόρχε νιούμπερι,аеропорт хорхе ньюбері,маҳалла ҳаво юрг нубри,хорхе ньюбери,נמל התעופה חורחה ניוברי,محله هوایی یورگ نوبری,ホルヘ・ニューベリー空港,乔治·纽伯里机场,豪爾赫·紐伯里機場,豪爾赫·紐貝里機場,아에로파르케 호르헤뉴베리',
    NOW(), NOW()), ('6301848', NULL, 'San Fernando Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.45306, -58.58972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san fernando airport san fernando airport argentina ar aeroporto de san fernando,aeroportul san fernando,aeropuerto internacional de san fernando,lapangan terbang antarabangsa san fernando,sadf,san fernando,san fernando airport,aeroport international de san fernando,aéroport international de san fernando,frwdgah sn frnandw,mtar san frnandw,sheng fei er nan duo ji chang,фурудгоҳи син фрнонду,فرودگاه سن فرناندو,مطار سان فرناندو,サン・フェルナンド空港,聖費爾南多機場',
    NOW(), NOW()), ('6301849', NULL, 'El Palomar Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.60994, -58.61259, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el palomar airport el palomar airport argentina ar aeroport d''el palomar,aeroporto di el palomar,aeroportul el palomar,aeropuerto el palomar,aéroport d''el palomar,epa,el palomar airport,flughafen buenos aires-el palomar,lapangan terbang el palomar,sadp,ai er pa luo ma ji chang,frwdgah al palwmar,фурудгоҳи ил полумор,فرودگاه ال پالومار,エル・パロマル空港,埃爾帕洛馬機場',
    NOW(), NOW()), ('6301850', NULL, 'El Bolsón Airport', 'El Bolson Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -41.94319, -71.53229, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el bolsón airport el bolson airport argentina ar aeropuerto de el bolson,aeropuerto de el bolsón,ehl,el bolson airport,el bolsón airport,savb',
    NOW(), NOW()), ('6354982', NULL, 'Bus Terminal', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.89505, -68.83033, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bus terminal bus terminal argentina ar',
    NOW(), NOW()), ('6525769', NULL, 'Hosteria Puerto San Julian', 'HOSTERIA PUERTO SAN JULIAN',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.02676, -68.88014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hosteria puerto san julian hosteria puerto san julian argentina ar',
    NOW(), NOW()), ('6942822', NULL, 'Terminal de Omnibus Gral. Belgrano, SFE', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.64316, -60.7003, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal de omnibus gral. belgrano, sfe terminal de omnibus gral. belgrano, sfe argentina ar',
    NOW(), NOW()), ('6942869', NULL, 'Nueva Terminal de Rafaela', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.2412, -61.50667, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'nueva terminal de rafaela nueva terminal de rafaela argentina ar',
    NOW(), NOW()), ('6942914', NULL, 'Acceso Terminal Santa Fe', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.64197, -60.69987, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'acceso terminal santa fe acceso terminal santa fe argentina ar',
    NOW(), NOW());