INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('1134594', NULL, 'Lakah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.201, 63.29701, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lakah sang lakah sang afghanistan af lakah sang,lokasang,lokeh sang,lokka,luka sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134595', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.76534, 64.78793, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokasang,lokehsang,lukah sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134596', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.51964, 64.10149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokasang,lokehsang,lukah sang,lukasang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134599', NULL, 'Lōkānō Ḏab', 'Lokano Dab',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.59945, 63.5421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lōkānō ḏab lokano dab afghanistan af lokano d`ab,lokano dab,lukanu dab,lōkāno d‘ab,lōkānō ḏab,lūkānū dab ,لوکانو ډب',
    NOW(), NOW()), ('1134600', NULL, 'Lukah-ye Khwājak', 'Lukah-ye Khwajak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.52637, 65.10808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye khwājak lukah-ye khwajak afghanistan af loka-i-khwajak,loka-i-khwājak,lokah-ye khvajak,lokah-ye khvājak,lukah-ye khwajak,lukah-ye khwājak,لکۀ خواجک',
    NOW(), NOW()), ('1134601', NULL, 'Lōkā Khēl', 'Loka Khel',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.01634, 69.71869, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lōkā khēl loka khel afghanistan af loka khel,lokakhejl'',lokakhel,lokakheyl'',lokakheyl’,lukakhel,lukakheyl,lōkā khēl,lōkākhēl,lūkākheyl,lūkākhēl,lwka khyl,локахейль,لوكا خيل,لوکا خېل',
    NOW(), NOW()), ('1134892', NULL, 'Lālō Kalā', 'Lalo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.49764, 68.77206, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lālō kalā lalo kala afghanistan af lalo kala,lalow kala,lalow qal`eh,lalu,lalu kala,lalu qala,lālo kalā,lālow kalā,lālow qal‘eh,lālō kalā,razvaliny lalukala,lalw kla,لالو کلا',
    NOW(), NOW()), ('1134919', NULL, 'Lālī Māndêh', 'Lali Mandeh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.65528, 67.07627, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lālī māndêh lali mandeh afghanistan af lali mandah,lali mandeh,lalimandekh,lāli māndah,lāli mānḏeh,lālī māndêh,jwy laly,laly mandh,جوئ لالی,لالی مانده',
    NOW(), NOW()), ('1134986', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.13099, 64.46718, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af gora lukasang,lakasang,lokasang,lokehsang,lukah sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1135980', NULL, 'Khōshāmand', 'Khoshamand',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.68567, 68.23801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'khōshāmand khoshamand afghanistan af khosamand,khoshamand,khos̄āmanḏ,khus amad,khusamand,khush amad,khushamand,khus̄ āmad,khus̄āmand,khvosh amad,khvosh mand,khvosh āmad,khvoshamand,khvoshāmand,khōshāmand,khūsh āmad,khwsh amd,khwshamnd,خوش آمد,خوشامند',
    NOW(), NOW()), ('1138454', NULL, 'Kharābah-ye Kamāl Khān', 'Kharabah-ye Kamal Khan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.30713, 61.87042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kharābah-ye kamāl khān kharabah-ye kamal khan afghanistan af band-i-kamal khan,band-i-kamāl khan,bandar-i-kamal khan,bandar-i-kamāl khān,kharabah-ye kamal khan,kharabeh-ye kamal khan,kharābah-ye kamāl khān,kharābeh-ye kamāl khān,خرابۀ کمال خان',
    NOW(), NOW()), ('1138457', NULL, 'Kalātah-ye Kamāl Khān', 'Kalatah-ye Kamal Khan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.3053, 61.89575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalātah-ye kamāl khān kalatah-ye kamal khan afghanistan af bandar-i-kamal khan,bandar-i-kamāl khān,kalatah-ye kamal khan,kalate kamal khan,kalātah-ye kamāl khān,kalātē kamāl khān,kamal khan,kamal khan bandar,kamāl khān,kamāl khān bandar,کلاتۀ کمال خان',
    NOW(), NOW()), ('1139106', NULL, 'Kōh-e Jōlōgah', 'Koh-e Jologah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.84591, 62.35355, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e jōlōgah koh-e jologah afghanistan af gory dzhuluka,koh-e jologah,koh-e julukah,kohe jologa,kohe juluka,kohe jōlōga,kohe jūlūka,kuh-e jologa,kuh-e jowlugah,kōh-e jōlōgah,kōh-e jūlūkah,kūh-e jowlūgah,kūh-e jōlōga,kwh jwlwgh,kwh jwlwkh,کوه جولوکه,کوه جولوگه',
    NOW(), NOW()), ('1142562', NULL, 'Ilman-e Ūchownah', 'Ilman-e Uchownah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.72245, 66.78947, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilman-e ūchownah ilman-e uchownah afghanistan af elman-e uchawnah,elman-i-uchawna,il''mani-uchavna,ilman-e uchownah,ilman-e ūchownah,il’mani-uchavna,almn awchwnh,ильмани-учавна,المن اوچونه',
    NOW(), NOW()), ('1144490', NULL, 'Dahan-e Lūkah Sang', 'Dahan-e Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.57912, 65.93241, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dahan-e lūkah sang dahan-e lukah sang afghanistan af dahan-e lukah sang,dahan-e lukasang,dahan-e lūkah sang,dahan-e lūkasang,dhn lwkh sng,دهن لوکه سنگ',
    NOW(), NOW()), ('1144715', NULL, 'Dahan Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.04475, 65.73356, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dahan bandar dahan bandar afghanistan af dahan bandar,dakhanbandar,dhn bndr,دهن بندر',
    NOW(), NOW()), ('1145863', NULL, 'Chahār Burjak', 'Chahar Burjak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.38914, 62.13086, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chahār burjak chahar burjak afghanistan af caharburjak,chahar burjak,chaharborjak,chahār burjak,chahārborjak,chakharburdzhak,chhar brjk,chharbrjk,čahārburjak,چهار برجک,چهاربرجك',
    NOW(), NOW()), ('1145864', NULL, 'Chahār Burjah', 'Chahar Burjah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.23555, 67.03381, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chahār burjah chahar burjah afghanistan af caharburja,cahāṟbuṟja,chahar borjeh,chahar burjah,chaharborja,chahār borjeh,chahār burjah,chahārborja,chhar brjh,چهار برجه',
    NOW(), NOW()), ('1146335', NULL, 'Bulōkah', 'Bulokah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.3248, 65.86064, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bulōkah bulokah afghanistan af boloka,boluka,bolōka,bolūka,bulokah,bulōkah,blwkh,بلوکه',
    NOW(), NOW()), ('1146499', NULL, 'Bīābān Darah', 'Biaban Darah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.44983, 65.92394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bīābān darah biaban darah afghanistan af biaban darah,biaban darreh,biabandarra,byaban darrah,byābān ḏaṟṟah,bīābān darah,bīābān darreh,byaban darah,byaban drh,بيابان دَرَه,بیابان دره',
    NOW(), NOW()), ('1146559', NULL, 'Bindaray', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.05583, 68.44039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bindaray bindaray afghanistan af bandaray,banḏaṟay,bendaray,bindaray,bndry,بندری',
    NOW(), NOW()), ('1146965', NULL, 'Bar Gulō Kalā', 'Bar Gulo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.6511, 69.23363, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bar gulō kalā bar gulo kala afghanistan af bar golo kala,bar golo kalā,bar gulo kala,bar gulō kalā,bar-gulukala,br glw kla,بر گلو كلا,بر گلو کلا',
    NOW(), NOW()), ('1147209', NULL, 'Kōh-e Bandar Ghūnak', 'Koh-e Bandar Ghunak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.67171, 65.1245, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e bandar ghūnak koh-e bandar ghunak afghanistan af koh-e bandar ghunak,kohe bandarghunak,kohe banḏaṟghūnak,kuh-e bandarghunak,kōh-e bandar ghūnak,kūh-e bandarghūnak,kwh bndrghwnk,کوه بندرغونک',
    NOW(), NOW()), ('1147210', NULL, 'Bandar Ghūnak', 'Bandar Ghunak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.65932, 65.1341, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar ghūnak bandar ghunak afghanistan af bandar ghunak,bandar ghūnak,bandarghunak,banḏaṟghūnak,bndrghwnk,بندرغونک',
    NOW(), NOW()), ('1147211', NULL, 'Bandar-e Wasaţī', 'Bandar-e Wasati',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.28893, 61.90769, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e wasaţī bandar-e wasati afghanistan af bandar-e vasati,bandar-e vasaţī,bandar-e wasati,bandar-e wasaţī,bandare wasate,bandare wasati,banḏaṟe wasaṯē,banḏaṟe wasaṯī,bndr wsty,بندر وسطی',
    NOW(), NOW()), ('1147212', NULL, 'Bandar-e Shamālī', 'Bandar-e Shamali',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.29444, 61.90697, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e shamālī bandar-e shamali afghanistan af bandar-e shamali,bandar-e shamālī,bandar-e shomali,bandar-e shomālī,bandare samali,bandare šamālī,bndr shmaly,بندر شمالی',
    NOW(), NOW()), ('1147213', NULL, 'Bandar-e Mullāhā', 'Bandar-e Mullaha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.35648, 64.58443, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e mullāhā bandar-e mullaha afghanistan af bandar,bandar-e mollaha,bandar-e mollāhā,bandar-e mullaha,bandar-e mullāhā,bandar-i-mullaha,banḏaṟ-i-mullāhā,bndr mla ha,بندر ملا ها',
    NOW(), NOW()), ('1147214', NULL, 'Bandar-e Junūbī', 'Bandar-e Junubi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.28385, 61.93471, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e junūbī bandar-e junubi afghanistan af bandar-e jonubi,bandar-e jonūbī,bandar-e junubi,bandar-e junūbī,bandare janubi,banḏaṟe janūbī,bndr jnwby,بندر جنوبی',
    NOW(), NOW()), ('1147215', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.33672, 64.58087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi,bandar-e `abdul baqi,bandar-e ‘abd ol bāqī,bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi,bandar-i-`abdulbaqi (1),banḏaṟ-i-‘abdulbāqī,banḏaṟ-i-‘abdulbāqī (1),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1147216', NULL, 'Bandar Darah', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.06394, 70.76343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar darah bandar darah afghanistan af bandar darah,bandar darreh,dolina bandardarra,bndr drh,بندر دره,درۀ بندر',
    NOW(), NOW()), ('1147217', NULL, 'Tahānah-ye Bandar', 'Tahanah-ye Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.22056, 71.15775, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tahānah-ye bandar tahanah-ye bandar afghanistan af tahana-i-bandar,tahanah-ye bandar,tahaneh-ye bandar,tahāna-i-banḏar,tahānah-ye bandar,tahāneh-ye bandar,thanh y bndr,تهانه ی بندر',
    NOW(), NOW()), ('1148845', NULL, 'Alō Kalā', 'Alo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.29736, 68.26636, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alō kalā alo kala afghanistan af alo kala,alo kalā,alukala,alō kalā,alw kla,الو کلا,قلعهٔٔ الو',
    NOW(), NOW()), ('1148924', NULL, '‘Alī Manşūr', '''Ali Mansur',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.48402, 62.61785, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘alī manşūr ''ali mansur afghanistan af alimansur,`ali mansur,علی منصور,‘alī manşūr',
    NOW(), NOW()), ('1148925', NULL, '‘Alī Manşūr', '''Ali Mansur',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.46579, 62.27037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘alī manşūr ''ali mansur afghanistan af letnik alimansur,`ali mansur,علی منصور,‘alī manşūr',
    NOW(), NOW()), ('1423713', NULL, 'Maimana Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.93034, 64.76132, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maimana airport maimana airport afghanistan af mmz,maimana airport,maimanah airport,maymaneh airport,maīmanah airport,oamn',
    NOW(), NOW()), ('1423933', NULL, 'Dablukanṯāl Ghar', 'Dablukantal Ghar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34343, 71.11074, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dablukanṯāl ghar dablukantal ghar afghanistan af dablukantal ghar,dablukanṯāl ghar,gora dablukantal''gar,gora dablukantal’gar,kwh dblkntal,دبلکنټال غر,كوهٔ دبلكنتال,ḏablukantāl ghar',
    NOW(), NOW()), ('1424203', NULL, 'Tapah-ye Lūkah', 'Tapah-ye Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.69658, 63.46661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tapah-ye lūkah tapah-ye lukah afghanistan af tapa-i-iuka,tapa-i-iūka,tapah-ye lukah,tapah-ye lūkah,tappeh-ye yowkah,تپۀ لوکه',
    NOW(), NOW()), ('1424430', NULL, 'Lūkah-ye Jigarīhā', 'Lukah-ye Jigariha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.06858, 64.52708, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye jigarīhā lukah-ye jigariha afghanistan af luka-i-jegariha,lukah-e jegariha,lukah-ye jigariha,lūka-i-jegaṟihā,lūkah-e jegarīhā,lūkah-ye jigarīhā,لوکۀ جگری ها',
    NOW(), NOW()), ('1424435', NULL, 'Lūkah-ye Dūrānī', 'Lukah-ye Durani',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.09668, 64.51856, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye dūrānī lukah-ye durani afghanistan af luka-i-durrani,lukah-e dorrani,lukah-ye durani,lūka-i-ḏuṟṟāni,lūkah-e dorrānī,lūkah-ye dūrānī,لوکۀ دورانی',
    NOW(), NOW()), ('1424507', NULL, 'Lūkah-ye Ḩowẕhā-ye Buz', 'Lukah-ye Howzha-ye Buz',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.08685, 64.66376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye ḩowẕhā-ye buz lukah-ye howzha-ye buz afghanistan af luka-i-hawdzha-i-buz,lukah-e howzha-ye boz,lukah-ye howzha-ye buz,lūka-i-ḩawḏẕhā-i-buz,lūkah-e ḩowẕhā-ye boz,lūkah-ye ḩowẕhā-ye buz,لوکۀ حوض های بز',
    NOW(), NOW()), ('1424508', NULL, 'Lūkah-ye Quranghay', 'Lukah-ye Quranghay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.08916, 64.64684, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye quranghay lukah-ye quranghay afghanistan af luka-i-qoranghay,lukah-e qoranghay,lukah-ye quranghay,lūka-i-qoṟanghay,lūkah-e qoranghay,lūkah-ye quranghay,لوکۀ قرنغی',
    NOW(), NOW()), ('1424519', NULL, 'Lūkah-ye Chāh-e Buzkash', 'Lukah-ye Chah-e Buzkash',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.10179, 64.64257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye chāh-e buzkash lukah-ye chah-e buzkash afghanistan af luka-i-cahe buzkas,lukah-e chah-e bozkash,lukah-ye chah-e buzkash,lūka-i-cāhe buzkās,lūkah-e chāh-e bozkāsh,lūkah-ye chāh-e buzkash,لوکۀ چاه بز کش',
    NOW(), NOW()), ('1424681', NULL, 'Manţaqah-ye Bandar', 'Mantaqah-ye Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34306, 64.58667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manţaqah-ye bandar mantaqah-ye bandar afghanistan af mantaqa-i-bandar,mantaqa-i-banḏaṟ,mantaqah-ye bandar,mantaqeh-ye bandar,manţaqah-ye bandar,manţaqeh-ye bandar,mntqh bndr,منطقه بندر',
    NOW(), NOW()), ('1424684', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34716, 64.57879, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi (3),bandar-e `abdul baqi,bandar-e ‘abd ol bāqī (3),bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi (3),banḏaṟ-i-‘abdulbāqī (3),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1424685', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.3579, 64.56267, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi (2),bandar-e `abdul baqi,bandar-e ‘abd ol bāqī (2),bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi (2),banḏaṟ-i-‘abdulbāqī (2),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1425130', NULL, 'Lês̲h̲ōlō Kêlay', 'Lesholo Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.86401, 69.63468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lês̲h̲ōlō kêlay lesholo kelay afghanistan af lesholo kelay,lesholokay,lesholukalay,leshowlo kalay,lesolo kalay,les̲h̲owlo kalay,lês̲h̲ōlō kêlay,lês̲h̲ōlōkay,lěšolo kalay,لښولو کلی,لښولوکی',
    NOW(), NOW()), ('1434136', NULL, 'Urgun Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.93222, 69.15639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'urgun airport urgun airport afghanistan af oaog,urn,urgun,urgun airport',
    NOW(), NOW()), ('1434427', NULL, '‘Ālimān Kōṯkay', '''Aliman Kotkay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.25147, 69.87035, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘ālimān kōṯkay ''aliman kotkay afghanistan af alemankotkay,`aleman kotkay,`aleman kotkey,`aleman kowtkay,`aliman kotkay,عالمان كوتكی,عالمان کوټکی,‘ālemān kowtkay,‘ālemān kōtkay,‘ālimān kōṯkay,‘ālêmān kōṯkêy',
    NOW(), NOW()), ('1434618', NULL, 'Khost International Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.33359, 69.95192, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'khost international airport khost international airport afghanistan af kht,khost,khost airfield,matun,matun airfield,mātūn airfield,oaks,mydan hwayy khwst,ميدانٔٔ هوائئ خوست',
    NOW(), NOW()), ('1434876', NULL, 'Malōkān', 'Malokan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.44123, 69.10739, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'malōkān malokan afghanistan af malokan,malukan,malōkān,malūkān,malwkan,mlwkan,مالوكان,ملوکان',
    NOW(), NOW());