INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('7668714', NULL, 'Clarence Valley Regional Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.7594, 153.03, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clarence valley regional airport clarence valley regional airport australia au clarence valley regional airport,gfn,grafton airport,ygfn',
    NOW(), NOW()), ('7668715', NULL, 'Geelong Airport (historical)', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.225, 144.33299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'geelong airport (historical) geelong airport (historical) australia au gex,geelong airport,yglg',
    NOW(), NOW()), ('7668716', NULL, 'Glen Innes Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.675, 151.689, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'glen innes airport glen innes airport australia au gli,ygli',
    NOW(), NOW()), ('7668717', NULL, 'Griffith Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.2508, 146.067, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'griffith airport griffith airport australia au gff,ygth',
    NOW(), NOW()), ('7668718', NULL, 'Gympie Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.2828, 152.702, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gympie airport gympie airport australia au aeroportul gympie,gyp,gympie airport,lapangan terbang gympie,ygym,frwdgah gympy,фурудгоҳи гимпи,فرودگاه گیمپی',
    NOW(), NOW()), ('7668719', NULL, 'Hay Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5314, 144.83, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hay airport hay airport australia au aeroportul hay,bandar udara hay,flughafen hay,hxx,hay,hay airport,lapangan terbang hay,yhay,aeroport de hay,aeroporto di hay,aéroport de hay,frwdgah hy,фурудгоҳи ҳий,فرودگاه هی',
    NOW(), NOW()), ('7668720', NULL, 'Horn Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.5864, 142.28999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horn island airport horn island airport australia au aeroportul horn island,hid,horn island airport,khorn-ajlend,lapangan terbang horn i,yhid,aeroport de thursday island,aéroport de thursday island,frwdgah hrn aylnd,hon dao kong gang,huo en dao ji chang,фурудгоҳи ҳрн оилнд,хорн-айленд,فرودگاه هرن آیلند,ホーン島空港,霍恩岛机场,霍恩島機場',
    NOW(), NOW()), ('7668721', NULL, 'Halls Creek Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.2339, 127.67, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'halls creek airport halls creek airport australia au aeroportul halls creek,hcq,halls creek airport,lapangan terbang halls creek,port lotniczy halls creek,yhlc,aeroport de halls creek,aeroporto di halls creek,aéroport de halls creek,frwdgah hl kryk,фурудгоҳи ҳштн крик,فرودگاه هل کریک',
    NOW(), NOW()), ('7668722', NULL, 'Mount Hotham Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.0475, 147.334, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount hotham airport mount hotham airport australia au aeroportul mount hotham,lapangan terbang mt hotham,mhu,maunt gotem,maunt-khotehm,mount hotham airport,yhot,frwdgah mawnt hwtham,маунт готем,маунт-хотэм,فرودگاه ماونت هوتهام',
    NOW(), NOW()), ('7668723', NULL, 'Hopetoun Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.7153, 142.36, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hopetoun airport hopetoun airport australia au aeroportul hopetoun,htu,hopetoun airport,lapangan terbang hopetoun,yhpn,aeroporto di hopetoun,aeropuerto de hopetoun,frwdgah hptwn,фурудгоҳи ҳптун,فرودگاه هپتون',
    NOW(), NOW()), ('7668724', NULL, 'Horsham Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.6697, 142.173, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horsham airport horsham airport australia au aeroportul horsham,flughafen horsham,hsm,horsham,horsham airport,lapangan terbang horsham,yhsm,aeroporto di horsham,frwdgah hwrsham,фурудгоҳи ҳуршом,فرودگاه هورشام',
    NOW(), NOW()), ('7668725', NULL, 'Inverell Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.8883, 151.144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inverell airport inverell airport australia au aeroportul inverell,bandar udara inverell,flughafen inverell,ivr,inverell,inverell airport,lapangan terbang inverell,yivl,aeroport de inverell,aeroporto di inverell,aéroport de inverell,frwdgah aynwrl,фурудгоҳи оинурл,فرودگاه اینورل',
    NOW(), NOW()), ('7668726', NULL, 'Kalbarri Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.68892, 114.25919, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalbarri airport kalbarri airport australia au aeroport de kalbarri,aéroport de kalbarri,kax,kalbarri airport,ykbr',
    NOW(), NOW()), ('7668727', NULL, 'Streaky Bay Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.8358, 134.293, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'streaky bay airport streaky bay airport australia au aeroportul streaky bay,kby,lapangan terbang streaky bay,streaky bay airport,ykby,aeroport de streaky bay,aeroporto di streaky bay,aeropuerto de streaky bay,aéroport de streaky bay,frwdgah khlyj astryky,фурудгоҳи халеҷ острики,فرودگاه خلیج استریکی',
    NOW(), NOW()), ('7668728', NULL, 'Kerang Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.7514, 143.939, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kerang airport kerang airport australia au aeroportul kerang,flughafen kerang,kra,kerang,kerang airport,lapangan terbang kerang,yker,aeroport de kerang,aeroporto di kerang,aéroport de kerang,frwdgah krng,фурудгоҳи крнг,فرودگاه کرنگ',
    NOW(), NOW()), ('7668729', NULL, 'King Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -39.87796, 143.88258, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'king island airport king island airport australia au kns,king island airport,ykii',
    NOW(), NOW()), ('7668730', NULL, 'Leonora Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.8781, 121.315, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leonora airport leonora airport australia au aeroportul leonora,lno,lapangan terbang leonora,leonora airport,yleo,aerodrome de leonora,aérodrome de leonora,frwdgah lywnwra,фурудгоҳи леҳвнуро,فرودگاه لئونورا',
    NOW(), NOW()), ('7668731', NULL, 'Lord Howe Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.54036, 159.07843, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lord howe island airport lord howe island airport australia au flugplatz lord-howe-insel,ldh,ylhi',
    NOW(), NOW()), ('7668732', NULL, 'Lockhart River Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.7869, 143.30499, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lockhart river airport lockhart river airport australia au aeroportul lockhart river,irg,lapangan terbang lockhart river,lockhart river airport,ylhr,aeroport de lockhart river,aéroport de lockhart river,frwdgah rwdkhanh lwkhart,rokkuhatoriba kong gang,фурудгоҳи рӯдхона лухорт,فرودگاه رودخانه لوخارت,ロックハートリバー空港',
    NOW(), NOW()), ('7668733', NULL, 'Lismore Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.8303, 153.25999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lismore airport lismore airport australia au lsy,ylis',
    NOW(), NOW()), ('7668734', NULL, 'Lightning Ridge Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.4567, 147.98399, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lightning ridge airport lightning ridge airport australia au aeroportul lightning ridge,flughafen lightning ridge,lhg,lapangan terbang lightning ridge,lightning ridge,lightning ridge airport,ylrd,aeroport de lightning ridge,aeroporto di lightning ridge,aéroport de lightning ridge,frwdgah laytnyng ryj,фурудгоҳи лоитинг риҷ,فرودگاه لایتنینگ ریج',
    NOW(), NOW()), ('7668735', NULL, 'Leinster Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.8433, 120.703, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leinster airport leinster airport australia au aeroportul leinster,ler,lapangan terbang leinster,leinster airport,lenster,ylst,frwdgah lynstr,ленстер,фурудгоҳи линстр,فرودگاه لینستر',
    NOW(), NOW()), ('7668736', NULL, 'Laverton Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.61564, 122.424, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laverton airport laverton airport australia au lvo,yltn',
    NOW(), NOW()), ('7668737', NULL, 'Latrobe Regional Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.2072, 146.47, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'latrobe regional airport latrobe regional airport australia au aeroportul latrobe valley,flughafen latrobe,lapangan terbang latrobe valley,latrobe regional airport,latrobe valley,latrobe valley airport,tgn,yltv,aeroporto di latrobe valley,frwdgah ltrwb wly,ratorobu,фурудгоҳи лтруб вли,فرودگاه لتروب ولی,ラトローブ',
    NOW(), NOW()), ('7668738', NULL, 'Mareeba Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.0692, 145.41901, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mareeba airport mareeba airport australia au mrg,ymba',
    NOW(), NOW()), ('7668739', NULL, 'Mallacoota Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.5983, 149.72, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mallacoota airport mallacoota airport australia au aeroportul mallacoota,flughafen mallacoota,mallacoota,mallacoota airport,xmc,ymco,aeroport de mallacoota,aeroporto di mallacoota,aéroport de mallacoota,frwdgah malakwta,فرودگاه مالاکوتا',
    NOW(), NOW()), ('7668740', NULL, 'Mudgee Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5625, 149.61099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mudgee airport mudgee airport australia au aeroportul mudgee,dge,lapangan terbang mudgee,mudgee,mudgee airport,ymdg,aeroport de mudgee,aeroporto di mudgee,aéroport de mudgee,frwdgah mwdgy,ma qi ji chang,majji kong gang,фурудгоҳи мудги,فرودگاه مودگی,マッジー空港,馬奇機場',
    NOW(), NOW()), ('7668741', NULL, 'Merimbula Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.9086, 149.901, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'merimbula airport merimbula airport australia au aeroportul merimbula,lapangan terbang merimbula,mim,merimbula,merimbula airport,ymer,aeroport de merimbula,aeroporto di merimbula,aéroport de merimbula,frwdgah mrymbwla,merinbura kong gang,фурудгоҳи мримбуло,فرودگاه مریمبولا,メリンブラ空港',
    NOW(), NOW()), ('7668742', NULL, 'Mount Magnet Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.1161, 117.842, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount magnet airport mount magnet airport australia au aeroportul mount magnet,flugplatz mount magnet,lapangan terbang mount magnet,mmg,maunt-magnet,mount magnet airport,ymog,frwdgah mawnt mgnyt,маунт-магнет,фурудгоҳи мовнт мгнит,فرودگاه ماونت مگنیت',
    NOW(), NOW()), ('7668743', NULL, 'Moree Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.4989, 149.845, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moree airport moree airport australia au aeroportul moree,lapangan terbang moree,mrz,moree,moree airport,ymor,aeroport de moree,aeroporto di moree,aéroport de moree,frwdgah mwry,mo li ji chang,mori kong gang,фурудгоҳи мӯр,فرودگاه موری,モリー空港,莫里机场,莫里機場',
    NOW(), NOW()), ('7668744', NULL, 'Moruya Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.8978, 150.144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moruya airport moruya airport australia au aeroportul moruya,lapangan terbang moruya,mya,moruya,moruya airport,ymry,aeroport de moruya,aeroporto di moruya,aéroport de moruya,frwdgah mwrwya,moruya kong gang,فرودگاه مورویا,モルヤ空港',
    NOW(), NOW()), ('7668745', NULL, 'Muttaburra Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.5833, 144.533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'muttaburra airport muttaburra airport australia au utb,ymtb',
    NOW(), NOW()), ('7668746', NULL, 'Mount Gambier Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.7456, 140.785, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount gambier airport mount gambier airport australia au lapangan terbang mount gambier,mgb,mount gambier airport,port lotniczy mount gambier,ymtg,aeroport de mount gambier,aeroporto di mount gambier,aeropuerto de mount gambier,aéroport de mount gambier,frwdgah mawnt gmbyr,gan bi er shan ji chang,mauntoganbia kong gang,فرودگاه ماونت گمبیر,マウントガンビア空港,甘比爾山機場',
    NOW(), NOW()), ('7668747', NULL, 'Murray Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -9.91667, 144.05499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'murray island airport murray island airport australia au myi,ymae',
    NOW(), NOW()), ('7668748', NULL, 'Maryborough Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.5133, 152.715, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maryborough airport maryborough airport australia au aeroportul maryborough,lapangan terbang maryborough,mbh,maryborough airport,ymyb,aerodrome de maryborough,aérodrome de maryborough,فرودگاه ماری‌براوت',
    NOW(), NOW()), ('7668749', NULL, 'Narrabri Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.3192, 149.827, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'narrabri airport narrabri airport australia au aeroportul narrabri,lapangan terbang narrabri,naa,narrabri,narrabri airport,ynbr,aeroport de narrabri,aeroporto di narrabri,aéroport de narrabri,frwdgah narrabry,naraburi kong gang,фурудгоҳи норробри,فرودگاه ناررابری,ナラブリ空港',
    NOW(), NOW()), ('7668750', NULL, 'Narromine Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.2147, 148.22501, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'narromine airport narromine airport australia au aeroportul narromine,lapangan terbang narromine,letiste narromine,letiště narromine,narromine,narromine airport,qrm,ynrm,aeroport de narromine,aeroporto di narromine,aéroport de narromine,frwdgah narwmayn,naromain kong gang,фурудгоҳи норумоин,فرودگاه ناروماین,ナロマイン空港',
    NOW(), NOW()), ('7668751', NULL, 'Newman Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.4178, 119.803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newman airport newman airport australia au aeroportul newman,bandar udara newman,lapangan terbang newman,newman airport,port lotniczy newman,ynwn,zne,aeroport de newman,aéroport de newman,frwdgah nywmn,niu man,niu man ji chang,فرودگاه نیومن,紐曼,纽曼机场',
    NOW(), NOW()), ('7668752', NULL, 'Nyngan Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.5511, 147.203, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nyngan airport nyngan airport australia au aeroportul nyngan,bandar udara nyngan,flughafen nyngan,lapangan terbang nyngan,nyn,nyngan,nyngan airport,ynyn,aeroport de nyngan,aeroporto di nyngan,aéroport de nyngan,frwdgah nyngan,фурудгоҳи нингон,فرودگاه نینگان',
    NOW(), NOW()), ('7668753', NULL, 'Olympic Dam Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.485, 136.877, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic dam airport olympic dam airport australia au aeroportul olympic dam,lapangan terbang olympic dam,olp,olimpik dam,olympic dam,olympic dam airport,yold,aerodrome d''olympic dam,ao lin pi ke ba ji chang,aérodrome d''olympic dam,frwdgah almpyk dm,олімпік дам,фурудгоҳи улампек дам,فرودگاه المپیک دم,奧林匹克壩機場',
    NOW(), NOW()), ('7668754', NULL, 'Orange Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3817, 149.133, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'orange airport orange airport australia au aeroportul orange,flughafen orange,lapangan terbang orange,oag,orange,orange airport,yorg,aeroport d''orange,aeroporto di orange,aéroport d''orange,frwdgah awrnj,orenji kong gang,фурудгоҳи оврнҷ,فرودگاه اورنج,オレンジ空港',
    NOW(), NOW()), ('7668755', NULL, 'Palm Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.7553, 146.58099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palm island airport palm island airport australia au aeroport de palm island,aeropuerto de palm island,aéroport de palm island,flughhafen palm island,lapangan terbang palm island,pmk,palm island airport,ypam,frwdgah palm aylnd,фурудгоҳи полм оилнд,فرودگاه پالم آیلند',
    NOW(), NOW()), ('7668756', NULL, 'Paraburdoo Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.17228, 117.747, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paraburdoo airport paraburdoo airport australia au aeroport de paraburdoo,aeroportul paraburdoo,aeropuerto de paraburdoo,aéroport de paraburdoo,flughafen paraburdoo,lapangan terbang paraburdoo,pbo,paraburdoo airport,port lotniczy paraburdoo,ypbo,frwdgah parabwrdw,parabadou kong gang,фурудгоҳи поробурду,فرودگاه پارابوردو,パラバドゥー 空港',
    NOW(), NOW()), ('7668757', NULL, 'Aeropelican Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.0667, 151.64799, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeropelican airport aeropelican airport australia au aeropelican airport,beo,ylmq',
    NOW(), NOW()), ('7668758', NULL, 'Karratha Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.7122, 116.773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karratha airport karratha airport australia au aeroportul karratha,kta,karrata,karratha airport,lapangan terbang karratha,maes awyr karratha,port lotniczy karratha,ypka,aeroport de karratha,aéroport de karratha,frwdgah karata,ka la sa ji chang,karassa kong gang,каррата,фурудгоҳи корото,فرودگاه کاراتا,カラーッサ空港,卡拉萨机场,卡拉薩機場',
    NOW(), NOW()), ('7668759', NULL, 'Parkes Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1314, 148.239, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parkes airport parkes airport australia au lapangan terbang parkes,pke,ypks',
    NOW(), NOW()), ('7668760', NULL, 'Port Keats Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.25, 129.52901, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port keats airport port keats airport australia au pkt,port keats airport,ypkt',
    NOW(), NOW()), ('7668761', NULL, 'Port Lincoln Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.6053, 135.88, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln airport port lincoln airport australia au aeroportul port lincoln,aeropuerto de port lincoln,aeropuertu de port lincoln,lapangan terbang port lincoln,plo,port lincoln airport,san bay port lincoln,sân bay port lincoln,yplc,aeroport de port lincoln,aeroporto di port lincoln,aéroport de port lincoln,frwdgah pwrt lynkwln,lin ken gang fei ji chang,potorinkan kong gang,фурудгоҳи пӯр линкулн,فرودگاه پورت لینکولن,ポートリンカーン空港,林肯港飛機場',
    NOW(), NOW()), ('7668762', NULL, 'Port Macquarie Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4358, 152.86301, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port macquarie airport port macquarie airport australia au lapangan terbang port macquarie,pqq,ypmq',
    NOW(), NOW()), ('7668763', NULL, 'Renmark Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.1964, 140.674, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'renmark airport renmark airport australia au aeroportul renmark,aeropuerto de renmark,lapangan terbang renmark,rmk,renmark,renmark airport,yren,aeroport de renmark,aeroporto di renmark,aéroport de renmark,frwdgah rnmark,renmaku kong gang,ренмарк,фурудгоҳи рнморк,فرودگاه رنمارک,レンマーク空港',
    NOW(), NOW());