INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12482304', NULL, 'Puerto Sucre', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.45193, -66.09312, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto sucre puerto sucre bolivia bo puerto sucre',
    NOW(), NOW()), ('12482340', NULL, 'Puerto Consuelo II', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.5325, -65.59779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto consuelo ii puerto consuelo ii bolivia bo puerto consuelo ii',
    NOW(), NOW()), ('12482343', NULL, 'Puerto Consuelo I', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.49668, -65.53075, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto consuelo i puerto consuelo i bolivia bo puerto consuelo i',
    NOW(), NOW()), ('12482368', NULL, 'Puerto Román', 'Puerto Roman',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.78314, -65.84783, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto román puerto roman bolivia bo puerto roman,puerto román',
    NOW(), NOW()), ('12482393', NULL, 'Puerto Carrero', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.97943, -65.56071, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto carrero puerto carrero bolivia bo puerto carrero',
    NOW(), NOW()), ('12482405', NULL, 'Puerto Carrero', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.10602, -65.33947, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto carrero puerto carrero bolivia bo puerto carrero',
    NOW(), NOW()), ('12482496', NULL, 'Puerto Morales Ayma', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.99006, -67.41884, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto morales ayma puerto morales ayma bolivia bo puerto morales ayma',
    NOW(), NOW()), ('12482641', NULL, 'Puerto Bolívar', 'Puerto Bolivar',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -9.96028, -66.46983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto bolívar puerto bolivar bolivia bo puerto bolivar,puerto bolívar',
    NOW(), NOW()), ('12482663', NULL, 'Puerto Sucre', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -10.71915, -66.65094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto sucre puerto sucre bolivia bo puerto sucre',
    NOW(), NOW()), ('12494322', NULL, 'Puerto Junín', 'Puerto Junin',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.71861, -65.39756, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto junín puerto junin bolivia bo puerto junin,puerto junín',
    NOW(), NOW()), ('12494326', NULL, 'Puerto San Mateo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.69485, -65.24151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san mateo puerto san mateo bolivia bo puerto san mateo',
    NOW(), NOW()), ('12496521', NULL, 'Estancia Kalapierna', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.40779, -63.13244, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia kalapierna estancia kalapierna bolivia bo estancia kalapierna',
    NOW(), NOW()), ('12498255', NULL, 'Chilimani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.74267, -69.12681, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chilimani chilimani bolivia bo chilimani',
    NOW(), NOW()), ('12498320', NULL, 'Santa Rosa de Limani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.65714, -68.24827, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa rosa de limani santa rosa de limani bolivia bo santa rosa de limani',
    NOW(), NOW()), ('12498607', NULL, 'Puerto la Cruz', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.16272, -63.07453, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto la cruz puerto la cruz bolivia bo puerto la cruz',
    NOW(), NOW()), ('12498678', NULL, 'Puerto San Pedro', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.4594, -62.30216, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san pedro puerto san pedro bolivia bo puerto san pedro',
    NOW(), NOW()), ('12498944', NULL, 'Puerto Pando', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.14892, -67.68401, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto pando puerto pando bolivia bo puerto pando',
    NOW(), NOW()), ('12498971', NULL, 'Puerto el Carmen', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.13976, -67.67178, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto el carmen puerto el carmen bolivia bo puerto el carmen',
    NOW(), NOW()), ('12498991', NULL, 'Plan Aeropuerto', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.04363, -69.25453, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'plan aeropuerto plan aeropuerto bolivia bo plan aeropuerto',
    NOW(), NOW()), ('12499442', NULL, 'Alto Puerto León', 'Alto Puerto Leon',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.02647, -67.57313, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alto puerto león alto puerto leon bolivia bo alto puerto leon,alto puerto león',
    NOW(), NOW()), ('12504319', NULL, 'Puerto Flores', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.04645, -64.60733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto flores puerto flores bolivia bo puerto flores',
    NOW(), NOW()), ('12504423', NULL, 'Illimani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.11574, -64.63204, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'illimani illimani bolivia bo illimani',
    NOW(), NOW()), ('12504454', NULL, 'Puerto Pallar', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.76345, -64.81532, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto pallar puerto pallar bolivia bo puerto pallar',
    NOW(), NOW()), ('12504486', NULL, 'Illimani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.28423, -64.65077, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'illimani illimani bolivia bo illimani',
    NOW(), NOW()), ('12504503', NULL, 'Puerto Rico', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.24128, -64.93264, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto rico puerto rico bolivia bo puerto rico',
    NOW(), NOW()), ('12504548', NULL, 'Puerto Chimoré', 'Puerto Chimore',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.83, -64.97562, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto chimoré puerto chimore bolivia bo puerto chimore,puerto chimoré',
    NOW(), NOW()), ('12504646', NULL, 'Puerto Andino', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.09556, -64.56017, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto andino puerto andino bolivia bo puerto andino',
    NOW(), NOW()), ('12504662', NULL, 'Puerto Rico', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.70503, -64.06962, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto rico puerto rico bolivia bo puerto rico',
    NOW(), NOW()), ('12504713', NULL, 'Puerto Ichilo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.05022, -64.64084, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto ichilo puerto ichilo bolivia bo puerto ichilo',
    NOW(), NOW()), ('12504727', NULL, 'Puerto Avaroa', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.28304, -64.19228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto avaroa puerto avaroa bolivia bo puerto avaroa',
    NOW(), NOW()), ('12504767', NULL, 'Sindicato Agrario Illimani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.24388, -64.27017, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sindicato agrario illimani sindicato agrario illimani bolivia bo sindicato agrario illimani',
    NOW(), NOW()), ('12504871', NULL, 'Puerto Cotaigaita', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.17314, -64.4629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto cotaigaita puerto cotaigaita bolivia bo puerto cotaigaita',
    NOW(), NOW()), ('12504887', NULL, 'Puerto Chore', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.10184, -64.26424, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto chore puerto chore bolivia bo puerto chore',
    NOW(), NOW()), ('12505037', NULL, 'Puerto Bolívar', 'Puerto Bolivar',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.06948, -64.80846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto bolívar puerto bolivar bolivia bo puerto bolivar,puerto bolívar',
    NOW(), NOW()), ('12506209', NULL, 'Puerto Limón', 'Puerto Limon',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.24959, -63.95348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto limón puerto limon bolivia bo puerto limon,puerto limón',
    NOW(), NOW()), ('12511731', NULL, 'Puerto Yumani', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.35421, -67.49142, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto yumani puerto yumani bolivia bo puerto yumani',
    NOW(), NOW()), ('12511735', NULL, 'Solimán', 'Soliman',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.44592, -67.41736, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'solimán soliman bolivia bo soliman,solimán',
    NOW(), NOW()), ('12511788', NULL, 'El Porteño', 'El Porteno',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.82876, -67.16958, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el porteño el porteno bolivia bo el porteno,el porteño',
    NOW(), NOW()), ('12511810', NULL, 'Puerto San Borja', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.98308, -65.79929, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san borja puerto san borja bolivia bo puerto san borja',
    NOW(), NOW()), ('12511825', NULL, 'Puerto Codo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.87626, -66.73078, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto codo puerto codo bolivia bo puerto codo',
    NOW(), NOW()), ('12511827', NULL, 'Puerto Gregorio', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.92177, -66.74632, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto gregorio puerto gregorio bolivia bo puerto gregorio',
    NOW(), NOW()), ('12511899', NULL, 'Puerto Yucumo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.266, -66.75698, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto yucumo puerto yucumo bolivia bo puerto yucumo',
    NOW(), NOW()), ('12511940', NULL, 'Puerto Motor', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.41676, -67.49759, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto motor puerto motor bolivia bo puerto motor',
    NOW(), NOW()), ('12512020', NULL, 'Puerto Triunfo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.73851, -66.5995, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto triunfo puerto triunfo bolivia bo puerto triunfo',
    NOW(), NOW()), ('12512055', NULL, 'Puerto Méndez', 'Puerto Mendez',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.85814, -66.69366, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto méndez puerto mendez bolivia bo puerto mendez,puerto méndez',
    NOW(), NOW()), ('12512057', NULL, 'Puerto Lata', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.9109, -66.73481, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto lata puerto lata bolivia bo puerto lata',
    NOW(), NOW()), ('12512058', NULL, 'Puerto Salas', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.92081, -66.74201, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto salas puerto salas bolivia bo puerto salas',
    NOW(), NOW()), ('12512102', NULL, 'Puerto Yucumo', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.14052, -66.89868, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto yucumo puerto yucumo bolivia bo puerto yucumo',
    NOW(), NOW()), ('12515448', NULL, 'Puerto Troncas', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.08985, -57.60258, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto troncas puerto troncas bolivia bo puerto troncas',
    NOW(), NOW()), ('12515501', NULL, 'Puerto Mandiore', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.24001, -57.55809, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto mandiore puerto mandiore bolivia bo puerto mandiore',
    NOW(), NOW());