INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('6300609', NULL, 'Cachimbo Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.33394, -54.96542, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cachimbo airport cachimbo airport brazil br aeroporto do cachimbo,aeroportul cachimbo,cachimbo airport,campo de provas brigadeiro velloso test ve egitim kompleksi,campo de provas brigadeiro velloso test ve eğitim kompleksi,lapangan terbang cachimbo,sbcc,frwdgah kchymbw,ka xin bo ji chang,kachinbo kong jun ji de,фурудгоҳи кчимбу,فرودگاه کچیمبو,カチンボ空軍基地,卡辛波机场,卡辛波機場',
    NOW(), NOW()), ('6300610', NULL, 'Campo Grande International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.46867, -54.6725, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'campo grande international airport campo grande international airport brazil br aeroport internacional de campo grande,aeroport international de campo grande,aeroporto internacional de campo grande,aeroporto internazionale di campo grande,aeropuerto internacional de campo grande,aéroport international de campo grande,bandar udara internasional campo grande,cgr,campo grande international airport,campo grande internationella flygplats,campo grande kansainvaelinen lentoasema,campo grande kansainvälinen lentoasema,internationale luchthaven campo grande,lapangan terbang antarabangsa campo grande,medzinarodne letisko campo grande,medzinárodné letisko campo grande,mezhdunarodnyj aehroport kampu-grandi,port lotniczy campo grande,sbcg,san bay quoc te campo grande,sân bay quốc tế campo grande,международный аэропорт кампу-гранди',
    NOW(), NOW()), ('6300611', NULL, 'Maranhão / Carolina Airport', 'Maranhao / Carolina Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.32044, -47.45867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maranhão / carolina airport maranhao / carolina airport brazil br aeroport de maranhao / carolina,aéroport de maranhão / carolina,cln,maranhao / carolina airport,maranhão / carolina airport,sbci',
    NOW(), NOW()), ('6300612', NULL, 'Parauapebas Carajás Airport', 'Parauapebas Carajas Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.11781, -50.00347, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parauapebas carajás airport parauapebas carajas airport brazil br aeroport de parauapebas carajas,aeroporto de parauapebas carajas,aeroporto de parauapebas carajás,aéroport de parauapebas carajás,cks,parauapebas carajas airport,parauapebas carajás airport,sbcj',
    NOW(), NOW()), ('6300613', NULL, 'Campo Nossa Senhora de Fatima', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.94594, -51.14437, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campo nossa senhora de fatima campo nossa senhora de fatima brazil br canoas,porto alegre canoas ab aeropuerto,qns,sbco',
    NOW(), NOW()), ('6300614', NULL, 'Campos–Bartolomeu Lysandro Airport', 'Campos-Bartolomeu Lysandro Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.69833, -41.30167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campos–bartolomeu lysandro airport campos-bartolomeu lysandro airport brazil br aeroporto de campos-bartolomeu lysandro,aeroporto de campos–bartolomeu lysandro,caw,campos-bartolomeu lysandro airport,campos–bartolomeu lysandro airport,sbcp',
    NOW(), NOW()), ('6300615', NULL, 'Corumbá International Airport', 'Corumba International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.01193, -57.67305, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'corumbá international airport corumba international airport brazil br aeroporto internacional de corumba,aeroporto internacional de corumbá,cmg,corumba international airport,corumbá international airport,sbcr',
    NOW(), NOW()), ('6300616', NULL, 'Caravelas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.65228, -39.25307, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caravelas airport caravelas airport brazil br aeropuerto de caravelas,crq,caravelas airport,sbcv',
    NOW(), NOW()), ('6300617', NULL, 'Marechal Rondon International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.65293, -56.11672, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'marechal rondon international airport marechal rondon international airport brazil br aeroport international de cuiaba,aeroporto internacional marechal rondon,aeroporto di cuiaba-maresciallo rondon,aeroporto di cuiabá-maresciallo rondon,aeropuerto internacional marechal rondon,aéroport international de cuiabá,cgb,cuiaba international airport,cuiabá international airport,lapangan terbang antarabangsa marechal rondon,marechal rondon international airport,marshal rondon,mezhdunarodnyj aehroport marshal rondon,sbcy,san bay quoc te marechal rondon,sân bay quốc tế marechal rondon,маршал рондон,международный аэропорт маршал рондон,فرودگاه بین‌المللی مارشال روندو',
    NOW(), NOW()), ('6300618', NULL, 'Cruzeiro do Sul International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.59991, -72.76949, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'cruzeiro do sul international airport cruzeiro do sul international airport brazil br aeroporto internacional de cruzeiro do sul,aeroporto de cruzeiro do sul,aeroportul international cruzeiro do sul,aeroportul internațional cruzeiro do sul,aeropuerto internacional de cruzeiro do sul,aeropuertu internacional de cruzeiro do sul,czs,cruzeiro do sul international airport,flughafen cruzeiro do sul,lapangan terbang antarabangsa cruzeiro do sul,maes awyr rhyngwladol cruzeiro do sul,mezhdunarodnyj aehroport kruzejru-du-sul,sbcz,san bay quoc te cruzeiro do sul,sân bay quốc tế cruzeiro do sul,aeroport international de cruzeiro do sul,aéroport international de cruzeiro do sul,nan ke lu sai luo guo ji ji chang,международный аэропорт крузейру-ду-сул,фурудгоҳи бин‌алмилалӣ крузиру ду сул,فرودگاه بین‌المللی کروزیرو دو سول,クルゼイロ・ド・スル国際空港,南克魯賽羅國際機場',
    NOW(), NOW()), ('6300619', NULL, 'Presidente Prudente Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.17506, -51.42464, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'presidente prudente airport presidente prudente airport brazil br aeroporto de presidente prudente,lapangan terbang presidente prudente,ppb,presidente prudente,presidente prudente airport,sbdn',
    NOW(), NOW()), ('6300620', NULL, 'Eduardo Gomes International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.03861, -60.04972, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'eduardo gomes international airport eduardo gomes international airport brazil br eduardo gomes international,eduardo gomes international airport,mao,sbeg',
    NOW(), NOW()), ('6300623', NULL, 'Foz do Iguaçu / Cataratas International Airport', 'Foz do Iguacu / Cataratas International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.59615, -54.48721, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'foz do iguaçu / cataratas international airport foz do iguacu / cataratas international airport brazil br aeroporto internacional de foz do iguacu / cataratas,aeroporto internacional de foz do iguaçu / cataratas,aeropuerto internacional de foz do iguacu,aeropuerto internacional de foz do iguaçu,foz do iguacu / cataratas international airport,foz do iguaçu / cataratas international airport,igu,mezhdunarodnyj aehroport fos-du-iguasu,sbfi,fosu・do・iguasu guo ji kong gang,frwdgah byn‌almlly fwz dw aygwasw,международный аэропорт фос-ду-игуасу,فرودگاه بین‌المللی فوز دو ایگواسو,フォス・ド・イグアス国際空港',
    NOW(), NOW()), ('6300624', NULL, 'Florianópolis-Hercílio Luz International Airport', 'Florianopolis-Hercilio Luz International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.66665, -48.55047, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'florianópolis-hercílio luz international airport florianopolis-hercilio luz international airport brazil br aeroport international florianopolis-hercilio luz,aeroporto hercilio luz,aeroporto hercílio luz,aeroporto internacional hercilio luz,aeroporto internacional hercílio luz,aéroport international florianópolis-hercílio luz,fln,florianopolis-hercilio luz international airport,florianópolis-hercílio luz international airport,sbfl',
    NOW(), NOW()), ('6300625', NULL, 'Fernando de Noronha Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.85493, -32.42334, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fernando de noronha airport fernando de noronha airport brazil br aeroporto de fernando de noronha,aeropuerto de fernando de noronha,fen,fernando de noronha,fernando de noronha airport,sbfn',
    NOW(), NOW()), ('6300628', NULL, 'Santa Genoveva / Goiânia Airport', 'Santa Genoveva / Goiania Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.63203, -49.22069, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa genoveva / goiânia airport santa genoveva / goiania airport brazil br aeroport de santa genoveva / goiania,aeroporto santa genoveva / goiania,aeroporto santa genoveva / goiânia,aéroport de santa genoveva / goiânia,gyn,sbgo,santa genoveva / goiania airport,santa genoveva / goiânia airport',
    NOW(), NOW()), ('6300629', NULL, 'São Paulo–Guarulhos International Airport', 'Sao Paulo-Guarulhos International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.43057, -46.48101, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'são paulo–guarulhos international airport sao paulo-guarulhos international airport brazil br aeroporto internacional de guarulhos,gru,sbgr,sao paulo/guarulhos–governador andre franco montoro international airport,sao paulo–guarulhos international airport,são paulo/guarulhos–governador andré franco montoro international airport,são paulo–guarulhos international airport',
    NOW(), NOW()), ('6300633', NULL, 'Ilhéus Jorge Amado Airport', 'Ilheus Jorge Amado Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.81604, -39.03155, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilhéus jorge amado airport ilheus jorge amado airport brazil br aeroporto de ilheus/bahia-jorge amado,aeroporto de ilhéus/bahia-jorge amado,ios,ilheus/bahia-jorge amado airport,ilhéus/bahia-jorge amado airport,sbil',
    NOW(), NOW()), ('6300635', NULL, 'Presidente Castro Pinto International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.14838, -34.95068, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'presidente castro pinto international airport presidente castro pinto international airport brazil br aeroport international presidente castro pinto,aeroporto internacional presidente castro pinto,aéroport international presidente castro pinto,jpa,presidente castro pinto international airport,sbjp,frwdgah byn‌almlly przydant kastrw pyntw,فرودگاه بین‌المللی پرزیدانت کاسترو پینتو',
    NOW(), NOW()), ('6300637', NULL, 'Viracopos International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.00738, -47.13452, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'viracopos international airport viracopos international airport brazil br aeroport international de viracopos–campinas,aeroporto internacional de campinas,aeroporto internacional de viracopos,aeroporto internacional de viracopos/campinas,aeroporto internacional de viracopos–campinas,aeroporto internazionale viracopos-campinas,aeroporto de viracopos,aeroportul international viracopos,aeroportul internațional viracopos,aeropuerto internacional de campinas,aeropuertu internacional de campinas,aéroport international de viracopos–campinas,bandar udara internasional viracopos-campinas,campinas-viracopos internationella flygplats,flughafen viracopos,lapangan terbang antarabangsa viracopos,luchthaven viracopos,maes awyr rhyngwladol viracopos,mezhdunarodnyj aehroport virakopus/kampinas,port lotniczy campinas-viracopos,sbkp,san bay quoc te viracopos-campinas,sao paulo viracopos,sân bay quốc tế viracopos-campinas,vcp,viracopos international airport,viracopos-campinas nemzetkoezi repueloter,viracopos-campinas nemzetközi repülőtér,viracopos/campinas international airport,virakopus,aeroport international de viracopos/campinas,aéroport international de viracopos/campinas,bilakopuseu kampinaseu gugjegonghang,kan pi na si,kan pi na si-wei la ke bo si,mtar fyrakwbws aldwly,vuirakopposu guo ji kong gang,виракопус,международный аэропорт виракопус/кампинас,фурудгоҳи бин‌алмилалӣ вирокупус-компинос,فرودگاه بین‌المللی ویراکوپوس-کامپیناس,مطار فيراكوبوس الدولى,ヴィラコッポス国際空港,坎皮納斯,坎皮納斯-維拉科伯斯,坎皮纳斯,비라코푸스 캄피나스 국제공항',
    NOW(), NOW()), ('6300638', NULL, 'Londrina Aeroporto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.33363, -51.13007, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'londrina aeroporto londrina aeroporto brazil br ldb,sblo',
    NOW(), NOW()), ('6300640', NULL, 'Marabá Airport', 'Maraba Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.36859, -49.13802, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marabá airport maraba airport brazil br aeroporto de maraba/joao correa da rocha,aeroporto de marabá/joão correa da rocha,aeroportul maraba,aeroportul marabá,aeropuerto de maraba,aeropuerto de marabá,flughafen joao correa da rocha,flughafen joão correa da rocha,lapangan terbang maraba,mab,maraba,maraba airport,marabá airport,sbma,aeroport de maraba,aeroporto di maraba,aeroporto di marabá,aéroport de marabá,frwdgah maraba,ma la ba ji chang,maraba kong gang,فرودگاه مارابا,マラバ空港,馬拉巴机场,馬拉巴機場',
    NOW(), NOW()), ('6300641', NULL, 'Benedito Lacerda Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.34303, -41.76603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'benedito lacerda airport benedito lacerda airport brazil br aeroporto benedito lacerda,benedito lacerda airport,mea,macae airport,macaé airport,sbme',
    NOW(), NOW()), ('6300642', NULL, 'Maringá Regional Airport', 'Maringa Regional Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.47639, -52.01641, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maringá regional airport maringa regional airport brazil br aeroport regional de maringa,aeroporto regional de maringa - silvio name junior,aeroporto regional de maringá - sílvio name júnior,aéroport régional de maringa,mgf,maringa regional airport,maringá regional airport,sbmg,silvio name junior regional airport,sílvio name júnior regional airport',
    NOW(), NOW()), ('6300644', NULL, 'Maceió/Zumbi dos Palmares International Airport', 'Maceio/Zumbi dos Palmares International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.51081, -35.79168, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'maceió/zumbi dos palmares international airport maceio/zumbi dos palmares international airport brazil br aeroporto internacional maceio/zumbi dos palmares,aeroporto internacional maceió/zumbi dos palmares,campo dos palmares airport,mcz,maceio/zumbi dos palmares international airport,maceió/zumbi dos palmares international airport,sbmo',
    NOW(), NOW()), ('6300645', NULL, 'Macapá-Alberto Alcolumbre International Airport', 'Macapa-Alberto Alcolumbre International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    0.05066, -51.07218, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'macapá-alberto alcolumbre international airport macapa-alberto alcolumbre international airport brazil br aeroport international de macapa,aeroporto internacional de macapa-alberto alcolumbre,aeroporto internacional de macapá-alberto alcolumbre,aeropuerto de macapa,aeropuerto de macapá,aéroport international de macapá,mcp,macapa-alberto alcolumbre international airport,macapá-alberto alcolumbre international airport,mezhdunarodnyj aehroport makapa,sbmq,frwdgah byn‌almlly mkapa,международный аэропорт макапа,فرودگاه بین‌المللی مکاپا',
    NOW(), NOW()), ('6300647', NULL, 'Campo de Marte Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.50912, -46.63775, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campo de marte airport campo de marte airport brazil br aehroport kampu-di-marti,aeroporto campo de marte,aeropuerto campo de marte,campo de marte airport,rte,sbmt,kan pu-de ma er te ji chang,аэропорт кампу-ди-марти,坎普-德马尔特机场',
    NOW(), NOW()), ('6300651', NULL, 'Parnaiba Aeroporto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.89375, -41.73196, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parnaiba aeroporto parnaiba aeroporto brazil br phb,sbpb',
    NOW(), NOW()), ('6300654', NULL, 'Paranaguá Airport', 'Paranagua Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.5402, -48.53116, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paranaguá airport paranagua airport brazil br aeroporto santos dumont,png,paranagua airport,paranaguá airport,sspg,santos dumont airport',
    NOW(), NOW()), ('6300657', NULL, 'Porto Nacional Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.71942, -48.39974, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto nacional airport porto nacional airport brazil br pnb,porto nacional aeroporto,porto nacional airport,sbpn',
    NOW(), NOW()), ('6300658', NULL, 'Ponta Porã International Airport', 'Ponta Pora International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.54964, -55.70261, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'ponta porã international airport ponta pora international airport brazil br aeroporto internacional de ponta pora,aeroporto internacional de ponta porã,aeropuerto internacional de ponta pora,aeropuerto internacional de ponta porã,flughafen ponta pora,flughafen ponta porã,lapangan terbang antarabangsa ponta pora,pmg,ponta pora international airport,ponta pora intl,ponta porã international airport,ponta-poran,sbpp,aerodrome de ponta pora,aérodrome de ponta porã,mtar bwnta bwra aldwly,понта-поран,фурудгоҳи бин‌алмилалӣ пунто пуреҳо,فرودگاه بین‌المللی پونتا پورئا,مطار بونتا بورا الدولى,ポンタ・ポラン空港',
    NOW(), NOW()), ('6300659', NULL, 'Porto Seguro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.43864, -39.08092, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto seguro porto seguro brazil br bps,sbps',
    NOW(), NOW()), ('6300660', NULL, 'Governador Jorge Teixeira de Oliveira International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.70929, -63.90228, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'governador jorge teixeira de oliveira international airport governador jorge teixeira de oliveira international airport brazil br aeroporto internacional de porto velho - belmonte,aeroporto internacional de porto velho - governador jorge teixeira de oliveira,aeroporto de belmonte,belmonte airport,governador jorge teixeira de oliveira international airport,pvh,porto velho - governador jorge teixeira de oliveira international airport,sbpv',
    NOW(), NOW()), ('6300661', NULL, 'Pedro Otacílio Figueiredo Airport', 'Pedro Otacilio Figueiredo Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.86276, -40.86311, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pedro otacílio figueiredo airport pedro otacilio figueiredo airport brazil br aeroport pedro otacilio figueiredo,aeroporto pedro otacilio figueiredo,aeroporto pedro otacílio figueiredo,aeroportul vitoria da conquista,aeroportul vitória da conquista,aéroport pedro otacílio figueiredo,flughafen pedro otacilio figueiredo,flughafen pedro otacílio figueiredo,lapangan terbang vitoria da conquista,pedro otacilio figueiredo airport,pedro otacílio figueiredo airport,sbvc,vdc,vitoria da conquista,vitoria da conquista airport,vitória da conquista airport,frwdgah wytwrya da kwnkysta,фурудгоҳи витурио до кункисто,فرودگاه ویتوریا دا کونکیستا,ビトリア・ダ・コンキスタ',
    NOW(), NOW()), ('6300663', NULL, 'Recife/Guararapes–Gilberto Freyre International Airport', 'Recife/Guararapes-Gilberto Freyre International Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.12679, -34.92304, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'recife/guararapes–gilberto freyre international airport recife/guararapes-gilberto freyre international airport brazil br aeroport internacional de recife,aeroporto internacional do recife/guararapes-gilberto freyre,aeroporto internazionale guararapes-gilberto freyre di recife,aeroportul international recife/guararapes-gilberto freyre,aeroportul internațional recife/guararapes–gilberto freyre,aeropuerto internacional de recife,aeropuertu internacional de recife,bandar udara internasional recife,flughafen guararapes - gilberto freyre,guararapes internasjonale lufthavn,internationale luchthaven guararapes,lapangan terbang guararapes - gilberto freyre,maes awyr rhyngwladol recife/guararapes-gilberto freyre,maes awyr rhyngwladol recife/guararapes–gilberto freyre,mizhnarodnij aeroport guararapis,port lotniczy recife,rec,recife aeroporto,recife international airport,recife/guararapes–gilberto freyre international airport,resifi,sbrf,san bay quoc te recife/guararapes-gilberto freyre,sân bay quốc tế recife/guararapes-gilberto freyre,aeroport international de recife,aéroport international de recife,frwdgah rykayf,mtar rysyfy jwararabys jylbrtw frayr aldwly,міжнародний аеропорт гуарарапіс,ресифи,фурудгоҳи рикоиф,فرودگاه ریکایف,مطار ريسيفى جوارارابيس جيلبرتو فراير الدولى,レシフェ/グアララペス・ジルベルト・フレイレ国際空港,累西腓/瓜拉拉皮斯－吉尔贝托·弗雷雷国际机场',
    NOW(), NOW()), ('6300664', NULL, 'Santos Dumont Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91046, -43.16313, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santos dumont airport santos dumont airport brazil br aeroport santos dumont,aeroporto santos dumont,aeroportul santos dumont,aeropuerto santos dumont,aeropuertu santos dumont,bandar udara santos dumont,flughafen rio de janeiro-santos dumont,flughafen rio de janeiro–santos dumont,lapangan terbang santos dumont,luchthaven santos-dumont,port lotniczy rio de janeiro-santos dumont,rio de janeiro aeroporto,sbrj,sdu,san bay santos dumont,santos dumont airport,santos dumont flyplass,santos dumont oro uostas,santos dumontflygplatsen,santos dumontin lentoasema,santos-djumon,sân bay santos dumont,aeroport santos dumont de rio de janeiro,aéroport santos dumont de rio de janeiro,frwdgah santws dwmnt,liudejaneilu santuseu dumonteu gonghang,sheng du meng te ji chang,сантос-дюмон,фурудгоҳи сонтус думнт,فرودگاه سانتوس دومنت,サントス・ドゥモン空港,圣杜蒙特机场,聖杜蒙特機場,리우데자네이루 산투스 두몬트 공항',
    NOW(), NOW()), ('6300665', NULL, 'Leite Lopes Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.13417, -47.77419, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leite lopes airport leite lopes airport brazil br aeroporto estadual dr. leite lopes,dr. leite lopes state airport,leite lopes airport,rao,sbrp',
    NOW(), NOW()), ('6300666', NULL, 'Resende Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.47826, -44.47909, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'resende airport resende airport brazil br aeroport de resende,aeroporto de resende,aeropuerto de resende,aéroport de resende,flughafen resende,rez,resende airport,sdrs',
    NOW(), NOW()), ('6300668', NULL, 'Bartolomeu de Gusmão Airport (historical)', 'Bartolomeu de Gusmao Airport (historical)',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.93176, -43.71533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bartolomeu de gusmão airport (historical) bartolomeu de gusmao airport (historical) brazil br aeroporto bartolomeu de gusmao,aeroporto bartolomeu de gusmão,bartolomeu de gusmao airport,bartolomeu de gusmão airport,sbsc,snz',
    NOW(), NOW()), ('6300670', NULL, 'Marechal Cunha Machado International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.58536, -44.23414, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'marechal cunha machado international airport marechal cunha machado international airport brazil br aeroport international marechal cunha machado,aeroporto internacional marechal cunha machado,aeroporto internacional de sao luis,aeroporto internacional de são luís,aeroporto sao luis,aeroporto são luís,aeroporto tirirical,aéroport international marechal cunha machado,flughafen sao luis,flughafen são luís,lapangan terbang antarabangsa marechal cunha machado,marechal cunha machado international airport,marshal kun''ja machadu,sbsl,slz,san bay quoc te marechal cunha machado,sao luis airport,sân bay quốc tế marechal cunha machado,são luís airport,tirirical airport,маршал кунья мачаду,فرودگاه بین‌المللی مارشال کونیا ماچادو',
    NOW(), NOW()), ('6300671', NULL, 'Aeroporto de Santa Maria', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.71136, -53.68815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto de santa maria aeroporto de santa maria brazil br ria,sbsm',
    NOW(), NOW()), ('6300672', NULL, 'Santarém-Maestro Wilson Fonseca Airport', 'Santarem-Maestro Wilson Fonseca Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.42243, -54.79279, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santarém-maestro wilson fonseca airport santarem-maestro wilson fonseca airport brazil br aehroport maehstro vilson fonseka,aeroport santarem–maestro wilson fonseca,aeroporto de santarem–maestro wilson fonseca,aeroporto de santarém–maestro wilson fonseca,aéroport santarém–maestro wilson fonseca,sbsn,stm,santarem–maestro wilson fonseca airport,santarém–maestro wilson fonseca airport,аэропорт маэстро вилсон фонсека',
    NOW(), NOW()), ('6300673', NULL, 'Santos Aeroporto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.92521, -46.2875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santos aeroporto santos aeroporto brazil br sbst,ssz',
    NOW(), NOW()), ('6300674', NULL, 'Salvador International Airport, Deputado Luís Eduardo Magalhães', 'Salvador International Airport, Deputado Luis Eduardo Magalhaes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.91099, -38.33104, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'salvador international airport, deputado luís eduardo magalhães salvador international airport, deputado luis eduardo magalhaes brazil br aeroporto dois de julho,aeroporto internacional de salvador,aeroporto internacional de salvador deputado luis eduardo magalhaes,aeroporto internacional de salvador deputado luís eduardo magalhães,deputado luis eduardo magalhaes international airport,deputado luís eduardo magalhães international airport,dois de julho international airport,sbsv,ssa,salvador international airport',
    NOW(), NOW()), ('6300676', NULL, 'Tefé Airport', 'Tefe Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.38294, -64.72406, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tefé airport tefe airport brazil br aehroport tefe,aeroport de tefe,aeroporto regional de tefe,aeroporto regional de tefé,aéroport de tefé,sbtf,tff,tefe airport,tefé airport,аэропорт тефе',
    NOW(), NOW()), ('6300677', NULL, 'Tarauacá Airport', 'Tarauaca Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.15526, -70.78327, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tarauacá airport tarauaca airport brazil br aeroport jose galera dos santos,aeroporto jose galera dos santos,aeroporto josé galera dos santos,aeroportul tarauaca,aeroportul tarauacá,aeropuerto jose galera dos santos,aeropuerto josé galera dos santos,aéroport josé galera dos santos,flughafen tarauaca,flughafen tarauacá,jose galera dos santos airport,josé galera dos santos airport,lapangan terbang tarauaca,sbtk,trq,tarauaca airport,tarauacá airport,tarauaka,tarauaka kong gang,тарауака,タラウアカ空港',
    NOW(), NOW()), ('6300678', NULL, 'Tabatinga International Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.25567, -69.93583, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'tabatinga international airport tabatinga international airport brazil br aeroport international de tabatinga,aéroport international de tabatinga,mezhdunarodnyj aehroport tabatinga,sbtt,tbt,tabatinga international airport,frwdgah byn‌almlly tabatynga,международный аэропорт табатинга,فرودگاه بین‌المللی تاباتینگا',
    NOW(), NOW()), ('6300679', NULL, 'Tucuruí Airport', 'Tucurui Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.78601, -49.72027, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tucuruí airport tucurui airport brazil br aeroport de tucurui,aeroporto de tucurui,aeroporto de tucuruí,aeropuerto de tucurui,aeropuerto de tucuruí,aéroport de tucuruí,sbtu,tur,tucurui airport,tucuruí airport',
    NOW(), NOW()), ('6300680', NULL, 'Sao Gabriel Da Cachoeira Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -0.14842, -66.98559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sao gabriel da cachoeira airport sao gabriel da cachoeira airport brazil br sbua,sjl',
    NOW(), NOW()), ('6300682', NULL, 'Uberlândia–Ten. Cel. Av. César Bombonato Airport', 'Uberlandia-Ten. Cel. Av. Cesar Bombonato Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.88284, -48.22559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uberlândia–ten. cel. av. césar bombonato airport uberlandia-ten. cel. av. cesar bombonato airport brazil br aeroporto de uberlandia-ten. cel. av. cesar bombonato,aeroporto de uberlândia–ten. cel. av. césar bombonato,aeroporto di uberlandia,aeroporto di uberlândia,aeroportul uberlandia,aeroportul uberlândia,aeropuerto de uberlandia,aeropuerto de uberlândia,flughafen ten cel aviador cesar bombonato,flughafen ten cel aviador césar bombonato,lapangan terbang ten cel av cesar bombonato,luchthaven uberlandia,luchthaven uberlândia,sbul,udi,uberlandia,uberlandia airport,uberlandia-ten. cel. av. cesar bombonato airport,uberlândia airport,uberlândia–ten. cel. av. césar bombonato airport,aeroport d''uberlandia,aéroport d''uberlândia,frwdgah awbrlanjh,uberuranjia,wu bei lan di ya,фурудгоҳи овбрлонҷҳ,فرودگاه اوبرلانجه,ウベルランジア,乌贝兰迪亚,烏貝蘭迪亞',
    NOW(), NOW());