INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('12280456', NULL, 'Fazenda Portela', 'FazendaPortela',
    NULL, 'AO', 'Angola', NULL, NULL,
    -13.01577, 14.04417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda portela fazendaportela angola ao',
    NOW(), NOW()), ('12333664', NULL, 'Tchessilimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -14.04981, 16.2624, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tchessilimane tchessilimane angola ao',
    NOW(), NOW()), ('12333980', NULL, 'Tchitilimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -14.33302, 16.96705, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tchitilimane tchitilimane angola ao',
    NOW(), NOW()), ('12361728', NULL, 'Cilimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -12.97337, 18.25673, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cilimane cilimane angola ao',
    NOW(), NOW()), ('12361900', NULL, 'Cilimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -13.07207, 18.03134, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cilimane cilimane angola ao',
    NOW(), NOW()), ('12362051', NULL, 'Silimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -13.64422, 18.54571, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'silimane silimane angola ao',
    NOW(), NOW()), ('12402393', NULL, 'Catoca Airport', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -9.43244, 20.31179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'catoca airport catoca airport angola ao ctv',
    NOW(), NOW()), ('12425315', NULL, 'Tchilimane', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -15.69361, 17.5474, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tchilimane tchilimane angola ao',
    NOW(), NOW()), ('12425322', NULL, 'Chana Tchilimane', 'ChanaTchilimane',
    NULL, 'AO', 'Angola', NULL, NULL,
    -15.71498, 17.56798, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chana tchilimane chanatchilimane angola ao',
    NOW(), NOW()), ('12519328', NULL, 'Dr. Antonio Agostinho Neto International Airport', NULL,
    NULL, 'AO', 'Angola', NULL, NULL,
    -9.05086, 13.49906, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'dr. antonio agostinho neto international airport dr. antonio agostinho neto international airport angola ao fnbj,nbj',
    NOW(), NOW()), ('13312245', NULL, 'Porto Alexandre', 'PortoAlexandre',
    NULL, 'AO', 'Angola', NULL, NULL,
    -15.80051, 11.88572, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto alexandre portoalexandre angola ao',
    NOW(), NOW()), ('13312329', NULL, 'Malembo Heliport', 'MalemboHeliport',
    NULL, 'AO', 'Angola', NULL, NULL,
    -5.39528, 12.21278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'malembo heliport malemboheliport angola ao',
    NOW(), NOW()), ('6620309', NULL, 'Peter I Island', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -68.84722, -90.59673, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'peter i island peter i island aq aq enez per ian,enez pêr iañ,i petr araly,i pyotr adasi,i pyotr adası,i петран гӏайре,ile pierre ier,ilha de pedro i,illa pedro i,illa pere i,insula petru i,insulo petro la unua,isla pedro i,isoa de pe primmo,isoa de pè primmo,isola pietro i,oilean pheadar i,oileán pheadar i,ostriv petra i,ostrov petra i,ostrvo petra i,pedro i  isla,peeter i saar,peter 1.s oy,peter 1.s øy,peter i island,peter i island (norway),peter i oy,peter i soulu,peter i øy,peter i-eiland,peter i-eilan,peter i-eiland,peter i-eilân,peter is o,peter is ø,peter-i.-insel,peter-i.-insel (norwegen),petera i sala,petr i utravy,petra i  ostrov,petro i sala,pulau peter i,pulo peter i,pētera i sala,vostrau pjatra i,wyspa piotra i,bi de yi shi dao,jzyrh ptr ykm,jzyrt btrs alawl,keaa pi texr thi 1,peteleu 1se seom,pitara 1 dbipa,pyotoru1shi dao,île pierre ier,νησί του πέτρου α΄,і петр аралы,востраў пятра i,острво петра i,остров петра i,острів петра i,петр i утравы,פטר הראשון,جزيرة بطرس الأول,جزیره پتر یکم,جزیرہ پیٹر اول,পিটার ১ দ্বীপ,เกาะปีเตอร์ที่ 1,პეტრე i-ის კუნძული,ピョートル1世島,彼得一世岛,彼得一世島,페테르 1세 섬',
    NOW(), NOW()), ('6620767', NULL, 'Marambio Airport', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.23922, -56.63538, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marambio airport marambio airport aq aq aerodromo marambio,aeroport de marambio,aeródromo marambio,aéroport de marambio,marambio airport,marambio-basen,marambio-basen (argentina),sawb',
    NOW(), NOW()), ('6622070', NULL, 'Napier Island', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -69.22295, -67.78717, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier island napier island aq aq napier island',
    NOW(), NOW()), ('6622071', NULL, 'Napier Mountains', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -66.5, 53.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier mountains napier mountains aq aq napier mountains',
    NOW(), NOW()), ('6622072', NULL, 'Napier Peak', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -62.67198, -60.31835, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier peak napier peak aq aq napier peak',
    NOW(), NOW()), ('6622074', NULL, 'Napier, roca', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -62.16694, -58.43965, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier, roca napier, roca aq aq napier rock,napier  roca',
    NOW(), NOW()), ('6622109', NULL, 'Marina, punta', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.49629, -62.46068, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina, punta marina, punta aq aq marina  punta,navy point',
    NOW(), NOW()), ('6622132', NULL, 'Neko, puerto', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.83833, -62.53272, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'neko, puerto neko, puerto aq aq neko harbor,neko harbour,neko  puerto',
    NOW(), NOW()), ('6622203', NULL, 'New Harbor', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -77.6, 163.85, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'new harbor new harbor aq aq new harbor,new harbour',
    NOW(), NOW()), ('6622205', NULL, 'New Plymouth', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -62.61813, -61.18474, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'new plymouth new plymouth aq aq echeverria  puerto,echeverría  puerto,new plymouth,nueva plymouth  bahia,nueva plymouth  bahía',
    NOW(), NOW()), ('6622301', NULL, 'Nisi-Hamna Ike', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -69.29167, 39.71667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nisi-hamna ike nisi-hamna ike aq aq',
    NOW(), NOW()), ('6622393', NULL, 'North Portal', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -68.58, 78.12722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north portal north portal aq aq',
    NOW(), NOW()), ('6622690', NULL, 'Orne Harbor', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.62161, -62.53193, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'orne harbor orne harbor aq aq orne harbor,orne harbour,orne  puerto',
    NOW(), NOW()), ('6622813', NULL, 'Paal, puerto', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -60.716, -45.583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paal, puerto paal, puerto aq aq paal harbor,paal harbour,paal  puerto,pal harbour,pål harbour',
    NOW(), NOW()), ('6622894', NULL, 'Paradise Harbour', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.85, -62.9, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'paradise harbour paradise harbour aq aq paradise harbor,paradise harbour,paraiso  bahia,paraiso  puerto,paraíso  bahía,paraíso  puerto',
    NOW(), NOW()), ('6623019', NULL, 'Pearl Harbor Glacier', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -72.25, 167.66667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'pearl harbor glacier pearl harbor glacier aq aq pearl harbor glacier',
    NOW(), NOW()), ('6623264', NULL, 'Pierce Peak', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -84.866, -63.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierce peak pierce peak aq aq pierce peak',
    NOW(), NOW()), ('6623265', NULL, 'Pedro, monte', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -63.96667, -61.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pedro, monte pedro, monte aq aq pedro  monte,pierre  mount',
    NOW(), NOW()), ('6623267', NULL, 'Mount Pierre', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -71.3, 35.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre mount pierre aq aq mont pierre,mount pierre,pierre,pi ai er shan,皮埃爾山',
    NOW(), NOW()), ('6623360', NULL, 'Belles Pierres, Terrasse des', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -66.67111, 140.01139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belles pierres, terrasse des belles pierres, terrasse des aq aq',
    NOW(), NOW()), ('6623492', NULL, 'Port-Martin', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -66.81944, 141.39167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port-martin port-martin aq aq port martin /fr./,port-martin',
    NOW(), NOW()), ('6623493', NULL, 'Portal Mountain', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -78.1, 159.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal mountain portal mountain aq aq portal mountain,portal  mount,bo ta er shan,波塔爾山',
    NOW(), NOW()), ('6623494', NULL, 'Portal Point', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -64.50284, -61.75896, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal point portal point aq aq portal point,portal  punta',
    NOW(), NOW()), ('6623495', NULL, 'Portal Rock', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -83.83333, 165.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal rock portal rock aq aq portal rock,bo te er yan,波特爾岩',
    NOW(), NOW()), ('6623496', NULL, 'Portalen', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -72.71667, -3.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portalen portalen aq aq portalen,portalen pass',
    NOW(), NOW()), ('6623497', NULL, 'Portal, The', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -78.03333, 159.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal, the portal, the aq aq portal  the',
    NOW(), NOW()), ('6623498', NULL, 'Porten', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -72.21667, 2.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porten porten aq aq porten,porten pass',
    NOW(), NOW()), ('6623500', NULL, 'Porteous, punta', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -60.724, -45.675, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteous, punta porteous, punta aq aq porteous point,porteous  punta',
    NOW(), NOW()), ('6623501', NULL, 'Porters Pinnacles', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -71.55, -99.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters pinnacles porters pinnacles aq aq porters pinnacles',
    NOW(), NOW()), ('6623502', NULL, 'Mount Porteus', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -66.81667, 51.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount porteus mount porteus aq aq mount porteus,porteus,bo tu si shan,הר פורטאוס,波圖斯山',
    NOW(), NOW()), ('6623503', NULL, 'Porthos Range', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -70.44472, 65.65528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porthos range porthos range aq aq porthos range',
    NOW(), NOW()), ('6623504', NULL, 'Portnipa Peak', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -72.23333, 2.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portnipa peak portnipa peak aq aq portnipa,portnipa peak',
    NOW(), NOW()), ('6623856', NULL, 'Rambler Harbor', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -66.46846, -66.42781, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'rambler harbor rambler harbor aq aq rambler harbor,rambler harbour',
    NOW(), NOW()), ('6624107', NULL, 'Rhamnus, Mount', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -68.18209, -66.82755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rhamnus, mount rhamnus, mount aq aq rhamnus  mount',
    NOW(), NOW()), ('6625631', NULL, 'Birks, Mount', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -65.2899, -62.16325, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birks, mount birks, mount aq aq birks  mount,napier birks  monte',
    NOW(), NOW()), ('6625635', NULL, 'Soberanía, Puerto', 'Soberania, Puerto',
    NULL, 'AQ', 'AQ', NULL, NULL,
    -62.48333, -59.63333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'soberanía, puerto soberania, puerto aq aq',
    NOW(), NOW()), ('6625767', NULL, 'South Portal', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -68.58361, 78.12778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south portal south portal aq aq',
    NOW(), NOW()), ('6625821', NULL, 'Spence, puerto', NULL,
    NULL, 'AQ', 'AQ', NULL, NULL,
    -60.683, -45.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'spence, puerto spence, puerto aq aq spence harbor,spence harbour,spence  puerto',
    NOW(), NOW());