INSERT INTO ports (
        world_port_index, region_name, main_port_name, alternate_port_name,
        un_locode, country_code, country_name, world_water_body, iho_sea_area,
        latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
        tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
        max_vessel_length, max_vessel_beam, max_vessel_draft,
        pilotage_compulsory, pilotage_available, tugs_assistance,
        facilities_wharves, facilities_anchorage, facilities_container,
        facilities_oil_terminal, facilities_lng_terminal, search_text,
        created_at, updated_at
      ) VALUES ('3452631', NULL, 'Pôrto Tagaçaba', 'Porto Tagacaba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.21667, -48.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto tagaçaba porto tagacaba brazil br',
    NOW(), NOW()), ('3452632', NULL, 'Pôrto Taboado', 'Porto Taboado',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.18333, -51.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto taboado porto taboado brazil br porto taboado,porto tabuado,porto do taboado,pôrto taboado,pôrto tabuado',
    NOW(), NOW()), ('3452633', NULL, 'Pôrto Sol de Maio', 'Porto Sol de Maio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.06067, -54.38397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sol de maio porto sol de maio brazil br porto sol de maio,pôrto sol de maio,sol de maio',
    NOW(), NOW()), ('3452634', NULL, 'Pôrto Sinop', 'Porto Sinop',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.08333, -53.98333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sinop porto sinop brazil br porto sinop,porto snope,pôrto sinop,pôrto snope',
    NOW(), NOW()), ('3452635', NULL, 'Pôrto Sete de Setembro', 'Porto Sete de Setembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.18333, -54.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sete de setembro porto sete de setembro brazil br',
    NOW(), NOW()), ('3452636', NULL, 'Pôrto Sete de Setembro', 'Porto Sete de Setembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.21667, -52.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sete de setembro porto sete de setembro brazil br porto 7 de setembro,porto sete de setembro,pôrto 7 de setembro,pôrto sete de setembro',
    NOW(), NOW()), ('3452637', NULL, 'Baía de Pôrto Seguro', 'Baia de Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.45, -39.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baía de pôrto seguro baia de porto seguro brazil br baia de porto seguro,baía de pôrto seguro',
    NOW(), NOW()), ('3452638', NULL, 'Pôrto Seguro', 'Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9, -50.43333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto seguro porto seguro brazil br',
    NOW(), NOW()), ('3452639', NULL, 'Pôrto Seguro', 'Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.68333, -42.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto seguro porto seguro brazil br porto seguro,pôrto seguro',
    NOW(), NOW()), ('3452640', NULL, 'Porto Seguro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.44972, -39.06472, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'porto seguro porto seguro brazil br bps,portu-seguru,bwrtw syjwrw,parto seguro,sai gu lu gang,порту-сегуру,بورتو سيجورو,পর্টো সেগুরো,პორტუ-სეგურუ,ポルト・セグーロ,塞古鲁港',
    NOW(), NOW()), ('3452641', NULL, 'Pôrto Sassoró', 'Porto Sassoro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.56667, -54.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sassoró porto sassoro brazil br porto sassora,porto sassoro,pôrto sassorá,pôrto sassoró,sassoro,sassoró',
    NOW(), NOW()), ('3452642', NULL, 'Pôrto Sapé', 'Porto Sape',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.9, -53.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sapé porto sape brazil br',
    NOW(), NOW()), ('3452643', NULL, 'Pôrto Sapé', 'Porto Sape',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.88333, -54.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sapé porto sape brazil br porto cafe,porto cape,porto sape,pôrto café,pôrto capé,pôrto sapé',
    NOW(), NOW()), ('3452644', NULL, 'Pôrto São Pedro', 'Porto Sao Pedro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.75, -53.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são pedro porto sao pedro brazil br',
    NOW(), NOW()), ('3452645', NULL, 'Pôrto São Paulo Novo', 'Porto Sao Paulo Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.98333, -52.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são paulo novo porto sao paulo novo brazil br',
    NOW(), NOW()), ('3452646', NULL, 'Pôrto São Martinho', 'Porto Sao Martinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.73333, -54.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são martinho porto sao martinho brazil br porto martinho,porto sao martinho,pôrto são martinho',
    NOW(), NOW()), ('3452647', NULL, 'Pôrto São José Velho', 'Porto Sao Jose Velho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.36937, -56.79125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são josé velho porto sao jose velho brazil br porto sao jose,porto sao jose velho,pôrto são josé,pôrto são josé velho,sao jose,são josé',
    NOW(), NOW()), ('3452648', NULL, 'Porto São José', 'Porto Sao Jose',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.71861, -53.17639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto são josé porto sao jose brazil br sao jose,são josé',
    NOW(), NOW()), ('3452649', NULL, 'Pôrto São João', 'Porto Sao Joao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63333, -53.13333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são joão porto sao joao brazil br porto sao joao,pôrto são joão,sao joao,são joão',
    NOW(), NOW()), ('3452650', NULL, 'Pôrto São Jerônimo', 'Porto Sao Jeronimo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.07153, -50.18797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são jerônimo porto sao jeronimo brazil br porto sao jeronimo,porto sao jeronymo,porto do jeronimo,pôrto são jeronymo,pôrto são jerônimo,pôrto do jerónimo,sao jeronimo,são jerônimo',
    NOW(), NOW()), ('3452651', NULL, 'Pôrto São Francisco', 'Porto Sao Francisco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6, -53.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são francisco porto sao francisco brazil br',
    NOW(), NOW()), ('3452652', NULL, 'Pôrto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.57452, -54.27658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são domingos porto sao domingos brazil br',
    NOW(), NOW()), ('3452653', NULL, 'Pôrto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.21667, -50.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são domingos porto sao domingos brazil br porto sao domingos,porto de sao domingos,porto de são domingos,pôrto são domingos',
    NOW(), NOW()), ('3452654', NULL, 'Porto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.95, -51.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto são domingos porto sao domingos brazil br porto sao domingos,porto são domingos',
    NOW(), NOW()), ('3452655', NULL, 'Pôrto São Bento', 'Porto Sao Bento',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.01667, -53.71667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são bento porto sao bento brazil br',
    NOW(), NOW()), ('3452656', NULL, 'Pôrto Santo Antônio', 'Porto Santo Antonio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.47227, -54.34361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santo antônio porto santo antonio brazil br',
    NOW(), NOW()), ('3452657', NULL, 'Praia do Pôrto Santo', 'Praia do Porto Santo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.81667, -43.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'praia do pôrto santo praia do porto santo brazil br praia do porto santo,praia do pôrto santo',
    NOW(), NOW()), ('3452658', NULL, 'Pôrto Santa Rosa', 'Porto Santa Rosa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.46667, -53.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa rosa porto santa rosa brazil br',
    NOW(), NOW()), ('3452659', NULL, 'Pôrto Santa Rosa', 'Porto Santa Rosa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.98333, -57.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa rosa porto santa rosa brazil br porto santa rosa,pôrto santa rosa,santa rosa',
    NOW(), NOW()), ('3452660', NULL, 'Pôrto Santana', 'Porto Santana',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.66667, -52.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santana porto santana brazil br',
    NOW(), NOW()), ('3452661', NULL, 'Pôrto Santa Maria', 'Porto Santa Maria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.71667, -52.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa maria porto santa maria brazil br',
    NOW(), NOW()), ('3452662', NULL, 'Pôrto Santa Bárbara', 'Porto Santa Barbara',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.5, -53.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa bárbara porto santa barbara brazil br porto santa barbara,pôrto santa bárbara,santa barbara,santa bárbara',
    NOW(), NOW()), ('3452663', NULL, 'Pôrto Rolon', 'Porto Rolon',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.23333, -53.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rolon porto rolon brazil br',
    NOW(), NOW()), ('3452664', NULL, 'Pôrto Rode', 'Porto Rode',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.16667, -53.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rode porto rode brazil br',
    NOW(), NOW()), ('3452665', NULL, 'Pôrto Rio Iguatemi', 'Porto Rio Iguatemi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.93333, -54.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rio iguatemi porto rio iguatemi brazil br',
    NOW(), NOW()), ('3452666', NULL, 'Pôrto Rio Amambaí', 'Porto Rio Amambai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.33333, -53.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rio amambaí porto rio amambai brazil br',
    NOW(), NOW()), ('3452667', NULL, 'Porto Rico', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.77222, -53.26694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto rico porto rico brazil br',
    NOW(), NOW()), ('3452668', NULL, 'Pôrto Ribeiro', 'Porto Ribeiro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.45, -48.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ribeiro porto ribeiro brazil br porto ribeiro,pôrto ribeiro',
    NOW(), NOW()), ('3452669', NULL, 'Pôrto Ribeirão Vermelho', 'Porto Ribeirao Vermelho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7, -51.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ribeirão vermelho porto ribeirao vermelho brazil br porto ribeirao vermelho,pôrto ribeirão vermelho,vermelho',
    NOW(), NOW()), ('3452670', NULL, 'Porto Real do Colégio', 'Porto Real Do Colegio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.10538, -36.72695, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real do colégio porto real do colegio brazil br',
    NOW(), NOW()), ('3452671', NULL, 'Porto Real do Colégio', 'Porto Real do Colegio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.18583, -36.84, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real do colégio porto real do colegio brazil br porto real do collegio',
    NOW(), NOW()), ('3452672', NULL, 'Porto Real', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.41972, -44.29028, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real porto real brazil br',
    NOW(), NOW()), ('3452673', NULL, 'Pôrto Quiqui', 'Porto Quiqui',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.95, -54.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quiqui porto quiqui brazil br porto kiki,porto quiqui,pôrto kiki,pôrto quiqui',
    NOW(), NOW()), ('3452674', NULL, 'Pôrto Quinze de Novembro', 'Porto Quinze de Novembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.78333, -52.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de novembro porto quinze de novembro brazil br porto 15 novembro,porto 15 de novembre,porto quinze de novembro,pôrto 15 novembro,pôrto 15 de novembre,pôrto quinze de novembro',
    NOW(), NOW()), ('3452675', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.71667, -53.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agôsto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452676', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.65, -53.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agôsto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452677', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.96667, -53.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agosto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452678', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.21667, -59.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze,porto quinze de agosto,pôrto 15 de agosto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452680', NULL, 'Pôrto Quebracho', 'Porto Quebracho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.83333, -57.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quebracho porto quebracho brazil br porto quebracho,porto quebrado,pôrto quebracho,pôrto quebrado',
    NOW(), NOW()), ('3452681', NULL, 'Pôrto Quebra-Canoas', 'Porto Quebra-Canoas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91667, -50.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quebra-canoas porto quebra-canoas brazil br porto quebra-canoas,porto teixeira,pôrto quebra-canoas',
    NOW(), NOW());