INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('3840733', NULL, 'Portillo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.31667, -68.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo portillo argentina ar',
    NOW(), NOW()), ('3840734', NULL, 'Portillo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -23.53333, -65.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo portillo argentina ar',
    NOW(), NOW()), ('3840735', NULL, 'Cerro los Portezuelos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.26769, -67.98909, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro los portezuelos cerro los portezuelos argentina ar',
    NOW(), NOW()), ('3840736', NULL, 'Estación Portezuelo Infiernillo', 'Estacion Portezuelo Infiernillo',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.45, -67.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estación portezuelo infiernillo estacion portezuelo infiernillo argentina ar',
    NOW(), NOW()), ('3840737', NULL, 'Cerros del Portezuelo de Borbarán', 'Cerros del Portezuelo de Borbaran',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.88628, -68.41126, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerros del portezuelo de borbarán cerros del portezuelo de borbaran argentina ar',
    NOW(), NOW()), ('3840738', NULL, 'Portezuelo de Arce', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.9, -66.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de arce portezuelo de arce argentina ar',
    NOW(), NOW()), ('3840739', NULL, 'Cerro Portezuelo Carqueque', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.53081, -70.05559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo carqueque cerro portezuelo carqueque argentina ar cerro portezuelo carqueque,cerro portillo carqueque',
    NOW(), NOW()), ('3840740', NULL, 'Puesto Portezuelo Barreales Hondo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.81667, -68.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto portezuelo barreales hondo puesto portezuelo barreales hondo argentina ar',
    NOW(), NOW()), ('3840741', NULL, 'Sierra del Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.89473, -69.55007, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sierra del portezuelo sierra del portezuelo argentina ar',
    NOW(), NOW()), ('3840742', NULL, 'Sierra del Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.13732, -65.19607, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sierra del portezuelo sierra del portezuelo argentina ar',
    NOW(), NOW()), ('3840743', NULL, 'Río del Portezuelo', 'Rio del Portezuelo',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.71836, -68.11065, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'río del portezuelo rio del portezuelo argentina ar rio del portezuelo,río del portezuelo',
    NOW(), NOW()), ('3840744', NULL, 'Puesto Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.31818, -65.4215, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto portezuelo puesto portezuelo argentina ar',
    NOW(), NOW()), ('3840745', NULL, 'Puesto Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.27184, -65.06422, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto portezuelo puesto portezuelo argentina ar',
    NOW(), NOW()), ('3840746', NULL, 'Loma del Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.89189, -68.65916, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'loma del portezuelo loma del portezuelo argentina ar',
    NOW(), NOW()), ('3840747', NULL, 'Cerro de Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.27636, -65.07322, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro de portezuelo cerro de portezuelo argentina ar cerro de portezuelo',
    NOW(), NOW()), ('3840748', NULL, 'Cerro Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -43.2, -70.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo cerro portezuelo argentina ar cerro portezuelo',
    NOW(), NOW()), ('3840749', NULL, 'Cerro Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.75, -67.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo cerro portezuelo argentina ar cerro portezuelo',
    NOW(), NOW()), ('3840750', NULL, 'Cerro Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.87327, -71.24174, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo cerro portezuelo argentina ar cerro portezuelo',
    NOW(), NOW()), ('3840751', NULL, 'Cerro Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.50534, -64.67174, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo cerro portezuelo argentina ar',
    NOW(), NOW()), ('3840752', NULL, 'Cerro Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.28913, -65.67904, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro portezuelo cerro portezuelo argentina ar cerro portezuelo',
    NOW(), NOW()), ('3840753', NULL, 'Arroyo del Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.3, -70.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo del portezuelo arroyo del portezuelo argentina ar',
    NOW(), NOW()), ('3840754', NULL, 'Arroyo del Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.3669, -65.80118, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo del portezuelo arroyo del portezuelo argentina ar',
    NOW(), NOW()), ('3840755', NULL, 'Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -23.56667, -65.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo portezuelo argentina ar',
    NOW(), NOW()), ('3840756', NULL, 'Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.37015, -64.21498, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo portezuelo argentina ar',
    NOW(), NOW()), ('3840757', NULL, 'Portezuelo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.91667, -66.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo portezuelo argentina ar portezucho,portezuelo',
    NOW(), NOW()), ('3840758', NULL, 'Pampa Porteña', 'Pampa Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.98471, -61.41691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pampa porteña pampa portena argentina ar pampa portena,pampa porteña',
    NOW(), NOW()), ('3840759', NULL, 'Laguna de la Porteña', 'Laguna de la Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.55366, -70.22752, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna de la porteña laguna de la portena argentina ar laguna cafuenco,laguna cafuencó,laguna de la portena,laguna de la porteña,laguna de la portona,laguna de la portoña',
    NOW(), NOW()), ('3840760', NULL, 'Isla Porteña', 'Isla Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.8, -63.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'isla porteña isla portena argentina ar isla portena,isla porteña',
    NOW(), NOW()), ('3840761', NULL, 'Colonia Porteña', 'Colonia Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.96667, -62.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colonia porteña colonia portena argentina ar',
    NOW(), NOW()), ('3840762', NULL, 'Porteña', 'Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.01409, -62.06204, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porteña portena argentina ar portena,porteña',
    NOW(), NOW()), ('3840763', NULL, 'Puesto Port Arthur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.97828, -60.75004, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto port arthur puesto port arthur argentina ar',
    NOW(), NOW()), ('3840764', NULL, 'Portada Covunco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.78704, -70.17444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portada covunco portada covunco argentina ar',
    NOW(), NOW()), ('3840765', NULL, 'Arroyo Chorrillo de la Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -50.52832, -71.64894, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo chorrillo de la portada arroyo chorrillo de la portada argentina ar arroyo chorrillo de la portada,chorrillo de la portada',
    NOW(), NOW()), ('3840766', NULL, 'Cerro La Portada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -43.01825, -71.614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro la portada cerro la portada argentina ar cerro la portada',
    NOW(), NOW()), ('3840936', NULL, 'Paso del Planchón', 'Paso del Planchon',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.2, -70.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso del planchón paso del planchon argentina ar paso del planchon,paso del planchón,portezuelo del planchon,portezuelo del planchón',
    NOW(), NOW()), ('3840947', NULL, 'Portezuelo de Piuquenes', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.63331, -69.87461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de piuquenes portezuelo de piuquenes argentina ar paso piuquenes,paso del portillo de los piuquenes,portezuelo los piuquenes',
    NOW(), NOW()), ('3841009', NULL, 'Puerto Pirámide', 'Puerto Piramide',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.58333, -64.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto pirámide puerto piramide argentina ar port piramide,port pirámide,puerto piramide,puerto piramides,puerto pirámide,puerto pirámides,puerto de piramide,puerto de pirámide',
    NOW(), NOW()), ('3841111', NULL, 'Portezuelo Pilunchaya', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.6, -71.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo pilunchaya portezuelo pilunchaya argentina ar paso de pilunchaya,paso de pitunchaya,portezuelo pilunchaya',
    NOW(), NOW()), ('3841160', NULL, 'Arroyo Pierrestegui', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.5989, -71.37427, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo pierrestegui arroyo pierrestegui argentina ar',
    NOW(), NOW()), ('3841187', NULL, 'Portezuelo Piedras Bayas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.97433, -70.20466, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo piedras bayas portezuelo piedras bayas argentina ar portezuelo piedras bayas,portillo piedras bayas',
    NOW(), NOW()), ('3841246', NULL, 'Portillo de la Piedra Blanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.56667, -69.31667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la piedra blanca portillo de la piedra blanca argentina ar',
    NOW(), NOW()), ('3841333', NULL, 'Portillo del Pico', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.78691, -69.5634, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del pico portillo del pico argentina ar',
    NOW(), NOW()), ('3841476', NULL, 'Perito Moreno', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -41.11618, -71.4094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'perito moreno perito moreno argentina ar perito moreno,puerto moreno',
    NOW(), NOW()), ('3841626', NULL, 'Paso de Pelambres', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.7, -70.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de pelambres paso de pelambres argentina ar paso pelambres,paso de pelambres,paso los pelambres,pelambres,portezuelo de los pelambres',
    NOW(), NOW()), ('3841712', NULL, 'Portillo Pedernales', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.91132, -69.48736, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo pedernales portillo pedernales argentina ar',
    NOW(), NOW()), ('3841803', NULL, 'Portezuelo de Pasto Ventura', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.66919, -67.22404, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de pasto ventura portezuelo de pasto ventura argentina ar abra de ventura,portezuelo de pasto ventura',
    NOW(), NOW()), ('3841873', NULL, 'Puesto Paso de los Potrillos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.93333, -67.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto paso de los potrillos puesto paso de los potrillos argentina ar portillos,puesto paso de los potrillos',
    NOW(), NOW()), ('3841927', NULL, 'Puerto Parry', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.77386, -64.36993, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto parry puerto parry argentina ar',
    NOW(), NOW()), ('3841960', NULL, 'Puerto Páramo Chico', 'Puerto Paramo Chico',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -53.01521, -68.26581, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto páramo chico puerto paramo chico argentina ar paramo chico,puerto paramo chico,puerto páramo chico,páramo chico',
    NOW(), NOW()), ('3842006', NULL, 'Portezuelo Pantojo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.73333, -71.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo pantojo portezuelo pantojo argentina ar paso pantoja,portezuelo pantajo,portezuelo pantojo',
    NOW(), NOW()), ('3842043', NULL, 'Portillo Pan de Azúcar', 'Portillo Pan de Azucar',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.61934, -70.11231, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo pan de azúcar portillo pan de azucar argentina ar',
    NOW(), NOW()), ('3842116', NULL, 'Pampa La Porteña', 'Pampa La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.89233, -61.1198, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pampa la porteña pampa la portena argentina ar pampa la portena,pampa la porteña',
    NOW(), NOW()), ('3842173', NULL, 'Portillo de la Pampa', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.28373, -69.04573, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de la pampa portillo de la pampa argentina ar',
    NOW(), NOW()), ('3842327', NULL, 'Portezuelo de Palauco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.88431, -69.49439, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de palauco portezuelo de palauco argentina ar',
    NOW(), NOW()), ('3842359', NULL, 'Puerto Pajarito', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -47.03923, -66.62621, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto pajarito puerto pajarito argentina ar',
    NOW(), NOW()), ('3842422', NULL, 'Portezuelo del Pachón', 'Portezuelo del Pachon',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.75, -70.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del pachón portezuelo del pachon argentina ar portezuelo del pachon,portezuelo del pachón',
    NOW(), NOW()), ('3842487', NULL, 'Paso Overas Sur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.85, -70.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso overas sur paso overas sur argentina ar paso overas sur,portezuelo las overas sur',
    NOW(), NOW()), ('3842488', NULL, 'Paso Overas Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.83333, -70.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso overas norte paso overas norte argentina ar paso overas norte,portezuelo las overas norte',
    NOW(), NOW()), ('3842493', NULL, 'Portezuelo Oveleros', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.16986, -67.29042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo oveleros portezuelo oveleros argentina ar',
    NOW(), NOW()), ('3842581', NULL, 'Paso Quebrada Seca Oriental', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.38333, -70.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso quebrada seca oriental paso quebrada seca oriental argentina ar paso quebrada seca,paso quebrada seca oriental,paso de munizaga,portezuelo oriental de la quebrada seca',
    NOW(), NOW()), ('3842779', NULL, 'Paso Quebrada Seca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.38333, -70.1, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso quebrada seca paso quebrada seca argentina ar paso manizaga,paso munizaga,paso quebrada seca,paso de manizaga,portezuelo munizaga,portezuelo occidental de la quebrada seca,portezuelo quebrada seca occidental',
    NOW(), NOW()), ('3842884', NULL, 'Nueve de Julio', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.3983, -60.93792, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nueve de julio nueve de julio argentina ar nueve de julio,nueve de julio airport,sazx',
    NOW(), NOW()), ('3842943', NULL, 'Portezuelo Noveno', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -48.48333, -71.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo noveno portezuelo noveno argentina ar',
    NOW(), NOW()), ('3842965', NULL, 'Portillo del Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.5977, -70.0981, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del norte portillo del norte argentina ar',
    NOW(), NOW()), ('3842966', NULL, 'Portillo del Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.21667, -69.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del norte portillo del norte argentina ar',
    NOW(), NOW()), ('3843043', NULL, 'Portillo del Ñireco', 'Portillo del Nireco',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.03746, -70.61688, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del ñireco portillo del nireco argentina ar',
    NOW(), NOW()), ('3843119', NULL, 'Portezuelo Nevada', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.35, -67.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo nevada portezuelo nevada argentina ar',
    NOW(), NOW()), ('3843543', NULL, 'Portillo de Mulas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.81198, -68.98343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de mulas portillo de mulas argentina ar',
    NOW(), NOW()), ('3843579', NULL, 'Paso los Muchachos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.26667, -70.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso los muchachos paso los muchachos argentina ar paso los muchachos,portezuelo de los muchachos',
    NOW(), NOW()), ('3843755', NULL, 'Portillo Moradito', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.55, -69, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo moradito portillo moradito argentina ar',
    NOW(), NOW()), ('3843963', NULL, 'Portillo el Molle', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.23276, -67.63079, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo el molle portillo el molle argentina ar',
    NOW(), NOW()), ('3844206', NULL, 'Portezuelo de las Minas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.86163, -69.63823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de las minas portezuelo de las minas argentina ar paso de las minas,portezuelo de las minas',
    NOW(), NOW()), ('3844260', NULL, 'Portezuelo del Milico', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.68024, -69.83919, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del milico portezuelo del milico argentina ar',
    NOW(), NOW()), ('3844396', NULL, 'Portillo Mercedario', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.98556, -70.20638, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo mercedario portillo mercedario argentina ar',
    NOW(), NOW()), ('3844443', NULL, 'Puerto Melo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -45.01998, -65.85292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto melo puerto melo argentina ar',
    NOW(), NOW()), ('3844496', NULL, 'Portillo del Medio', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.39914, -69.90655, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del medio portillo del medio argentina ar',
    NOW(), NOW()), ('3844900', NULL, 'Marcos Juárez Airport', 'Marcos Juarez Airport',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.68333, -62.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marcos juárez airport marcos juarez airport argentina ar aerodromo marcos juarez,aeródromo marcos juárez,saom',
    NOW(), NOW()), ('3845080', NULL, 'Portezuelo Mal Paso', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.98732, -67.25823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo mal paso portezuelo mal paso argentina ar',
    NOW(), NOW()), ('3845153', NULL, 'Malimán de Arriba', 'Maliman de Arriba',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.93469, -69.16991, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'malimán de arriba maliman de arriba argentina ar maliman de arriba,malimán de arriba',
    NOW(), NOW()), ('3845154', NULL, 'Malimán', 'Maliman',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.95864, -69.17893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'malimán maliman argentina ar maliman,maliman de abajo,malimán,malimán de abajo',
    NOW(), NOW()), ('3845171', NULL, 'Portezuelo del Mal Barco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.08862, -69.89415, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del mal barco portezuelo del mal barco argentina ar',
    NOW(), NOW()), ('3845225', NULL, 'Portezuelo de Maíz Gordo', 'Portezuelo de Maiz Gordo',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.35, -64.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de maíz gordo portezuelo de maiz gordo argentina ar portezuelo de maiz gordo,portezuelo de maíz gordo,puerta del maiz gordo,puerta del maíz gordo',
    NOW(), NOW()), ('3845437', NULL, 'Portezuelo de las Lozas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.05, -68.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de las lozas portezuelo de las lozas argentina ar paso fraile,paso las lozas,paso de las lozas,portezuelo de las lozas',
    NOW(), NOW()), ('3845573', NULL, 'Portezuelo Los Tábanos', 'Portezuelo Los Tabanos',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.33333, -71.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo los tábanos portezuelo los tabanos argentina ar portezuelo los tabanos,portezuelo los tábanos',
    NOW(), NOW()), ('3845611', NULL, 'Portezuelo Los Rucos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.26667, -71.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo los rucos portezuelo los rucos argentina ar portezuelo los rucos',
    NOW(), NOW()), ('3845726', NULL, 'Arroyo Los Porteños', 'Arroyo Los Portenos',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.93159, -60.52691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo los porteños arroyo los portenos argentina ar',
    NOW(), NOW()), ('3845796', NULL, 'Portillo de Los Patos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.81667, -70.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de los patos portillo de los patos argentina ar',
    NOW(), NOW()), ('3846280', NULL, 'Portillo Los Chilenos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.04209, -69.673, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo los chilenos portillo los chilenos argentina ar',
    NOW(), NOW()), ('3846643', NULL, 'Portezuelo de Loncoche', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.70464, -69.67081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de loncoche portezuelo de loncoche argentina ar portezuelo de loncoche,portillo de loncoche',
    NOW(), NOW()), ('3846737', NULL, 'Logroño', 'Logrono',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.50363, -61.69559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'logroño logrono argentina ar logrono,logroño,portalis',
    NOW(), NOW()), ('3846770', NULL, 'Portezuelo Llullaillaco Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.63333, -68.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo llullaillaco norte portezuelo llullaillaco norte argentina ar portezuelo llullaillaco norte,portezuelo de la zorra vieja',
    NOW(), NOW()), ('3846833', NULL, 'Lipeo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -22.43113, -64.73845, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lipeo lipeo argentina ar lipeo,lipeo argentino,puerto lipes argentino',
    NOW(), NOW()), ('3846878', NULL, 'Arroyo Limenco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.03615, -70.89359, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo limenco arroyo limenco argentina ar arroyo limenco,arroyo llimanco',
    NOW(), NOW()), ('3846957', NULL, 'Portezuelo de León Muerto', 'Portezuelo de Leon Muerto',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.02331, -66.85671, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de león muerto portezuelo de leon muerto argentina ar',
    NOW(), NOW()), ('3847431', NULL, 'Portezuelo La Tranca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.61831, -66.78694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo la tranca portezuelo la tranca argentina ar',
    NOW(), NOW()), ('3847976', NULL, 'La Sortija', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.11188, -60.6907, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la sortija la sortija argentina ar la sortija,pierini',
    NOW(), NOW()), ('3848026', NULL, 'Portezuelo Las Numeradas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.09512, -69.69092, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo las numeradas portezuelo las numeradas argentina ar',
    NOW(), NOW()), ('3848895', NULL, 'Puerto Larrea', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -44.48767, -65.31431, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto larrea puerto larrea argentina ar',
    NOW(), NOW()), ('3849318', NULL, 'Estancia La Porteñita', 'Estancia La Portenita',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -47.28214, -70.06193, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteñita estancia la portenita argentina ar',
    NOW(), NOW()), ('3849319', NULL, 'Estancia La Porteñita', 'Estancia La Portenita',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.18011, -63.32803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteñita estancia la portenita argentina ar',
    NOW(), NOW());