INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('1435493', NULL, 'Salimānī Kārēz', 'Salimani Karez',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.18845, 62.95192, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salimānī kārēz salimani karez afghanistan af kyariz salemani,salemani karez,salemani kariz,salemāni kāṟēz,salemānī kārīz,salimani karez,salimānī kārēz,سلمانی کارېز',
    NOW(), NOW()), ('1436024', NULL, 'Pōrtah Akarah', 'Portah Akarah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.52446, 67.30078, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah akarah portah akarah afghanistan af porta akara,portah akarah,powrtah akarah,pōrtah akarah,pōṟta akaṟa,pwrth akrh,پورته اکره',
    NOW(), NOW()), ('1436045', NULL, 'Pōrtah Salād', 'Portah Salad',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.54061, 67.37061, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah salād portah salad afghanistan af porta salad,portah salad,powrtah salad,powrtah salād,pōrtah salād,pōṟta salāḏ,pwrth slad,پورته سلاد',
    NOW(), NOW()), ('1437188', NULL, 'Lūkhah', 'Lukhah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.40746, 67.36755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkhah lukhah afghanistan af lowkhah,luka,lukha,lukhah,lūkha,lūkhah,lwkhh,لوخه',
    NOW(), NOW()), ('1438104', NULL, 'Golō Kalā', 'Golo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.64387, 69.25277, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'golō kalā golo kala afghanistan af golo kala,golō kalā,gulukala,glw kl,glw kla,گلو كل,گلو کلا',
    NOW(), NOW()), ('1440105', NULL, 'Kōh-e Sangar-e ‘Alīmān', 'Koh-e Sangar-e ''Aliman',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.33313, 63.57134, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e sangar-e ‘alīmān koh-e sangar-e ''aliman afghanistan af koh-e sangar-e `aliman,kohe sangare ''aliman,kohe sangaṟe ’alimān,kuh-e sangar-e ''aliman,kōh-e sangar-e ‘alīmān,kūh-e sangar-e ’alīmān,کوه سنگر علیمان',
    NOW(), NOW()), ('1440106', NULL, 'Kōh-e Sangar-e Ghalīmān', 'Koh-e Sangar-e Ghaliman',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.32487, 63.62931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e sangar-e ghalīmān koh-e sangar-e ghaliman afghanistan af koh-e sangar-e ghaliman,kohe sangare ghaliman,kohe sangaṟe ghalimān,kuh-e sangar-e ghaliman,kōh-e sangar-e ghalīmān,kūh-e sangar-e ghalīmān,kwh sngr ghlyman,کوه سنگر غلیمان',
    NOW(), NOW()), ('1442983', NULL, 'Larī Bandar Kārēz', 'Lari Bandar Karez',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.34911, 67.87381, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'larī bandar kārēz lari bandar karez afghanistan af kyariz laribandar,lari bandar karez,lari bandar kariz,larī bandar kārēz,larī bandar kārīz,laṟi banḏaṟ kāṟēz,لری بندر کارېز',
    NOW(), NOW()), ('1447253', NULL, 'Ghazni Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.53194, 68.41333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ghazni airport ghazni airport afghanistan af gzi,ghazni airport,oagn,mydan hwayy ghzny,ميدانٔ هوائئ غزنی',
    NOW(), NOW()), ('1448497', NULL, 'Lukah-ye Surkh', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.84392, 63.91631, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye surkh lukah-ye surkh afghanistan af loka-i-surkh,loka-i-suṟkh,lokah-ye sorkh,lukah-ye surkh,لکۀ سرخ',
    NOW(), NOW()), ('1448501', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.83414, 63.89855, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokah sang,lokasang,lukah sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1448593', NULL, 'Lukah-ye Surkh', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.95449, 63.91507, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye surkh lukah-ye surkh afghanistan af loka-i-surkh,loka-i-suṟkh,lokah-ye sorkh,lukah-ye surkh,لکۀ سرخ',
    NOW(), NOW()), ('1449318', NULL, 'Nōlōkak', 'Nolokak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.74054, 66.21856, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nōlōkak nolokak afghanistan af nolokak,nowlukak,nowlūkak,nōlōkak,nwlwkk,نولوکک',
    NOW(), NOW()), ('1449744', NULL, 'Darah-ye Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.96462, 65.8075, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'darah-ye bandar darah-ye bandar afghanistan af darah-ye bandar,darya bandar,daryā bandar,درۀ بندر',
    NOW(), NOW()), ('1449939', NULL, 'Lūkah', 'Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.55975, 65.71295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah lukah afghanistan af lowkah,luka,lukah,lūka,lūkah,lwkh,لوكه,لوکه',
    NOW(), NOW()), ('1453658', NULL, 'Lō Kandah', 'Lo Kandah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.80427, 68.57231, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lō kandah lo kandah afghanistan af lo kanda,lo kandah,lo kanḏa,lowyah kandah,loya kanda,loyah kandah,lukanda,lō kandah,lōya kanḏa,lōyah kandah,lw kndh,lwyh kndh,لو کنده,لویه کنده',
    NOW(), NOW()), ('1453897', NULL, 'Tarin Kowt Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.60412, 65.86595, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tarin kowt airport tarin kowt airport afghanistan af oatn,tii,tarin kowt airport,tereen airport,tirinkot,tryn,ترین',
    NOW(), NOW()), ('1453901', NULL, 'Ahmad Shah Baba International Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.50737, 65.85035, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'ahmad shah baba international airport ahmad shah baba international airport afghanistan af aeroport internacional de kandahar,aeroporto internacional de candaar,aeroporto de kandahar,aeroportul international kandahar,aeroportul internațional kandahar,aeropuerto internacional de kandahar,aeropuertu internacional de kandahar,ahmad shah baba international airport,bandar udara kandahar,de afghanestan baynulmelali hawa''i dagar,de afghanistan baynulmilali hawa''i dagar,de qandahar baynulmelali hawa''i dagar,de qandahar baynulmilali hawa''i dagar,dê afghānistān baynulmilalī hawā’ī ḏagar,dê qandahār baynulmilalī hawā’ī ḏagar,flughafen kandahar,kdh,kandagar,kandahar,kandahar airfield,kandahar airport,kandahar international airport,kandahar internasjonale lufthavn,kandahari nemzetkoezi repueloter,kandaharin kansainvaelinen lentoasema,kandaharin kansainvälinen lentoasema,kandaharreko nazioarteko aireportua,kandahári nemzetközi repülőtér,kandahār,kandahār airfield,kandehar uluslararasi havalimani,kandehar uluslararası havalimanı,lapangan terbang kandahar,maes awyr rhyngwladol kandahar,oakn,port lotniczy kandahar,qandahor xalqaro aeroporti,aeroport international de kandahar,aeroporto internazionale di kandahar,aéroport international de kandahar,kan da ha guo ji ji chang,kandahaleu gugjegonghang,kandahara antararastriya vimanatala,kandaharu guo ji kong gang,kandhara antarrastriya vimanaksetra,mtar ahmd shah baba aldwly,mydan hwayy kndhar,кандагар,נמל התעופה הבינלאומי של קנדהאר,د افغانستان بینلمللی هوائی ډگر,د قندهار بینلمللی هوائی ډگر,د کندهار نړيوال هوايي ډګر,قندھار بین الاقوامی ہوائی اڈہ,مطار أحمد شاه بابا الدولي,ميدانٔ هوائئ كندهار,कंदहार आंतरराष्ट्रीय विमानतळ,कांधार अन्तर्राष्ट्रीय विमानक्षेत्र,ḏe afghānestān baynulmelali hawā’i dagaṟ,ḏe qanḏahāṟ baynulmelali hawā’i dagaṟ,カンダハール国際空港,坎大哈国际机场,칸다하르 국제공항',
    NOW(), NOW()), ('1454002', NULL, 'Hamid Karzai International Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.56585, 69.21233, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'hamid karzai international airport hamid karzai international airport afghanistan af aeroport kabul,aeroport international de kaboul,aeroporto internacional de cabul,aeroporto internacional de kabul,aeropuerto internacional de kabul,aéroport international de kaboul,bandar udara antarabangsa kabul,flughafen kabul,kbl,kabul,kabul international,kabul international airport,kabul internasjonale lufthavn,kabuli nemzetkoezi repueloter,kabuli nemzetközi repülőtér,kabulin kansainvaelinen lentoasema,kabulin kansainvälinen lentoasema,khojarawas,khojarawāš,khwaja rawash airport,lapangan terbang antarabangsa kabul,luchthaven kabul,oakb,port lotniczy kabul,san bay quoc te kabul,sân bay quốc tế kabul,ka bu er guo ji ji chang,kaburu guo ji kong gang,mydan hwayy kabl,кабул,د كابل هوايي ډګر,فرودگاه بین‌المللی کابل,میدانٔ هوائیٔ کابل,カーブル国際空港,喀布尔国际机场',
    NOW(), NOW()), ('1454052', NULL, 'Bagram', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.94639, 69.265, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bagram bagram afghanistan af aerodrom bagram,bagram,bagram air base,bagram airfield,logistics support area anaconda,oai,oaix,mydan hwayy bgram,میدانٔ هوائیٔ بگرام',
    NOW(), NOW()), ('1454265', NULL, 'Farah Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.36566, 62.16608, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'farah airport farah airport afghanistan af aeroportul farah,bandar udara farah,fah,farah airport,farah aeroporti,farahin lentoasema,farahs flygplats,ferah havalimani,ferah havalimanı,lapangan terbang farah,oafr,port lotniczy farah,aerodrome de farah,aérodrome de farah,fa la ji chang,fara kong gang,mtar frah,mydan hwayy frah,фурудгоҳи форо,مطار فراه,میدانٔ هوائئ فراه,ファラー空港,法拉機場',
    NOW(), NOW()), ('1454285', NULL, 'Bost', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.56005, 64.36487, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bost bost afghanistan af aerodrom bust,bst,bost,bost airfield,bost airport,lashkar gah,lashkargah airport,oabt,mydan hwayy bst,ميدانٔ هوائئ بست',
    NOW(), NOW()), ('1454312', NULL, 'Shindand Air Base', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.39133, 62.26098, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shindand air base shindand air base afghanistan af aehroport shindand,bandar udara shindand,base aerienne de shindand,base aérienne de shindand,lapangan terbang shindand,oah,oasd,shindand air base,shindands flygbas,vliegbasis shindand,mydan hwayy shyndnd,shen dan de kong jun ji de,shindando kong jun ji de,аэропорт шинданд,قاعدة شيندند الجوية,ميدانٔ هوائئ شيندند,シーンダンド空軍基地,申丹德空軍基地',
    NOW(), NOW()), ('1454453', NULL, 'Tapa Heliport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.74488, 62.59911, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tapa heliport tapa heliport afghanistan af tapa heliport',
    NOW(), NOW()), ('1454973', NULL, 'Herat International Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.2111, 62.22851, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'herat international airport herat international airport afghanistan af aerodrom gerat,hea,herat airfield,herāt airfield,oahr,mydan hwayy hrat,ميدانٔ هوائئ هرات',
    NOW(), NOW()), ('1455042', NULL, 'Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.26889, 65.87104, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar afghanistan af bandar,dolina bandar,bndr,بندر',
    NOW(), NOW()), ('1455057', NULL, 'Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.2293, 65.81134, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar afghanistan af bandar',
    NOW(), NOW()), ('1455222', NULL, 'Taygh-e Lūkah Surkh', 'Taygh-e Lukah Surkh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.43567, 65.58218, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taygh-e lūkah surkh taygh-e lukah surkh afghanistan af gora lukayi-surkh,taygh-e lukah surkh,taygh-e lūkah surkh,teghe loka-i-surkh,tigh-e lokeh-ye-sorkh,tēghe loka-i-suṟkh,tīgh-e lokeh-ye-sorkh,tygh lwkh srkh,تیغ لوکه سرخ',
    NOW(), NOW()), ('1458437', NULL, 'Lakah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.93227, 64.82597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lakah sang lakah sang afghanistan af gora lukasang,lakah sang,lokasang,lokehsang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1458583', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.62559, 64.89863, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af gora lukasang,lokasang,lokehsang,lukah sang,lwkh sng,لوکه سنگ',
    NOW(), NOW()), ('1458670', NULL, 'Kōh-e Lukah Sang', 'Koh-e Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.58687, 64.54621, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e lukah sang koh-e lukah sang afghanistan af gora lukasang,koh-e lukah sang,kohe lakasang,kohe lokasang,kuh-e lokehsang,kōh-e lukah sang,kūh-e lokehsang,kwh lkh sng,کوه لکه سنگ',
    NOW(), NOW()), ('1459568', NULL, 'Lūkah-ye Lār Bandī', 'Lukah-ye Lar Bandi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.93552, 63.20593, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye lār bandī lukah-ye lar bandi afghanistan af gora lukayi-larbandi,lowkah-ye-larbandi,lowkah-ye-lārbandī,luka-i-larbandi,lukah-ye lar bandi,lūka-i-lāṟbanḏi,lūkah-ye lār bandī,لوکۀ لار بندی',
    NOW(), NOW()), ('1459725', NULL, 'Kōtal-e Lukah Sang', 'Kotal-e Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.129, 64.45729, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōtal-e lukah sang kotal-e lukah sang afghanistan af kotal-e lukah sang,kotale lokasang,kowtal-e lokehsang,kōtal-e lukah sang,kōtale lokasang,kwtl lkh sng,کوتل لکه سنگ',
    NOW(), NOW()), ('1459728', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.1059, 64.42534, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokehsang,lukah sang,lukasang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1459853', NULL, 'Pushtah-ye Lakah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.3969, 64.96496, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pushtah-ye lakah sang pushtah-ye lakah sang afghanistan af gora lukasang,poshteh-ye lokehsang,pushtah-ye lakah sang,pusta lokasang,pušta lokasang,پشتۀ لکه سنگ',
    NOW(), NOW()), ('1460097', NULL, 'Lūkah Mazār', 'Lukah Mazar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.29604, 64.65189, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah mazār lukah mazar afghanistan af gora lukamazar,lukah mazar,lukamazar,lukehmazar,lūkah mazār,lūkamazāṟ,lūkehmazār,lwkh mzar,لوکه مزار',
    NOW(), NOW()), ('1460116', NULL, 'Lukah Kōhak', 'Lukah Kohak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.00053, 64.96597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah kōhak lukah kohak afghanistan af lokakohak,lokakōhak,lokehkuhak,lokehkūhak,lukah kohak,lukah kōhak,lkh kwhk,لکه کوهک',
    NOW(), NOW()), ('1460204', NULL, 'Chahār Burjah', 'Chahar Burjah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.3355, 67.90468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chahār burjah chahar burjah afghanistan af caharburja,chahar burjah,chaharborjeh,chahār burjah,chahārborjeh,chakharburdzha,chhar brjh,čahārburja,چهار برجه',
    NOW(), NOW()), ('1460376', NULL, 'Kōtal-e Lukah Sang', 'Kotal-e Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.24372, 67.70239, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōtal-e lukah sang kotal-e lukah sang afghanistan af kotal-e lukah sang,kotale lokasang,kowtal-e lokehsang,kōtal-e lukah sang,kōtale lokasang,pereval lukasang,kwtl lkh sng,کوتل لکه سنگ',
    NOW(), NOW()), ('1460826', NULL, 'Lukah-ye Yakabayd', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.30949, 64.40849, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye yakabayd lukah-ye yakabayd afghanistan af gora lukayi-yakabed,loka-i-yakabed,loka-i-yakabēḏ,lokeh-ye yekehbid,lokeh-ye yekehbīd,lukah-ye yakabayd,لکۀ یکبید',
    NOW(), NOW()), ('1461462', NULL, 'Lokahhā-ye Surkh', 'Lokahha-ye Surkh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.34829, 65.00067, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lokahhā-ye surkh lokahha-ye surkh afghanistan af gora lukakhaji-surkh,gora lukakhayi-surkh,lokaha-i-surkh,lokaha-ye sorkh,lokahha-ye surkh,lokahhā-ye surkh,lokahā-i-suṟkh,lokahā-ye sorkh,lokehha-ye sorkh,lokehhā-ye sorkh,lkh hay srkh,гора лукахайи-сурх,لكه های سرخ,لکه های سرخ',
    NOW(), NOW()), ('1464912', NULL, 'Chownī Nowbahār', 'Chowni Nowbahar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.65978, 69.37954, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chownī nowbahār chowni nowbahar afghanistan af cawni nawbahar,chavni nowbahar,chavnī nowbahār,chowni nowbahar,chownī nowbahār,chwny nwbhar,čawnī nawbahār,چونی نوبهار',
    NOW(), NOW()), ('1465312', NULL, 'Bōlōkah', 'Bolokah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.00763, 69.58873, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bōlōkah bolokah afghanistan af boloka,bolokah,bulukah,bōlōka,bōlōkah,būlūkah,bwlwkh,بولوکه',
    NOW(), NOW()), ('1467687', NULL, 'Daryā-ye Tāluqān', 'Darya-ye Taluqan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.7324, 69.20495, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'daryā-ye tāluqān darya-ye taluqan afghanistan af darrah-e taloqan,darrah-e tāloqān,darya-i-taloqan,darya-i-taluqan,darya-i-tāloqān,darya-ye taloqan,darya-ye taluqan,daryā-ye tāloqān,daryā-ye tāluqān,talukan,dryay talqan,талукан,درۀ تالقان,دریای تالقان,ḏaṟyā-i-tāluqān',
    NOW(), NOW()), ('1468146', NULL, 'Kōh-e Bandar-e ‘Alī Qōl', 'Koh-e Bandar-e ''Ali Qol',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.37506, 70.24026, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e bandar-e ‘alī qōl koh-e bandar-e ''ali qol afghanistan af koh-e bandar-e `ali qol,koh-i-bandar-i-`ali qul,koh-i-banḏaṟ-i-‘ali qūl,kuh-e bandar-e `ali qul,kōh-e bandar-e ‘alī qōl,kūh-e bandar-e ‘alī qūl,کوه بندر علی قول',
    NOW(), NOW()), ('1469016', NULL, 'Kōh-e Fōrghāmanōl', 'Koh-e Forghamanol',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.16726, 70.16087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e fōrghāmanōl koh-e forghamanol afghanistan af koh-e forghamanol,kohe forghamanol,kohe fōrghamanōl,kuh-e furghamanul,kōh-e fōrghāmanōl,kūh-e fūrghamanūl,kwh fwrghamnwl,کوه فورغامنول',
    NOW(), NOW()), ('1470215', NULL, 'Lūkah-ye Sangābak', 'Lukah-ye Sangabak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.9671, 64.23733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye sangābak lukah-ye sangabak afghanistan af luka-i-sangabak,lukah-e sangabak,lukah-ye sangabak,lūka-i-sangābak,lūkah-e sangābak,lūkah-ye sangābak,لوکۀ سنگابک',
    NOW(), NOW()), ('1470531', NULL, 'Lūkah-ye Safēd', 'Lukah-ye Safed',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.84568, 64.11902, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye safēd lukah-ye safed afghanistan af luka-i-safed,lukah-e sefid,lukah-ye safayd,lukah-ye safed,lūka-i-safēḏ,lūkah-e sefīd,lūkah-ye safayd,lūkah-ye safēd,لوکۀ سفېد',
    NOW(), NOW()), ('1470653', NULL, 'Sar-e Kōh-e Bandarghānī', 'Sar-e Koh-e Bandarghani',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.57374, 64.03128, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sar-e kōh-e bandarghānī sar-e koh-e bandarghani afghanistan af sar-e koh-e bandarghani,sar-e kuh-e bandarghani,sar-e kōh-e bandarghānī,sar-e kūh-e bandarghānī,sare kohe bandarghani,saṟe kohe banḏaṟghāni,sr kwh bndrghany,سر کوه بندرغانی',
    NOW(), NOW()), ('1470664', NULL, 'Lukah Band', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.67013, 64.20363, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah band lukah band afghanistan af lokaband,lokabanḏ,lukah band,lkh bnd,لکه بند',
    NOW(), NOW()), ('1470852', NULL, 'Lūkah-ye Tīzak', 'Lukah-ye Tizak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.63454, 65.30514, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye tīzak lukah-ye tizak afghanistan af luka-i-tizak,lukah-ye tizak,lūka-i-tizak,lūkah-ye tizak,lūkah-ye tīzak,لوکۀ تیزک',
    NOW(), NOW()), ('1470853', NULL, 'Lūkah-ye Būchah', 'Lukah-ye Buchah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.62521, 65.28194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye būchah lukah-ye buchah afghanistan af luka-i-buca,lukah-ye buchah,lūka-i-būča,lūkah-ye būchah,لوکۀ بوچه',
    NOW(), NOW()), ('1470872', NULL, 'Lūkah-ye Sartarkīdah', 'Lukah-ye Sartarkidah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.57907, 65.36021, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye sartarkīdah lukah-ye sartarkidah afghanistan af luka-i-sartarkida,lukah-ye sartarakideh,lukah-ye sartarkidah,lūka-i-saṟtaṟkiḏa,lūkah-ye sartarakīdeh,lūkah-ye sartarkīdah,لوکۀ سرترکیده',
    NOW(), NOW()), ('1470895', NULL, 'Lukah-ye Zākhān', 'Lukah-ye Zakhan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.68877, 64.41646, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye zākhān lukah-ye zakhan afghanistan af loka-i-zakhan,loka-i-zākhān,lokah-ye zakhan,lokah-ye zākhān,lukah-ye zakhan,lukah-ye zākhān,لکۀ زاخان',
    NOW(), NOW()), ('1470939', NULL, 'Kōh-e Pas-e Lukah', 'Koh-e Pas-e Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.5163, 64.38271, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e pas-e lukah koh-e pas-e lukah afghanistan af koh-e pas-e lukah,kohe pase loka,kuh-e pase lokah,kōh-e pas-e lukah,kūh-e pase lokah,kwh ps lkh,کوه پس لکه',
    NOW(), NOW()), ('1471008', NULL, 'Kōh-e Bandarak', 'Koh-e Bandarak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.4933, 64.23559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e bandarak koh-e bandarak afghanistan af gora bandarak,koh-e bandarak,kohe bandarak,kohe bānḏaṟak,kuh-e bandarak,kōh-e bandarak,kūh-e bandarak,kwh bandrk,کوه باندرک',
    NOW(), NOW()), ('1471279', NULL, 'Lukah-ye Dashtak', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.91692, 65.40155, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye dashtak lukah-ye dashtak afghanistan af loka-i-dastak,loka-i-ḏastak,lokah-ye dashtak,lukah-ye dashtak,لکۀ دشتک',
    NOW(), NOW()), ('1471281', NULL, 'Lukah-ye Bād', 'Lukah-ye Bad',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.9373, 65.35717, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye bād lukah-ye bad afghanistan af loka-i-bad,loka-i-bāḏ,lokah-ye bad,lokah-ye bād,lukah-ye bad,lukah-ye bād,لکۀ باد',
    NOW(), NOW()), ('1471500', NULL, 'Kharī Lūkasanghā', 'Khari Lukasangha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.08422, 63.53764, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kharī lūkasanghā khari lukasangha afghanistan af',
    NOW(), NOW()), ('1472241', NULL, 'Rōd-e ‘Alī Manşūr', 'Rod-e `Ali Mansur',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.45033, 62.20392, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rōd-e ‘alī manşūr rod-e `ali mansur afghanistan af alimansur,khusk,khušk,rod-e `ali mansur,rod-i-`ali mansur,rud-e khushk,rud-e `ali mansur,rōd-e ‘alī manşūr,rūd-e khushk,rūd-e ‘alī manşūr,رود علی منصور,رودٔ علی منصور,ṟōḏ-i-‘alī manşūr',
    NOW(), NOW()), ('1472337', NULL, 'Ghêlō Kazan', 'Ghelo Kazan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.98951, 69.57294, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ghêlō kazan ghelo kazan afghanistan af ghelo kazan,ghilo kazan,ghilō kazan,ghêlō kazan,gora gelukazan,ghlw kzn,ghylw kzn,غلو کزن,غيلو كزن',
    NOW(), NOW()), ('1472938', NULL, 'Alō Kêlay', 'Alo Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.68365, 69.8186, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alō kêlay alo kelay afghanistan af alo kalay,alo kelay,alukalay,alō kêlay,alw kly,الو کلی,قريۀ الو',
    NOW(), NOW()), ('1473611', NULL, 'Bandar Khūlah', 'Bandar Khulah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.06889, 70.76447, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar khūlah bandar khulah afghanistan af bandar kholeh,bandar khulah,bandar khūlah,bandarkhula,bndr khwlh,dhan bndr,بندر خوله,دهانٔ بندر',
    NOW(), NOW()), ('1473819', NULL, 'Bāndaṟ Khwaṟ', 'Bandar Khwar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.17521, 70.79031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bāndaṟ khwaṟ bandar khwar afghanistan af bandar khwar,bandarkhvar,bāndaṟ khwaṟ,باندړ خوړ,شيلۀ بندر',
    NOW(), NOW()), ('1474543', NULL, 'Shāmangal', 'Shamangal',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.6348, 70.23972, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shāmangal shamangal afghanistan af samangal,shah mangal,shamangal,shamangal'',shamangal’,shāmangal,shamngl,shh mngl,šāmangal,شامنگل,شه منگل',
    NOW(), NOW()), ('1475348', NULL, 'Limangal Khwaṟ', 'Limangal Khwar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.26864, 71.10094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'limangal khwaṟ limangal khwar afghanistan af lemangal khwar,lemangal khwaṟ,limangal khwar,limangal khwaṟ,limangal''khvar,limangal’khvar,شيلۀ لمنگل,لمنگل خوړ',
    NOW(), NOW()), ('1476074', NULL, 'Lūkasang', 'Lukasang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.56994, 65.95407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkasang lukasang afghanistan af lukasang,lūkasang,lwksng,لوکسنگ',
    NOW(), NOW()), ('1476075', NULL, 'Jar-e Lūkasang', 'Jar-e Lukasang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.57863, 65.93144, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jar-e lūkasang jar-e lukasang afghanistan af jar-e lokah ssang,jar-e lukasang,jar-e lōkah ssang,jar-e lūkasang,jr lwkh sng,jr lwksng,جر لوکسنگ,جر لوکه سنگ',
    NOW(), NOW()), ('1476093', NULL, 'Sar-e Lūkasang', 'Sar-e Lukasang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.51242, 65.96381, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sar-e lūkasang sar-e lukasang afghanistan af sar-e lokah sang,sar-e lukasang,sar-e lōkah sang,sar-e lūkasang,sr lwkh sng,sr lwksng,سر لوکسنگ,سر لوکه سنگ',
    NOW(), NOW()), ('1480546', NULL, 'Pōrtah Kārēz', 'Portah Karez',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.15174, 67.94087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah kārēz portah karez afghanistan af kyariz porta,porta karez,porta kārēz,portah karez,portah kariz,portah kārīz,pōrtah kārēz,پورته کارېز',
    NOW(), NOW()), ('6252369', NULL, 'Kunduz Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.66518, 68.9109, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kunduz airport kunduz airport afghanistan af aehrodrom kunduz,konduz airport,kunduz airport,oauz,und,mydan hwayy kndz,аэродром кундуз,ميدانٔ هوائئ كندز',
    NOW(), NOW()), ('6300000', NULL, 'Fayzabad Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.12113, 70.51791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fayzabad airport fayzabad airport afghanistan af aeroport de fayzabad,aeroportul fayzabad,aeropuerto de fayzabad,aeropuertu de fayzabad,aéroport de fayzabad,bandar udara faizabad,fbd,faizabadin lentoasema,fayzabad airport,fayzobod aeroporti,feizabadas lidosta,feizābādas lidosta,feyzabad havaalani,feyzabad havaalanı,feyzabads flygplats,lapangan terbang faizabad,letiste fajzabad,letiště fajzábád,oafz,port lotniczy fajzabad,fa zha ba de ji chang,faizabado kong gang,phayajabada bimanabandara,фурудгоҳи фийз‌обод,فرودگاه فیض‌آباد,ফয়জাবাদ বিমানবন্দর,ファイザーバード空港,法扎巴德機場',
    NOW(), NOW()), ('7428348', NULL, 'Dê Kêlay Māndêh', 'De Kelay Mandeh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.5872, 65.31187, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dê kêlay māndêh de kelay mandeh afghanistan af de kelay mandeh,de keli mandah,de keli mandeh,de keli māndah,dê kêlay māndêh,kelimandekh,d kly mandh,د کلی مانده,ḏe keli mānḏeh',
    NOW(), NOW()), ('7489621', NULL, 'Lukah-ye Safēd', 'Lukah-ye Safed',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.00442, 63.86387, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye safēd lukah-ye safed afghanistan af lukah-ye safayd,lukah-ye safed,lukah-ye safēd,لکۀ سفېد',
    NOW(), NOW()), ('7501450', NULL, 'Zaranj Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.1037, 61.9365, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'zaranj airport zaranj airport afghanistan af forudgah jakhsur,forūdgāh jakhsūr,oazj,zaj,zaranj airport,frwdgah jkhswr,فرودگاه جخسور',
    NOW(), NOW()), ('7537180', NULL, 'Lukah', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.45727, 65.35253, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah lukah afghanistan af lokah,lukah,lōkah,lkh,lwkh,لوکه,لکه',
    NOW(), NOW()), ('7542380', NULL, 'Khar-e Lūkah Sang Hā', 'Khar-e Lukah Sang Ha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.08038, 63.52762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'khar-e lūkah sang hā khar-e lukah sang ha afghanistan af khar-e lukah sang ha,khar-e lūkah sang hā,khr lwkh sng ha,خر لوکه سنگ ها',
    NOW(), NOW()), ('7563973', NULL, 'Marīnā', 'Marina',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.62181, 70.35553, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marīnā marina afghanistan af marina,marīnā,mryna,مرینا',
    NOW(), NOW()), ('7668387', NULL, 'Bamiyan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.8086, 67.8182, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bamiyan airport bamiyan airport afghanistan af bin,oabn',
    NOW(), NOW()), ('7668388', NULL, 'Chakcharan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.526, 65.27, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chakcharan airport chakcharan airport afghanistan af ccn,oacc',
    NOW(), NOW()), ('7668389', NULL, 'Qala i Naw Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.98493, 63.11671, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'qala i naw airport qala i naw airport afghanistan af aeroport de qala i naw,aeroportul qala i naw,aéroport de qala i naw,bandar udara qala-i-naw,kale i novas lidosta,kale-i nev havalimani,kale-i nev havalimanı,lqn,lapangan terbang qala-i-naw,oaqn,port lotniczy kala-je nau,qal''eh-ye nawin lentoasema,qala i naw airport,qala-i-naw airport,qaleh-ye nows flygplats,frwdgah qlʿh nw  afghanstan,karaenau kong gang,nao bao ji chang,фурудгоҳи қалъа ну,فرودگاه قلعه نو، افغانستان,カラエナウ空港,瑙堡机场',
    NOW(), NOW()), ('7730737', NULL, 'Darwaz Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    38.4611, 70.8825, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'darwaz airport darwaz airport afghanistan af aeroportul darwaz,daz,darvaz havalimani,darvaz havalimanı,darwaz airport,darwaz flygplats,darwaz ji chang,darwaz kong gang,darwaz機場,darwaz空港,letiste darwaz,letiště darwáz,oadz,port lotniczy darwaz,aerodrome de darwaz,aérodrome de darwaz,frwdgah drwaz,mtar drwaz,فرودگاه درواز,مطار درواز',
    NOW(), NOW()), ('7730738', NULL, 'Khwahan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.8902, 70.2039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'khwahan airport khwahan airport afghanistan af aeroportul khwahan,havahan havalimani,havahan havalimanı,kwh,khwahan airport,khwahan kong gang,khwahans flygplats,khwahan空港,letiste chwahan,letiště chwáhán,oahn,port lotniczy chwahan,aerodrome de khwahan,aérodrome de khwahan,frwdgah khwahan,kha''oyahana bimanabandara,mtar khwhan,فرودگاه خواهان,مطار خوهان,খওয়াহান বিমানবন্দর',
    NOW(), NOW()), ('7730739', NULL, 'Sheghnan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.56667, 71.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sheghnan airport sheghnan airport afghanistan af aeroportul sheghnan,letiste sugnan,letiště šugnan,oasn,port lotniczy szighnan,sga,sheghnan airport,sheghnan kong gang,sheghnan空港,shighnan airport,shighnans flygplats,siganan havalimani,aerodrome de sheghnan,aérodrome de sheghnan,frwdgah shqnn,mtar shyghnan,seghanana bimanabandara,xie ge na mu ji chang,şiganan havalimanı,фурудгоҳи шқнн,فرودگاه شقنن,مطار شيغنان,শেঘনান বিমানবন্দর,謝格納姆機場,谢格纳姆机场',
    NOW(), NOW()), ('8298749', NULL, 'Taloqan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.77057, 69.53009, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taloqan airport taloqan airport afghanistan af oatq,tqn,taloqan airport',
    NOW(), NOW()), ('8355623', NULL, 'Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.29203, 61.90887, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar bandar afghanistan af bandar,bndr,بندر',
    NOW(), NOW()), ('8531896', NULL, 'Sardeh Band Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.32114, 68.63682, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sardeh band airport sardeh band airport afghanistan af aeroportul sardeh band,band e sardeh dam airpor,oads,port lotniczy sardeh band,sbf,sardeh band airport,sardeh band havalimani,sardeh band havalimanı,sardeh bands flygplats,frwdgah srdh‌bnd,mtar sardyh band,sha dan ban de ji chang,فرودگاه سرده‌بند,مطار سارديه باند,サルデ・バンド空港,沙丹班德机场,沙丹班德機場',
    NOW(), NOW()), ('8593983', NULL, 'Ḩāmund Band', 'Hamund Band',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.51994, 66.83702, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ḩāmund band hamund band afghanistan af hamund band,hamnd bnd,حامند بند,ḩāmund band',
    NOW(), NOW()), ('8617813', NULL, 'Zaranj Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.9722, 61.86612, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'zaranj airport zaranj airport afghanistan af oazj,zaj,zaranj airport',
    NOW(), NOW()), ('9031064', NULL, 'Razer Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.01714, 70.76071, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'razer airport razer airport afghanistan af kur,oarz,razer airport',
    NOW(), NOW()), ('9034570', NULL, 'Taywara Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.54206, 64.42559, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taywara airport taywara airport afghanistan af oatw',
    NOW(), NOW()), ('9034737', NULL, 'Yawan Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.56368, 70.44475, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yawan airport yawan airport afghanistan af aeroportul yawan,letiste jawan,letiště jawán,oayw,yawan airport,yawan kong gang,yawans flygplats,yawan空港,frwdgah yawan,mtar yawan,فرودگاه یاوان,مطار ياوان',
    NOW(), NOW()), ('9035756', NULL, 'Yangi Qaleh Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.45636, 69.64126, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yangi qaleh airport yangi qaleh airport afghanistan af aeroportul yangi qaleh,oayq,yangi qalas flygplats,yangi qaleh airport,mtar yanjy kala,فرودگاه ینگی‌قلعه,مطار يانجي كالا,イアンギー・キャラー空港',
    NOW(), NOW()), ('9166170', NULL, 'Kunduz Terminal', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.66694, 68.91139, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'kunduz terminal kunduz terminal afghanistan af',
    NOW(), NOW()), ('9166353', NULL, 'Ministry of Transportation', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.53236, 69.1887, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ministry of transportation ministry of transportation afghanistan af',
    NOW(), NOW()), ('9166375', NULL, 'Ministry of Transportation and Aviation', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.53236, 69.18868, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ministry of transportation and aviation ministry of transportation and aviation afghanistan af',
    NOW(), NOW()), ('9166487', NULL, 'Nili Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.73608, 66.15768, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nili airport nili airport afghanistan af',
    NOW(), NOW()), ('9166507', NULL, 'Muqur Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.87665, 67.84527, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'muqur airport muqur airport afghanistan af muqur airport,muqur airport,muqurs flygplats,oamk,frwdgah mqr,maka kong gang,mtar mqwr,فرودگاه مقر,مطار مقور,マカー空港',
    NOW(), NOW()), ('11473861', NULL, 'Khal Khan Heliport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.5496, 71.34042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'khal khan heliport khal khan heliport afghanistan af khal khan heliport',
    NOW(), NOW()), ('3575954', NULL, 'V. C. Bird International Airport', NULL,
    NULL, 'AG', 'Antigua and Barbuda', NULL, NULL,
    17.13675, -61.79267, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'v. c. bird international airport v. c. bird international airport antigua and barbuda ag anu,antigua airport,antigua flygplats,flughafen vc bird international,lapangan terbang antarabangsa v c bird,port lotniczy vc bird,tapa,v. c. bird international airport,vcbado guo ji kong gang,vcバード国際空港,wei er bo de guo ji ji chang,維爾伯德國際機場',
    NOW(), NOW());