INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('11525645', NULL, 'Tubarao', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.28697, -40.24397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tubarao tubarao brazil br porto de tubarao,porto de tubarão,tubarao',
    NOW(), NOW()), ('11525646', NULL, 'Rio De Janeiro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.90243, -43.17236, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rio de janeiro rio de janeiro brazil br rio de janeiro',
    NOW(), NOW()), ('11525647', NULL, 'Niterói', 'Niteroi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.88192, -43.11647, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'niterói niteroi brazil br niteroi,niterói',
    NOW(), NOW()), ('11525648', NULL, 'Paranaguá', 'Paranagua',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.50274, -48.51376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paranaguá paranagua brazil br paranagua,paranaguá',
    NOW(), NOW()), ('11525649', NULL, 'Sao Francisco', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.25, -48.63333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sao francisco sao francisco brazil br sao francisco',
    NOW(), NOW()), ('11608472', NULL, 'Santana do Livramento Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.836, -55.626, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santana do livramento airport santana do livramento airport brazil br lvb,santana do livramento',
    NOW(), NOW()), ('11612611', NULL, 'Antonio Guerreiro Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.10918, -44.65127, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'antonio guerreiro airport antonio guerreiro airport brazil br antonio guerreiro airport,gms,snyw',
    NOW(), NOW()), ('11778247', NULL, 'Floating Dock Affonso Penna (historical)', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7861, -43.14633, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'floating dock affonso penna (historical) floating dock affonso penna (historical) brazil br',
    NOW(), NOW()), ('11789386', NULL, 'Ilha do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.09338, -45.7058, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilha do porto ilha do porto brazil br',
    NOW(), NOW()), ('11821257', NULL, 'Rio de Janeiro Harbour', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8957, -43.15239, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'rio de janeiro harbour rio de janeiro harbour brazil br',
    NOW(), NOW()), ('11952683', NULL, 'Portal das Artes', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.21771, -44.73378, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal das artes portal das artes brazil br',
    NOW(), NOW()), ('11959902', NULL, 'Porto do Itinga', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.27803, -48.69429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto do itinga porto do itinga brazil br porto do itinga',
    NOW(), NOW()), ('11960380', NULL, 'Ribeirão do Porto Franco', 'Ribeirao do Porto Franco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.19912, -49.0746, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ribeirão do porto franco ribeirao do porto franco brazil br ribeirao do porto franco,ribeirão do porto franco',
    NOW(), NOW()), ('11960866', NULL, 'Córrego do Porto', 'Corrego do Porto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.26736, -52.37921, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego do porto corrego do porto brazil br corrego do porto,córrego do porto',
    NOW(), NOW()), ('11960947', NULL, 'Fazenda Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.89718, -52.36549, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porto fazenda porto brazil br fazenda porto',
    NOW(), NOW()), ('11969532', NULL, 'Fazenda Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9894, -47.46014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda portela fazenda portela brazil br fazenda portela',
    NOW(), NOW()), ('11970201', NULL, 'Portão Pesado', 'Portao Pesado',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8296, -47.31351, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portão pesado portao pesado brazil br portao pesado,portão pesado',
    NOW(), NOW()), ('11979417', NULL, 'Inner Harbour (historical)', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.04919, -34.86541, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'inner harbour (historical) inner harbour (historical) brazil br',
    NOW(), NOW()), ('12024138', NULL, 'Porto do Saco', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9097, -42.52212, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto do saco porto do saco brazil br porto do saco',
    NOW(), NOW()), ('12024365', NULL, 'Porto Pacheco', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.53835, -42.16407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto pacheco porto pacheco brazil br porto pacheco',
    NOW(), NOW()), ('12024685', NULL, 'Serra dos Portelas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.80937, -42.55667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra dos portelas serra dos portelas brazil br serra dos portelas',
    NOW(), NOW()), ('12024698', NULL, 'Fazenda dos Portelas', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.80168, -42.57289, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda dos portelas fazenda dos portelas brazil br fazenda dos portelas',
    NOW(), NOW()), ('12024720', NULL, 'Porto Taboado', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.52611, -42.67467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto taboado porto taboado brazil br porto taboado',
    NOW(), NOW()), ('12025132', NULL, 'Serra dos Portões', 'Serra dos Portoes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.1788, -43.0776, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra dos portões serra dos portoes brazil br serra dos portoes,serra dos portões',
    NOW(), NOW()), ('12032521', NULL, 'Portuaria', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.88095, -43.21729, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portuaria portuaria brazil br',
    NOW(), NOW()), ('12070314', NULL, 'Metropolitana De Porto Alegre', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.35152, -51.6837, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'metropolitana de porto alegre metropolitana de porto alegre brazil br',
    NOW(), NOW()), ('12105153', NULL, 'Água Boa Airport', 'Agua Boa Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.02531, -52.15432, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'água boa airport agua boa airport brazil br aeroport d''agua boa,aeroporto de agua boa,aeroporto de água boa,agua boa airport,aéroport d''água boa,ggb,swhp,água boa airport',
    NOW(), NOW()), ('12105154', NULL, 'Almeirim Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.48227, -52.5805, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'almeirim airport almeirim airport brazil br aeroporto de almeirim,almeirim airport,flughafen almeirim,ggf,snya',
    NOW(), NOW()), ('12105156', NULL, 'Gastão Mesquita Airport', 'Gastao Mesquita Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.68996, -52.64142, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gastão mesquita airport gastao mesquita airport brazil br aeroporto regional engenheiro gastao de mesquita filho,aeroporto regional engenheiro gastão de mesquita filho,cianorte airport,ggh,gastao mesquita airport,gastão mesquita airport,ssct',
    NOW(), NOW()), ('12108348', NULL, 'Praia do Porto da Barra', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.0029, -38.53293, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'praia do porto da barra praia do porto da barra brazil br praia do porto da barra',
    NOW(), NOW()), ('12108747', NULL, 'Hospital Português', 'Hospital Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.00278, -38.52443, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hospital português hospital portugues brazil br hospital portugues,hospital português',
    NOW(), NOW()), ('12108813', NULL, 'Porto Seco Pirajá', 'Porto Seco Piraja',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.90812, -38.45278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto seco pirajá porto seco piraja brazil br porto seco piraja,porto seco pirajá',
    NOW(), NOW()), ('12109129', NULL, 'Ginásio Poliesportivo Nélio Dias', 'Ginasio Poliesportivo Nelio Dias',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.73322, -35.25393, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ginásio poliesportivo nélio dias ginasio poliesportivo nelio dias brazil br ginasio poliesportivo nelio dias,ginásio poliesportivo nélio dias',
    NOW(), NOW()), ('12109447', NULL, 'Complexo Esportivo Alvamar Furtado de Mendonça', 'Complexo Esportivo Alvamar Furtado de Mendonca',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.76922, -35.1959, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'complexo esportivo alvamar furtado de mendonça complexo esportivo alvamar furtado de mendonca brazil br complexo esportivo alvamar furtado de mendonca,complexo esportivo alvamar furtado de mendonça',
    NOW(), NOW()), ('12115786', NULL, 'Córrego das Porteiras', 'Corrego das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.91012, -47.36508, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego das porteiras corrego das porteiras brazil br corrego das porteiras,córrego das porteiras',
    NOW(), NOW()), ('12116033', NULL, 'Córrego Porteiras', 'Corrego Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.30852, -47.66814, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteiras corrego porteiras brazil br corrego porteiras,córrego porteiras',
    NOW(), NOW()), ('12117478', NULL, 'Fazenda do Ribeirão das Porteiras', 'Fazenda do Ribeirao das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.01512, -50.01183, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda do ribeirão das porteiras fazenda do ribeirao das porteiras brazil br fazenda do ribeirao das porteiras,fazenda do ribeirão das porteiras',
    NOW(), NOW()), ('12117605', NULL, 'Fazenda Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.42608, -49.74557, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda marina fazenda marina brazil br fazenda marina',
    NOW(), NOW()), ('12117710', NULL, 'Fazenda da Porteira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.55284, -50.4863, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda da porteira fazenda da porteira brazil br fazenda da porteira',
    NOW(), NOW()), ('12117970', NULL, 'Córrego do Português', 'Corrego do Portugues',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.73184, -49.73922, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego do português corrego do portugues brazil br corrego do portugues,córrego do português',
    NOW(), NOW()), ('12120525', NULL, 'Córrego das Porteiras', 'Corrego das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.37906, -50.25475, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego das porteiras corrego das porteiras brazil br corrego das porteiras,córrego das porteiras',
    NOW(), NOW()), ('12125773', NULL, 'Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.60959, -56.11077, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto porto brazil br do porto,porto',
    NOW(), NOW()), ('12125785', NULL, 'Bela Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.6334, -56.07111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bela marina bela marina brazil br bela marina',
    NOW(), NOW()), ('12130470', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.49759, -47.72757, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12130575', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.97275, -47.51837, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12130667', NULL, 'Riacho das Porteiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.47334, -46.53953, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'riacho das porteiras riacho das porteiras brazil br riacho das porteiras',
    NOW(), NOW()), ('12131982', NULL, 'Fazenda Portão Vermelho', 'Fazenda Portao Vermelho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.25859, -52.18397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda portão vermelho fazenda portao vermelho brazil br fazenda portao vermelho,fazenda portão vermelho',
    NOW(), NOW()), ('12136248', NULL, 'Porto Maria Teresa', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.61959, -52.05762, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto maria teresa porto maria teresa brazil br porto maria teresa',
    NOW(), NOW()), ('12137486', NULL, 'Porto da Madeira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.00769, -34.88923, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto da madeira porto da madeira brazil br porto da madeira',
    NOW(), NOW()), ('12138948', NULL, 'Córrego das Porteiras', 'Corrego das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.39549, -49.88858, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego das porteiras corrego das porteiras brazil br corrego das porteiras,córrego das porteiras',
    NOW(), NOW()), ('12138958', NULL, 'Córrego da Porteira', 'Corrego da Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.75624, -50.15028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego da porteira corrego da porteira brazil br corrego da porteira,corrego do porteira,córrego da porteira,córrego do porteira',
    NOW(), NOW()), ('12139143', NULL, 'Córrego da Porteira', 'Corrego da Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.4909, -49.24988, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego da porteira corrego da porteira brazil br corrego da porteira,córrego da porteira',
    NOW(), NOW()), ('12139168', NULL, 'Córrego da Porteira', 'Corrego da Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.69127, -49.42842, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego da porteira corrego da porteira brazil br corrego da porteira,córrego da porteira',
    NOW(), NOW()), ('12139308', NULL, 'Fazenda Porteira', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.65055, -48.82281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda porteira fazenda porteira brazil br fazenda porteira',
    NOW(), NOW()), ('12139358', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.32868, -48.838, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12139417', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.63921, -48.83282, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12139482', NULL, 'Fazenda das Porteiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.2443, -48.64464, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda das porteiras fazenda das porteiras brazil br fazenda das porteiras',
    NOW(), NOW()), ('12139580', NULL, 'Córrego das Porteiras', 'Corrego das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.22726, -48.63426, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego das porteiras corrego das porteiras brazil br corrego das porteiras,córrego das porteiras',
    NOW(), NOW()), ('12139588', NULL, 'Lagoa da Porta', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.23985, -48.40812, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lagoa da porta lagoa da porta brazil br lagoa da porta',
    NOW(), NOW()), ('12139596', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.53698, -48.44679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12139628', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.77833, -48.81253, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12139631', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.73271, -48.54619, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12140443', NULL, 'Córrego Porteira', 'Corrego Porteira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.27376, -48.26758, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego porteira corrego porteira brazil br corrego porteira,córrego porteira',
    NOW(), NOW()), ('12140446', NULL, 'Córrego das Porteiras', 'Corrego das Porteiras',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.23988, -48.09011, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'córrego das porteiras corrego das porteiras brazil br corrego das porteiras,córrego das porteiras',
    NOW(), NOW()), ('12140789', NULL, 'Riacho da Porta', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.04056, -47.75695, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'riacho da porta riacho da porta brazil br riacho da porta',
    NOW(), NOW()), ('12179537', NULL, 'Porto Rico', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.81791, -43.85882, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto rico porto rico brazil br porto rico',
    NOW(), NOW()), ('12181805', NULL, 'Fazenda das Porteiras', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.59074, -44.06691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda das porteiras fazenda das porteiras brazil br fazenda das porteiras',
    NOW(), NOW()), ('12196081', NULL, 'Porto do Acu', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.86034, -41.02083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto do acu porto do acu brazil br',
    NOW(), NOW()), ('12196097', NULL, 'Porto Alumar', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.67904, -44.35991, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto alumar porto alumar brazil br',
    NOW(), NOW()), ('12229389', NULL, 'Ginásio de Esportes Tesourinha', 'Ginasio de Esportes Tesourinha',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -30.04553, -51.21982, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ginásio de esportes tesourinha ginasio de esportes tesourinha brazil br ginasio de esportes tesourinha,ginásio de esportes tesourinha',
    NOW(), NOW()), ('12238280', NULL, 'Angra dos Reis Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.97539, -44.30742, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'angra dos reis airport angra dos reis airport brazil br gdr,sdag',
    NOW(), NOW()), ('12238281', NULL, 'Paraty Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.22404, -44.72465, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paraty airport paraty airport brazil br jpy,sdtk',
    NOW(), NOW()), ('12377069', NULL, 'Colégio Visconde de Porto Seguro', 'Colegio Visconde de Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.60561, -46.71933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colégio visconde de porto seguro colegio visconde de porto seguro brazil br colegio visconde de porto seguro,colégio visconde de porto seguro',
    NOW(), NOW()), ('12377224', NULL, 'Jardim Portinari', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.70624, -46.59676, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jardim portinari jardim portinari brazil br jardim portinari',
    NOW(), NOW()), ('12377259', NULL, 'Porto Novo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.73855, -46.62838, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto novo porto novo brazil br porto novo',
    NOW(), NOW()), ('12386450', NULL, 'Jardim Portela', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.54535, -46.9422, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jardim portela jardim portela brazil br jardim portela',
    NOW(), NOW()), ('12386453', NULL, 'Jardim Marina', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.54876, -46.95165, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jardim marina jardim marina brazil br jardim marina',
    NOW(), NOW()), ('12388836', NULL, 'Serra do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.36647, -46.97125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra do porto serra do porto brazil br serra do porto',
    NOW(), NOW()), ('12396316', NULL, 'Sítio Porta do Sol', 'Sitio Porta do Sol',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.10662, -46.98361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porta do sol sitio porta do sol brazil br sitio porta do sol,sítio porta do sol',
    NOW(), NOW()), ('12396325', NULL, 'Sítio Porta do Céu', 'Sitio Porta do Ceu',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.12874, -46.97964, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio porta do céu sitio porta do ceu brazil br sitio porta do ceu,sítio porta do céu',
    NOW(), NOW()), ('12396418', NULL, 'Sítio Portão Grande', 'Sitio Portao Grande',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.19847, -46.80676, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sítio portão grande sitio portao grande brazil br sitio portao grande,sítio portão grande',
    NOW(), NOW()), ('12402353', NULL, 'Juruti Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.18711, -56.0924, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'juruti airport juruti airport brazil br jrt,snrj',
    NOW(), NOW()), ('12402376', NULL, 'Paragominas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.01825, -47.32124, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paragominas airport paragominas airport brazil br jpe,sneb',
    NOW(), NOW()), ('12402396', NULL, 'Apuí Airport', 'Apui Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.17375, -59.83897, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'apuí airport apui airport brazil br iup',
    NOW(), NOW()), ('12402397', NULL, 'São Paulo Catarina Executive Airport', 'Sao Paulo Catarina Executive Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.42659, -47.17185, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'são paulo catarina executive airport sao paulo catarina executive airport brazil br jhf,sbjh',
    NOW(), NOW()), ('12402419', NULL, 'Planalto Serrano Regional Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.62861, -50.35081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'planalto serrano regional airport planalto serrano regional airport brazil br eea,sncp',
    NOW(), NOW()), ('12402423', NULL, 'Walfrido Salmito de Almeida Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.0428, -40.89372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'walfrido salmito de almeida airport walfrido salmito de almeida airport brazil br jsb,swbe',
    NOW(), NOW()), ('12402440', NULL, 'Antônio Ribeiro Nogueira Jr. State Airport', 'Antonio Ribeiro Nogueira Jr. State Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.16316, -46.7873, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'antônio ribeiro nogueira jr. state airport antonio ribeiro nogueira jr. state airport brazil br jtn,sdim',
    NOW(), NOW()), ('12402443', NULL, 'Aeroporto Brigadeiro Eduardo Gomes', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.81357, -56.0363, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeroporto brigadeiro eduardo gomes aeroporto brigadeiro eduardo gomes brazil br nvm',
    NOW(), NOW()), ('12420786', NULL, 'Vacaria Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.42923, -51.02383, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vacaria airport vacaria airport brazil br snee,vcc',
    NOW(), NOW()), ('12420823', NULL, 'Aeródromo de Lorenzo', 'Aerodromo de Lorenzo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.39018, -38.91019, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aeródromo de lorenzo aerodromo de lorenzo brazil br aerodromo de lorenzo,aeroporto da terceira praia,aeródromo de lorenzo,mxq,sncl',
    NOW(), NOW()), ('12432112', NULL, 'Setor de Clubes Esportivos Norte', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.78739, -47.85045, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'setor de clubes esportivos norte setor de clubes esportivos norte brazil br setor de clubes esportivos norte',
    NOW(), NOW()), ('12432113', NULL, 'Setor de Clubes Esportivos Sul', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.81732, -47.85509, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'setor de clubes esportivos sul setor de clubes esportivos sul brazil br setor de clubes esportivos sul',
    NOW(), NOW()), ('12467089', NULL, 'Escola Clodoaldo Portugal Caribê', 'Escola Clodoaldo Portugal Caribe',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.68701, -46.45994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'escola clodoaldo portugal caribê escola clodoaldo portugal caribe brazil br escola clodoaldo portugal caribe,escola clodoaldo portugal caribê',
    NOW(), NOW()), ('12470233', NULL, 'Portal da Foz', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.5047, -54.53687, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portal da foz portal da foz brazil br',
    NOW(), NOW()), ('12482880', NULL, 'Fazenda do Porto', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.09806, -46.49398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda do porto fazenda do porto brazil br fazenda do porto',
    NOW(), NOW()), ('12491985', NULL, 'Araripina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.58566, -40.5353, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'araripina airport araripina airport brazil br jaw,snab',
    NOW(), NOW()), ('12492000', NULL, 'Salinopolis Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -0.69368, -47.32848, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'salinopolis airport salinopolis airport brazil br opp,snsm',
    NOW(), NOW()), ('12492001', NULL, 'Serra da Capivara Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.08066, -42.64303, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'serra da capivara airport serra da capivara airport brazil br nsr,swkq',
    NOW(), NOW()), ('12497022', NULL, 'Terminal Turístico Janeth Dias de Araújo', 'Terminal Turistico Janeth Dias de Araujo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.1392, -44.1686, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal turístico janeth dias de araújo terminal turistico janeth dias de araujo brazil br terminal turistico janeth dias de araujo,terminal turístico janeth dias de araújo',
    NOW(), NOW());