INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('3196056', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.85372, 19.02311, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba gnjica,lukavac,lukovac',
    NOW(), NOW()), ('3196057', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.68062, 18.26679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba lukavac,lukovac',
    NOW(), NOW()), ('3196064', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.82043, 16.4794, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba lukavica,lukavice',
    NOW(), NOW()), ('3196065', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.81152, 18.06279, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba lukavica',
    NOW(), NOW()), ('3196066', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.76452, 18.16887, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba lukavica',
    NOW(), NOW()), ('3196067', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.70363, 18.75651, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba',
    NOW(), NOW()), ('3196068', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.16015, 19.04132, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba',
    NOW(), NOW()), ('3196069', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.82693, 18.38318, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba lukavica,srpsko sarajevo',
    NOW(), NOW()), ('3196075', NULL, 'Lukavac Gornji', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.59097, 18.54372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac gornji lukavac gornji ba ba lukavac gornji,lukavac srpski,pravoslavni lukavac,srpski lukavac',
    NOW(), NOW()), ('3196076', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.90836, 18.72977, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba',
    NOW(), NOW()), ('3196077', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.79778, 18.47308, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba',
    NOW(), NOW()), ('3196079', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.54245, 18.52618, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'lukavac lukavac ba ba lukavac,lukavac muslimanski,lukavacas,muslimanski lukavac,lu ka wa ci,лукавац,盧卡瓦茨',
    NOW(), NOW()), ('3196081', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.54389, 18.37667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba',
    NOW(), NOW()), ('3196095', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.15972, 16.40806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka',
    NOW(), NOW()), ('3196096', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.97351, 19.22501, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka,medna luka,лука',
    NOW(), NOW()), ('3196098', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.95411, 18.47666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka',
    NOW(), NOW()), ('3196099', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.94612, 18.25418, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3196100', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.54208, 18.22558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka,luke',
    NOW(), NOW()), ('3196101', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.43527, 18.11614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka',
    NOW(), NOW()), ('3198843', NULL, 'Jaruške Gornje', 'Jaruske Gornje',
    NULL, 'BA', 'BA', NULL, NULL,
    44.4408, 18.42248, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jaruške gornje jaruske gornje ba ba jaruske gornje,jaruške gornje,muslimanske jazuske,muslimanske jazuške',
    NOW(), NOW()), ('3199804', NULL, 'Grabovica Donja', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.54874, 18.71202, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grabovica donja grabovica donja ba ba grabovica donja,muslimanska-grabovica',
    NOW(), NOW()), ('3199936', NULL, 'Gornji Ramići', 'Gornji Ramici',
    NULL, 'BA', 'BA', NULL, NULL,
    44.58385, 16.71703, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornji ramići gornji ramici ba ba gorni ramici,gornji ramici,gornji ramiçi,gornji ramići,muslimanski ramici,muslimanski ramići,ramici gornji,ramići gornji,горњи рамићи',
    NOW(), NOW()), ('3199974', NULL, 'Gornji Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.85919, 18.40774, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornji lukavac gornji lukavac ba ba gornji lukavac,lukavac gornji',
    NOW(), NOW()), ('3199975', NULL, 'Gornji Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.12338, 18.2837, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornji lukavac gornji lukavac ba ba gornji lukavac,lukavac gornji',
    NOW(), NOW()), ('3200019', NULL, 'Gornji Galjipovci', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.87159, 17.61489, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornji galjipovci gornji galjipovci ba ba galjipovci gornji,gornji galjipovci,muslimanski galjipovci',
    NOW(), NOW()), ('3200059', NULL, 'Gornje Živinice', 'Gornje Zivinice',
    NULL, 'BA', 'BA', NULL, NULL,
    44.42921, 18.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornje živinice gornje zivinice ba ba gornje zivinice,gornje živinice,muslimanske zivinice,muslimanske živinice,zivinice gornje,živinice gornje',
    NOW(), NOW()), ('3200116', NULL, 'Gornje Ledenice', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.91678, 18.45398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornje ledenice gornje ledenice ba ba gornje ledenice,ledenice gornje,muslimanski ledenice',
    NOW(), NOW()), ('3200228', NULL, 'Gornja Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.39779, 18.72583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornja lukavica gornja lukavica ba ba gornja lukavica,lukavica gornja',
    NOW(), NOW()), ('3200900', NULL, 'Džemat', 'Dzemat',
    NULL, 'BA', 'BA', NULL, NULL,
    44.20296, 18.97695, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'džemat dzemat ba ba dzemat,džemat,muslimanski dzemat,muslimanski džemat',
    NOW(), NOW()), ('3201444', NULL, 'Donji Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.83634, 18.4455, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donji lukavac donji lukavac ba ba donja lukavac,donji lukavac,lukavac donji',
    NOW(), NOW()), ('3201445', NULL, 'Donji Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.11155, 18.29784, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donji lukavac donji lukavac ba ba donji lukavac,lukavac donji',
    NOW(), NOW()), ('3201586', NULL, 'Donje Baljvine', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.46667, 17.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donje baljvine donje baljvine ba ba donje baljvine,muslimanske baljvine',
    NOW(), NOW()), ('3201664', NULL, 'Donja Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.40769, 18.70974, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donja lukavica donja lukavica ba ba donja lukavica,lukavica donja',
    NOW(), NOW()), ('3201667', NULL, 'Donja Lovnica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.40601, 18.13867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donja lovnica donja lovnica ba ba donja lovnica,lovnica donja,lovnica muslimanska',
    NOW(), NOW()), ('3202564', NULL, 'Čitluk', 'Citluk',
    NULL, 'BA', 'BA', NULL, NULL,
    43.22861, 17.70083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'čitluk citluk ba ba aequum,chitluk,citluk,citlukas,opshtina chitluk,qi te lu ke,čitluk,čitlukas,општина читлук,читлук,契特卢克',
    NOW(), NOW()), ('3202891', NULL, 'Čaklovići Donji', 'Caklovici Donji',
    NULL, 'BA', 'BA', NULL, NULL,
    44.51615, 18.73839, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'čaklovići donji caklovici donji ba ba caklovici donji,calkovici donji,muslimanski caklovici,muslimanski čaklovići,čaklovići donji,čalkovići donji',
    NOW(), NOW()), ('3203587', NULL, 'Bradići Donji', 'Bradici Donji',
    NULL, 'BA', 'BA', NULL, NULL,
    44.50771, 18.13356, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bradići donji bradici donji ba ba bradic donji,bradici donji,bradici muslimanski,bradić donji,bradići donji,bradići muslimanski,donji bradici,donji bradići,muslimanski bradici,muslimanski bradići',
    NOW(), NOW()), ('3204147', NULL, 'Biljani Donji', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.60794, 16.66777, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'biljani donji biljani donji ba ba biljani donji,muslimanski biljani',
    NOW(), NOW()), ('3204540', NULL, 'Železnička Stanica Banja Luka Predgrađe', 'Zeleznicka Stanica Banja Luka Predgrade',
    NULL, 'BA', 'BA', NULL, NULL,
    44.8, 17.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'železnička stanica banja luka predgrađe zeleznicka stanica banja luka predgrade ba ba stanica banja luka predgrade,stanica banja luka predgrađe,zeleznicka stanica banja luka predgrade,železnička stanica banja luka predgrađe',
    NOW(), NOW()), ('3204541', NULL, 'Banja Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.77879, 17.20629, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'banja luka banja luka ba ba bnx,bagnaluka,bana luka,bania louka,bania luka,banialuca,banja luka,banja luka - bana luka,banja-luka,banja-lukae,banjalucka,banjaluka,banjaluko,banya luka,baņa luka,ba ni ya lu ka,ban ya luk a,banja luka,banja lwka,banya lwka,banyaluka,μπάνια λούκα,баня лука,баня-лукæ,баня-лука,банꙗ лоука,бања лука,բանյա լուկա,באניה לוקה,بانجا لوکا,بانيا لوكا,بانیا لوکا,बंजा लुका,บันยาลูกา,ბანია-ლუკა,バニャ・ルカ,巴尼亚卢卡,바냐루카',
    NOW(), NOW()), ('3204568', NULL, 'Baljkovica Donja', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.46667, 18.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baljkovica donja baljkovica donja ba ba muslimanska baljkovica',
    NOW(), NOW()), ('3206120', NULL, 'Vučja Luka', 'Vucja Luka',
    NULL, 'BA', 'BA', NULL, NULL,
    43.92546, 18.5154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vučja luka vucja luka ba ba vucja luka,vučja luka',
    NOW(), NOW()), ('3206513', NULL, 'Kaliman', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.38236, 18.74018, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kaliman kaliman ba ba kaliman,lalovina',
    NOW(), NOW()), ('3211081', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.82104, 18.68733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba lukavac',
    NOW(), NOW()), ('3211132', NULL, 'Marina Glava', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.58143, 18.55771, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina glava marina glava ba ba',
    NOW(), NOW()), ('3211418', NULL, 'Babina Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.51372, 18.8087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'babina luka babina luka ba ba',
    NOW(), NOW()), ('3212752', NULL, 'Gornji Kalimanići', 'Gornji Kalimanici',
    NULL, 'BA', 'BA', NULL, NULL,
    43.91317, 18.99143, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornji kalimanići gornji kalimanici ba ba gornji kalimanici,gornji kalimanići',
    NOW(), NOW()), ('3229999', NULL, 'Federation of Bosnia and Herzegovina', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44, 17.58333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'federation of bosnia and herzegovina federation of bosnia and herzegovina ba ba bosniak-croat federation,fbih,federacija bih,federacija bikh,federacija bosne i hercegovine,federacija bosne i khercegovine,federacija bosnii i gercegoviny,federacio bosnio kaj hercegovino,federacion de bosnia-herzegovina,federation de bosnie-et-herzegovine,federation of b&h,federation of bosnia and herzegovina,federazione di bosnia ed erzegovina,foederation bosnien und herzegowina,fédération de bosnie-et-herzégovine,föderation bosnien und herzegowina,muslimansko-hrvatska federacija,федерация боснии и герцеговины,федерација бих,федерација босне и херцеговине',
    NOW(), NOW()), ('3234510', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.76953, 18.8913, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba lukavac',
    NOW(), NOW()), ('3235959', NULL, 'Dnoluka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.34, 17.33917, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dnoluka dnoluka ba ba',
    NOW(), NOW()), ('3236524', NULL, 'Lukači', 'Lukaci',
    NULL, 'BA', 'BA', NULL, NULL,
    44.49024, 17.1162, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukači lukaci ba ba',
    NOW(), NOW()), ('3237375', NULL, 'Velika Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.05623, 17.34714, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'velika luka velika luka ba ba',
    NOW(), NOW()), ('3237376', NULL, 'Mala Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.04902, 17.33527, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mala luka mala luka ba ba',
    NOW(), NOW()), ('3237510', NULL, 'Lukajići', 'Lukajici',
    NULL, 'BA', 'BA', NULL, NULL,
    44.20849, 16.66807, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukajići lukajici ba ba',
    NOW(), NOW()), ('3237790', NULL, 'Samarina Kosa', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.15702, 17.24914, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'samarina kosa samarina kosa ba ba samarina kosa',
    NOW(), NOW()), ('3241696', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    45.0375, 17.54556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3242456', NULL, 'Marina Voda', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.08944, 18.42472, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina voda marina voda ba ba',
    NOW(), NOW()), ('3242816', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.12167, 18.3525, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3244539', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.05566, 18.4982, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3247169', NULL, 'Marina Glavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.70583, 16.84722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina glavica marina glavica ba ba',
    NOW(), NOW()), ('3247399', NULL, 'Muslimanska Jasenica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.835, 16.2586, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'muslimanska jasenica muslimanska jasenica ba ba',
    NOW(), NOW()), ('3247974', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.57805, 16.67677, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3248098', NULL, 'Ralja Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.87528, 16.72139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ralja luka ralja luka ba ba',
    NOW(), NOW()), ('3248327', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.84364, 17.33267, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3248990', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.25871, 17.93375, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3249176', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.81569, 16.50581, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba lukavica,lukavice',
    NOW(), NOW()), ('3249575', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.61278, 17.29733, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3249607', NULL, 'Lukanovci', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.88028, 16.41139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukanovci lukanovci ba ba',
    NOW(), NOW()), ('3251377', NULL, 'Ranjena Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.28917, 17.55722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ranjena luka ranjena luka ba ba',
    NOW(), NOW()), ('3251557', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.28694, 17.57583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3251776', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.35881, 18.00586, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka',
    NOW(), NOW()), ('3252274', NULL, 'Lukanjsko Brdo', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.93639, 17.6425, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukanjsko brdo lukanjsko brdo ba ba',
    NOW(), NOW()), ('3252465', NULL, 'Hajdučka Luka', 'Hajducka Luka',
    NULL, 'BA', 'BA', NULL, NULL,
    44.33194, 18.28889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hajdučka luka hajducka luka ba ba',
    NOW(), NOW()), ('3253215', NULL, 'Sportski Centar Babanovac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.31322, 17.57196, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sportski centar babanovac sportski centar babanovac ba ba',
    NOW(), NOW()), ('3254006', NULL, 'Marina Voda', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.62111, 18.90806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina voda marina voda ba ba',
    NOW(), NOW()), ('3254303', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.68722, 17.54694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba',
    NOW(), NOW()), ('3255076', NULL, 'Crni Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.79597, 18.96372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'crni lukavac crni lukavac ba ba',
    NOW(), NOW()), ('3256187', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.79237, 18.7638, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3256955', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.73084, 18.74999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3257392', NULL, 'Marina Glavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.42972, 17.66028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina glavica marina glavica ba ba',
    NOW(), NOW()), ('3257439', NULL, 'Marina Glavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.56, 17.75333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina glavica marina glavica ba ba',
    NOW(), NOW()), ('3257454', NULL, 'Marina Glavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.54417, 17.70167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina glavica marina glavica ba ba',
    NOW(), NOW()), ('3259051', NULL, 'Rogovna Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.98803, 15.94779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rogovna luka rogovna luka ba ba',
    NOW(), NOW()), ('3260231', NULL, 'Lukači', 'Lukaci',
    NULL, 'BA', 'BA', NULL, NULL,
    44.29437, 16.31169, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukači lukaci ba ba',
    NOW(), NOW()), ('3260368', NULL, 'Lukačeva Uvala', 'Lukaceva Uvala',
    NULL, 'BA', 'BA', NULL, NULL,
    44.30306, 16.34306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukačeva uvala lukaceva uvala ba ba',
    NOW(), NOW()), ('3260594', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.55472, 17.57222, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3261835', NULL, 'Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    44.51755, 18.42211, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavac lukavac ba ba',
    NOW(), NOW()), ('3263135', NULL, 'Lukavački Potok', 'Lukavacki Potok',
    NULL, 'BA', 'BA', NULL, NULL,
    44.5719, 18.53494, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavački potok lukavacki potok ba ba',
    NOW(), NOW()), ('3263253', NULL, 'Lukavačka Reka', 'Lukavacka Reka',
    NULL, 'BA', 'BA', NULL, NULL,
    44.53094, 18.51743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavačka reka lukavacka reka ba ba',
    NOW(), NOW()), ('3263618', NULL, 'Lukavica', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.25567, 18.57467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavica lukavica ba ba',
    NOW(), NOW()), ('3263782', NULL, 'Donja Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.28494, 18.54287, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donja luka donja luka ba ba',
    NOW(), NOW()), ('3263785', NULL, 'Gornja Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.28278, 18.55278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gornja luka gornja luka ba ba',
    NOW(), NOW()), ('3264176', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    42.65444, 18.30389, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3265556', NULL, 'Kašmarina', 'Kasmarina',
    NULL, 'BA', 'BA', NULL, NULL,
    43.37204, 17.77804, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kašmarina kasmarina ba ba',
    NOW(), NOW()), ('3265615', NULL, 'Donji Lukavac', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.11194, 18.29806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donji lukavac donji lukavac ba ba doni lukavac,donji lukavac,доњи лукавац',
    NOW(), NOW()), ('3265624', NULL, 'Lukavačko Polje', 'Lukavacko Polje',
    NULL, 'BA', 'BA', NULL, NULL,
    43.12194, 18.26861, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukavačko polje lukavacko polje ba ba',
    NOW(), NOW()), ('3265645', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.3282, 17.82284, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba',
    NOW(), NOW()), ('3265704', NULL, 'Donja Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    42.89543, 17.98027, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donja luka donja luka ba ba',
    NOW(), NOW()), ('3265992', NULL, 'Luka', NULL,
    NULL, 'BA', 'BA', NULL, NULL,
    43.23462, 18.29475, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luka luka ba ba luka',
    NOW(), NOW()), ('3266374', NULL, 'Lukače', 'Lukace',
    NULL, 'BA', 'BA', NULL, NULL,
    43.15083, 18.10417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukače lukace ba ba',
    NOW(), NOW());