INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('8156223', NULL, 'Harbour Islets Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -40.64004, 144.73402, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour islets conservation area harbour islets conservation area australia au harbour islets conservation area',
    NOW(), NOW()), ('8156285', NULL, 'Kelvedon Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.94, 147.35001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kelvedon sports ground kelvedon sports ground australia au kelvedon sports ground',
    NOW(), NOW()), ('8156423', NULL, 'Glenhuon Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.31833, 115.7186, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'glenhuon sportsground glenhuon sportsground australia au glenhuon sportsground',
    NOW(), NOW()), ('8156629', NULL, 'Jurien Bay Sports and Recreation Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.30099, 115.0515, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jurien bay sports and recreation centre jurien bay sports and recreation centre australia au jurien bay sports and recreation centre',
    NOW(), NOW()), ('8157067', NULL, 'Little Plain Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.5818, 152.28461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'little plain sportsground little plain sportsground australia au little plain sportsground',
    NOW(), NOW()), ('8157101', NULL, 'Mckay Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9068, 151.2346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mckay sportsground mckay sportsground australia au mckay sportsground',
    NOW(), NOW()), ('8157127', NULL, 'Maitland Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7318, 151.55119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maitland sportsground maitland sportsground australia au maitland sportsground',
    NOW(), NOW()), ('8157155', NULL, 'Mannering Park Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1485, 151.53461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mannering park sportsground mannering park sportsground australia au mannering park sportsground',
    NOW(), NOW()), ('8157200', NULL, 'Mauger Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3652, 149.2346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mauger sportsground mauger sportsground australia au mauger sportsground',
    NOW(), NOW()), ('8157203', NULL, 'Max Ruddock Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7652, 150.9679, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'max ruddock reserve max ruddock reserve australia au max ruddock reserve',
    NOW(), NOW()), ('8157294', NULL, 'Mountain District Sports Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.2818, 151.2012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mountain district sports park mountain district sports park australia au mountain district sports park',
    NOW(), NOW()), ('8157342', NULL, 'Munmorah Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1985, 151.5679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'munmorah sportsground munmorah sportsground australia au munmorah sportsground',
    NOW(), NOW()), ('8157376', NULL, 'Lake Entrance Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lake entrance sportsfield lake entrance sportsfield australia au lake entrance sportsfield',
    NOW(), NOW()), ('8157454', NULL, 'Laurieton Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.6471, 152.7998, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laurieton sporting complex laurieton sporting complex australia au laurieton sporting complex',
    NOW(), NOW()), ('8157479', NULL, 'Mark Leece Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.793, 150.7887, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mark leece sporting complex mark leece sporting complex australia au mark leece sporting complex',
    NOW(), NOW()), ('8157545', NULL, 'Mclean Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5652, 148.3846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mclean sportsground mclean sportsground australia au mclean sportsground',
    NOW(), NOW()), ('8157649', NULL, 'Margaret Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7793, 150.78011, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'margaret porter reserve margaret porter reserve australia au margaret porter reserve',
    NOW(), NOW()), ('8157737', NULL, 'Lyrebird Sports Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8805, 150.61259, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lyrebird sports park lyrebird sports park australia au lyrebird sports park',
    NOW(), NOW()), ('8157837', NULL, 'Maluka Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.46311, 132.27951, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maluka park maluka park australia au maluka park',
    NOW(), NOW()), ('8157999', NULL, 'Lower Portrush Road Buffer Reserve Number One', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.89004, 138.62997, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lower portrush road buffer reserve number one lower portrush road buffer reserve number one australia au lower portrush road buffer reserve number one',
    NOW(), NOW()), ('8158047', NULL, 'Lower Portrush Road Buffer Reserve Number Three', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.89161, 138.63238, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lower portrush road buffer reserve number three lower portrush road buffer reserve number three australia au lower portrush road buffer reserve number three',
    NOW(), NOW()), ('8158048', NULL, 'Lower Portrush Road Buffer Reserve Number Two', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.89049, 138.6306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lower portrush road buffer reserve number two lower portrush road buffer reserve number two australia au lower portrush road buffer reserve number two',
    NOW(), NOW()), ('8158191', NULL, 'Myer Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.96669, 138.54755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'myer sports ground myer sports ground australia au myer sports ground',
    NOW(), NOW()), ('8158258', NULL, 'Little Swanport Private Nature Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.33, 147.86, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'little swanport private nature reserve little swanport private nature reserve australia au little swanport private nature reserve',
    NOW(), NOW()), ('8158279', NULL, 'Macquarie Harbour Historic Site', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.36, 145.45, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'macquarie harbour historic site macquarie harbour historic site australia au macquarie harbour historic site',
    NOW(), NOW()), ('8158456', NULL, 'Macmahon Ball Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.71958, 145.15375, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'macmahon ball paddock macmahon ball paddock australia au macmahon ball paddock',
    NOW(), NOW()), ('8158461', NULL, 'Manningham Donvale Indoor Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.79958, 145.17819, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manningham donvale indoor sports centre manningham donvale indoor sports centre australia au manningham donvale indoor sports centre',
    NOW(), NOW()), ('8158823', NULL, 'Police Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4152, 149.5846, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'police paddock police paddock australia au police paddock',
    NOW(), NOW()), ('8158853', NULL, 'Old Harbour Lagoon Wildlife Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.9318, 148.7596, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'old harbour lagoon wildlife reserve old harbour lagoon wildlife reserve australia au old harbour lagoon wildlife reserve',
    NOW(), NOW()), ('8158855', NULL, 'Old Wharf Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6318, 151.3179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'old wharf reserve old wharf reserve australia au old wharf reserve',
    NOW(), NOW()), ('8158883', NULL, 'Napier Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.5318, 149.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier park napier park australia au napier park',
    NOW(), NOW()), ('8158914', NULL, 'Newport Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6485, 151.30119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport park newport park australia au newport park',
    NOW(), NOW()), ('8158944', NULL, 'North Harbour Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 151.2679, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'north harbour reserve north harbour reserve australia au north harbour reserve',
    NOW(), NOW()), ('8158999', NULL, 'Panorama Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5568, 150.8346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'panorama sportsfield panorama sportsfield australia au panorama sportsfield',
    NOW(), NOW()), ('8159028', NULL, 'Paterson Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5985, 151.61791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paterson sportsground paterson sportsground australia au paterson sportsground',
    NOW(), NOW()), ('8159114', NULL, 'Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6485, 151.3179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter reserve porter reserve australia au porter reserve',
    NOW(), NOW()), ('8159115', NULL, 'Porters Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters park porters park australia au porters park',
    NOW(), NOW()), ('8159116', NULL, 'Porters Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.6485, 150.8512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters reserve porters reserve australia au porters reserve',
    NOW(), NOW()), ('8159117', NULL, 'Port Hacking Rugby Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0235, 151.1123, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hacking rugby field port hacking rugby field australia au port hacking rugby field',
    NOW(), NOW()), ('8159118', NULL, 'Portius Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portius park portius park australia au portius park',
    NOW(), NOW()), ('8159119', NULL, 'Portland Rifle Range', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3652, 150.0096, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland rifle range portland rifle range australia au portland rifle range',
    NOW(), NOW()), ('8159154', NULL, 'Purlewaugh Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.3485, 149.55119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'purlewaugh sports ground purlewaugh sports ground australia au purlewaugh sports ground',
    NOW(), NOW()), ('8159171', NULL, 'Queens Wharf Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8152, 151.0179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'queens wharf park queens wharf park australia au queens wharf park',
    NOW(), NOW()), ('8159284', NULL, 'Rockdale Womens Sportsfields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9485, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rockdale womens sportsfields rockdale womens sportsfields australia au rockdale womens sportsfields',
    NOW(), NOW()), ('8159319', NULL, 'Ruddock Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7485, 151.0679, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ruddock park ruddock park australia au ruddock park',
    NOW(), NOW()), ('8159321', NULL, 'Ruddock Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7152, 151.0679, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ruddock park ruddock park australia au ruddock park',
    NOW(), NOW()), ('8159322', NULL, 'Ruddock Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7652, 150.9679, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ruddock reserve ruddock reserve australia au ruddock reserve',
    NOW(), NOW()), ('8159384', NULL, 'Port Macquarie Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4318, 152.91789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port macquarie park port macquarie park australia au port macquarie park',
    NOW(), NOW()), ('8159445', NULL, 'Raby Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0152, 150.80119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'raby sports complex raby sports complex australia au raby sports complex',
    NOW(), NOW()), ('8159452', NULL, 'Rosemeadow Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0818, 150.78461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rosemeadow sports complex rosemeadow sports complex australia au rosemeadow sports complex',
    NOW(), NOW()), ('8159754', NULL, 'Rologas Sporting Fields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.511, 151.67371, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rologas sporting fields rologas sporting fields australia au rologas sporting fields',
    NOW(), NOW()), ('8159809', NULL, 'Newport Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.37732, 149.56663, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport conservation park newport conservation park australia au newport conservation park',
    NOW(), NOW()), ('8159824', NULL, 'Police Paddock Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.55841, 152.68384, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'police paddock conservation park police paddock conservation park australia au police paddock conservation park',
    NOW(), NOW()), ('8159880', NULL, 'Port Elliot Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.52991, 138.67548, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot oval port elliot oval australia au port elliot oval',
    NOW(), NOW()), ('8159894', NULL, 'Olympic Sportsfield', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.92169, 138.65269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic sportsfield olympic sportsfield australia au olympic sportsfield',
    NOW(), NOW()), ('8159920', NULL, 'Port Gawler Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66993, 138.4398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port gawler conservation park port gawler conservation park australia au port gawler conservation park',
    NOW(), NOW()), ('8159934', NULL, 'Port Noarlunga Aquatic Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.15296, 138.46394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port noarlunga aquatic reserve port noarlunga aquatic reserve australia au port noarlunga aquatic reserve',
    NOW(), NOW()), ('8159938', NULL, 'Point Davenport Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.16043, 137.33449, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point davenport conservation park point davenport conservation park australia au point davenport conservation park',
    NOW(), NOW()), ('8159956', NULL, 'Port Broughton Caravan Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.60678, 137.92839, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton caravan park port broughton caravan park australia au port broughton caravan park',
    NOW(), NOW()), ('8159989', NULL, 'Porter Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.54744, 138.5925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter reserve porter reserve australia au porter reserve',
    NOW(), NOW()), ('8159996', NULL, 'Philips Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.88145, 138.51852, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'philips sports field philips sports field australia au philips sports field',
    NOW(), NOW()), ('8160017', NULL, 'Olympic Park Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.83283, 140.77457, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'olympic park sports field olympic park sports field australia au olympic park sports field',
    NOW(), NOW()), ('8160081', NULL, 'Patterson Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.89301, 138.64343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'patterson sportsground patterson sportsground australia au patterson sportsground',
    NOW(), NOW()), ('8160110', NULL, 'Porter Scrub Conservation Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.86496, 138.90778, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter scrub conservation park porter scrub conservation park australia au porter scrub conservation park',
    NOW(), NOW()), ('8160138', NULL, 'Newton Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.88373, 138.68986, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newton sports ground newton sports ground australia au newton sports ground',
    NOW(), NOW()), ('8160169', NULL, 'Port Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.19245, 138.00926, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port oval port oval australia au port oval',
    NOW(), NOW()), ('8160195', NULL, 'New Town Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.85, 147.28999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'new town sports ground new town sports ground australia au new town sports ground',
    NOW(), NOW()), ('8160201', NULL, 'North Chigwell Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.8, 147.24001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north chigwell sports ground north chigwell sports ground australia au north chigwell sports ground',
    NOW(), NOW()), ('8160204', NULL, 'North Hobart Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.86, 147.31, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north hobart sports ground north hobart sports ground australia au north hobart sports ground',
    NOW(), NOW()), ('8160245', NULL, 'Pierces Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.92, 147.35001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierces reserve pierces reserve australia au pierces reserve',
    NOW(), NOW()), ('8160246', NULL, 'Piersons Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.05, 147.34, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piersons park piersons park australia au piersons park',
    NOW(), NOW()), ('8160253', NULL, 'Police Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.23, 146.39999, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'police paddock police paddock australia au police paddock',
    NOW(), NOW()), ('8160254', NULL, 'Port Cygnet Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.17, 147.08, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port cygnet conservation area port cygnet conservation area australia au port cygnet conservation area',
    NOW(), NOW()), ('8160255', NULL, 'Port Sorell Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.17, 146.53999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port sorell conservation area port sorell conservation area australia au port sorell conservation area',
    NOW(), NOW()), ('8160277', NULL, 'Ravenswood Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.41, 147.16, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ravenswood sports ground ravenswood sports ground australia au ravenswood sports ground',
    NOW(), NOW()), ('8160317', NULL, 'Royal Derwent Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.78, 147.06, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'royal derwent sports ground royal derwent sports ground australia au royal derwent sports ground',
    NOW(), NOW()), ('8160349', NULL, 'Port Arthur Historic Site', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.15, 147.84, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port arthur historic site port arthur historic site australia au port arthur historic site',
    NOW(), NOW()), ('8160388', NULL, 'Portsea Recreation Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.32458, 144.71542, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portsea recreation reserve portsea recreation reserve australia au portsea recreation reserve',
    NOW(), NOW()), ('8160391', NULL, 'Port Campbell National Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.64144, 143.06813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port campbell national park port campbell national park australia au port campbell national park',
    NOW(), NOW()), ('8160587', NULL, 'Port Hedland Community Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.3081, 118.6055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hedland community park port hedland community park australia au port hedland community park',
    NOW(), NOW()), ('8160588', NULL, 'Port Kennedy Scientific Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.36306, 115.7097, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kennedy scientific park port kennedy scientific park australia au port kennedy scientific park',
    NOW(), NOW()), ('8160589', NULL, 'Portmarnock Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.53528, 115.6978, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portmarnock reserve portmarnock reserve australia au portmarnock reserve',
    NOW(), NOW()), ('8160815', NULL, 'Shellharbour Municipality War Memorial Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour municipality war memorial park shellharbour municipality war memorial park australia au shellharbour municipality war memorial park',
    NOW(), NOW()), ('8160816', NULL, 'Shellharbour Pioneer Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5818, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour pioneer park shellharbour pioneer park australia au shellharbour pioneer park',
    NOW(), NOW()), ('8160817', NULL, 'Shellharbour War Memorial Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.5485, 150.8512, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour war memorial park shellharbour war memorial park australia au shellharbour war memorial park',
    NOW(), NOW()), ('8160891', NULL, 'Uki Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.4152, 153.3346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uki sports oval uki sports oval australia au uki sports oval',
    NOW(), NOW()), ('8161070', NULL, 'Tenambit Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7457, 151.6123, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tenambit sports area tenambit sports area australia au tenambit sports area',
    NOW(), NOW()), ('8161118', NULL, 'Victoria Sports Oval', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.6985, 147.8346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'victoria sports oval victoria sports oval australia au victoria sports oval',
    NOW(), NOW()), ('8161141', NULL, 'Wimbo Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.88112, 151.20076, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wimbo paddock wimbo paddock australia au wimbo paddock',
    NOW(), NOW()), ('8161150', NULL, 'Wellington Show and Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5485, 148.91789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wellington show and sports ground wellington show and sports ground australia au wellington show and sports ground',
    NOW(), NOW()), ('8161222', NULL, 'Sydney Cricket and Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.89351, 151.22704, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sydney cricket and sports ground sydney cricket and sports ground australia au sydney cricket and sports ground',
    NOW(), NOW()), ('8161243', NULL, 'West Guildford Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 150.9512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west guildford sports centre west guildford sports centre australia au west guildford sports centre',
    NOW(), NOW()), ('8161287', NULL, 'The Boiler Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 150.894, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the boiler paddock the boiler paddock australia au the boiler paddock',
    NOW(), NOW()), ('8161603', NULL, 'Tuncurry Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.1652, 152.4846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tuncurry sports centre tuncurry sports centre australia au tuncurry sports centre',
    NOW(), NOW()), ('8161814', NULL, 'War Memorial Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.8485, 153.4429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'war memorial sportsground war memorial sportsground australia au war memorial sportsground',
    NOW(), NOW()), ('8161879', NULL, 'West End Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5818, 149.55119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west end sporting complex west end sporting complex australia au west end sporting complex',
    NOW(), NOW()), ('8161883', NULL, 'Wharf Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.15961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wharf reserve wharf reserve australia au wharf reserve',
    NOW(), NOW()), ('8161954', NULL, 'Woodberry Sports Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7985, 151.6512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woodberry sports centre woodberry sports centre australia au woodberry sports centre',
    NOW(), NOW()), ('8161977', NULL, 'Wright Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3485, 149.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wright sportsground wright sportsground australia au wright sportsground',
    NOW(), NOW()), ('8162025', NULL, 'Westport Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4152, 152.9012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'westport park westport park australia au westport park',
    NOW(), NOW());