INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('3452631', NULL, 'Pôrto Tagaçaba', 'Porto Tagacaba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.21667, -48.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto tagaçaba porto tagacaba brazil br',
    NOW(), NOW()), ('3452632', NULL, 'Pôrto Taboado', 'Porto Taboado',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.18333, -51.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto taboado porto taboado brazil br porto taboado,porto tabuado,porto do taboado,pôrto taboado,pôrto tabuado',
    NOW(), NOW()), ('3452633', NULL, 'Pôrto Sol de Maio', 'Porto Sol de Maio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.06067, -54.38397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sol de maio porto sol de maio brazil br porto sol de maio,pôrto sol de maio,sol de maio',
    NOW(), NOW()), ('3452634', NULL, 'Pôrto Sinop', 'Porto Sinop',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.08333, -53.98333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sinop porto sinop brazil br porto sinop,porto snope,pôrto sinop,pôrto snope',
    NOW(), NOW()), ('3452635', NULL, 'Pôrto Sete de Setembro', 'Porto Sete de Setembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.18333, -54.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sete de setembro porto sete de setembro brazil br',
    NOW(), NOW()), ('3452636', NULL, 'Pôrto Sete de Setembro', 'Porto Sete de Setembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.21667, -52.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sete de setembro porto sete de setembro brazil br porto 7 de setembro,porto sete de setembro,pôrto 7 de setembro,pôrto sete de setembro',
    NOW(), NOW()), ('3452637', NULL, 'Baía de Pôrto Seguro', 'Baia de Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.45, -39.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baía de pôrto seguro baia de porto seguro brazil br baia de porto seguro,baía de pôrto seguro',
    NOW(), NOW()), ('3452638', NULL, 'Pôrto Seguro', 'Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9, -50.43333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto seguro porto seguro brazil br',
    NOW(), NOW()), ('3452639', NULL, 'Pôrto Seguro', 'Porto Seguro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.68333, -42.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto seguro porto seguro brazil br porto seguro,pôrto seguro',
    NOW(), NOW()), ('3452640', NULL, 'Porto Seguro', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.44972, -39.06472, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'porto seguro porto seguro brazil br bps,portu-seguru,bwrtw syjwrw,parto seguro,sai gu lu gang,порту-сегуру,بورتو سيجورو,পর্টো সেগুরো,პორტუ-სეგურუ,ポルト・セグーロ,塞古鲁港',
    NOW(), NOW()), ('3452641', NULL, 'Pôrto Sassoró', 'Porto Sassoro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.56667, -54.76667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sassoró porto sassoro brazil br porto sassora,porto sassoro,pôrto sassorá,pôrto sassoró,sassoro,sassoró',
    NOW(), NOW()), ('3452642', NULL, 'Pôrto Sapé', 'Porto Sape',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.9, -53.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sapé porto sape brazil br',
    NOW(), NOW()), ('3452643', NULL, 'Pôrto Sapé', 'Porto Sape',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.88333, -54.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto sapé porto sape brazil br porto cafe,porto cape,porto sape,pôrto café,pôrto capé,pôrto sapé',
    NOW(), NOW()), ('3452644', NULL, 'Pôrto São Pedro', 'Porto Sao Pedro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.75, -53.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são pedro porto sao pedro brazil br',
    NOW(), NOW()), ('3452645', NULL, 'Pôrto São Paulo Novo', 'Porto Sao Paulo Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.98333, -52.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são paulo novo porto sao paulo novo brazil br',
    NOW(), NOW()), ('3452646', NULL, 'Pôrto São Martinho', 'Porto Sao Martinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.73333, -54.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são martinho porto sao martinho brazil br porto martinho,porto sao martinho,pôrto são martinho',
    NOW(), NOW()), ('3452647', NULL, 'Pôrto São José Velho', 'Porto Sao Jose Velho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.36937, -56.79125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são josé velho porto sao jose velho brazil br porto sao jose,porto sao jose velho,pôrto são josé,pôrto são josé velho,sao jose,são josé',
    NOW(), NOW()), ('3452648', NULL, 'Porto São José', 'Porto Sao Jose',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.71861, -53.17639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto são josé porto sao jose brazil br sao jose,são josé',
    NOW(), NOW()), ('3452649', NULL, 'Pôrto São João', 'Porto Sao Joao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.63333, -53.13333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são joão porto sao joao brazil br porto sao joao,pôrto são joão,sao joao,são joão',
    NOW(), NOW()), ('3452650', NULL, 'Pôrto São Jerônimo', 'Porto Sao Jeronimo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.07153, -50.18797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são jerônimo porto sao jeronimo brazil br porto sao jeronimo,porto sao jeronymo,porto do jeronimo,pôrto são jeronymo,pôrto são jerônimo,pôrto do jerónimo,sao jeronimo,são jerônimo',
    NOW(), NOW()), ('3452651', NULL, 'Pôrto São Francisco', 'Porto Sao Francisco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.6, -53.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são francisco porto sao francisco brazil br',
    NOW(), NOW()), ('3452652', NULL, 'Pôrto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.57452, -54.27658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são domingos porto sao domingos brazil br',
    NOW(), NOW()), ('3452653', NULL, 'Pôrto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.21667, -50.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são domingos porto sao domingos brazil br porto sao domingos,porto de sao domingos,porto de são domingos,pôrto são domingos',
    NOW(), NOW()), ('3452654', NULL, 'Porto São Domingos', 'Porto Sao Domingos',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.95, -51.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto são domingos porto sao domingos brazil br porto sao domingos,porto são domingos',
    NOW(), NOW()), ('3452655', NULL, 'Pôrto São Bento', 'Porto Sao Bento',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.01667, -53.71667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto são bento porto sao bento brazil br',
    NOW(), NOW()), ('3452656', NULL, 'Pôrto Santo Antônio', 'Porto Santo Antonio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.47227, -54.34361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santo antônio porto santo antonio brazil br',
    NOW(), NOW()), ('3452657', NULL, 'Praia do Pôrto Santo', 'Praia do Porto Santo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.81667, -43.25, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'praia do pôrto santo praia do porto santo brazil br praia do porto santo,praia do pôrto santo',
    NOW(), NOW()), ('3452658', NULL, 'Pôrto Santa Rosa', 'Porto Santa Rosa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.46667, -53.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa rosa porto santa rosa brazil br',
    NOW(), NOW()), ('3452659', NULL, 'Pôrto Santa Rosa', 'Porto Santa Rosa',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.98333, -57.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa rosa porto santa rosa brazil br porto santa rosa,pôrto santa rosa,santa rosa',
    NOW(), NOW()), ('3452660', NULL, 'Pôrto Santana', 'Porto Santana',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.66667, -52.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santana porto santana brazil br',
    NOW(), NOW()), ('3452661', NULL, 'Pôrto Santa Maria', 'Porto Santa Maria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.71667, -52.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa maria porto santa maria brazil br',
    NOW(), NOW()), ('3452662', NULL, 'Pôrto Santa Bárbara', 'Porto Santa Barbara',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.5, -53.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto santa bárbara porto santa barbara brazil br porto santa barbara,pôrto santa bárbara,santa barbara,santa bárbara',
    NOW(), NOW()), ('3452663', NULL, 'Pôrto Rolon', 'Porto Rolon',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.23333, -53.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rolon porto rolon brazil br',
    NOW(), NOW()), ('3452664', NULL, 'Pôrto Rode', 'Porto Rode',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.16667, -53.61667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rode porto rode brazil br',
    NOW(), NOW()), ('3452665', NULL, 'Pôrto Rio Iguatemi', 'Porto Rio Iguatemi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.93333, -54.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rio iguatemi porto rio iguatemi brazil br',
    NOW(), NOW()), ('3452666', NULL, 'Pôrto Rio Amambaí', 'Porto Rio Amambai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.33333, -53.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto rio amambaí porto rio amambai brazil br',
    NOW(), NOW()), ('3452667', NULL, 'Porto Rico', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.77222, -53.26694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto rico porto rico brazil br',
    NOW(), NOW()), ('3452668', NULL, 'Pôrto Ribeiro', 'Porto Ribeiro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.45, -48.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ribeiro porto ribeiro brazil br porto ribeiro,pôrto ribeiro',
    NOW(), NOW()), ('3452669', NULL, 'Pôrto Ribeirão Vermelho', 'Porto Ribeirao Vermelho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.7, -51.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ribeirão vermelho porto ribeirao vermelho brazil br porto ribeirao vermelho,pôrto ribeirão vermelho,vermelho',
    NOW(), NOW()), ('3452670', NULL, 'Porto Real do Colégio', 'Porto Real Do Colegio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.10538, -36.72695, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real do colégio porto real do colegio brazil br',
    NOW(), NOW()), ('3452671', NULL, 'Porto Real do Colégio', 'Porto Real do Colegio',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.18583, -36.84, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real do colégio porto real do colegio brazil br porto real do collegio',
    NOW(), NOW()), ('3452672', NULL, 'Porto Real', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.41972, -44.29028, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto real porto real brazil br',
    NOW(), NOW()), ('3452673', NULL, 'Pôrto Quiqui', 'Porto Quiqui',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.95, -54.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quiqui porto quiqui brazil br porto kiki,porto quiqui,pôrto kiki,pôrto quiqui',
    NOW(), NOW()), ('3452674', NULL, 'Pôrto Quinze de Novembro', 'Porto Quinze de Novembro',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.78333, -52.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de novembro porto quinze de novembro brazil br porto 15 novembro,porto 15 de novembre,porto quinze de novembro,pôrto 15 novembro,pôrto 15 de novembre,pôrto quinze de novembro',
    NOW(), NOW()), ('3452675', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.71667, -53.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agôsto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452676', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.65, -53.53333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agôsto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452677', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.96667, -53.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze de agosto,pôrto 15 de agosto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452678', NULL, 'Pôrto Quinze de Agôsto', 'Porto Quinze de Agosto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.21667, -59.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quinze de agôsto porto quinze de agosto brazil br porto 15 de agosto,porto quinze,porto quinze de agosto,pôrto 15 de agosto,pôrto quinze de agôsto',
    NOW(), NOW()), ('3452680', NULL, 'Pôrto Quebracho', 'Porto Quebracho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.83333, -57.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quebracho porto quebracho brazil br porto quebracho,porto quebrado,pôrto quebracho,pôrto quebrado',
    NOW(), NOW()), ('3452681', NULL, 'Pôrto Quebra-Canoas', 'Porto Quebra-Canoas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91667, -50.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto quebra-canoas porto quebra-canoas brazil br porto quebra-canoas,porto teixeira,pôrto quebra-canoas',
    NOW(), NOW()), ('3452682', NULL, 'Primavera', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.53342, -52.94773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'primavera primavera brazil br porto primavera,primavera,pôrto primavera',
    NOW(), NOW()), ('3452683', NULL, 'Pôrto Porobeu', 'Porto Porobeu',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.95, -56.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto porobeu porto porobeu brazil br porto porobeu,porto santa maria,porto da fazenda santa maria do poborereu,porto da fazenda santa maria do poboreu,porto do fazenda santa maria,pôrto porobeu,pôrto da fazenda santa maria do poboreu',
    NOW(), NOW()), ('3452684', NULL, 'Pôrto Piraí', 'Porto Pirai',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.73333, -54.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto piraí porto pirai brazil br',
    NOW(), NOW()), ('3452685', NULL, 'Pôrto Pirabebe', 'Porto Pirabebe',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.31667, -53.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto pirabebe porto pirabebe brazil br',
    NOW(), NOW()), ('3452686', NULL, 'Pôrto Piquiri', 'Porto Piquiri',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.4, -53.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto piquiri porto piquiri brazil br porto pequeri,porto piquiri,pôrto pequeri,pôrto piquiri',
    NOW(), NOW()), ('3452687', NULL, 'Pôrto Pio Prado', 'Porto Pio Prado',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.05, -50.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto pio prado porto pio prado brazil br',
    NOW(), NOW()), ('3452688', NULL, 'Gôio En', 'Goio En',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.27972, -52.69, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gôio en goio en brazil br goio en,goio-ere,goio-erè,goy en,goyo-en,porto goio en,porto goyo en',
    NOW(), NOW()), ('3452689', NULL, 'Pôrto Pinduva', 'Porto Pinduva',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.55, -47.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto pinduva porto pinduva brazil br',
    NOW(), NOW()), ('3452690', NULL, 'Pôrto Perobá', 'Porto Peroba',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9, -53.63333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto perobá porto peroba brazil br',
    NOW(), NOW()), ('3452691', NULL, 'Pôrto Passo Cuê', 'Porto Passo Cue',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.30676, -54.45945, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto passo cuê porto passo cue brazil br',
    NOW(), NOW()), ('3452692', NULL, 'Pôrto Passagem', 'Porto Passagem',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.01667, -48.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto passagem porto passagem brazil br passagem,porto passagem,pôrto passagem',
    NOW(), NOW()), ('3452693', NULL, 'Pôrto Paraguaia', 'Porto Paraguaia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.36667, -53.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto paraguaia porto paraguaia brazil br porto papagaio,porto paraguaia,pôrto papagaio,pôrto paraguaia',
    NOW(), NOW()), ('3452694', NULL, 'Pôrto Pantanal', 'Porto Pantanal',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.95, -57.93333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto pantanal porto pantanal brazil br porto pantanal,pôrto pantanal',
    NOW(), NOW()), ('3452695', NULL, 'Palmital', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.04191, -48.80787, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palmital palmital brazil br palmital,porto palmital,porto do palmital,pôrto palmital,pôrto do palmital',
    NOW(), NOW()), ('3452696', NULL, 'Pôrto Palmira', 'Porto Palmira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.96667, -50.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto palmira porto palmira brazil br porto,porto palmira,pôrto,pôrto palmira',
    NOW(), NOW()), ('3452697', NULL, 'Pôrto Oculto', 'Porto Oculto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.8, -54.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto oculto porto oculto brazil br porto occulto,porto oculto,pôrto oculto',
    NOW(), NOW()), ('3452698', NULL, 'Pôrto Oculto', 'Porto Oculto',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.18333, -54.11667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto oculto porto oculto brazil br',
    NOW(), NOW()), ('3452699', NULL, 'Pôrto Ocoí', 'Porto Ocoi',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.21667, -54.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto ocoí porto ocoi brazil br porto ocoi,porto ocoy,porto oeoi,puerto ocoi,pôrto ocoí',
    NOW(), NOW()), ('3452700', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.05, -54.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br',
    NOW(), NOW()), ('3452701', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.71667, -54.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br',
    NOW(), NOW()), ('3452702', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.88333, -42.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br porto novo,pôrto novo',
    NOW(), NOW()), ('3452703', NULL, 'Porto Novo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.29845, -40.36779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto novo porto novo brazil br porto novo,pôrto novo',
    NOW(), NOW()), ('3452704', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.76667, -57.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br porto novo,porto velho,porto do triunfo,pôrto novo,pôrto velho,pôrto do triunfo',
    NOW(), NOW()), ('3452705', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.81667, -56.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br',
    NOW(), NOW()), ('3452706', NULL, 'Porto Novo', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.29361, -43.90889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto novo porto novo brazil br',
    NOW(), NOW()), ('3452707', NULL, 'Pôrto Novo', 'Porto Novo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.78333, -44.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto novo porto novo brazil br',
    NOW(), NOW()), ('3452708', NULL, 'Pôrto Notícia', 'Porto Noticia',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.8, -54.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto notícia porto noticia brazil br porto dourado,porto noticia,pôrto dourado,pôrto notícia',
    NOW(), NOW()), ('3452709', NULL, 'Pôrto Nóbrega', 'Porto Nobrega',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.16667, -47.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto nóbrega porto nobrega brazil br',
    NOW(), NOW()), ('3452710', NULL, 'Pôrto Nhô-Nhô Morais', 'Porto Nho-Nho Morais',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.62003, -52.14667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto nhô-nhô morais porto nho-nho morais brazil br nhonho morais,porto nho-nho morais,pôrto nhô-nhô morais',
    NOW(), NOW()), ('3452711', NULL, 'Porto Nacional', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.70806, -48.41722, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto nacional porto nacional brazil br pnb,porto nacional',
    NOW(), NOW()), ('3452712', NULL, 'Porto Murtinho', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.69889, -57.8825, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'porto murtinho porto murtinho brazil br',
    NOW(), NOW()), ('3452713', NULL, 'Pôrto Morrinho', 'Porto Morrinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.63333, -57.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto morrinho porto morrinho brazil br',
    NOW(), NOW()), ('3452714', NULL, 'Pôrto Morocó', 'Porto Moroco',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.4, -55.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto morocó porto moroco brazil br porto maraca,porto maracá,porto monoco,porto moroco,porto mororo,pôrto monoco,pôrto morocó,pôrto mororó',
    NOW(), NOW()), ('3452715', NULL, 'Pôrto Militão', 'Porto Militao',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.93333, -49.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto militão porto militao brazil br porto militao,pôrto militão',
    NOW(), NOW()), ('3452716', NULL, 'Pôrto Mercedes', 'Porto Mercedes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.33333, -55.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto mercedes porto mercedes brazil br',
    NOW(), NOW()), ('3452717', NULL, 'Pôrto Menezes', 'Porto Menezes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.06667, -50.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto menezes porto menezes brazil br',
    NOW(), NOW()), ('3452718', NULL, 'Pôrto Mendes', 'Porto Mendes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.38885, -54.52746, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto mendes porto mendes brazil br porto a. mendes,porto mendes,pôrto a. mendes,pôrto mendes',
    NOW(), NOW()), ('3452719', NULL, 'Porto Mendes', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.48965, -54.30782, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto mendes porto mendes brazil br mendez,porto mendes goncalves,puerto mendes,puerto mendez,puerto méndez,pôrto mendes gonçalves',
    NOW(), NOW()), ('3452720', NULL, 'Pôrto Meira', 'Porto Meira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -25.56667, -54.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto meira porto meira brazil br porto general meira,porto meira,pôrto general meira,pôrto meira',
    NOW(), NOW()), ('3452721', NULL, 'Porto Mauá', 'Porto Maua',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.57528, -54.66806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto mauá porto maua brazil br maua,mauá',
    NOW(), NOW()), ('3452722', NULL, 'Pôrto Matarazzo', 'Porto Matarazzo',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.93333, -50.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto matarazzo porto matarazzo brazil br',
    NOW(), NOW()), ('3452723', NULL, 'Pôrto Martins', 'Porto Martins',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.66667, -48.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto martins porto martins brazil br porto martins,pôrto martins',
    NOW(), NOW()), ('3452724', NULL, 'Pôrto Marrecas', 'Porto Marrecas',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.35, -51.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marrecas porto marrecas brazil br marrecas,porto,porto marrecas,porto das marrecas,pôrto marrecas,pôrto das marrecas',
    NOW(), NOW()), ('3452725', NULL, 'Pôrto Marques', 'Porto Marques',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.11667, -53.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marques porto marques brazil br',
    NOW(), NOW()), ('3452726', NULL, 'Pôrto Marinho', 'Porto Marinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.91667, -50.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marinho porto marinho brazil br',
    NOW(), NOW()), ('3452727', NULL, 'Pôrto Marinho', 'Porto Marinho',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.71667, -42.26667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marinho porto marinho brazil br porto marinho,pôrto marinho',
    NOW(), NOW()), ('3452728', NULL, 'Pôrto Maria', 'Porto Maria',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.46667, -52.88333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto maria porto maria brazil br',
    NOW(), NOW()), ('3452729', NULL, 'Pôrto Marcos Pereira', 'Porto Marcos Pereira',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.13333, -50.23333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marcos pereira porto marcos pereira brazil br',
    NOW(), NOW()), ('3452730', NULL, 'Pôrto Marcondes', 'Porto Marcondes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.53333, -52.03333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto marcondes porto marcondes brazil br',
    NOW(), NOW()), ('3452731', NULL, 'Pôrto Manuel Nunes', 'Porto Manuel Nunes',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.2, -50.75, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pôrto manuel nunes porto manuel nunes brazil br porto manuel nunes,porto nunes,pôrto manuel nunes,pôrto nunes',
    NOW(), NOW());