INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('6300793', NULL, 'Viru Viru International Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.64476, -63.13536, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'viru viru international airport viru viru international airport bolivia bo aeroport internacional viru viru,aeroport international de viru viru,aeroporto internacional viru viru,aeroporto internazionale viru viru,aeroporto viru viru,aeroportul international viru viru,aeroportul internațional viru viru,aeropuerto internacional viru viru,aéroport international de viru viru,bandar udara internasional viru viru,flughafen viru viru,lapangan terbang antarabangsa viru viru,luchthaven viru viru,maes awyr rhyngwladol viru viru,mezhdunarodnyj aehroport viru-viru,port lotniczy viru viru,slvr,san bay quoc te viru viru,santa cruz viru viru airport,sân bay quốc tế viru viru,vvi,viru viru international airport,viru viru nemzetkoezi repueloter,viru viru nemzetközi repülőtér,viru virun kansainvaelinen lentoasema,viru virun kansainvälinen lentoasema,wiru wiru antanka pampa,bilubilu gugjegonghang,birubiru guo ji kong gang,sheng ke lu si,международный аэропорт виру-виру,фурудгоҳи бин‌алмилалӣ виру виру,נמל התעופה הבין-לאומי וירו וירו,فرودگاه بین‌المللی ویرو ویرو,ビルビル国際空港,聖克魯斯,비루비루 국제공항',
    NOW(), NOW()), ('6300794', NULL, 'Yacuiba Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.96092, -63.65167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yacuiba airport yacuiba airport bolivia bo aeroportul yacuiba,aeropuerto de yacuiba,aeropuertu de yacuiba,byc,flughafen yacuiba,lapangan terbang yacuiba,maes awyr yacuiba,port lotniczy yacuiba,slya,san bay yacuiba,sân bay yacuíba,yacuiba,yacuiba airport,frwdgah yaswyyba,ya kui wa ji chang,yakuiba kong gang,фурудгоҳи иосуеҳибо,فرودگاه یاسوئیبا,ヤクイバ空港,亞奎瓦機場',
    NOW(), NOW()), ('7026834', NULL, 'Terminal Bimodal', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.78924, -63.16051, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'terminal bimodal terminal bimodal bolivia bo',
    NOW(), NOW()), ('7534465', NULL, 'Iquique Terminal', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.97871, -67.13174, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'iquique terminal iquique terminal bolivia bo',
    NOW(), NOW()), ('7559203', NULL, 'Transportista', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.83884, -63.17634, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'transportista transportista bolivia bo',
    NOW(), NOW()), ('7668467', NULL, 'Bermejo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -22.7733, -64.3129, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bermejo airport bermejo airport bolivia bo aeroportul bermejo,aeropuerto de bermejo,aeropuertu de bermejo,bjo,bermejo airport,lapangan terbang bermejo,maes awyr bermejo,port lotniczy bermejo,slbj,bei er mei huo ji chang,berumeho kong gang,frwdgah brmhw,фурудгоҳи брмҳу,فرودگاه برمهو,ベルメホ空港,貝爾梅霍機場',
    NOW(), NOW()), ('7730889', NULL, 'Baures Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.58333, -63.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'baures airport baures airport bolivia bo aeroportul baures,bvl,baures airport,baures flygfaelt,baures flygfält,slba',
    NOW(), NOW()), ('7731273', NULL, 'Monteagudo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.827, -63.961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'monteagudo airport monteagudo airport bolivia bo mhw,slag',
    NOW(), NOW()), ('7731290', NULL, 'San Matías Airport', 'San Matias Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.3392, -58.4019, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san matías airport san matias airport bolivia bo mqk,slti',
    NOW(), NOW()), ('7731417', NULL, 'Puerto Rico Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.10766, -67.55116, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto rico airport puerto rico airport bolivia bo pur,slpr',
    NOW(), NOW()), ('7731510', NULL, 'Santa Rosa De Yacuma Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.0662, -66.7868, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa rosa de yacuma airport santa rosa de yacuma airport bolivia bo slsr,srb,santa rosa airport',
    NOW(), NOW()), ('7731511', NULL, 'San Ramón Airport', 'San Ramon Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.2639, -64.6039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san ramón airport san ramon airport bolivia bo aeroportul san ramon,aeroportul san ramón,aeropuerto de san ramon,aeropuerto de san ramón,lapangan terbang san ramon,slra,srd,san ramon airport,san ramón airport,サン・ラモン空港',
    NOW(), NOW()), ('7731594', NULL, 'Capitán Av. Vidal Villagomez Toledo Airport', 'Capitan Av. Vidal Villagomez Toledo Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.4825, -64.0994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'capitán av. vidal villagomez toledo airport capitan av. vidal villagomez toledo airport bolivia bo aeropuerto capitan av. vidal villagomez toledo,aeropuerto capitán av. vidal villagomez toledo,slvg,vah',
    NOW(), NOW()), ('8521812', NULL, 'Porton', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.98889, -63.2621, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porton porton bolivia bo comunidad poton contagaita,porton',
    NOW(), NOW()), ('8986180', NULL, 'Ixiamas Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.76315, -68.13682, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ixiamas airport ixiamas airport bolivia bo aeroportul ixiamas,aeropuerto de ixiamas,ixiamas airport,slix,aerodrome d''ixiamas,aérodrome d''ixiamas,ikushiamasu kong gang,イクシアマス空港',
    NOW(), NOW()), ('8986234', NULL, 'Vuelta Grande Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.89989, -63.19385, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vuelta grande airport vuelta grande airport bolivia bo aeroportul vuelta grande,aeropuerto vuelta grande,slvu,vuelta grande airport,ブエルタ・グランデ空港',
    NOW(), NOW()), ('8987081', NULL, 'Bulo Bulo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.25429, -64.36458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bulo bulo airport bulo bulo airport bolivia bo slbb',
    NOW(), NOW()), ('8989445', NULL, 'Florida Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.60718, -61.19835, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'florida airport florida airport bolivia bo slfl',
    NOW(), NOW()), ('8989446', NULL, 'Cavinas Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.55017, -66.91233, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cavinas airport cavinas airport bolivia bo slcv',
    NOW(), NOW()), ('8989717', NULL, 'Laguna Loa Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.28383, -66.79199, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna loa airport laguna loa airport bolivia bo aeroportul laguna loa,laguna loa airport,slll,ラグナ・ロア空港',
    NOW(), NOW()), ('8989718', NULL, 'El Peru del Apere Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.6041, -65.63503, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el peru del apere airport el peru del apere airport bolivia bo slep',
    NOW(), NOW()), ('8989719', NULL, 'San Lorenzo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.4521, -65.68172, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san lorenzo airport san lorenzo airport bolivia bo sllz',
    NOW(), NOW()), ('8989720', NULL, 'Nuevo Mundo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.48043, -66.03337, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nuevo mundo airport nuevo mundo airport bolivia bo slno',
    NOW(), NOW()), ('8989721', NULL, 'Rincon del Tigre Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.20053, -58.16969, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rincon del tigre airport rincon del tigre airport bolivia bo slrx',
    NOW(), NOW()), ('8989722', NULL, 'Villa Elvira Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.64409, -64.44037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa elvira airport villa elvira airport bolivia bo slvv',
    NOW(), NOW()), ('8989723', NULL, 'Tiboy Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.81088, -66.25412, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiboy airport tiboy airport bolivia bo aeroportul tiboy,sltb,tiboy airport,tiboi kong gang,ティボイ空港',
    NOW(), NOW()), ('8989749', NULL, 'Blanca Flor Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.72607, -66.928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blanca flor airport blanca flor airport bolivia bo slbf',
    NOW(), NOW()), ('8990003', NULL, 'Caigua Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.13599, -63.75237, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caigua airport caigua airport bolivia bo aeroportul caigua,aeropuerto caigua,caigua airport,slci,kaigua kong gang,カイグア空港',
    NOW(), NOW()), ('8990014', NULL, 'Charagua Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.78568, -63.18945, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'charagua airport charagua airport bolivia bo aeroportul charagua,aeropuerto charagua,charagua airport,slcg,charagua kong gang,チャラグア空港',
    NOW(), NOW()), ('8990016', NULL, 'Chimore Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.98973, -65.14107, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chimore airport chimore airport bolivia bo aeropuerto chimore,cca,chimore airport,slhi',
    NOW(), NOW()), ('8990030', NULL, 'El Cocal Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.56997, -66.07179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el cocal airport el cocal airport bolivia bo slea',
    NOW(), NOW()), ('8990097', NULL, 'El Rancho Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.13774, -65.13294, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el rancho airport el rancho airport bolivia bo sleh',
    NOW(), NOW()), ('8990102', NULL, 'Espino Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.29672, -63.20932, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'espino airport espino airport bolivia bo slei',
    NOW(), NOW()), ('8990105', NULL, 'Flor de Oro Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.55444, -61.00491, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'flor de oro airport flor de oro airport bolivia bo aeroportul flor de oro,flor de oro airport,slfo,フロール・デ・オロ空港',
    NOW(), NOW()), ('8990109', NULL, 'Huacareta Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.39291, -64.01572, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'huacareta airport huacareta airport bolivia bo aeropuerto huacareta,slhc',
    NOW(), NOW()), ('8990113', NULL, 'Intiraymi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.80159, -67.43273, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'intiraymi airport intiraymi airport bolivia bo sliy',
    NOW(), NOW()), ('8990121', NULL, 'La Floresta Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.02811, -63.08884, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la floresta airport la floresta airport bolivia bo aeropuerto la floresta,slcd',
    NOW(), NOW()), ('8990183', NULL, 'Las Brizas Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.55838, -65.73107, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'las brizas airport las brizas airport bolivia bo aeroportul las brizas,las brizas airport,las brizas flygfaelt,las brizas flygfält,sllb,ラス・ブリサス空港',
    NOW(), NOW()), ('9019087', NULL, 'Mizque Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -17.93097, -65.37878, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mizque airport mizque airport bolivia bo slmz',
    NOW(), NOW()), ('9028143', NULL, 'Pitai Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.80796, -65.61984, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pitai airport pitai airport bolivia bo aeroportul pitai,pitai airport,slpi,pitai kong gang,ピータイ空港',
    NOW(), NOW()), ('9028573', NULL, 'Porvenir Velasco Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.98965, -61.54217, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porvenir velasco airport porvenir velasco airport bolivia bo aeroportul porvenir velasco,aeropuerto de porvenir velasco,porvenir velasco airport,slpn,ポルベニル・ベラスコ空港',
    NOW(), NOW()), ('9029614', NULL, 'Progreso Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.17885, -65.37537, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'progreso airport progreso airport bolivia bo aeroportul progreso,progreso airport,slpg,purogureso kong gang,プログレソ空港',
    NOW(), NOW()), ('9031059', NULL, 'Rancho Alegre Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -12.18414, -65.81072, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rancho alegre airport rancho alegre airport bolivia bo slrh',
    NOW(), NOW()), ('9031065', NULL, 'Refugio Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.76559, -61.03292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'refugio airport refugio airport bolivia bo aeroportul refugio,refugio airport,slrf,refuhio kong gang,レフヒオ空港',
    NOW(), NOW()), ('9034546', NULL, 'Rosal Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.96984, -65.6697, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rosal airport rosal airport bolivia bo slrl',
    NOW(), NOW()), ('9034555', NULL, 'Saipura Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.39536, -63.07165, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saipura airport saipura airport bolivia bo aeroportul saipura,slss,saipura airport,saipura kong gang,サイプラ空港',
    NOW(), NOW()), ('9034560', NULL, 'Sipuati Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.06561, -63.1095, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sipuati airport sipuati airport bolivia bo slsp',
    NOW(), NOW()), ('9034562', NULL, 'San Miguel de Gaser Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.90929, -66.12825, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san miguel de gaser airport san miguel de gaser airport bolivia bo aeroportul san miguel de gaser,slsg,san miguel de gaser airport,サン・ミゲル・デ・ハセル空港',
    NOW(), NOW()), ('9034569', NULL, 'Abapo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.63402, -62.93707, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'abapo airport abapo airport bolivia bo slab',
    NOW(), NOW()), ('9034663', NULL, 'Ventilla Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.17473, -67.16805, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ventilla airport ventilla airport bolivia bo aeroportul ventilla,aeropuerto de ventilla,sltl,ventilla airport,bentiya kong gang,ベンティーヤ空港',
    NOW(), NOW()), ('9034683', NULL, 'El Triunfo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.85325, -65.80441, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el triunfo airport el triunfo airport bolivia bo aeroportul el triunfo,el triunfo airport,slef,aerodrome de el triunfo,aérodrome de el triunfo,エル・トリウンフォ空港',
    NOW(), NOW()), ('9034684', NULL, 'Laguna Colorada Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -22.2735, -67.77376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna colorada airport laguna colorada airport bolivia bo sllc',
    NOW(), NOW()), ('9034685', NULL, 'Izozog Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.67025, -63.00234, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'izozog airport izozog airport bolivia bo aeroportul izozog,izozog airport,sliz,isosogu kong gang,イソソグ空港',
    NOW(), NOW()), ('9034732', NULL, 'El Desengaño Airport', 'El Desengano Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.27355, -65.43999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el desengaño airport el desengano airport bolivia bo sldn',
    NOW(), NOW()), ('9034734', NULL, 'Choreti Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.50967, -64.96696, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'choreti airport choreti airport bolivia bo aeroportul choreti,aeropuerto choreti,choreti airport,slct,choreti kong gang,チョレティ空港',
    NOW(), NOW()), ('9034735', NULL, 'El Porvenir Sur Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.7548, -63.20937, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el porvenir sur airport el porvenir sur airport bolivia bo slpw',
    NOW(), NOW()), ('9034738', NULL, 'Camiare Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.0823, -65.65812, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camiare airport camiare airport bolivia bo aeroportul camiare,camiare airport,slcm,kamiare kong gang,カミアレ空港',
    NOW(), NOW()), ('9034739', NULL, 'Itaguazurenda Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.78459, -63.08558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itaguazurenda airport itaguazurenda airport bolivia bo aeroportul itaguazurenda,aeropuerto itaguazurenda,itaguazurenda airport,slit,itauasurenda kong gang,イタウアスレンダ空港',
    NOW(), NOW()), ('9034743', NULL, 'Nieve Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.02248, -65.81197, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nieve airport nieve airport bolivia bo slnv',
    NOW(), NOW()), ('9034745', NULL, 'El Cairo Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.79078, -66.3215, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el cairo airport el cairo airport bolivia bo aeroportul el cairo,el cairo airport,slec,エル・カイロ空港',
    NOW(), NOW()), ('9034746', NULL, 'Cachascani Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.52687, -64.2342, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cachascani airport cachascani airport bolivia bo slha',
    NOW(), NOW()), ('9034747', NULL, 'San Juan Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.16387, -64.75849, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san juan airport san juan airport bolivia bo sljn',
    NOW(), NOW()), ('9034748', NULL, 'Irobi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.26898, -63.69182, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'irobi airport irobi airport bolivia bo aeroportul irobi,irobi airport,slir,irobi kong gang,イロビ空港',
    NOW(), NOW()), ('9034751', NULL, 'Josuani Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.10796, -66.17364, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'josuani airport josuani airport bolivia bo sljs',
    NOW(), NOW()), ('9034756', NULL, 'La Vertiente Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.28738, -63.29558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la vertiente airport la vertiente airport bolivia bo slvt',
    NOW(), NOW()), ('9034761', NULL, 'El Paraíso Airport', 'El Paraiso Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.40399, -65.87994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el paraíso airport el paraiso airport bolivia bo sleo',
    NOW(), NOW()), ('9034763', NULL, 'Taquipirenda Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -20.33702, -63.14083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taquipirenda airport taquipirenda airport bolivia bo aeroportul taquipirenda,slta,taquipirenda airport,takipirenda kong gang,タキピレンダ空港',
    NOW(), NOW()), ('9035116', NULL, 'La Esperanza Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.41725, -65.51774, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la esperanza airport la esperanza airport bolivia bo slez',
    NOW(), NOW()), ('9035117', NULL, 'El Salvador Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.49839, -66.76301, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el salvador airport el salvador airport bolivia bo slev',
    NOW(), NOW()), ('9035118', NULL, 'Florencia Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.68738, -65.53025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'florencia airport florencia airport bolivia bo aeroportul florencia,florencia airport,slfr,furorenshia kong gang,フロレンシア空港',
    NOW(), NOW()), ('9035120', NULL, 'Palmira Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.73741, -66.40967, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'palmira airport palmira airport bolivia bo aeroportul palmira,palmira airport,slpm,parumira kong gang,パルミラ空港',
    NOW(), NOW()), ('9035122', NULL, 'Santa Ana de Huachi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.49463, -67.44329, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa ana de huachi airport santa ana de huachi airport bolivia bo aeroportul santa ana de huachi,slsh,santa ana de huachi airport,サンタ・アナ・デ・ウアチ空港',
    NOW(), NOW()), ('9035124', NULL, 'Santa Rita Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.90872, -66.36251, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa rita airport santa rita airport bolivia bo aeroportul santa rita,slrt,santa rita airport,サンタ・リタ空港',
    NOW(), NOW()), ('9035125', NULL, 'Villazon Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -22.05152, -65.63803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villazon airport villazon airport bolivia bo aeroportul villazon,slvz,villazon airport,biryason kong gang,ビリャソン空港',
    NOW(), NOW()), ('9035127', NULL, 'Urusi Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.32365, -66.12804, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'urusi airport urusi airport bolivia bo aeroportul urusi,slus,urusi airport,urushi kong gang,ウルシ空港',
    NOW(), NOW()), ('9035128', NULL, 'San Francisco Naciff Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.75673, -64.47228, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san francisco naciff airport san francisco naciff airport bolivia bo aeroportul san francisco naciff,slzf,san francisco naciff airport,サン・フランシスコ・ナシフ空港',
    NOW(), NOW()), ('9035129', NULL, 'San Pedro del Rio Blanco Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.1876, -63.54801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san pedro del rio blanco airport san pedro del rio blanco airport bolivia bo slzj',
    NOW(), NOW()), ('9035130', NULL, 'Venecia Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.63641, -66.75031, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'venecia airport venecia airport bolivia bo aeroportul venecia,slve,venecia airport,beneshia kong gang,ベネシア空港',
    NOW(), NOW()), ('9035131', NULL, 'Tupiza Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.33944, -65.61275, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tupiza airport tupiza airport bolivia bo sltz',
    NOW(), NOW()), ('9035132', NULL, 'Tiguipa Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.00508, -63.30421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiguipa airport tiguipa airport bolivia bo slty',
    NOW(), NOW()), ('9035136', NULL, 'Santiago Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.229, -65.45058, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santiago airport santiago airport bolivia bo sltg',
    NOW(), NOW()), ('9035269', NULL, 'Angora Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.42837, -65.7918, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'angora airport angora airport bolivia bo aeroportul angora,aeropuerto de angora,angora airport,angora flygfaelt,angora flygfält,slan,angora kong gang,アンゴラ空港',
    NOW(), NOW()), ('9035275', NULL, 'Bella Unión Airport', 'Bella Union Airport',
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.62743, -65.27372, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bella unión airport bella union airport bolivia bo aeroporto bella union,aeroporto bella unión,aeroportul bella union,aeroportul bella unión,aeropuerto de bella union,aeropuerto de bella unión,bella union airport,bella unión airport,slbn,ベジャ・ウニオン空港',
    NOW(), NOW()), ('9035276', NULL, 'Bella Vista Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.86825, -66.33081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bella vista airport bella vista airport bolivia bo slbv',
    NOW(), NOW()), ('9035279', NULL, 'Buen Retiro Ballivian Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.91318, -66.56269, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buen retiro ballivian airport buen retiro ballivian airport bolivia bo aeroportul buen retiro ballivian,aeropuerto de buen retiro ballivian,aeropuerto de buen retiro ballivián,buen retiro ballivian airport,slbt,ブエン・レティロ・バリビアン空港',
    NOW(), NOW()), ('9035280', NULL, 'Buen Retiro Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.44469, -63.50278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'buen retiro airport buen retiro airport bolivia bo aeroportul buen retiro,buen retiro airport,slbr,ブエン・レティロ空港',
    NOW(), NOW()), ('9035654', NULL, 'Retiro Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.48682, -66.30773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'retiro airport retiro airport bolivia bo slrr',
    NOW(), NOW()), ('9035656', NULL, 'Yabog Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -18.65493, -63.13281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yabog airport yabog airport bolivia bo aeroportul yabog,maes awyr yabog,slyg,yabog airport',
    NOW(), NOW()), ('9035658', NULL, 'Villa Negrita Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.28214, -65.80266, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa negrita airport villa negrita airport bolivia bo aeroportul villa negrita,slvn,villa negrita airport,ビジャ・ネグリタ空港',
    NOW(), NOW()), ('9035745', NULL, 'San Carlos Gutierrez Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.56371, -65.52617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san carlos gutierrez airport san carlos gutierrez airport bolivia bo aeropuerto san carlos gutierrez,slsd',
    NOW(), NOW()), ('9035746', NULL, 'San Pedro Salvatierra Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -14.83716, -65.70335, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san pedro salvatierra airport san pedro salvatierra airport bolivia bo aeroportul san pedro salvatierra,slzb,san pedro salvatierra airport,サン・ペドロ・サルバティエラ空港',
    NOW(), NOW()), ('9036029', NULL, 'Huacaraje Airport', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -13.60591, -63.87928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'huacaraje airport huacaraje airport bolivia bo aeroportul huacaraje,bvk,huacaraje airport,slhj,uakarahe kong gang,wa ka la he ji chang,ウアカラヘ空港,瓦卡拉赫機場',
    NOW(), NOW()), ('9882982', NULL, 'La Terminal', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -21.54363, -64.72763, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'la terminal la terminal bolivia bo',
    NOW(), NOW()), ('10400331', NULL, 'Puerto Acosta Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.5, -69.16667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto acosta municipality puerto acosta municipality bolivia bo',
    NOW(), NOW()), ('10400341', NULL, 'Puerto Carabuco Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -15.58333, -69, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto carabuco municipality puerto carabuco municipality bolivia bo',
    NOW(), NOW()), ('10400500', NULL, 'Puerto Villarroel Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.9167, -64.75, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'puerto villarroel municipality puerto villarroel municipality bolivia bo',
    NOW(), NOW()), ('10400599', NULL, 'Puerto Perez Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -16.3333, -68.5833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto perez municipality puerto perez municipality bolivia bo',
    NOW(), NOW()), ('10400840', NULL, 'Puerto Rico Municipality', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -11.36667, -67.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto rico municipality puerto rico municipality bolivia bo',
    NOW(), NOW()), ('11138010', NULL, 'Portezuelo Armasaya', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.63872, -68.5968, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo armasaya portezuelo armasaya bolivia bo portezuelo armasaya',
    NOW(), NOW()), ('11140761', NULL, 'Hito XXXV', NULL,
    NULL, 'BO', 'Bolivia', NULL, NULL,
    -19.44086, -68.44047, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hito xxxv hito xxxv bolivia bo hito xxxv,portezuelo de la sierra de huilla',
    NOW(), NOW());