INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('8162027', NULL, 'Wilson River Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.3485, 152.78461, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wilson river sports ground wilson river sports ground australia au wilson river sports ground',
    NOW(), NOW()), ('8162032', NULL, 'The Bull Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3068, 148.229, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the bull paddock the bull paddock australia au the bull paddock',
    NOW(), NOW()), ('8162040', NULL, 'The Macquarie Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.9185, 151.7957, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the macquarie pier the macquarie pier australia au the macquarie pier',
    NOW(), NOW()), ('8162052', NULL, 'Woodport Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.443, 151.37759, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woodport park woodport park australia au woodport park',
    NOW(), NOW()), ('8162081', NULL, 'Tomaree Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7402, 152.11791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tomaree sports complex tomaree sports complex australia au tomaree sports complex',
    NOW(), NOW()), ('8162127', NULL, 'Tumbulgum Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.2763, 153.46291, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tumbulgum sportsground tumbulgum sportsground australia au tumbulgum sportsground',
    NOW(), NOW()), ('8162157', NULL, 'Toronto Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.0118, 151.5901, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'toronto sports ground toronto sports ground australia au toronto sports ground',
    NOW(), NOW()), ('8162175', NULL, 'Ted Burge Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8263, 150.9707, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ted burge sportsground ted burge sportsground australia au ted burge sportsground',
    NOW(), NOW()), ('8162288', NULL, 'Wyong Regional Sporting Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.2727, 151.4476, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wyong regional sporting complex wyong regional sporting complex australia au wyong regional sporting complex',
    NOW(), NOW()), ('8162401', NULL, 'Ulladulla Sports Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3652, 150.4637, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ulladulla sports park ulladulla sports park australia au ulladulla sports park',
    NOW(), NOW()), ('8162402', NULL, 'Shamrock Hill Sporting Fields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7746, 151.59261, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shamrock hill sporting fields shamrock hill sporting fields australia au shamrock hill sporting fields',
    NOW(), NOW()), ('8162466', NULL, 'Senate Road Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.18358, 137.99638, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senate road sports ground senate road sports ground australia au senate road sports ground',
    NOW(), NOW()), ('8162474', NULL, 'Wallaroo Sporting Club', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.93625, 137.62396, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wallaroo sporting club wallaroo sporting club australia au wallaroo sporting club',
    NOW(), NOW()), ('8162544', NULL, 'St Philips Sportsfields', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.87835, 138.61691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'st philips sportsfields st philips sportsfields australia au st philips sportsfields',
    NOW(), NOW()), ('8162680', NULL, 'University of Adelaide Sport Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.91496, 138.60275, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'university of adelaide sport field university of adelaide sport field australia au university of adelaide sport field',
    NOW(), NOW()), ('8162748', NULL, 'Yatala Harbor-Upper Spencer Gulf Aquatic Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.73929, 137.90112, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'yatala harbor-upper spencer gulf aquatic reserve yatala harbor-upper spencer gulf aquatic reserve australia au yatala harbor-upper spencer gulf aquatic reserve',
    NOW(), NOW()), ('8162769', NULL, 'University Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.9102, 138.60922, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'university sports field university sports field australia au university sports field',
    NOW(), NOW()), ('8162774', NULL, 'Tea Tree Gully Sports Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.82161, 138.7231, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tea tree gully sports area tea tree gully sports area australia au tea tree gully sports area',
    NOW(), NOW()), ('8162809', NULL, 'St Georges Sportsground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.90776, 138.67714, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'st georges sportsground st georges sportsground australia au st georges sportsground',
    NOW(), NOW()), ('8162863', NULL, 'Tubemakers Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.85503, 138.58693, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tubemakers sports ground tubemakers sports ground australia au tubemakers sports ground',
    NOW(), NOW()), ('8162898', NULL, 'Torrens Valley Sports Field', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.86846, 138.6929, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'torrens valley sports field torrens valley sports field australia au torrens valley sports field',
    NOW(), NOW()), ('8162972', NULL, 'South Burnie Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.06, 145.89999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south burnie sports ground south burnie sports ground australia au south burnie sports ground',
    NOW(), NOW()), ('8162973', NULL, 'South Hobart Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.89, 147.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south hobart sports ground south hobart sports ground australia au south hobart sports ground',
    NOW(), NOW()), ('8162974', NULL, 'Southport Lagoon Conservation Area', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.49, 146.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'southport lagoon conservation area southport lagoon conservation area australia au southport lagoon conservation area',
    NOW(), NOW()), ('8162986', NULL, 'St George Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.59, 147.11999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'st george sports ground st george sports ground australia au st george sports ground',
    NOW(), NOW()), ('8163055', NULL, 'Trial Harbour State Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.92, 145.17, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'trial harbour state reserve trial harbour state reserve australia au trial harbour state reserve',
    NOW(), NOW()), ('8163062', NULL, 'University Sports Grounds', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.9, 147.32001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'university sports grounds university sports grounds australia au university sports grounds',
    NOW(), NOW()), ('8163064', NULL, 'Upper Burnie Sports Ground', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.06, 145.89999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'upper burnie sports ground upper burnie sports ground australia au upper burnie sports ground',
    NOW(), NOW()), ('8163168', NULL, 'Western Port State Wildlife Reserve', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.23986, 145.29069, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'western port state wildlife reserve western port state wildlife reserve australia au western port state wildlife reserve',
    NOW(), NOW()), ('8163263', NULL, 'South Hedland Sports Complex', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.40171, 118.5908, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south hedland sports complex south hedland sports complex australia au south hedland sports complex',
    NOW(), NOW()), ('8163408', NULL, 'Vela-Luka Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.10944, 115.7939, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vela-luka park vela-luka park australia au vela-luka park',
    NOW(), NOW()), ('8164985', NULL, 'Mount Amarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9152, 150.1846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount amarina mount amarina australia au mount amarina',
    NOW(), NOW()), ('8166223', NULL, 'Illuka Peak', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.59101, 138.62823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'illuka peak illuka peak australia au illuka peak',
    NOW(), NOW()), ('8166387', NULL, 'East Portal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.22, 146.42999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east portal east portal australia au east portal',
    NOW(), NOW()), ('8166724', NULL, 'Mount Bendock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.1531, 148.94646, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount bendock mount bendock australia au mount bendock',
    NOW(), NOW()), ('8167450', NULL, 'Piallaway Paddock Mountains', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.1985, 150.5846, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piallaway paddock mountains piallaway paddock mountains australia au piallaway paddock mountains',
    NOW(), NOW()), ('8167453', NULL, 'Pieries Peak', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.2152, 151.30119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pieries peak pieries peak australia au pieries peak,pieries point',
    NOW(), NOW()), ('8168111', NULL, 'Mount Port Arthur', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.59694, 145.225, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount port arthur mount port arthur australia au mount port arthur',
    NOW(), NOW()), ('8168112', NULL, 'Mount Portwine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.85222, 147.2375, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount portwine mount portwine australia au mount portwine',
    NOW(), NOW()), ('8168625', NULL, 'West Portal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.19, 146.39999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west portal west portal australia au west portal',
    NOW(), NOW()), ('8169175', NULL, 'Braddocks Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.3201, 138.15984, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braddocks bridge braddocks bridge australia au braddocks bridge',
    NOW(), NOW()), ('8169212', NULL, 'Piers Richmond Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.86483, 138.66109, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piers richmond bridge piers richmond bridge australia au piers richmond bridge',
    NOW(), NOW()), ('8169230', NULL, 'Portuguese Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.68963, 138.98703, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portuguese bridge portuguese bridge australia au portuguese bridge',
    NOW(), NOW()), ('8169239', NULL, 'Swanport Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.14737, 139.30885, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'swanport bridge swanport bridge australia au swanport bridge,shi yun bo qiao,師運砵橋',
    NOW(), NOW()), ('8169409', NULL, 'Porters Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.5, 146.73, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters bridge porters bridge australia au porters bridge',
    NOW(), NOW()), ('8169656', NULL, 'Little Swanport River Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.33, 147.92999, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'little swanport river bridge little swanport river bridge australia au little swanport river bridge',
    NOW(), NOW()), ('8169797', NULL, 'Southport Rivulet Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.41, 146.91, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'southport rivulet bridge southport rivulet bridge australia au southport rivulet bridge',
    NOW(), NOW()), ('8169843', NULL, 'Wattle Paddock Creek Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.46, 147.92, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wattle paddock creek bridge wattle paddock creek bridge australia au wattle paddock creek bridge',
    NOW(), NOW()), ('8169844', NULL, 'Weaning Paddock Creek Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.54, 146.03, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'weaning paddock creek bridge weaning paddock creek bridge australia au weaning paddock creek bridge',
    NOW(), NOW()), ('8169991', NULL, 'Port Bouvard Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.60546, 115.6398, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port bouvard bridge port bouvard bridge australia au port bouvard bridge',
    NOW(), NOW()), ('8170384', NULL, 'Spiers Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.31042, 142.81985, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'spiers bridge spiers bridge australia au spiers bridge',
    NOW(), NOW()), ('8170489', NULL, 'Airport Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.61917, 116.68, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport bridge airport bridge australia au airport bridge',
    NOW(), NOW()), ('8170530', NULL, 'Cold Harbour Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.90599, 116.7915, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cold harbour bridge cold harbour bridge australia au cold harbour bridge',
    NOW(), NOW()), ('8171137', NULL, 'Braddock Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7152, 150.7012, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'braddock public school braddock public school australia au braddock public school',
    NOW(), NOW()), ('8171351', NULL, 'Five Dock Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8652, 151.1262, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'five dock public school five dock public school australia au five dock public school',
    NOW(), NOW()), ('8171387', NULL, 'Coffs Harbour High School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.3152, 153.1346, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour high school coffs harbour high school australia au coffs harbour high school',
    NOW(), NOW()), ('8171388', NULL, 'Coffs Harbour Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2985, 153.11791, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour public school coffs harbour public school australia au coffs harbour public school',
    NOW(), NOW()), ('8171389', NULL, 'Coffs Harbour Technical College', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.2985, 153.0179, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour technical college coffs harbour technical college australia au coffs harbour technical college',
    NOW(), NOW()), ('8171792', NULL, 'Harbord Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7652, 151.28461, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbord public school harbord public school australia au harbord public school',
    NOW(), NOW()), ('8171818', NULL, 'Iluka Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.3985, 153.3512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka public school iluka public school australia au iluka public school',
    NOW(), NOW()), ('8172240', NULL, 'Lower Portland Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4318, 150.8846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lower portland public school lower portland public school australia au lower portland public school',
    NOW(), NOW()), ('8172344', NULL, 'Coffs Harbour Learning Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.34799, 153.07148, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour learning centre coffs harbour learning centre australia au coffs harbour learning centre',
    NOW(), NOW()), ('8172811', NULL, 'Broken Bay Sport and Recreation Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.5652, 151.2512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'broken bay sport and recreation centre broken bay sport and recreation centre australia au broken bay sport and recreation centre',
    NOW(), NOW()), ('8172887', NULL, 'Docker River School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.87322, 129.08225, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'docker river school docker river school australia au docker river school',
    NOW(), NOW()), ('8173093', NULL, 'Beachport Primary School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.47996, 140.01125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beachport primary school beachport primary school australia au beachport primary school',
    NOW(), NOW()), ('8173350', NULL, 'Albany Secondary Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.99111, 117.8633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'albany secondary ed support centre albany secondary ed support centre australia au albany secondary ed support centre',
    NOW(), NOW()), ('8173364', NULL, 'Armadale Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.16194, 116.1142, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'armadale education support centre armadale education support centre australia au armadale education support centre',
    NOW(), NOW()), ('8173378', NULL, 'Avonvale Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.64556, 116.6608, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'avonvale education support centre avonvale education support centre australia au avonvale education support centre',
    NOW(), NOW()), ('8173412', NULL, 'Beldon Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.77444, 115.7572, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beldon education support centre beldon education support centre australia au beldon education support centre',
    NOW(), NOW()), ('8173418', NULL, 'Belridge Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.77028, 115.7633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belridge education support centre belridge education support centre australia au belridge education support centre',
    NOW(), NOW()), ('8173493', NULL, 'Canning Vale Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.07583, 115.9125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canning vale education support centre canning vale education support centre australia au canning vale education support centre',
    NOW(), NOW()), ('8173495', NULL, 'Cannington Community Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.01528, 115.9456, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cannington community education support centre cannington community education support centre australia au cannington community education support centre',
    NOW(), NOW()), ('8173517', NULL, 'Cassia Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.40944, 118.6078, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cassia education support centre cassia education support centre australia au cassia education support centre',
    NOW(), NOW()), ('8173548', NULL, 'Cloverdale Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.95917, 115.9361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cloverdale education support centre cloverdale education support centre australia au cloverdale education support centre',
    NOW(), NOW()), ('8173579', NULL, 'Creaney Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.80444, 115.7875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'creaney education support centre creaney education support centre australia au creaney education support centre',
    NOW(), NOW()), ('8173588', NULL, 'Cyril Jackson Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.9125, 115.9403, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cyril jackson education support centre cyril jackson education support centre australia au cyril jackson education support centre',
    NOW(), NOW()), ('8173596', NULL, 'Dampier Primary School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.66444, 116.7061, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier primary school dampier primary school australia au dampier primary school',
    NOW(), NOW()), ('8173640', NULL, 'East Victoria Park Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.97944, 115.9083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east victoria park ed support centre east victoria park ed support centre australia au east victoria park ed support centre',
    NOW(), NOW()), ('8173646', NULL, 'Eastern Goldfields Shs Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.76806, 121.4786, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eastern goldfields shs ed support centre eastern goldfields shs ed support centre australia au eastern goldfields shs ed support centre',
    NOW(), NOW()), ('8173728', NULL, 'Gwynne Park Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.16167, 115.9994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gwynne park education support centre gwynne park education support centre australia au gwynne park education support centre',
    NOW(), NOW()), ('8173775', NULL, 'Jandakot Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.13861, 115.8453, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jandakot ed support centre jandakot ed support centre australia au jandakot ed support centre',
    NOW(), NOW()), ('8173788', NULL, 'Joondalup Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.72361, 115.7608, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'joondalup ed support centre joondalup ed support centre australia au joondalup ed support centre',
    NOW(), NOW()), ('8173794', NULL, 'Kalamunda Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.97083, 116.0508, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalamunda education support centre kalamunda education support centre australia au kalamunda education support centre',
    NOW(), NOW()), ('8173811', NULL, 'Karratha Education Support Ctr', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.72833, 116.8589, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karratha education support ctr karratha education support ctr australia au karratha education support ctr',
    NOW(), NOW()), ('8173843', NULL, 'Koorana Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.34222, 115.7653, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'koorana education support centre koorana education support centre australia au koorana education support centre',
    NOW(), NOW()), ('8173866', NULL, 'Langford Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.04528, 115.9361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'langford education support centre langford education support centre australia au langford education support centre',
    NOW(), NOW()), ('8173872', NULL, 'Leda Education Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.26028, 115.8042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leda education support centre leda education support centre australia au leda education support centre',
    NOW(), NOW()), ('8173877', NULL, 'Leeming Shs Ed Support Centre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.07472, 115.8561, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leeming shs ed support centre leeming shs ed support centre australia au leeming shs ed support centre',
    NOW(), NOW()), ('8175158', NULL, 'The Hills Sports High School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7818, 150.9429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the hills sports high school the hills sports high school australia au the hills sports high school',
    NOW(), NOW()), ('8175267', NULL, 'Newport Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6485, 151.30119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport public school newport public school australia au newport public school',
    NOW(), NOW()), ('8175351', NULL, 'Matraville Sports High School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9652, 151.24291, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'matraville sports high school matraville sports high school australia au matraville sports high school',
    NOW(), NOW()), ('8175397', NULL, 'Middle Harbour Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.82323, 151.23354, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'middle harbour public school middle harbour public school australia au middle harbour public school',
    NOW(), NOW()), ('8175531', NULL, 'Napier Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.5152, 144.9512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier public school napier public school australia au napier public school,napier street public school',
    NOW(), NOW()), ('8175532', NULL, 'Napier Street Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.5152, 144.9512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier street public school napier street public school australia au napier street public school',
    NOW(), NOW()), ('8175572', NULL, 'Nords Wharf Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1318, 151.6012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nords wharf public school nords wharf public school australia au nords wharf public school',
    NOW(), NOW()), ('8175725', NULL, 'Port Kenny Special Rural School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.16543, 134.68428, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kenny special rural school port kenny special rural school australia au port kenny special rural school',
    NOW(), NOW()), ('8175751', NULL, 'Port Hacking High School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0318, 151.1012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hacking high school port hacking high school australia au port hacking high school',
    NOW(), NOW()), ('8175752', NULL, 'Port Kembla Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.4818, 150.90961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla public school port kembla public school australia au port kembla public school',
    NOW(), NOW()), ('8175753', NULL, 'Port Kembla High School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.4818, 150.9012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kembla high school port kembla high school australia au port kembla high school',
    NOW(), NOW()), ('8175754', NULL, 'Portland Lower Public School', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4318, 150.8846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland lower public school portland lower public school australia au portland lower public school',
    NOW(), NOW());