INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('2063036', NULL, 'Port Lincoln', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.72625, 135.87442, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port lincoln port lincoln australia au plo,port lincoln,port-linkol''n,pt lincoln,lin ken gang,poteulingkeon,potorinkan,порт-линкольн,порт-лінкольн,پورٹ لنکولن,პორტ-ლინკოლნი,ポートリンカーン,林肯港,포트링컨',
    NOW(), NOW()), ('2063037', NULL, 'Portland River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.5, 116.83333, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portland river portland river australia au portland,portland river',
    NOW(), NOW()), ('2063038', NULL, 'Port Kenny', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.16667, 134.7, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port kenny port kenny australia au port kenny',
    NOW(), NOW()), ('2063040', NULL, 'Port Julia', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66667, 137.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port julia port julia australia au port julia',
    NOW(), NOW()), ('2063041', NULL, 'Port Hughes', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.08333, 137.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hughes port hughes australia au port hughes',
    NOW(), NOW()), ('2063042', NULL, 'Port Hedland', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.31215, 118.61059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hedland port hedland australia au phe,port hedland,port khedland,port-gedlend,port-khedlend,poteuhedeullaendeu,potoheddorando,pwrt hdlnd,порт хедланд,порт-гедленд,порт-хедленд,פורט הדלנד,პორტ-ჰედლანდი,ポートヘッドランド,포트헤들랜드',
    NOW(), NOW()), ('2063044', NULL, 'Port Germein', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.02162, 138.00133, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port germein port germein australia au port germein',
    NOW(), NOW()), ('2063045', NULL, 'Porters Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.43333, 134.23333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters well porters well australia au',
    NOW(), NOW()), ('2063046', NULL, 'Porters Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.98333, 137.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters hill porters hill australia au',
    NOW(), NOW()), ('2063047', NULL, 'Porters Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.9, 130.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porters creek porters creek australia au',
    NOW(), NOW()), ('2063048', NULL, 'Porter Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.50249, 123.5268, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter hill porter hill australia au',
    NOW(), NOW()), ('2063049', NULL, 'Porter Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.74037, 135.88268, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter bay porter bay australia au porter bay',
    NOW(), NOW()), ('2063050', NULL, 'Mount Porter', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.635, 131.8203, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount porter mount porter australia au mount porter',
    NOW(), NOW()), ('2063051', NULL, 'Port Elliot', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.53017, 138.67922, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port elliot port elliot australia au port elliot',
    NOW(), NOW()), ('2063052', NULL, 'Port Davis Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.25, 137.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port davis creek port davis creek australia au',
    NOW(), NOW()), ('2063053', NULL, 'Port Clinton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.22429, 138.02055, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port clinton port clinton australia au',
    NOW(), NOW()), ('2063054', NULL, 'Port Broughton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6007, 137.93597, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port broughton port broughton australia au port broughton',
    NOW(), NOW()), ('2063055', NULL, 'Port Augusta West', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.48611, 137.75833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta west port augusta west australia au',
    NOW(), NOW()), ('2063056', NULL, 'Port Augusta', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.49597, 137.77281, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port augusta port augusta australia au haveno augusta,haveno aŭgusta,kurdnatta,pug,port augusta,port avgusta,port ogasta,port onkousta,port-agasta,port-avgusta,port-ogasta,portogasta,puerto augusta,ao gu si ta gang,phxr thx xkas ta,port agasta,port akasta,porta agasta,porta ogasta,poteuogeoseuta,potoogasuta,pwrt agwsta,πορτ ωγκούστα,порт августа,порт-августа,порт-агаста,порт-огаста,պորտ օգաստա,פורט אוגוסטה,ميناء أوغستا,ميناء اوجستا,پورت آگوستا,پورٹ آگستا,پورٹ آگسٹا، جنوبی آسٹریلیا,پۆرت ئۆگەستا,पोर्ट अगस्ता,पोर्ट ऑगस्टा,পোর্ট অগাস্টা,પોર્ટ ઑગસ્ટા,போர்ட் அகஸ்டா,పోర్ట్ అగస్టా,ಪೋರ್ಟ್ ಆಗಸ್ಟಾ,പോർട്ട് അഗസ്റ്റ,පෝර්ට් ඔගස්ටා,พอร์ทออกัสตา,პორტ-ოგასტა,ポートオーガスタ,奥古斯塔港,奧古斯塔港,포트오거스타',
    NOW(), NOW()), ('2063058', NULL, 'Port Adelaide River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.78333, 138.46667, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port adelaide river port adelaide river australia au port adelaide river,port river',
    NOW(), NOW()), ('2063059', NULL, 'Port Adelaide', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8462, 138.50302, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port adelaide port adelaide australia au port adelaide,پورٹ ایڈیلیڈ، جنوبی آسٹریلیا',
    NOW(), NOW()), ('2063171', NULL, 'Point Turton', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.95233, 137.35652, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point turton point turton australia au port turton',
    NOW(), NOW()), ('2063181', NULL, 'Point Davenport Shoal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.18333, 137.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point davenport shoal point davenport shoal australia au',
    NOW(), NOW()), ('2063420', NULL, 'Pierre Spring', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.24588, 121.0989, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pierre spring pierre spring australia au',
    NOW(), NOW()), ('2063421', NULL, 'Mount Pierre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.29414, 125.8738, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre mount pierre australia au',
    NOW(), NOW()), ('2063422', NULL, 'Piero Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.83815, 118.3614, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'piero well piero well australia au',
    NOW(), NOW()), ('2063423', NULL, 'Pieradutta Waterhole', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.78333, 136.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pieradutta waterhole pieradutta waterhole australia au',
    NOW(), NOW()), ('2063509', NULL, 'Petermarina Pool', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.78333, 119.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'petermarina pool petermarina pool australia au',
    NOW(), NOW()), ('2063630', NULL, 'Pelican Lagoon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.81249, 137.8016, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pelican lagoon pelican lagoon australia au pelican lagoon,port dache',
    NOW(), NOW()), ('2063697', NULL, 'Pear Creek Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.6167, 119.5661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pear creek well pear creek well australia au pear creek well,pier creek well',
    NOW(), NOW()), ('2063749', NULL, 'Port Patterson', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.61667, 130.43333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port patterson port patterson australia au',
    NOW(), NOW()), ('2064011', NULL, 'Oyster Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.9775, 117.95889, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'oyster harbour oyster harbour australia au oyster harbour',
    NOW(), NOW()), ('2064230', NULL, 'Old Napier Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.25, 124.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'old napier downs old napier downs australia au',
    NOW(), NOW()), ('2064833', NULL, 'Port Nelson', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.06869, 125.01532, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port nelson port nelson australia au',
    NOW(), NOW()), ('2064975', NULL, 'Napier Range', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.34806, 124.8444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier range napier range australia au napier range',
    NOW(), NOW()), ('2064976', NULL, 'Napier Peninsula', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.06667, 135.71667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier peninsula napier peninsula australia au napier peninsula',
    NOW(), NOW()), ('2064977', NULL, 'Napier Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.18333, 124.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier downs napier downs australia au',
    NOW(), NOW()), ('2064978', NULL, 'Napier Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83333, 118, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier creek napier creek australia au',
    NOW(), NOW()), ('2064979', NULL, 'Napier Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.34248, 124.6743, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier creek napier creek australia au',
    NOW(), NOW()), ('2064980', NULL, 'Napier Broome Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.0433, 126.6121, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier broome bay napier broome bay australia au napier broome bay',
    NOW(), NOW()), ('2064981', NULL, 'Napier Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.5227, 131.4828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier bay napier bay australia au napier bay',
    NOW(), NOW()), ('2064982', NULL, 'Point Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.95605, 135.91359, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point napier point napier australia au napier point,point napier',
    NOW(), NOW()), ('2064983', NULL, 'Mount Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.53583, 129.17, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount napier mount napier australia au mount napier',
    NOW(), NOW()), ('2064984', NULL, 'Napier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83333, 118, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier napier australia au',
    NOW(), NOW()), ('2065228', NULL, 'Murdock Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.98333, 138.91667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'murdock hill murdock hill australia au murdock hill',
    NOW(), NOW()), ('2065322', NULL, 'Mundoora Arm', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.61667, 137.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mundoora arm mundoora arm australia au mundoora arm,port broughton',
    NOW(), NOW()), ('2065549', NULL, 'Mount Riddoch', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.04112, 134.67257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount riddoch mount riddoch australia au mount riddoch,mount riddock,mount riddock homestead',
    NOW(), NOW()), ('2065553', NULL, 'Mount Pierre Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.33333, 125.95, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount pierre creek mount pierre creek australia au',
    NOW(), NOW()), ('2065633', NULL, 'Mount Dockrell Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.83333, 127.16667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount dockrell well mount dockrell well australia au',
    NOW(), NOW()), ('2065842', NULL, 'Moonta Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.03571, 137.54407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moonta bay moonta bay australia au moonta bay,port moonta',
    NOW(), NOW()), ('2066750', NULL, 'Port McArthur', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.78333, 136.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port mcarthur port mcarthur australia au',
    NOW(), NOW()), ('2066847', NULL, 'Mary Ann Haven', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.95, 120.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mary ann haven mary ann haven australia au hopetoun harbour,mary ann haven',
    NOW(), NOW()), ('2067330', NULL, 'Lynedoch Shoal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.01667, 130.81667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lynedoch shoal lynedoch shoal australia au lynedoch bank,lynedoch shoal,lynedock bank',
    NOW(), NOW()), ('2067675', NULL, 'Port Lincoln', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.7, 135.93333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln port lincoln australia au',
    NOW(), NOW()), ('2067826', NULL, 'Port Le Hunte', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.08333, 133.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port le hunte port le hunte australia au',
    NOW(), NOW()), ('2067929', NULL, 'Gulf Point Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.78829, 138.48584, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gulf point marina gulf point marina australia au',
    NOW(), NOW()), ('2067954', NULL, 'Port Langdon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.75, 136.78333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port langdon port langdon australia au',
    NOW(), NOW()), ('2068140', NULL, 'Kumarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.70534, 119.6039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kumarina kumarina australia au kumarina,kumarina mining centre',
    NOW(), NOW()), ('2068414', NULL, 'Kingston South East', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.83073, 139.8522, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kingston south east kingston south east australia au kingston,kingston se,kingston south east,kingston-saut-ist,port caroline,кингстон-саут-ист',
    NOW(), NOW()), ('2068630', NULL, 'Port Keats', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.08333, 129.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port keats port keats australia au',
    NOW(), NOW()), ('2069482', NULL, 'Port Hurd', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.65, 130.21667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hurd port hurd australia au fort hurd,port hurd',
    NOW(), NOW()), ('2069531', NULL, 'Port Hughes', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.05083, 117.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hughes port hughes australia au',
    NOW(), NOW()), ('2069717', NULL, 'Holdfast Bay Harbor', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.97509, 138.51116, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'holdfast bay harbor holdfast bay harbor australia au',
    NOW(), NOW()), ('2069790', NULL, 'Hillarys Boat Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.96667, 122.86667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hillarys boat harbour hillarys boat harbour australia au',
    NOW(), NOW()), ('2070092', NULL, 'Port Harding', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.06222, 117.65056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port harding port harding australia au',
    NOW(), NOW()), ('2070139', NULL, 'Hampton Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.66667, 116.7, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hampton harbour hampton harbour australia au',
    NOW(), NOW()), ('2070269', NULL, 'Gundockerta Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.11667, 122.76667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gundockerta hill gundockerta hill australia au',
    NOW(), NOW()), ('2070369', NULL, 'Port Grey', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.78333, 114.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port grey port grey australia au',
    NOW(), NOW()), ('2070395', NULL, 'Port Gregory', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.2, 114.23333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port gregory port gregory australia au',
    NOW(), NOW()), ('2070551', NULL, 'Gove Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.21667, 136.66667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gove harbour gove harbour australia au',
    NOW(), NOW()), ('2070779', NULL, 'Gnabberdocking', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.71667, 119.06667, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gnabberdocking gnabberdocking australia au',
    NOW(), NOW()), ('2070997', NULL, 'Geranium Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.9, 126.55, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'geranium harbour geranium harbour australia au',
    NOW(), NOW()), ('2071010', NULL, 'Port George IV', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.37706, 124.66618, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port george iv port george iv australia au port george iv,port george the fourth',
    NOW(), NOW()), ('2071206', NULL, 'Freycinet Estuary', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.41667, 113.66667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'freycinet estuary freycinet estuary australia au freycinet estuary,henri freycinet estuary,henri freycinet harbour',
    NOW(), NOW()), ('2071222', NULL, 'Fremantle Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.05167, 115.7408, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'fremantle harbour fremantle harbour australia au fremantle harbour',
    NOW(), NOW()), ('2071268', NULL, 'Franklin Harbor', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7172, 136.93803, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'franklin harbor franklin harbor australia au flinders lake,franklin harbor,franklin harbour',
    NOW(), NOW()), ('2071732', NULL, 'Port Eyre', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.98333, 132.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port eyre port eyre australia au',
    NOW(), NOW()), ('2071855', NULL, 'Port Essington (Historical)', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.36159, 132.15368, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port essington (historical) port essington (historical) australia au',
    NOW(), NOW()), ('2072105', NULL, 'Elimang Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.83333, 138.68333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'elimang well elimang well australia au',
    NOW(), NOW()), ('2072599', NULL, 'Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.55, 135.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port douglas port douglas australia au port douglas',
    NOW(), NOW()), ('2072729', NULL, 'Dockrell Reef', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.66667, 116.53333, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dockrell reef dockrell reef australia au',
    NOW(), NOW()), ('2072730', NULL, 'Dockety Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.71667, 139.13333, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dockety bay dockety bay australia au',
    NOW(), NOW()), ('2072731', NULL, 'Docker Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.55818, 128.79562, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'docker creek docker creek australia au docker creek,docker river,the docker',
    NOW(), NOW()), ('2072732', NULL, 'Mount Dockerell', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.8, 127.23333, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount dockerell mount dockerell australia au mount dockerell,mount dockrell',
    NOW(), NOW()), ('2072884', NULL, 'The Devonport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.45, 136.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the devonport the devonport australia au',
    NOW(), NOW()), ('2072947', NULL, 'Port Denison', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.26667, 114.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port denison port denison australia au port denison',
    NOW(), NOW()), ('2072950', NULL, 'Port Denison', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.27367, 114.92068, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port denison port denison australia au denison,port denison',
    NOW(), NOW()), ('2073105', NULL, 'Davenport River', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.65651, 132.67892, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport river davenport river australia au',
    NOW(), NOW()), ('2073106', NULL, 'Davenport Range', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.78333, 134.8, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport range davenport range australia au davenport,davenport range,khrebet davenport,давенпорт,хребет давенпорт',
    NOW(), NOW()), ('2073107', NULL, 'Davenport Hills', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.8, 129.31667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport hills davenport hills australia au',
    NOW(), NOW()), ('2073108', NULL, 'Point Davenport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.16408, 137.33956, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point davenport point davenport australia au point davenport',
    NOW(), NOW()), ('2073109', NULL, 'Mount Davenport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.25719, 131.31523, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount davenport mount davenport australia au mount davenport',
    NOW(), NOW()), ('2073110', NULL, 'Mount Davenport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.3555, 130.77347, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount davenport mount davenport australia au',
    NOW(), NOW()), ('2073123', NULL, 'Port Darwin', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.49574, 130.81395, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port darwin port darwin australia au',
    NOW(), NOW()), ('2073124', NULL, 'Darwin', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.46113, 130.84185, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'darwin darwin australia au drw,daarwin,darvin,darvina,darvinas,darvino,darwin,dārvina,ntargouin,palmerston,port darwin,da er wen,da er wen gang,dar win,dara''u''ina,daravina,darvina,darvini,darwyn,dauin,dawin,drwwyn,tarvin,ντάργουιν,дарвин,дарвін,դարվին,דארווין,דרווין,داروين,داروین,داروین، قوزئی توپراق‌لاری,ڈارون,डार्विन,ডারউইন,ਡਾਰਵਿਨ,டார்வின்,ഡാർവിൻ,ดาร์วิน,ဒါဝင်မြို့,დარვინი,ダーウィン,达尔文,达尔文港,다윈',
    NOW(), NOW()), ('2073195', NULL, 'Dampiers Monument', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.12554, 123.4407, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampiers monument dampiers monument australia au dampiers monument',
    NOW(), NOW()), ('2073196', NULL, 'Dampier Reef', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.36052, 113.07599, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier reef dampier reef australia au dampier reef',
    NOW(), NOW()), ('2073197', NULL, 'Dampier Land', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.5, 122.91667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier land dampier land australia au dampier land',
    NOW(), NOW()), ('2073198', NULL, 'Dampier Downs', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.4, 123.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier downs dampier downs australia au',
    NOW(), NOW()), ('2073199', NULL, 'Dampier Archipelago', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.53333, 116.6, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier archipelago dampier archipelago australia au dampier archipelago',
    NOW(), NOW());