INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('6510212', NULL, 'Comfort Inn The Pier', 'COMFORT INN THE PIER',
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.1, 146.8333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn the pier comfort inn the pier australia au',
    NOW(), NOW()), ('6510317', NULL, 'Comfort Inn Port Arthur', 'COMFORT INN PORT ARTHUR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -43.15, 147.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn port arthur comfort inn port arthur australia au',
    NOW(), NOW()), ('6510609', NULL, 'Comfort Inn Haven Marina', 'COMFORT INN HAVEN MARINA',
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.9833, 138.5166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn haven marina comfort inn haven marina australia au',
    NOW(), NOW()), ('6510857', NULL, 'Peppers Delgany Portsea', 'PEPPERS DELGANY PORTSEA',
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.3166, 144.7166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'peppers delgany portsea peppers delgany portsea australia au',
    NOW(), NOW()), ('6510910', NULL, 'Harbourside Apartments', 'HARBOURSIDE APARTMENTS',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.85, 151.2166, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbourside apartments harbourside apartments australia au',
    NOW(), NOW()), ('6510957', NULL, 'Marina Quays Intl Ex Chancellor', 'MARINA QUAYS INTL EX CHANCELLOR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -25, 134, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina quays intl ex chancellor marina quays intl ex chancellor australia au',
    NOW(), NOW()), ('6511762', NULL, 'Comfort Inn Port Fairy', 'COMFORT INN PORT FAIRY',
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.38588, 142.23669, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn port fairy comfort inn port fairy australia au',
    NOW(), NOW()), ('6511766', NULL, 'Comfort Inn Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4833, 145.4666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn port douglas comfort inn port douglas australia au',
    NOW(), NOW()), ('6512067', NULL, 'Airport Hotel And Convention C', 'AIRPORT HOTEL AND CONVENTION C',
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.6735, 144.8883, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport hotel and convention c airport hotel and convention c australia au',
    NOW(), NOW()), ('6513350', NULL, 'Quality Inn Airport Internation', 'QUALITY INN AIRPORT INTERNATION',
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.4053, 153.1015, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quality inn airport internation quality inn airport internation australia au',
    NOW(), NOW()), ('6513354', NULL, 'Comfort Inn Port Augusta', 'COMFORT INN PORT AUGUSTA',
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.5, 137.7666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn port augusta comfort inn port augusta australia au',
    NOW(), NOW()), ('6514044', NULL, 'Comfort Inn Port Campbell', 'COMFORT INN PORT CAMPBELL',
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.6166, 142.9833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn port campbell comfort inn port campbell australia au',
    NOW(), NOW()), ('6514243', NULL, 'Comfort Inn Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.3499, 149.2333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn airport comfort inn airport australia au',
    NOW(), NOW()), ('6515477', NULL, 'Comfort Inn Airport Admiralty', 'COMFORT INN AIRPORT ADMIRALTY',
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.4392, 153.0551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comfort inn airport admiralty comfort inn airport admiralty australia au',
    NOW(), NOW()), ('6515481', NULL, 'North Sydney Harbourview Hotel', 'NORTH SYDNEY HARBOURVIEW HOTEL',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.85, 151.2166, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'north sydney harbourview hotel north sydney harbourview hotel australia au',
    NOW(), NOW()), ('6516025', NULL, 'Country Comfort Port Macquair', 'COUNTRY COMFORT PORT MACQUAIR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4333, 152.9166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'country comfort port macquair country comfort port macquair australia au',
    NOW(), NOW()), ('6517053', NULL, 'Mercure Hotel Sydney Airport', 'MERCURE HOTEL SYDNEY AIRPORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.93442, 151.15607, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mercure hotel sydney airport mercure hotel sydney airport australia au',
    NOW(), NOW()), ('6523466', NULL, 'Grand Mercure Docklands', 'GRAND MERCURE DOCKLANDS',
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.8151, 144.9369, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand mercure docklands grand mercure docklands australia au',
    NOW(), NOW()), ('6523939', NULL, 'Rendezvous Reef Resort Port Dou', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4833, 145.4666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rendezvous reef resort port dou rendezvous reef resort port dou australia au',
    NOW(), NOW()), ('6524832', NULL, 'Darwin Airport Resort', 'DARWIN AIRPORT RESORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.4556, 130.8355, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'darwin airport resort darwin airport resort australia au',
    NOW(), NOW()), ('6524933', NULL, 'Dockside Central Apartment Ht', 'DOCKSIDE CENTRAL APARTMENT HT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.441, 153.1131, 'Large', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'dockside central apartment ht dockside central apartment ht australia au',
    NOW(), NOW()), ('6525226', NULL, 'Elan Riverside Pier Hotel', 'ELAN RIVERSIDE PIER HOTEL',
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.9333, 115.8333, 'Small', 'River (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'elan riverside pier hotel elan riverside pier hotel australia au',
    NOW(), NOW()), ('6525949', NULL, 'Best Western Fawkner Airport', 'BEST WESTERN FAWKNER AIRPORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.72837, 144.96366, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'best western fawkner airport best western fawkner airport australia au',
    NOW(), NOW()), ('6526970', NULL, 'Clarion Hotel Mackay Marina', 'CLARION HOTEL MACKAY MARINA',
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.15, 149.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clarion hotel mackay marina clarion hotel mackay marina australia au',
    NOW(), NOW()), ('6527297', NULL, 'Best Western Harbour City Mtl', 'BEST WESTERN HARBOUR CITY MTL',
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.85, 151.25, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'best western harbour city mtl best western harbour city mtl australia au',
    NOW(), NOW()), ('6527610', NULL, 'Quality Inn Airport Heritage', 'QUALITY INN AIRPORT HERITAGE',
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.4392, 153.0551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quality inn airport heritage quality inn airport heritage australia au',
    NOW(), NOW()), ('6527784', NULL, 'Port Douglas Plantation Resort', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4833, 145.4666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port douglas plantation resort port douglas plantation resort australia au',
    NOW(), NOW()), ('6528619', NULL, 'Quality Inn Port Macquarie', 'QUALITY INN PORT MACQUARIE',
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.4333, 152.9166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quality inn port macquarie quality inn port macquarie australia au',
    NOW(), NOW()), ('6529454', NULL, 'Quest On Dixon Darling Harbour', 'QUEST ON DIXON DARLING HARBOUR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8676, 151.2096, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'quest on dixon darling harbour quest on dixon darling harbour australia au',
    NOW(), NOW()), ('6529525', NULL, 'Quest Harbour Village Apt', 'QUEST HARBOUR VILLAGE APT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.04999, 115.7666, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'quest harbour village apt quest harbour village apt australia au',
    NOW(), NOW()), ('6531182', NULL, 'Best Western Airport Hacienda', 'BEST WESTERN AIRPORT HACIENDA',
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.5, 153.0166, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'best western airport hacienda best western airport hacienda australia au',
    NOW(), NOW()), ('6615560', NULL, 'Docklands Stadium', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.81636, 144.94761, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'docklands stadium docklands stadium australia au colonial stadium,docklands stadium,etihad stadium,marvel stadium,telstra dome,the dome',
    NOW(), NOW()), ('6615597', NULL, 'Cruising Yacht Club of Australia', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87436, 151.23377, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cruising yacht club of australia cruising yacht club of australia australia au cyc,cyc  rushcutters  sydney  nsw,cyca',
    NOW(), NOW()), ('6619100', NULL, 'Darling Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.86847, 151.20034, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'darling harbour darling harbour australia au puerto darling,da ling gang,dalling habeo,daringuhaba,ダーリングハーバー,打令港,達令港,달링 하버',
    NOW(), NOW()), ('6619257', NULL, 'Manly Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.80019, 151.28466, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manly wharf manly wharf australia au',
    NOW(), NOW()), ('6619624', NULL, 'Newport Lakes', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.83833, 144.87345, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport lakes newport lakes australia au',
    NOW(), NOW()), ('6619636', NULL, 'Newport College of Tafe', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.84951, 144.87765, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'newport college of tafe newport college of tafe australia au',
    NOW(), NOW()), ('6621339', NULL, 'Cams Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.12612, 151.62094, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cams wharf cams wharf australia au',
    NOW(), NOW()), ('6639630', NULL, 'Hobart Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.8357, 147.5069, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hobart airport hobart airport australia au',
    NOW(), NOW()), ('6693764', NULL, 'Yarra Bank Heliport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.82226, 144.95678, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yarra bank heliport yarra bank heliport australia au batman park helipad,kah,ybpk,yarra bank heliport',
    NOW(), NOW()), ('6697153', NULL, 'Iluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.73554, 115.73058, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka iluka australia au',
    NOW(), NOW()), ('6940992', NULL, 'Jandakot Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.09377, 115.8783, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jandakot airport jandakot airport australia au jad,ypjt,frwdgah jandakwt,فرودگاه جانداکوت',
    NOW(), NOW()), ('6949405', NULL, 'Darling Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8723, 151.199, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'darling harbour darling harbour australia au',
    NOW(), NOW()), ('6949406', NULL, 'Finger Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8675, 151.221, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'finger wharf finger wharf australia au finger wharf,pristan'' zaliva vullumulu,fngr warf,ping-geo seonchagjang,shou zhi ma tou,пристань залива вуллумулу,فنگر وارف,フィンガー・ワーフ,手指码头,手指碼頭,핑거 선착장',
    NOW(), NOW()), ('6949422', NULL, 'Sydney Harbour National Park', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.81465, 151.29577, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'sydney harbour national park sydney harbour national park australia au',
    NOW(), NOW()), ('6954012', NULL, 'clarion suites southern cross on harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.86762, 151.2101, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'clarion suites southern cross on harbour clarion suites southern cross on harbour australia au',
    NOW(), NOW()), ('6954019', NULL, 'gateway devonport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.17842, 146.35867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gateway devonport gateway devonport australia au',
    NOW(), NOW()), ('6954024', NULL, 'ibis sydney king street wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.86571, 151.20389, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ibis sydney king street wharf ibis sydney king street wharf australia au',
    NOW(), NOW()), ('6954143', NULL, 'shangri la the marina cairns', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.99915, 145.67128, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shangri la the marina cairns shangri la the marina cairns australia au',
    NOW(), NOW()), ('6954231', NULL, 'crowne plaza darling harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87406, 151.2034, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'crowne plaza darling harbour crowne plaza darling harbour australia au',
    NOW(), NOW()), ('6954268', NULL, 'grand mercure darling harbour apartments', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.51468, 148.80838, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand mercure darling harbour apartments grand mercure darling harbour apartments australia au',
    NOW(), NOW()), ('6954275', NULL, 'holiday inn darling harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87733, 151.20331, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'holiday inn darling harbour holiday inn darling harbour australia au',
    NOW(), NOW()), ('6954278', NULL, 'holiday inn sydney airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.92648, 151.18735, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'holiday inn sydney airport holiday inn sydney airport australia au',
    NOW(), NOW()), ('6954949', NULL, 'mercure hotel harbourside cairns', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.90475, 145.68615, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mercure hotel harbourside cairns mercure hotel harbourside cairns australia au',
    NOW(), NOW()), ('6954953', NULL, 'metro apartments on darling harbour sydney', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.86867, 151.20377, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'metro apartments on darling harbour sydney metro apartments on darling harbour sydney australia au',
    NOW(), NOW()), ('6955005', NULL, 'park regis piermonde', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.92792, 145.77689, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'park regis piermonde park regis piermonde australia au',
    NOW(), NOW()), ('6955008', NULL, 'port douglas retreat', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4847, 145.46316, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port douglas retreat port douglas retreat australia au',
    NOW(), NOW()), ('6955017', NULL, 'quality hotel airport international', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.43815, 153.06789, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'quality hotel airport international quality hotel airport international australia au',
    NOW(), NOW()), ('6955019', NULL, 'quality hotel melbourne airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.69486, 144.88111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quality hotel melbourne airport quality hotel melbourne airport australia au',
    NOW(), NOW()), ('6955022', NULL, 'quality inn suites port macquarie', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.43121, 152.8969, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quality inn suites port macquarie quality inn suites port macquarie australia au',
    NOW(), NOW()), ('6955035', NULL, 'rydges sabaya resort port douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.51534, 145.46574, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rydges sabaya resort port douglas rydges sabaya resort port douglas australia au',
    NOW(), NOW()), ('6955048', NULL, 'stamford plaza sydney airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.94668, 151.18392, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stamford plaza sydney airport stamford plaza sydney airport australia au',
    NOW(), NOW()), ('6955055', NULL, 'the harbour lights cairns', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.92083, 145.78038, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'the harbour lights cairns the harbour lights cairns australia au',
    NOW(), NOW()), ('6955061', NULL, 'the sebel harbourside kiama', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.66867, 150.85608, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'the sebel harbourside kiama the sebel harbourside kiama australia au',
    NOW(), NOW()), ('7283691', NULL, 'HVDC Basslink - Giffard Cable Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.40617, 147.06847, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hvdc basslink - giffard cable terminal hvdc basslink - giffard cable terminal australia au',
    NOW(), NOW()), ('7521471', NULL, 'Docklands', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.8149, 144.95052, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'docklands docklands australia au doklends,mo er ben bin hai gang qu,доклендс,墨爾本濱海港區',
    NOW(), NOW()), ('7626288', NULL, 'The Reef Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.48422, 145.46022, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the reef marina the reef marina australia au',
    NOW(), NOW()), ('7668679', NULL, 'Alpha Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.6461, 146.584, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alpha airport alpha airport australia au abh,aeroportul alpha,alpha airport,alpha lufthavn,lapangan terbang alpha,yaph,a er fa ji chang,aeroport d''alpha,aeroporto di alpha,aeropuerto de alpha,aéroport d''alpha,frwdgah alfa,фурудгоҳи алфа,فرودگاه آلفا,阿爾法機場',
    NOW(), NOW()), ('7668680', NULL, 'Ararat Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.3094, 142.989, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ararat airport ararat airport australia au ary,ararat,ararat airport,ararat airport,flughafen ararat,lapangan terbang ararat,yara,aeroport d''ararat,aeroporto di ararat,aéroport d''ararat,frwdgah ararat,ya la la te ji chang,арарат,фурудгоҳи оророт,فرودگاه آرارات,فڕۆکەخانەی ئارارات,亞拉拉特機場',
    NOW(), NOW()), ('7668681', NULL, 'Argyle Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.6369, 128.451, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'argyle airport argyle airport australia au aeroport de argyle,aeroportul argyle,aeropuerto de argyle,argajl,argyle airport,aéroport de argyle,bandar udara argyle,gyl,lapangan terbang argyle,yarg,frwdgah argyl,аргайл,фурудгоҳи оргил,فرودگاه آرگیل',
    NOW(), NOW()), ('7668683', NULL, 'Aurukun Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.3539, 141.72099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aurukun airport aurukun airport australia au auu,aeroport d''aurukun,aeroportul aurukun,aurukun airport,aéroport d''aurukun,lapangan terbang aurukun,port lotniczy aurukun,yaur,frwdgah awrwkwn,orukun kong gang,ou lu kun ji chang,фурудгоҳи оврукун,فرودگاه اوروکون,オールクン空港,歐魯昆機場',
    NOW(), NOW()), ('7668684', NULL, 'Blackall Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.4298, 145.43319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blackall airport blackall airport australia au bkq,blackall airport,ybck',
    NOW(), NOW()), ('7668685', NULL, 'Broken Hill Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.0014, 141.472, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'broken hill airport broken hill airport australia au bhq,ybhi',
    NOW(), NOW()), ('7668686', NULL, 'Bourke Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.0392, 145.952, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bourke airport bourke airport australia au aeroport de bourke,aeroportul bourke,aéroport de bourke,brk,bandar udara bourke,bourke,bourke airport,bourke ji chang,bourke機場,flughafen bourke,lapangan terbang bourke,ybke,aeroporto di bourke,frwdgah bwrk,фурудгоҳи бурк,فرودگاه بورک',
    NOW(), NOW()), ('7668687', NULL, 'Benalla Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.5519, 146.007, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'benalla airport benalla airport australia au aeroporto de benalla,aeroportul benalla,bln,benalla airport,flughafen benalla,lapangan terbang benalla,ybla,aeroport de benalla,aeroporto di benalla,aeropuerto de benalla,aéroport de benalla,bei na la ji chang,benara kong gang,frwdgah bnala,фурудгоҳи беналла,فرودگاه بنالا,ベナラ空港,貝納拉機場',
    NOW(), NOW()), ('7668688', NULL, 'Bairnsdale Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.8875, 147.56799, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bairnsdale airport bairnsdale airport australia au aeroportul bairnsdale,bsj,bairnsdale,bairnsdale airport,bairnsdale ji chang,bairnsdale機場,flughafen bairnsdale,lapangan terbang bairnsdale,ybns,aeroporto di bairnsdale,frwdgah bayrnsdal,фурудгоҳи байрнсдейл,فرودگاه بایرنسدال',
    NOW(), NOW()), ('7668689', NULL, 'Balranald Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.6236, 143.578, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'balranald airport balranald airport australia au bzd,ybrn',
    NOW(), NOW()), ('7668690', NULL, 'Brewarrina Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.9739, 146.817, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brewarrina airport brewarrina airport australia au aeroportul brewarrina,bwq,bandar udara brewarrina,brewarrina,brewarrina airport,flughafen brewarrina,lapangan terbang brewarrina,ybrw,aeroport de brewarrina,aeroporto di brewarrina,aéroport de brewarrina,bu lei wo li na ji chang,frwdgah brwaryna,фурудгоҳи бреварина,فرودگاه بروارینا,佈雷沃里納機場,布雷沃里納機場',
    NOW(), NOW()), ('7668691', NULL, 'Sunshine Coast Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.6033, 153.091, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sunshine coast airport sunshine coast airport australia au aehroport sanshajn-kost,aeroporto de sunshine coast,aeroportul sunshine coast,lapangan terbang maroochydore/sunshine coast,mcy,maroochydore airport,sunshine coast airport,ybsu,aerodrome de sunshine coast,aérodrome de sunshine coast,frwdgah sanshayn kwst,mtar sn shayn kwst,port lotniczy sunshine coast,seonsyainkoseuteu gonghang,yang guang hai an ji chang,аэропорт саншайн-кост,фурудгоҳи соншоин куст,فرودگاه سانشاین کوست,مطار صن شاين كوست,サンシャイン・コースト空港,陽光海岸機場,선샤인코스트 공항',
    NOW(), NOW()), ('7668692', NULL, 'Bathurst Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -11.76822, 130.61779, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bathurst island airport bathurst island airport australia au brt,bathurst island airport,ybti',
    NOW(), NOW()), ('7668693', NULL, 'Blackwater Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.6031, 148.80701, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blackwater airport blackwater airport australia au aeroportul blackwater,blt,blackwater airport,lapangan terbang blackwater,maes awyr blackwater,ybtr,frwdgah blkwtr,hei shui ji chang,фурудгоҳи блкутр,فرودگاه بلکوتر,黑水機場',
    NOW(), NOW()), ('7668694', NULL, 'Bundaberg Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.9039, 152.319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bundaberg airport bundaberg airport australia au bdb,ybud',
    NOW(), NOW()), ('7668695', NULL, 'Carnarvon Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.8806, 113.672, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carnarvon airport carnarvon airport australia au aeroportul carnarvon,cvq,carnarvon airport,karnarvon,lapangan terbang carnarvon,ycar,aeroport de carnarvon,aéroport de carnarvon,frwdgah karnarwn,jia na fen ji chang,карнарвон,فرودگاه کارنارون,加拿分機場',
    NOW(), NOW()), ('7668696', NULL, 'Cobar Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.5383, 145.79401, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cobar airport cobar airport australia au aeroportul cobar,caz,cobar,cobar airport,flughafen cobar,lapangan terbang cobar,ycba,aeroport de cobar,aeroporto di cobar,aéroport de cobar,frwdgah kwbar,ke ba ji chang,koba gonghang,koba kong gang,фурудгоҳи кубор,فرودگاه کوبار,コーバー空港,科巴機場,코바 공항',
    NOW(), NOW()), ('7668697', NULL, 'Coober Pedy Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.04, 134.72099, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coober pedy airport coober pedy airport australia au aeroportul coober pedy,cpd,coober pedy,coober pedy airport,flugplatz coober pedy,kuber-pedi,lapangan terbang coober pedy,ycbp,aeroport coober pedy,aeroporto di coober pedy,aéroport coober pedy,frwdgah kwbr pdy,ku bo pei de ji chang,kubapedi kong gang,кубер-педи,кубер-педі,фурудгоҳи кубр пди,فرودگاه کوبر پدی,クーバーペディ空港,庫伯佩地機場',
    NOW(), NOW()), ('7668698', NULL, 'Chinchilla Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.775, 150.617, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chinchilla airport chinchilla airport australia au ccl,ycca',
    NOW(), NOW()), ('7668699', NULL, 'Cloncurry Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.6686, 140.504, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cloncurry airport cloncurry airport australia au aeroportul cloncurry,bandar udara cloncurry,cnj,cloncurry airport,lapangan terbang cloncurry,maes awyr cloncurry,port lotniczy cloncurry,yccy,aeroport de cloncurry,aéroport de cloncurry,frwdgah klwnkary,ke lang ke li ji chang,kuronkari kong gang,фурудгоҳи клункори,فرودگاه کلونکاری,クロンカリー空港,克朗克里机场,克朗克里機場',
    NOW(), NOW()), ('7668700', NULL, 'Charters Towers Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.0431, 146.27299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'charters towers airport charters towers airport australia au aeroportul charters towers,cxt,charters towers airport,lapangan terbang charters towers,port lotniczy charters towers,ycht,cha te si bao ji chang,chatazutawazu kong gang,frwdgah chartr tawr,фурудгоҳи чортр товр,فرودگاه چارتر تاور,チャーターズタワーズ空港,查特斯堡機場',
    NOW(), NOW()), ('7668701', NULL, 'Cooktown Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.4447, 145.18401, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cooktown airport cooktown airport australia au aeroport de cooktown,aeroportul cooktown,aéroport de cooktown,bandar udara cooktown,ctn,cooktown airport,lapangan terbang cooktown,port lotniczy cooktown,yckn,frwdgah kwktawn,ku ke dui ji chang,kukkutaun kong gang,фурудгоҳи куктовн,فرودگاه کوکتاون,クックタウン空港,庫克敦機場',
    NOW(), NOW()), ('7668702', NULL, 'Coonamble Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.9833, 148.37601, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coonamble airport coonamble airport australia au aeroportul coonamble,cnb,coonamble,coonamble airport,flughafen coonamble,lapangan terbang coonamble,ycnm,aeroport de coonamble,aeroporto di coonamble,aéroport de coonamble,frwdgah kwnambl,ku nan bu er ji chang,ku nan bu lin ji chang,kunanburu kong gang,фурудгоҳи куномбл,فرودگاه کونامبل,クーナンブル空港,庫南布林機場,庫南布爾機場',
    NOW(), NOW()), ('7668703', NULL, 'Cessnock Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7875, 151.342, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cessnock airport cessnock airport australia au aeroportul cessnock,ces,cessnock,cessnock airport,flughafen cessnock,lapangan terbang cessnock,ycnk,aeroport de cessnock,aeroporto di cessnock,aéroport de cessnock,frwdgah ssnwk,sai si nuo ke ji chang,sesunokku kong gang,фурудгоҳи сснук,فرودگاه سسنوک,セスノック空港,塞斯諾克機場',
    NOW(), NOW()), ('7668704', NULL, 'Corowa Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.9947, 146.35699, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'corowa airport corowa airport australia au cww,ycor',
    NOW(), NOW()), ('7668705', NULL, 'Corryong Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.1828, 147.888, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'corryong airport corryong airport australia au aeroportul corryong,cyg,corryong airport,flughafen corryong,lapangan terbang corryong,ycrg,aeroporto di corryong,aeropuerto de corryong,frwdgah kwrywng,ke li yang ji chang,фурудгоҳи курюнг,فرودگاه کوریونگ,科里揚機場',
    NOW(), NOW()), ('7668706', NULL, 'Cootamundra Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.6239, 148.028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cootamundra airport cootamundra airport australia au cmd,yctm',
    NOW(), NOW()), ('7668707', NULL, 'Cowra Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8447, 148.649, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cowra airport cowra airport australia au aeroportul cowra,cwt,cowra,cowra airport,flughafen cowra,lapangan terbang cowra,ycwr,aeroport de cowra,aeroporto di  cowra,aéroport de cowra,frwdgah kwra,kao la ji chang,kaura kong gang,фурудгоҳи куро,فرودگاه کورا,カウラ空港,考拉機場',
    NOW(), NOW()), ('7668708', NULL, 'Devonport Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.1697, 146.42999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'devonport airport devonport airport australia au aeroportul devonport,aeropuerto de devonport,aeropuertu de devonport,dpo,devonport,devonport airport,lapangan terbang devonport,letiste devonport,letiště devonport,port lotniczy devonport,ydpo,aeroport de devonport,aeroporto di devonport,aéroport de devonport,de wen gang ji chang,frwdgah dwnprt,девонпорт,фурудгоҳи дунпрт,فرودگاه دونپرت,德文港機場',
    NOW(), NOW()), ('7668709', NULL, 'Echuca Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.1572, 144.76199, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'echuca airport echuca airport australia au aeroportul echuca,ech,echuca airport,lapangan terbang echuca,yech,aeroporto di echuca,aeropuerto de echuca,ai se ka ji chang,echuka kong gang,frwdgah achwka,фурудгоҳи очуко,فرودگاه اچوکا,エチューカ空港,艾瑟卡機場',
    NOW(), NOW()), ('7668710', NULL, 'Emerald Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.5675, 148.179, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'emerald airport emerald airport australia au aeroportul emerald,emd,emerald airport,lapangan terbang emerald,yeml,aeroport d''emerald,ai mo la er de ji chang,aéroport d''emerald,emerarudo kong gang,frwdgah amrald,фурудгоҳи омролд,فرودگاه امرالد,エメラルド空港,埃默拉爾德机场,埃默拉爾德機場',
    NOW(), NOW()), ('7668711', NULL, 'Esperance Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6844, 121.823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'esperance airport esperance airport australia au aeroportul esperance,epr,ehsperans,esperance airport,lapangan terbang esperance,maes awyr esperance,port lotniczy esperance,yesp,aerodrome d''esperance,ai si pei lan si ji chang,aérodrome d''espérance,esuperansu kong gang,frwdgah asprans,фурудгоҳи оспронс,эсперанс,فرودگاه اسپرانس,エスペランス空港,埃斯佩蘭斯機場',
    NOW(), NOW()), ('7668713', NULL, 'Gunnedah Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.9611, 150.25101, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gunnedah airport gunnedah airport australia au aeroportul gunnedah,bandar udara gunnedah,flughafen gunnedah,guh,gunnedah,gunnedah airport,lapangan terbang gunnedah,ygdh,aeroport de gunnedah,aeroporto di gunnedah,aéroport de gunnedah,frwdgah ganda,фурудгоҳи гондо,فرودگاه گاندا',
    NOW(), NOW());