INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('3571835', NULL, 'Mouth of Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54192, -76.96439, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mouth of harbour cay mouth of harbour cay bahamas bs mouth of harbour cay',
    NOW(), NOW()), ('3571848', NULL, 'Moriah Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.46667, -75.66667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'moriah harbour cay moriah harbour cay bahamas bs moriah harbour cay',
    NOW(), NOW()), ('3571895', NULL, 'Mayaguana Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.379, -73.014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mayaguana airport mayaguana airport bahamas bs myg,mymm,mayaguana',
    NOW(), NOW()), ('3571912', NULL, 'Marsh Harbour District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.4, -77.16667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'marsh harbour district marsh harbour district bahamas bs marsh harbour,marsh harbour district',
    NOW(), NOW()), ('3571913', NULL, 'Marsh Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54124, -77.0636, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'marsh harbour marsh harbour bahamas bs mhh,marsh harbour',
    NOW(), NOW()), ('3571949', NULL, 'Clarence A. Bain Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.28812, -77.679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clarence a. bain airport clarence a. bain airport bahamas bs clarence a. bain airport,may,myab,mangrove cay airport',
    NOW(), NOW()), ('3571956', NULL, 'Major’s Cay Harbour', 'Major''s Cay Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.73615, -74.1418, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'major’s cay harbour major''s cay harbour bahamas bs major cay harbour,major''s cay harbour,major’s cay harbour',
    NOW(), NOW()), ('3571965', NULL, 'Lynyard Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.36968, -76.98195, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lynyard cay lynyard cay bahamas bs leonard cay,little harbour cay,lynyard cay',
    NOW(), NOW()), ('3571973', NULL, 'Low Water Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.41667, -75.81667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'low water harbour cay low water harbour cay bahamas bs low water harbour cay',
    NOW(), NOW()), ('3572051', NULL, 'Little Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.57804, -77.72004, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour cay little harbour cay bahamas bs little harbour cay',
    NOW(), NOW()), ('3572052', NULL, 'Little Harbour Bay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.33333, -77.01667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour bay little harbour bay bahamas bs',
    NOW(), NOW()), ('3572053', NULL, 'Little Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.31667, -76.98333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour little harbour bahamas bs',
    NOW(), NOW()), ('3572054', NULL, 'Little Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.98238, -74.85335, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'little harbour little harbour bahamas bs little harbour',
    NOW(), NOW()), ('3572096', NULL, 'Lantern Head Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    20.95631, -73.28259, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'lantern head harbour lantern head harbour bahamas bs',
    NOW(), NOW()), ('3572153', NULL, 'Inagua Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    20.97565, -73.67509, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inagua airport inagua airport bahamas bs iga,inagua airport,myig,matthew town airport,port lotniczy inagua,frwdgah aynagwa,فرودگاه ایناگوا',
    NOW(), NOW()), ('3572157', NULL, 'Hurricane Hole', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.33333, -77.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hurricane hole hurricane hole bahamas bs hurricane hole,little harbour',
    NOW(), NOW()), ('3572177', NULL, 'Torch Cay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.39764, -75.49893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'torch cay airport torch cay airport bahamas bs hog cay exuma airfield,myey,tcv',
    NOW(), NOW()), ('3572208', NULL, 'Head of Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.58658, -76.99503, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'head of harbour head of harbour bahamas bs head of harbour',
    NOW(), NOW()), ('3572211', NULL, 'Hawks Nest Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15361, -75.52405, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hawks nest airport hawks nest airport bahamas bs hawks nest airport,mych',
    NOW(), NOW()), ('3572215', NULL, 'Hawks Nest', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15, -75.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hawks nest hawks nest bahamas bs hawks nest,hawks nest harbour',
    NOW(), NOW()), ('3572237', NULL, 'Hard Bargain', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23, -74.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hard bargain hard bargain bahamas bs hard bargain,hard bargain airport',
    NOW(), NOW()), ('3572238', NULL, 'Harbour Island District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.48946, -76.63513, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour island district harbour island district bahamas bs gjao harbour,haborailenda,harboro sala,harbour adasi,harbour adası,harbour island,harbour island district,harbour uhartea,hāborailenda,illa harbour,isla harbour,kharbor-ajlend,nisi charmpor,pulau harbour,pulong harbour,ha bo dao,haba dao,habeoseom,harabara dbipa,harbar divi,harbar dvipa,harbara a''ilenda,harbara a''isalamda,harbara dvipa,harbor-ailendi,harpoyur  aislantu,jzyrh harbwr  bahama,đảo harbour,νησί χάρμπορ,харбор-айленд,جزيرة الميناء,جزیره هاربور، باهاما,حاربوور آئی لینڈ,हार्बर आईसलँड,हार्बर द्वीप,হারবার দ্বীপ,હાર્બર આઇલેન્ડ,ஹார்போயூர்  ஐஸ்லாந்து,హార్బర్ దీవి,ಹಾರ್ಬರ್ ದ್ವೀಪ,හාර්බර් දුපත,ฮาร์เบอร์ ไอส์แลนด์,ჰარბორ-აილენდი,ハーバー島,哈勃岛,哈勃島,하버섬',
    NOW(), NOW()), ('3572239', NULL, 'Harbour Island', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.5, -76.63333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour island harbour island bahamas bs hbi,harbor island,harbour island',
    NOW(), NOW()), ('3572240', NULL, 'Harbour Estate', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.1, -74.51667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour estate harbour estate bahamas bs',
    NOW(), NOW()), ('3572274', NULL, 'Green’s Harbour', 'Green''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.05548, -74.43769, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'green’s harbour green''s harbour bahamas bs',
    NOW(), NOW()), ('3572290', NULL, 'Great Harbour Cay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.74099, -77.84444, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour cay airport great harbour cay airport bahamas bs ghc,great harbour cay airport,mybg',
    NOW(), NOW()), ('3572291', NULL, 'Great Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.7287, -77.84028, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour cay great harbour cay bahamas bs ghc,great harbor cay,great harbour,great harbour cay',
    NOW(), NOW()), ('3572292', NULL, 'Great Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.09893, -74.95202, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour great harbour bahamas bs clarence harbour,great harbour',
    NOW(), NOW()), ('3572310', NULL, 'Grand Bahama Auxiliary Air Force', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.62789, -78.36496, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand bahama auxiliary air force grand bahama auxiliary air force bahamas bs gbi,grand bahama aux af airport,grand bahama aux. a.f.b.,grand bahama auxiliary air force',
    NOW(), NOW()), ('3572311', NULL, 'Graham’s Harbour', 'Graham''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.14187, -74.48185, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'graham’s harbour graham''s harbour bahamas bs',
    NOW(), NOW()), ('3572312', NULL, 'Governor''s Harbour District (historical)', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.25952, -76.31164, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'governor''s harbour district (historical) governor''s harbour district (historical) bahamas bs ghb,governor''s harbour,governor''s harbour district',
    NOW(), NOW()), ('3572313', NULL, 'Governor’s Harbour', 'Governor''s Harbour',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.16667, -76.23333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'governor’s harbour governor''s harbour bahamas bs governor harbor,governor harbour,governor''s harbour,governors harbor,governor’s harbour',
    NOW(), NOW()), ('3572320', NULL, 'Gorda Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.09123, -77.54065, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gorda cay gorda cay bahamas bs castaway cay airport,myag',
    NOW(), NOW()), ('3572348', NULL, 'Georgetown Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.49871, -75.76262, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'georgetown harbour georgetown harbour bahamas bs',
    NOW(), NOW()), ('3572372', NULL, 'Grand Bahama International Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.55869, -78.69555, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'grand bahama international airport grand bahama international airport bahamas bs aeroport international de grand bahama,aeropuerto internacional de grand bahama,aéroport international de grand bahama,bandar udara internasional grand bahama,fpo,freeport international airport,grand bahama international airport,grand bahaman kansainvaelinen lentoasema,grand bahaman kansainvälinen lentoasema,lapangan terbang antarabangsa grand bahama,mygf,mezhdunarodnyj aehroport bol''shogo bagamy,port lotniczy wielka bahama,san bay quoc te grand bahama,sân bay quốc tế grand bahama,da ba ha ma guo ji ji chang,frwdgah byn‌almlly grnd bahama,gurandobahama guo ji kong gang,международный аэропорт большого багамы,фурудгоҳи бин‌алмилалӣ грнд баҳама,فرودگاه بین‌المللی گرند باهاما,グランドバハマ国際空港,大巴哈馬國際機場,大巴哈马国际机场',
    NOW(), NOW()), ('3572373', NULL, 'Freeport Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.52087, -78.78035, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'freeport harbour freeport harbour bahamas bs freeport harbour',
    NOW(), NOW()), ('3572374', NULL, 'City of Freeport District', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.52028, -78.64528, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'city of freeport district city of freeport district bahamas bs city of freeport,city of freeport district,freeport,freeport district,friiport,frijport,friport,friporta,friportas,frīporta,fri phxrth,fry pwrt,frybwrt,fu li bo te,furipoto,peulipoteu,phri porta,phriport,phriporta,piripport,prypwrt,zi you gang,φρίπορτ,фрийпорт,фрипорт,фріпорт,פריפורט,فريبورت,فری پورت,فری پورٹ، بہاماس,फ्री पोर्ट,फ्रीपोर्ट,ফ্রিপোর্ট,ફ્રીપોર્ટ,பிரிப்போர்ட்,ఫ్రీపోర్ట్,ಫ್ರೀಪೋರ್ಟ್,ෆ්රීපෝර්ට්,ฟรีพอร์ท,ფრიპორტი,フリーポート,弗里波特,自由港,프리포트',
    NOW(), NOW()), ('3572375', NULL, 'Freeport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.53333, -78.7, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'freeport freeport bahamas bs fpo,freeport,freeport city,friport,фрипорт',
    NOW(), NOW()), ('3572381', NULL, 'Fowl Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.26873, -76.53875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fowl cay fowl cay bahamas bs fowl cay,fowl cay airport,myxa',
    NOW(), NOW()), ('3572425', NULL, 'Exuma Harbour Estates', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.5, -75.76667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'exuma harbour estates exuma harbour estates bahamas bs',
    NOW(), NOW()), ('3572426', NULL, 'Exuma Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.54121, -75.81799, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'exuma harbour exuma harbour bahamas bs',
    NOW(), NOW()), ('3572434', NULL, 'Elizabeth Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.50796, -75.73009, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'elizabeth harbour elizabeth harbour bahamas bs elizabeth harbour,elizabeth howbon',
    NOW(), NOW()), ('3572462', NULL, 'Dunmore Town', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.50216, -76.63633, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dunmore town dunmore town bahamas bs dunmore town,harbour island',
    NOW(), NOW()), ('3572490', NULL, 'Dollar Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.51667, -79.26667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'dollar harbour dollar harbour bahamas bs',
    NOW(), NOW()), ('3572509', NULL, 'Delaport Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.07965, -77.43158, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delaport point delaport point bahamas bs delaport point',
    NOW(), NOW()), ('3572510', NULL, 'Delaport Bay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.08333, -77.4, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'delaport bay delaport bay bahamas bs',
    NOW(), NOW()), ('3572512', NULL, 'Deep Water Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.63112, -77.92081, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'deep water cay deep water cay bahamas bs deep water cay,deep water cay airport,mygd',
    NOW(), NOW()), ('3572535', NULL, 'Cutlass Bay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.14899, -75.39797, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cutlass bay airport cutlass bay airport bahamas bs aeroport de la baie de cutlass,aeroportul cutlass bay,aéroport de la baie de cutlass,cutlass bay airport,lapangan terbang cutlass bay,mycx,カットラス・ベイ空港',
    NOW(), NOW()), ('3572558', NULL, 'Cross Harbour Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.91948, -77.28442, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cross harbour point cross harbour point bahamas bs cedar point,cross harbor point,cross harbour point',
    NOW(), NOW()), ('3572559', NULL, 'Cross Harbour Creek', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.93333, -77.26667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cross harbour creek cross harbour creek bahamas bs',
    NOW(), NOW()), ('3572560', NULL, 'Cross Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.9623, -77.30327, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cross harbour cross harbour bahamas bs cross harbour',
    NOW(), NOW()), ('3572567', NULL, 'Colonel Hill Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.74563, -74.18072, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colonel hill airport colonel hill airport bahamas bs aeroportul colonel hill,cri,colonel hill airport,colonel hill ji chang,colonel hill機場,crooked island airport,lapangan terbang colonel hill,myci,port lotniczy colonel hill,frwdgah kwlnl hyl,фурудгоҳи кулнл ҳил,فرودگاه کولنل هیل,コロネル・ヒル空港',
    NOW(), NOW()), ('3572599', NULL, 'Coral Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.98176, -77.46534, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coral harbour coral harbour bahamas bs coral harbor,coral harbour',
    NOW(), NOW()), ('3572604', NULL, 'South Andros Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15745, -77.58356, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south andros airport south andros airport bahamas bs aeroport d''andros sud,aéroport d''andros sud,congo town airport,myak,south andros airport,tzn',
    NOW(), NOW()), ('3572652', NULL, 'Chub Cay International Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.41723, -77.88161, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'chub cay international airport chub cay international airport bahamas bs aeroport international de chub cay,aeroportul chub cay,aéroport international de chub cay,ccz,chub cay international airport,chub dao guo ji ji chang,chub島國際機場,lapangan terbang antarabangsa chub cay,mybc,maes awyr rhyngwladol chub cay,port lotniczy chub cay,фурудгоҳи бин‌алмилалӣ чоб кий,فرودگاه بین‌المللی چاب کی,チャブ・ケイ国際空港',
    NOW(), NOW()), ('3572669', NULL, 'Cedar Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.89532, -77.65198, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'cedar harbour cedar harbour bahamas bs cedar harbor,cedar harbour',
    NOW(), NOW()), ('3572689', NULL, 'Carrion Crow Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.64, -77.93687, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'carrion crow harbour carrion crow harbour bahamas bs carrion crow harbour',
    NOW(), NOW()), ('3572694', NULL, 'Cape Santa Maria', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.64885, -75.32304, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cape santa maria cape santa maria bahamas bs cape santa maria airport',
    NOW(), NOW()), ('3572712', NULL, 'Burrows Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.93053, -74.84433, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'burrows harbour burrows harbour bahamas bs',
    NOW(), NOW()), ('3572716', NULL, 'Bullocks Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.75205, -77.86895, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bullocks harbour bullocks harbour bahamas bs bullock harbour,bullocks harbour,bullocks harbour settlement',
    NOW(), NOW()), ('3572765', NULL, 'Boat Harbour Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54414, -77.04133, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour point boat harbour point bahamas bs boat harbour point',
    NOW(), NOW()), ('3572766', NULL, 'Boat Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.98027, -77.39989, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'boat harbour boat harbour bahamas bs',
    NOW(), NOW()), ('3572812', NULL, 'Big Thrift Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.53333, -77.85, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big thrift harbour cay big thrift harbour cay bahamas bs big thrift harbour cay',
    NOW(), NOW()), ('3572829', NULL, 'Big Harbour Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.64897, -77.8924, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'big harbour cay big harbour cay bahamas bs big harbour cay',
    NOW(), NOW()), ('3572847', NULL, 'Bennetts Harbor', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.56347, -75.63989, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'bennetts harbor bennetts harbor bahamas bs bennet harbour,bennets harbour,bennett''s harbour,bennett''s harbour settlement,bennetts harbor,bennett’s harbour,bennett’s harbour settlement',
    NOW(), NOW()), ('3572887', NULL, 'Commonwealth of The Bahamas', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.04082, -77.37122, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'commonwealth of the bahamas commonwealth of the bahamas bahamas bs ba-ha-ma,ba-ha-ma (bahamas),bachames,bagam,bagam araldary,bagam utraulary,bagama adalary,bagama araldary,bagama orollari,bagaman gӏajrenash,bagami,bagams''ki ostrovi,bagamskia astravy,bagamskie ostrova,bagamy,bagamyn arluud,bahaamas,baham adalari,baham adaları,bahama,bahama islands,bahama saared,bahama''s,bahama-szigetek,bahamaas,bahamaeyjar,bahamak,bahamalar,bahamaoyggjar,bahamas,bahamas nutome,bahamasa,bahamase,bahamasi,bahamasɛ,bahamat,bahama’s,bahamen,bahames,bahamet,bahami,bahamner,bahamoj,bahamos,bahamu salas,bahamu salos,bahamuaens,bahamuäns,bahamy,bahamyan kgziner,bahamák,bahamų salos,bahâmasa,bakhame,bakhami,bakhamski o-vi,bakhamski ostrovi,bakhamski ostrovi,baħamas,bhahamas,bàhámásì,colony of the bahamas,commonwealth of the bahamas,insulae bahamenses,na h-eileanan bhathama,orileede bahamasi,orílẹ́ède bàhámásì,pahama,the bahamas,y bahamas,ynysow bahama,albahama,albhama,ba ha ma,bahama,bahama dbipapunja,bahama guo,bahamacha,bahamaja,bahamas,bahamasa,bahamasi,bahamaza,bahamis kʼundzulebi,bahmas,baھama,baہamas,bhamas,bʼahʼamʼas,i-bahamas,il-bahamas,jzr albhama,na bahamai,na bahámaí,pahamas,prathes bahamas,ʼyy bhʼmh,μπαχάμες,багам,багам аралдары,багам утраулары,багама аралдары,багаман гӏайренаш,багами,багамские острова,багамскія астравы,багамські острови,багамы,багамын арлууд,бахаме,бахами,бахамски о-ви,бахамски острови,бахамски острови,բահամյան կղզիներ,բահամներ,איי בהאמה,איי הבהמה,באַהאַמאַס,באהאמה  איי,الباهاما,البهاما,باهاما,باهاماس,باهماس,باھاما,بهاماس,بَہامَس,بہاماس,بەھاما,جزر البهاما,बहामा,बहामाज,बहामाज़,बहामास,বাহামা,বাহামা দ্বীপপুঞ্জ,বাহামাছ,ਬਹਾਮਾਸ,બહામાસ,ବାହାମାସ୍,பஹாமாஸ்,బహామాస్,ಬಹಾಮಾಸ್,ബഹാമാസ്,බහමාස්,บาฮามาส,ประเทศบาฮามาส,ບາຮາມາສ,བ་ཧ་མས,བྷ་ཧ་མས྄,བྷཱ་མས྄།,ဘဟားမား,ბაჰამის კუნძულები,ባሃማስ,បាហាមា,បាហាមាស,បាហាម៉ា,バハマ,バハマ国,巴哈馬,巴哈马,바하마',
    NOW(), NOW()), ('3572893', NULL, 'Atwood Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.71667, -73.8841, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'atwood harbour atwood harbour bahamas bs attwood harbour,atwood harbour',
    NOW(), NOW()), ('3572898', NULL, 'Arthur''s Town Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.629, -75.67306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arthur''s town airport arthur''s town airport bahamas bs atc,aeroportul arthur''s town,arthur''s town airport,lapangan terbang arthur''s town,myca,port lotniczy arthur''s town,a se zhen ji chang,frwdgah artwrz tawn,фурудгоҳи ортурз товн,فرودگاه آرتورز تاون,アーサーズ・タウン空港,阿瑟鎮機場',
    NOW(), NOW()), ('3572907', NULL, 'Andros Town International Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.69756, -77.79316, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'andros town international airport andros town international airport bahamas bs asd,andros town international airport,myaf',
    NOW(), NOW()), ('3739565', NULL, 'Riding Point Terminal', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.625, -78.23056, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'riding point terminal riding point terminal bahamas bs',
    NOW(), NOW()), ('3739596', NULL, 'Barnett Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.6375, -79.31667, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'barnett harbour barnett harbour bahamas bs',
    NOW(), NOW()), ('3739601', NULL, 'Ocean Cay Terminal', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.41667, -79.21667, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'ocean cay terminal ocean cay terminal bahamas bs',
    NOW(), NOW()), ('3740245', NULL, 'Harbour Point', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.1025, -74.96, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour point harbour point bahamas bs',
    NOW(), NOW()), ('3740295', NULL, 'Reef Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.15145, -75.33428, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'reef harbour reef harbour bahamas bs',
    NOW(), NOW()), ('3740298', NULL, 'Port Nelson Salt Pond', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.65, -74.825, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port nelson salt pond port nelson salt pond bahamas bs',
    NOW(), NOW()), ('3741019', NULL, 'Borco Oil Terminal', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.50417, -78.775, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'borco oil terminal borco oil terminal bahamas bs',
    NOW(), NOW()), ('3830933', NULL, 'Lyford Cay Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.04254, -77.51673, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'lyford cay harbour lyford cay harbour bahamas bs lyford cay harbour',
    NOW(), NOW()), ('3830953', NULL, 'Davis Harbor', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.73095, -76.22016, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'davis harbor davis harbor bahamas bs davis harbor',
    NOW(), NOW()), ('6299936', NULL, 'South Bimini Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.69988, -79.26466, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south bimini airport south bimini airport bahamas bs aeroport de bimini sud,aeroport de south bimini,aeroportul south bimini,aéroport de bimini sud,bim,bimini international airport,haravayin biminii odanavakayan,lapangan terbang south bimini,mybs,port lotniczy poludniowe bimini,port lotniczy południowe bimini,south bimini airport,frwdgah swt bymyny,nan bi mi ni ji chang,фурудгоҳи сӯят бимини,հարավային բիմինիի օդանավակայան,فرودگاه سوت بیمینی,サウス・ビミニ空港,南比米尼机场,南比米尼機場',
    NOW(), NOW()), ('6299937', NULL, 'George Town Exuma International Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.56123, -75.87484, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'george town exuma international airport george town exuma international airport bahamas bs exuma international airport,ggt,george town exuma international airport,myef',
    NOW(), NOW()), ('6299942', NULL, 'San Salvador Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.06328, -74.52397, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'san salvador airport san salvador airport bahamas bs aeroport de san salvador,aeroportul san salvador,aéroport de san salvador,cockburn town airport,lapangan terbang antarabangsa san salvador,mysm,port lotniczy san salvador,san salvador airport,zsa,aeroporto di san salvador,frwdgah san salwadwr,sheng sa er wa duo dao,sheng sa er wa duo ji chang,фурудгоҳи сон солуодур,فرودگاه سان سالوادور,サン・サルバドル空港,圣萨尔瓦多机场,聖薩爾瓦多島,聖薩爾瓦多機場',
    NOW(), NOW()), ('6469645', NULL, 'Abaco Beach Resort & Boat Harbour', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.54185, -77.07458, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'abaco beach resort & boat harbour abaco beach resort & boat harbour bahamas bs',
    NOW(), NOW()), ('6472407', NULL, 'Port Lucaya Resort & Yacht Club', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.5386, -78.6331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lucaya resort & yacht club port lucaya resort & yacht club bahamas bs',
    NOW(), NOW()), ('6495208', NULL, 'Harborside Resort at Atlantis', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.0806, -77.325, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harborside resort at atlantis harborside resort at atlantis bahamas bs',
    NOW(), NOW()), ('6497414', NULL, 'Hawks Nest Resort & Marina', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.1488, -75.526, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hawks nest resort & marina hawks nest resort & marina bahamas bs',
    NOW(), NOW()), ('6500371', NULL, 'Sandyport Beaches Resort', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.0728, -77.441, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sandyport beaches resort sandyport beaches resort bahamas bs',
    NOW(), NOW()), ('6503483', NULL, 'Paradise Island Harbour Resort All Inclusive', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.0795, -77.3169, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'paradise island harbour resort all inclusive paradise island harbour resort all inclusive bahamas bs',
    NOW(), NOW()), ('6520654', NULL, 'Valentines Resort Harbour Islan', 'VALENTINES RESORT HARBOUR ISLAN',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.5, -76.6499, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'valentines resort harbour islan valentines resort harbour islan bahamas bs',
    NOW(), NOW()), ('6526011', NULL, 'Freeport Resort And Club', 'FREEPORT RESORT AND CLUB',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    26.5333, -78.6999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'freeport resort and club freeport resort and club bahamas bs',
    NOW(), NOW()), ('6529946', NULL, 'Harborside Resort At Atlantis', 'HARBORSIDE RESORT AT ATLANTIS',
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.08203, -77.32276, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harborside resort at atlantis harborside resort at atlantis bahamas bs',
    NOW(), NOW()), ('7626918', NULL, 'Staniel Cay yacht club', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.17256, -76.44532, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'staniel cay yacht club staniel cay yacht club bahamas bs',
    NOW(), NOW()), ('7627000', NULL, 'Highborne Cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.7096, -76.82278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'highborne cay highborne cay bahamas bs highbourne marina',
    NOW(), NOW()), ('7627001', NULL, 'Alen cay', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    24.66987, -76.81061, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alen cay alen cay bahamas bs',
    NOW(), NOW()), ('7668362', NULL, 'Spring Point Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.4418, -73.9709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'spring point airport spring point airport bahamas bs axp,myap',
    NOW(), NOW()), ('7668363', NULL, 'Duncan Town Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.1818, -75.7295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'duncan town airport duncan town airport bahamas bs aeroportul duncan town,dct,duncan town airport,lapangan terbang duncan town,myrd,deng ken zhen ji chang,frwdgah dankn tawn,фурудгоҳи донкн товн,فرودگاه دانکن تاون,ダンカン・タウン空港,鄧肯鎮機場',
    NOW(), NOW()), ('7668364', NULL, 'Port Nelson Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    23.68344, -74.83625, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port nelson airport port nelson airport bahamas bs aeroportul port nelson,myrp,new port nelson airport,port nelson airport,rcy,rum cay airport,frwdgah pwrt nlswn,фурудгоҳи пӯр нлсун,فرودگاه پورت نلسون,ポート・ネルソン空港',
    NOW(), NOW()), ('7730118', NULL, 'Governor''s Harbour Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.2847, -76.331, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'governor''s harbour airport governor''s harbour airport bahamas bs aeroportul governor''s harbour,ghb,governor''s harbour airport,lapangan terbang governors harbour,myem,port lotniczy governor''s harbour,frwdgah gwrnrs harbr,jia fu na gang,tong zhi zhe gang ji chang,фурудгоҳи гурнрс ҳорбр,فرودگاه گورنرس هاربر,ガバナーズ・ハーバー空港,加弗納港,加弗纳港,統治者港機場',
    NOW(), NOW()), ('7730681', NULL, 'Cat Cay Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.555, -79.276, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cat cay airport cat cay airport bahamas bs aeroportul cat cay,cxy,cat cay airport,mycc,mao dao ji chang,キャット・ケイ空港,貓島機場',
    NOW(), NOW()), ('7730682', NULL, 'Pitts Town Airport', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    22.8297, -74.3461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pitts town airport pitts town airport bahamas bs aeroportul pitts town,mycp,pwn,pitts town airport,ピッツ・タウン空港',
    NOW(), NOW()), ('7730683', NULL, 'Nassau Paradise Island Airport (historical)', NULL,
    NULL, 'BS', 'Bahamas', NULL, NULL,
    25.083, -77.3, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nassau paradise island airport (historical) nassau paradise island airport (historical) bahamas bs mypi,nassau paradise island airport,new providence airport,pid',
    NOW(), NOW());