INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('7730154', NULL, 'Guajará-Mirim Airport', 'Guajara-Mirim Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.7864, -65.2848, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'guajará-mirim airport guajara-mirim airport brazil br aeroport de guajara-mirim,aeroporto de guajara-mirim,aeroporto de guajará-mirim,aeropuerto de guajara-mirim,aeropuerto de guajará-mirim,aéroport de guajará-mirim,flughafen guajara-mirim,flughafen guajará-mirim,gjm,guajara-mirim airport,guajará-mirim airport,sbgm',
    NOW(), NOW()), ('7730155', NULL, 'Itacoatiara Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.12726, -58.4812, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itacoatiara airport itacoatiara airport brazil br ita,sbic',
    NOW(), NOW()), ('7730156', NULL, 'Lages Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -27.7821, -50.2815, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lages airport lages airport brazil br aeroporto de lages,aeroportul lages,aeropuerto de lages,flughafen lages,laj,lages airport,lapangan terbang lages,sblj,aeroport de lages,aéroport de lages,rajesu kong gang,ラジェス空港',
    NOW(), NOW()), ('7730157', NULL, 'Lins Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.664, -49.7305, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lins airport lins airport brazil br aeroporto de lins,aeroportul lins,aeropuerto de lins,flughafen lins,lip,lapangan terbang lins,lins airport,sbln,aerodrome de lins,aérodrome de lins,rinsu kong gang,リンス空港',
    NOW(), NOW()), ('7730158', NULL, 'Minaçu Airport', 'Minacu Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.5491, -48.1953, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'minaçu airport minacu airport brazil br mqh,sbmc',
    NOW(), NOW()), ('7730159', NULL, 'Monte Dourado Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -0.88984, -52.6022, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'monte dourado airport monte dourado airport brazil br aeroporto de monte dourado,aeroportul monte dourado,aeropuerto de monte dourado,flughafen monte dourado,lapangan terbang monte dourado,meu,monte dourado airport,sbmd,aerodrome de monte dourado,aérodrome de monte dourado,frwdgah mwnth dwradw,meng te du la duo ji chang,фурудгоҳи мунта дуроду,فرودگاه مونته دورادو,モンテ・ドウラード空港,蒙特杜拉多機場',
    NOW(), NOW()), ('7730160', NULL, 'Marília Airport', 'Marilia Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.1969, -49.9264, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marília airport marilia airport brazil br mii,sbml',
    NOW(), NOW()), ('7730161', NULL, 'Base de Aviação de Taubaté Airport', 'Base de Aviacao de Taubate Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0401, -45.516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'base de aviação de taubaté airport base de aviacao de taubate airport brazil br qhp,sbta',
    NOW(), NOW()), ('7730162', NULL, 'Tiriós Airport', 'Tirios Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    2.22347, -55.9461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tiriós airport tirios airport brazil br sbts',
    NOW(), NOW()), ('7730163', NULL, 'Major Brigadeiro Trompowsky Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.5901, -45.4733, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'major brigadeiro trompowsky airport major brigadeiro trompowsky airport brazil br sbvg,vag',
    NOW(), NOW()), ('7730779', NULL, 'Caldas Novas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.7253, -48.6075, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caldas novas airport caldas novas airport brazil br clv,sbcn',
    NOW(), NOW()), ('7730780', NULL, 'Governador Valadares Airport (GVR, SBGV)', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.8952, -41.9822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'governador valadares airport (gvr, sbgv) governador valadares airport (gvr, sbgv) brazil br aeroporto coronel altino machado de oliveira,coronel altino machado de oliveira airport,gvr,governador valadares airport,sbgv',
    NOW(), NOW()), ('7730781', NULL, 'Chapada Diamantina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.4823, -41.277, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chapada diamantina airport chapada diamantina airport brazil br lec,sble',
    NOW(), NOW()), ('7730782', NULL, 'Una-Comandatuba Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.3574, -38.99822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'una-comandatuba airport una-comandatuba airport brazil br aeroporto de una-comandatuba,sbtc,una,una-comandatuba airport',
    NOW(), NOW()), ('7730783', NULL, 'Luiz dal Canalle Filho Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.6863, -53.6975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'luiz dal canalle filho airport luiz dal canalle filho airport brazil br aeroporto luiz dal canalle filho,luiz dal canalle filho airport,sbtd,tow,toledo airport',
    NOW(), NOW()), ('7730811', NULL, 'Aripuanã Airport', 'Aripuana Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.18639, -59.4575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aripuanã airport aripuana airport brazil br air,aeroport d''aripuana,aeroporto de aripuana,aeroporto de aripuanã,aeropuerto de aripuana,aeropuerto de aripuanã,aripuana airport,aripuanã airport,aéroport d''aripuanã,ssou',
    NOW(), NOW()), ('7730818', NULL, 'Alenquer Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.9175, -54.7211, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alenquer airport alenquer airport brazil br alt,sdwq',
    NOW(), NOW()), ('7730821', NULL, 'Cirilo Queiróz Airport', 'Cirilo Queiroz Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -16.18389, -40.66722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cirilo queiróz airport cirilo queiroz airport brazil br amj,snar',
    NOW(), NOW()), ('7730827', NULL, 'Arapiraca Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.77536, -36.6292, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arapiraca airport arapiraca airport brazil br apq,snal',
    NOW(), NOW()), ('7730829', NULL, 'Nova Vida Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.17806, -62.82556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nova vida airport nova vida airport brazil br aqm,swni',
    NOW(), NOW()), ('7730850', NULL, 'Novo Campo Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.83456, -67.3124, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novo campo airport novo campo airport brazil br bcr,swnk',
    NOW(), NOW()), ('7730853', NULL, 'Barra do Corda Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.5025, -45.21583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barra do corda airport barra do corda airport brazil br bdc,snbc',
    NOW(), NOW()), ('7730874', NULL, 'Sócrates Mariani Bittencourt Airport', 'Socrates Mariani Bittencourt Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.2554, -41.8175, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sócrates mariani bittencourt airport socrates mariani bittencourt airport brazil br bms,snbu',
    NOW(), NOW()), ('7730875', NULL, 'Blumenau Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.8306, -49.0903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'blumenau airport blumenau airport brazil br bnu,ssbl',
    NOW(), NOW()), ('7730878', NULL, 'Barreiras Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.0789, -45.009, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barreiras airport barreiras airport brazil br aeroporto de barreiras,aeroportul barreiras,aeropuerto de barreiras,bra,barreiras airport,flughafen barreiras,lapangan terbang barreiras,snbr,aerodrome de barreiras,aérodrome de barreiras,ba lei la si ji chang,bareirasu,frwdgah baryras,фурудгоҳи борирос,فرودگاه باریراس,バレイラス,巴雷拉斯機場',
    NOW(), NOW()), ('7730879', NULL, 'Barreirinha Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.79242, -57.0579, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barreirinha airport barreirinha airport brazil br barreirinha airport,swbi',
    NOW(), NOW()), ('7730881', NULL, 'Balsas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.52603, -46.0533, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'balsas airport balsas airport brazil br bss,snbs',
    NOW(), NOW()), ('7730890', NULL, 'Belmonte Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.8717, -38.8719, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'belmonte airport belmonte airport brazil br bvm,snbl',
    NOW(), NOW()), ('7730891', NULL, 'Breves Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.63653, -50.4436, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'breves airport breves airport brazil br bvs,snvs',
    NOW(), NOW()), ('7730901', NULL, 'Carauari Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.87152, -66.8975, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carauari airport carauari airport brazil br aeroporto de carauari,aeroportul carauari,aeropuerto de carauari,caf,carauari airport,flughafen carauari,lapangan terbang carauari,swca,aeroport de carauari,arauari kong gang,aéroport de carauari,frwdgah krawary,ka la wa li ji chang,фурудгоҳи кровори,فرودگاه کراواری,アラウアリ空港,卡拉瓦里機場',
    NOW(), NOW()), ('7730902', NULL, 'Caruaru Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.28239, -36.0135, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caruaru airport caruaru airport brazil br cau,snru',
    NOW(), NOW()), ('7730912', NULL, 'Confresa Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.6344, -51.5636, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'confresa airport confresa airport brazil br cfo,sjhg',
    NOW(), NOW()), ('7730920', NULL, 'Coari Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -4.13406, -63.1326, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coari airport coari airport brazil br aeroporto de coari,aeroportul coari,aeropuerto de coari,ciz,coari airport,flughafen coari,lapangan terbang coari,maes awyr coari,swko,aeroport de coari,aéroport de coari,frwdgah kwary,koari kong gang,kua li ji chang,фурудгоҳи куори,فرودگاه کواری,コアリ空港,夸里機場,誇里機場',
    NOW(), NOW()), ('7730921', NULL, 'Cornélio Procópio Airport', 'Cornelio Procopio Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.1525, -50.6025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cornélio procópio airport cornelio procopio airport brazil br aeroporto de cornelio procopio,aeroporto de cornélio procópio,aeroportul cornelio procopio,aeroportul cornélio procópio,aeropuerto de cornelio procopio,aeropuerto de cornélio procópio,cko,cornelio procopio airport,cornélio procópio airport,flughafen francisco lacerda junior,flughafen francisco lacerda júnior,lapangan terbang cornelio procopio,sscp,aerodrome de francisco lacerda junior,aérodrome de francisco lacerda júnior,ke nei li wu-pu luo ke pi wu ji chang,コルネーリオ・プロコーピオ空港,科內利烏-普羅科皮烏機場',
    NOW(), NOW()), ('7730925', NULL, 'Camocim Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.89618, -40.858, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camocim airport camocim airport brazil br cmc,snwc',
    NOW(), NOW()), ('7730927', NULL, 'Santana do Araguaia Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -9.31997, -50.3285, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santana do araguaia airport santana do araguaia airport brazil br cmp,snke',
    NOW(), NOW()), ('7730930', NULL, 'Canavieiras Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.667, -38.9547, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canavieiras airport canavieiras airport brazil br cnv,sned',
    NOW(), NOW()), ('7730937', NULL, 'Campo dos Amarais Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.8592, -47.1082, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'campo dos amarais airport campo dos amarais airport brazil br aeroporto campo dos amarais,aeroportul campo dos amarais,aeropuerto campo dos amarais,cpq,campinas international airport,campinas-campos dos amarais delstatsflygplats - prefeito francisco amaral,campinas-campos dos amarais delstatsflygplats – prefeito francisco amaral,campo dos amarais airport,flughafen aerodromo estadual de campinas / amarais,flughafen aerodrómo estadual de campinas / amarais,kampu-dus-amarais,lapangan terbang amarais,sdam,aerodrome de estadual de campos dos amarais - prefeito francisco amaral,aérodrome de estadual de campos dos amarais - prefeito francisco amaral,frwdgah kmpww das amarays,кампу-дус-амараис,фурудгоҳи кмпув дос омороис,فرودگاه کمپوو داس آمارایس,カンポ・ドス・アマライス空港',
    NOW(), NOW()), ('7730938', NULL, 'Cururupu Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.82111, -44.86694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cururupu airport cururupu airport brazil br cpu,sncu',
    NOW(), NOW()), ('7730939', NULL, 'Canarana Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.57444, -52.27056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canarana airport canarana airport brazil br aeroporto de canarana,aeroportul canarana,aeropuerto de canarana,cqa,canarana airport,flughafen canarana,lapangan terbang canarana,swek,aerodrome de canarana,aérodrome de canarana',
    NOW(), NOW()), ('7730941', NULL, 'Costa Marques Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -12.4211, -64.2516, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'costa marques airport costa marques airport brazil br cqs,swcq',
    NOW(), NOW()), ('7730949', NULL, 'Santa Cruz do Sul Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.6841, -52.4122, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa cruz do sul airport santa cruz do sul airport brazil br aeroporto luiz beck da silva,aeroporto de santa cruz do sul,aeroportul santa cruz do sul,aeropuerto de santa cruz do sul,csu,flughafen santa cruz do sul,lapangan terbang santa cruz do sul,sssc,santa cruz do sul airport,aerodrome de santa cruz do sul,aérodrome de santa cruz do sul',
    NOW(), NOW()), ('7730950', NULL, 'Carutapera Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.22482, -46.01823, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'carutapera airport carutapera airport brazil br aeroport de carutapera,aeroporto de carutapera,aeropuerto de carutapera,aéroport de carutapera,ctp,carutapera airport',
    NOW(), NOW()), ('7730951', NULL, 'Santa Vitória do Palmar Airport', 'Santa Vitoria do Palmar Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -33.50222, -53.34417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa vitória do palmar airport santa vitoria do palmar airport brazil br ctq,ssvp',
    NOW(), NOW()), ('7730973', NULL, 'Brigadeiro Cabral Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.1807, -44.8709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brigadeiro cabral airport brigadeiro cabral airport brazil br aeroport de divinopolis,aeroporto brigadeiro cabral,aéroport de divinópolis,brigadeiro cabral airport,diq,divinopolis airport,divinópolis airport,sndv',
    NOW(), NOW()), ('7730979', NULL, 'Diamantino Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.3769, -56.4004, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'diamantino airport diamantino airport brazil br dmt,swdm',
    NOW(), NOW()), ('7730982', NULL, 'Dianópolis Airport', 'Dianopolis Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.5954, -46.8467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dianópolis airport dianopolis airport brazil br dno,dianopolis airport,dianópolis airport,swdn',
    NOW(), NOW()), ('7730986', NULL, 'Dourados Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.2019, -54.9266, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dourados airport dourados airport brazil br aeroporto regional de dourados,aeroportul dourados,aeropuerto regional de dourados,dou,dourados airport,flugplatz sao pedro,flugplatz são pedro,lapangan terbang dourados,maes awyr dourados,ssdo,douradosu,duo la du si ji chang,frwdgah dwradws,mtar dwradws,фурудгоҳи дуродус,فرودگاه دورادوس,مطار دورادوس,ドウラドス,多拉杜斯機場',
    NOW(), NOW()), ('7731012', NULL, 'Eirunepé Airport', 'Eirunepe Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.63953, -69.8798, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eirunepé airport eirunepe airport brazil br ern,swei',
    NOW(), NOW()), ('7731020', NULL, 'Paulo Abdala Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.0592, -53.0635, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paulo abdala airport paulo abdala airport brazil br aeroporto paulo abdala,aeroportul francisco beltrao,aeroportul francisco beltrão,aeropuerto de francisco beltrao,aeropuerto de francisco beltrão,fbe,flughafen paulo abdala,francisco beltrao airport,francisco beltrão airport,lapangan terbang francisco beltrao,paulo abdala airport,ssfb,aerodrome de paulo abdala,aérodrome de paulo abdala,bei er de lang ji chang,frwdgah frnsyskw bltrwn,фурудгоҳи фрнсиску блтрун,فرودگاه فرنسیسکو بلترون,フランシスコ・ベルトラン空港,貝爾德朗機場',
    NOW(), NOW()), ('7731021', NULL, 'Feijó Airport', 'Feijo Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.16438, -70.35286, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'feijó airport feijo airport brazil br aeroport de  feijo,aeropuerto de  feijo,aeropuerto de  feijó,aéroport de  feijó,fej,feijo airport,feijó airport,swfj',
    NOW(), NOW()), ('7731027', NULL, 'Cangapara Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.84639, -43.0773, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cangapara airport cangapara airport brazil br flb,snqg',
    NOW(), NOW()), ('7731033', NULL, 'Franca Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.5922, -47.3829, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'franca airport franca airport brazil br frc,simk',
    NOW(), NOW()), ('7731046', NULL, 'Guadalupe Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -6.78222, -43.5822, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'guadalupe airport guadalupe airport brazil br gdp,sngd',
    NOW(), NOW()), ('7731064', NULL, 'Fazenda Canadá Airport', 'Fazenda Canada Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.86056, -48.42216, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fazenda canadá airport fazenda canada airport brazil br fazenda canada airport,fazenda canadá airport,sngm',
    NOW(), NOW()), ('7731065', NULL, 'Guanambi Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.2082, -42.7461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'guanambi airport guanambi airport brazil br aeroporto de guanambi,aeroportul guanambi,aeropuerto de guanambi,flughafen guanambi,gnm,guanambi airport,lapangan terbang guanambi,sngi,aerodrome de guanambi,aérodrome de guanambi,frwdgah gwanamby,gua nan bi ji chang,guananbi kong gang,фурудгоҳи гуономби,فرودگاه گوآنامبی,グァナンビ空港,瓜南比機場',
    NOW(), NOW()), ('7731067', NULL, 'Gurupi Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.7396, -49.1322, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gurupi airport gurupi airport brazil br grp,gurupi airport,swgi',
    NOW(), NOW()), ('7731104', NULL, 'Santa Isabel do Morro Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.5723, -50.6662, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'santa isabel do morro airport santa isabel do morro airport brazil br ido,swiy,santa isabel do morro airport',
    NOW(), NOW()), ('7731111', NULL, 'Ijuí Airport', 'Ijui Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -28.3687, -53.8466, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ijuí airport ijui airport brazil br iju,ssij',
    NOW(), NOW()), ('7731118', NULL, 'Ipiranga Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.93907, -69.694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ipiranga airport ipiranga airport brazil br ipg,swii',
    NOW(), NOW()), ('7731119', NULL, 'Ipiaú Airport', 'Ipiau Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.174, -39.685, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ipiaú airport ipiau airport brazil br ipu,sniu',
    NOW(), NOW()), ('7731120', NULL, 'Irecê Airport', 'Irece Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.3399, -41.847, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'irecê airport irece airport brazil br ire,snic',
    NOW(), NOW()), ('7731122', NULL, 'Agropecuária Castanhais Airport', 'Agropecuaria Castanhais Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -8.7, -51.17417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'agropecuária castanhais airport agropecuaria castanhais airport brazil br agropecuaria castanhais airport,agropecuária castanhais airport,snyh',
    NOW(), NOW()), ('7731123', NULL, 'Itabuna Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.8105, -39.2904, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itabuna airport itabuna airport brazil br itn,snha',
    NOW(), NOW()), ('7731124', NULL, 'Itaqui Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.1731, -56.5367, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'itaqui airport itaqui airport brazil br itq,ssiq',
    NOW(), NOW()), ('7731135', NULL, 'Jacobina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.1632, -40.5531, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jacobina airport jacobina airport brazil br jcm,snjb',
    NOW(), NOW()), ('7731136', NULL, 'Jequié Airport', 'Jequie Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.8777, -40.0716, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jequié airport jequie airport brazil br jeq,snjk',
    NOW(), NOW()), ('7731138', NULL, 'Juína Airport', 'Juina Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.41765, -58.71059, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'juína airport juina airport brazil br jia,juina airport,juína airport,swjn',
    NOW(), NOW()), ('7731143', NULL, 'Jales Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.293, -50.5464, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jales airport jales airport brazil br jls,sdjl',
    NOW(), NOW()), ('7731145', NULL, 'Januária Airport', 'Januaria Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -15.4738, -44.3855, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'januária airport januaria airport brazil br jna,snjn',
    NOW(), NOW()), ('7731146', NULL, 'Ji-Paraná Airport', 'Ji-Parana Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.8708, -61.8465, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ji-paraná airport ji-parana airport brazil br aeroport jose coleto,aeroporto jose coleto,aeroporto josé coleto,aeroportul ji-parana,aeroportul ji-paraná,aeropuerto de ji-parana,aeropuerto de ji-paraná,aéroport josé coleto,flughafen ji-parana,flughafen ji-paraná,jpr,ji-parana airport,ji-paraná airport,jose coleto airport,josé coleto airport,sbji,frwdgah zhy-parana,ji=parana kong gang,фурудгоҳи жи-пороно,فرودگاه ژی-پارانا,ジ＝パラナ空港',
    NOW(), NOW()), ('7731147', NULL, 'Juruena Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.30583, -58.48944, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'juruena airport juruena airport brazil br aeroporto de juruena,aeroportul juruena,aeropuerto de juruena,flughafen juruena,jrn,juruena airport,lapangan terbang juruena,swju,juruena kong gang,ジュルエナ空港',
    NOW(), NOW()), ('7731210', NULL, 'Lábrea Airport', 'Labrea Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.27897, -64.7695, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lábrea airport labrea airport brazil br lbr,swlb',
    NOW(), NOW()), ('7731218', NULL, 'Leopoldina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -21.4661, -42.727, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leopoldina airport leopoldina airport brazil br lep,sndn',
    NOW(), NOW()), ('7731247', NULL, 'Livramento do Brumado Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -13.6506, -41.8339, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'livramento do brumado airport livramento do brumado airport brazil br livramento do brumado airport,snlb',
    NOW(), NOW()), ('7731257', NULL, 'Matupá Airport', 'Matupa Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -10.17028, -54.95278, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'matupá airport matupa airport brazil br aeroporto de matupa,aeroporto de matupá,aeroportul matupa,aeroportul matupá,aeropuerto de matupa,aeropuerto de matupá,flughafen regional orlando villas boas,mbk,matupa airport,matupá airport,orlando villas-boas regional airport,orlando villas-bôas regional airport,swxm,aerodrome de regional orlando villas boas,aérodrome de regional orlando villas boas,matoupa kong gang,マトゥパ空港',
    NOW(), NOW()), ('7731260', NULL, 'Maués Airport', 'Maues Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -3.37217, -57.7248, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maués airport maues airport brazil br mbz,swmw',
    NOW(), NOW()), ('7731297', NULL, 'Monte Alegre Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.9958, -54.0742, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'monte alegre airport monte alegre airport brazil br mte,monte alegre airport,snma',
    NOW(), NOW()), ('7731306', NULL, 'Mucuri Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.0489, -39.8642, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mucuri airport mucuri airport brazil br aerodromo mucuri,aeroportul mucuri,aeropuerto de mucuri,aeródromo mucuri,flugplatz mucuri,lapangan terbang mucuri,mvs,mucuri airport,snmu',
    NOW(), NOW()), ('7731340', NULL, 'Nanuque Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.8233, -40.3299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'nanuque airport nanuque airport brazil br nnu,snnu',
    NOW(), NOW()), ('7731342', NULL, 'Niquelândia Airport', 'Niquelandia Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -14.4349, -48.4915, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'niquelândia airport niquelandia airport brazil br nql,swnq',
    NOW(), NOW()), ('7731353', NULL, 'Novo Aripuanã Airport', 'Novo Aripuana Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -5.11803, -60.3649, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'novo aripuanã airport novo aripuana airport brazil br nvp,swna',
    NOW(), NOW()), ('7731372', NULL, 'Presidente João Batista Figueiredo Airport', 'Presidente Joao Batista Figueiredo Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.885, -55.58611, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'presidente joão batista figueiredo airport presidente joao batista figueiredo airport brazil br aeroporto presidente joao figueiredo,aeroporto presidente joão figueiredo,ops,presidente joao batista figueiredo airport,presidente joão batista figueiredo airport,sbsi,sinop airport',
    NOW(), NOW()), ('7731375', NULL, 'Oriximiná Airport', 'Oriximina Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.71408, -55.8362, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oriximiná airport oriximina airport brazil br aeroporto de oriximina,aeroporto de oriximiná,aeroportul oriximina,aeroportul oriximiná,aeropuerto de oriximina,aeropuerto de oriximiná,flughafen oriximina,flughafen oriximiná,lapangan terbang oriximina,orx,oriximina airport,oriximiná airport,snox,aerodrome d''oriximina,aérodrome d''oriximiná,frwdgah awryksymyna,orishimina kong gang,фурудгоҳи овриксимино,فرودگاه اوریکسیمینا,オリシミナ空港',
    NOW(), NOW()), ('7731377', NULL, 'Ourinhos Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9665, -49.9133, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ourinhos airport ourinhos airport brazil br ous,sdou',
    NOW(), NOW()), ('7731384', NULL, 'Pimenta Bueno Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -11.6416, -61.1791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pimenta bueno airport pimenta bueno airport brazil br pbq,swpm',
    NOW(), NOW()), ('7731389', NULL, 'Picos Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -7.06206, -41.5237, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'picos airport picos airport brazil br pcs,snpc',
    NOW(), NOW()), ('7731392', NULL, 'Prado Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -17.2967, -39.2712, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'prado airport prado airport brazil br pdf,snrd',
    NOW(), NOW()), ('7731398', NULL, 'Pinheiro Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.48361, -45.06722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pinheiro airport pinheiro airport brazil br phi,snye',
    NOW(), NOW()), ('7731399', NULL, 'Parintins Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -2.67302, -56.7772, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parintins airport parintins airport brazil br pin,swpi',
    NOW(), NOW()), ('7731405', NULL, 'Patos de Minas Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -18.6728, -46.4912, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'patos de minas airport patos de minas airport brazil br aeroporto de patos de minas,aeroportul patos de minas,aeropuerto de patos de minas,flughafen patos de minas,lapangan terbang patos de minas,poj,patos de minas airport,snpd,aerodrome de patos de minas,aérodrome de patos de minas,frwdgah patws dw mynas,pa tu si di mi na si ji chang,фурудгоҳи потус ду минос,فرودگاه پاتوس دو میناس,パトス・デ・ミナス,帕图斯迪米纳斯机场,帕圖斯迪米納斯機場',
    NOW(), NOW()), ('7731409', NULL, 'Pouso Alegre Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.2892, -45.9191, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pouso alegre airport pouso alegre airport brazil br ppy,snza',
    NOW(), NOW()), ('7731414', NULL, 'Municipal José Figueiredo Airport', 'Municipal Jose Figueiredo Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -20.7322, -46.6618, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'municipal josé figueiredo airport municipal jose figueiredo airport brazil br psw,snos',
    NOW(), NOW()), ('7731415', NULL, 'Pato Branco Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -26.2178, -52.6943, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pato branco airport pato branco airport brazil br aeroporto de pato branco,aeroportul pato branco,aeropuerto de pato branco,flughafen juvenal loureiro cardoso,lapangan terbang pato branco,pto,pato branco airport,sspb,aerodrome de juvenal loureiro cardoso,aérodrome de juvenal loureiro cardoso,パト・ブランコ空港',
    NOW(), NOW()), ('7731416', NULL, 'Porto de Moz Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -1.74145, -52.2361, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porto de moz airport porto de moz airport brazil br ptq,snmz',
    NOW(), NOW()), ('7731419', NULL, 'Paranavaí Airport', 'Paranavai Airport',
    NULL, 'BR', 'Brazil', NULL, NULL,
    -23.0899, -52.4885, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paranavaí airport paranavai airport brazil br pvi,sspi',
    NOW(), NOW()), ('7731422', NULL, 'Castro Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -24.8075, -49.9603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'castro airport castro airport brazil br qac,ssqt',
    NOW(), NOW()), ('7731423', NULL, 'Colatina Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -19.487, -40.5794, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colatina airport colatina airport brazil br qch,sncx',
    NOW(), NOW()), ('7731424', NULL, 'Botucatu Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -22.9395, -48.468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'botucatu airport botucatu airport brazil br qcj,sdbk',
    NOW(), NOW()), ('7731425', NULL, 'Canela Airport', NULL,
    NULL, 'BR', 'Brazil', NULL, NULL,
    -29.3702, -50.832, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canela airport canela airport brazil br aeroport de canela,aeroporto de canela,aeroportul canela,aeropuerto de canela,aéroport de canela,cel,canela airport,flughafen canela,lapangan terbang canela,qcn,sscn',
    NOW(), NOW());