INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('12110493', NULL, 'Dubai Seawings Seaplane Terminal', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.25972, 55.27163, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'dubai seawings seaplane terminal dubai seawings seaplane terminal united arab emirates ae dst,dubai seaplane terminal,dubai seawings seaplane terminal',
    NOW(), NOW()), ('12195566', NULL, 'Hamriya Free Zone Port', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.4685, 55.50169, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hamriya free zone port hamriya free zone port united arab emirates ae',
    NOW(), NOW()), ('12324578', NULL, 'Ruwais Port', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.13691, 52.75349, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ruwais port ruwais port united arab emirates ae',
    NOW(), NOW()), ('12324580', NULL, 'Ras al Khaimah Port', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.79447, 55.95525, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ras al khaimah port ras al khaimah port united arab emirates ae',
    NOW(), NOW()), ('12639995', NULL, 'Yas Marina Abu Dhabi', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.46681, 54.60771, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yas marina abu dhabi yas marina abu dhabi united arab emirates ae',
    NOW(), NOW()), ('12747982', NULL, 'Abu Dhabi International Airport', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.43776, 54.65092, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'abu dhabi international airport abu dhabi international airport united arab emirates ae abu dhabi international airport,mtar abwzby aldwly,مطار أبوظبي الدولي',
    NOW(), NOW()), ('12748012', NULL, 'Airport East District', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.31424, 55.71939, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport east district airport east district united arab emirates ae airport east district,shrq almtar,شرق المطار',
    NOW(), NOW()), ('12748124', NULL, 'Al Ain International Airport', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.28394, 55.62129, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'al ain international airport al ain international airport united arab emirates ae al ain international airport,mtar alʿyn aldwly,مطار العين الدولي',
    NOW(), NOW()), ('12748194', NULL, 'Abu Dhabi International Airport', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.43776, 54.65092, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'abu dhabi international airport abu dhabi international airport united arab emirates ae abu dhabi international airport,mtar abwzby aldwly,مطار ابوظبي الدولي',
    NOW(), NOW()), ('12748690', NULL, 'Al Ain International Airport 2', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.26255, 55.61115, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'al ain international airport 2 al ain international airport 2 united arab emirates ae 2 mtar alʿyn aldwly,2 مطار العين الدولي,al ain international airport 2',
    NOW(), NOW()), ('12748831', NULL, 'Industrial Port', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.29641, 54.41679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'industrial port industrial port united arab emirates ae industrial port,almynaʾ alsnaʿy,الميناء الصناعي',
    NOW(), NOW()), ('12749143', NULL, 'Al Sila Harbour', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.11188, 51.77283, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'al sila harbour al sila harbour united arab emirates ae al sila harbour,mynaʾ alslʿ,ميناء السلع',
    NOW(), NOW()), ('12749275', NULL, 'Marina Royal Compound', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.4799, 54.31355, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina royal compound marina royal compound united arab emirates ae marina royal compound,mjmʿ maryna almlky,مجمّع مارينا الملكى',
    NOW(), NOW()), ('12749366', NULL, 'Al Ain International Airport 1', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.29803, 55.62797, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'al ain international airport 1 al ain international airport 1 united arab emirates ae 1 mtar alʿyn aldwly,1 مطار العين الدولي,al ain international airport 1',
    NOW(), NOW()), ('12749387', NULL, 'Harbour', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    24.52299, 54.38708, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour harbour united arab emirates ae harbour,almynaʾ,الميناء',
    NOW(), NOW()), ('13060597', NULL, 'Dubai Int''L Airport', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.2519, 55.36792, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dubai int''l airport dubai int''l airport united arab emirates ae dubai int''l airport,mtar dby aldwly,مطار دبي الدولي',
    NOW(), NOW()), ('13060632', NULL, 'Al Hamriya Port', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.30071, 55.33339, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'al hamriya port al hamriya port united arab emirates ae al hamriya port,mynaʾ alhmryt,ميناء الحمرية',
    NOW(), NOW()), ('13060666', NULL, 'Port Saeed', NULL,
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.25101, 55.33272, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port saeed port saeed united arab emirates ae port saeed,bwr sʿyd,بور سعيد',
    NOW(), NOW()), ('13061119', NULL, 'Markaz Iţfā’ Bur Sa‘īd', 'Markaz Itfa'' Bur Sa`id',
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.25636, 55.32551, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'markaz iţfā’ bur sa‘īd markaz itfa'' bur sa`id united arab emirates ae markaz itfa'' bur sa`id,markaz iţfā’ bur sa‘īd,port saeed fire station,مركز اطفاء بر سعيد',
    NOW(), NOW()), ('13304380', NULL, 'Gharbiyah Early Warning Site Heliport', 'GharbiyahEarlyWarningSiteHeliport',
    NULL, 'AE', 'United Arab Emirates', NULL, NULL,
    25.64761, 56.12874, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gharbiyah early warning site heliport gharbiyahearlywarningsiteheliport united arab emirates ae gharbiyah early warning site heliport,gharbiyahearlywarningsiteheliport',
    NOW(), NOW()), ('1110363', NULL, 'Bandar Kandao', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.95719, 70.66029, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar kandao bandar kandao afghanistan af bandar kandao,pereval bandarkandao',
    NOW(), NOW()), ('1115022', NULL, 'Senjelay Manda', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.39306, 67.12694, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'senjelay manda senjelay manda afghanistan af sandzelai mandeh,sandzelay mandeh,sandzêlay māndêh,sandzêlaī māndêh,sendzelay mandah,sendzelay māndah,senjelay manda,senjelay mandeh,senjelay mānḏeh,senjelay mānḏēh,sindzhilimandekh,سنځلی مانده',
    NOW(), NOW()), ('1120493', NULL, 'Qizil Qal‘ah', 'Qizil Qal''ah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    37.19041, 68.61126, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'qizil qal‘ah qizil qal''ah afghanistan af gizil qala,kyzylkala,qezel qal`a,qezel qal`eh,qezel qal‘a,qezel qal‘eh,qizil qal`ah,qizil qala,qizil qal‘ah,seckhan bandac,sher khan,sherkhan bandar,shir khan,shir khan bandar,shirhan,shīr khān,sēċkhān bandaċ,قزل قلعه',
    NOW(), NOW()), ('1121765', NULL, 'Dê Walī Māndêh', 'De Wali Mandeh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.10587, 66.13987, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dê walī māndêh de wali mandeh afghanistan af de wali mandah,de wali mandeh,dê walī māndêh,valimandekh,wali mandah,wali mandeh,wali māndah,wali mānḏeh,walī māndêh,d wly mandh,wly mandh,د ولی مانده,ولی مانده,ḏe wali mānḏəh',
    NOW(), NOW()), ('1121835', NULL, 'Wêch Bāndar', 'Wech Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.05225, 70.72216, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wêch bāndar wech bandar afghanistan af gora vachbandar,wac bandar,wach bandar,wach bāndar,wač bāndar,wech bandar,wêch bāndar,bandr khshk,wch bandr,باندرٔ خشك,وچ باندر',
    NOW(), NOW()), ('1123000', NULL, 'Talūkān', 'Talukan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.46285, 65.32529, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'talūkān talukan afghanistan af talukan,talūkān,tulukhan,tlwkan,تلوکان',
    NOW(), NOW()), ('1123001', NULL, 'Talūkān', 'Talukan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.44386, 65.31652, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'talūkān talukan afghanistan af talukan,talūkān,tlwkan,تلوکان',
    NOW(), NOW()), ('1123004', NULL, 'Taloqan', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.73605, 69.53451, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'taloqan taloqan afghanistan af khanabad,tqn,taikhan,taleqan,talikan,talikhan,taliqan,talkan,talokan,taloqan,talugan,talukan,talukanas,taluqan,tologan,tâloqân,tāleqān,tāloqān,tāluqān,tālīqān,ta lu kan,talokam,talokuvan,taloqana,talqan,таликан,талукан,تالقان,तालोक़ान,तालोकां,தலோகுவான்,თალიკანი,塔卢坎',
    NOW(), NOW()), ('1123226', NULL, 'Takhbandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.14034, 64.39658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'takhbandar takhbandar afghanistan af takhbandar,takhbanḏaṟ,tkhbndr,تخبندر',
    NOW(), NOW()), ('1123230', NULL, 'Wilāyat-e Takhār', 'Wilayat-e Takhar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.66667, 69.75, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'wilāyat-e takhār wilayat-e takhar afghanistan af lalawigan ng takhar,pravincyja takhar,propinsi takhar,provincia takhar,provincia de takhar,provincija takar,provinco tahar,provinco taĥar,província de takhar,tachar,tacharo provincija,tachár,tahar,tahar vilayeti,tahara,tahār,tahāra,takhar,takhar province,takhar seng,takhar séng,takhar ajmag,takhar probintzia,takhari provints,takharin maakunta,takhâr,takhār,takhāri provints,talugan,talukan,taluqan,taxar,taxor viloyati,tekhar province,texar,təxar,velayat-e takhar,velāyat-e takhār,vilojati takhor,wilayah takhar,wilayat-e takhar,wilāyat-e takhār,astwn tkhar,ta ha er sheng,ta ha sheng,tahaleuju,taharu zhou,takar,takhar,takhar vylayyty,takhara,takhara pradesa,takhara pranta,takhara suba,thakh har,tkhar,tkhar wlayt,tkhar wylayt,wlayt tkhar,ταχάρ,вилояти тахор,правінцыя тахар,провинција такар,тахар,тахар аймаг,տախար,תח''אר,آستون تخار,تاخار ۋىلايىتى,تخار,تخار ولايت,تخار ویلایت,صوبہ تخار,ولاية تخار,ولایت تخار,پارێزگای تەخار,तख़ार प्रान्त,तखार,तखार प्रान्त,তখর প্রদেশ,ਤਖਾਰ ਸੂਬਾ,તખાર,டகார்,టఖర్,ತಖರ್,ටක්හාර්,ทัคฮาร์,თახარის პროვინცია,タハール州,塔哈尔省,塔哈爾省,塔哈省,타하르주',
    NOW(), NOW()), ('1124250', NULL, 'Slēmānzaī', 'Slemanzai',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.5025, 66.96433, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'slēmānzaī slemanzai afghanistan af slemanzai,slemanzi,slimanzai,slimānzaī,slēmānzaī,slēmānzi,soleymanzi,soleymānzi,slmanzy,slymanzy,سلمانزی,سلیمانزی,سلېمانزی',
    NOW(), NOW()), ('1124257', NULL, 'Sulaīmān Nāwêr', 'Sulaiman Nawer',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.07859, 65.69083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sulaīmān nāwêr sulaiman nawer afghanistan af ozero suleymannavar,soleman nawer,soleyman nawar,soleymān nāwar,solēmān nāweṟ,sulaiman nawer,sulaīmān nāwêr,jwy suliman,slyman nawr,جوئ سُلِيمان,سلیمان ناور',
    NOW(), NOW()), ('1124704', NULL, 'Kharah-ye Siyāh', 'Kharah-ye Siyah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.59125, 65.05086, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kharah-ye siyāh kharah-ye siyah afghanistan af khara-i-syah,kharah-ye siah,kharah-ye siyah,kharah-ye siyāh,kharah-ye sīāh,khaṟa-i-syāh,loka-i-bor,loka-i-bōṟ,lukah-ye bor,lukah-ye bōr,خرۀ سیاه,لکۀ بور',
    NOW(), NOW()), ('1124874', NULL, 'Shūlūkak', 'Shulukak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.25206, 66.43589, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shūlūkak shulukak afghanistan af shulukak,shūlūkak,sulukak,shwlwkk,šūlūkak,شولوکک',
    NOW(), NOW()), ('1125654', NULL, 'Shamnah Sar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.59454, 66.6603, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shamnah sar shamnah sar afghanistan af samnasar,shamnah sar,shamnasar,shamsanar,shmnh sr,shmnsr,šamnasar,شمنسر,شمنه سر',
    NOW(), NOW()), ('1126907', NULL, 'Kōh-e Sar Lūkah', 'Koh-e Sar Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.2904, 65.69459, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e sar lūkah koh-e sar lukah afghanistan af gora sarluka,koh-e sar lukah,kohe sarluka,kohe saṟlūka,kuh-e sar lukah,kuh-e sarlowkah,kōh-e sar lūkah,kūh-e sar lūkah,kūh-e sarlowkah,kwh sr lwkh,کوه سر لوکه',
    NOW(), NOW()), ('1130027', NULL, 'Qal‘ah-ye Bandar', 'Qal''ah-ye Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.32922, 64.57073, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'qal‘ah-ye bandar qal''ah-ye bandar afghanistan af qal`a-i-bandar,qal`ah-ye bandar,qal`eh-ye bandar,qal‘a-i-banḏaṟ,qal‘ah-ye bandar,qal‘eh-ye bandar,قلعۀ بندر',
    NOW(), NOW()), ('1130470', NULL, 'Pōrtah Shiglōn Kêlay', 'Portah Shiglon Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.68607, 67.48569, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah shiglōn kêlay portah shiglon kelay afghanistan af porta seglon kalay,portah shiglon kelay,portashiglon-kalay,powrtah sheglown kalay,pōrtah shiglōn kêlay,pōṟta seglōn kalay,pwrth shglwn kly,پورته شگلون کلی',
    NOW(), NOW()), ('1130471', NULL, 'Pōrtah Mīl', 'Portah Mil',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.25473, 66.12388, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah mīl portah mil afghanistan af porta mil,portah mil,purtah mil,pōrtah mīl,pōṟta mīl,pūrtah mīl,urochishche portamil'',urochishche portamil’,myl bala,pwrth myl,ميلٔ بالا,پورته میل',
    NOW(), NOW()), ('1130472', NULL, 'Pōrtah Kārēzgay Kêlay', 'Portah Karezgay Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.72458, 67.45105, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah kārēzgay kêlay portah karezgay kelay afghanistan af porta karezgay kalay,porta karizgay kalay,portah karezgay kelay,portakarezgay-kalay,powrtah karizgay kalay,powrtah kāṟīzgay kalay,pōrtah kārēzgay kêlay,pōṟta kāṟēzgay kalay,pōṟta kāṟīzgay kalay,pwrth karyzgy kly,پورته کاریزگی كلی,پورته کارېزگی کلی',
    NOW(), NOW()), ('1130473', NULL, 'Pōrtah Kêlay', 'Portah Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.04306, 67.74177, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah kêlay portah kelay afghanistan af porta kalay,portah kelay,powrtah kalay,pōrtah kêlay,pōṟta kalay,pwrth kly,پورته کلی',
    NOW(), NOW()), ('1130474', NULL, 'Pōrtah Ghanī Murgh', 'Portah Ghani Murgh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.46245, 63.31883, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pōrtah ghanī murgh portah ghani murgh afghanistan af gani morgh,ganimurgh,gānī morgh,porta ghani murgh,portaganimurg,portah ghani morgh,portah ghani murgh,portah ghanī morgh,purtah ghani morgh,pōrtah ghanī murgh,pōṟta ghani muṟgh,pūrtah ghanī morgh,pwrth ghny mrgh,پورته غنی مرغ',
    NOW(), NOW()), ('1131029', NULL, 'Pas-e Lukah', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.53137, 64.37186, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pas-e lukah pas-e lukah afghanistan af pas-e lokah,pas-e lukah,pase loka,ps lkh,پس لکه',
    NOW(), NOW()), ('1134482', NULL, 'Lūkah Sang', 'Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.73432, 61.77436, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah sang lukah sang afghanistan af luka sang,lukah sang,lūka sang,lūkah sang,lwkh sng,لوکه سنگ',
    NOW(), NOW()), ('1134483', NULL, 'Lūkasang', 'Lukasang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.52693, 65.96379, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkasang lukasang afghanistan af lokah sang,lukasang,lōkah sang,lūkasang,lwkh sng,lwksng,لوکسنگ,لوکه سنگ',
    NOW(), NOW()), ('1134484', NULL, 'Lūkah-ye Siyāh', 'Lukah-ye Siyah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.12156, 64.54233, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye siyāh lukah-ye siyah afghanistan af luka-i-syah,lukah-e siah,lukah-ye siah,lukah-ye siyah,lūka-i-syāh,lūkah-e sīāh,lūkah-ye siyāh,lūkah-ye sīāh,لوکۀ سیاه',
    NOW(), NOW()), ('1134485', NULL, 'Lūkah-ye Surkh', 'Lukah-ye Surkh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.23971, 63.46421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye surkh lukah-ye surkh afghanistan af luka-i-surkh,lukah-ye sorkh,lukah-ye surkh,lūka-i-suṟkh,lūkah-ye sorkh,lūkah-ye surkh,لوکۀ سرخ',
    NOW(), NOW()), ('1134486', NULL, 'Lūkah-ye Raḩmatullāh', 'Lukah-ye Rahmatullah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.26082, 64.65656, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye raḩmatullāh lukah-ye rahmatullah afghanistan af gora lukayi-rakhmatulla,luka-i-rahmatullah,lukah-ye rahmatullah,lukeh-ye rahmatollah,lūka-i-ṟaḩmatullāh,lūkah-ye raḩmatullāh,lūkeh-ye raḩmatollāh,لوکۀ رحمت اللـه',
    NOW(), NOW()), ('1134487', NULL, 'Tangī-ye Lūkah', 'Tangi-ye Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.26062, 65.70038, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tangī-ye lūkah tangi-ye lukah afghanistan af surkh,suṟkh,tangi lowkah,tangi luka,tangi surkh,tangi-ye lukah,tangi-ye surkh,tangiluka,tangī lowkah,tangī lūka,tangī suṟkh,tangī-ye lūkah,tangī-ye surkh,tngy lwkh,tngy srkh,تنگی سرخ,تنگی لوکه',
    NOW(), NOW()), ('1134590', NULL, 'Lukah-ye Surkh', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.09382, 65.45234, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye surkh lukah-ye surkh afghanistan af lokae surkh,lokae suṟkh,lokeh-ye sorkh,lukah-ye surkh,لکۀ سرخ',
    NOW(), NOW()), ('1134594', NULL, 'Lakah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.201, 63.29701, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lakah sang lakah sang afghanistan af lakah sang,lokasang,lokeh sang,lokka,luka sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134595', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.76534, 64.78793, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokasang,lokehsang,lukah sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134596', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.51964, 64.10149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af lokasang,lokehsang,lukah sang,lukasang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1134599', NULL, 'Lōkānō Ḏab', 'Lokano Dab',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.59945, 63.5421, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lōkānō ḏab lokano dab afghanistan af lokano d`ab,lokano dab,lukanu dab,lōkāno d‘ab,lōkānō ḏab,lūkānū dab ,لوکانو ډب',
    NOW(), NOW()), ('1134600', NULL, 'Lukah-ye Khwājak', 'Lukah-ye Khwajak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.52637, 65.10808, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah-ye khwājak lukah-ye khwajak afghanistan af loka-i-khwajak,loka-i-khwājak,lokah-ye khvajak,lokah-ye khvājak,lukah-ye khwajak,lukah-ye khwājak,لکۀ خواجک',
    NOW(), NOW()), ('1134601', NULL, 'Lōkā Khēl', 'Loka Khel',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.01634, 69.71869, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lōkā khēl loka khel afghanistan af loka khel,lokakhejl'',lokakhel,lokakheyl'',lokakheyl’,lukakhel,lukakheyl,lōkā khēl,lōkākhēl,lūkākheyl,lūkākhēl,lwka khyl,локахейль,لوكا خيل,لوکا خېل',
    NOW(), NOW()), ('1134892', NULL, 'Lālō Kalā', 'Lalo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.49764, 68.77206, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lālō kalā lalo kala afghanistan af lalo kala,lalow kala,lalow qal`eh,lalu,lalu kala,lalu qala,lālo kalā,lālow kalā,lālow qal‘eh,lālō kalā,razvaliny lalukala,lalw kla,لالو کلا',
    NOW(), NOW()), ('1134919', NULL, 'Lālī Māndêh', 'Lali Mandeh',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.65528, 67.07627, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lālī māndêh lali mandeh afghanistan af lali mandah,lali mandeh,lalimandekh,lāli māndah,lāli mānḏeh,lālī māndêh,jwy laly,laly mandh,جوئ لالی,لالی مانده',
    NOW(), NOW()), ('1134986', NULL, 'Lukah Sang', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.13099, 64.46718, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lukah sang lukah sang afghanistan af gora lukasang,lakasang,lokasang,lokehsang,lukah sang,lkh sng,لکه سنگ',
    NOW(), NOW()), ('1135980', NULL, 'Khōshāmand', 'Khoshamand',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.68567, 68.23801, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'khōshāmand khoshamand afghanistan af khosamand,khoshamand,khos̄āmanḏ,khus amad,khusamand,khush amad,khushamand,khus̄ āmad,khus̄āmand,khvosh amad,khvosh mand,khvosh āmad,khvoshamand,khvoshāmand,khōshāmand,khūsh āmad,khwsh amd,khwshamnd,خوش آمد,خوشامند',
    NOW(), NOW()), ('1138454', NULL, 'Kharābah-ye Kamāl Khān', 'Kharabah-ye Kamal Khan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.30713, 61.87042, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kharābah-ye kamāl khān kharabah-ye kamal khan afghanistan af band-i-kamal khan,band-i-kamāl khan,bandar-i-kamal khan,bandar-i-kamāl khān,kharabah-ye kamal khan,kharabeh-ye kamal khan,kharābah-ye kamāl khān,kharābeh-ye kamāl khān,خرابۀ کمال خان',
    NOW(), NOW()), ('1138457', NULL, 'Kalātah-ye Kamāl Khān', 'Kalatah-ye Kamal Khan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.3053, 61.89575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalātah-ye kamāl khān kalatah-ye kamal khan afghanistan af bandar-i-kamal khan,bandar-i-kamāl khān,kalatah-ye kamal khan,kalate kamal khan,kalātah-ye kamāl khān,kalātē kamāl khān,kamal khan,kamal khan bandar,kamāl khān,kamāl khān bandar,کلاتۀ کمال خان',
    NOW(), NOW()), ('1139106', NULL, 'Kōh-e Jōlōgah', 'Koh-e Jologah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.84591, 62.35355, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e jōlōgah koh-e jologah afghanistan af gory dzhuluka,koh-e jologah,koh-e julukah,kohe jologa,kohe juluka,kohe jōlōga,kohe jūlūka,kuh-e jologa,kuh-e jowlugah,kōh-e jōlōgah,kōh-e jūlūkah,kūh-e jowlūgah,kūh-e jōlōga,kwh jwlwgh,kwh jwlwkh,کوه جولوکه,کوه جولوگه',
    NOW(), NOW()), ('1142562', NULL, 'Ilman-e Ūchownah', 'Ilman-e Uchownah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.72245, 66.78947, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ilman-e ūchownah ilman-e uchownah afghanistan af elman-e uchawnah,elman-i-uchawna,il''mani-uchavna,ilman-e uchownah,ilman-e ūchownah,il’mani-uchavna,almn awchwnh,ильмани-учавна,المن اوچونه',
    NOW(), NOW()), ('1144490', NULL, 'Dahan-e Lūkah Sang', 'Dahan-e Lukah Sang',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.57912, 65.93241, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dahan-e lūkah sang dahan-e lukah sang afghanistan af dahan-e lukah sang,dahan-e lukasang,dahan-e lūkah sang,dahan-e lūkasang,dhn lwkh sng,دهن لوکه سنگ',
    NOW(), NOW()), ('1144715', NULL, 'Dahan Bandar', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.04475, 65.73356, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dahan bandar dahan bandar afghanistan af dahan bandar,dakhanbandar,dhn bndr,دهن بندر',
    NOW(), NOW()), ('1145863', NULL, 'Chahār Burjak', 'Chahar Burjak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.38914, 62.13086, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chahār burjak chahar burjak afghanistan af caharburjak,chahar burjak,chaharborjak,chahār burjak,chahārborjak,chakharburdzhak,chhar brjk,chharbrjk,čahārburjak,چهار برجک,چهاربرجك',
    NOW(), NOW()), ('1145864', NULL, 'Chahār Burjah', 'Chahar Burjah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.23555, 67.03381, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'chahār burjah chahar burjah afghanistan af caharburja,cahāṟbuṟja,chahar borjeh,chahar burjah,chaharborja,chahār borjeh,chahār burjah,chahārborja,chhar brjh,چهار برجه',
    NOW(), NOW()), ('1146335', NULL, 'Bulōkah', 'Bulokah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.3248, 65.86064, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bulōkah bulokah afghanistan af boloka,boluka,bolōka,bolūka,bulokah,bulōkah,blwkh,بلوکه',
    NOW(), NOW()), ('1146499', NULL, 'Bīābān Darah', 'Biaban Darah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    31.44983, 65.92394, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bīābān darah biaban darah afghanistan af biaban darah,biaban darreh,biabandarra,byaban darrah,byābān ḏaṟṟah,bīābān darah,bīābān darreh,byaban darah,byaban drh,بيابان دَرَه,بیابان دره',
    NOW(), NOW()), ('1146559', NULL, 'Bindaray', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.05583, 68.44039, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bindaray bindaray afghanistan af bandaray,banḏaṟay,bendaray,bindaray,bndry,بندری',
    NOW(), NOW()), ('1146965', NULL, 'Bar Gulō Kalā', 'Bar Gulo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.6511, 69.23363, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bar gulō kalā bar gulo kala afghanistan af bar golo kala,bar golo kalā,bar gulo kala,bar gulō kalā,bar-gulukala,br glw kla,بر گلو كلا,بر گلو کلا',
    NOW(), NOW()), ('1147209', NULL, 'Kōh-e Bandar Ghūnak', 'Koh-e Bandar Ghunak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.67171, 65.1245, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kōh-e bandar ghūnak koh-e bandar ghunak afghanistan af koh-e bandar ghunak,kohe bandarghunak,kohe banḏaṟghūnak,kuh-e bandarghunak,kōh-e bandar ghūnak,kūh-e bandarghūnak,kwh bndrghwnk,کوه بندرغونک',
    NOW(), NOW()), ('1147210', NULL, 'Bandar Ghūnak', 'Bandar Ghunak',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.65932, 65.1341, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar ghūnak bandar ghunak afghanistan af bandar ghunak,bandar ghūnak,bandarghunak,banḏaṟghūnak,bndrghwnk,بندرغونک',
    NOW(), NOW()), ('1147211', NULL, 'Bandar-e Wasaţī', 'Bandar-e Wasati',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.28893, 61.90769, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e wasaţī bandar-e wasati afghanistan af bandar-e vasati,bandar-e vasaţī,bandar-e wasati,bandar-e wasaţī,bandare wasate,bandare wasati,banḏaṟe wasaṯē,banḏaṟe wasaṯī,bndr wsty,بندر وسطی',
    NOW(), NOW()), ('1147212', NULL, 'Bandar-e Shamālī', 'Bandar-e Shamali',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.29444, 61.90697, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e shamālī bandar-e shamali afghanistan af bandar-e shamali,bandar-e shamālī,bandar-e shomali,bandar-e shomālī,bandare samali,bandare šamālī,bndr shmaly,بندر شمالی',
    NOW(), NOW()), ('1147213', NULL, 'Bandar-e Mullāhā', 'Bandar-e Mullaha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.35648, 64.58443, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e mullāhā bandar-e mullaha afghanistan af bandar,bandar-e mollaha,bandar-e mollāhā,bandar-e mullaha,bandar-e mullāhā,bandar-i-mullaha,banḏaṟ-i-mullāhā,bndr mla ha,بندر ملا ها',
    NOW(), NOW()), ('1147214', NULL, 'Bandar-e Junūbī', 'Bandar-e Junubi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    30.28385, 61.93471, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e junūbī bandar-e junubi afghanistan af bandar-e jonubi,bandar-e jonūbī,bandar-e junubi,bandar-e junūbī,bandare janubi,banḏaṟe janūbī,bndr jnwby,بندر جنوبی',
    NOW(), NOW()), ('1147215', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.33672, 64.58087, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi,bandar-e `abdul baqi,bandar-e ‘abd ol bāqī,bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi,bandar-i-`abdulbaqi (1),banḏaṟ-i-‘abdulbāqī,banḏaṟ-i-‘abdulbāqī (1),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1147216', NULL, 'Bandar Darah', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.06394, 70.76343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar darah bandar darah afghanistan af bandar darah,bandar darreh,dolina bandardarra,bndr drh,بندر دره,درۀ بندر',
    NOW(), NOW()), ('1147217', NULL, 'Tahānah-ye Bandar', 'Tahanah-ye Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    36.22056, 71.15775, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tahānah-ye bandar tahanah-ye bandar afghanistan af tahana-i-bandar,tahanah-ye bandar,tahaneh-ye bandar,tahāna-i-banḏar,tahānah-ye bandar,tahāneh-ye bandar,thanh y bndr,تهانه ی بندر',
    NOW(), NOW()), ('1148845', NULL, 'Alō Kalā', 'Alo Kala',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.29736, 68.26636, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alō kalā alo kala afghanistan af alo kala,alo kalā,alukala,alō kalā,alw kla,الو کلا,قلعهٔٔ الو',
    NOW(), NOW()), ('1148924', NULL, '‘Alī Manşūr', '''Ali Mansur',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.48402, 62.61785, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘alī manşūr ''ali mansur afghanistan af alimansur,`ali mansur,علی منصور,‘alī manşūr',
    NOW(), NOW()), ('1148925', NULL, '‘Alī Manşūr', '''Ali Mansur',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    34.46579, 62.27037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘alī manşūr ''ali mansur afghanistan af letnik alimansur,`ali mansur,علی منصور,‘alī manşūr',
    NOW(), NOW()), ('1423713', NULL, 'Maimana Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.93034, 64.76132, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maimana airport maimana airport afghanistan af mmz,maimana airport,maimanah airport,maymaneh airport,maīmanah airport,oamn',
    NOW(), NOW()), ('1423933', NULL, 'Dablukanṯāl Ghar', 'Dablukantal Ghar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34343, 71.11074, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dablukanṯāl ghar dablukantal ghar afghanistan af dablukantal ghar,dablukanṯāl ghar,gora dablukantal''gar,gora dablukantal’gar,kwh dblkntal,دبلکنټال غر,كوهٔ دبلكنتال,ḏablukantāl ghar',
    NOW(), NOW()), ('1424203', NULL, 'Tapah-ye Lūkah', 'Tapah-ye Lukah',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.69658, 63.46661, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tapah-ye lūkah tapah-ye lukah afghanistan af tapa-i-iuka,tapa-i-iūka,tapah-ye lukah,tapah-ye lūkah,tappeh-ye yowkah,تپۀ لوکه',
    NOW(), NOW()), ('1424430', NULL, 'Lūkah-ye Jigarīhā', 'Lukah-ye Jigariha',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.06858, 64.52708, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye jigarīhā lukah-ye jigariha afghanistan af luka-i-jegariha,lukah-e jegariha,lukah-ye jigariha,lūka-i-jegaṟihā,lūkah-e jegarīhā,lūkah-ye jigarīhā,لوکۀ جگری ها',
    NOW(), NOW()), ('1424435', NULL, 'Lūkah-ye Dūrānī', 'Lukah-ye Durani',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.09668, 64.51856, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye dūrānī lukah-ye durani afghanistan af luka-i-durrani,lukah-e dorrani,lukah-ye durani,lūka-i-ḏuṟṟāni,lūkah-e dorrānī,lūkah-ye dūrānī,لوکۀ دورانی',
    NOW(), NOW()), ('1424507', NULL, 'Lūkah-ye Ḩowẕhā-ye Buz', 'Lukah-ye Howzha-ye Buz',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.08685, 64.66376, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye ḩowẕhā-ye buz lukah-ye howzha-ye buz afghanistan af luka-i-hawdzha-i-buz,lukah-e howzha-ye boz,lukah-ye howzha-ye buz,lūka-i-ḩawḏẕhā-i-buz,lūkah-e ḩowẕhā-ye boz,lūkah-ye ḩowẕhā-ye buz,لوکۀ حوض های بز',
    NOW(), NOW()), ('1424508', NULL, 'Lūkah-ye Quranghay', 'Lukah-ye Quranghay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.08916, 64.64684, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye quranghay lukah-ye quranghay afghanistan af luka-i-qoranghay,lukah-e qoranghay,lukah-ye quranghay,lūka-i-qoṟanghay,lūkah-e qoranghay,lūkah-ye quranghay,لوکۀ قرنغی',
    NOW(), NOW()), ('1424519', NULL, 'Lūkah-ye Chāh-e Buzkash', 'Lukah-ye Chah-e Buzkash',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.10179, 64.64257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lūkah-ye chāh-e buzkash lukah-ye chah-e buzkash afghanistan af luka-i-cahe buzkas,lukah-e chah-e bozkash,lukah-ye chah-e buzkash,lūka-i-cāhe buzkās,lūkah-e chāh-e bozkāsh,lūkah-ye chāh-e buzkash,لوکۀ چاه بز کش',
    NOW(), NOW()), ('1424681', NULL, 'Manţaqah-ye Bandar', 'Mantaqah-ye Bandar',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34306, 64.58667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manţaqah-ye bandar mantaqah-ye bandar afghanistan af mantaqa-i-bandar,mantaqa-i-banḏaṟ,mantaqah-ye bandar,mantaqeh-ye bandar,manţaqah-ye bandar,manţaqeh-ye bandar,mntqh bndr,منطقه بندر',
    NOW(), NOW()), ('1424684', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.34716, 64.57879, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi (3),bandar-e `abdul baqi,bandar-e ‘abd ol bāqī (3),bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi (3),banḏaṟ-i-‘abdulbāqī (3),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1424685', NULL, 'Bandar-e ‘Abdul Bāqī', 'Bandar-e ''Abdul Baqi',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    35.3579, 64.56267, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bandar-e ‘abdul bāqī bandar-e ''abdul baqi afghanistan af bandar-e `abd ol baqi (2),bandar-e `abdul baqi,bandar-e ‘abd ol bāqī (2),bandar-e ‘abdul bāqī,bandar-i-`abdulbaqi (2),banḏaṟ-i-‘abdulbāqī (2),bndr ʿbdl baqy,بندر عبدل باقی',
    NOW(), NOW()), ('1425130', NULL, 'Lês̲h̲ōlō Kêlay', 'Lesholo Kelay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.86401, 69.63468, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lês̲h̲ōlō kêlay lesholo kelay afghanistan af lesholo kelay,lesholokay,lesholukalay,leshowlo kalay,lesolo kalay,les̲h̲owlo kalay,lês̲h̲ōlō kêlay,lês̲h̲ōlōkay,lěšolo kalay,لښولو کلی,لښولوکی',
    NOW(), NOW()), ('1434136', NULL, 'Urgun Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    32.93222, 69.15639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'urgun airport urgun airport afghanistan af oaog,urn,urgun,urgun airport',
    NOW(), NOW()), ('1434427', NULL, '‘Ālimān Kōṯkay', '''Aliman Kotkay',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.25147, 69.87035, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, '‘ālimān kōṯkay ''aliman kotkay afghanistan af alemankotkay,`aleman kotkay,`aleman kotkey,`aleman kowtkay,`aliman kotkay,عالمان كوتكی,عالمان کوټکی,‘ālemān kowtkay,‘ālemān kōtkay,‘ālimān kōṯkay,‘ālêmān kōṯkêy',
    NOW(), NOW()), ('1434618', NULL, 'Khost International Airport', NULL,
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.33359, 69.95192, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'khost international airport khost international airport afghanistan af kht,khost,khost airfield,matun,matun airfield,mātūn airfield,oaks,mydan hwayy khwst,ميدانٔٔ هوائئ خوست',
    NOW(), NOW()), ('1434876', NULL, 'Malōkān', 'Malokan',
    NULL, 'AF', 'Afghanistan', NULL, NULL,
    33.44123, 69.10739, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'malōkān malokan afghanistan af malokan,malukan,malōkān,malūkān,malwkan,mlwkan,مالوكان,ملوکان',
    NOW(), NOW());