INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('2207288', NULL, 'Ampol Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.40833, 153.15139, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ampol wharf ampol wharf australia au',
    NOW(), NOW()), ('2207309', NULL, 'Point Lookout', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.42726, 153.53664, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'point lookout point lookout australia au point lookout,point lukaut,поинт лукаут',
    NOW(), NOW()), ('2207387', NULL, 'Cairns International Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.88583, 145.75528, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'cairns international airport cairns international airport australia au cns,cairns,ybcs',
    NOW(), NOW()), ('2207424', NULL, 'Thursday Island Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.58943, 142.22278, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'thursday island harbour thursday island harbour australia au',
    NOW(), NOW()), ('2207476', NULL, 'Ocean Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.05139, 145.9125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ocean wharf ocean wharf australia au ocean wharf',
    NOW(), NOW()), ('2207477', NULL, 'McGaw Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.05278, 145.91111, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mcgaw pier mcgaw pier australia au jones pier,mcgaw pier',
    NOW(), NOW()), ('2207545', NULL, 'Saint Kilda Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.86431, 144.96959, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saint kilda pier saint kilda pier australia au',
    NOW(), NOW()), ('2207604', NULL, 'Princes Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.84282, 144.92626, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'princes pier princes pier australia au princes pier,プリンセス・ピア',
    NOW(), NOW()), ('2207605', NULL, 'Station Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.84445, 144.93107, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'station pier station pier australia au station pier,town pier,che zhan ma tou,huo che zhan zhan qiao,火車站棧橋,火车站栈桥,車站碼頭',
    NOW(), NOW()), ('2207607', NULL, 'Saint Kilda Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.87556, 144.97806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saint kilda marina saint kilda marina australia au',
    NOW(), NOW()), ('2207613', NULL, 'Middle Brighton Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.90875, 144.9832, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'middle brighton pier middle brighton pier australia au',
    NOW(), NOW()), ('2207800', NULL, 'Five Dock Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.1429, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'five dock bay five dock bay australia au five dock bay',
    NOW(), NOW()), ('2207801', NULL, 'Five Dock Point', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.84417, 151.14472, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'five dock point five dock point australia au five dock point',
    NOW(), NOW()), ('2207848', NULL, 'North Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.80778, 151.2775, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'north harbour north harbour australia au',
    NOW(), NOW()), ('2207955', NULL, 'Port Lihou', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.75, 142.2, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lihou port lihou australia au',
    NOW(), NOW()), ('2207968', NULL, 'Port Albany', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -10.73359, 142.59893, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port albany port albany australia au',
    NOW(), NOW()), ('2208268', NULL, 'Sydney International Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.94611, 151.17722, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'sydney international airport sydney international airport australia au aeroport sidnej,aeroport sydney-kingsford smith,aeroporto internacional de sydney,aeroporto internazionale kingsford smith,aeropuerto internacional kingsford smith,aéroport sydney-kingsford smith,bandar udara sydney,flughafen sydney,kingsford-smith airport,lapangan terbang antarabangsa kingsford smith,mascot airport,mezhdunarodnyj aehroport sidneja,međunarodni aerodromkingsford smit sidnej,syd,sydney airport,sydney international airport,yssy,frwdgah sydny,mtar sydny,nml htʻwph sl sydny,shidoni guo ji kong gang,sidani vimanatala,sideuni gonghang,tha xakasyan nana cha ti khing sf xrd smith,xi ni ji chang,аеропорт сідней,международный аэропорт сиднея,међународни аеродромкингсфорд смит сиднеј,נמל התעופה של סידני,فرودگاه سیدنی,مطار سيدني,सिडनी विमानतळ,ท่าอากาศยานนานาชาติคิงส์ฟอร์ดสมิธ,シドニー国際空港,悉尼机场,시드니 공항',
    NOW(), NOW()), ('2208291', NULL, 'Sydney Harbour Bridge', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.85249, 151.21046, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'sydney harbour bridge sydney harbour bridge australia au cau cang sydney,cầu cảng sydney,daraja la bandari ya sydney,droichead chuan sydney,garbor-bridzh,harbor brij,harbour bridge,harbour bridge  sydney,jambatan pelabuhan sydney,jembatan sydney harbour,kharbor-bridzh,kharbur bridzh,most kharbar-brydzh,pont harbwr sydney,pont del port de sydney,ponte da baia de sydney,ponte da baía de sydney,puent d''a badia de sydney,puent d''a badía de sydney,sidinee tɛ kondoloko,sidnej kharbor bridzh,sidnejaus uosto tiltas,sidnejski most,sidnejski zalivski most,sidney liman koepruesue,sidney liman köprüsü,sidnėjaus uosto tiltas,sydney hafenbruecke,sydney hafenbrücke,sydney harbour bridge,sydney harbour bridge  sdyney,sydneyhafnarbruin,sydneyhafnarbrúin,sydneyhawebrug,sydneyjski pristaniski most,sydneyjski pristaniški most,the coathanger,tulay ng daungan ng sydney,bndry pl sydny,citni turaimukap palam,gsr nml sydny,hababurijji,jsr mynaʾ sydny,pl bndrgah sydny,puente de la bahia de sidney,puente de la bahía de sídney,saphan sidniy har bexr,sidani bandaragaha pula,sideuni habeo beuliji,sidni bandaragaha bamdha,sidni harbar setuve,sidni harbar vantena,xi ni gang wan da qiao,xi ni hai gang da qiao,xue li gang wan da qiao,xue li hai gang da qiao,гарбор-брідж,мост харбар-брыдж,сидней харбор бридж,сиднејски заливски мост,сиднејски мост,харбор-бридж,харбър бридж,հարբոր բրիջ,גשר נמל סידני,بندری پل سیدنی,جسر ميناء سيدني,پل بندرگاه سیدنی,ہاربر برج,सिडनी बंदरगाह पुल,सिड्नी बन्दरगाह बाँध,சிட்னி துறைமுகப் பாலம்,సిడ్నీ హార్బర్ వంతెన,ಸಿಡ್ನಿ ಹಾರ್ಬರ್ ಸೇತುವೆ,സിഡ്നി ഹാർബർ പാലം,สะพานซิดนีย์ฮาร์เบอร์,ハーバーブリッジ,悉尼海港大桥,悉尼港灣大橋,雪梨海港大橋,雪梨港灣大橋,시드니 하버 브리지',
    NOW(), NOW()), ('6255006', NULL, 'Shellharbour North Beach', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.57217, 150.86872, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'shellharbour north beach shellharbour north beach australia au',
    NOW(), NOW()), ('6255013', NULL, 'Illawarra Regional Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.56044, 150.7889, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'illawarra regional airport illawarra regional airport australia au wol,yshl',
    NOW(), NOW()), ('6290236', NULL, 'Airport West', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.7247, 144.88126, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'airport west airport west australia au',
    NOW(), NOW()), ('6290242', NULL, 'Melbourne Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.67333, 144.84333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'melbourne airport melbourne airport australia au aerodrom melburn,aeroport melbourne-tullamarine,aeroporto de melbourne,aeroporto di melbourne,aeropuerto internacional tullamarine,aéroport melbourne-tullamarine,bandar udara internasional melbourne,flughafen melbourne,lapangan terbang antarabangsa melbourne,mel,mel''burn,melbourne airport,melbourne lufthavn,melbournen lentoasema,melburno oro uostas,port lotniczy melbourne,san bay melbourne,sân bay melbourne,tullamarine airport,ymml,frwdgah mlbwrn,melabarna vimanatala,melbeoleun gonghang,meruborun kong gang,mo er ben ji chang,mtar mlbwrn aldwly,tha xakas yan mel beirn,аеродром мелбурн,мельбурн,фурудгоҳи млбрн,נמל התעופה הבינלאומי מלבורן,فرودگاه ملبورن,مطار ملبورن الدولي,मेलबर्न विमानतळ,ท่าอากาศยานเมลเบิร์น,メルボルン空港,墨尔本机场。,墨爾本機場,멜버른 공항',
    NOW(), NOW()), ('6301288', NULL, 'Ayers Rock Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.1891, 130.97754, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ayers rock airport ayers rock airport australia au ayq,aehroport ehrs-rok,ayers rock airport,connellan airport,yaye,аэропорт эрс-рок',
    NOW(), NOW()), ('6301289', NULL, 'Archerfield Aerodrome', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.57028, 153.00806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'archerfield aerodrome archerfield aerodrome australia au aeroportul archerfield,archerfield aerodrome,archerfield airport,lapangan terbang archerfield,maes awyr archerfield,ybaf,achafirudo kong gang,frwdgah archrfyld,фурудгоҳи орчрфилд,فرودگاه آرچرفیلد,アーチャーフィールド空港',
    NOW(), NOW()), ('6301291', NULL, 'Alice Springs Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.80364, 133.90038, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alice springs airport alice springs airport australia au asp,aeroport dalice springs,aeroport de alice springs,aeropuerto de alice springs,alice springs airport,alis-springs,aéroport dalice springs,aéroport de alice springs,bandar udara alice springs,flughafen alice springs,lapangan terbang alice springs,port lotniczy alice springs,ybas,aelliseu seupeulingseu gonghang,ai li si quan ji chang,frwdgah alys aspryngz,алис-спрингс,фурудгоҳи олес оспрингз,فرودگاه آلیس اسپرینگز,アリス・スプリングス空港,愛麗斯泉機場,앨리스 스프링스 공항',
    NOW(), NOW()), ('6301292', NULL, 'Brisbane Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.38417, 153.1175, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brisbane airport brisbane airport australia au aerodrom brizbejn,aeroport de brisbane,aeroporto internacional de brisbane,aeroporto de brisbane,aeroporto di brisbane,aeroportul brisbane,aeropuerto de brisbane,aeropuertu de brisbane,bne,bandar udara brisbane,brisbane airport,brisbane lufthavn,brisbane lufthavn,brisbane''i lennujaam,brisbane-lughawe,brisbanen lentoasema,brisben,brisbeno oro uostas,flughafen brisbane,flughaveno brisbano,lapangan terbang brisbane,letiste brisbane,letiště brisbane,maes awyr brisbane,port lotniczy brisbane,san bay brisbane,sân bay brisbane,ybbn,aeroport international de brisbane,aéroport international de brisbane,beulijeubeon gonghang,bu li si ban ji chang,burisuben kong gang,frwdgah bryzbn,mtar bryzban,аеродром бризбејн,брисбен,фурудгоҳи бризбн,נמל התעופה בריזביין,فرودگاه بریزبن,مطار بريزبان,ブリスベン空港,布里斯班機場,브리즈번 공항',
    NOW(), NOW()), ('6301293', NULL, 'Gold Coast Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.16444, 153.50472, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gold coast airport gold coast airport australia au aeroport international de gold coast,aeroporto di gold coast,aeropuerto de gold coast,aéroport international de gold coast,bandar udara gold coast,coolangatta airport,gold coast airport,gold coast flygplats,gold coastin lentoasema,gold-kost,ool,port lotniczy gold coast,san bay gold coast,sân bay gold coast,ybcg,frwdgah gwld kwst,goldeukoseuteu gonghang,gorudokosuto kong gang,huang jin hai an ji chang,голд-кост,фурудгоҳи гулд куст,فرودگاه گولد کوست,ゴールドコースト空港,黄金海岸机场,골드코스트 공항',
    NOW(), NOW()), ('6301295', NULL, 'Charleville Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.41333, 146.2625, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'charleville airport charleville airport australia au aeroportul charleville,ctl,charleville airport,lapangan terbang charleville,letiste charleville,letiště charleville,ybcv,aeroport de charleville,aéroport de charleville,cha er wei er ji chang,charuvuiru kong gang,frwdgah charlwyl,sha lei wei er ji chang,фурудгоҳи чорлуил,فرودگاه چارلویل,チャールヴィル空港,查爾維爾機場,沙勒維爾機場,沙勒维尔机场',
    NOW(), NOW()), ('6301297', NULL, 'Longreach Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.43333, 144.26667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'longreach airport longreach airport australia au lre,ylre',
    NOW(), NOW()), ('6301298', NULL, 'Mount Isa Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.66389, 139.48861, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount isa airport mount isa airport australia au aeroportul mount isa,isa,lapangan terbang mt isa,maunt-ajza,mount isa airport,mount isa amo,port lotniczy mount isa,ybma,aerodrome de mount isa,aérodrome de mount isa,frwdgah mawnt ayzya,mauntoaisa kong gang,yi sa shan ji chang,маунт-айза,فرودگاه ماونت آیزیا,マウントアイサ空港,伊萨山机场,伊薩山機場',
    NOW(), NOW()), ('6301301', NULL, 'Proserpine Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.495, 148.55222, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'proserpine airport proserpine airport australia au aeroportul whitsunday coast,lapangan terbang whitsunday coast,ppp,proserpine airport,proserpine/whitsunday coast airport,whitsunday coast airport,ybpn,aeroport de whitsunday coast,aéroport de whitsunday coast,frwdgah prwsrpayn-wyt sandy kwst,jiang ling dao hai an ji chang,mtar waytsnday kwst,фурудгоҳи прусрпоин-вит сондий куст,فرودگاه پروسرپاین-ویت ساندی کوست,مطار وايتصنداى كوست,ウィットサンデー・コースト空港,降灵岛海岸机场,降靈島海岸機場',
    NOW(), NOW()), ('6301302', NULL, 'Rockhampton Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.37651, 150.47392, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rockhampton airport rockhampton airport australia au rok,ybrk',
    NOW(), NOW()), ('6301303', NULL, 'Broome International Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.94881, 122.22719, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'broome international airport broome international airport australia au bme,ybrm',
    NOW(), NOW()), ('6301304', NULL, 'Townsville Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -19.2525, 146.76528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'townsville airport townsville airport australia au aeroportul townsville,bandar udara townsville,lapangan terbang antarabangsa townsville,letiste townsville,letiště townsville,maes awyr townsville,port lotniczy townsville,raaf base garbutt,raaf base townsville,san bay quoc te townsville,sân bay quốc tế townsville,tsv,taunsvill,townsville airport,townsville amo,townsville international airport,ybtl,aeroport international de townsville,aéroport international de townsville,tang si wei er ji chang,taunzubiru kong gang,таунсвилл,фурудгоҳи товнсуил,فرودگاه بین‌المللی تانزویل,タウンズビル空港,汤斯维尔机场,湯斯維爾機場',
    NOW(), NOW()), ('6301305', NULL, 'Weipa Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.67861, 141.92528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'weipa airport weipa airport australia au aeroportul weipa,lapangan terbang weipa,wei,weipa airport,weipa city,ybwp,aerodrome de weipa,aérodrome de weipa,ueipa kong gang,wei pa ji chang,ウェイパ空港,韋帕機場,韦帕机场',
    NOW(), NOW()), ('6301306', NULL, 'Gove Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.27128, 136.82017, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gove airport gove airport australia au aeroport de airport,aeropuerto de gove,aéroport de airport,gov,gove airport,ypgv',
    NOW(), NOW()), ('6301307', NULL, 'Tennant Creek Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -19.63333, 134.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tennant creek airport tennant creek airport australia au tca,ytnk',
    NOW(), NOW()), ('6301308', NULL, 'Avalon Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.03944, 144.46944, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'avalon airport avalon airport australia au avv,aerodrom avalon,aeroporto de avalon,aeroportul avalon,avalon,avalon airport,avalon flygplats,lapangan terbang avalon,ymav,aballon gonghang,abaron kong gang,aeroport de melbourne-avalon,aeroporto di avalon,ai hua long ji chang,aéroport de melbourne-avalon,frwdgah awlan,авалон,аеродром авалон,фурудгоҳи овлон,ایوالون ہوائی اڈا,فرودگاه اولان,فڕۆکەخانەی ئاڤەڵۆن,アバロン空港,爱华隆机场,아발론 공항',
    NOW(), NOW()), ('6301309', NULL, 'Albury Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.06778, 146.95806, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'albury airport albury airport australia au abx,ymay',
    NOW(), NOW()), ('6301310', NULL, 'Devonport East', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.16667, 146.36667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'devonport east devonport east australia au ymdv',
    NOW(), NOW()), ('6301311', NULL, 'Essendon Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.72806, 144.90194, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'essendon airport essendon airport australia au aerodrom esendon,aeroporto de essendon,aeroportul essendon,ehssendon,essendon,essendon airport,essendon fields airport,essendon lufthavn,flughafen essendon,issendon,lapangan terbang essendon,letiste essendon,letiště essendon,meb,ymen,aeroport d''essendon,aeroporto di essendon,ai sen deng ji chang,aéroport d''essendon,esendeun gonghang,essendon kong gang,frwdgah asndwn,іссендон,аеродром есендон,фурудгоҳи осндун,эссендон,ایسینڈن ہوائی اڈا,فرودگاه اسندون,エッセンドン空港,埃森登机场,埃森登機場,에센든 공항',
    NOW(), NOW()), ('6301313', NULL, 'Hobart Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.83611, 147.51028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hobart airport hobart airport australia au hba,ymhb',
    NOW(), NOW()), ('6301314', NULL, 'Launceston Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.54528, 147.21417, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'launceston airport launceston airport australia au flughafen launceston,lst,ymlt',
    NOW(), NOW()), ('6301316', NULL, 'Moorabbin Airport Aws', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.97583, 145.10222, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'moorabbin airport aws moorabbin airport aws australia au mbw,moorabbin airport,moorabbin harry hawker airport,ymmb',
    NOW(), NOW()), ('6301318', NULL, 'Mildura Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.22917, 142.08556, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mildura airport mildura airport australia au aeroportul mildura,lapangan terbang mildura,letiste mildura,letiště mildura,mql,mild''jura,mildura,mildura airport,ymia,aeroport de mildura,aéroport de mildura,frwdgah myldwra,mi er di la ji chang,mi er du la ji chang,mirudeyura kong gang,милдьюра,мілд''юра,фурудгоҳи милдуро,فرودگاه میلدورا,ミルデューラ空港,米尔杜拉机场,米爾杜拉機場,米爾迪拉機場',
    NOW(), NOW()), ('6301322', NULL, 'Adelaide Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.945, 138.53056, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'adelaide airport adelaide airport australia au adl,adelaida,adelaide airport,adelaide lufthavn,adelaide lufthavn,adelaide''i lennujaam,adelaide-lughawe,adelaiden lentoasema,aeroport d''adelaida,aeroporto internacional de adelaide,aeroporto de adelaida,aeroportul adelaide,aeropuerto internacional de adelaida,aeropuertu internacional d''adelaide,bandar udara internasional adelaide,flughafen adelaide,flughaveno adelajdo,lapangan terbang antarabangsa adelaide,letiste adelaide,letiště adelaide,maes awyr adelaide,port lotniczy adelaide,san bay quoc te adelaide,sân bay quốc tế adelaide,ypad,a de lai de ji chang,a de li ji chang,aderedo kong gang,aedeulleideu gonghang,aeroport international d''adelaide,aeroporto di adelaide,aéroport international d''adélaïde,frwdgah adlayd,mtar adylayd,аделаида,аделаїда,фурудгоҳи одлоид,فرودگاه آدلاید,مطار اديلايد,アデレード空港,阿地利機場,阿德萊德機場,애들레이드 공항',
    NOW(), NOW()), ('6301325', NULL, 'Ceduna Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.12489, 133.70151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ceduna airport ceduna airport australia au ced,ceduna airport,ycdu',
    NOW(), NOW()), ('6301330', NULL, 'Forrest Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.84358, 128.11295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'forrest airport forrest airport australia au fos,forrest airport,yfrt',
    NOW(), NOW()), ('6301331', NULL, 'Geraldton Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.79572, 114.704, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'geraldton airport geraldton airport australia au aeroport de geraldton,aeropuerto de geraldton,aéroport de geraldton,get,geraldton airport,ygel',
    NOW(), NOW()), ('6301332', NULL, 'Kalgoorlie-Boulder Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.78646, 121.45828, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kalgoorlie-boulder airport kalgoorlie-boulder airport australia au aehroport kalgurli-boulder,aeroport de kalgoorlie-boulder,aéroport de kalgoorlie-boulder,kgi,kalgoorlie-boulder airport,ypkg,аэропорт калгурли-боулдер',
    NOW(), NOW()), ('6301333', NULL, 'East Kimberley Regional Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.78042, 128.71149, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east kimberley regional airport east kimberley regional airport australia au east kimberley regional airport,knx,kununurra airport,kununurra kununurra aws,ypku',
    NOW(), NOW()), ('6301334', NULL, 'Leigh Creek Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.59833, 138.42583, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'leigh creek airport leigh creek airport australia au lgh,leigh creek airport,ylec',
    NOW(), NOW()), ('6301335', NULL, 'Meekatharra Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.60848, 118.54548, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'meekatharra airport meekatharra airport australia au lapangan terbang meekatharra,mkr,ymek',
    NOW(), NOW()), ('6301336', NULL, 'Port Hedland Pardoo', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.37778, 118.62639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hedland pardoo port hedland pardoo australia au phe,yppd',
    NOW(), NOW()), ('6301341', NULL, 'Bankstown Airport Aws', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.92444, 150.98833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bankstown airport aws bankstown airport aws australia au bwu,ysbk',
    NOW(), NOW()), ('6301342', NULL, 'Canberra International Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.30694, 149.195, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'canberra international airport canberra international airport australia au aerodrom kanbera,aeroporto internazionale di canberra,aeroporto de camberra,aeroporto de canberra,aeroportul international canberra,aeroportul internațional canberra,aeropuerto internacional de canberra,bandar udara internasional canberra,cbr,canberra airport,canberra international airport,canberra internasjonale lufthavn,canberran kansainvaelinen lentoasema,canberran kansainvälinen lentoasema,flughafen canberra,internacia flughaveno kanbero,kanberos oro uostas,kanberra,lapangan terbang canberra,maes awyr rhyngwladol canberra,port lotniczy canberra,san bay quoc te canberra,sân bay quốc tế canberra,yscb,aeroport de canberra,aéroport de canberra,kaenbeola gugjegonghang,kainabara hava''i adda,kan pei la guo ji ji chang,kyanbera guo ji kong gang,mtar kanbra,аеродром канбера,канберра,фурудгоҳи байн‌алмиллалии канбера,נמל התעופה קנברה,فرودگاه بین‌المللی کانبرا,مطار كانبرا,कैनबरा हवाई अड्डा,キャンベラ国際空港,坎培拉國際機場,캔버라 국제공항',
    NOW(), NOW()), ('6301343', NULL, 'Coffs Harbour Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.32056, 153.11639, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'coffs harbour airport coffs harbour airport australia au cfs,coffs harbour airport,coffs harbour mo,ycfs',
    NOW(), NOW()), ('6301345', NULL, 'Camden Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.04028, 150.68722, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'camden airport camden airport australia au cdu,yscn',
    NOW(), NOW()), ('6301346', NULL, 'Dubbo', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.21667, 148.57472, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dubbo dubbo australia au aeroportul dubbo city,ciudad de dubbo,dbo,dubbo,dubbo airport,dubbo city airport,dubbo city regional airport,dubbo cityn lentoasema,flughafen dubbo city,lapangan terbang dubbo,letiste dubbo,letiště dubbo,ysdu,aeroport de dubbo,aeroporto di dubbo city,aéroport de dubbo,da bo ji chang,dabo kong gang,duo bao shi zhi xian ji chang,frwdgah dabw syty,фурудгоҳи добу сетӣ е,فرودگاه دابو سیتی,ダボ空港,多寶市支線機場,达博机场,達博機場',
    NOW(), NOW()), ('6301349', NULL, 'RAAF Base Richmond', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.60056, 150.78083, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'raaf base richmond raaf base richmond australia au bandar udara raaf base richmond,base aerea de richmond,base aérea de richmond,lapangan terbang richmond,raaf base richmond,xrh,ysri,frwdgah nyrwy hwayy sltnty astralya dr paygah rychmwnd,ritchimondo kong jun ji de,фурудгоҳи нерӯе ҳаво салтанате устуролеё дар пойгоҳи ричмунд,آر اے اے ایف بیس رچمنڈ,فرودگاه نیروی هوایی سلطنتی استرالیا در پایگاه ریچموند,リッチモンド空軍基地',
    NOW(), NOW()), ('6301351', NULL, 'Tamworth Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.08389, 150.84667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tamworth airport tamworth airport australia au lapangan terbang tamworth,tmw,ystw',
    NOW(), NOW()), ('6301352', NULL, 'Wagga Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.16528, 147.46639, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wagga airport wagga airport australia au raaf base forest hill,wga,yswg',
    NOW(), NOW()), ('6301882', NULL, 'Parafield Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.79333, 138.63306, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'parafield airport parafield airport australia au aeroporto de parafield,aeroportul parafield,lapangan terbang parafield,letiste parafield,letiště parafield,parafield,parafield airport,yppf,aeroport de parafield,aeroporto di parafield,aéroport de parafield,bai li fei lu ji chang,frwdgah parafyld,parafirudo kong gang,фурудгоҳи порофилд,فرودگاه پارافیلد,パラフィールド空港,柏立非路機場',
    NOW(), NOW()), ('6354932', NULL, 'Dunk Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.93913, 146.14151, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dunk island airport dunk island airport australia au dki,dunk island,dunk island airport,ydki',
    NOW(), NOW()), ('6354938', NULL, 'Lizard Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.67303, 145.45418, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lizard island airport lizard island airport australia au aeroportul lizard island,lzr,lapangan terbang lizard island,lizard island,lizard island airport,ylzi,frwdgah jzyrh swsmar,rizado dao kong gang,фурудгоҳи ҷазира сусмор,فرودگاه جزیره سوسمار,リザード島空港',
    NOW(), NOW()), ('6354956', NULL, 'Hervey Bay Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.32184, 152.88422, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hervey bay airport hervey bay airport australia au hvb,hervey bay,hervey bay airport,yhba',
    NOW(), NOW()), ('6355170', NULL, 'd''Albora Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.71827, 152.14477, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'd''albora marina d''albora marina australia au',
    NOW(), NOW()), ('6453413', NULL, 'Kingscote Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.71526, 137.5257, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kingscote airport kingscote airport australia au kgc,kingscote,kingscote airport,yksc',
    NOW(), NOW()), ('6462686', NULL, 'Rydges Port Macquarie', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.428, 152.9093, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rydges port macquarie rydges port macquarie australia au',
    NOW(), NOW()), ('6464578', NULL, 'Somerset Darling Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8721, 151.204, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'somerset darling harbour somerset darling harbour australia au',
    NOW(), NOW()), ('6464697', NULL, 'Medina Grand Harbourside', 'MEDINA GRAND HARBOURSIDE',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8676, 151.2096, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'medina grand harbourside medina grand harbourside australia au',
    NOW(), NOW()), ('6468571', NULL, 'Quality Hotel Port Of Echuca', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.1265, 144.7476, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'quality hotel port of echuca quality hotel port of echuca australia au',
    NOW(), NOW()), ('6468634', NULL, 'The Sebel Pier One Sydney', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8538, 151.2085, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the sebel pier one sydney the sebel pier one sydney australia au',
    NOW(), NOW()), ('6468696', NULL, 'Sheraton Mirage Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.5025, 145.4632, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sheraton mirage port douglas sheraton mirage port douglas australia au',
    NOW(), NOW()), ('6474912', NULL, 'Breakfree Royal Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.8881, 145.7542, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'breakfree royal harbour breakfree royal harbour australia au',
    NOW(), NOW()), ('6476637', NULL, 'Rendezvous Reef Resort Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.5185, 145.467, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'rendezvous reef resort port douglas rendezvous reef resort port douglas australia au',
    NOW(), NOW()), ('6476728', NULL, 'Mantra Treetops Resort & Spa Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.5148, 145.4646, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mantra treetops resort & spa port douglas mantra treetops resort & spa port douglas australia au',
    NOW(), NOW()), ('6478391', NULL, 'Stamford Sydney Airport Hotel', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9307, 151.1864, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stamford sydney airport hotel stamford sydney airport hotel australia au',
    NOW(), NOW()), ('6481317', NULL, 'Harbour Rocks Hotel', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8596, 151.2079, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour rocks hotel harbour rocks hotel australia au harbour rocks hotel,fndq harbwr rwks,فندق هاربور روكس',
    NOW(), NOW()), ('6484434', NULL, 'Shangri-La Hotel, The Marina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.9209, 145.7803, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shangri-la hotel, the marina shangri-la hotel, the marina australia au',
    NOW(), NOW()), ('6485010', NULL, 'Marriott Sydney Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8625, 151.209, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'marriott sydney harbour marriott sydney harbour australia au',
    NOW(), NOW()), ('6490554', NULL, 'Vulcan Hotel - Darling Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87861, 151.19694, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'vulcan hotel - darling harbour vulcan hotel - darling harbour australia au',
    NOW(), NOW()), ('6491931', NULL, 'Latitude 16 Port Douglas Apartments', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4847, 145.4668, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'latitude 16 port douglas apartments latitude 16 port douglas apartments australia au',
    NOW(), NOW()), ('6492749', NULL, 'Alice Springs Airport Motel', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.6999, 133.8833, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'alice springs airport motel alice springs airport motel australia au',
    NOW(), NOW()), ('6492932', NULL, 'Sea Temple Resort and Spa Port', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4833, 145.4666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sea temple resort and spa port sea temple resort and spa port australia au',
    NOW(), NOW()), ('6493292', NULL, 'The Meridian at Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4859, 145.4658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the meridian at port douglas the meridian at port douglas australia au',
    NOW(), NOW()), ('6494356', NULL, 'Quest Docklands', 'QUEST DOCKLANDS',
    NULL, 'AU', 'Australia', NULL, NULL,
    -25, 134, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'quest docklands quest docklands australia au',
    NOW(), NOW()), ('6495038', NULL, 'Mantra Aqueous on Port', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4847, 145.4667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mantra aqueous on port mantra aqueous on port australia au',
    NOW(), NOW()), ('6500354', NULL, 'Oaks Plaza Pier Glenelg', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.9772, 138.5103, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'oaks plaza pier glenelg oaks plaza pier glenelg australia au',
    NOW(), NOW()), ('6500763', NULL, 'Best Western Ciloms Airport', 'BEST WESTERN CILOMS AIRPORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.6999, 144.8666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'best western ciloms airport best western ciloms airport australia au',
    NOW(), NOW()), ('6501203', NULL, 'Peppers Seaport Hotel', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.4335, 147.1331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'peppers seaport hotel peppers seaport hotel australia au',
    NOW(), NOW()), ('6501307', NULL, 'Breakfree Portsea Resort', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.5384, 145.4673, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'breakfree portsea resort breakfree portsea resort australia au',
    NOW(), NOW()), ('6502360', NULL, 'Outrigger Heritage Resort Port Douglas', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.4831, 145.4629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'outrigger heritage resort port douglas outrigger heritage resort port douglas australia au',
    NOW(), NOW()), ('6506543', NULL, 'Hotel Ibis Sydney Airport', 'HOTEL IBIS SYDNEY AIRPORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.92837, 151.18721, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hotel ibis sydney airport hotel ibis sydney airport australia au',
    NOW(), NOW()), ('6506706', NULL, 'Somerset On The Pier', 'SOMERSET ON THE PIER',
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.87784, 147.3193, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'somerset on the pier somerset on the pier australia au',
    NOW(), NOW()), ('6507646', NULL, 'Hilton Airport', 'HILTON AIRPORT',
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.6999, 144.8666, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hilton airport hilton airport australia au',
    NOW(), NOW()), ('6507963', NULL, 'Novotel Sydney Darling Harbour', 'NOVOTEL SYDNEY DARLING HARBOUR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87141, 151.19754, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'novotel sydney darling harbour novotel sydney darling harbour australia au',
    NOW(), NOW()), ('6508037', NULL, 'Hotel Ibis Darling Harbour', 'HOTEL IBIS DARLING HARBOUR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8706, 151.19771, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hotel ibis darling harbour hotel ibis darling harbour australia au',
    NOW(), NOW()), ('6508143', NULL, 'Airport Sydney International', 'AIRPORT SYDNEY INTERNATIONAL',
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9333, 151.2, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'airport sydney international airport sydney international australia au',
    NOW(), NOW()), ('6509047', NULL, 'Country Comfort Coffs Harbour', 'COUNTRY COMFORT COFFS HARBOUR',
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.3, 153.1333, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'country comfort coffs harbour country comfort coffs harbour australia au',
    NOW(), NOW());