INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('5960479', NULL, 'Georges Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.35015, -60.96521, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'georges harbour georges harbour canada ca',
    NOW(), NOW()), ('5960535', NULL, 'Georgetown Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.1668, -62.53195, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'georgetown harbour georgetown harbour canada ca',
    NOW(), NOW()), ('5960995', NULL, 'Gids Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.4168, -86.23321, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gids harbour gids harbour canada ca',
    NOW(), NOW()), ('5961191', NULL, 'Gillen Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.98103, -129.60048, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gillen harbour gillen harbour canada ca',
    NOW(), NOW()), ('5961218', NULL, 'Gillesport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.66662, -54.74816, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gillesport gillesport canada ca',
    NOW(), NOW()), ('5961568', NULL, 'Glace Bay Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.20014, -59.94844, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glace bay harbour glace bay harbour canada ca',
    NOW(), NOW()), ('5961727', NULL, 'Glasgow Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.31685, -60.96521, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glasgow harbour glasgow harbour canada ca',
    NOW(), NOW()), ('5961965', NULL, 'Glen Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.88338, -105.10113, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glen harbour glen harbour canada ca',
    NOW(), NOW()), ('5962195', NULL, 'Glory Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.00442, -99.95274, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glory harbour glory harbour canada ca',
    NOW(), NOW()), ('5962227', NULL, 'Glovers Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.44994, -55.49818, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glovers harbour glovers harbour canada ca',
    NOW(), NOW()), ('5962228', NULL, 'Glovers Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.46664, -55.48148, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'glovers harbour glovers harbour canada ca',
    NOW(), NOW()), ('5962298', NULL, 'Goat Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.35875, -128.87062, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'goat harbour goat harbour canada ca',
    NOW(), NOW()), ('5962771', NULL, 'Goldstream Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.72631, -128.00469, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'goldstream harbour goldstream harbour canada ca',
    NOW(), NOW()), ('5962889', NULL, 'Good Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.9168, -79.83296, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'good harbour good harbour canada ca',
    NOW(), NOW()), ('5962890', NULL, 'Good Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.12972, -100.15025, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'good harbour good harbour canada ca',
    NOW(), NOW()), ('5963011', NULL, 'Goodwithy Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.98319, -53.78139, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'goodwithy harbour goodwithy harbour canada ca',
    NOW(), NOW()), ('5963068', NULL, 'Gooseberry Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.88318, -53.61478, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gooseberry harbour gooseberry harbour canada ca',
    NOW(), NOW()), ('5963163', NULL, 'Goose Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.75014, -64.01543, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'goose harbour goose harbour canada ca',
    NOW(), NOW()), ('5963164', NULL, 'Goose Harbour Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.5521, -61.41469, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'goose harbour lake goose harbour lake canada ca',
    NOW(), NOW()), ('5963362', NULL, 'Goose Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.64987, -93.13358, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'goose portage goose portage canada ca',
    NOW(), NOW()), ('5963593', NULL, 'Gorge Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.09729, -125.01283, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gorge harbour gorge harbour canada ca',
    NOW(), NOW()), ('5963695', NULL, 'Gosport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.11806, -77.02444, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gosport gosport canada ca',
    NOW(), NOW()), ('5963696', NULL, 'Gosport', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.02156, -77.71981, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gosport gosport canada ca',
    NOW(), NOW()), ('5963919', NULL, 'Govers Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.31663, -55.24817, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'govers harbour govers harbour canada ca',
    NOW(), NOW()), ('5963957', NULL, 'Gowlland Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.07672, -125.2259, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gowlland harbour gowlland harbour canada ca',
    NOW(), NOW()), ('5963992', NULL, 'Grace Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.05185, -124.74564, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grace harbour grace harbour canada ca',
    NOW(), NOW()), ('5964102', NULL, 'Graham Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    74.50155, -88.18336, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'graham harbour graham harbour canada ca',
    NOW(), NOW()), ('5964233', NULL, 'Grand Bank Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.09995, -55.76504, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand bank harbour grand bank harbour canada ca',
    NOW(), NOW()), ('5964255', NULL, 'Grand Bruit Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.66669, -58.2318, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand bruit harbour grand bruit harbour canada ca',
    NOW(), NOW()), ('5964296', NULL, 'Grande anse du Dock', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.28342, -64.69874, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grande anse du dock grande anse du dock canada ca',
    NOW(), NOW()), ('5964325', NULL, 'Grande Greve Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.63344, -60.8652, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grande greve harbour grande greve harbour canada ca',
    NOW(), NOW()), ('5964364', NULL, 'Grand Étang Harbour', 'Grand Etang Harbour',
    NULL, 'CA', 'Canada', NULL, NULL,
    46.55014, -61.04851, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand étang harbour grand etang harbour canada ca',
    NOW(), NOW()), ('5964408', NULL, 'Grand Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.68675, -66.76568, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand harbour grand harbour canada ca',
    NOW(), NOW()), ('5964409', NULL, 'Grand Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.67491, -66.75422, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand harbour grand harbour canada ca',
    NOW(), NOW()), ('5964546', NULL, 'Grand lac Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.78833, -73.84528, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand lac pierre grand lac pierre canada ca',
    NOW(), NOW()), ('5964599', NULL, 'Grand Le Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.68321, -54.78152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand le pierre grand le pierre canada ca',
    NOW(), NOW()), ('5964600', NULL, 'Grand Le Pierre Brook', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.68321, -54.78152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand le pierre brook grand le pierre brook canada ca',
    NOW(), NOW()), ('5964601', NULL, 'Grand Le Pierre Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.66661, -54.78152, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grand le pierre harbour grand le pierre harbour canada ca',
    NOW(), NOW()), ('5964602', NULL, 'Grand Le Pierre Head', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.66521, -54.78492, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand le pierre head grand le pierre head canada ca',
    NOW(), NOW()), ('5964635', NULL, 'Grandois Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.10006, -55.74804, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grandois harbour grandois harbour canada ca',
    NOW(), NOW()), ('5964655', NULL, 'Grand Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.25009, -84.88313, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand portage grand portage canada ca',
    NOW(), NOW()), ('5964656', NULL, 'Grand Portage Creek', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.18541, -94.78986, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grand portage creek grand portage creek canada ca',
    NOW(), NOW()), ('5964975', NULL, 'Grant Point Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.56681, -88.15001, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grant point harbour grant point harbour canada ca',
    NOW(), NOW()), ('5965402', NULL, 'Grassy Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.71657, -93.03357, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grassy portage grassy portage canada ca',
    NOW(), NOW()), ('5965403', NULL, 'Grassy Portage Bay', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.69987, -93.08358, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grassy portage bay grassy portage bay canada ca',
    NOW(), NOW()), ('5965773', NULL, 'Great Brule Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.6499, -54.13144, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great brule harbour great brule harbour canada ca',
    NOW(), NOW()), ('5965774', NULL, 'Great Burin Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.99994, -55.165, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great burin harbour great burin harbour canada ca',
    NOW(), NOW()), ('5965787', NULL, 'Great Chance Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.5166, -53.68139, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great chance harbour great chance harbour canada ca',
    NOW(), NOW()), ('5965788', NULL, 'Great Cherry Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.11673, -90.13348, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'great cherry portage great cherry portage canada ca',
    NOW(), NOW()), ('5965826', NULL, 'Great Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.51665, -55.84833, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour great harbour canada ca',
    NOW(), NOW()), ('5965827', NULL, 'Great Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.51665, -55.84833, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour great harbour canada ca',
    NOW(), NOW()), ('5965828', NULL, 'Great Harbour Bight', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.49995, -55.83163, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour bight great harbour bight canada ca',
    NOW(), NOW()), ('5965829', NULL, 'Great Harbour Deep', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.36672, -56.44814, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour deep great harbour deep canada ca',
    NOW(), NOW()), ('5965830', NULL, 'Great Harbour Deep', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.36672, -56.51484, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great harbour deep great harbour deep canada ca great harbour deep',
    NOW(), NOW()), ('5965841', NULL, 'Great Islets Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.15006, -55.74803, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great islets harbour great islets harbour canada ca',
    NOW(), NOW()), ('5965843', NULL, 'Great Jervis Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.66665, -56.16505, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great jervis harbour great jervis harbour canada ca',
    NOW(), NOW()), ('5965844', NULL, 'Great Jervis Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.64995, -56.16505, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great jervis harbour great jervis harbour canada ca',
    NOW(), NOW()), ('5965849', NULL, 'Great Lawn Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.93324, -55.54833, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great lawn harbour great lawn harbour canada ca',
    NOW(), NOW()), ('5965866', NULL, 'Great Portage Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.43997, -92.27658, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'great portage lake great portage lake canada ca',
    NOW(), NOW()), ('5965875', NULL, 'Great Sandy Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.68321, -54.31487, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great sandy harbour great sandy harbour canada ca',
    NOW(), NOW()), ('5965881', NULL, 'Great Southern Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.7471, -53.97873, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great southern harbour great southern harbour canada ca',
    NOW(), NOW()), ('5965882', NULL, 'Great St. Julien Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.10006, -55.73134, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great st. julien harbour great st. julien harbour canada ca',
    NOW(), NOW()), ('5965883', NULL, 'Great St. Lawrence Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.89994, -55.36502, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great st. lawrence harbour great st. lawrence harbour canada ca',
    NOW(), NOW()), ('5965887', NULL, 'Great Triton Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.53324, -55.61488, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'great triton harbour great triton harbour canada ca',
    NOW(), NOW()), ('5965934', NULL, 'Greely Haven', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    71.93452, -104.83629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'greely haven greely haven canada ca',
    NOW(), NOW()), ('5966097', NULL, 'Green Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.70676, -65.1545, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'green harbour green harbour canada ca',
    NOW(), NOW()), ('5966138', NULL, 'Greenhill Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    48.73344, -83.44979, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'greenhill portage greenhill portage canada ca',
    NOW(), NOW()), ('5966300', NULL, 'Green Island Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    57.66694, -61.78134, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'green island harbour green island harbour canada ca',
    NOW(), NOW()), ('5966456', NULL, 'Greenough Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.98337, -81.43306, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greenough harbour greenough harbour canada ca',
    NOW(), NOW()), ('5966580', NULL, 'Green''s Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.63319, -53.49809, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'green''s harbour green''s harbour canada ca green''s harbour',
    NOW(), NOW()), ('5966581', NULL, 'Greens Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.64989, -53.51479, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greens harbour greens harbour canada ca',
    NOW(), NOW()), ('5966582', NULL, 'Greens Harbour Beach', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.63459, -53.50639, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greens harbour beach greens harbour beach canada ca',
    NOW(), NOW()), ('5966583', NULL, 'Greens Harbour Head', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.67349, -53.52449, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greens harbour head greens harbour head canada ca',
    NOW(), NOW()), ('5966584', NULL, 'Greens Harbour Point', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.66989, -53.52869, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greens harbour point greens harbour point canada ca',
    NOW(), NOW()), ('5966585', NULL, 'Greens Harbour Pond', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.63459, -53.50639, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greens harbour pond greens harbour pond canada ca',
    NOW(), NOW()), ('5966618', NULL, 'Greenspond Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.06658, -53.56476, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'greenspond harbour greenspond harbour canada ca',
    NOW(), NOW()), ('5966837', NULL, 'Grenon Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    52.85193, -100.20523, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grenon harbour grenon harbour canada ca',
    NOW(), NOW()), ('5966911', NULL, 'Grevigneux Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.73339, -56.0981, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grevigneux harbour grevigneux harbour canada ca',
    NOW(), NOW()), ('5966954', NULL, 'Grey Islands Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.71672, -55.59802, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grey islands harbour grey islands harbour canada ca',
    NOW(), NOW()), ('5966955', NULL, 'Grey Islands Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    50.70002, -55.59802, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grey islands harbour grey islands harbour canada ca',
    NOW(), NOW()), ('5967061', NULL, 'Griffin Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.53338, -55.79794, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'griffin harbour griffin harbour canada ca',
    NOW(), NOW()), ('5967088', NULL, 'Griffith Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.59999, -130.54882, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'griffith harbour griffith harbour canada ca',
    NOW(), NOW()), ('5967153', NULL, 'Grimsby Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    43.20011, -79.54961, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'grimsby harbour grimsby harbour canada ca',
    NOW(), NOW()), ('5967225', NULL, 'Griquet Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.55008, -55.44795, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'griquet harbour griquet harbour canada ca',
    NOW(), NOW()), ('5967429', NULL, 'Grotte de la Maison de Pierre', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.45011, -75.56601, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'grotte de la maison de pierre grotte de la maison de pierre canada ca',
    NOW(), NOW()), ('5967813', NULL, 'Gull Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.19922, -96.62062, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gull harbour gull harbour canada ca',
    NOW(), NOW()), ('5967814', NULL, 'Gull Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.19422, -96.61342, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gull harbour gull harbour canada ca',
    NOW(), NOW()), ('5967815', NULL, 'Gull Harbour Beach', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.19142, -96.62252, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gull harbour beach gull harbour beach canada ca',
    NOW(), NOW()), ('5967816', NULL, 'Gull Harbour Point', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    51.20222, -96.61232, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gull harbour point gull harbour point canada ca',
    NOW(), NOW()), ('5968203', NULL, 'Gull Rock Portage', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    49.58345, -84.73319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gull rock portage gull rock portage canada ca',
    NOW(), NOW()), ('5968295', NULL, 'Gunboat Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.9213, -130.14424, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'gunboat harbour gunboat harbour canada ca',
    NOW(), NOW()), ('5968473', NULL, 'Gunters Wharf', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.83344, -66.19886, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gunters wharf gunters wharf canada ca',
    NOW(), NOW()), ('5968622', NULL, 'Guysborough Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.38345, -61.48184, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'guysborough harbour guysborough harbour canada ca',
    NOW(), NOW()), ('5968779', NULL, 'Haddock', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    53.81684, -115.98554, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock haddock canada ca',
    NOW(), NOW()), ('5968780', NULL, 'Haddock Bank', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    46.35014, -60.33176, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock bank haddock bank canada ca',
    NOW(), NOW()), ('5968781', NULL, 'Haddock Cove', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.73321, -54.24815, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock cove haddock cove canada ca',
    NOW(), NOW()), ('5968782', NULL, 'Haddock Creek', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    47.48341, -83.08309, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock creek haddock creek canada ca',
    NOW(), NOW()), ('5968783', NULL, 'Haddock Harbour', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.53344, -61.13182, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'haddock harbour haddock harbour canada ca',
    NOW(), NOW()), ('5968784', NULL, 'Haddock Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    44.69366, -64.50444, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock lake haddock lake canada ca',
    NOW(), NOW()), ('5968785', NULL, 'Haddock Lake', NULL,
    NULL, 'CA', 'Canada', NULL, NULL,
    45.20143, -67.09198, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'haddock lake haddock lake canada ca',
    NOW(), NOW());