INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('8220117', NULL, 'Steamers Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.9152, 151.78461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'steamers wharf steamers wharf australia au steamers wharf',
    NOW(), NOW()), ('8220118', NULL, 'Sunshine Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1152, 151.5679, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sunshine wharf sunshine wharf australia au sunshine wharf',
    NOW(), NOW()), ('8220119', NULL, 'Swan Reach Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.7152, 151.6846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'swan reach wharf swan reach wharf australia au swan reach wharf',
    NOW(), NOW()), ('8220120', NULL, 'Taronga Park Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 151.2346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taronga park wharf taronga park wharf australia au taronga park wharf,taronga wharf',
    NOW(), NOW()), ('8220121', NULL, 'Tennis Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6318, 151.28461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tennis wharf tennis wharf australia au tennis wharf',
    NOW(), NOW()), ('8220122', NULL, 'Thames Street Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.1846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'thames street wharf thames street wharf australia au thames street wharf',
    NOW(), NOW()), ('8220123', NULL, 'Throsby Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.9235, 151.7596, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'throsby wharf throsby wharf australia au throsby wharf',
    NOW(), NOW()), ('8220124', NULL, 'Toronto Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.0124, 151.6012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'toronto wharf toronto wharf australia au toronto wharf',
    NOW(), NOW()), ('8220125', NULL, 'Tuggerah Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3152, 151.4512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tuggerah wharf tuggerah wharf australia au tuggerah wharf',
    NOW(), NOW()), ('8220126', NULL, 'Valentia Street Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 151.16789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'valentia street wharf valentia street wharf australia au valentia street wharf',
    NOW(), NOW()), ('8220127', NULL, 'Veteran Hall Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4818, 151.3346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'veteran hall wharf veteran hall wharf australia au veteran hall wharf',
    NOW(), NOW()), ('8220128', NULL, 'Walseley Street Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.15961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'walseley street wharf walseley street wharf australia au walseley street wharf,wolseley street wharf',
    NOW(), NOW()), ('8220130', NULL, 'Wangi Point Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.0818, 151.61791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wangi point wharf wangi point wharf australia au wangi point wharf',
    NOW(), NOW()), ('8220131', NULL, 'Wardell Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.9485, 153.4512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wardell wharf wardell wharf australia au wardell wharf',
    NOW(), NOW()), ('8220133', NULL, 'Woy Woy Bay Public Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4652, 151.30119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woy woy bay public wharf woy woy bay public wharf australia au woy woy bay public wharf',
    NOW(), NOW()), ('8220134', NULL, 'Wyee Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.1402, 151.5262, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wyee wharf wyee wharf australia au wyee wharf',
    NOW(), NOW()), ('8220135', NULL, 'Yattalunga Public Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4652, 151.3512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yattalunga public wharf yattalunga public wharf australia au yattalunga public wharf',
    NOW(), NOW()), ('8220136', NULL, 'Bullock Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4152, 150.80119, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullock wharf bullock wharf australia au bullock wharf',
    NOW(), NOW()), ('8220137', NULL, 'Duffys Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.6735, 151.16789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'duffys wharf duffys wharf australia au duffys wharf',
    NOW(), NOW()), ('8220138', NULL, 'Byalla Lane Public Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.471, 151.3437, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'byalla lane public wharf byalla lane public wharf australia au byalla lane public wharf',
    NOW(), NOW()), ('8220139', NULL, 'Batemans Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.33535, 151.50204, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'batemans wharf batemans wharf australia au batemans wharf',
    NOW(), NOW()), ('8220140', NULL, 'Central Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4818, 151.3512, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'central wharf central wharf australia au central wharf',
    NOW(), NOW()), ('8220141', NULL, 'Erina Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4318, 151.3846, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'erina wharf erina wharf australia au erina wharf',
    NOW(), NOW()), ('8220142', NULL, 'Eulalia Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4818, 151.36791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'eulalia wharf eulalia wharf australia au eulalia wharf',
    NOW(), NOW()), ('8220143', NULL, 'Gosford Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4152, 151.3346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gosford wharf gosford wharf australia au gosford wharf',
    NOW(), NOW()), ('8220144', NULL, 'Humphreys Road Public Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.4818, 151.36791, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'humphreys road public wharf humphreys road public wharf australia au humphreys road public wharf,humphries road public wharf',
    NOW(), NOW()), ('8220145', NULL, 'South Park Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9068, 150.95261, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'south park wharf south park wharf australia au south park wharf',
    NOW(), NOW()), ('8220146', NULL, 'Long Point Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9027, 150.961, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'long point wharf long point wharf australia au long point wharf',
    NOW(), NOW()), ('8220147', NULL, 'Bradbury Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.9018, 150.9546, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bradbury wharf bradbury wharf australia au bradbury wharf',
    NOW(), NOW()), ('8220148', NULL, 'Gladesville Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gladesville wharf gladesville wharf australia au gladesville wharf',
    NOW(), NOW()), ('8220149', NULL, 'Hunters Hill Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8402, 151.1512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'hunters hill wharf hunters hill wharf australia au hunters hill wharf',
    NOW(), NOW()), ('8220150', NULL, 'Villa Maria Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8402, 151.1429, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'villa maria wharf villa maria wharf australia au villa maria wharf',
    NOW(), NOW()), ('8220151', NULL, 'Woolwich Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8318, 151.16789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'woolwich wharf woolwich wharf australia au woolwich wharf',
    NOW(), NOW()), ('8220152', NULL, 'Cooks Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 151.1512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cooks wharf cooks wharf australia au cooks wharf',
    NOW(), NOW()), ('8220153', NULL, 'Henley Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'henley wharf henley wharf australia au henley wharf',
    NOW(), NOW()), ('8220155', NULL, 'Cove Street Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8485, 151.16789, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cove street wharf cove street wharf australia au cove street wharf',
    NOW(), NOW()), ('8220156', NULL, 'Sydney Olympic Park Ferry Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.8418, 151.07899, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'sydney olympic park ferry terminal sydney olympic park ferry terminal australia au sydney olympic park ferry terminal',
    NOW(), NOW()), ('8220157', NULL, 'Skinner Lowes Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.3274, 153.4035, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'skinner lowes wharf skinner lowes wharf australia au skinner lowes wharf',
    NOW(), NOW()), ('8220160', NULL, 'Taronga Zoo Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.843, 151.2401, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'taronga zoo wharf taronga zoo wharf australia au taronga zoo wharf',
    NOW(), NOW()), ('8220179', NULL, 'East Arm Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.4907, 130.8817, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east arm wharf east arm wharf australia au east arm wharf',
    NOW(), NOW()), ('8220182', NULL, 'Fishermans Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.45921, 130.85014, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fishermans wharf fishermans wharf australia au fishermans wharf',
    NOW(), NOW()), ('8220183', NULL, 'Fort Hill Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.47193, 130.84608, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fort hill wharf fort hill wharf australia au fort hill wharf',
    NOW(), NOW()), ('8220187', NULL, 'Iron Ore Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.47251, 130.84308, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iron ore wharf iron ore wharf australia au iron ore wharf',
    NOW(), NOW()), ('8220199', NULL, 'Port Keats Barge Landing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.2326, 129.51891, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port keats barge landing port keats barge landing australia au port keats barge landing',
    NOW(), NOW()), ('8220205', NULL, 'Sitebark Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.48015, 130.92925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sitebark wharf sitebark wharf australia au sitebark wharf',
    NOW(), NOW()), ('8220208', NULL, 'Southport Boat Ramp', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.7187, 130.9458, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'southport boat ramp southport boat ramp australia au southport boat ramp',
    NOW(), NOW()), ('8220209', NULL, 'Stokes Hill Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.47034, 130.84935, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stokes hill wharf stokes hill wharf australia au',
    NOW(), NOW()), ('8220235', NULL, 'Port Neill Jetty', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.11651, 136.34932, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port neill jetty port neill jetty australia au port neill jetty',
    NOW(), NOW()), ('8220240', NULL, 'B P Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.82576, 138.50665, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'b p wharf b p wharf australia au b p wharf',
    NOW(), NOW()), ('8220243', NULL, 'North Parade Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84352, 138.49956, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'north parade wharf north parade wharf australia au north parade wharf',
    NOW(), NOW()), ('8220244', NULL, 'Fishermans Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.81099, 138.51813, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fishermans wharf fishermans wharf australia au fishermans wharf',
    NOW(), NOW()), ('8220249', NULL, 'Bowhill Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.88426, 139.62137, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bowhill wharf bowhill wharf australia au bowhill wharf',
    NOW(), NOW()), ('8220263', NULL, 'Maddock and Monchis Landing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.16579, 140.20325, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maddock and monchis landing maddock and monchis landing australia au maddock and monchis landing',
    NOW(), NOW()), ('8220271', NULL, 'Cunningham Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.18208, 138.02089, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cunningham pier cunningham pier australia au cunningham pier',
    NOW(), NOW()), ('8220277', NULL, 'Port Willunga Jetty', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.26181, 138.45936, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port willunga jetty port willunga jetty australia au port willunga jetty',
    NOW(), NOW()), ('8220293', NULL, 'Port Lincoln Town Jetty', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.71914, 135.85852, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln town jetty port lincoln town jetty australia au town jetty',
    NOW(), NOW()), ('8220305', NULL, 'Steamer Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.53574, 138.90462, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'steamer paddock steamer paddock australia au steamer paddock',
    NOW(), NOW()), ('8220317', NULL, 'Pelican Point Container Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.76453, 138.50143, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'pelican point container terminal pelican point container terminal australia au pelican point container terminal',
    NOW(), NOW()), ('8220318', NULL, 'Caltex Oil Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.82431, 138.50755, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caltex oil wharf caltex oil wharf australia au caltex oil wharf',
    NOW(), NOW()), ('8220325', NULL, 'Welshpool Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.70347, 146.45152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'welshpool pier welshpool pier australia au welshpool pier',
    NOW(), NOW()), ('8220330', NULL, 'Barry Bickley Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.89806, 113.6514, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'barry bickley wharf barry bickley wharf australia au barry bickley wharf',
    NOW(), NOW()), ('8220336', NULL, 'Port Bonython Loading Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.99592, 137.76428, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port bonython loading terminal port bonython loading terminal australia au port bonython loading terminal',
    NOW(), NOW()), ('8220360', NULL, 'McLaren Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84251, 138.5034, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mclaren wharf mclaren wharf australia au mclaren wharf',
    NOW(), NOW()), ('8220365', NULL, 'Brinkley Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.36213, 139.37152, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'brinkley wharf brinkley wharf australia au brinkley wharf',
    NOW(), NOW()), ('8220368', NULL, 'Shell Company Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83215, 138.50613, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'shell company wharf shell company wharf australia au shell company wharf',
    NOW(), NOW()), ('8220379', NULL, 'Portee Landing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.43008, 139.60933, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portee landing portee landing australia au portee landing',
    NOW(), NOW()), ('8220382', NULL, 'Musgrave Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84395, 138.49565, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'musgrave wharf musgrave wharf australia au musgrave wharf',
    NOW(), NOW()), ('8220383', NULL, 'Goolwa Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.5045, 138.78613, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'goolwa wharf goolwa wharf australia au goolwa wharf',
    NOW(), NOW()), ('8220385', NULL, 'Port Martin', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.43966, 138.86968, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port martin port martin australia au port martin',
    NOW(), NOW()), ('8220401', NULL, 'Queens Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.8416, 138.50558, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'queens wharf queens wharf australia au queens wharf',
    NOW(), NOW()), ('8220409', NULL, 'MV Troubridge Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84502, 138.49774, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mv troubridge terminal mv troubridge terminal australia au mv troubridge terminal',
    NOW(), NOW()), ('8220427', NULL, 'Princes Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.84384, 138.49818, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'princes wharf princes wharf australia au princes wharf',
    NOW(), NOW()), ('8220433', NULL, 'Mobil Oil Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.82734, 138.50629, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mobil oil wharf mobil oil wharf australia au mobil oil wharf',
    NOW(), NOW()), ('8220446', NULL, 'Cement Company Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.83058, 138.50619, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cement company wharf cement company wharf australia au cement company wharf',
    NOW(), NOW()), ('8220447', NULL, 'The Settlers Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.10532, 138.0255, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the settlers wharf the settlers wharf australia au the settlers wharf',
    NOW(), NOW()), ('8220455', NULL, 'Kings Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.42, 147.11999, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kings wharf kings wharf australia au kings wharf',
    NOW(), NOW()), ('8220456', NULL, 'Macquarie Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.88, 147.34, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'macquarie wharf macquarie wharf australia au macquarie wharf',
    NOW(), NOW()), ('8220462', NULL, 'Beauty Point Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.15, 146.82001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'beauty point wharf beauty point wharf australia au beauty point wharf',
    NOW(), NOW()), ('8220463', NULL, 'Bell Bay Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.14421, 146.90137, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bell bay wharf bell bay wharf australia au bell bay wharf',
    NOW(), NOW()), ('8220465', NULL, 'Comalco Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.13389, 146.86951, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'comalco wharf comalco wharf australia au comalco wharf',
    NOW(), NOW()), ('8220467', NULL, 'Ferry Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.13, 146.86, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ferry wharf ferry wharf australia au ferry wharf',
    NOW(), NOW()), ('8220469', NULL, 'Inspection Head Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.15, 146.82001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'inspection head wharf inspection head wharf australia au inspection head wharf',
    NOW(), NOW()), ('8220470', NULL, 'Tanker Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -41.13, 146.85001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tanker wharf tanker wharf australia au tanker wharf',
    NOW(), NOW()), ('8220472', NULL, 'Altona Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.87181, 144.82959, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'altona pier altona pier australia au altona pier',
    NOW(), NOW()), ('8220479', NULL, 'Fletchers Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.10403, 144.36903, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fletchers pier fletchers pier australia au fletchers pier',
    NOW(), NOW()), ('8220481', NULL, 'Harbour Lights Landing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.81861, 144.9436, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'harbour lights landing harbour lights landing australia au harbour lights landing',
    NOW(), NOW()), ('8220482', NULL, 'K S Anderson Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.35347, 141.61931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'k s anderson wharf k s anderson wharf australia au k s anderson wharf',
    NOW(), NOW()), ('8220485', NULL, 'Marina Drive Jetty', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.04486, 145.58125, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina drive jetty marina drive jetty australia au marina drive jetty',
    NOW(), NOW()), ('8220486', NULL, 'Mildura Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.18306, 142.16667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mildura wharf mildura wharf australia au mildura wharf',
    NOW(), NOW()), ('8220489', NULL, 'Mornington Pier', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.21153, 145.03098, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mornington pier mornington pier australia au mornington pier',
    NOW(), NOW()), ('8220506', NULL, 'Dampier Landing', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.50902, 113.0161, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier landing dampier landing australia au dampier landing',
    NOW(), NOW()), ('8220520', NULL, 'Ferry Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.28683, 149.12432, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'ferry terminal ferry terminal australia au ferry terminal',
    NOW(), NOW()), ('8224808', NULL, 'Springvale Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.78696, 127.67025, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'springvale airport springvale airport australia au springvale airport,zvg,aerodrome de springvale,aérodrome de springvale',
    NOW(), NOW()), ('8224836', NULL, 'Lake Gregory Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.10914, 127.61873, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lake gregory airport lake gregory airport australia au lge,lake gregory airport',
    NOW(), NOW()), ('8236190', NULL, 'Davenport Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.7333, 134.98331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'davenport mine davenport mine australia au davenport mine',
    NOW(), NOW()), ('8236210', NULL, 'Great Davenport Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.75, 134.98331, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'great davenport mine great davenport mine australia au great davenport mine',
    NOW(), NOW()), ('8236220', NULL, 'Jabiluka Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -12.5306, 132.9082, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jabiluka mine jabiluka mine australia au jabiluka mine',
    NOW(), NOW()), ('8236279', NULL, 'Port Darwn Camp Mine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.53435, 131.53185, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port darwn camp mine port darwn camp mine australia au port darwn camp mine',
    NOW(), NOW()), ('8236618', NULL, 'Horse Paddock Opal Diggings', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.45419, 137.1718, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'horse paddock opal diggings horse paddock opal diggings australia au horse paddock opal diggings',
    NOW(), NOW()), ('8236783', NULL, 'Port Lincoln Mines', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.33127, 136.03252, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port lincoln mines port lincoln mines australia au port lincoln mines',
    NOW(), NOW());