INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('8533849', NULL, 'Kimba Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.09276, 136.46695, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kimba airport kimba airport australia au yimb',
    NOW(), NOW()), ('8533854', NULL, 'Sunrise Dam Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.10114, 122.45142, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sunrise dam airport sunrise dam airport australia au ysrd',
    NOW(), NOW()), ('8533858', NULL, 'Jundee Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.42127, 120.57967, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'jundee airport jundee airport australia au yjun',
    NOW(), NOW()), ('8533859', NULL, 'Mangalore Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.88753, 145.18334, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mangalore airport mangalore airport australia au ymng',
    NOW(), NOW()), ('8533875', NULL, 'Yarrawonga Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.03034, 146.02866, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yarrawonga airport yarrawonga airport australia au aeroportul yarrawonga,lapangan terbang yarrawonga,yywg,yarrawonga airport,frwdgah yarawwnga,фурудгоҳи иоровунго,فرودگاه یاراوونگا',
    NOW(), NOW()), ('8533883', NULL, 'Plutonic Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.31555, 119.42701, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'plutonic airport plutonic airport australia au yplu',
    NOW(), NOW()), ('8533889', NULL, 'Loxton Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.47858, 140.66515, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'loxton airport loxton airport australia au ylox',
    NOW(), NOW()), ('8538545', NULL, 'Hampton Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.67145, 116.6747, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'hampton harbour hampton harbour australia au hampton harbour',
    NOW(), NOW()), ('8538547', NULL, 'Port Warrender', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.5258, 125.8774, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port warrender port warrender australia au port warrender',
    NOW(), NOW()), ('8538843', NULL, 'Port Hacking', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.0652, 151.1346, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port hacking port hacking australia au port hacking,port-khaking,порт-хакинг',
    NOW(), NOW()), ('8555578', NULL, 'Cunderdin Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.62349, 117.21674, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cunderdin airport cunderdin airport australia au aeroportul cunderdin,cunderdin airport,lapangan terbang cunderdin,ycun',
    NOW(), NOW()), ('8555580', NULL, 'Fortescue Dave Forrest Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.2892, 119.4343, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fortescue dave forrest airport fortescue dave forrest airport australia au cloudbreak fortes airport,fortescue dave forrest airport,kfe,yfdf',
    NOW(), NOW()), ('8555581', NULL, 'Phillip Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.52003, 145.32691, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'phillip island airport phillip island airport australia au ypid',
    NOW(), NOW()), ('8555582', NULL, 'Yarram Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -38.56656, 146.75209, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yarram airport yarram airport australia au yyrm',
    NOW(), NOW()), ('8555583', NULL, 'Wentworth Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.08716, 141.89697, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wentworth airport wentworth airport australia au ywto',
    NOW(), NOW()), ('8555584', NULL, 'Murrin Murrin Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.71043, 121.88571, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'murrin murrin airport murrin murrin airport australia au aeroport de murrin murrin,aéroport de murrin murrin,murrin murrin airport,wui,ymmi',
    NOW(), NOW()), ('8555592', NULL, 'Yandicoogina Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.67433, 119.16553, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'yandicoogina airport yandicoogina airport australia au aeroportul barimunya,byp,barimunya airport,barimunya ji chang,barimunya機場,lapangan terbang barimunya,ybry,aerodrome de barimunya,aérodrome de barimunya',
    NOW(), NOW()), ('8555593', NULL, 'Saint Arnaud Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.63952, 143.18484, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'saint arnaud airport saint arnaud airport australia au ysta',
    NOW(), NOW()), ('8555594', NULL, 'Forrestania Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.58253, 119.70795, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'forrestania airport forrestania airport australia au yfta',
    NOW(), NOW()), ('8555596', NULL, 'Kambalda Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.19606, 121.60037, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'kambalda airport kambalda airport australia au kdb,kambalda airport,ykbl',
    NOW(), NOW()), ('8555597', NULL, 'Bronzewing Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.36632, 121.03221, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bronzewing airport bronzewing airport australia au ybwg',
    NOW(), NOW()), ('8555598', NULL, 'Darlot Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.87831, 121.2764, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'darlot airport darlot airport australia au ydlo',
    NOW(), NOW()), ('8555599', NULL, 'Coondewanna Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.96661, 118.81413, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'coondewanna airport coondewanna airport australia au cjf,coondewanna airport,ycwa',
    NOW(), NOW()), ('8555608', NULL, 'Goodooga Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.07427, 147.38717, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'goodooga airport goodooga airport australia au ygda',
    NOW(), NOW()), ('8555610', NULL, 'Donald Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.36141, 143.00496, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'donald airport donald airport australia au ydod',
    NOW(), NOW()), ('8555612', NULL, 'Sea Lake Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.53121, 142.8899, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sea lake airport sea lake airport australia au yslk',
    NOW(), NOW()), ('8555613', NULL, 'Warburton Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.12446, 126.58323, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'warburton airport warburton airport australia au ywbr',
    NOW(), NOW()), ('8555614', NULL, 'Troughton Island Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -13.75279, 126.14875, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'troughton island airport troughton island airport australia au aeroportul troughton island,lapangan terbang troughton i,troughton island airport,ytti',
    NOW(), NOW()), ('8555616', NULL, 'Golden Grove Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.76337, 116.96925, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'golden grove airport golden grove airport australia au ygge',
    NOW(), NOW()), ('8555617', NULL, 'Wycheproof Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -36.06442, 143.24028, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'wycheproof airport wycheproof airport australia au ywyf',
    NOW(), NOW()), ('8555618', NULL, 'The Monument Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.81166, 139.92329, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'the monument airport the monument airport australia au aeroportul the monument,lapangan terbang the monument,phq,phosphate hill airport,the monument airport,ytmo,yi sa shan,ザ・モニュメント空港,伊薩山',
    NOW(), NOW()), ('8555620', NULL, 'Lake Cargelligo Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.28492, 146.37109, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lake cargelligo airport lake cargelligo airport australia au ylcg',
    NOW(), NOW()), ('8555625', NULL, 'Windarling Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.03232, 119.38585, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'windarling airport windarling airport australia au wrn,windarling airport,ywdg',
    NOW(), NOW()), ('8555626', NULL, 'William Creek Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.9061, 136.34385, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'william creek airport william creek airport australia au aeroportul william creek,william creek,william creek airport,yywc',
    NOW(), NOW()), ('8555628', NULL, 'Century Mine Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.756, 138.7066, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'century mine airport century mine airport australia au ycny',
    NOW(), NOW()), ('8555629', NULL, 'Springsure Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -24.1285, 148.08676, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'springsure airport springsure airport australia au yspi',
    NOW(), NOW()), ('8555633', NULL, 'Lawlers Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.0922, 120.5395, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lawlers airport lawlers airport australia au aeroport de lawlers,aéroport de lawlers,lawlers airport,ylaw',
    NOW(), NOW()), ('8555654', NULL, 'Lake Johnston Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.31971, 120.55156, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'lake johnston airport lake johnston airport australia au yljn',
    NOW(), NOW()), ('8555655', NULL, 'Pooncarie Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.37338, 142.58627, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'pooncarie airport pooncarie airport australia au ypce',
    NOW(), NOW()), ('8555664', NULL, 'Mount Gordon Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -19.77262, 139.40221, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'mount gordon airport mount gordon airport australia au gpd,mount gordon airport,ygon',
    NOW(), NOW()), ('8555873', NULL, 'Redcliffe Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -27.20632, 153.06916, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'redcliffe airport redcliffe airport australia au aeroportul redcliffe,lapangan terbang redcliffe,redcliffe airport,yred,frwdgah rdklyf  astralya,фурудгоҳи рдклиф,فرودگاه ردکلیف، استرالیا',
    NOW(), NOW()), ('8555897', NULL, 'Maryborough Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -37.03478, 143.70787, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'maryborough airport maryborough airport australia au ymbu',
    NOW(), NOW()), ('8555943', NULL, 'Birchip Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -35.99948, 142.91513, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'birchip airport birchip airport australia au aeroportul birchip,birchip,birchip airport,lapangan terbang birchip,ybir',
    NOW(), NOW()), ('8556004', NULL, 'Ginbata Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.55767, 120.04814, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ginbata airport ginbata airport australia au aeroportul ginbata,gbw,ginbata airport,sylvania homestead airport,ygia,aerodrome de ginbata,aérodrome de ginbata',
    NOW(), NOW()), ('8556009', NULL, 'Miles Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -26.80936, 150.16517, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miles airport miles airport australia au aeroportul miles,miles airport,miles ji chang,miles機場,wle,ymls,mairuzu kong gang,マイルズ空港',
    NOW(), NOW()), ('8556010', NULL, 'West Angelas Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.13673, 118.70667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west angelas airport west angelas airport australia au wlp,west angelas airport,yang',
    NOW(), NOW()), ('8556012', NULL, 'West Angelas Mine Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.17786, 118.69994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'west angelas mine airport west angelas mine airport australia au west angelas mine airport',
    NOW(), NOW()), ('8594392', NULL, 'Porter Bay', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -42.82, 147.32001, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'porter bay porter bay australia au porter bay',
    NOW(), NOW()), ('8594507', NULL, 'Old Harbour Lagoon', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -31.9235, 148.7596, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'old harbour lagoon old harbour lagoon australia au old harbour lagoon',
    NOW(), NOW()), ('8594593', NULL, 'Manly Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.7985, 151.28461, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'manly wharf manly wharf australia au manly wharf',
    NOW(), NOW()), ('8596468', NULL, 'Top Bullock Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.11229, 139.04092, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'top bullock paddock bore top bullock paddock bore australia au top bullock paddock bore',
    NOW(), NOW()), ('8596647', NULL, 'Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.18206, 139.76623, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paddock bore paddock bore australia au paddock bore',
    NOW(), NOW()), ('8596661', NULL, 'Stockport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.74217, 139.75219, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'stockport stockport australia au stockport',
    NOW(), NOW()), ('8596836', NULL, 'Bull Paddock Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.75922, 140.26861, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bull paddock dam bull paddock dam australia au bull paddock dam',
    NOW(), NOW()), ('8597006', NULL, 'Bullock Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.58669, 141.55773, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullock paddock tank bullock paddock tank australia au bullock paddock tank',
    NOW(), NOW()), ('8597069', NULL, 'Big Paddock Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.0433, 142.05942, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big paddock dam big paddock dam australia au big paddock dam',
    NOW(), NOW()), ('8598675', NULL, 'Bullock Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.43271, 145.18332, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullock paddock bore bullock paddock bore australia au bullock paddock bore',
    NOW(), NOW()), ('8598770', NULL, 'River Paddock Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.47851, 145.84623, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'river paddock dam river paddock dam australia au river paddock dam',
    NOW(), NOW()), ('8598906', NULL, 'Portwine', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.82798, 147.15699, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portwine portwine australia au port wine,portwine',
    NOW(), NOW()), ('8599641', NULL, 'Port of Saint Lawrence', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.27783, 149.60077, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'port of saint lawrence port of saint lawrence australia au port of saint lawrence',
    NOW(), NOW()), ('8600138', NULL, 'Port Norman', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.54195, 140.7906, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port norman port norman australia au port norman',
    NOW(), NOW()), ('8600280', NULL, 'Waterloo Holding Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.73746, 142.61252, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'waterloo holding paddock waterloo holding paddock australia au waterloo holding paddock',
    NOW(), NOW()), ('8600283', NULL, 'Middle Yard Holding Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.6521, 142.72978, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'middle yard holding paddock middle yard holding paddock australia au middle yard holding paddock',
    NOW(), NOW()), ('8600369', NULL, 'Bullock Paddock Yard', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.77066, 143.45847, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullock paddock yard bullock paddock yard australia au bullock paddock yard',
    NOW(), NOW()), ('8600426', NULL, 'Bundock Yards', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -19.18501, 144.3791, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bundock yards bundock yards australia au bundock yards',
    NOW(), NOW()), ('8600517', NULL, 'Mourilyan Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.60024, 146.12513, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'mourilyan harbour mourilyan harbour australia au mourilyan harbour',
    NOW(), NOW()), ('8605646', NULL, 'Sundown Plain Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.27228, 134.13079, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'sundown plain paddock sundown plain paddock australia au',
    NOW(), NOW()), ('8605921', NULL, 'Marina Plains', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.54974, 143.87319, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'marina plains marina plains australia au',
    NOW(), NOW()), ('8605969', NULL, 'Reedy Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -15.75661, 141.69761, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'reedy paddock reedy paddock australia au',
    NOW(), NOW()), ('8606141', NULL, 'Ram Paddock Well', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -18.00528, 122.6024, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ram paddock well ram paddock well australia au',
    NOW(), NOW()), ('8606492', NULL, 'Bullock Paddock Yards', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.56832, 144.19777, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bullock paddock yards bullock paddock yards australia au',
    NOW(), NOW()), ('8606532', NULL, 'Flattery Harbour', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.93908, 145.31087, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'flattery harbour flattery harbour australia au',
    NOW(), NOW()), ('8607327', NULL, 'Cow Paddock Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.4333, 135.8833, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cow paddock bore cow paddock bore australia au',
    NOW(), NOW()), ('8608205', NULL, 'Napier Creek', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -16.63275, 126.3296, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'napier creek napier creek australia au',
    NOW(), NOW()), ('8608290', NULL, 'Erskine Terminal', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -17.84626, 124.36837, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'erskine terminal erskine terminal australia au',
    NOW(), NOW()), ('8612467', NULL, 'First Plain Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.3603, 143.15322, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'first plain paddock tank first plain paddock tank australia au first plain paddock tank',
    NOW(), NOW()), ('8612468', NULL, 'Second Plain Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.39869, 143.18089, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'second plain paddock tank second plain paddock tank australia au second plain paddock tank',
    NOW(), NOW()), ('8612665', NULL, 'Edwards Paddock Tank', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.79511, 143.52462, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'edwards paddock tank edwards paddock tank australia au edwards paddock tank',
    NOW(), NOW()), ('8615120', NULL, 'Portana', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.76591, 135.37512, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portana portana australia au portana',
    NOW(), NOW()), ('8615497', NULL, 'Port Bonython', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -32.99073, 137.77537, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port bonython port bonython australia au port bonython',
    NOW(), NOW()), ('8615502', NULL, 'Port Davis', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.26673, 137.85411, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'port davis port davis australia au port davis',
    NOW(), NOW()), ('8616643', NULL, 'Dampier Rock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -34.28158, 122.35379, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier rock dampier rock australia au dampier rock',
    NOW(), NOW()), ('8617210', NULL, 'Karara Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.21451, 116.68442, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'karara airport karara airport australia au kqr,karara airport,ykar',
    NOW(), NOW()), ('8621817', NULL, 'Dampier Archipelago', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.52049, 116.44114, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dampier archipelago dampier archipelago australia au',
    NOW(), NOW()), ('8623372', NULL, 'Big Paddock Dam', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -22.92028, 114.12111, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'big paddock dam big paddock dam australia au big paddock dam',
    NOW(), NOW()), ('8623497', NULL, 'Handocks Bore', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -21.79085, 115.674, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'handocks bore handocks bore australia au',
    NOW(), NOW()), ('8623624', NULL, 'East Paddock Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -23.49981, 115.6233, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'east paddock hill east paddock hill australia au',
    NOW(), NOW()), ('8624784', NULL, 'Trap Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -20.55277, 132.11939, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'trap paddock trap paddock australia au',
    NOW(), NOW()), ('8626451', NULL, 'Iluka', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -29.66779, 149.41931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'iluka iluka australia au iluka',
    NOW(), NOW()), ('8628260', NULL, 'Amarina', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.98341, 152.97983, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'amarina amarina australia au amarina',
    NOW(), NOW()), ('8633784', NULL, 'Home Paddock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -25.76466, 148.38662, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'home paddock home paddock australia au home paddock',
    NOW(), NOW()), ('8644119', NULL, 'Truscott-Mungalalu Airport', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -14.08996, 126.3826, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'truscott-mungalalu airport truscott-mungalalu airport australia au ttx,truscott-mungalalu airport,ytst',
    NOW(), NOW()), ('8645218', NULL, 'Little Pier Street', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87814, 151.20245, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'little pier street little pier street australia au little pier street',
    NOW(), NOW()), ('8645357', NULL, 'Gregory', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.18833, 114.25167, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gregory gregory australia au gregory,port gregory',
    NOW(), NOW()), ('8647168', NULL, 'Poison Paddock Mill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -28.32254, 118.10322, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'poison paddock mill poison paddock mill australia au poison paddock mill',
    NOW(), NOW()), ('8647739', NULL, 'Gnabberdocking Rock', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.70595, 119.0726, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gnabberdocking rock gnabberdocking rock australia au gnabberdocking rock',
    NOW(), NOW()), ('8648375', NULL, 'Gundockerta Hill', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -30.76592, 122.1309, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gundockerta hill gundockerta hill australia au gundockerta hill',
    NOW(), NOW()), ('8648723', NULL, 'Cockle Bay Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.87187, 151.20224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cockle bay wharf cockle bay wharf australia au cockle bay wharf',
    NOW(), NOW()), ('8663298', NULL, 'Ferry Wharf', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.85812, 151.22994, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'ferry wharf ferry wharf australia au ferry wharf',
    NOW(), NOW()), ('8663442', NULL, 'Cowper Wharf Roadway', NULL,
    NULL, 'AU', 'Australia', NULL, NULL,
    -33.86864, 151.21918, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cowper wharf roadway cowper wharf roadway australia au cowper wharf roadway',
    NOW(), NOW());