INSERT INTO ports (
      world_port_index, region_name, main_port_name, alternate_port_name,
      un_locode, country_code, country_name, world_water_body, iho_sea_area,
      latitude, longitude, harbor_size, harbor_type, harbor_use, shelter_afforded,
      tidal_range, entrance_width, channel_depth, anchorage_depth, cargo_pier_depth,
      max_vessel_length, max_vessel_beam, max_vessel_draft,
      pilotage_compulsory, pilotage_available, tugs_assistance,
      facilities_wharves, facilities_anchorage, facilities_container,
      facilities_oil_terminal, facilities_lng_terminal, search_text,
      created_at, updated_at
    ) VALUES ('3430601', NULL, 'Montecarlo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.56849, -54.7579, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'montecarlo montecarlo argentina ar montecarlo,puerto montecarlo',
    NOW(), NOW()), ('3430669', NULL, 'Miramar Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.2279, -57.87199, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'miramar airport miramar airport argentina ar aeroport de miramar,aeropuerto de miramar,aéroport de miramar,mjr,miramar airport',
    NOW(), NOW()), ('3430864', NULL, 'Astor Piazzolla International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.93417, -57.57333, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'astor piazzolla international airport astor piazzolla international airport argentina ar aeroporto internacional astor piazolla,aeroporto di mar del plata,aeroportul international astor piazzolla,aeroportul internațional astor piazzolla,aeropuerto internacional de mar del plata astor piazzolla,aeropuerto internacional de mar del plata ástor piazzolla,astor piazzolla international airport,flughafen mar del plata,internationale luchthaven astor piazzolla,lapangan terbang brig gen d bartolome de la col,mdq,maes awyr rhyngwladol astor piazzolla,mar del plata,port lotniczy mar del plata,sazm,aeroport astor piazzolla de mar del plata,aéroport astor piazzolla de mar del plata,фурудгоҳи бин‌алмилалӣ остур пиотзуло,فرودگاه بین‌المللی آستور پیاتزولا,アスター・ピアソラ国際空港,阿斯托爾·皮亞佐拉國際機場',
    NOW(), NOW()), ('3431712', NULL, 'Las Marinas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.01667, -59.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'las marinas las marinas argentina ar',
    NOW(), NOW()), ('3432019', NULL, 'Puesto La Porteña', 'Puesto La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.4, -57.9, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto la porteña puesto la portena argentina ar',
    NOW(), NOW()), ('3432020', NULL, 'Puesto La Porteña', 'Puesto La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.0447, -58.20575, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puesto la porteña puesto la portena argentina ar',
    NOW(), NOW()), ('3432021', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.02497, -57.44656, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3432022', NULL, 'La Porteña', 'La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.93916, -59.33221, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la porteña la portena argentina ar estancia la portena,estancia la porteña,la portena,la porteña',
    NOW(), NOW()), ('3432023', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.30877, -59.09587, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar estancia la portena,estancia la porteña',
    NOW(), NOW()), ('3432024', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.29473, -59.97914, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3432025', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.49606, -59.1451, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3432026', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.95, -58.85, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3432027', NULL, 'Estancia La Porteña', 'Estancia La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.28551, -59.53554, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la porteña estancia la portena argentina ar',
    NOW(), NOW()), ('3432028', NULL, 'Almacén La Porteña', 'Almacen La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.23703, -59.0177, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'almacén la porteña almacen la portena argentina ar',
    NOW(), NOW()), ('3432029', NULL, 'La Portena', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.03333, -57.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'la portena la portena argentina ar',
    NOW(), NOW()), ('3432038', NULL, 'Puerto La Plata', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.85, -57.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto la plata puerto la plata argentina ar la plata,puerto la plata',
    NOW(), NOW()), ('3432230', NULL, 'Estancia La Marina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.0715, -58.48374, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia la marina estancia la marina argentina ar',
    NOW(), NOW()), ('3433429', NULL, 'Irineo Portela', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.97983, -59.67012, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'irineo portela irineo portela argentina ar i. portela,ireneo portela,irineo portela',
    NOW(), NOW()), ('3433536', NULL, 'Puerto Hormiguero', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.59329, -56.03438, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto hormiguero puerto hormiguero argentina ar hormiguero,puerto hormiguero',
    NOW(), NOW()), ('3434452', NULL, 'Arroyo El Portugués', 'Arroyo El Portugues',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.13333, -58.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo el portugués arroyo el portugues argentina ar',
    NOW(), NOW()), ('3434453', NULL, 'Estancia El Porteño', 'Estancia El Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.73765, -59.60114, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia el porteño estancia el porteno argentina ar',
    NOW(), NOW()), ('3434454', NULL, 'Canal El Porteño', 'Canal El Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.02821, -57.35154, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal el porteño canal el porteno argentina ar',
    NOW(), NOW()), ('3434455', NULL, 'Arroyo El Porteño', 'Arroyo El Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.01667, -57.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo el porteño arroyo el porteno argentina ar',
    NOW(), NOW()), ('3434456', NULL, 'El Porteño', 'El Porteno',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.72398, -59.57751, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'el porteño el porteno argentina ar',
    NOW(), NOW()), ('3434521', NULL, 'Estancia El Oportuno', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.21667, -58.38333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia el oportuno estancia el oportuno argentina ar',
    NOW(), NOW()), ('3435050', NULL, 'Dock Sud', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.65063, -58.34493, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'dock sud dock sud argentina ar dock sud,dock sur',
    NOW(), NOW()), ('3435365', NULL, 'Clorinda Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -25.3, -57.73333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'clorinda airport clorinda airport argentina ar aeropuerto clorinda,clx,clorinda airport,satc',
    NOW(), NOW()), ('3435529', NULL, 'Cerro Campo Santamarina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.63333, -59.28333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cerro campo santamarina cerro campo santamarina argentina ar',
    NOW(), NOW()), ('3435679', NULL, 'Caraguatay', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.60587, -54.78093, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caraguatay caraguatay argentina ar caraguatay,puerto caraguatay',
    NOW(), NOW()), ('3435910', NULL, 'Buenos Aires', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.61315, -58.37723, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'buenos aires buenos aires argentina ar bue,baires,bonaero,bonaeropolis,bonaëropolis,bos aires,bouenos aires,bouonezar,bouonézâr,buehnas-ajrehs,buehnos ajres,buehnos-ajres,buehnos-ajres osh,buenos aires,buenos airės,buenos ajres,buenos ares,buenos ayres,buenos-aires,buenos-ajres,buenos-ayres,buenos-aýres,buenosairesa,buénos ayrés,bwenoze,bwènozè,búenos aíres,ciudad autonoma de buenos aires,ciudad autónoma de buenos aires,ciudad de la santisima trinidad y puerto de santa maria del buen ayre,ciudad de la santísima trinidad y puerto de santa maría del buen ayre,lungsod ng buenos aires,santa maria del buen ayre,santa maría del buen ayre,bawnosxires,bu yi nuo si ai li si,bu''enosa a''iresa,buenos-airesi,buenosaires,buenoseuaileseu,buenosuairesu,buraenosa a''iresa,buyenosa a''iresa,bwyns ayrs,bwynws ayrs,bwynws ayrys,byu''enosa erisa,byunas airis,byunas ayels,bywns ayrs,puvenas airis,μπουένος ΄aιρες,μπουένος άιρες,буенос аирес,буенос айрес,буенос аірес,буенос ајрес,буенос-аирес,буенос-айрес,буэнас-айрэс,буэнос айрес,буэнос-айрес,буэнос-айрес ош,բուենոս այրես,בואנוס איירס,בוענאס איירעס,بوئنوس آیرس,بوينس آيرس,بوينوس ايريس,بۆینس ئایرس,بیونس آئرس,बुएनोस आइरेस,ब्युएनॉस एरीस,বুয়েনোস আইরেস,বুৱেনোস আইরেস,புவெனஸ் ஐரிஸ்,ಬ್ಯೂನಸ್ ಐರಿಸ್,ബ്യൂണസ് അയേഴ്സ്,บัวโนสไอเรส,པུ་ཨེ་ནོ་སི་ཨས་རི་སི།,ဗျူနိုအေးရိစ်မြို့,ბუენოს-აირესი,ብዌኖስ አይሬስ,ブエノスアイレス,布宜諾斯艾利斯,布宜诺斯艾利斯,부에노스아이레스',
    NOW(), NOW()), ('3473394', NULL, 'Puerto Nuevo', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.58085, -58.37193, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto nuevo puerto nuevo argentina ar buenos aires,puerto nuevo',
    NOW(), NOW()), ('3473395', NULL, 'Puerto Olivos', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.50833, -58.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto olivos puerto olivos argentina ar',
    NOW(), NOW()), ('3473396', NULL, 'Puerto San Isidro', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.45833, -58.5, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san isidro puerto san isidro argentina ar',
    NOW(), NOW()), ('3473397', NULL, 'Puerto San Fernando', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.43333, -58.55, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san fernando puerto san fernando argentina ar',
    NOW(), NOW()), ('3473398', NULL, 'Puerto Tigre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.42361, -58.58333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto tigre puerto tigre argentina ar',
    NOW(), NOW()), ('3473774', NULL, 'Canal de Acceso al Puerto de Buenos Aires', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.63713, -58.10763, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'canal de acceso al puerto de buenos aires canal de acceso al puerto de buenos aires argentina ar buenos aires channel',
    NOW(), NOW()), ('3473786', NULL, 'Gran Dock', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.86667, -57.9, 'Small', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'gran dock gran dock argentina ar',
    NOW(), NOW()), ('3832041', NULL, 'Portezuelo del Morado', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.32169, -70.00657, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del morado portezuelo del morado argentina ar portezuelo del morada,portezuelo del morado',
    NOW(), NOW()), ('3832241', NULL, 'Portillo Yesito', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.63333, -70.45, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo yesito portillo yesito argentina ar',
    NOW(), NOW()), ('3832247', NULL, 'Portezuelo de la Yesera', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.03466, -69.63584, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de la yesera portezuelo de la yesera argentina ar',
    NOW(), NOW()), ('3832374', NULL, 'Yacimientos Petrolíferos Fiscales Planta Terminal Puerto Rosales', 'Yacimientos Petroliferos Fiscales Planta Terminal Puerto Rosales',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.92527, -62.04751, 'Medium', 'Coastal (Artificial)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'yacimientos petrolíferos fiscales planta terminal puerto rosales yacimientos petroliferos fiscales planta terminal puerto rosales argentina ar',
    NOW(), NOW()), ('3832428', NULL, 'Estancia V. Oporto', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -45.5474, -69.28843, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia v. oporto estancia v. oporto argentina ar',
    NOW(), NOW()), ('3832839', NULL, 'Portillo del Viento', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.92785, -69.41488, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del viento portillo del viento argentina ar',
    NOW(), NOW()), ('3832840', NULL, 'Portezuelo del Viento', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.0604, -69.52095, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del viento portezuelo del viento argentina ar',
    NOW(), NOW()), ('3832870', NULL, 'Estancia Vieja La Porteña', 'Estancia Vieja La Portena',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.43886, -70.62929, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia vieja la porteña estancia vieja la portena argentina ar estancia vieja,estancia vieja la portena,estancia vieja la porteña',
    NOW(), NOW()), ('3832905', NULL, 'Portezuelo Vicuñorco', 'Portezuelo Vicunorco',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.23468, -66.99687, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo vicuñorco portezuelo vicunorco argentina ar',
    NOW(), NOW()), ('3833068', NULL, 'Puerto Venado', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -41.0507, -71.37504, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto venado puerto venado argentina ar',
    NOW(), NOW()), ('3833131', NULL, 'Portezuelo Vega del Loro', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -34.73037, -69.65033, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo vega del loro portezuelo vega del loro argentina ar',
    NOW(), NOW()), ('3833136', NULL, 'Portezuelo de Vega', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -29.70522, -67.04499, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de vega portezuelo de vega argentina ar',
    NOW(), NOW()), ('3833190', NULL, 'Puerto Vancouver', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.8, -64.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto vancouver puerto vancouver argentina ar bahia vancouver,port vancouver,puerto vancouver',
    NOW(), NOW()), ('3833193', NULL, 'Laguna Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.99364, -60.52734, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'laguna vallimanca laguna vallimanca argentina ar',
    NOW(), NOW()), ('3833194', NULL, 'Estancia Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.95199, -60.47615, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia vallimanca estancia vallimanca argentina ar',
    NOW(), NOW()), ('3833195', NULL, 'Arroyo Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.82394, -60.2973, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'arroyo vallimanca arroyo vallimanca argentina ar',
    NOW(), NOW()), ('3833196', NULL, 'Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.93333, -60.51667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vallimanca vallimanca argentina ar',
    NOW(), NOW()), ('3833197', NULL, 'Vallimanca', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.3429, -61.03302, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'vallimanca vallimanca argentina ar vallimanca',
    NOW(), NOW()), ('3833232', NULL, 'Paso Vallecito', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -30.45, -70.15, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso vallecito paso vallecito argentina ar paso vallecillo,paso vallecito,portezuelo vallecillos,portezuelo vallecitos,portezuelo de vallecita,punto accesible vallecito',
    NOW(), NOW()), ('3833247', NULL, 'Portezuelo de Valle Ancho Sur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.43333, -68.96667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de valle ancho sur portezuelo de valle ancho sur argentina ar portezuelo valle ancho ii,portezuelo valle ancho segundo,portezuelo valle ancho sur,portezuelo de valle ancho sur',
    NOW(), NOW()), ('3833248', NULL, 'Portezuelo de Valle Ancho Norte', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.41667, -68.93333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de valle ancho norte portezuelo de valle ancho norte argentina ar portezuelo valle ancho i,portezuelo valle ancho norte,portezuelo valle ancho norte primero,portezuelo de valle ancho norte',
    NOW(), NOW()), ('3833276', NULL, 'Estancia Valdés', 'Estancia Valdes',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.44474, -63.649, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'estancia valdés estancia valdes argentina ar estancia valdes,estancia valdés,puerto valdes,puerto valdés',
    NOW(), NOW()), ('3833305', NULL, 'Portillo de las Vacas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.83333, -69.56667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo de las vacas portillo de las vacas argentina ar',
    NOW(), NOW()), ('3833353', NULL, 'Uspallata Pass', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.8253, -70.08295, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uspallata pass uspallata pass argentina ar boquete uspallata,la cumbre,paso de uspallata,paso de la cumbre,portillo de uspallata,uspallata pass,uspallata-juncal pass',
    NOW(), NOW()), ('3833359', NULL, 'Uspallata', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.55, -69.33333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'uspallata uspallata argentina ar aeropuerto de uspallata,uspallata,uspallata airport',
    NOW(), NOW()), ('3833376', NULL, 'Portillo Urrutia', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.44379, -70.38662, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo urrutia portillo urrutia argentina ar',
    NOW(), NOW()), ('3833610', NULL, 'Paso Tromen Primero', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -39.5, -71.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso tromen primero paso tromen primero argentina ar paso tromen i,paso tromen primero,portezuelo tromen,portezuelo tromén',
    NOW(), NOW()), ('3833622', NULL, 'Paso Trolón', 'Paso Trolon',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.78333, -70.35, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso trolón paso trolon argentina ar paso trolon,paso trolón,portezuelo trolon sur,portezuelo trolón sur',
    NOW(), NOW()), ('3833688', NULL, 'Paso de Tres Quebradas', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.31667, -68.86667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de tres quebradas paso de tres quebradas argentina ar paso toro muerto,paso tres quebradas,paso de toro muerto,paso de tres quebradas,portezuelo de tres quebradas',
    NOW(), NOW()), ('3833724', NULL, 'Tres Porteñas', 'Tres Portenas',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.89884, -68.38811, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tres porteñas tres portenas argentina ar tres portenas,tres porteñas',
    NOW(), NOW()), ('3833860', NULL, 'Tres Arroyos Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.38876, -60.32928, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'tres arroyos airport tres arroyos airport argentina ar oyo,sazh,tres arroyos airport',
    NOW(), NOW()), ('3834028', NULL, 'Portillo la Totora', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.23175, -70.14542, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo la totora portillo la totora argentina ar',
    NOW(), NOW()), ('3834056', NULL, 'Portezuelo Toscoso', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -35.54828, -70.16731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo toscoso portezuelo toscoso argentina ar portezuelo toscoso,portillo toscoso',
    NOW(), NOW()), ('3834292', NULL, 'Portezuelo de Tocino', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.8, -67.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de tocino portezuelo de tocino argentina ar',
    NOW(), NOW()), ('3834416', NULL, 'Portillo del Tigre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.14198, -69.5509, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del tigre portillo del tigre argentina ar',
    NOW(), NOW()), ('3834544', NULL, 'Portillo del Telégrafo', 'Portillo del Telegrafo',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.78813, -68.99957, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo del telégrafo portillo del telegrafo argentina ar',
    NOW(), NOW()), ('3834614', NULL, 'Portezuelo Tar', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -48.95, -72, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo tar portezuelo tar argentina ar',
    NOW(), NOW()), ('3834982', NULL, 'Portezuelo Sumich', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -46.8, -70.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sumich portezuelo sumich argentina ar',
    NOW(), NOW()), ('3835072', NULL, 'Portezuelo de Soroche', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -27.0778, -67.46224, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de soroche portezuelo de soroche argentina ar',
    NOW(), NOW()), ('3835119', NULL, 'Cajón Solimán', 'Cajon Soliman',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.01667, -71.06667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'cajón solimán cajon soliman argentina ar',
    NOW(), NOW()), ('3835211', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.15, -71.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar paso pulul norte,portezuelo santa pola,portezuelo sin nombre',
    NOW(), NOW()), ('3835212', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.11667, -71.01667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo san rosario,portezuelo sin nombre',
    NOW(), NOW()), ('3835213', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.01667, -71.05, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo sin nombre',
    NOW(), NOW()), ('3835214', NULL, 'Portezuelo Sin Nombre', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -37.95, -71.08333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sin nombre portezuelo sin nombre argentina ar portezuelo sin nombre',
    NOW(), NOW()), ('3835356', NULL, 'Portezuelo Laguna Fea', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.16667, -70.48333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo laguna fea portezuelo laguna fea argentina ar paso saco,paso de sepulveda,paso de sepúlveda,portezuelo laguna fea',
    NOW(), NOW()), ('3835953', NULL, 'Portezuelo Santa Rosa', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -28.93333, -67.65, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo santa rosa portezuelo santa rosa argentina ar',
    NOW(), NOW()), ('3836082', NULL, 'Colonia Santamarina', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -36.3, -64.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'colonia santamarina colonia santamarina argentina ar',
    NOW(), NOW()), ('3836280', NULL, 'Aerodromo Santa Fe', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -31.66667, -60.83333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'aerodromo santa fe aerodromo santa fe argentina ar safe,santa fe airport,santa fé airport',
    NOW(), NOW()), ('3836297', NULL, 'Puerto Santa Elena', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -44.52289, -65.34865, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto santa elena puerto santa elena argentina ar port santa elena,puerto santa elena',
    NOW(), NOW()), ('3836383', NULL, 'Portillo Santa Clara', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -33.26649, -69.69321, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portillo santa clara portillo santa clara argentina ar portillo santa clara,portillo del azufre',
    NOW(), NOW()), ('3836607', NULL, 'Fondeadero San Román', 'Fondeadero San Roman',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.25242, -64.25867, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'fondeadero san román fondeadero san roman argentina ar fondeadero roman,fondeadero san roman,fondeadero san román,puerto san roman,puerto san román',
    NOW(), NOW()), ('3836687', NULL, 'Portezuelo Sanquilcó', 'Portezuelo Sanquilco',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -38.73513, -70.8114, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo sanquilcó portezuelo sanquilco argentina ar',
    NOW(), NOW()), ('3837055', NULL, 'Caleta San Luis', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.73632, -63.95931, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'caleta san luis caleta san luis argentina ar puerto san luis,puerto shank',
    NOW(), NOW()), ('3837131', NULL, 'Bahía San Julián', 'Bahia San Julian',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -49.34035, -67.709, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'bahía san julián bahia san julian argentina ar bahia san julian,bahía san julián,puerto san julian,san julian bay,san julián bay',
    NOW(), NOW()), ('3837140', NULL, 'Puerto San Juan del Salvamento', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -54.73949, -63.85529, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san juan del salvamento puerto san juan del salvamento argentina ar puerto san juan,puerto san juan del salvamento,saint john harbour',
    NOW(), NOW()), ('3837255', NULL, 'Puerto San José', 'Puerto San Jose',
    NULL, 'AR', 'Argentina', NULL, NULL,
    -42.41729, -64.12117, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san josé puerto san jose argentina ar',
    NOW(), NOW()), ('3837639', NULL, 'Paso de San Francisco', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.87169, -68.29731, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'paso de san francisco paso de san francisco argentina ar paso de san francisco,portezuelo san francisco,san francisco pass',
    NOW(), NOW()), ('3837913', NULL, 'Portezuelo de San Buenaventura', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -26.78479, -67.88299, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de san buenaventura portezuelo de san buenaventura argentina ar',
    NOW(), NOW()), ('3837980', NULL, 'San Antonio Oeste', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.73193, -64.94769, 'Medium', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, true,
    true, true, false,
    false, false, 'san antonio oeste san antonio oeste argentina ar oes,puerto san antonio oeste,san antonio oeste,san antonio oestė,xi sheng an dong ni ao,西圣安东尼奥',
    NOW(), NOW()), ('3837999', NULL, 'Puerto San Antonio', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -40.74526, -64.86488, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'puerto san antonio puerto san antonio argentina ar',
    NOW(), NOW()), ('3838282', NULL, 'Portezuelo de Salin Sur', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.36667, -68.18333, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo de salin sur portezuelo de salin sur argentina ar paso del salin,paso del salín,portezuelo salin,portezuelo salín,portezuelo de salin sur',
    NOW(), NOW()), ('3838559', NULL, 'Rosario International Airport', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -32.90361, -60.785, 'Large', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    true, true, true,
    true, true, true,
    false, false, 'rosario international airport rosario international airport argentina ar aeroporto internacional rosario islas malvinas,aeroporto de rosario-illas malvinas,aeroporto di rosario,aeroportul international rosario - islas malvinas,aeroportul internațional rosario – islas malvinas,aeropuerto internacional rosario,aeropuerto internacional rosario islas malvinas,bandar udara internasional rosario - islas malvinas,bandar udara internasional rosario – islas malvinas,flughafen rosario,lapangan terbang rosario,port lotniczy rosario,ros,rosario - islas malvinas international airport,rosario international airport,rosario – islas malvinas international airport,saar,aeroport de rosario,aéroport de rosario,luo sa li ao,mtar rwzaryw aldwlyt,rosario,фурудгоҳи бин‌алмилалӣ рсрю – оислс млуинс,נמל התעופה הבינלאומי רוסאריו איסלאס מלווינס,فرودگاه بین‌المللی رسریو – ایسلس ملوینس,مطار روزاريو الدولية,ロサリオ,羅薩里奧',
    NOW(), NOW()), ('3838597', NULL, 'Portezuelo del Rosal', NULL,
    NULL, 'AR', 'Argentina', NULL, NULL,
    -24.46667, -64.46667, 'Small', 'Coastal (Natural)', 'Commercial', 'Good',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL,
    false, true, false,
    true, true, false,
    false, false, 'portezuelo del rosal portezuelo del rosal argentina ar',
    NOW(), NOW());